### ISSUE TITLE
[SYCL] linking sycl gives missing __cpu_model

### ISSUE THREAD

**Issue by airlied** [intel/llvm#10]
On Fedora 28 + gcc 8.2.1

CMakeFiles/sycl.dir/source/detail/device_info.cpp.o: In function `cl::sycl::detail::get_native_vector_width(unsigned long)':
device_info.cpp:(.text._ZN2cl4sycl6detail23get_native_vector_widthEm+0x3): undefined reference to `__cpu_model'

I can fix this by manually adding -lgcc to the end of the c++ linker line, but that probably means something has gone wrong elsewhere, just mentioning here in case anyone else hits it.

**Comment by bader** [comment]
Hi Dave, thanks for reporting this issue. We have seen the sample problem with Ubuntu and implemented a workaround in CMake files here: https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L102
I think we should look at this problem more carefully and implement a more robust solution.

**Comment by kusma** [comment]
I'm seeing the same problem as well on Fedora 29 + gcc 8.2.1.

**Comment by keryell** [comment]
It works out of the box on Ubuntu 18.10 & g++ 8.2.0 at least...

**Comment by airlied** [comment]
There's probably no harm in expanding the workaround to always just link -lgcc on gcc.
