### ISSUE TITLE
[SYCL] Remove aspect-ext_oneapi_bfloat16_math_functions

### ISSUE THREAD

**Issue by JackAKirk** [intel/llvm#10010]
It doesn't look like `aspect-ext_oneapi_bfloat16_math_functions` has any purpose at all since all bfloat16 math functions now have generic implementations. I think we can probably remove it and then set this test to run generically:

https://github.com/intel/llvm/blob/453ffdcf41dd50ec66b5cc9ea6304fadd10f18e8/sycl/test-e2e/BFloat16/bfloat16_builtins.cpp#L1

@jinge90 do you think this makes sense?

**Comment by steffenlarsen** [comment]
Ping @jinge90 on the question above.

**Comment by jinge90** [comment]
Hi, @steffenlarsen and @JackAKirk 
Yes, for "non-cuda" targets, we just use generic fp32 math functions to implement these bf16 functions, they can run on any device.
Thanks very much.

**Comment by steffenlarsen** [comment]
https://github.com/intel/llvm/pull/13696 should address this.
