### ISSUE TITLE
no member named 'cl_uint' in namespace 'sycl::opencl'

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#10021]
info.cpp:358:59: error: no member named 'cl_uint' in namespace 'sycl::opencl'
  print_info<info::device::reference_count, sycl::opencl::cl_uint>(

path: [sycl/test-e2e/info.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Basic/info.cpp)
command: icpx info.cpp -fsycl

**Comment by AlexeySachkov** [comment]
Hi @jinz2014, 

Could you please specify which version of `icpx` you are running? (`icpx --version`)

Most likely, that is some older release, which doesn't yet have `sycl::opencl::cl_*` types support. Those type aliases were added in #7931. They missed 2023.1 oneAPI release, but should be available in 2023.2 oneAPI release.
