### ISSUE TITLE
same device ip values

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#10184]
I have a question. Where is the deviceIp (e.g. 0x03008000) defined ?  The values are the same for the two architectures.

```
std::map<uint32_t, oneapi_exp_arch> MapDeviceIpToArch = {

          {0x03008000, oneapi_exp_arch::intel_gpu_adl_s},
          {0x03008000, oneapi_exp_arch::intel_gpu_rpl_s},

```

**Comment by AlexeySachkov** [comment]
Hi @jinz2014,

Tagging @dm-vodopyanov here to help answering the question. Brief search suggests that we may not have a public documentation listing those values, but looking into internal documentation, it seems valid that those two entries have the same value.

**Comment by jinz2014** [comment]
Thanks

**Comment by dm-vodopyanov** [comment]
Thanks @jinz2014, I re-opened it because it should be addressed.
