### ISSUE TITLE
Add `sycl-optlevel` attribute to device functions

### ISSUE THREAD

**Issue by victor-eds** [intel/llvm#10197]
**Describe the bug**

According to [PropagateCompilerFlagsToRuntime.md](https://github.com/intel/llvm/blob/bb96f8589c40ce468ddb9495ce0a09d3026eb933/sycl/doc/design/PropagateCompilerFlagsToRuntime.md), each function in the device module should be added a `sycl-optlevel` attribute hosting a value set to the optimization level used to compile the module. Do so in `cgeist`.

**To Reproduce**

Run `PropagateOptionsToBackend/sycl-opt-level-level-zero.cpp` test. It will fail as L0 will be missing that attribute in the device functions.

**Environment (please complete the following information):**

- Target device and vendor: Intel GPU
- DPC++ version: 3c6c15693651f1d9aa4b71191d8c916ff30083ee

**Comment by asudarsa** [comment]
Please feel free to add me to the review process if/when you try to add this attribute.

Thanks

**Comment by victor-eds** [comment]
> Please feel free to add me to the review process if/when you try to add this attribute.

Thanks a lot, @asudarsa. Will do

**Comment by victor-eds** [comment]
Fix: https://github.com/intel/llvm/pull/10630
Test: https://github.com/intel/llvm/pull/11304
