### ISSUE TITLE
Latest Khronos SYCL CTS build is broken

### ISSUE THREAD

**Issue by bader** [intel/llvm#1023]
https://github.com/KhronosGroup/SYCL-CTS/pull/35 updated accessor test.
Corresponding spec change is here: https://github.com/KhronosGroup/SYCL-Docs/pull/31.

**Comment by garimagu** [comment]
The change in the SYCL doc essentially done the following functional changes to accessors:
Image Accessors: Removed get_size() method, and added get_range() method.
Local Accessors: Added get_range() method. 
Creating a PR for this change.

**Comment by garimagu** [comment]
https://github.com/intel/llvm/pull/1050
