### ISSUE TITLE
ESIMD operator_assignment_glb_mask test failed in post-commit.

### ISSUE THREAD

**Issue by bader** [intel/llvm#10293]
**Describe the bug**
Post-commit check has failed for https://github.com/intel/llvm/commit/7f12b287236fa9cfbe5042321b0ab5ad701a907d on Windows:

```
FAIL: SYCL :: ESIMD/api/functional/operators/operator_assignment_glb_mask.cpp (437 of 1440)
******************** TEST 'SYCL :: ESIMD/api/functional/operators/operator_assignment_glb_mask.cpp' FAILED ********************
Script:
--
: 'RUN: at line 8';    D:/github/_work/llvm/llvm/install/bin/clang++.exe   -fsycl -fsycl-targets=spir64 D:\github\_work\llvm\llvm\llvm\sycl\test-e2e\ESIMD\api\functional\operators\operator_assignment_glb_mask.cpp -o D:\github\_work\llvm\llvm\build-e2e\ESIMD\api\functional\operators\Output\operator_assignment_glb_mask.cpp.tmp.out
: 'RUN: at line 9';   env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu  D:\github\_work\llvm\llvm\build-e2e\ESIMD\api\functional\operators\Output\operator_assignment_glb_mask.cpp.tmp.out
--
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 8"
$ "D:/github/_work/llvm/llvm/install/bin/clang++.exe" "-fsycl" "-fsycl-targets=spir64" "D:\github\_work\llvm\llvm\llvm\sycl\test-e2e\ESIMD\api\functional\operators\operator_assignment_glb_mask.cpp" "-o" "D:\github\_work\llvm\llvm\build-e2e\ESIMD\api\functional\operators\Output\operator_assignment_glb_mask.cpp.tmp.out"
$ ":" "RUN: at line 9"
$ "env" "ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu" "D:\github\_work\llvm\llvm\build-e2e\ESIMD\api\functional\operators\Output\operator_assignment_glb_mask.cpp.tmp.out"
# command output:
Running on Intel(R) Iris(R) Xe Graphics
SYCL exception caught: Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)

error: command failed with exit status: 1

--
```

`PI_ERROR_DEVICE_NOT_AVAILABLE` error code is quite surprising as one of 747 tests failed:
```
Failed Tests (1):
  SYCL :: ESIMD/api/functional/operators/operator_assignment_glb_mask.cpp


Testing Time: 1759.05s
  Unsupported      : 680
  Passed           : 746
  Expectedly Failed:  13
  Failed           :   1
```

I think the system is configured correctly and bug is either in GPU driver or DPC++. Unfortunately, there is no stable reproducer as the issue seems to be flaky.

Full log - https://github.com/intel/llvm/actions/runs/5512643476/jobs/10050470704
Archived version - [logs_91096.zip](https://github.com/intel/llvm/files/12009011/logs_91096.zip)

**Environment (please complete the following information):**

- OS: Windows
- Target device and vendor: Intel GPU
- DPC++ version: 7f12b287236fa9cfbe5042321b0ab5ad701a907d 
- Dependencies version:
  - Unfortunately, post-commit script does run sycl-ls, so I don't know the driver version, but I assume it matches the version from https://github.com/intel/llvm/blob/sycl/devops/dependencies.json#L52. I.e. igfx_win_101.1191.

**Additional context**
Note sure if it's relevant, but "Set env" step has following output: 

```
error: could not lock config file C:/Program Files/Git/etc/gitconfig: Permission denied
```
"Set env" step status is "success". @aelovikov-intel, do you think this is a bug in Windows CI script?

**Comment by aelovikov-intel** [comment]
I haven't had much experience with our Windows CI setup. Maybe @cperkinsintel knows more?

**Comment by sarnex** [comment]
No reports of this since 2023, test is enabled and passed for me 5 times consistently on the failing hardware/OS with a manual run and the shader cache disabled. Closing for now.
