### ISSUE TITLE
[SYCL][HIP] clangrt builtins lib not found

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#10612]
I encountered the following error when building the oneMKL interface with the SYCL compiler.  Thanks for your instructions.

/opt/rocm/hip/lib/cmake/hip/hip-config.cmake:331 (message):
clangrt builtins lib not found

Reference
https://github.com/oneapi-src/oneMKL/issues/336

**Comment by JackAKirk** [comment]
compiler-rt is not built by default. Here are steps to build it: https://github.com/oneapi-src/oneMKL/issues/336#issuecomment-1664069060

**Comment by bader** [comment]
@JackAKirk, why is this library required for oneMKL?

**Comment by bader** [comment]
```
/opt/rocm/hip/lib/cmake/hip/hip-config.cmake:331 (message):
clangrt builtins lib not found
```
It seems like it's needed for rocm, not DPC++.
