### ISSUE TITLE
Link time warning: expects `'nvptx64-nvidia-cuda-sm_50-` but finds  `nvptx64-nvidia-cuda--sm_50-`

### ISSUE THREAD

**Issue by densamoilov** [intel/llvm#10621]
When building [oneDNN](https://github.com/oneapi-src/oneDNN) with NVIDIA backend using nightly-20230714 compiler I get the following link time warning when the oneDNN library is being created:
```bash
clang++: error: linked binaries do not contain expected 'nvptx64-nvidia-cuda-sm_50-' target; found targets: 'spir64-unknown-unknown--, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-, nvptx64-nvidia-cuda--sm_50-' [-Werror,-Wsycl-target]
```
The target `-fsycl-targets=nvptx64-nvidia-cuda` is specified when compiling the oneDNN source code, it is also specified when we link the object files to get the final oneDNN library.

The most suspicious thing to me is that the compiler expects `'nvptx64-nvidia-cuda-sm_50-` but it can only find `nvptx64-nvidia-cuda--sm_50-` so the difference is just a dash or something is missing between the dashes.

Do you have any ideas where the difference is coming from?

**Comment by bader** [comment]
@densamoilov, please, try nightly build nightly-20230729 (expected tomorrow). There were a couple of fixes in the driver, which can potentially help (e.g. https://github.com/intel/llvm/commit/0fd9a4eb17a2db0fed151ba9d975804322966bcc and https://github.com/intel/llvm/commit/12ca2db0e30b155c7d6bf14320dd1ba468ac9294).

**Comment by densamoilov** [comment]
@bader, do you happen to know what could cause the errors below?
```bash
In file included from include/sycl/backend.hpp:16:
include/sycl/feature_test.hpp:19:1: error: unknown type name '__SYCL_INLINE_VER_NAMESPACE'
__SYCL_INLINE_VER_NAMESPACE(_V1) {
^
include/sycl/feature_test.hpp:92:2: error: expected ';' after top level declarator
} // __SYCL_INLINE_VER_NAMESPACE(_V1)
 ^
 ;
2 errors generated.
```

**Comment by bader** [comment]
Yes. Please, remove include/sycl/version.hpp and include/sycl/feature_test.hpp from your /sycl/ directory.
See https://github.com/intel/llvm/pull/10339#issuecomment-1633335878.

**Comment by densamoilov** [comment]
@bader, thanks! The issue is gone in the recommended compiler version.

**Comment by bader** [comment]
> The issue is gone in the recommended compiler version.

Great! Please, close the issue.
