### ISSUE TITLE
Unexpected llvm intrinsic:  `llvm.fptosi.sat.i8.f64`

### ISSUE THREAD

**Issue by fwyzard** [intel/llvm#10709]
**Describe the bug**

While building a SYCL application, clang/llvm aborts with an error about an unsupported intrinsic:
```
InvalidFunctionCall: Unexpected llvm intrinsic:
 llvm.fptosi.sat.i8.f64 [Src: /data/user/fwyzard/sycl/llvm/llvm-spirv/lib/SPIRV/SPIRVWriter.cpp:4544 false ]
```

**To Reproduce**
Please find attached a preprocessed file that reproduces the problem: [gpuVertexFinder.ii.gz](https://github.com/intel/llvm/files/12270181/gpuVertexFinder.ii.gz) .

The failure can be reproduced with
```bash
gunzip gpuVertexFinder.ii.gz
clang++ -std=c++17 -O2 -fPIC -pipe -g -fsycl gpuVertexFinder.ii -shared -o liboutput.so
```
using the latest nightly.

The nightly itself was built with
```bash
python3 llvm/buildbot/configure.py --cmake-opt=-DCMAKE_INSTALL_PREFIX=/data/user/fwyzard/sycl/install/sycl-nightly/20230805_160000 -o /data/user/fwyzard/sycl/build/sycl-nightly/20230805_160000 --cmake-gen 'Unix Makefiles' --cuda --cmake-opt=-DCUDA_TOOLKIT_ROOT_DIR=/cvmfs/patatrack.cern.ch/externals/x86_64/rhel8/nvidia/cuda-11.8.0 --hip --hip-platform AMD --cmake-opt=-DSYCL_BUILD_PI_HIP_ROCM_DIR=/cvmfs/patatrack.cern.ch/externals/x86_64/rhel8/amd/rocm-5.4.0 --enable-all-llvm-targets --disable-fusion --shared-libs -t Release
make -C /data/user/fwyzard/sycl/build/sycl-nightly/20230805_160000 -j 24 all sycl-toolchain install
```
from the commit 8e0cc4b7a845df9389a1313a3e680babc4d87782 corresponding to the tag [sycl-nightly/20230805_160000](https://github.com/intel/llvm/tree/sycl-nightly/20230805_160000) .

The full build log is attached: [build-sycl_nightly_20230805_160000.log.gz](https://github.com/intel/llvm/files/12270118/build-sycl_nightly_20230805_160000.log.gz) .

**Environment (please complete the following information):**

- OS: Linux, observed on Ubuntu 22.04 and on RHEL 8.7
- Target device and vendor: spir64, for JIT to Intel CPU and GPU
- DPC++ version: 8e0cc4b7a845df9389a1313a3e680babc4d87782
- Dependencies version: OpenCL CPU runtime 2023.15.3.0.20

**Additional context**
The program compiles and runs successfully using oneAPI 2023.2.0, and older versions of the open source SYCL compiler.

**Comment by fwyzard** [comment]
@AuroraPerego @igorvorobtsov FYI

**Comment by fwyzard** [comment]
@igorvorobtsov, I've attached a preprocessed file build in a different way:
  - standard includes are not included
  - local includes have been preprocessed
  - the Eigen header-only library is included alongside the single source file

It can be used like
```
tar xaf gpuVertexFinder.tgz
clang++ -std=c++17 -O2 -fPIC -fsycl  -Wno-deprecated-declarations -shared gpuVertexFinder.cc -o gpuVertexFinder.so
```
which fails with
```
InvalidFunctionCall: Unexpected llvm intrinsic:
 llvm.fptosi.sat.i8.f64 [Src: /data/user/fwyzard/sycl/llvm/llvm-spirv/lib/SPIRV/SPIRVWriter.cpp:4544 false ]
llvm-foreach: 
clang++: error: llvm-spirv command failed with exit code 8 (use -v to see invocation)
```

**Comment by fwyzard** [comment]
Sorry, looks like I forgot to attach the archive: 
[gpuVertexFinder.tar.gz](https://github.com/intel/llvm/files/12370969/gpuVertexFinder.tar.gz)

**Comment by igorvorobtsov** [comment]
Note that I don't see this problem with icpx nightly build (20230816)

**Comment by igorvorobtsov** [comment]
[test.zip](https://github.com/intel/llvm/files/12399476/test.zip)

**Comment by MrSidims** [comment]
@LU-JOHN has added translation of the intrinsic in the translator in
```
commit aab0dac9225808840f1c8dbed33ce8b20549ca6e
Author: LU-JOHN <111294400+LU-JOHN@users.noreply.github.com>
Date:   Mon Sep 18 11:14:34 2023 -0500

    Translate llvm.fpto[s|u]i.sat.* intrinsics (#2149)

    Signed-off-by: Lu, John <john.lu@intel.com>

```
@fwyzard @igorvorobtsov do you still observe that sort of issue or it can be closed?

**Comment by igorvorobtsov** [comment]
I am not able to reproduce this problem anymore, so, I believe it can be closed.
