### ISSUE TITLE
Clang memory consumption increase in "in-process" execution model

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#1085]
Clang tool executes cc1 commands in the same process after b4a99a0. It causes increasing memory consumption for compilations where several source files are passed (for C++ application) or several build steps (e.g. for SYCL application we have host, device and integration header step per source file). Memory is not freed for all cc1 commands until end of overall process.
Commit d357addeb91134e480e61303fc91294fb876adb5  forces clang driver use old behavior until memory issue is fixed

**Comment by bader** [comment]
@erichkeane filed a bug here https://bugs.llvm.org/show_bug.cgi?id=44823.
Proposed fix: https://reviews.llvm.org/D74447.

@vladimirlaz, could you check if the proposed fix helps, please?
If so, please, replace https://github.com/intel/llvm/commit/d357addeb91134e480e61303fc91294fb876adb5 with the proper fix.

**Comment by vladimirlaz** [comment]
revert of workaround in https://github.com/intel/llvm/pull/1391
