### ISSUE TITLE
sub_group_mask is not conforming to the extension

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#10896]
The problem really is that the current implementation neither conforms to version 1 nor 2, probably because the existence of the `private`
```
sub_group_mask(BitsType rhs, size_t bn)
```
avoids all other constructors being implicitly defined.

_Originally posted by @masterleinad in https://github.com/intel/llvm/issues/10886#issuecomment-1684236012_

**Comment by KornevNikita** [comment]
Implemented version 2 in https://github.com/intel/llvm/pull/11195
