### ISSUE TITLE
[UR][CPU] libpi_native_cpu.so missing

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#10910]
Q. What would be the right configuration to get the SYCL on CPU backend to be working with UR (ofcourse taking into considerations all the non-supported features/in-development for CPU). I see some warnings related to `libpi_native_cpu.so` missing when doing a standard build for either CUDA or HIP plugins.

SYCL_PI_TRACE[-1]: dlopen(/lustre/orion/gen243/scratch/abagusetty/llvm/build/install/lib/libpi_native_cpu.so) failed with </lustre/orion/gen243/scratch/abagusetty/llvm/build/install/lib/libpi_native_cpu.so: cannot open shared object file: No such file or directory>

**Comment by Alcpz** [comment]
To enable the `native_cpu` plugin, you have to add `--enable-plugin native_cpu` to the `buildbot/configure.py` script. 
Be aware however that NativeCPU is still in early development and it has very few functionalities implemented.

There is more information regarding NativeCPU at https://github.com/intel/llvm/blob/sycl/sycl/doc/design/SYCLNativeCPU.md
