### ISSUE TITLE
[SYCL-MLIR] Investigate constant-propagation.mlir failure with an assertion in `DenseAnalysis`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#10935]
The following assert in `mlir/lib/Analysis/DataFlow/DenseAnalysis.cpp` causes `mlir-sycl/test/Transforms/constant-propagation.mlir` to fail. It is temporarily commented out in https://github.com/intel/llvm/pull/10895. This issue should add the assert back after investigation.
```
      // assert(op == branch || toBlock->getParent() != op->getBlock()->getParent());
```

**Comment by victor-eds** [comment]
After local testing: https://github.com/llvm/llvm-project/commit/5d8813dec69360fce897f063a4a65106ae8ea22b introduced this bug, fixed by https://github.com/llvm/llvm-project/commit/10ae8ae8375d6b69064204338a33500917749da9. You can cherry-pick the latter into your `merge` branch.

**Comment by victor-eds** [comment]
#11153 should fix this. PR accepted upstream already
