### ISSUE TITLE
choose cpu_selector to queue or device throw an instance of 'sycl::_V1::runtime_error'

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#11021]
**Describe the bug**
SYCL cannot choose cpu_selector to execute throw an instance of 'sycl::_V1::runtime_error'

**To Reproduce**

This is the code
```

#include <sycl/sycl.hpp>
#include <iostream>
#include <vector>
using namespace sycl;

int main(){
    std::cout<<"hello sycl"<<std::endl;
    const int N = 4;
    const int MAGIC_NUM = 42;
    std::vector<int> vec_num = {3,4,5,6,7,8,9};
    std::cout<<vec_num[0]<<std::endl;

    queue q;
    // queue q{ sycl::default_selector {} };
    // queue q{ sycl::gpu_selector {}};
    // auto dev = q.get_device();
    sycl::device dev {sycl::cpu_selector_v};
    std::cout<<"default queue select device info : "<<&dev<<std::endl;
    std::cout<<"default queue select device vendor id : "<<dev.get_info<sycl::info::device::vendor_id>()<<std::endl;
    std::cout<<"default queue select device vendor name : "<<dev.get_info<sycl::info::device::name>()<<std::endl;
    auto devices = dev.get_devices();
    for (auto &device : devices) {
            std::cout << "  queue get device: " << device.get_info<sycl::info::device::name>() << std::endl;
            std::cout << "  queue get device vendor id: " << device.get_info<sycl::info::device::vendor_id>()<< std::endl;
            std::cout << "  queue get device max compute units : " << device.get_info<info::device::max_compute_units>()<< std::endl;
            std::cout << "  queue get device global mem size: " << (device.get_info<info::device::global_mem_size>()/(1024*1024*1024))<< " GB "<< std::endl;
            std::cout << "  queue get device global mem cache size: " <<(device.get_info<info::device::global_mem_cache_size>()/(1024*1024))<<" MB "<< std::endl;
            std::cout << "  queue get device max mem alloc size: " << (device.get_info<info::device::max_mem_alloc_size>()/(1024*1024*1024))<< " GB "<< std::endl;
            std::cout << "  queue get device object address : " << &device << std::endl;                    
    }

    return 0;
}

```

**Environment (please complete the following information):**

- OS: Linux [Ubuntu 18.04]
- Target device and vendor: Nvidia GPU
- DPC++ version: clang-16
- Dependencies version: cuda-11.2

**Additional context**

**Comment by bader** [comment]
> SYCL cannot choose cpu_selector to execute throw an instance of 'sycl::_V1::runtime_error'

A few questions:
- What does exception message say?
- Do you have OpenCL CPU device?
- What is the output of `sycl-ls` tool?

**Comment by wangzy0327** [comment]
The message say.
```
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  No device of requested type 'info::device_type::cpu' available. -1 (PI_ERROR_DEVICE_NOT_FOUND)
```
I have Nvidia GPU device
sycl-ls
```
[ext_oneapi_cuda:gpu:0] NVIDIA CUDA BACKEND, Tesla V100-PCIE-32GB 0.0 [CUDA 11.2]
[ext_oneapi_cuda:gpu:1] NVIDIA CUDA BACKEND, Tesla V100-PCIE-32GB 0.0 [CUDA 11.2]
```

**Comment by bader** [comment]
This is expected behavior. There is no CPU device to select. You can configure OpenCL CPU to make you code to work with `cpu_selector`.

**Comment by wangzy0327** [comment]
How to configure OpenCL CPU in SYCL Nvidia device?

**Comment by bader** [comment]
> How to configure OpenCL CPU in SYCL Nvidia device?

I'm not sure I follow you here. Do mean NVIDIA CPU or GPU device? If your intention is to use NVIDIA GPU device, you should use `gpu_selector`.

**Comment by wangzy0327** [comment]
> > How to configure OpenCL CPU in SYCL Nvidia device?
> 
> I'm not sure I follow you here. Do mean NVIDIA CPU or GPU device? If your intention is to use NVIDIA GPU device, you should use `gpu_selector`.

I means the NVIDIA GPU device. If I use `gpu_selector` with Nvidia GPU in SYCL platform，how can I use CPU in same programming SYCL interface to verify the Nvidia GPU compute result. The programming paradigm I am referring to is like this.
```
queue q {sycl::gpu_selector_v};
q.submit([&](sycl::handler &cgh){
    cgh.parallel_for<>();
}

```

**Comment by bader** [comment]
Get started guide provides installation instructions for OpenCL CPU. https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime

You should be able to execute SYCL kernel code on CPU device (assuming that you CPU architecture is x86 based).

**Comment by wangzy0327** [comment]
OK，Thank you for reply.

**Comment by maarquitos14** [comment]
@wangzy0327 I'm closing this issue as it seems you were able to resolve your problem. Feel free to reopen otherwise.
