### ISSUE TITLE
Compilation error while trying to build LLVM

### ISSUE THREAD

**Issue by eyalsason** [intel/llvm#11138]
https://github.com/intel/llvm/blame/68dc47d93cf2535db8f7c9f718e0de94eaa124ca/llvm/lib/Target/ARM/ARMFastISel.cpp#L2183

Compilation error in file ARMFastISel.cpp:2967:
error: ‘getInt32PtrTy’ is not a member of ‘llvm::Type’

 $ cmake --build .
[  0%] Built target LLVMDemangle
[  0%] Built target LLVMSupportBlake3
[  4%] Built target LLVMSupport
[  4%] Built target LLVMTableGen
[  4%] Built target obj.LLVMTableGenCommon
[  4%] Built target LLVMTableGenCommon
[  4%] Built target llvm-min-tblgen
[  4%] Built target vt_gen
[  4%] Built target LLVMCodeGenTypes
[  4%] Built target LLVMTableGenGlobalISel
[  4%] Built target intrinsics_gen
[  6%] Built target llvm-tblgen
[  6%] Built target llvm_vcsrevision_h
[  6%] Built target RISCVTargetParserTableGen
[  7%] Built target LLVMTargetParser
[  7%] Built target LLVMBinaryFormat
[  7%] Built target LLVMBitstreamReader
[  7%] Built target LLVMRemarks
[ 10%] Built target LLVMCore
[ 10%] Built target LLVMFuzzerCLI
[ 10%] Built target LLVMTextAPI
[ 10%] Built target LLVMBitReader
[ 10%] Built target LLVMAsmParser
[ 10%] Built target LLVMIRReader
[ 12%] Built target LLVMDebugInfoCodeView
[ 13%] Built target LLVMMC
[ 13%] Built target LLVMMCParser
[ 15%] Built target LLVMObject
[ 16%] Built target LLVMDebugInfoDWARF
[ 16%] Built target LLVMDebugInfoMSF
[ 20%] Built target LLVMDebugInfoPDB
[ 20%] Built target LLVMDebugInfoBTF
[ 20%] Built target LLVMSymbolize
[ 20%] Built target LLVMProfileData
[ 23%] Built target LLVMAnalysis
[ 23%] Built target LLVMBitWriter
[ 26%] Built target LLVMTransformUtils
[ 26%] Built target LLVMAggressiveInstCombine
[ 26%] Built target LLVMInstCombine
[ 27%] Built target LLVMScalarOpts
[ 27%] Built target LLVMFuzzMutate
[ 29%] Built target LLVMFileCheck
[ 29%] Built target LLVMInterfaceStub
[ 29%] Built target LLVMIRPrinter
[ 29%] Built target LLVMObjCARCOpts
[ 29%] Built target LLVMTarget
[ 35%] Built target LLVMCodeGen
[ 36%] Built target LLVMSelectionDAG
[ 38%] Built target LLVMAsmPrinter
[ 38%] Built target LLVMMIRParser
[ 40%] Built target LLVMGlobalISel
[ 40%] Built target LLVMDWARFLinker
[ 40%] Built target LLVMDWARFLinkerParallel
[ 40%] Built target LLVMExtensions
[ 40%] Built target LLVMFrontendHLSL
[ 40%] Built target acc_gen
[ 40%] Built target LLVMFrontendOpenACC
[ 40%] Built target omp_gen
[ 40%] Built target LLVMFrontendOpenMP
[ 41%] Built target LLVMInstrumentation
[ 41%] Built target LLVMVectorize
[ 41%] Built target LLVMLinker
[ 43%] Built target LLVMipo
[ 43%] Built target LLVMHello_exports
[ 43%] Built target LLVMHello
[ 43%] Built target LLVMCoroutines
[ 43%] Built target LLVMCFGuard
[ 43%] Built target DeviceConfigFile
[ 43%] Built target GenXIntrinsicDescriptionGen
[ 43%] Built target GenXIntrinsicsGen
[ 43%] Built target LLVMGenXIntrinsics
[ 44%] Built target LLVMSYCLLowerIR
[ 44%] Built target LLVMPasses
[ 44%] Built target LLVMLTO
[ 44%] Built target LLVMMCDisassembler
[ 46%] Built target LLVMMCA
[ 46%] Built target LLVMObjCopy
[ 46%] Built target LLVMObjectYAML
[ 46%] Built target LLVMOption
[ 46%] Built target LLVMDebuginfod
[ 46%] Built target LLVMDebugInfoGSYM
[ 46%] Built target LLVMDebugInfoLogicalView
[ 46%] Built target LLVMDWP
[ 46%] Built target LLVMOrcShared
[ 47%] Built target LLVMOrcTargetProcess
[ 47%] Built target LLVMRuntimeDyld
[ 47%] Built target LLVMExecutionEngine
[ 47%] Built target LLVMInterpreter
[ 47%] Built target JITLinkTableGen
[ 49%] Built target LLVMJITLink
[ 49%] Built target LLVMMCJIT
[ 50%] Built target LLVMWindowsDriver
[ 52%] Built target LLVMOrcJIT
[ 52%] Built target AArch64CommonTableGen
[ 52%] Built target LLVMAArch64Info
[ 52%] Built target LLVMAArch64Utils
[ 52%] Built target LLVMAArch64Desc
[ 53%] Built target LLVMAArch64CodeGen
[ 53%] Built target LLVMAArch64AsmParser
[ 53%] Built target LLVMAArch64Disassembler
[ 53%] Built target AMDGPUCommonTableGen
[ 53%] Built target InstCombineTableGen
[ 53%] Built target LLVMAMDGPUInfo
[ 53%] Built target LLVMAMDGPUUtils
[ 53%] Built target LLVMAMDGPUDesc
[ 58%] Built target LLVMAMDGPUCodeGen
[ 58%] Built target LLVMAMDGPUAsmParser
[ 58%] Built target LLVMAMDGPUDisassembler
[ 58%] Built target LLVMAMDGPUTargetMCA
[ 58%] Built target ARMCommonTableGen
[ 58%] Built target LLVMARMInfo
[ 60%] Built target LLVMARMUtils
[ 60%] Built target LLVMARMDesc
[ 60%] Building CXX object lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/ARMFastISel.cpp.o
/home/esason/falcon_shores/NEO/llvm/llvm/lib/Target/ARM/ARMFastISel.cpp: In member function ‘unsigned int {anonymous}::ARMFastISel::getLibcallReg(const llvm::Twine&)’:
/home/esason/falcon_shores/NEO/llvm/llvm/lib/Target/ARM/ARMFastISel.cpp:2183:22: error: ‘getInt32PtrTy’ is not a member of ‘llvm::Type’
 2183 |   Type *GVTy = Type::getInt32PtrTy(*Context, /*AS=*/0);
      |                      ^~~~~~~~~~~~~
/home/esason/falcon_shores/NEO/llvm/llvm/lib/Target/ARM/ARMFastISel.cpp: In member function ‘unsigned int {anonymous}::ARMFastISel::ARMLowerPICELF(const llvm::GlobalValue*, llvm::MVT)’:
/home/esason/falcon_shores/NEO/llvm/llvm/lib/Target/ARM/ARMFastISel.cpp:2967:50: error: ‘getInt32PtrTy’ is not a member of ‘llvm::Type’
 2967 |       MF->getDataLayout().getPrefTypeAlign(Type::getInt32PtrTy(*Context));
      |                                                  ^~~~~~~~~~~~~
make[2]: *** [lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/build.make:230: lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/ARMFastISel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:19692: lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
 $

**Comment by maksimsab** [comment]
Hi @eyalsason 
Is it still an issue?

**Comment by maksimsab** [comment]
I close it as stale
