### ISSUE TITLE
runtime error when running Cuda backend for SYCL - returns CL_INVALID_VALUE -30 error

### ISSUE THREAD

**Issue by varsha-madananth** [intel/llvm#1119]
I built sycl toolchain with support for nvidia cuda.  The app builds find on -fsycl-targets=nvptx64-nvidia-cuda-sycldevice.  I get the following error when i run the exe. I have attached the compile commands and also gdb output.  Any help debugging would be appreciated. 

clinfo -l
Platform #0: Intel(R) FPGA Emulation Platform for OpenCL(TM)
 `-- Device #0: Intel(R) FPGA Emulation Device
Platform #1: Intel(R) OpenCL
 `-- Device #0: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Platform #2: NVIDIA CUDA
 `-- Device #0: GeForce GTX 1080

[simplesyclapplogs.txt](https://github.com/intel/llvm/files/4189259/simplesyclapplogs.txt)

Thanks,
Varsha

**Comment by bader** [comment]
@varsha-madananth, according to the log, your application used OpenCL back-end, which seems unintentional.
I suggest checking if `SYCL_BE` environment variable is set like this `SYCL_BE=PI_CUDA`.
Also it would be great if queue is created with device selector argument to make sure that application is using correct device.
More information how to build/run SYCL applications using CUDA back-end you can find here: https://github.com/codeplaysoftware/sycl-for-cuda/blob/cuda/sycl/doc/GetStartedWithSYCLCompiler.md.
Tagging @Ruyk, who can correct me if I got it wrong.

**Comment by varsha-madananth** [comment]
@bader : I have followed the instructions from https://github.com/codeplaysoftware/sycl-for-cuda/blob/cuda/sycl/doc/GetStartedWithSYCLCompiler.md.
Currently, the executable does not work with SYCL_BE=PI_CUDA not set as per the documentation.
If i do not set the variable, i get the following. 

Build program log for 'GeForce GTX 1080':
<kernel>:1:2: error: source file is not valid UTF-8
P<ED>U<BA><U+0001>
 ^
<kernel>:1:1: error: unknown type name 'P'
P<ED>U<BA><U+0001>
^
<kernel>:1:4: error: source file is not valid UTF-8
P<ED>U<BA><U+0001>
      ^
<kernel>:1:3: error: variable has address space that is not supported in program scope declaration
P<ED>U<BA><U+0001>
     ^
<kernel>:1:4: error: expected ';' after top level declarator
P<ED>U<BA><U+0001>
      ^
      ;
 0 (CL_SUCCESS)

However, there has been changes to the codebase yesterday which gives build errors while doing a make on sycl-for-cuda. I probably will have to open another issue for that. I will keep you posted. 

Thanks,
Varsha

**Comment by Ruyk** [comment]
There is an issue on the default device selection introduced by the latest PI plugin changes. Basically, SYCL_BE is ignored when using default selection, and can return an opencl device when there is no SPIRV binary or viceversa. We are working on a fix for that on the cuda-dev branch. This also affects a number of LIT tests, in case you see failures there.

**Comment by Ruyk** [comment]
The CUDA backend has been merged, this  problem should be solved now. Could you try again and let us know?

**Comment by jinz2014** [comment]
I also got the same error. Could you also suggest debugging methods ?

**Comment by Ruyk** [comment]
https://github.com/intel/llvm/pull/1293

**Comment by bader** [comment]
@varsha-madananth, does #1293 with clarified instructions fix your problem?

**Comment by jinz2014** [comment]
Yes. Thanks for improving the guide.

**Comment by bader** [comment]
@Ruyk, 👍.
