### ISSUE TITLE
Windows / SYCL E2E : failed Graph/submission_while_executing.cpp

### ISSUE THREAD

**Issue by smaslov-intel** [intel/llvm#11277]
In https://github.com/intel/llvm/pull/11262 a test fix resulted in another E2E test failure on Windows:
> Failed Tests (1):
  SYCL :: Graph/submission_while_executing.cpp

See https://github.com/intel/llvm/actions/runs/6268278788/job/17023099631?pr=11262

> $ "env" "ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu" "D:\github\_work\llvm\llvm\build-e2e\Graph\Output\submission_while_executing.cpp.tmp.out"
Assertion failed: ErrorCode == sycl::errc::invalid, file D:/github/_work/llvm/llvm/llvm/sycl/test-e2e/Graph/submission_while_executing.cpp, line 69

**Comment by EwanC** [comment]
Closing as fixed by https://github.com/intel/llvm/pull/11303
