### ISSUE TITLE
feature_test.hpp:  error: expected constructor, destructor, or type conversion before ‘(’ token

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#11287]
building from the source produces the following errors:

include/sycl/feature_test.hpp:19:28: error: expected constructor, destructor, or type conversion before ‘(’ token
   19 | __SYCL_INLINE_VER_NAMESPACE(_V1) {

**Comment by AlexeySachkov** [comment]
Hi @jinz2014, the macro was completely removed from the codebase in #10510. If I'm not mistaken, `feature_test.hpp` is a file which is auto-generated from sources and put into build directory - if it was not re-generated by some reason then you will see an error like this.

I would suggest the following steps:
- if you updated your local copy of source code, make sure that there were no conflicts and that update was clean
- do a clean build, i.e. remove `build` directory

**Comment by jinz2014** [comment]
Thank you.
