### ISSUE TITLE
ordered_queue is not derived from sycl::queue

### ISSUE THREAD

**Issue by kevin-harms** [intel/llvm#1130]
https://github.com/intel/llvm/blob/dd329d61fa427edb28cad917c08aa040814289f4/sycl/doc/extensions/OrderedQueue/ordered_queue.h#L2

Given the definition of sycl::ordered_queue, it can not be passed as a parameter to functions or methods that take a sycl::queue because it is not derived from sycl::queue. This limits the usefulness of sycl::ordered_queue. (Or all existing code needs to be updated to accept both types).

**Comment by jbrodman** [comment]
Hi,

Based on feedback, we decided to deprecate ordered_queue in favor of: https://github.com/intel/llvm/pull/1035

Now there is only just the queue class.  The 'ordered'ness is determined by a property of the queue and can be queried by the programmer.

**Comment by bader** [comment]
@jbrodman, I think we need to update the extension documentation.

**Comment by jbrodman** [comment]
@bader, we did: https://github.com/intel/llvm/pull/1042
:)

**Comment by bader** [comment]
I mean make it obvious that first version is deprecated. It's done in the source code only. 
If someone reads only documentation there are two legit versions of the proposal.
:)

**Comment by jbrodman** [comment]
Aha.

Done: https://github.com/intel/llvm/pull/1131

**Comment by bader** [comment]
Fixed by #1035, #1042 and #1131.

**Comment by bader** [comment]
@kevin-harms, let us know if you have any other issues with using ordered queues.
