### ISSUE TITLE
Failure in SYCL Pre Commit on Linux / test on AMD/HIP

### ISSUE THREAD

**Issue by dkhaldi** [intel/llvm#11405]
Multiple PRs are getting this failure that does not seem to be triggered by the PR changes.
see https://github.com/intel/llvm/pull/11384, https://github.com/intel/llvm/pull/11393

Description of the failure:
Run sycl-ls --verbose
ur_die: failed hipMemGetInfo() API.
terminate called without an active exception
[ext_oneapi_hip:gpu:0] AMD HIP BACKEND, AMD Radeon RX 6[7](https://github.com/intel/llvm/actions/runs/6395275862/job/17359111386?pr=11393#step:17:8)00 XT gfx1031 [HIP 50731.[9](https://github.com/intel/llvm/actions/runs/6395275862/job/17359111386?pr=11393#step:17:10)2]

Platforms: 1
Platform [#1]:
    Version  : HIP 50731.92
    Name     : AMD HIP BACKEND
    Vendor   : AMD Corporation
    Devices  : 1
        Device [#0]:
        Type       : gpu
        Version    : gfx[10](https://github.com/intel/llvm/actions/runs/6395275862/job/17359111386?pr=11393#step:17:11)31
        Name       : AMD Radeon RX 6700 XT
        Vendor     : AMD Corporation
        Driver     : HIP 50731.92
Aborted (core dumped)
        Aspects    : gpu fp64 online_compiler online_linker queue_profiling usm_device_allocations usm_host_allocations ext_intel_pci_address usm_atomic_host_allocations atomic64 ext_intel_device_info_uuid ext_oneapi_native_assert
Error: Process completed with exit code [13](https://github.com/intel/llvm/actions/runs/6395275862/job/17359111386?pr=11393#step:17:14)4.

**Comment by againull** [comment]
Some AMD runners had old kernel mode driver. We updated KMD on those machines and now issue is resolved.
