### ISSUE TITLE
[PI] print information about plugins ?

### ISSUE THREAD

**Issue by fwyzard** [intel/llvm#1160]
Is there a way to print information about the plugin being used by each platform ?

And/or, if there a way to print information about the plugin(s) being loaded ?

**Comment by bader** [comment]
AFAIK, some information is logged if `SYCL_PI_TRACE` env. variable is set, but I'm not sure it includes information about plugins being used or loaded.
@romanovvlad or @smaslov-intel should be able to clarify this.

**Comment by romanovvlad** [comment]
I believe we have added some logging functionality, @againull could you please comment?

**Comment by againull** [comment]
Hi!
SYCL_PI_TRACE=1 ./test.exe
prints information about plugins being loaded and platform/device being selected.

SYCL_PI_TRACE=-1 enables all existing output from PI. 
You can see which plugins failed to load, scores for devices during device selection and PI calls.

**Comment by romanovvlad** [comment]
Closing as done.
