### ISSUE TITLE
[SYCL] `aligned_alloc_xxx<T>` returns non-null when the alignment argument is not a power of 2 

### ISSUE THREAD

**Issue by wangdi4** [intel/llvm#11642]
**Describe the bug**
USM allocation functions `aligned_alloc` templated on allocation type T returns non-null when the alignment argument is not a power of 2 (source ), which conflicts with the SYCL2020 specification [4.8.3 USM allocations](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_usm_allocations): _Some of the allocation functions take an explicit alignment parameter. Like std::aligned_alloc, these functions return nullptr if the alignment is not supported by the implementation._

**To Reproduce**
1. source code
    https://github.com/intel/llvm/blob/e75f21902a944c2776c43082d3f01843426a9525/sycl/test-e2e/USM/align.cpp
    This test checks that `aligned_alloc_xxx` and `aligned_alloc_xxx<T>` return nullptr when the alignment argument is not a power of 2

2. Specify the command which should be used to compile the program
   compile: `clang++   -fsycl -fsycl-targets=spir64 align.cpp -o align.cpp.tmp.out`
   run: `env ONEAPI_DEVICE_SELECTOR=opencl:cpu align.cpp.tmp.out`

3. Indicate what is wrong and what was expected
  CI [SYCL E2E test](https://github.com/intel/llvm/actions/runs/6626310291/job/17999293926?pr=10235) shows that the non-templated `aligned_alloc_xxx` cases return nullptr as expected, but the templated `aligned_alloc_xxx<T>` cases return non-null

**Environment (please complete the following information):**
- OS: Linux
- Target device and vendor: Intel CPU
- DPC++ version: clang version 18.0.0

**Additional context**

**Comment by HPS-1** [comment]
Fixed and merged in PR: https://github.com/intel/llvm/pull/12569
