### ISSUE TITLE
[CUDA] Upstream the SPIR-V translator changes into KhronosGroup/SPIRV-LLVM-Translator

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#1166]
#1091 changed some things in the translator, in particular 09b3b2e.
All these commits were squashed into 7a9a4251f57f78164df2eda4b17efc4c26b4356d

We might lose this changes while doing pulldowns from KhronosGroup/SPIRV-LLVM-Translator repo

**Comment by AlexeySachkov** [comment]
I've found a bug in this commit, which affects translation from SPIR-V to LLVM IR: some built-in SPIR-V variables translated not into OpenCL built-ins, but into something strange, like: `__spirv_BuiltInWorkgroupId` -> `__spirv_WorkgroupId_z` (not `get_group_id`).

Faulty code is additional lanes in the following mapping:

https://github.com/intel/llvm/blob/3b6799ab420db1ffc8d72c7941fed89f91abcb0f/llvm-spirv/lib/SPIRV/OCLUtil.h#L594-L644

This map is referenced as:

https://github.com/intel/llvm/blob/3b6799ab420db1ffc8d72c7941fed89f91abcb0f/llvm-spirv/lib/SPIRV/OCLUtil.h#L130-L131

And the only use of it is in `SPIRVReader`: built-in id is mapped back to unmangled OpenCL built-in:

https://github.com/intel/llvm/blob/3b6799ab420db1ffc8d72c7941fed89f91abcb0f/llvm-spirv/lib/SPIRV/SPIRVReader.cpp#L241-L254

I think it would be better to refactor the whole map, i.e. swap types of key and value.

@Alexander-Johnston, @Ruyk, please fix this bug during upstreaming to KhronosGroup/SPIRV-LLVM-Translator

**Comment by AlexeySachkov** [comment]
Unfortunately, my analysis wasn't quite correct: mentioned map is actually used to map from string to built-in id:

https://github.com/intel/llvm/blob/3b6799ab420db1ffc8d72c7941fed89f91abcb0f/llvm-spirv/lib/SPIRV/OCL20ToSPIRV.cpp#L1262-L1263

So, it seems that we cannot just remove additional lines with stuff like `add("__spirv_GlobalSize_x", BuiltInGlobalSize);` - we probably need two independent mappings here:

- LLVM IR -> SPIR-V: it will contain both OpenCL C built-ins as well as ones in form of SPIR-V friendly IR
- SPIR-V -> LLVM IR: it will contain only OpenCL C equivalents

**Comment by bader** [comment]
+@Naghasan

**Comment by AlexeySachkov** [comment]
Also, as quick workaround/hack we just need to modify the mapping:

https://github.com/intel/llvm/blob/3b6799ab420db1ffc8d72c7941fed89f91abcb0f/llvm-spirv/lib/SPIRV/OCLUtil.h#L610-L616

By some reason `__spirv_WorkgroupSize_*` are inserted twice: if we left only the first one bunch of them, then reverse mapping would only contain `BuiltInWorkgroupSize` -> `"get_local_size"`, which is fine for the consumption part. The same applies for `__spirv_WorkgroupId_*` which is also duplicated in this map

**Comment by Naghasan** [comment]
Oh yes, that's not really the intention here. I will make sure this doesn't happen for SPIR-V -> LLVM IR

**Comment by bader** [comment]
@AlexeySachkov, @Naghasan, is #1393 resolved this issue?

**Comment by Naghasan** [comment]
Yes, normally #1393 restored the llvm-spirv to upstream

**Comment by bader** [comment]
@AlexeySachkov, I'm closing this issue.
