### ISSUE TITLE
Distributing SYCL Applications with AdaptiveCpp (Windows)

### ISSUE THREAD

**Issue by blinkfrog** [intel/llvm#11712]
Hello,

I've been working on a SYCL-based application using AdaptiveCpp, and I've run into challenges when distributing the compiled application. While the app runs perfectly on my development machine, it fails to initialize the CUDA backend on other systems, unless they have a full AdaptiveCpp installation. This requirement is a significant barrier to entry for end-users.

Specifics:
I've compiled my app with --acpp-targets="cuda:sm_75"
The application works fine on my machine.
Distributing the app with only hipSYCL-rt.dll and cudart64_12.dll is insufficient.
Paths to the AdaptiveCpp folder appear to be hardcoded in hipSYCL-rt.dll. If I rename AdaptiveCPP folder then the app stops to work on my machine too.

Questions:
Is there a way to make AdaptiveCpp look for its backend DLLs in the application's folder, or specify the path programmatically?
Are there options for static linking?
Are there any best practices or recommended approaches for distributing AdaptiveCpp-dependent applications in a user-friendly manner?
I'd appreciate any guidance or advice on how to distribute an AdaptiveCpp-dependent application more easily. Thank you!

**Comment by bader** [comment]
@illuhad, can you transfer this issue to https://github.com/AdaptiveCpp/AdaptiveCpp?

**Comment by blinkfrog** [comment]
> @illuhad, can you transfer this issue to https://github.com/AdaptiveCpp/AdaptiveCpp?

I am sorry, I confused the tabs. I'll recreate the issue there.

**Comment by bader** [comment]
> > @illuhad, can you transfer this issue to https://github.com/AdaptiveCpp/AdaptiveCpp?
> 
> I am sorry, I confused the tabs. I'll recreate the issue there.

That works too. Thanks! I'm closing this one.
