### ISSUE TITLE
[AMDGPU] math E2E tests failed with 5db63d29fdc1fbf301c3d010d6e00e004d82fcdc

### ISSUE THREAD

**Issue by jsji** [intel/llvm#11857]
**Describe the bug**

The is found in pulldown CI
https://github.com/intel/llvm/actions/runs/6817150181/job/18544258845

Failed Tests (8):
  SYCL :: Basic/built-ins/marray_geometric.cpp
  SYCL :: Basic/built-ins/vec_common.cpp
  SYCL :: Basic/built-ins/vec_geometric.cpp
  SYCL :: Basic/built-ins/vec_math.cpp
  SYCL :: Basic/built-ins/vec_relational.cpp
  SYCL :: DeviceLib/built-ins/ext_native_math.cpp
  SYCL :: DeviceLib/built-ins/vector_relational.cpp
  SYCL :: DeviceLib/math_test_marray_vec.cpp

**NOTE: 5db63d29fdc1fbf301c3d010d6e00e004d82fcdc is reverted temporarily in pulldown https://github.com/intel/llvm/pull/11838 to avoid lit failures, we should reland it once the problem is fixed.**

**To Reproduce**

Merge 5db63d29fdc1fbf301c3d010d6e00e004d82fcdc, then build and test e2e on AMDGPU.

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: AMDGPU
- DPC++ version:  sycl + 5db63d29fdc1fbf301c3d010d6e00e004d82fcdc

**Comment by hdelan** [comment]
This has been fixed by this commit upstream: https://github.com/llvm/llvm-project/commit/28b505475

So adding this commit to pulldown should fix this problem.

**Comment by jsji** [comment]
Fixed.
