### ISSUE TITLE
Compilation for ARM target fails because there is still a non-opaque pointer API in use

### ISSUE THREAD

**Issue by keryell** [intel/llvm#11905]
**Describe the bug**

Compilation for ARM target fails because there is still a non-opaque pointer API in use.
```
/storage/rkeryell/SYCL/sycl-mlir/llvm/llvm/lib/Target/ARM/ARMFastISel.cpp:2183:22:
error: ‘getInt32PtrTy’ is not a member of ‘llvm::Type’
 2183 |   Type *GVTy = Type::getInt32PtrTy(*Context, /*AS=*/0);
      |                      ^~~~~~~~~~~~~
/storage/rkeryell/SYCL/sycl-mlir/llvm/llvm/lib/Target/ARM/ARMFastISel.cpp: In member function ‘unsigned int {anonymous}::ARMFastISel::ARMLowerPICELF(const llvm::GlobalValue*, llvm::MVT)’:
/storage/rkeryell/SYCL/sycl-mlir/llvm/llvm/lib/Target/ARM/ARMFastISel.cpp:2967:50: error: ‘getInt32PtrTy’ is not a member of ‘llvm::Type’
 2967 |       MF->getDataLayout().getPrefTypeAlign(Type::getInt32PtrTy(*Context));
      |                                                  ^~~~~~~~~~~~~
```

It looks like this is because the following commit is missing from upstream:
```
commit fd05c34b18fbc3f37494bef9118c368f0c11595a
Author: Bjorn Pettersson <...@ericsson.com>
Date:   Mon Jul 31 16:32:44 2023 +0200

    Stop using legacy helpers indicating typed pointer types. NFC
    
    Since we no longer support typed LLVM IR pointer types, the code can
    be simplified into for example using PointerType::get directly instead
    of using Type::getInt8PtrTy and Type::getInt32PtrTy etc.
    
    Differential Revision: https://reviews.llvm.org/D156733
```
It would be nice to check that most of the current commits are actually in the `sycl` branch.

**To Reproduce**

I am actually configuring and compiling the `sycl-mlir` branch with
` -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;ARM;AArch64"`
but the commit is also missing from the `sycl` branch.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- Target device and vendor: ARM
- DPC++ version: ff61613e225a from today.

**Comment by jsji** [comment]
yeah, ARM targets was never tested before.

**Comment by bader** [comment]
> yeah, ARM targets was never tested before.

The main problem is issue uncovers is that we have little control over which patches were merged and which were not. I think in general we keep all the patches, but some patches reverted due to "reasons" and there is no process to have them back. We rely on discipline of the folks who do the pulldown from llvm.org.

In this particular case, I think we reverted this patch while were preparing SYCL code base for opaque pointers infrastructure and some patches were not re-applied. Could you check that we don't other cases like this, please?

**Comment by jsji** [comment]
https://github.com/intel/llvm/pull/11906 to fix it.

**Comment by jsji** [comment]
> The main problem is issue uncovers is that we have little control over which patches were merged and which were not. I think in general we keep all the patches, but some patches reverted due to "reasons" and there is no process to have them back. We rely on discipline of the folks who do the pulldown from llvm.org.


Yes, there is NO documented process about reverts and fixes in LLVM-SPIRV-pulldown process. The general guideline is to create follow up issues for reverts and fixes. We can document the process,  but TBH, even with processes defined, we also rely on the discipline of folks to follow the process.

We will follow up to check any further missing commits.

**Comment by keryell** [comment]
Thanks for the reactivity!
