### ISSUE TITLE
#11517 introduces "Attempting to use a built-in kernel. They are not fully supported" errors in SYCL-CTS

### ISSUE THREAD

**Issue by hvdijk** [intel/llvm#11996]
**Describe the bug**
After #11517 was merged, several kernel bundle tests in the SYCL CTS started to fail. I am not managing to find an open bug for this, so I am opening one to make sure it does not get missed or forgotten.

**To Reproduce**
Build DPC++, no special options needed.
Build SYCL-CTS, no special options needed.
Run `bin/test_kernel_bundle`.

On DPC++ commit f4ed132f243ab43816ebe826669d978139964df2, this ends with:

```
test cases:  99 |  85 passed | 14 skipped
assertions: 254 | 254 passed |  0 skipped
```

On DPC++ commit 096676e8d4d87475860723ed8a4d8c256bcd98c2, this ends with:

```
test cases:  99 |  78 passed | 8 failed | 13 skipped
assertions: 262 | 254 passed | 8 failed |  0 skipped
```

The failures all look the same; taking `get_kernel_bundle_builtin_kernels` as an example, it shows:

```
Filters: "get_kernel_bundle_builtin_kernels"
Randomness seeded to: 793146351

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The SYCL 2020 Conformance Test Suite is a Catch2 v3.2.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
get_kernel_bundle_builtin_kernels
-------------------------------------------------------------------------------
/home/harald/SYCL-CTS/tests/kernel_bundle/../common/../../util/proxy.h:47
...............................................................................

/home/harald/SYCL-CTS/util/logger.cpp:41: 
warning:
  Run test for sycl::get_kernel_bundle<BundleState>(context) overload

/home/harald/SYCL-CTS/util/logger.cpp:41: 
warning:
  Run test for sycl::get_kernel_bundle<BundleState>(context, kernel_ids)
  overload

/home/harald/SYCL-CTS/util/sycl_exceptions.h:244: 
warning:
  SYCL exception
  with category name: 'sycl'
  with code: 'kernel_argument'
  with code raw value: '6'
  with code message: 'SYCL Error'
  with what: 'Attempting to use a built-in kernel. They are not fully
  supported'

/home/harald/SYCL-CTS/util/test_base.cpp:28: FAILED:
explicitly with message:
  a SYCL exception was caught: Attempting to use a built-in kernel. They are
  not fully supported

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

Tested with `intel-oneapi-runtime-opencl-2023.2.2-47`.

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Intel CPU
- DPC++ version: 096676e8d4d87475860723ed8a4d8c256bcd98c2
- Dependencies version: intel-oneapi-runtime-opencl-2023.2.2-47

**Additional context**

**Comment by AlexeySachkov** [comment]
Thanks for the report, @hvdijk!

Tagging @dm-vodopyanov who is looking into it already. Also tagging @cperkinsintel as the PR author for awareness
