### ISSUE TITLE
[SYCL] segfault in clCreateProgramWithIL with OpenCL 2.0

### ISSUE THREAD

**Issue by kusma** [intel/llvm#12]
My distro (Fedora 29) provides OpenCL with version reported as "OpenCL 2.0 beignet 1.3", which is incapable of using SPIR-V.

So when we unconditionally run clCreateProgramWithIL because we have a SPIR-V binary, we end up crashing with a SIGSEGV.

IMO, we should try to deal with this a bit more gracefully.

**Comment by bader** [comment]
Fixed by #11.
