### ISSUE TITLE
 The specified local size {0, 0, 0} doesn't match the required work-group size specified in the program source {1, 1, 256} -54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#12006]
The compiler (icx 2024.0) reports mismatch of work-group size for the following code snippets. 

The specified local size {0, 0, 0} doesn't match the required work-group size specified in the program source {1, 1, 256} -54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)

Do users need to specify the local size ?  Thanks.

```
class Add {
  public:
  Add(int *acc) : p(acc) {}
  [[sycl::reqd_work_group_size(256)]]
  void operator()(sycl::id<1> i) const {
    p[i]++;
  }

  private:
    int *p;
};

int main() {
 
   int *d_data = sycl::malloc_device<int>(1000000, q);

   q.submit([&](sycl::handler& h) {
      h.parallel_for(size, Add(d_data));
    }).wait();

}
```

**Comment by AlexeySachkov** [comment]
Hi @jinz2014,

> Do users need to specify the local size ? 

Yes, I think this is the case. From [Table 180|https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.kernel.attributes] of the SYCL 2020 specification:

> **`reqd_work_group_size(dim0)`**
> **`reqd_work_group_size(dim0, dim1)`**
> **`reqd_work_group_size(dim0, dim1, dim2)`**
>
> If the kernel is submitted to a device that does support the work-group size, **but the application provides an `nd_range` that does not match the size from the attribute, then the implementation must throw a synchronous `exception` with the `errc::nd_range` error code.**

This is not exactly explicit, but I think that it is implied by that "application provides an `nd_range` that does not match" part of the spec.

Corresponding SYCL-CTS were updated in KhronosGroup/SYCL-CTS#596 to match that behavior.

I know that both @Pennycook and @gmlueck agree that the attribute doesn't make sense for a "simple" form of `parallel_for` (one which accepts a `range` instead of `nd_range`), but I'm not aware of any PRs to make this restriction more explicit/verbose

**Comment by jinz2014** [comment]
For the "simple" form of "parallel_for" without "nd_range", I think the attribute makes sense (i.e. the execution of the program will not cause the runtime error and the work-group size is specified once"

**Comment by AlexeySachkov** [comment]
> For the "simple" form of "parallel_for" without "nd_range", I think the attribute makes sense (i.e. the execution of the program will not cause the runtime error and the work-group size is specified once"

If I understand correctly, "simple" form of `parallel_for` allows implementations don't use any work-groups at all and therefore no work-group sizes can be set for such `parallel_for` - even through an attribute.

**Comment by jinz2014** [comment]
When "range" is specified for "parallel_for", user should not add any attribute for the required work group size.

When "nd_range" is specified for "parallel_for", user may add an attribute for the required work group size.

Is that right ?

**Comment by AlexeySachkov** [comment]
> When "range" is specified for "parallel_for", user should not add any attribute for the required work group size.
> 
> When "nd_range" is specified for "parallel_for", user may add an attribute for the required work group size.
> 
> Is that right ?

That is my understanding, yes. Note that I'm not sure that you can omit local size from an `nd_range` and rely on the attribute to have it set. We have [`sycl_ext_oneapi_auto_local_range`](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_auto_local_range.asciidoc) that allows you to omit specifying local size, but I don't know how does it work in combination with the attribute. Tagging @0x12CC  as the implementor to consider that co-existence.
