### ISSUE TITLE
ONEAPI_DEVICE_SELECTOR and sycl-ls use different terminology

### ISSUE THREAD

**Issue by jamesreinders** [intel/llvm#12048]
**Describe the bug**
ONEAPI_DEVICE_SELECTOR and sycl-ls use different terminology

**To Reproduce**
Running sycl-ls will yield output such as:
sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2023.16.10.0.17_160000]
[opencl:cpu:1] Intel(R) OpenCL, 13th Gen Intel(R) Core(TM) i7-13700K OpenCL 3.0 (Build 0) [2023.16.10.0.17_160000]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics OpenCL 3.0 NEO  [23.22.26516.25]
[opencl:gpu:3] Intel(R) OpenCL Graphics, Intel(R) UHD Graphics 770 OpenCL 3.0 NEO  [23.22.26516.25]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.26516]
[ext_oneapi_level_zero:gpu:1] Intel(R) Level-Zero, Intel(R) UHD Graphics 770 1.3 [1.3.26516]

The information in the brackets is similar, but incompatible with ONEAPI_DEVICE_SELECTOR syntax.
Two examples:   
(1) "ext_oneapi_level_zero" is simply "level_zero" for ONEAPI_DEVICE_SELECTOR
(2) ":gpu:1" is either ":1" or ":gpu" for ONEAPI_DEVICE_SELECTOR, but not both (and yes - they aren't quite the same)

Proposal:   Please have a discussion between ONEAPI_DEVICE_SELECTOR support and sycl-ls - and figure out how to converge on a syntax for both printing and using that is the same.

This is very confusing as is - and will create more and more issues when trying to explain to any user (inside or outside Intel).

**Comment by AlexeySachkov** [comment]
FYI: (1) was recently discussed here: https://github.com/intel/llvm/pull/12007#discussion_r1405803885 and it is considered to be a bug in `sycl-ls`

**Comment by aelovikov-intel** [comment]
https://github.com/intel/llvm/pull/12368 addresses second issue.
