### ISSUE TITLE
Unused argument in GraphBuilder member function

### ISSUE THREAD

**Issue by alexbatashev** [intel/llvm#1208]
https://github.com/intel/llvm/commit/7a9a4251f57f78164df2eda4b17efc4c26b4356d introduced a new argument to `addHostAccessor` function which seems to be unused in this function. The same applies to `addHostAccessor` in Scheduler as well. These artifacts must be removed from code.

https://github.com/intel/llvm/blob/8d77a38bf178e906a9bd598fa5ea5bf4899eafc4/sycl/source/detail/scheduler/graph_builder.cpp#L340-L380

**Comment by Ruyk** [comment]
@Alexander-Johnston could this be an accident while re-basing?

**Comment by StuartDAdams** [comment]
Well spotted. I'll have a PR up to address this shortly.
