### ISSUE TITLE
 vec (+swizzle) and annotated_arg should define their binary operators as hidden friends

### ISSUE THREAD

**Issue by rolandschulz** [intel/llvm#12094]
Both vec (+swizzle) and annotated_arg don't define the their binary operators as hidden friends. For vec the spec is clear that it should be a hidden friend. For annotated_arg we should make this clear.

_Originally posted by @rolandschulz in https://github.com/intel/llvm/pull/11971#discussion_r1416679574_

**Comment by steffenlarsen** [comment]
These have been addressed:

- `vec`: https://github.com/intel/llvm/pull/12396
- Swizzles: https://github.com/intel/llvm/pull/13012
- `annotated_arg`: https://github.com/intel/llvm/pull/12232

@rolandschulz - I will close this. Please reopen if you believe we missed something.
