### ISSUE TITLE
[SYCL]Buffer size zero

### ISSUE THREAD

**Issue by mehdi-goli** [intel/llvm#123]
I have noticed that It is possible to create a buffer of size zero. e.g.
`
#include <CL/sycl.hpp>
int main(){
    auto buff = cl::sycl::buffer<float>(cl::sycl::range<1>(0));
    return 0;
}
`
What does buffer size zero mean?

**Comment by romanovvlad** [comment]
I believe you will get error/crash if you try to use such buffer. I think we need to throw error in c'tor in this case.

**Comment by keryell** [comment]
From a generic programming point-of-view, I do not see any issue about creating buffers with size 0.

**Comment by archibate** [comment]
Agree, if SYCL buffers could allow size zero, I can easily replace `std::vector<T>` by `sycl::buffer<T, 1>` in my code. For now I have to wrap the `sycl::buffer` around with my own `buffer` class by default initializing to `1`, and store the true size in `m_size`, along with other `std::vector`-alike methods like `resize` and `capacity`.
