### ISSUE TITLE
'sycl::_V1regregression with Crash on nd_range_error with OneAPi version 2023-WW46 

### ISSUE THREAD

**Issue by jcdatin** [intel/llvm#12363]
**Describe the bug**
convolution 1D (Y axis) that used to run fine with oneAPI core 2023-WW13 now crashes with 
'sycl::_V1::nd_range_error'
  what():  Non-uniform work-groups are not supported by the target device -54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)

**To Reproduce**
run the following function with following data 
workGroupSize: 1024
maxgroupSize: 1024
gws: 2048 788
lws: 1024 1

and 
1. Include code snippet as short as possible
int ConvolY( const cv::Mat& mask,
             const cv::Rect& bbox,
             const cv::Mat& projIn,
             const cv::Mat& filter,
             cv::Mat& projOut,
             sycl::queue* q )
{
    std::cout << "\nConvolY: "<<std::endl;
    uint32_t width = bbox.width;
    uint32_t height = bbox.height;

    const uint32_t kernelSize = filter.total();
    uint32_t workGroupSize = q->get_device().get_info<sycl::info::device::max_work_group_size>();
    workGroupSize = sycl::min<uint32_t>(workGroupSize, 1024);
    workGroupSize = sycl::max<uint32_t>(workGroupSize, kernelSize);
    const uint32_t localMemSize =  2*workGroupSize + 3*kernelSize;
    std::cout << "workGroupSize: "<< workGroupSize << std::endl;
    std::cout << "maxgroupSize: " << q->get_device().get_info<sycl::info::device::max_work_group_size>() << std::endl;
    
    uint32_t blockSize_x = 1;
    uint32_t blockSize_y = workGroupSize;
    sycl::range<2> gws (roundUP(height, blockSize_y), roundUP(width, blockSize_x));
    sycl::range<2> lws (blockSize_y, blockSize_x);
    std::cout << "gws: "<< gws[0] << " " << gws[1] << std::endl;
    std::cout << "lws: "<< lws[0] << " " << lws[1] << std::endl;

    q->submit([&] (sycl::handler &cgh) {

        auto pMask = mask.ptr<uint8_t>(0);
        auto pFilter = filter.ptr<float>(0);
        auto pProjIn = projIn.ptr<float>(0);
        auto pProjOut = projOut.ptr<float>(0);
        uint32_t x0 = bbox.x;
        uint32_t y0 = bbox.y;
        uint32_t gWidth = projIn.cols;
        uint32_t gHeight = projIn.rows;
        
        sycl::accessor<float, 1, sycl_read_write, sycl::access::target::local> sMem(localMemSize, cgh);

        cgh.parallel_for<class convolY>(sycl::nd_range<2>(gws, lws), [=] (sycl::nd_item<2> item) {

            uint32_t x = item.get_global_id(1);
            uint32_t y = item.get_global_id(0);
            uint32_t lid = item.get_local_id(0);
            uint32_t gid = (y + y0) * gWidth + (x + x0) ;
            uint32_t groupSize = item.get_local_range(0);
            auto projIn = sMem.get_pointer();
            auto mask = projIn + groupSize + kernelSize;
            auto filter = mask + groupSize + kernelSize;
            uint32_t halfSize = kernelSize/2;
            uint32_t oLid = lid + halfSize;

            float res = 0.0;
            bool validCoords = ( x < width && y < height );
            bool enabled = false;

            if (validCoords) {
                projIn[oLid] = pProjIn[gid];
                mask[oLid] = (pMask[gid] == ucSEIN);
                enabled = mask[oLid];

                if ( lid==0 ) {
                    for(int i=0; i<kernelSize; i++) { // copy filter
                        filter[i] = pFilter[i];
                    }

                    for(int i=0; i<halfSize; i++) {
                        int idx = (y + y0 - halfSize + i)*gWidth + x + x0;
                        int gy = y + y0 - halfSize + i;
                        projIn[i] = gy >= 0 ? pProjIn[idx] : 0;
                        mask[i] = gy >= 0 ? (pMask[idx] == ucSEIN) : 0;
                    }
                }
                else if ( lid == (groupSize-1) || y == (height-1) ) {
                    for(int i=1; i<=halfSize; i++) {
                        int idx = (y + y0 + i)*gWidth + x + x0;
                        int gy = y + y0 + i;
                        projIn[oLid + i] = gy < gHeight  ? pProjIn[idx] : 0;
                        mask[oLid + i] = gy < gHeight ? (pMask[idx] == ucSEIN) : 0; 
                    }
                }
            }
            
            item.barrier(sycl::access::fence_space::local_space);
            
            if (enabled) {
                res = ConvolOp(projIn, mask, filter, kernelSize, lid);
            }
      
            if (validCoords) {
                pProjOut[gid] = projIn[oLid] + res;
            }
        });

    });

    return 0;
};

2. Specify the command which should be used to compile the program
3. GPU_ARCH ?= sm_75
#for Ampere nvidia GPU - A2000, A4000 use sm_86

CXX_FLAGS=" -fsycl -O3 -Wno-undefined-var-template -I/usr/local/include/sycl/CL/sycl -Xsycl-target-backend --cuda-gpu-arch=${GPU_ARCH} -ffast-math "

I have tested on RTX8000 VM (sm_75) , this used to work with 2023_WW13 but not on 2023-WW46
CXX = clang++ (clang18 for oneAPi 2023-WW46)

4. Specify the comment which should be used to launch the program

6. Indicate what is wrong and what was expected
program crash with above trace

8. should work as for 2023-WW13

**Environment (please complete the following information):**

- OS: [e.g Windows/Linux]
    - SLES15 SP4
- Target device and vendor: [e.g. Intel GPU]
    - nvidia RTX8000
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
    - clang18 / OneAPI 2023-WW13
- Dependencies version: [e.g. low-level runtime versions (like NEO 20.04)]
none
**Additional context**
used to work with oneAPI 2023-WW13 (clang17)

**Comment by rafbiels** [comment]
This is a bug in the Unified Runtime CUDA adapter, specifically in checking whether the kernel fits within the maximum number of registers used per thread block. The thread block size is computed incorrectly, leading to the check erroneously failing when it should pass in some cases.

This specific failing corner case happens on a device where the maximum number of registers per thread block is 65536, as in most NVIDIA GPUs from the past few years. The kernel in question uses 64 registers per thread and is submitted with a local work group size (i.e. the thread block size) of 1024. This gives 64*1024=65536 registers which is right at the limit, but still fits. The bug causes the size to be miscomputed as 1025, which then makes the check compare 65600 against 65535 and the check fails.

Here's a simple reproducer, which worked for me on a GeForce RTX 3060:
```cpp
#include <sycl/sycl.hpp>
#include <iostream>

template<typename... Args>
float __attribute__ ((noinline)) foo(Args& ...args) {
  return (args + ...);
}

struct TestKernel {
  void operator()(sycl::nd_item<2>) const {
    // Adjust the number of variables declared below to reach the device
    // limit for the number of registers per thread block
    volatile int v01{1};
    volatile int v02{1};
    volatile int v03{1};
    volatile int v04{1};
    volatile int v05{1};
    volatile int v06{1};
    volatile int v07{1};
    volatile int v08{1};
    volatile int v09{1};
    volatile int v10{1};
    volatile int v11{1};
    volatile int v12{1};
    volatile int v13{1};
    volatile int v14{1};
    volatile int v15{1};
    volatile int v16{1};
    volatile int v17{1};
    volatile int v18{1};
    volatile int v19{1};
    volatile int v20{1};
    volatile int v21{1};
    volatile int v22{1};
    volatile int v23{1};
    volatile int v24{1};
    volatile int v25{1};
    volatile int v26{1};
    volatile int v27{1};
    volatile int v28{1};
    volatile int v29{1};
    volatile int v30{1};
    // volatile int v31{1};
    // volatile int v31{1};
    // NB: 4 registers are used for nd_item parameter passing logic,
    // so we only need 30 ints to make the kernel use 64 regs (30*2 + 4)
  
    foo(v01, v02, v03, v04, v05, v06, v07, v08,
        v09, v10, v11, v12, v13, v14, v15, v16,
        v17, v18, v19, v20, v21, v22, v23, v24,
        v25, v26, v27, v28, v29, v30//, v31, v32
    );
  }
};

int main(int argc, char** argv) {
  sycl::queue q{};

  auto b = sycl::get_kernel_bundle<TestKernel, sycl::bundle_state::executable>(q.get_context());
  auto k = b.template get_kernel<TestKernel>();
  auto maxWGSize{k.template get_info<sycl::info::kernel_device_specific::work_group_size>(q.get_device())};
  std::cout << "TestKernel max WG size on this device: " << maxWGSize << std::endl;

  sycl::nd_range<2> ndRange{{2*maxWGSize,2},{maxWGSize, 1}};

  q.submit([&](sycl::handler& cgh){
    cgh.parallel_for(ndRange, TestKernel{});
  }).wait_and_throw();
}
```

The output (with an extra printout added in the affected UR check) shows:
```sh
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --offload-arch=sm_86 -O3 -g -o reproducer reproducer.cpp 
$ ./reproducer
TestKernel max WG size on this device: 1024
RB: hasExceededMaxRegistersPerBlock: 1025 * 64 > 65536 = 65600 > 65536 = true
terminate called after throwing an instance of 'sycl::_V1::nd_range_error'
  what():  Non-uniform work-groups are not supported by the target device -54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)
Aborted (core dumped)
```
We see the 1025 here is wrong. I have fix which turns this into:
```sh
$ ./reproducer
TestKernel max WG size on this device: 1024
RB: hasExceededMaxRegistersPerBlock: 1024 * 64 > 65536 = 65536 > 65536 = false
```

The PR is incoming later today.
