### ISSUE TITLE
ONEAPI_DEVICE_SELECTOR does not throw upon an invalid device name 'acc' 

### ISSUE THREAD

**Issue by uditagarwal97** [intel/llvm#12387]
For some reason, ONEAPI_DEVICE_SELECTOR does not throw an exception upon passing an invalid device name 'acc'. AFAIK, 'acc' device is valid for SYCL_DEVICE_FILTER (now depreciated) but is invalid for ONEAPI_DEVICE_SELECTOR.

**To reproduce**
```
/llvm/build/bin$ ONEAPI_DEVICE_SELECTOR=*:acc  ./sycl-ls

Warning: ONEAPI_DEVICE_SELECTOR environment variable is set to *:acc.

To see device ids, please unset ONEAPI_DEVICE_SELECTOR.
 ```
**Expected**: SYCL exception
```
/llvm/build/bin$ ONEAPI_DEVICE_SELECTOR=*:xpu ./sycl-ls

Warning: ONEAPI_DEVICE_SELECTOR environment variable is set to *:xpu.

To see device ids, please unset ONEAPI_DEVICE_SELECTOR.
 
SYCL Exception encountered: error parsing device number: xpu
```

DPC++ commit: 6eac61af50 (12 Jan, 2024)

**Comment by uditagarwal97** [comment]
@gmlueck FYI

**Comment by gmlueck** [comment]
Agreed.  We don't document "acc" as a valid device type.

**Comment by uditagarwal97** [comment]
Okay. I'll create an internal tracker for this issue.

**Comment by uditagarwal97** [comment]
Fixed in https://github.com/intel/llvm/commit/698417a1571bb8f0d9c37487fa75f103ff8b1c37
