### ISSUE TITLE
Update SYCL customization in linkerwrapper after 12c90bd612fe

### ISSUE THREAD

**Issue by jsji** [intel/llvm#12448]
**Describe the bug**
Upstream has updated linkerwrapper in 
https://github.com/llvm/llvm-project/commit/12c90bd612fe7eb9e991bbfce8ca0ec43a3caccb

Merging it will get a failure in clang/test/Driver/linker-wrapper.c

See https://github.com/intel/llvm/actions/runs/7576661596/job/20636328020?pr=12442 for the error message.

We might need to update our SYCL customization after this commit.

**To Reproduce**

Cherry-pick 12c90bd612fe7eb9e991bbfce8ca0ec43a3caccb 
build and test on Windows

This commit is not yet include in WW03's pulldown, it will be merged in WW04's pulldown
so we should fix our customization before 01/25/2024. Thanks.

**Comment by jsji** [comment]
@intel/dpcpp-tools-reviewers FYI, please have a look and update our customization accordingly. Thanks.

**Comment by asudarsa** [comment]
This test is failing in upstream llvm with a similar error message. It is surprising that the change was merged with a failing test. https://buildkite.com/llvm-project/github-pull-requests/builds/30337
I think we can either 'not' merge this commit or merge this commit and mark the test as XFAIL till it gets fixed upstream.

Thanks

**Comment by jsji** [comment]
Thanks @asudarsa ! Yes, we have reverted it, so yes, we can reland it once it is fixed upstream. Thanks.

**Comment by jsji** [comment]
This was reverted yesterday.
[Revert "[LinkerWrapper] Handle AMDGPU Target-IDs correctly when linki…](https://github.com/ROCm/llvm-project/commit/8912c86618d06a676457ad5050bd88426df3567b) …

I also reported the failures to PR in https://github.com/llvm/llvm-project/pull/78359#issuecomment-1904075945.

Let us see whether author will fix it.

Note that we have some additional failures due to customization, but these should be somehow easier to fix.

```
# | <<<<<<
# |            1: D:\github\_work\llvm\llvm\build\bin\clang-offload-bundler.exe: error: invalid target 'sycl-', unknown target triple '' 
# | check:172     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
# |            2: D:\github\_work\llvm\llvm\build\bin\clang-offload-bundler.exe: error: invalid target 'sycl-', unknown target triple '' 
# | check:172     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |            3: D:\github\_work\llvm\llvm\build\bin\clang-offload-bundler.exe: error: invalid target 'sycl-', unknown target triple '' 
```

**Comment by asudarsa** [comment]
Hi @jsji 

I would like to point out the 'revert' has happened downstream in 
https://github.com/ROCm
/
[llvm-project](https://github.com/ROCm/llvm-project)
and the change is still present in upstream LLVM.
We can revisit this if and when the owner turns 'on' the test for windows.

Thanks

**Comment by jsji** [comment]
Thanks. Yes, sure, let it be for now. We will revisit later if we see failures in our test next pulldown.
