### ISSUE TITLE
[SYCL] support compile SYCL runtime api using g++/clang++

### ISSUE THREAD

**Issue by alanzhai219** [intel/llvm#12457]
**Is your feature request related to a problem? Please describe**
- When build a software for heterogeneous system including CPU and GPUs, we always use device compiler(nvcc) to compile the kernels or the wrappers (for kernels) to shared library. And then regular compiler is reponsible to compile the runtime codes and link them tegather. It it uncommon that use nvcc to compile the whole project though it can do it.

- Now, icpx can compile the sycl kernel but g++ cannot compile the sycl runtime api, which is different with nvcc pipeline. 

**Describe the solution you would like**
From my view, runtime api should not depend on icpx and g++ can handle it.
1. icpx compile the kernels or wrappers(for kernels) to so.
2. g++ compile the sycl runtime api and link to the so, generate an execution.
or
1. provide a C style wrapper `sycl_runtime.h` or `sycl_runtime_api.h` like `cuda_runtime.h` or `cuda_runtime_api.h`, which is also a good solution. 

**Describe alternatives you have considered**
1. Have to create a **deeper** wrapper for sycl runtime api and kernel at the customer side. And then export it like regular C or C++ api.
2. use icpx compile wrapper to shared libaray `*.so`.
3. use g++ to compile other host codes and link it with above `so`.

**Additional context**
code is here.
[sample.zip](https://github.com/intel/llvm/files/14008358/sample.zip)

**Comment by steffenlarsen** [comment]
Hi @alanzhai219 ! We do support the use of select non-DPC++ host compilers. Please see https://github.com/intel/llvm/blob/sycl/sycl/doc/FAQ.md#q-how-are-dpc-compilation-phases-different-from-those-of-a-usual-c-compiler-can-i-customize-this-flow-for-my-applications. Does this fulfill your requirements?

**Comment by alanzhai219** [comment]
@steffenlarsen Maybe not. In this spec, developers must select DPC++ as their main compiler, right?
But you know, many projects treat cuda or sycl as a device language. They always use nvcc to compile cuda kernel and then link the binary with other codes by g++ or clang++ tool chain.
In this common case, we cannot force them to use DPC++ as their main compiler. Instead, sycl runtime and sycl kernel should be **decoupled**. 
- sycl runtime can be compiled using g++ and clang++, not triggered by DPC++. We should NOT force developers changing their main compiler. 
- sycl kernel is more specific and it should be compiled by DPC++
That is more acceptable!
What do you think?

**Comment by steffenlarsen** [comment]
To my knowledge, it should be possible to compile a program with non-SYCL compilers that use the SYCL runtime, with some caveats. You can, for example, not use or reference kernels by their names. What you can do however, is wrap the kernel launches in a function, compile those with DPC++ (potentially with another host compiler as previously mentioned) and link them with the application built with the non-SYCL compiler.

For example, you could have
```c++
void MyVecAdd(sycl::queue Q, size_t N, int *LHSVec, int *RHSVec, int *OutVec) {
   Q.parallel_for(N, [=](sycl::id<1> It) {
     OutVec[It] = LHSVec[It] + RHSVec[It];
  });
}
```
in a separate library and call `MyVecAdd` from your main application. The `sycl::queue` and the USM device allocations (or buffers if you prefer) could be created in the application compiled with the non-SYCL compiler.

Let me know if you have a more specific structure in mind and we can explore that too.

**Comment by steffenlarsen** [comment]
@alanzhai219 - Did my previous answer help resolve the issue? If so, are you okay with closing this?

**Comment by KornevNikita** [comment]
@alanzhai219 friendly ping. Can we close this?
