### ISSUE TITLE
SYCL Graph extension: print wrong dependencies with accessors

### ISSUE THREAD

**Issue by antonio-decaro** [intel/llvm#12473]
### Bug Description
Using the "SYCL Graph" extension we noticed that the `print_graph` function shows a linear dependency between three kernels even if there is no data dependency.

### To Reproduce
We executed three kernels that take as input two buffers `a_buf` and `b_buf` (accessors in read mode) and perform a vector addition into respectively `sum_buf1`, `sum_buf2`, and `sum_buf3` distinct output buffer (accessors in write mode). 
```C++
void concurrent_kernels(sycl::queue &q, std::vector<int> &a, std::vector<int> &b) {
  // vectors initializion
  // definition of vectors s1, s2, s3

  sycl::buffer<int> a_buf{a.data(), sycl::range{a.size()}};
  sycl::buffer<int> b_buf{b.data(), sycl::range{b.size()}};
  sycl::buffer<int> sum_buf1{s1.data(), sycl::range{s1.size()}};
  sycl::buffer<int> sum_buf2{s2.data(), sycl::range{s2.size()}};
  sycl::buffer<int> sum_buf3{s3.data(), sycl::range{s3.size()}};

  // set write_back false to each buffer

  size_t num_groups = 1;
  size_t wg_size = 256;

  sycl_ext::command_graph cg (q.get_context(), q.get_device(), {sycl_ext::property::graph::assume_buffer_outlives_graph{}});
  cg.begin_recording(q);

  q.submit([&](sycl::handler &h) {
    sycl::accessor a_acc(a_buf, h, sycl::read_only);
    sycl::accessor b_acc(b_buf, h, sycl::read_only);
    sycl::accessor sum_acc(sum_buf1, h, sycl::write_only, sycl::no_init);

    h.parallel_for<SumA>(sycl::nd_range<1>(num_groups * wg_size, wg_size),
                    [=](sycl::nd_item<1> index) {
                      size_t loc_id = index.get_local_id();
                      sum_acc[loc_id] = 0;
                      for (int j = 0; j < 1000; j++)
                        for (size_t i = loc_id; i < GLOBAL_SIZE; i += wg_size) {
                          sum_acc[loc_id] += a_acc[i] + b_acc[i];
                        }
                    });
  });
  q.submit([&](sycl::handler &h) {
    sycl::accessor a_acc(a_buf, h, sycl::read_only);
    sycl::accessor b_acc(b_buf, h, sycl::read_only);
    sycl::accessor sum_acc(sum_buf2, h, sycl::write_only, sycl::no_init);

    h.parallel_for<SumB>(sycl::nd_range<1>(num_groups * wg_size, wg_size),
                    [=](sycl::nd_item<1> index) {
                      size_t loc_id = index.get_local_id();
                      sum_acc[loc_id] = 0;
                      for (int j = 0; j < 1000; j++)
                        for (size_t i = loc_id; i < GLOBAL_SIZE; i += wg_size) {
                          sum_acc[loc_id] += a_acc[i] + b_acc[i];
                        }
                    });
  });
  q.submit([&](sycl::handler &h) {
    sycl::accessor a_acc(a_buf, h, sycl::read_only);
    sycl::accessor b_acc(b_buf, h, sycl::read_only);
    sycl::accessor sum_acc(sum_buf3, h, sycl::write_only, sycl::no_init);

    h.parallel_for<SumC>(sycl::nd_range<1>(num_groups * wg_size, wg_size),
                    [=](sycl::nd_item<1> index) {
                      size_t loc_id = index.get_local_id();
                      sum_acc[loc_id] = 0;
                      for (int j = 0; j < 1000; j++)
                        for (size_t i = loc_id; i < GLOBAL_SIZE; i += wg_size) {
                          sum_acc[loc_id] += a_acc[i] + b_acc[i];
                        }
                    });
  });

  cg.end_recording(q);
  cg.print_graph("./graph.dot");
  auto eg = cg.finalize();
  q.submit([&](sycl::handler &h) {
    h.ext_oneapi_graph(eg);
  });
  q.wait();
}
```

#### Compiling and Executing
1. To compile: `/path/to/llvm/build/clang++ -fsycl snippet.cpp`
2. To execute: `vtune -collect gpu-offload -- ./a.out`

#### Execution Output
The output file generated by the `print_graph` function shows linear dependency between the kernels:
```
digraph dot {
"0x37fe160" [style=bold, label="ID = 0x37fe160\nTYPE = CGExecKernel \nNAME = _ZTS4SumA\n"];
"0x38015d0" [style=bold, label="ID = 0x38015d0\nTYPE = CGExecKernel \nNAME = _ZTS4SumB\n"];
  "0x37fe160" -> "0x38015d0"
"0x3801630" [style=bold, label="ID = 0x3801630\nTYPE = CGExecKernel \nNAME = _ZTS4SumC\n"];
  "0x38015d0" -> "0x3801630"
}
```

#### Expected Output
We expect that the output file generated by the function `print_graph` doesn't contain any dependency between the kernels.
We expect the output to be as follows:
```
digraph dot {
"0x37fe160" [style=bold, label="ID = 0x37fe160\nTYPE = CGExecKernel \nNAME = _ZTS4SumA\n"];
"0x38015d0" [style=bold, label="ID = 0x38015d0\nTYPE = CGExecKernel \nNAME = _ZTS4SumB\n"];
"0x3801630" [style=bold, label="ID = 0x3801630\nTYPE = CGExecKernel \nNAME = _ZTS4SumC\n"];
}
```

#### VTune Output
By inspecting the VTune output, we can see that each kernel is actually executed concurrently, according to the expected output.
<img width="1013" alt="VTune Output" src="https://github.com/intel/llvm/assets/56648074/21a99650-666d-49aa-9930-5b4012e318c6">

### Environment

- OS: Ubuntu 22.04.3 LTS
- Target device and vendor: Intel GPU ARC A770
- DPC++ version: https://github.com/intel/llvm.git b4ade4209f1beea2fce9aa33679febd038c28137

### Additional Context
We noticed that the problem happens when multiple kernel create a read-only accessor on the same buffer.

**Comment by EwanC** [comment]
tagging @intel/sycl-graphs-reviewers to reply

**Comment by Bensuo** [comment]
Thanks for reporting this issue. It seems that the graph is not taking access modes into account as it should. From a quick look it seems like this could potentially affect the actual execution of the graph (although it doesn't in this case). Will look into providing a fix for this!

**Comment by Bensuo** [comment]
https://github.com/intel/llvm/pull/13011 should fix this issue by preventing the creation of unnecessary edges based on access modes.

**Comment by antonio-decaro** [comment]
@Bensuo Sorry for the late response. I do confirm! I just tested the code I posted in the issue, and it looks like it works! Indeed, there are no more dependencies between the _sum_ kernels.

Thank you very much for your prompt response.
