### ISSUE TITLE
multi_ptr relational operators assumes nullptr is 0

### ISSUE THREAD

**Issue by Naghasan** [intel/llvm#12493]
**Describe the bug**

`multi_ptr` relational operators taking a `std::nullptr_t` are written in a way that assume it is the lowest possible value
(example https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/multi_ptr.hpp#L1575). However the C++ specs states there is no ordering requirement (https://eel.is/c++draft/expr.rel#4.3).

In practice, this is causing issues in the CUDA and AMDGPU backend as @mmoadeli uncovered. For instance, in CUDA the `nullptr` in the local address space is a non `0` value and `0` in this address space is the root of the allocated local memory.

**Comment by mmoadeli** [comment]
Below may be used to re-produce the issue for CUDA.
```
#include <sycl/sycl.hpp>

using multi_ptr_t = sycl::multi_ptr<long, sycl::access::address_space::local_space, sycl::access::decorated::yes>;

int main() {
  long value[2];
  try {
    sycl::queue Queue;
    sycl::buffer<long, 1> buf(value, sycl::range<1>(2));
    Queue.submit([&](sycl::handler &cgh) {
      auto dev_acc = buf.get_access<sycl::access::mode::discard_write>(cgh);
      sycl::local_accessor<long, 1> locAcc1(1, cgh);
      cgh.parallel_for<class test_multi_ptr_comparison>(
          sycl::nd_range<1>{1, 1}, [=](sycl::id<1>) {
            locAcc1[0] = 10;
            multi_ptr_t mp(locAcc1);
            multi_ptr_t nullptr_mptr(nullptr); 
            dev_acc[0] = std::less<multi_ptr_t>()(nullptr, mp); 
            dev_acc[1] = nullptr < mp; 
          });
    }).wait_and_throw();

  } catch (sycl::exception e) {
    std::cout << "SYCL exception caught: " << e.what();
    return 1;
  }
  std::cout << "value: " << value[0] << " "<< value[1] <<std::endl;
  return 0;
}
```

**Comment by dkhaldi** [comment]
@mmoadeli, I am not able to reproduce the results on Nvidia hardware right now.
Can you please paste the result you get on an Nvidia GPU with the code you have above?

**Comment by mmoadeli** [comment]
@dkhaldi 
Adjusting decorated::yes to decorated::no in the line:
`using multi_ptr_t = sycl::multi_ptr<long, sycl::access::address_space::local_space, sycl::access::decorated::yes>;
`
should expose the issue. The output is: `value: 0 1` on GeForce GTX 1050 Ti . It seems a bit weird; I recall that leaving the code as shown above used to reveal the problem with `nullptr`

**Comment by mmoadeli** [comment]
I also get `value: 0` with below code.
```
#include <sycl/sycl.hpp>

int main() {
  auto queue = sycl::queue();
  long value = 1;
  try {
    sycl::buffer<long> val_buffer(&value, sycl::range(1));
    queue
        .submit([&](sycl::handler &cgh) {
          auto acc_for_multi_ptr = val_buffer.template get_access(cgh);
          cgh.single_task<class kname>([=] {
            sycl::multi_ptr<long, sycl::access::address_space::local_space,
                            sycl::access::decorated::yes>
                mp(nullptr);
            acc_for_multi_ptr[0] = mp.get_raw() == nullptr;
          });
        })
        .wait_and_throw();
  } catch (sycl::exception e) {
    std::cout << "SYCL exception caught: " << e.what();
    return 1;
  }
  std::cout << "value: " << std::hex << value << std::endl;
  return 0;
}
```

**Comment by dkhaldi** [comment]
OK, using your initial code, I get:
value: 1 1 on PVC and the CPU
value: 0 0 on A100 decorated::yes
value: 0 1 on A100 decorated::no
So it seems like on Intel hardware, nullptr is treated as the lowest including in the C++ implementation (std::less).
on Nvidia, nullptr is not the lowest. You get the expected value "0" when "decorated::yes" is passed.
@mmoadeli, what do you suggest the fix should be?

**Comment by mmoadeli** [comment]
@dkhaldi 
This issue is an interesting one which I had intended to start working on next week. However, I am still unsure of a suitable approach to resolve it.

**Comment by dkhaldi** [comment]
@mmoadeli, do you have any clarifications updates on this issue? I got "0" with A100 with "decorated::yes".
So I am not sure there is a bug here.

**Comment by mmoadeli** [comment]
> @mmoadeli, do you have any clarifications updates on this issue? I got "0" with A100 with "decorated::yes". So I am not sure there is a bug here.

@dkhaldi It is almost done and I’ll have a PR shortly. All CTS multi_ptr tests and above one pass with the coming PR.
