### ISSUE TITLE
[CUDA][HIP] user_defined_reductions

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#12613]
// UNSUPPORTED: cuda || hip

#include <sycl/ext/oneapi/experimental/user_defined_reductions.hpp>

File: test-e2e/UserDefinedReductions/user_defined_reductions.cpp

**Comment by jinz2014** [comment]
I think the line '// UNSUPPORTED: cuda || hip' could be removed in the file. Thanks for checking again.

**Comment by steffenlarsen** [comment]
Patch to re-enable the test here: https://github.com/intel/llvm/pull/13057
