### ISSUE TITLE
Unresolved extern function '_Z17__spirv_ocl_s_absi' when using CUDA plugin

### ISSUE THREAD

**Issue by ywang30intel** [intel/llvm#1267]
Build with simple-sycl-app.cpp with cl::sycl::abs() function in the sycl kernel, this will trigger the following error:
$clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice simple-sycl-app.cpp -o test
ptxas fatal   : Unresolved extern function '_Z17__spirv_ocl_s_absi'
clang-11: error: ptxas command failed with exit code 255 (use -v to see invocation)

Just add cl::sycl::abs() function call in the kernel results in this error.
$cat simple-sycl-app.cpp 
#include <CL/sycl.hpp>

int main() {

	class CUDASelector : public cl::sycl::device_selector {
  public:
    int operator()(const cl::sycl::device &Device) const override {
      using namespace cl::sycl::info;

      const std::string DriverVersion = Device.get_info<device::driver_version>();

      if (Device.is_gpu() && (DriverVersion.find("CUDA") != std::string::npos)) {
        return 1;
      };
      return -1;
    }
};

  CUDASelector Selector;

  // Creating buffer of 4 ints to be used inside the kernel code
  cl::sycl::buffer<cl::sycl::cl_int, 1> Buffer(4);

  // Creating SYCL queue
  cl::sycl::queue Queue(Selector);

  // Size of index space for kernel
  cl::sycl::range<1> NumOfWorkItems{Buffer.get_count()};

  // Submitting command group(work) to queue
  Queue.submit([&](cl::sycl::handler &cgh) {
    // Getting write only access to the buffer on a device
    auto Accessor = Buffer.get_access<cl::sycl::access::mode::write>(cgh);
    // Executing kernel
    cgh.parallel_for<class FillBuffer>(
        NumOfWorkItems, [=](cl::sycl::id<1> WIid) {
          // Fill buffer with indexes
          Accessor[WIid] = **cl::sycl::abs**((cl::sycl::cl_int)WIid.get(0));
        });
  });

  // Getting read only access to the buffer on the host.
  // Implicit barrier waiting for queue to complete the work.
  const auto HostAccessor = Buffer.get_access<cl::sycl::access::mode::read>();

  // Check the results
  bool MismatchFound = false;
  for (size_t I = 0; I < Buffer.get_count(); ++I) {
    if (HostAccessor[I] != I) {
      std::cout << "The result is incorrect for element: " << I
                << " , expected: " << I << " , got: " << HostAccessor[I]
                << std::endl;
      MismatchFound = true;
    }
  }

  if (!MismatchFound) {
    std::cout << "The results are correct!" << std::endl;
  }

  return MismatchFound;
}

**Comment by jinz2014** [comment]
Please also add  sqrt

Unresolved extern function '_Z16__spirv_ocl_sqrtIddET_T0_'

Thanks

**Comment by jinz2014** [comment]
Please also add cl::sycl::trunc

**Comment by Ruyk** [comment]
Do you still have this problem? A number of PRs solving libcl issues have been merged, and the functions mentioned should be there...

**Comment by jinz2014** [comment]
abs is included.

Can you please add the following math functions for RSBench ?

ptxas fatal   : Unresolved extern function '_Z16__spirv_ocl_atand'
clang-11: error: ptxas command failed with exit code 255 (use -v to see invocation)

Thanks

**Comment by jinz2014** [comment]
Can you please point a link to "A number of PRs solving libcl issues have been merged" ? 

Thanks

**Comment by Ruyk** [comment]
If you filter by the "libclc" label, you can see the list of pr: https://github.com/intel/llvm/pulls?q=is%3Apr+label%3Alibclc+  
All required builtins for 1.2.1 should be up in the next few weeks.

**Comment by bader** [comment]
@ywang30intel, @jinz2014, please, verify that all built-ins are working now.

**Comment by jinz2014** [comment]
I verify that the benchmark runs successfully.

**Comment by bader** [comment]
Great! @jinz2014, thanks a lot for confirmation.

**Comment by khaled-rahman** [comment]
I faced unresolved extern function _Z17_spirv_ocl_frexpfPU3AS1i.
Could you please check it out?
