### ISSUE TITLE
[SYCL-FUSION] [DebugInfo] Enable support of non-instrinsic debug-info

### ISSUE THREAD

**Issue by jsji** [intel/llvm#12698]
Community has been trying to turn on non-instrinsic debug-info by default.

https://github.com/llvm/llvm-project/commit/5c9f7682b090124d9a8b69f92d3f7c269dca25fc

We need to enable support in our SYCL FUSION before we can turn it on by default.

These sycl-fusion tests are failing after enable it.

  SYCL-FUSION :: internalization/promote-local-nested.ll
  SYCL-FUSION :: internalization/promote-local-scalar.ll
  SYCL-FUSION :: internalization/promote-local-vec.ll
  SYCL-FUSION :: internalization/promote-private-nested.ll
  SYCL-FUSION :: internalization/promote-private-non-unit.ll
  SYCL-FUSION :: internalization/promote-private-scalar.ll
  SYCL-FUSION :: internalization/promote-private-vec.ll
  SYCL-FUSION :: kernel-fusion/check-remapping-interproc.ll
  SYCL-FUSION :: kernel-fusion/check-remapping.ll
  SYCL-FUSION :: kernel-fusion/required_work_group_size.ll
  SYCL-FUSION :: kernel-fusion/two-kernels-no-identities.ll
  SYCL-FUSION :: kernel-fusion/two-kernels-out-is-in.ll
  SYCL-FUSION :: kernel-fusion/work_group_size_hint.ll
  SYCL-FUSION :: syclcp/syclcp.ll

The work mostly include call NF->setIsNewDbgInfoFormat(F->IsNewDbgInfoFormat); after Function::Create.

Ref:
[0] https://llvm.org/docs/RemoveDIsDebugInfo.html
[1] https://discourse.llvm.org/t/rfc-instruction-api-changes-needed-to-eliminate-debug-intrinsics-from-ir/68939

**Comment by jsji** [comment]
@intel/dpcpp-kernel-fusion-reviewers Can you have a look? Thanks.

**Comment by victor-eds** [comment]
https://github.com/intel/llvm/pull/12712 should fix this issue when merged. I'll notify here when that's done.

**Comment by KornevNikita** [comment]
Hi @victor-eds, could you confirm if it's working now?

**Comment by victor-eds** [comment]
> Hi @victor-eds, could you confirm if it's working now?

It is working now. I'll close this now. Thanks for reminding! @KornevNikita
