### ISSUE TITLE
Test "ESIMD/unified_memory_api/scatter_lacc_dg2_pvc.cpp" failing on unrelated changes

### ISSUE THREAD

**Issue by sommerlukas** [intel/llvm#12769]
**Describe the bug**
The test `ESIMD/unified_memory_api/scatter_lacc_dg2_pvc.cpp` fails on unrelated changes in post-commit on multiple PRs.

**To Reproduce**

Amongst others, the test failed in post-commit on the following PRs:
* https://github.com/intel/llvm/pull/12549
* https://github.com/intel/llvm/pull/12680

**Comment by KornevNikita** [comment]
Fixed by 12745.
