### ISSUE TITLE
Assert tests fail on Windows Gen12

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#12797]
The following tests have started failing on CI Windows E2E testing on Gen12:
-   SYCL :: Assert/assert_in_kernels_win.cpp
-   SYCL :: Assert/assert_in_multiple_tus_one_ndebug_win.cpp
-   SYCL :: Assert/assert_in_multiple_tus_win.cpp
-   SYCL :: Assert/assert_in_one_kernel_win.cpp
-   SYCL :: Assert/assert_in_simultaneous_kernels_win.cpp
-   SYCL :: Assert/assert_in_simultaneously_multiple_tus.cpp
-   SYCL :: Assert/assert_in_simultaneously_multiple_tus_one_ndebug.cpp

See for example https://github.com/intel/llvm/pull/12778 and https://github.com/intel/llvm/pull/12766

**Comment by aelovikov-intel** [comment]
Possibly related: https://github.com/intel/llvm/issues/11364 (as per internal defect for win failures).

**Comment by lbushi25** [comment]
Can we close this now that https://github.com/intel/llvm/pull/15232 has been merged?
