### ISSUE TITLE
Add `value_type` type Alias to `sycl::vec` to match the SYCL 2020 Specification

### ISSUE THREAD

**Issue by Alcpz** [intel/llvm#12954]
### Is your feature request related to a problem? Please describe

The [SYCL 2020 specification](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_vec_interface) defines `sycl::vec` as a templated class `template <typename DataT, int NumElements> class vec`, with two type aliases for `DataT`: `element_type` and `value_type`.
DPCPP currently implements `element_type` but not the second, which ends with an inconsistent interface between data classes.

Minor example:

```cpp
#include <sycl/sycl.hpp>

template <typename Container, typename ValueT>
static constexpr bool contained_is_same_v =
    std::is_same_v<typename Container::value_type, ValueT>;

int main() {
    // fails at compile time
    // static_assert(contained_is_same_v<sycl::vec<unsigned, 1>, unsigned>); // Won´t compile
    static_assert(contained_is_same_v<sycl::marray<unsigned, 1>, unsigned>); // true
    static_assert(contained_is_same_v<sycl::buffer<unsigned>, unsigned>); // true
}
```

### Describe the solution you would like

`using value_type = DataT` type alias implemented as part of `sycl::vec`

### Additional context

Specializing for `sycl::vec` avoids the issue:

```cpp
#include <sycl/sycl.hpp>

template <typename Container, typename ValueT>
static constexpr bool contained_is_same_v =
    std::is_same_v<typename Container::value_type, ValueT>;

template <typename Contained, int NumElements, typename ValueT>
static constexpr bool
    contained_is_same_v<sycl::vec<Contained, NumElements>, ValueT> =
        std::is_same_v<Contained, ValueT>;

int main() {
    static_assert(contained_is_same_v<sycl::vec<unsigned, 1>, unsigned>); // true
    static_assert(contained_is_same_v<sycl::marray<unsigned, 1>, unsigned>); // true
    static_assert(contained_is_same_v<sycl::buffer<unsigned>, unsigned>); // true
}
```

Still, It would be a nice feature to avoid extra boilerplate code.

**Comment by lbushi25** [comment]
Hi @Alcpz , a PR for this is in review!
https://github.com/intel/llvm/pull/12960/

**Comment by Alcpz** [comment]
@lbushi25, working as expected now. Thanks a lot for that :+1:
