### ISSUE TITLE
MTL support for sycl_ext_oneapi_device_architecture

### ISSUE THREAD

**Issue by DDEle** [intel/llvm#12988]
### Is your feature request related to a problem? Please describe

Hi, I noticed that there is already some discussion of MTL in #10384 (which seems not active now). As some SKU of Meteor Lake has already launched, is there any plan to add MTL support for [sycl_ext_oneapi_device_architecture](https://github.com/intel/llvm/blob/nightly-2024-03-12/sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc)?

**Comment by dm-vodopyanov** [comment]
@DDEle thanks for the heads-up, the request was implemented in https://github.com/intel/llvm/commit/fee1b10901f94925fcae7b349c9b8ba7c40b3b00.
Closing as completed. Feel free to re-open the issue if something appears.
