### ISSUE TITLE
Follow the steps from public instructions TBB libraries in OpenCL RT installation failed

### ISSUE THREAD

**Issue by galinart** [intel/llvm#13009]
### Describe the bug

Follow the steps from public instructions TBB libraries in OpenCL RT installation failed
https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime 

### To reproduce

In particular sections:

Section 2. Create ICD file pointing to the new runtime (requires root access)
Creation of the file required to use different command since sudo only appried to "echo" command, not to file creation (see https://www.adamsdesk.com/posts/sudo-echo-permission-denied/#:~:text=It%20makes%20sense%20that%20if,not%20allowed%20to%20do%20so. )

e.g.
`echo "/opt/intel/oclcpuexp_<cpu_version>/x64/libintelocl.so" | sudo tee /etc/OpenCL/vendors/intel_expcpu.icd`

Section 4. Copy files from or create symbolic links to TBB libraries in OpenCL RT folder:

The symlinks required different syntax

Instead of:
`ln -s /opt/intel/oneapi-tbb-<tbb_version>/lib/intel64/gcc4.8/libtbb.so /opt/intel/oclcpuexp_<cpu_version>/x64`

Use:
`ln -s /opt/intel/oneapi-tbb-<tbb_version>/lib/intel64/gcc4.8/libtbb.so /opt/intel/oclcpuexp_<cpu_version>/x64/libtbb.so`

Section 5. Configure library paths (requires root access)

The same issue as 2.

### Environment

- OS: Linux

**Comment by againull** [comment]
Fixed in https://github.com/intel/llvm/pull/14204

**Comment by galinart** [comment]
@againull appreciated!
