### ISSUE TITLE
sycl/test-e2e/Plugin/interop-level-zero-image.cpp

### ISSUE THREAD

**Issue by ldrumm** [intel/llvm#13090]
Post-commit testing has been failing for multiple weeks. The root cause of this is sycl/test-e2e/Plugin/interop-level-zero-image.cpp which has been failing on the ARC GPUs consistently. This has clouded other test failures - why should anyone care about post-commit testing if it's always red?

 We should disable this test to lower the noise level; it's too late to revert the patch that introduced it.

**Comment by nrspruit** [comment]
Fixed in https://github.com/intel/llvm/pull/13338
