### ISSUE TITLE
Post-commit compilation fails with undefined reference to `__exp10'

### ISSUE THREAD

**Issue by sommerlukas** [intel/llvm#13225]
### Describe the bug

Compilation of DPC++ itself fails in the post-commit pipeline. 

The error message is:
```
AMDGPULibCalls.cpp:(.text._ZN4llvm14AMDGPULibCalls22evaluateScalarMathFuncERKNS_13AMDGPULibFuncERdS4_PNS_8ConstantES6_+0x31e): undefined reference to `__exp10'
```

### To reproduce

For example, see post-commit pipeline here: https://github.com/intel/llvm/actions/runs/8506162269/job/23295912063

### Environment

Post-commit pipeline on Linux

**Comment by sommerlukas** [comment]
@jsji As this started to fail soon after the pulldown last week (https://github.com/intel/llvm/pull/13103), do you think there's a chance of this being related to the pulldown?

**Comment by jsji** [comment]
> I have a similar issue when compiling code with DPC++ (DPC++ itself builds fine somehow). [9848fa4](https://github.com/intel/llvm/commit/9848fa4aa2a83b0fc3a93e5f905ef09c8dd85226) seems to be the culprit.
> 
> UPD: It was [reverted upstream](https://github.com/llvm/llvm-project/pull/68736#issuecomment-2009203758), so another pulldown should solve the problem.

Thanks @al42and , yes, [eefef900c6a24f2acd](https://github.com/llvm/llvm-project/commit/eefef900c6a24f2acd724726bc52884e058575da) is latest pulldown. https://github.com/intel/llvm/pull/13190

**Comment by bader** [comment]
@sommerlukas, https://github.com/intel/llvm/pull/13190 is merged. Please, close the issue if the problem is fixed.

**Comment by sommerlukas** [comment]
@bader @jsji Post-commit for the pulldown in #13190 failed with the same error message as described above, so it seems that the pulldown did not fix the issue.

https://github.com/intel/llvm/actions/runs/8510917365/job/23309509875

**Comment by jsji** [comment]
I tried to do a self-build locally, but my build passed.

```
/iusers/jinsongj/llvm/build# /iusers/jinsongj/llvm/install/bin/clang++ -v
clang version 19.0.0git (https://github.com/intel/llvm.git fce067000ae1d9893410e6b04ebf60d3f7df9f86)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /iusers/jinsongj/llvm/install/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
/iusers/jinsongj/llvm/build# grep CMAKE_C.*COMPILER: CMakeCache.txt
CMAKE_CXX_COMPILER:FILEPATH=/iusers/jinsongj/llvm/install/bin/clang++
CMAKE_C_COMPILER:FILEPATH=/iusers/jinsongj/llvm/install/bin/clang
/iusers/jinsongj/llvm/build# objdump -t lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPULibCalls.cpp.o|grep exp10
0000000000000000 l     O .rodata._ZL9tbl_exp10  0000000000000030 _ZL9tbl_exp10
0000000000000000 l    d  .rodata._ZL9tbl_exp10  0000000000000000 .rodata._ZL9tbl_exp10
```

**Comment by jsji** [comment]
I am able to reproduce the failures using old SYCL driver.

```
root@pod-ub22l-scsel-clx-20:/iusers/jinsongj/llvm/build# clang++ -v
clang version 19.0.0git (https://github.com/intel/llvm.git 5f2411c2230f1f2a80f1fb13503f405eb357c368)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /iusers/jinsongj/llvm/install/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
root@pod-ub22l-scsel-clx-20:/iusers/jinsongj/llvm/build# objdump -t lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPULibCalls.cpp.o|grep exp10
0000000000000000 l     O .rodata._ZL9tbl_exp10  0000000000000030 _ZL9tbl_exp10
0000000000000000 l    d  .rodata._ZL9tbl_exp10  0000000000000000 .rodata._ZL9tbl_exp10
0000000000000000         *UND*  0000000000000000 __exp10
```

**Comment by jsji** [comment]
And unfortunately, the latest nightly docker image is not updated due to a recent bug.

https://github.com/intel/llvm/actions/runs/8503213589/job/23288710904

**Comment by sommerlukas** [comment]
The post-commit failure in the "Commit" stage seems resolved, closing this issue.
