### ISSUE TITLE
Massive failures when enabling new dbgformat in llvm-link

### ISSUE THREAD

**Issue by jsji** [intel/llvm#13228]
### Describe the bug

We are seeing massive failures in pulldown when upstream enabled new dbgformat in llvm-link.
https://github.com/intel/llvm/commit/8263a883342d9925a4a1fd9752efc8deda5840fc

See https://github.com/intel/llvm/actions/runs/8470059471/job/23209282642 for more details.
### To reproduce

Merge in (or after) pulldown https://github.com/intel/llvm/pull/13190 
cherry-pick https://github.com/intel/llvm/commit/8263a883342d9925a4a1fd9752efc8deda5840fc

```
# RUN: at line 2
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/AddressSanitizer/common/demangle-kernel-name.cpp -Xsycl-target-frontend -fsanitize=address -O2 -g -o /__w/llvm/llvm/build-e2e/AddressSanitizer/common/Output/demangle-kernel-name.cpp.tmp
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/AddressSanitizer/common/demangle-kernel-name.cpp -Xsycl-target-frontend -fsanitize=address -O2 -g -o /__w/llvm/llvm/build-e2e/AddressSanitizer/common/Output/demangle-kernel-name.cpp.tmp
# .---command stderr------------
# | Unknown function for CallBase upgrade.
# | UNREACHABLE executed at /__w/llvm/llvm/src/llvm/lib/IR/AutoUpgrade.cpp:[42](https://github.com/intel/llvm/actions/runs/8470059471/job/23209282642#step:21:43)62!
# | PLEASE submit a bug report to https://github.com/intel/llvm/issues and include the crash backtrace.
# | Stack dump:
# | 0.	Program arguments: /__w/llvm/llvm/toolchain/bin/llvm-link -only-needed /tmp/lit-tmp-pvkvr07e/demangle-kernel-name-4bbbc3.bc /tmp/lit-tmp-pvkvr07e/libsycl-crt-bff144.o /tmp/lit-tmp-pvkvr07e/libsycl-complex-8d9dbc.o /tmp/lit-tmp-pvkvr07e/libsycl-complex-fp64-772474.o /tmp/lit-tmp-pvkvr07e/libsycl-cmath-45be32.o /tmp/lit-tmp-pvkvr07e/libsycl-cmath-fp64-27dd29.o /tmp/lit-tmp-pvkvr07e/libsycl-imf-0d80ec.o /tmp/lit-tmp-pvkvr07e/libsycl-imf-fp64-469e44.o /tmp/lit-tmp-pvkvr07e/libsycl-imf-bf16-abccf3.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-cassert-138c2b.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-cstring-e[43](https://github.com/intel/llvm/actions/runs/8470059471/job/23209282642#step:21:44)b25.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-complex-423d21.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-complex-fp64-97835c.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-cmath-7f73b7.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-cmath-fp64-6caf8c.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-imf-a61d13.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-imf-fp64-365638.o /tmp/lit-tmp-pvkvr07e/libsycl-fallback-imf-bf16-7cfff4.o /tmp/lit-tmp-pvkvr07e/libsycl-itt-user-wrappers-b733ae.o /tmp/lit-tmp-pvkvr07e/libsycl-itt-compiler-wrappers-a1b403.o /tmp/lit-tmp-pvkvr07e/libsycl-itt-stubs-1aa28b.o /tmp/lit-tmp-pvkvr07e/libsycl-sanitizer-5b1a14.o -o /tmp/lit-tmp-pvkvr07e/demangle-kernel-name-281180.bc --suppress-warnings
# | Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):

```

**Comment by jsji** [comment]
> This ([8263a88](https://github.com/intel/llvm/commit/8263a883342d9925a4a1fd9752efc8deda5840fc)) is one of many commits that were made in the community in this area. We might need all of them. I will try to cherry pick them all and see if the issue is resolved.
> 
> Thanks

Sorry,  `cherry-pick` here should be *based* on the latest pulldown PR.
The pulldown PR https://github.com/intel/llvm/actions/runs/8470059471/job/23209282642  should contains *ALL* of them, but we were still failing.  Reverting this make the pass. 

Thanks @asudarsa .

**Comment by jsji** [comment]
Looks like this is an issue also exist in community. Small reproducer:

```
$cat t.cpp
int __attribute__((always_inline)) func(int x) {
   return x * 2;
 }
$ clang++ -g -c -emit-llvm t.cpp
$ llvm-link t.bc
```

**Comment by jsji** [comment]
Add comments to original commit https://github.com/llvm/llvm-project/pull/86274#issuecomment-2030981662

**Comment by SLTozer** [comment]
This should be fixed in upstream now: https://github.com/llvm/llvm-project/commit/ed5fe66370cb0ea88913458d71959407dc7b1394

**Comment by KornevNikita** [comment]
Looks like it works now. At least this reproducer doesn't crash.

> Looks like this is an issue also exist in community. Small reproducer:
> 
> ```
> $cat t.cpp
> int __attribute__((always_inline)) func(int x) {
>    return x * 2;
>  }
> $ clang++ -g -c -emit-llvm t.cpp
> $ llvm-link t.bc
> ```

@jsji @asudarsa could you please verify?

**Comment by jsji** [comment]
Fixed. Thanks.
