### ISSUE TITLE
Graph E2E tests fail on unrelated changes in Arc post-commit

### ISSUE THREAD

**Issue by sommerlukas** [intel/llvm#13301]
### Describe the bug

The test `Graph/RecordReplay/valid_no_end.cpp` fails on unrelated changes in the post-commit pipeline. 

Example of a failed pipeline: https://github.com/intel/llvm/actions/runs/8570018495/job/23487886595

**Comment by EwanC** [comment]
See also https://github.com/intel/llvm/actions/runs/8596338570/job/23553181114 for `ValidUsage/empty_graph.cpp` failing on Arc in the post-commit of an unrelated PR.

**Comment by EwanC** [comment]
Closing this issue, as tests are disabled and we have an internal team task to investigate and re-enable.
