### ISSUE TITLE
Latest release cannot be extracted correctly

### ISSUE THREAD

**Issue by rogela** [intel/llvm#1337]
When the release 20200316 is extracted, include/CL shows up as a single file instead of the expected directory.

**Comment by bader** [comment]
Most likely this issue was introduced by https://github.com/intel/llvm/pull/1308.
@vladimirlaz, please, take a look.

**Comment by vladimirlaz** [comment]
I am working on that.

**Comment by vladimirlaz** [comment]
@rogela, please try 20200318 release. Fixed compiler package has been uploaded.
