### ISSUE TITLE
[SYCL][SPV_INTEL_bindless_images] Add OpConvertHandleToSampledImageINTEL back to the extension

### ISSUE THREAD

**Issue by wenju-he** [intel/llvm#13392]
### Is your feature request related to a problem? Please describe

Implementation of bindless sampled image in intel gpu backend will use a single 64-bit handle. Conversion from integer handle to sampled image is required. Sampler won't be present in OpConvertHandleToSampledImageINTEL.

@DBDuncan could you review this request?

**Comment by ProGTX** [comment]
This should have been fixed in https://github.com/intel/llvm/pull/13753

**Comment by wenju-he** [comment]
thank you @DBDuncan @ProGTX, closing this issue
