### ISSUE TITLE
[CUDA] "CL/sycl.hpp" include not found when compiling with CUDA backend

### ISSUE THREAD

**Issue by cgleggett** [intel/llvm#1342]
header CL/sycl.hpp is not automatically found when targeting the CUDA backend, unless the include directory is explicitly specified in the compilation line via `-I$(SYCL_BLD_DIR)/include/sycl`

This is not the case if the CUDA backend is not targeted.

**Comment by vladimirlaz** [comment]
Fix is available in https://github.com/intel/llvm/pull/1347

**Comment by cgleggett** [comment]
looks good. I'm now faced with #1353, but it looks like it's finding the header files without manual intervention.

**Comment by bader** [comment]
Fixed by https://github.com/intel/llvm/pull/1347.
