### ISSUE TITLE
CUDA unresolved extern function '_Z16__spirv_ocl_sqrtIffET_T0_' 

### ISSUE THREAD

**Issue by pvelesko** [intel/llvm#1350]
The same use case works in a simple reproducer, but when trying to compile the full code it breaks with the mentioned error. 
Tried using sqrt, cl::sycl::sqrt,compiler inline the function, manual inline, different sm_ targets. 

to reproduce:
export SYCL_BE=PI_CUDA
export ARCH=sycl-intel
make

./nbody.x 

[Reproducer attached](https://www.dropbox.com/s/h5zr7bkxlnod8vs/reproducer.tar?dl=0).

**Comment by christgau** [comment]
I'm observing the same issue but also with a very simple reproducer, basically a vector fill example that sets every vector element to the square root of the index. I built the compiler with fcadd26d7cf517127e9d5a99b293058ef9e0a7ab

Here's the code
```cpp
#include <cmath>
#include <CL/sycl.hpp>

constexpr size_t BUF_SIZE = 256;

int main() {
  bool retval = true;

  for (const cl::sycl::device &device : cl::sycl::device::get_devices()) {
    std::cout << "Running on SYCL device " << device.get_info<cl::sycl::info::device::name>()
              << ", driver version " << device.get_info<cl::sycl::info::device::driver_version>()
              << std::endl;

    cl::sycl::buffer<cl::sycl::cl_float, 1> Buffer(BUF_SIZE);
    cl::sycl::queue queue{device};
    cl::sycl::range<1> NumOfWorkItems{Buffer.get_count()};

    queue.submit([&](cl::sycl::handler &cgh) {
      auto Accessor = Buffer.get_access<cl::sycl::access::mode::write>(cgh);
      cgh.parallel_for<class FillBuffer>(
          NumOfWorkItems, [=](cl::sycl::id<1> WIid) {
            Accessor[WIid] = cl::sycl::sqrt(1.0f * (cl::sycl::cl_int)WIid.get(0));
          });
    });

    const auto HostAccessor = Buffer.get_access<cl::sycl::access::mode::read>();

    bool MismatchFound = false;
    for (size_t I = 0; I < Buffer.get_count(); ++I) {
      if (HostAccessor[I] != sqrt(1.0f * I)) {
        std::cout << "The result is incorrect for element: " << I
                  << " , expected: " << I << " , got: " << HostAccessor[I]
                  << std::endl;
        MismatchFound = true;
      }
    }

    if (!MismatchFound) {
      std::cout << "The results are correct!" << std::endl;
    }

    retval = retval && MismatchFound;
  }

  return retval;
}
```

I get the following error 

> ptxas fatal   : Unresolved extern function '_Z16__spirv_ocl_sqrtIffET_T0_'
> clang++: error: ptxas command failed with exit code 255 (use -v to see invocation)

ptxas is invoked with ` "/path/to/ptxas" -m64 -g --dont-merge-basicblocks --return-at-end -v --gpu-name sm_30 --output-file /tmp/vector_fill_sqrt-272876.o /tmp/vector_fill_sqrt-c7b9cb.s`

The compiler is invoked with basically nothing more than `-g -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice` as well as a path to the GCC toolchain that was used to build the compiler.

**Comment by Ruyk** [comment]
Could you retry this? A number of libcl PRs have been merged and we can't see this issue locally.

**Comment by jinz2014** [comment]
> I'm observing the same issue but also with a very simple reproducer, basically a vector fill example that sets every vector element to the square root of the index. I built the compiler with [fcadd26](https://github.com/intel/llvm/commit/fcadd26d7cf517127e9d5a99b293058ef9e0a7ab)
> 
> Here's the code
> 
> ```c++
> #include <cmath>
> #include <CL/sycl.hpp>
> 
> constexpr size_t BUF_SIZE = 256;
> 
> int main() {
>   bool retval = true;
> 
>   for (const cl::sycl::device &device : cl::sycl::device::get_devices()) {
>     std::cout << "Running on SYCL device " << device.get_info<cl::sycl::info::device::name>()
>               << ", driver version " << device.get_info<cl::sycl::info::device::driver_version>()
>               << std::endl;
> 
>     cl::sycl::buffer<cl::sycl::cl_float, 1> Buffer(BUF_SIZE);
>     cl::sycl::queue queue{device};
>     cl::sycl::range<1> NumOfWorkItems{Buffer.get_count()};
> 
>     queue.submit([&](cl::sycl::handler &cgh) {
>       auto Accessor = Buffer.get_access<cl::sycl::access::mode::write>(cgh);
>       cgh.parallel_for<class FillBuffer>(
>           NumOfWorkItems, [=](cl::sycl::id<1> WIid) {
>             Accessor[WIid] = cl::sycl::sqrt(1.0f * (cl::sycl::cl_int)WIid.get(0));
>           });
>     });
> 
>     const auto HostAccessor = Buffer.get_access<cl::sycl::access::mode::read>();
> 
>     bool MismatchFound = false;
>     for (size_t I = 0; I < Buffer.get_count(); ++I) {
>       if (HostAccessor[I] != sqrt(1.0f * I)) {
>         std::cout << "The result is incorrect for element: " << I
>                   << " , expected: " << I << " , got: " << HostAccessor[I]
>                   << std::endl;
>         MismatchFound = true;
>       }
>     }
> 
>     if (!MismatchFound) {
>       std::cout << "The results are correct!" << std::endl;
>     }
> 
>     retval = retval && MismatchFound;
>   }
> 
>   return retval;
> }
> ```
> 
> I get the following error
> 
> > ptxas fatal   : Unresolved extern function '_Z16__spirv_ocl_sqrtIffET_T0_'
> > clang++: error: ptxas command failed with exit code 255 (use -v to see invocation)
> 
> ptxas is invoked with ` "/path/to/ptxas" -m64 -g --dont-merge-basicblocks --return-at-end -v --gpu-name sm_30 --output-file /tmp/vector_fill_sqrt-272876.o /tmp/vector_fill_sqrt-c7b9cb.s`
> 
> The compiler is invoked with basically nothing more than `-g -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice` as well as a path to the GCC toolchain that was used to build the compiler.

sqrt is supported. 
Please do not compare in the following way
**std::cout << "The result is incorrect for element: " << I
                  << " , expected: " << sqrt(1.0f * I) << " , got: " << HostAccessor[I]
                  << std::endl;**

**Comment by pvelesko** [comment]
The issue persists with 6788713cc0469af65963c3948f66354fce28af1e

**Comment by pvelesko** [comment]
I didn't update my modulefiles and tested old version. Issue resolved with new patch.

**Comment by christgau** [comment]
I can confirm that the error is gone now. Programs compile and run fine now.

@jinz2014 sure the reproducer was/is not the best, but illustrated the main issue discussed here.
