### ISSUE TITLE
[CUDA] matrix multiplication

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#1354]
Can you please run the attached sycl example to double check the output ?

Thanks

Problem size: c(150,600) = a(150,300) * b(300,600)
fail - The result is incorrect for element: [0, 0], expected: 45150 , but got: 45012
fail - The result is incorrect for element: [0, 1], expected: 45150 , but got: 45012
fail - The result is incorrect for element: [0, 2], expected: 45150 , but got: 45012
fail - The result is incorrect for element: [0, 3], expected: 45150 , but got: 45012
fail - The result is incorrect for element: [0, 4], expected: 45150 , but got: 45012
fail - The results mis-match!

[matrix_mul_dpcpp.txt](https://github.com/intel/llvm/files/4357254/matrix_mul_dpcpp.txt)

**Comment by fwyzard** [comment]
I get the correct results using dpcpp from Intel oneAPI beta 5:
```bash
$ dpcpp --version
Intel(R) oneAPI DPC++ Compiler 2021.1-beta05 (2020.2.0.0304)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/inteloneapi/compiler/latest/linux/bin

$ dpcpp -O2 -g -x c++ -fsycl matrix_mul_dpcpp.txt -o matrix_mul_dpcpp

$ ./matrix_mul_dpcpp 
Device: Intel(R) Gen9 HD Graphics NEO
Problem size: c(150,600) = a(150,300) * b(300,600)
success - The results are correct!
```

**Comment by jinz2014** [comment]
I am sorry for missing the information. Please check it using SYCL for CUDA.

**Comment by hiaselhans** [comment]
i did test on cuda and had the same result as you. however changing the problem size to 1024 gave correct results
```
Problem size: c(128,512) = a(128,256) * b(256,512)
success - The results are correct!
```

maybe the issue is related to #1388 ?

**Comment by hiaselhans** [comment]
actually it does work well for problem sizes N*64.
@jinz2014 can you confirm that?

**Comment by jinz2014** [comment]
Sorry, I would not open the issue if I just ran the test with your problem sizes.

**Comment by hiaselhans** [comment]
> Sorry, I would not open the issue if I just ran the test with your problem sizes.

Sorry, i don't get it. What do you mean to say?

**Comment by jinz2014** [comment]
I will keep the issue open.

**Comment by hiaselhans** [comment]
> I will keep the issue open.

Of course.
In fact i was just asking you to verify in your environment that the matrix multiplication seems to work for a problem size of a multiple of 64.
This in turn could be helpful to find the root of your issue, which - i suppose - you'd like to see fixed after all...

**Comment by jinz2014** [comment]
I verified.

#define SIZE     1200   // Must be a multiple of 8.

When the SIZE is 32, 256, or 1024, the result is correct.

**Comment by bader** [comment]
@jinz2014, the attached sample works with the toolchain built from ca8b94ec5ef6844d10cf85bf279b7a7da8e3197b.

>  SYCL_BE=PI_CUDA /tmp/test
> 
> WARNING: The legacy environment variables SYCL_BE and SYCL_DEVICE_TYPE are deprecated. Please use SYCL_DEVICE_FILTER instead. For details, please refer to https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md
> 
> Device: TITAN RTX
> Problem size: c(150,600) = a(150,300) * b(300,600)
> success - The results are correct!
