### ISSUE TITLE
sycl-cts/accessor & sycl-cts/hierarchical fail in Nightly

### ISSUE THREAD

**Issue by KornevNikita** [intel/llvm#13574]
### Describe the bug

See: https://github.com/intel/llvm/actions/runs/8842488516/job/24281474191
- test_accessor - caused by a36e9f8969a5ad4346f84c925aa89e1a00128b7f. Probably the test uses the deprecated api.
**UPD.** Turning on in https://github.com/intel/llvm/pull/14159
- test_hierarchical fails with the new oclcpurt (2024.17.3.0.09_160000). It was turned off until yesterday so we didn't catch it earlier. Requires the next oclcpurt uplift.

**Comment by coldav** [comment]
Is this likely to be looked at any time soon? @aelovikov-intel  @KornevNikita

**Comment by aelovikov-intel** [comment]
I'm not looking into it currently. @KornevNikita , what about you?

**Comment by KornevNikita** [comment]
> I'm not looking into it currently. @KornevNikita , what about you?

@coldav I'll try to update `test_accessor` this or the next week, so it should pass.
But since we need a new oclcpurt for `test_hierarchical` as I understand - it would take a long time, as we updating it only once every ~4 months.

**Comment by KornevNikita** [comment]
This small PR should fix the `test_accessor` https://github.com/KhronosGroup/SYCL-CTS/pull/895.

**Comment by KornevNikita** [comment]
test_hierarchical still fails with new CPU RT

**Comment by KornevNikita** [comment]
https://github.com/intel/llvm/pull/16246
