### ISSUE TITLE
[SYCL] Code not using virtual functions relies on function pointers

### ISSUE THREAD

**Issue by bader** [intel/llvm#1361]
While I was reviewing https://github.com/intel/llvm/pull/1295, I realized that the compiler emits the code relying on function pointer extension support even when it's not supposed to.

Here is a short example ([godbolt link](https://godbolt.org/z/V-8MFp)):
```c++
struct A {                                       
  virtual void foo() {}                           
};                                                 
                                                   
struct B : A { 
  int x;                               
  int bar() { return x; }
};                                                 
                                                   
__attribute__((sycl_device)) void baz() {          
  B b;                                          
  int a = b.bar();
}  
```

Even though foo function doesn't use virtual functions, the produced code still initializes A::vtable, which type uses function pointer.
This can't be translated into standard SPIR-V format, which do not support function pointers.

@erichkeane, @Fznamznon, any thought on how to lower this case into standard SPIR-V?

**Comment by erichkeane** [comment]
When we did the implementation that allowed type 'A' here, I think the idea was that the translator would simply ignore the vtable in this case and not bother emitting it.

**Comment by bader** [comment]
AFAIK, it's a bit different. 
SPIR-V translator relies on clang to prohibit unsupported features, so they are not expected in LLVM IR. SPIR-V translator translates as much as it can and for add "Capabilities" to the final code, so 

For instance, if images are used in the LLVM IR, SPIR-V translator adds `ImageBasic` capability. Translator can't be configured to ignore/remove images from the LLVM IR, only clang can.
The same way they handle all OpenCL extensions and optional features.

On top of that, we can't always ignore function pointers as there is an extension which allows this feature.

Do you think we can add LLVM pass to clang to clean-up LLVM IR if function pointer support is not enabled?
