### ISSUE TITLE
"libsycl-fallback-cassert.spv" not found

### ISSUE THREAD

**Issue by hiaselhans** [intel/llvm#1367]
```
terminate called after throwing an instance of 'cl::sycl::compile_program_error'
  what():  Failed to load libsycl-fallback-cassert.spv -30 (CL_INVALID_VALUE)
```

i can't find the libsycl-fallback-cassert.spv in build/lib

i tried adding `libdevice` to `DLLVM_EXTERNAL_PROJECTS` and set `DLLVM_EXTERNAL_LIBDEVICE_SOURCE_DIR` as in #1276 but still can't find anything. what else do i need to build these files? it worked a few weeks back but now following the path in getting started doesn't work for me.

**Comment by bader** [comment]
> i tried adding `libdevice` to `DLLVM_EXTERNAL_PROJECTS` and set `DLLVM_EXTERNAL_LIBDEVICE_SOURCE_DIR` as in #1276 but still can't find anything. what else do i need to build these files?

You need to add `libdevice` to `LLVM_ENABLE_PROJECTS` variable.
The easiest way to configure CMake is to use https://github.com/intel/llvm/blob/sycl/buildbot/configure.py script.

**Comment by hiaselhans** [comment]
thanks for the quick answer! i used that script but only updated external_projects.

**Comment by hiaselhans** [comment]
i will compile, verify and close the issue.
and probably send a PR for gettingstarted
