### ISSUE TITLE
Build failure in macOs post-commit job

### ISSUE THREAD

**Issue by uditagarwal97** [intel/llvm#13728]
### Describe the bug

Example: https://github.com/intel/llvm/actions/runs/9015105018/job/24769084462
```
In file included from /Users/runner/work/llvm/llvm/src/sycl-fusion/common/lib/NDRangesHelper.cpp:9:
In file included from /Users/runner/work/llvm/llvm/src/sycl-fusion/common/lib/NDRangesHelper.h:12:
/Users/runner/work/llvm/llvm/src/sycl-fusion/common/include/Kernel.h:13:10: fatal error: 'sycl/detail/string.hpp' file not found
#include "sycl/detail/string.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[2251/3301] Copying clang's stdalign.h...
```

Failure first seen after: https://github.com/intel/llvm/pull/13701

### To reproduce

DPC++ commit: [b6a6f53](https://github.com/intel/llvm/commit/b6a6f53ffa4e1b8e272a0f9c2172ec13e14fa7c0)

### Environment

OS: macOS

**Comment by uditagarwal97** [comment]
@victor-eds FYI!

**Comment by victor-eds** [comment]
#13740 should fix this. `-I/Users/runner/work/llvm/llvm/build/include` is part of the failing build command, so the missing header should be included.

**Comment by victor-eds** [comment]
I'm leaving on holidays. @jopperm is the new assignee in case #13740 does not fix this.

**Comment by uditagarwal97** [comment]
Closing this issue as #13740 fixes this issue.
