### ISSUE TITLE
[sycl cts][OpenCL][spirv] Multiple SYCL CTS tests now fail to build using OpenCL backend

### ISSUE THREAD

**Issue by coldav** [intel/llvm#13722]
### Describe the bug

Multiple sycl cts tests fail to build with the error :` InvalidBitWidth: Invalid bit width in input:`. These tests include:
`
test_group_functions
test_vector_api
test_reduction
test_vector_swizzles
`
This was shown on https://github.com/codeplaysoftware/oneapi-construction-kit, host target as the OpenCL, (opencl:cpu), but I think it highly likely this would show up for any OpenCL implementation.

### To reproduce

git clone git@github.com:codeplaysoftware/oneapi-construction-kit.git
cd oneapi-construction-kit
export ONEAPI_CON_KIT_INSTALL_DIR=$PWD/build/install

cmake -Bbuild -DCA_LLVM_INSTALL_DIR=$LLVM_INSTALL_DIR -DCA_ENABLE_API=cl -DCMAKE_INSTALL_PREFIX=$ONEAPI_CON_KIT_INSTALL_DIR $PWD
cd build
make -j8 install
cd ../..

Build SYCL CTS as normal. Set export ONEAPI_DEVICE_SELECTOR=opencl:cpu (or whatever works on your system to select it).

**Comment by KornevNikita** [comment]
Hi @coldav, I also see this problem in our CI 3 days ago, but now it's gone. Could you please check if the issue really gone?
