### ISSUE TITLE
[CI] Linux post-commit build failure

### ISSUE THREAD

**Issue by uditagarwal97** [intel/llvm#13768]
### Describe the bug

Run: https://github.com/intel/llvm/actions/runs/9058914532/job/24885436139

The issue seems to be with the Docker container.

```
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
-- Check for working CXX compiler: /opt/sycl/bin/clang++ - broken
  The C++ compiler

    "/opt/sycl/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /__w/llvm/llvm/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_d1aa5 && [1/2] Building CXX object CMakeFiles/cmTC_d1aa5.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_d1aa5
    FAILED: cmTC_d1aa5 
    : && /opt/sycl/bin/clang++   CMakeFiles/cmTC_d1aa5.dir/testCXXCompiler.cxx.o -o cmTC_d1aa5   && :
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:[45](https://github.com/intel/llvm/actions/runs/9058914532/job/24885436139#step:7:46) (project)
```

### Environment

OS: Linux
DPC++ commit: b11a19b1896cc2f7ab43735aacf265182e22832c

**Comment by uditagarwal97** [comment]
@JackAKirk Could this be related to https://github.com/intel/llvm/pull/13752?

**Comment by JackAKirk** [comment]
> @JackAKirk Could this be related to #13752?

I think so, it seems that the post-commit uses the nightly image. Although I don't understand why it didn't occur here: https://github.com/intel/llvm/actions/runs/9056583535
Here is a temporary fix https://github.com/intel/llvm/pull/13769

AMD recently added a new apt package for rocm 6.1.1. I'll see if that works without the libstdc++-12-dev package...

**Comment by KornevNikita** [comment]
@uditagarwal97 @JackAKirk I guess it can be closed?
