### ISSUE TITLE
Allowed work group sizes in SYCL - CUDA backend

### ISSUE THREAD

**Issue by mfbalin** [intel/llvm#1388]
Hello,

I am writing SPMM code to do sparse matrix with dense matrix multiplication and I am trying to use the local memory while doing that. I have been using the CUDA backend so far and have been having trouble with the work-group sizes. CUDA doesn't seem to handle work-group sizes other than 1024 well, the code crashes with error messages as provided below. Do you have any tips on this?

[Click for code](https://paste.ubuntu.com/p/FRv7M24S7n/)

In the code, please take a look at the spmm function.

```
PI CUDA ERROR:
        Value:           1
        Name:            CUDA_ERROR_INVALID_VALUE
        Description:     invalid argument
        Function:        cuda_piEnqueueKernelLaunch
        Source Location: /home/mbalin3/sycl_workspace/llvm/sycl/plugins/cuda/pi_cuda.cpp:2097


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        commonEnqueueMemBufferCopyRect
        Source Location: /home/mbalin3/sycl_workspace/llvm/sycl/plugins/cuda/pi_cuda.cpp:2781


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        enqueueEventWait
        Source Location: /home/mbalin3/sycl_workspace/llvm/sycl/plugins/cuda/pi_cuda.cpp:289


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        _pi_event
        Source Location: /home/mbalin3/sycl_workspace/llvm/sycl/plugins/cuda/pi_cuda.cpp:114

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
Aborted (core dumped)
```

**Comment by mfbalin** [comment]
https://en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

In this link, in the large table of Technical specifications vs Compute Capability, "Maximum x-dimension of a grid of thread blocks" is specified as 2^31 - 1 where as "Maximum y-, or z-dimension of a grid of thread blocks" is specified as 65536. I noticed that when I give a 2d range where the first dimension is large and the second dimension is small, it maps this range onto the y and z dimensions leaving the x dimension as 1. Since the only dimension whose limits are sufficiently large is the x dimension, the "cuda_piEnqueueKernelLaunch" function in pi_cuda.hpp gives CUDA_ERROR_INVALID_VALUE. Thus, I think the problem could be fixed if a 2d range would map onto the x and y dimensions instead of y and z dimensions, which I am guessing what is currently happening. What do you think?

**Comment by bader** [comment]
There is a good article clarifying the motivation behind current mapping: https://codeplay.com/portal/11-18-19-computecpp-v1-1-6-changes-to-work-item-mapping-optimization

Another option is to change to order of indices in the application. Right?

**Comment by mfbalin** [comment]
I understand that we want sequential access to memory, and the innermost index is always the index that accesses the underlying memory sequentially. However the problem is not about transposing the index space. The problem is that given a 2d nd range whose dimensions are i and j, this maps onto y and z dimensions in the CUDA backend. What should happen is that when a 2d range is given, i and j should map to x and z while the size of the y dimension is initialized to 1 because x has larger grid size than y.
