### ISSUE TITLE
float atomics

### ISSUE THREAD

**Issue by hiaselhans** [intel/llvm#1410]
I have a real-world problem where float atomic_adds would greatly simplify the process and reduce kernel calls. Cuda comes with atomic_floats and this is somewhat documented in the sycl reference.

So i tried to set up a small example, compile and run with the cuda backend.
I found that in [atomic.hpp](https://github.com/intel/llvm/blob/c98559b7a870132c5fd26e2ffc81a2b639213b2f/sycl/include/CL/sycl/atomic.hpp#L22) there is an assert to prevent atomic's from being floats and i found in the spir-v specs that:
`Atomic instructions must declare a scalar 32-bit integer type, or a scalar 64-bit integer type if the Int64Atomics capability is enabled, for the value pointed to by Pointer.`

So - due to the lack of float atomics in the spir-v spec - is there a plan to support float atomics in sycl/dpc++ in the future?

**Comment by AlexeySachkov** [comment]
Hi @hiaselhans, 

Basically that assertion is enforced by the SYCL spec.

SPIR-V also don't have support for such atomics, but the translator we are using is capable to translate these functions somehow into undocumented, non-conformant with the spec, OpenCL built-ins which should even work on Intel CPU & GPU (again, this is unfortunately undocumented, so, no guarantees so far).

> is there a plan to support float atomics in sycl/dpc++ in the future?

Yes, definitely, please take a look at [ExtendedAtomics](https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions/ExtendedAtomics) proposal (note: it is not yet implemented).

**Comment by hiaselhans** [comment]
thanks @AlexeySachkov !
