### ISSUE TITLE
Build DPC++ toolchain failed on windows10

### ISSUE THREAD

**Issue by crocodiletongue** [intel/llvm#1426]
I tried to build intel sycl on Windows10 (64-bit) machine but an unexpectable  "ninja error" appears and building failed. I cannot understand the cause and solve.

Does anyone have an idea ?  

```
python %DPCPP_HOME%\llvm\buildbot\compile.py -s %DPCPP_HOME%\llvm -o %DPCPP_HOME%\build

args:Namespace(base_branch=None, branch=None, build_number=None, builder_dir=None, obj_dir='C:\\usr\\sycl_workspace\\build', pr_number=None, src_dir='C:\\usr\\sycl_workspace\\llvm')
['ninja', '-j', '12', 'deploy-sycl-toolchain', 'deploy-opencl-aot']
ninja: error: 'OpenCL-Headers', needed by 'tools/sycl/CMakeFiles/ocl-headers', missing and no known rule to make it
Traceback (most recent call last):
  File "C:\usr\sycl_workspace\llvm\buildbot\compile.py", line 43, in <module>
    ret = main()
  File "C:\usr\sycl_workspace\llvm\buildbot\compile.py", line 39, in main
    return do_compile(args)
  File "C:\usr\sycl_workspace\llvm\buildbot\compile.py", line 17, in do_compile
    subprocess.check_call(make_cmd, cwd=args.obj_dir)
  File "C:\Users\k-ojima.ESOL\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-j', '12', 'deploy-sycl-toolchain', 'deploy-opencl-aot']' returned non-zero exit status 1.
```

**Comment by hiaselhans** [comment]
did you try configure.py with `--no-ocl` ?

**Comment by crocodiletongue** [comment]
> did you try configure.py with `--no-ocl` ?

Thank you. I tried it then the compliation proceeded but get error in the middle.

```
[2340/2478] Building CXX object tools\sycl\source\CMakeFiles\sycld.dir\detail\builtins_relational.cpp.obj
Alignment of class vec is not in accordance with SYCL specification requirements, a limitation of the MSVC compiler(Error C2719).Applied default alignment.
ninja: build stopped: subcommand failed.
```

sycl/types.hpp seems to output the error when _WIN32 is defined. I wonder why this micro is defined although I use x64 Native Tools Command Prompt for VS 2019.

```
#if defined(_WIN32) && (_MSC_VER)
// MSVC Compiler doesn't allow using of function arguments with alignment
// requirements. MSVC Compiler Error C2719: 'parameter': formal parameter with
// __declspec(align('#')) won't be aligned. The align __declspec modifier
// is not permitted on function parameters. Function parameter alignment
// is controlled by the calling convention used.
// For more information, see Calling Conventions
// (https://docs.microsoft.com/en-us/cpp/cpp/calling-conventions).
// For information on calling conventions for x64 processors, see
// Calling Convention
// (https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention).
#pragma message ("Alignment of class vec is not in accordance with SYCL \
specification requirements, a limitation of the MSVC compiler(Error C2719).\
Applied default alignment.")
```

**Comment by hiaselhans** [comment]
but how would that make the compiler fail...? it's a pragma message.
i don't think they are even treated as warnings but could you try to set `DSYCL_ENABLE_WERROR=OFF` in configure.py?

according to [MS docs](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?redirectedfrom=MSDN&view=vs-2019) `_WIN32` is supposed to be true...

`_WIN32 Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.`

**Comment by bader** [comment]
Right. I see similar messages in successful CI builds. E.g. http://ci.llvm.intel.com:8010/#/builders/18/builds/1206/steps/9/logs/stdio.
This should be break the build.

**Comment by crocodiletongue** [comment]
Hi all 

Thank you for your reply.

I changed the buiId command according to GetStartedGuide.md includes the following release package, and the compilation finished properly even though the error messages still remain.

https://github.com/intel/llvm/releases/tag/20200331

```
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" ^
-DLLVM_EXTERNAL_PROJECTS="llvm-spirv;sycl" ^
-DLLVM_ENABLE_PROJECTS="clang;llvm-spirv;sycl" ^
-DLLVM_EXTERNAL_SYCL_SOURCE_DIR="%DPCPP_HOME%\llvm\sycl" ^
-DLLVM_EXTERNAL_LLVM_SPIRV_SOURCE_DIR="%DPCPP_HOME%\llvm\llvm-spirv" ^
-DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ^
"%DPCPP_HOME%\llvm\llvm"

ninja sycl-toolchain
```

**Comment by hiaselhans** [comment]
i think this can be closed @bader @crocodiletongue ?

**Comment by crocodiletongue** [comment]
I'm OK because I solved the problem with another way, but I think compile.py still has any problems.

python %DPCPP_HOME%\llvm\buildbot\compile.py -s %DPCPP_HOME%\llvm -o %DPCPP_HOME%\build

**Comment by bader** [comment]
@crocodiletongue, could you share what problems do you have and what commands do you run, please?
We regularly build DPC++ toolchain on Windows and there are should be no issues.

**Comment by hiaselhans** [comment]
i don't see a lot of differences between `compile.py` and manual commant, but it runs `ninja -j nproc sycl-toolchain`.
Memory could be a problem? :)
