### ISSUE TITLE
SPIR-V built-ins declarations rejected by the SYCL device compiler

### ISSUE THREAD

**Issue by bader** [intel/llvm#1429]
@Naghasan, I have problem with building libdevice library with my version of the SYCL compiler. "My version" includes improved "deferred diagnostics" patch from https://reviews.llvm.org/D70172, which seems to enable diagnostics https://github.com/intel/llvm/pull/1026 for the TableGen-emitted declarations. There seems to be a bug in existing implementation.

Am I right that SPIR-V built-ins are emitted w/o `sycl_device` attribute? If so, the SYCL device compiler is supposed to emit an error for declaration w/o definition and not explicitly annotated with `SYCL_EXTERNAL` macro (aka `sycl_device` attribute). NOTE: original header replaced by TableGen file included required annotations.

Can we add `sycl_device` attribute to SPIR-V built-ins if `-fsycl-is-device` language option is set?
Any other ideas how to fix libdevice build?
Let me know if you want me to share the compiler with fixed deferred diagnostics.

Tagging @s-kanaev, @erichkeane, @Fznamznon.

**Comment by Naghasan** [comment]
> Am I right that SPIR-V built-ins are emitted w/o sycl_device attribute?

No they are emitted with this attribute ([set here](https://github.com/intel/llvm/blob/sycl/clang/lib/Sema/SemaLookup.cpp#L912)), that would trigger SYCL diagnostics otherwise.

> Can we add sycl_device attribute to SPIR-V built-ins if -fsycl-is-device language option is set?

This should be check regardless I guess, I'll make a PR.

**Comment by bader** [comment]
I think I found the problem. The attribute set by clang is "implicit", where as original code was explicit.
Diagnostics is emitted because implicit attribute is added by clang during "device code traversal".

There are two ways to fix this problem:
1. Emit explicit attribute for SPIR-V built-ins.
2. @Fznamznon, I think you recently change the way clang emits device code and I think we don't add implicit attribute any more, right? If so, we can consider updating the diagnostics and remove "explicit attribute" requirement from [here](https://github.com/intel/llvm/blob/sycl/clang/lib/Sema/SemaSYCL.cpp#L1455).

**Comment by vladimirlaz** [comment]
@bader , @Fznamznon I faced the same issue during LLVM pulldown to intel/llvm and tried option 2 mentioned in Alexey's comment (https://github.com/otcshare/llvm/pull/1033/commits/061a2c6947fb41212c49aa74df49dd13af1b1199). It helps!!

**Comment by Fznamznon** [comment]
> @Fznamznon, I think you recently change the way clang emits device code and I think we don't add implicit attribute any more, right? If so, we can consider updating the diagnostics and remove "explicit attribute" requirement from here.

Right, implicit `sycl_device` attribute is not needed for all the functions to emit them in device code anymore. There are two places where I left adding it implicitly: 
- Applying `indirectly_callable` to a function https://github.com/intel/llvm/blob/d15de0bc493a323952f16aa9ba92605097aacf11/clang/lib/Sema/SemaDeclAttr.cpp#L4463 . I think we can safely remove it if we extend this condition https://github.com/intel/llvm/blob/d15de0bc493a323952f16aa9ba92605097aacf11/clang/lib/AST/ASTContext.cpp#L10194 by adding check for `indirectly_callable` attribute here (because `indirectly_callable` is supposed to force emitting of function like `SYCL_EXTERNAL`).
- Adding this attribute to generated OpenCL function https://github.com/intel/llvm/blob/d15de0bc493a323952f16aa9ba92605097aacf11/clang/lib/Sema/SemaSYCL.cpp#L1223 . I think I just missed it and it can be safely removed.

I can prepare a patch if you want.

**Comment by bader** [comment]
@Fznamznon, I don't think we should change the code for indirectly callable or SYCL kernel functions.
Your analysis shows that we should definitely lift the restriction on explicit attribute. 
If I understand it correctly, forward declaration annotated with `[[indirectly_callable]]` might still cause the error.

It seems to me that the right thing to do is to remove this line: https://github.com/intel/llvm/blob/sycl/clang/lib/Sema/SemaSYCL.cpp#L1455 and assume that even attribute is added implicitly to forward declaration, it's not a bug and compiler guarantees that function is available on the device.

Does it make sense to you?

**Comment by Fznamznon** [comment]
> @Fznamznon, I don't think we should change the code for indirectly callable or SYCL kernel functions.
> Your analysis shows that we should definitely lift the restriction on explicit attribute.
> If I understand it correctly, forward declaration annotated with `[[indirectly_callable]]` might still cause the error.
> 
> It seems to me that the right thing to do is to remove this line: https://github.com/intel/llvm/blob/sycl/clang/lib/Sema/SemaSYCL.cpp#L1455 and assume that even attribute is added implicitly to forward declaration, it's not a bug and compiler guarantees that function is available on the device.
> 
> Does it make sense to you?

Okay. But I don't see the point in adding `sycl_device` attribute to generated OpenCL kernel. This is not needed for device code outlining anymore and it shouldn't affect any diagnostics.

**Comment by bader** [comment]
> But I don't see the point in adding `sycl_device` attribute to generated OpenCL kernel. This is not needed for device code outlining anymore and it shouldn't affect any diagnostics.

Right.

**Comment by vladimirlaz** [comment]
@bader, yes until corresponding check is not submitted earlier
