### ISSUE TITLE
sycl/test-e2e/Regression/local-arg-align.cpp fails on Gen12

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#14297]
### Describe the bug

The test sycl/test-e2e/Regression/local-arg-align.cpp fails with
```
Error: incorrect alignment for argument b, required alignment: 16, address: 4000000010000004
```
on Gen12 GPU.

**Comment by bader** [comment]
@steffenlarsen, we already have issue for that fail - https://github.com/intel/llvm/issues/10682.

**Comment by steffenlarsen** [comment]
> @steffenlarsen, we already have issue for that fail - #10682.

@bader - I think we can close that one with https://github.com/intel/llvm/pull/13695 since it focuses on opaque pointers. The failure reported here seems to be Gen12 specific and actually relating to alignment

**Comment by bader** [comment]
No. It's related to opaque pointers support. GPU compiler doesn't handle opaque pointers with Alignment decoration correctly. This is a duplicate of #10682, which is not fully covered by #13695.

**Comment by steffenlarsen** [comment]
Ah, good to know. Thank you for clarifying. Closing this in favor of https://github.com/intel/llvm/issues/10682.
