### ISSUE TITLE
[SYCL] Test SYCL :: ESIMD/hardware_dispatch.cpp is failing on windows CI

### ISSUE THREAD

**Issue by lbushi25** [intel/llvm#14336]
### Describe the bug

The test SYCL :: ESIMD/hardware_dispatch.cpp is failing on Windows pre-commit CI.
Upon resolution, please remove the XFAIL from the test source.

### To reproduce

`clang++ -fsycl -fsycl-targets=intel_gpu_bdw hardware_dispatch.cpp  -Xs "-options -vc-codegen" -o hardware_dispatch_test
hardware_dispatch_test.exe`

### Environment

- OS: Windows

**Comment by sarnex** [comment]
@lbushi25 Can you send me a precommit CI run that shows the failure? Thanks

**Comment by lbushi25** [comment]
> @lbushi25 Can you send me a precommit CI run that shows the failure? Thanks

Hi @sarnex , I'm on it. Expect an update soon!

**Comment by lbushi25** [comment]
I've submitted a draft PR [here|https://github.com/intel/llvm/pull/14354] where I have removed all XFAIL comments from E2E tests to get an accurate summary of the failures. This is part of an ongoing effort to make sure that every XFAIL is documented with a GH issue linked in the test source.

**Comment by lbushi25** [comment]
> @lbushi25 Can you send me a precommit CI run that shows the failure? Thanks

The CI run: https://github.com/intel/llvm/pull/14354/checks
The E2E runs specifically have not started yet so I would check later/on Monday given how slow the CI runners have been to pick up jobs these last couple of days.

**Comment by sarnex** [comment]
Thanks, I'll take a look

**Comment by sarnex** [comment]
We need to use `tgllp` instead of `bdw` on Windows because the Windows driver doesn't support `bdw` anymore, but then we need the changes in https://github.com/intel/llvm/pull/14188, so waiting for that.
