### ISSUE TITLE
Tests hanging on Windows

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#14397]
### Describe the bug

The hang causes all jobs after to fail because the install dir can't be deleted, we need to disable these ASAP.

Timed Out Tests (3):
  SYCL :: BFloat16/bfloat16_vec.cpp
  SYCL :: Basic/stream/stream.cpp
  SYCL :: Complex/sycl_complex_stream_test.cpp

https://github.com/intel/llvm/actions/runs/9763792395/job/26955308516?pr=14388

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

### Environment

- OS: [e.g Windows/Linux]
- Target device and vendor: [e.g. Intel GPU]
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g. the output of `sycl-ls --verbose`]

**Comment by sarnex** [comment]
Talked to @KseniyaTikhomirova, these could possibly be related to her changes. She will do an initial investigation to see if it's related.

**Comment by KseniyaTikhomirova** [comment]
probably this could fix the hang https://github.com/intel/llvm/pull/14396, will check tomorrow and reenable back

**Comment by sarnex** [comment]
We are not seeing this anymore so closed as fixed with https://github.com/intel/llvm/pull/14396
