### ISSUE TITLE
Assertion `isValid(Attr)' for newly added RuntimeAligned.spt

### ISSUE THREAD

**Issue by jsji** [intel/llvm#14427]
### Describe the bug

Newly added RuntimeAligned.spt asserting in pulldown testing. https://github.com/intel/llvm/pull/14327

### To reproduce

> bin/llvm-spirv -spirv-text -r /iusers/jinsongj/llvmspirpd/llvm/llvm-spirv/test/extensions/INTEL/SPV_INTEL_runtime_aligned/RuntimeAligned.spt
> llvm-spirv: /iusers/jinsongj/sycl-web/llvm/llvm-spirv/lib/SPIRV/libSPIRV/SPIRVFunction.cpp:64: void SPIRV::SPIRVFunctionParameter::foreachAttr(std::function<void(spv::FunctionParameterAttribute)>): Assertion `isValid(Attr)' failed.
> PLEASE submit a bug report to https://github.com/intel/llvm/issues and include the crash backtrace.
> Stack dump:
> 0.      Program arguments: bin/llvm-spirv -spirv-text -r /iusers/jinsongj/llvmspirpd/llvm/llvm-spirv/test/extensions/INTEL/SPV_INTEL_runtime_aligned/RuntimeAligned.spt
>  #0 0x00007f60f45cdd00 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/iusers/jinsongj/sycl-web/llvm/build/lib/libLLVMSupport.so.19.0git+0x1dcd00)
>  #1 0x00007f60f45cb11f llvm::sys::RunSignalHandlers() (/iusers/jinsongj/sycl-web/llvm/build/lib/libLLVMSupport.so.19.0git+0x1da11f)
>  #2 0x00007f60f45cb275 SignalHandler(int) Signals.cpp:0:0
>  #3 0x00007f60f3fd4520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
>  #4 0x00007f60f40289fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
>  #5 0x00007f60f40289fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
>  #6 0x00007f60f40289fc pthread_kill ./nptl/pthread_kill.c:89:10
>  #7 0x00007f60f3fd4476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
>  #8 0x00007f60f3fba7f3 abort ./stdlib/abort.c:81:7
>  #9 0x00007f60f3fba71b _nl_load_domain ./intl/loadmsgcat.c:1177:9
> #10 0x00007f60f3fcbe96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
> #11 0x00007f60f51101e3 SPIRV::SPIRVFunctionParameter::foreachAttr(std::function<void (spv::FunctionParameterAttribute)>) (/iusers/jinsongj/sycl-web/llvm/build/lib/libLLVMSPIRVLib.so.19.0git+0x3871e3)
> #12 0x00007f60f4f8ac72 SPIRV::SPIRVToLLVM::transFunction(SPIRV::SPIRVFunction*) (/iusers/jinsongj/sycl-web/llvm/build/lib/libLLVMSPIRVLib.so.19.0git+0x201c72)
> #13 0x00007f60f4f8c31a SPIRV::SPIRVToLLVM::translate() (/iusers/jinsongj/sycl-web/llvm/build/lib/libLLVMSPIRVLib.so.19.0git+0x20331a)
> #14 0x00007f60f4f97516 llvm::convertSpirvToLLVM(llvm::LLVMContext&, SPIRV::SPIRVModule&, SPIRV::TranslatorOpts const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) (/iusers/jinsongj/sycl-web/llvm/build/lib/libLLVMSPIRVLib.so.19.0git+0x20e516)
> #15 0x00007f60f4f987b1 llvm::readSpirv(llvm::LLVMContext&, SPIRV::TranslatorOpts const&, std::istream&, llvm::Module*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) (/iusers/jinsongj/sycl-web/llvm/build/lib/libLLVMSPIRVLib.so.19.0git+0x20f7b1)
> #16 0x0000563ed02f56d2 convertSPIRVToLLVM(SPIRV::TranslatorOpts const&) llvm-spirv.cpp:0:0
> #17 0x0000563ed02e9b3f main (bin/llvm-spirv+0xab3f)
> #18 0x00007f60f3fbbd90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
> #19 0x00007f60f3fbbe40 call_init ./csu/../csu/libc-start.c:128:20
> #20 0x00007f60f3fbbe40 __libc_start_main ./csu/../csu/libc-start.c:379:5
> #21 0x0000563ed02ea645 _start (bin/llvm-spirv+0xb645)
> Aborted (core dumped)
>

**Comment by jsji** [comment]
@intel/dpcpp-spirv-reviewers FYI.

**Comment by vmaksimo** [comment]
@jsji please apply the fix attached - there was a problem with the conflict resolution which caused assertion failure.
[0001-Fix-conflict-resolution-for-SPV_INTEL_runtime_aligne.patch](https://github.com/user-attachments/files/16097141/0001-Fix-conflict-resolution-for-SPV_INTEL_runtime_aligne.patch)

**Comment by jsji** [comment]
> @jsji please apply the fix attached - there was a problem with the conflict resolution which caused assertion failure. [0001-Fix-conflict-resolution-for-SPV_INTEL_runtime_aligne.patch](https://github.com/user-attachments/files/16097141/0001-Fix-conflict-resolution-for-SPV_INTEL_runtime_aligne.patch)

Thanks @vmaksimo !

**Comment by vmaksimo** [comment]
Fix was merged, closing the issue
