### ISSUE TITLE
Dead Linux and Windows links to CPU OpenCL runtime in February'20 release notes

### ISSUE THREAD

**Issue by bjoernknafla** [intel/llvm#1443]
The [February'20 release notes ](https://github.com/intel/llvm/blob/sycl/sycl/ReleaseNotes.md#february20-release-notes) mention Linux [prerequisites](https://github.com/intel/llvm/blob/sycl/sycl/ReleaseNotes.md#linux) for the experimental Intel CPU Runtime for OpenCL whose link does not work:
* https://github.com/intel/llvm/releases/download/2020-02/oclcpuexp-2020.10.3.0.04_rel.tar.gz

The prerequisite section misses "Windows" as a sub-section header, and the listed Windows link for the CPU OpenCL runtime also does not work:
* https://github.com/intel/llvm/releases/download/2020-02/win-oclcpuexp-2020.10.3.0.04_rel.zip

In both cases the target URL page only shows "Not Found".

Where to download the Linux Intel CPU OpenCL runtime/drivers?

PS: I didn't check any other links in that document.

**Comment by electribald** [comment]
I have encountered the same issue.
The following links seem to be working:
https://github.com/intel/compute-runtime/releases/tag/20.06.15619
https://downloadcenter.intel.com/download/29426/Intel-Graphics-Windows-10-DCH-Drivers
But these are GPU related.

**Comment by romanovvlad** [comment]
Should be fixed soon.

**Comment by romanovvlad** [comment]
Should have been fixed. @bjoernknafla  Could you please confirm?

**Comment by bjoernknafla** [comment]
👍 Looks good to me! Thank you.
