### ISSUE TITLE
Failing `root_group` test when more than 1 work-group is launched.

### ISSUE THREAD

**Issue by GeorgeWeb** [intel/llvm#14462]
### Describe the bug

The [root_group](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/GroupAlgorithm/root_group.cpp) test fails when more than 1 work-group is launched because at the moment the [sycl::group_barrier(root_group)](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/GroupAlgorithm/root_group.cpp#L64) is not working correctly (synchronising cross-work-group) for Cuda. The work in-progress, so during that time the `root_group` will be `XFAIL`ed.

**Note:** Re-enable the test once the correct barrier implementation is in place.

### To reproduce

To reproduce, either increase the number of work-groups in the test or use the adapter changes in https://github.com/oneapi-src/unified-runtime/pull/1796 that will return more than 1 work-group from the [max_num_work_group_sync](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/GroupAlgorithm/root_group.cpp#L45) kernel-queue-specific info query.

### Environment

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: latest

### Additional context

This issue is used mostly for tracking, so we do not forget to re-enable the test.

**Comment by konradkusiak97** [comment]
This can be closed BTW. Here is the PR implementing the `root_group` barrier: https://github.com/intel/llvm/pull/14828
