### ISSUE TITLE
KernelFusion/sync_host_task.cpp timeout on OCL CPU

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#14496]
### Describe the bug

https://github.com/intel/llvm/actions/runs/9850284435/job/27195705652

```
TIMEOUT: SYCL :: KernelFusion/sync_host_task.cpp (2101 of 2101)
******************** TEST 'SYCL :: KernelFusion/sync_host_task.cpp' FAILED ********************
Exit Code: -9
Timeout: Reached timeout of 600 seconds

Command Output (stdout):
--
# RUN: at line 1
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/KernelFusion/sync_host_task.cpp -o /__w/llvm/llvm/build-e2e/KernelFusion/Output/sync_host_task.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/KernelFusion/sync_host_task.cpp -o /__w/llvm/llvm/build-e2e/KernelFusion/Output/sync_host_task.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 2
env SYCL_RT_WARNING_LEVEL=1 env ONEAPI_DEVICE_SELECTOR=opencl:cpu  /__w/llvm/llvm/build-e2e/KernelFusion/Output/sync_host_task.cpp.tmp.out 2>&1 | /__w/llvm/llvm/toolchain/bin/FileCheck /__w/llvm/llvm/llvm/sycl/test-e2e/KernelFusion/sync_host_task.cpp
# executed command: env SYCL_RT_WARNING_LEVEL=1 env ONEAPI_DEVICE_SELECTOR=opencl:cpu /__w/llvm/llvm/build-e2e/KernelFusion/Output/sync_host_task.cpp.tmp.out
# note: command had no output on stdout or stderr
# error: command failed with exit status: -9
# error: command reached timeout: True
# executed command: /__w/llvm/llvm/toolchain/bin/FileCheck /__w/llvm/llvm/llvm/sycl/test-e2e/KernelFusion/sync_host_task.cpp
# note: command had no output on stdout or stderr
# error: command failed with exit status: -9
# error: command reached timeout: True

```

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

### Environment

- OS: [e.g Windows/Linux]
- Target device and vendor: [e.g. Intel GPU]
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g. the output of `sycl-ls --verbose`]

**Comment by sommerlukas** [comment]
Thanks for flagging @sarnex!

Is there a way to see all commits merged between this nightly and the previous one?

**Comment by sarnex** [comment]
@sommerlukas Looks like this is it!

https://github.com/intel/llvm/compare/nightly-2024-07-08...nightly-2024-07-09

Also, it could be that it always could sporadically timeout and we just happened to hit it in this nightly but not specific commit caused it

**Comment by sarnex** [comment]
Closing for now, we don't think this is a real issue.
