### ISSUE TITLE
[CUDA] DeviceName may not contain NVIDIA

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#1459]
I found that DeviceName doesn't necessarily contain NVIDIA. Please double check.

class CUDASelector : public cl::sycl::device_selector {
  public:
    int operator()(const cl::sycl::device &Device) const override {
      using namespace cl::sycl::info;

      const std::string DeviceName = Device.get_info<device::name>();
      const std::string DeviceVendor = Device.get_info<device::vendor>();

      if (Device.is_gpu() && (DeviceName.find("NVIDIA") != std::string::npos)) {
        return 1;
      };
      return -1;
    }
};

**Comment by jinz2014** [comment]
I noticed some people changed DeviceName to DeviceVendor, but it was not reported. 

Thanks

**Comment by Ruyk** [comment]
The CUDA backend displays now "CUDA BACKEND" when PLATFORM VENDOR is queried. 
The "Device Vendor"  maps always to "NVIDIA Corporation", and "Device Name" queries maps to the value returned by `cuDeviceGetName`.

I think this issue can be closed now.
