### ISSUE TITLE
[CUDA] math functions support list

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#1461]
I think a table of math functions is needed for people to know which math functions are supported...

https://github.com/codeplaysoftware/computecpp-sdk/blob/master/samples/monte-carlo-pi.cpp
~/computecpp-sdk/samples$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice  monte-carlo-pi.cpp
ptxas fatal   : Unresolved extern function '_Z18__spirv_ocl_lengthDv2_f'

Add another one
ptxas fatal   : Unresolved extern function '_Z15__spirv_ocl_tanf'

**Comment by alexbatashev** [comment]
@Ruyk are all builtins listed on https://github.com/intel/llvm/blob/sycl/sycl/doc/cuda/cuda-vs-opencl-math-builtin-precisions.md supported by the backend?

**Comment by Ruyk** [comment]
Not yet, we are working on the full list, @Naghasan has the details

**Comment by Ruyk** [comment]
The complete working set of builtins required for SYCL 1.2.1 will be available in the next few weeks. Patches are being reviewed, check the libclc label (https://github.com/intel/llvm/pulls?q=is%3Apr+label%3Alibclc+)

**Comment by bader** [comment]
@jinz2014, most of the built-ins are implemented. Can we close this issue?

**Comment by jinz2014** [comment]
Though I am not a developer, I am interested to know where I can find the implementations. Thank you for pointing that out.

**Comment by bader** [comment]
These functions are implemented in libclc library.
Particularly `_Z15__spirv_ocl_tanf` definition should be added by https://github.com/intel/llvm/pull/1990 and `_Z18__spirv_ocl_lengthDv2_f` by https://github.com/intel/llvm/pull/1832.

You can find related PRs using the link provided by @Ruyk above.
