### ISSUE TITLE
Plugin/interop-opencl.cpp

### ISSUE THREAD

**Issue by RossBrunton** [intel/llvm#14661]

**Comment by RossBrunton** [comment]
Looks like it's in `sycl::make_context<backend::opencl>(ocl_context);`, where the device handles list is empty and thus results in a segfault in `urContextCreateWithNativeHandle`.

**Comment by omarahmed1111** [comment]
This will be fixed with this [PR](https://github.com/oneapi-src/unified-runtime/pull/1856) I think. As, the PR will change the device list to be optional.

**Comment by omarahmed1111** [comment]
It has another underneath fail, that is hiding after using the mentioned PR.
