### ISSUE TITLE
Basic/interop/construction_ocl.cpp

### ISSUE THREAD

**Issue by omarahmed1111** [intel/llvm#14665]

**Comment by omarahmed1111** [comment]
This will have half a fix with this PR: https://github.com/oneapi-src/unified-runtime/pull/1856 . The PR will fix a problem where the test will return `UR_RESULT_ERROR_INVALID_NULL_POINTER` as `urContextCreateWithNativeHandle` will be passed a null pointer `phDevices` and the PR will make this arg as optional, so will avoid making the validation layer returning an error code from that.

**Comment by omarahmed1111** [comment]
It have another failure that will also be fixed with this PR: https://github.com/oneapi-src/unified-runtime/pull/1791 merged.

**Comment by aarongreig** [comment]
seems to be fixed
