### ISSUE TITLE
KernelAndProgram/cache_env_vars.cpp

### ISSUE THREAD

**Issue by omarahmed1111** [intel/llvm#14709]

**Comment by aarongreig** [comment]
this one is still failing on windows

**Comment by omarahmed1111** [comment]
This was passing but the windows version of the test was failing `KernelAndProgram/cache_env_vars_win.cpp`. It had the same problem as other similar ones like `KernelAndProgram/cache_env_vars.cpp` where the check lines was testing for `urProgramBuild` when the test was using the new version of this entry-point `urProgramBuildExp`, so changing the check line to check for the new entry point would fix the test.
