### ISSUE TITLE
Two LLVM lit tests fail with BUILD_SHARED_LIBS flag set.

### ISSUE THREAD

**Issue by bader** [intel/llvm#1478]
Following tests are failing in post-commit job for the `sycl` branch.
```
Failing Tests (2):
    LLVM :: Other/cfg-printer-branch-weights.ll
    LLVM :: Other/cfg_deopt_unreach.ll
```
There are no obvious reasons why these tests might fail.

**Comment by AlexeySachkov** [comment]
@bader, I can't reproduce those failures locally - does it make sense to try and revert your patch? Is it possible to check `BUILD_SHARED_LIBS` configuration in pre-commit somehow?

**Comment by bader** [comment]
> does it make sense to try and revert your patch?

If by "your patch" you mean https://github.com/intel/llvm/commit/ff0b066b884cabbf34bafbd5b2a0da1ead9123e7 then yes.

> Is it possible to check `BUILD_SHARED_LIBS` configuration in pre-commit somehow?

You can add your pre-commit GitHub action workflow.
