### ISSUE TITLE
Questions about USM improvement

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#1484]
Could the developers explain Improved support for Unified Shared Memory (USM) pointers and Extension APIs to support USM version of device_ptr in Beta05 ?

Thanks

**Comment by alexbatashev** [comment]
@zjin-lcf the specification draft is available at https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions/USM for both SYCL and OpenCL. You can track changes by the commit history. Is there something that needs clarification?

**Comment by zjin-lcf** [comment]
Could you please clarify the USM version of device_ptr ?

**Comment by alexbatashev** [comment]
I think @jbrodman can provide an exhaustive answer to the question.

**Comment by zjin-lcf** [comment]
I will look at test examples related to the USM version of device_ptr. Thanks.
