### ISSUE TITLE
Fix for SYCL::KernelFusion/internalize_vfunc.cpp fail during SPIRV pulldown

### ISSUE THREAD

**Issue by calebwat** [intel/llvm#14850]
SYCL::KernelFusion/internalize_vfunc.cpp failed during the SYCL E2E testing for the SPIRV pulldown #14813 

The test was temporarily marked XFAIL to unblock pulldown, but it needs to be investigated and resolved properly.

**Comment by jsji** [comment]
FYI. @jopperm

**Comment by jopperm** [comment]
Thanks for the ping, we'll investigate!
