### ISSUE TITLE
`Plugin/level_zero_usm_residency.cpp` timeout in post-commit

### ISSUE THREAD

**Issue by sommerlukas** [intel/llvm#14863]
### Describe the bug

The test `Plugin/level_zero_usm_residency.cpp` times out on unrelated changes in post-commit CI.

See https://github.com/intel/llvm/actions/runs/10175954748/job/28144955957 for example.

**Comment by nrspruit** [comment]
Since the refactor of SYCL PI/UR this issue has not resurfaced, and this test is being run in CI successfully:
https://github.com/intel/llvm/actions/runs/12361121314/job/34497964803#step:22:842

I am closing this issue unless this resurfaces.
