### ISSUE TITLE
create new target component for unified-runtime, currently UR libs are installed as part of `COMPONENT level-zero-sycl-dev` - see this comment

### ISSUE THREAD

**Issue by callumfare** [intel/llvm#14924]

**Comment by KornevNikita** [comment]
@callumfare @kbenzie  hi! Was it resolved by https://github.com/oneapi-src/unified-runtime/pull/2169?

**Comment by kbenzie** [comment]
> @callumfare @kbenzie hi! Was it resolved by [oneapi-src/unified-runtime#2169](https://github.com/oneapi-src/unified-runtime/pull/2169)?

Partially, I think some intel/llvm side changes may also be necessary as there would be two different install commands with different components for the libraries.
