### ISSUE TITLE
LLD not packaged correctly into sycl-toolchain with shared library build

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#14986]
### Describe the bug

only the tool is installed, not the dependent shared libraries.

**Comment by bader** [comment]
@sarnex, see https://github.com/intel/llvm/discussions/14897. LLVM shared libraries are not installed if you build `deploy-sycl-toolchain` target.

**Comment by sarnex** [comment]
@bader Right, but HIP requires `lld`, and we already install `lld` specially for HIP [here](https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L508) and [here](https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L478). When we build with shared libs `lld` depends on `libLLDELF.so` and other shared libraries, so IMO we need to make sure the dependent shared libraries are installed.

I am not an expert in the build system so let me know if there is a better fix.

**Comment by sarnex** [comment]
Closing as this is expected and will be dealt with another way

**Comment by aelovikov-intel** [comment]
> @bader Right, but HIP requires `lld`, and we already install `lld` specially for HIP [here](https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L508) and [here](https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L478). When we build with shared libs `lld` depends on `libLLDELF.so` and other `libLLD...` libraries, so IMO we need to make sure the dependent `lld` shared libraries are installed when HIP is enabled.
> 
> I am not an expert in the build system so let me know if there is a better fix.

I agree with Nick here.
