### ISSUE TITLE
warning: multi-line comment coming from sycl header files [-Wcomment]

### ISSUE THREAD

**Issue by dvrogozh** [intel/llvm#15063]
Multi-line comment is coming from sycl header file and obscures compiler output giving the following warnings, This is probably specific to the code built with gcc as a host compiler, i.e. with `-fsycl-host-compiler=g++` since I am not sure whether clang warns about the same. As of now, that's how pytorch xpu backend is being built.
```
/home/gta/git/llvm/build/install/bin/../include/sycl/detail/builtins/builtins.hpp:235:1: warning: multi-line comment [-Wcomment]
  235 | // clang++ -[DU]__SYCL_DEVICE_ONLY__ -x c++ math_functions.inc  \
```
Please, fix.
https://github.com/intel/llvm/blob/15190894f787c72cc9125bc55ec0b34d2ba1b17f/sycl/include/sycl/detail/builtins/builtins.hpp#L235-L237

Introduced by https://github.com/intel/llvm/commit/7e9819da0e095f2e41061eb8be9b51a4caae048c. @aelovikov-intel : fyi

**Comment by aelovikov-intel** [comment]
What exactly is the problem here? @dvrogozh

**Comment by dvrogozh** [comment]
@aelovikov-intel : when you build code which uses sycl headers, you get multiple compiler warnings which obscure output. For example:
```
In file included from /home/gta/git/llvm/build/install/bin/../include/sycl/builtins.hpp:13,
                 from /home/gta/git/llvm/build/install/bin/../include/sycl/detail/image_accessor_util.hpp:17,
                 from /home/gta/git/llvm/build/install/bin/../include/sycl/accessor_image.hpp:4,
                 from /home/gta/git/llvm/build/install/bin/../include/sycl/sycl.hpp:13,
                 from /home/gta/git/pytorch/pytorch/third_party/torch-xpu-ops/test/sycl/simple_kernel.cpp:1:
/home/gta/git/llvm/build/install/bin/../include/sycl/detail/builtins/builtins.hpp:235:1: warning: multi-line comment [-Wcomment]
  235 | // clang++ -[DU]__SYCL_DEVICE_ONLY__ -x c++ math_functions.inc  \
      | ^
[1051/2001] Building SYCL (Device) object test_sycl_build_standalone_generated_simple_kernel.cpp.o
In file included from /home/gta/git/llvm/build/install/bin/../include/sycl/builtins.hpp:13,
                 from /home/gta/git/llvm/build/install/bin/../include/sycl/detail/image_accessor_util.hpp:17,
                 from /home/gta/git/llvm/build/install/bin/../include/sycl/accessor_image.hpp:4,
                 from /home/gta/git/llvm/build/install/bin/../include/sycl/sycl.hpp:13,
                 from /home/gta/git/pytorch/pytorch/third_party/torch-xpu-ops/test/sycl/simple_kernel.cpp:1:
/home/gta/git/llvm/build/install/bin/../include/sycl/detail/builtins/builtins.hpp:235:1: warning: multi-line comment [-Wcomment]
  235 | // clang++ -[DU]__SYCL_DEVICE_ONLY__ -x c++ math_functions.inc  \
      | ^
<...>
```
Please, fix compiler warning. Warning is due to EOL escapes on lines 235 and 236.

**Comment by aelovikov-intel** [comment]
> This is probably specific to the code built with gcc as a host compiler, i.e. with -fsycl-host-compiler=g++ since I am not sure whether clang warns about the same.

Probably not the `gcc` but the host compiler. When using custom host compiler, include paths are passed as `-I` and not `-isystem` (as in the case of not using custom host compiler).

**Comment by AlexeySachkov** [comment]
> I don't see how this can ever be a real issue though...

`-Werror` build?

**Comment by aelovikov-intel** [comment]
> > I don't see how this can ever be a real issue though...
> 
> `-Werror` build?

I meant why the warning should be even emitted for situation like this. It can be problematic if next line isn't a comment only, but that's not the case here!
