### ISSUE TITLE
handler_mem_op.cpp and buffer_dev_to_dev.cpp tests fail sporadically on cuda

### ISSUE THREAD

**Issue by fadeeval** [intel/llvm#1508]
sycl/test/basic_tests/handler/handler_mem_op.cpp and sycl/test/basic_tests/buffer/buffer_dev_to_dev.cpp tests fail sporadically on cuda.

Signed-off-by: Aleksander Fadeev aleksander.fadeev@intel.com

**Comment by bader** [comment]
sycl/test/basic_tests/buffer/buffer_dev_to_dev.cpp is disabled by #1526.

**Comment by bader** [comment]
sycl/test/basic_tests/handler/handler_mem_op.cpp is disabled by https://github.com/intel/llvm/pull/1533

**Comment by bjoernknafla** [comment]
Unchecked yet, but I suspect the following PR (fixing a racecondition when creating buffers before accessing them on device) addresses this issue: https://github.com/intel/llvm/pull/1798

**Comment by bader** [comment]
Should we enable them back and check?

**Comment by bjoernknafla** [comment]
I am currently running and rerunning these tests but am not seeing any fails on my local machine. Enabling them seems to be save or will then fail on other machines so it is clear that more investigation is necessary.

I will create  PR to re-enable the tests.

**Comment by bjoernknafla** [comment]
PR to re-enable these LIT tests for CUDA: https://github.com/intel/llvm/pull/1843
