### ISSUE TITLE
ESIMD/hardware_dispatch.cpp failing on Linux Arc

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#15096]
### Describe the bug

Constantly failing

```
FAIL: SYCL :: ESIMD/hardware_dispatch.cpp (624 of 2219)
******************** TEST 'SYCL :: ESIMD/hardware_dispatch.cpp' FAILED ********************
Exit Code: -6

Command Output (stdout):
--
# RUN: at line 10
/__w/llvm/llvm/toolchain/bin//clang++  -Werror  -Wno-error=deprecated-declarations -fsycl -fsycl-targets=intel_gpu_tgllp /__w/llvm/llvm/llvm/sycl/test-e2e/ESIMD/hardware_dispatch.cpp -o /__w/llvm/llvm/build-e2e/ESIMD/Output/hardware_dispatch.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -Werror -Wno-error=deprecated-declarations -fsycl -fsycl-targets=intel_gpu_tgllp /__w/llvm/llvm/llvm/sycl/test-e2e/ESIMD/hardware_dispatch.cpp -o /__w/llvm/llvm/build-e2e/ESIMD/Output/hardware_dispatch.cpp.tmp.out
# .---command stdout------------
# | Compilation from IR - skipping loading of FCL
# | Build succeeded.
# `-----------------------------
# RUN: at line 11
/__w/llvm/llvm/build-e2e/ESIMD/Output/hardware_dispatch.cpp.tmp.out
# executed command: /__w/llvm/llvm/build-e2e/ESIMD/Output/hardware_dispatch.cpp.tmp.out
# .---command stderr------------
# | terminate called after throwing an instance of 'sycl::_V1::exception'
# |   what():  No kernel named _ZTSZZ4mainENKUlRN4sycl3_V17handlerEE_clES2_E5test1 was found
# `-----------------------------
# error: command failed with exit status: -6

--

********************
```

https://github.com/intel/llvm/actions/runs/10407005499/job/28821834152

The guility commit is 38e588da39f7492570ea66c10f0fcc465562bddf

**Comment by sarnex** [comment]
@jzc Looks like https://github.com/intel/llvm/commit/38e588da39f7492570ea66c10f0fcc465562bddf is the guilty commit, I manually confirmed this is passing in the previous commit and fails with the above commit. Can you take a look? Thanks.

**Comment by jzc** [comment]
@sarnex I'll take a look

**Comment by jzc** [comment]
The device the test is running on is `intel_gpu_acm_g10`:

```
lit.py: /__w/llvm/llvm/llvm/sycl/test-e2e/lit.cfg.py:783: note: Architectures for level_zero:gpu: intel_gpu_acm_g10
```

After https://github.com/intel/llvm/commit/38e588da39f7492570ea66c10f0fcc465562bddf you should only be able to launch a device image compiled for a specific device (in this case `intel_gpu_tgllp` as `-fsycl-targets=intel_gpu_tgllp`) on a device with that architecture. so `intel_gpu_tgllp` is not `intel_gpu_acm_g10`, which leads device image selection to fail. (The error message is a bit misleading, noted [here](https://github.com/intel/llvm/pull/14909#discussion_r1707222605); I plan to improve the error message in another PR.) Should we  add `REQUIRE: arch-intel_gpu_tgllp` to the test?

**Comment by sarnex** [comment]
@jzc Sorry, I didn't even look at the failure. The reason this works today is because even for AOT, IGC saves the SPIR-V inside the `ocloc` produced binary and dynamically recompiles. 

But yeah I think it does make sense to restrict it to TGLLP, I'll fix it.
