### ISSUE TITLE
AMD/HIP tests not running in pre-commit testing

### ISSUE THREAD

**Issue by asudarsa** [intel/llvm#15122]
### Bug description

I am trying to gather test failures for an upcoming change in this 'draft' PR. https://github.com/intel/llvm/pull/15121
I see that the AMD/HIP tests are not running. Is there a reason and/or resolution for this?

Thanks

**Comment by uditagarwal97** [comment]
@asudarsa The AMD runner went rogue, so we had to move the AMD testing to postcommit: https://github.com/intel/llvm/pull/14977
If you want to trigger post-commit testing (including HIP), you could create a branch in intel/llvm with `sycl-devops-pr` as prefix (For example: `sycl-devops-pr/asudarsa/new-offload-test`) and then create a PR.

**Comment by KornevNikita** [comment]
@asudarsa @uditagarwal97 hi guys, I guess we can close this one?

**Comment by uditagarwal97** [comment]
> @asudarsa @uditagarwal97 hi guys, I guess we can close this one?

Yes, it's not really a bug.
