### ISSUE TITLE
[SYCL] Remove re-flower pass

### ISSUE THREAD

**Issue by bader** [intel/llvm#152]
Current approach with translation to SPIR-V uses re-flower pass. See this section for more details: https://github.com/intel/llvm/blob/sycl/sycl/doc/SYCL_compiler_and_runtime_design.md#integration-with-spir-v-format
To simplify SYCL compiler implementation and upstreaming work we should investigate if it's possible to translate SYCL to SPIR-V w/o this pass.

According to my understanding the main problem this pass solves is name conflicts.
For instance, type names defined for SPIR-V can conflict with user types - e.g. OpTypeEvent.

SPIR-V in LLVM IR format description: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/docs/SPIRVRepresentationInLLVM.rst

**Comment by Naghasan** [comment]
Those types could be defined as a predefined types in Sema in a non conflicting way.

i.e. `OpTypeEvent` could become in the header file `__spirv_OpTypeEvent`. In clang's Sema, the `init` would predefine this type `__spirv_OpTypeEvent` when SYCL is enable to some internal type (maybe reuse the clang's OpenCL event type ?) which can then be lowered in a similar way as it is done for OpenCL in CodeGen.

One issue here: there is a conflicts between the mangling for SPIR and the SPIR-V convention.

**Comment by bader** [comment]
@Naghasan, we are working on a bit different approach for SPIR-V types. Specifically for OpTypeEvent, we are trying to re-use OpenCL `event_t` in SYCL.
You can take the idea how it will be done from https://github.com/intel/llvm/pull/167.
@Fznamznon, could you create a PR with your current state or update https://github.com/intel/llvm/pull/167, please?

**Comment by Naghasan** [comment]
That's very similar to what I had in mind, the problem will just be the mangler in the end (i.e. having a mangling that make sense for both OpenCL C and the SPIR-V translator).

**Comment by Fznamznon** [comment]
@bader , @Naghasan , I've created PR with my changes - https://github.com/intel/llvm/pull/171
I'm trying to re-use OpenCL `event` and `sampler` types -https://github.com/intel/llvm/pull/171/commits/076d7a1d21bb95bde54c57edc848e02a137567bf
