### ISSUE TITLE
pi_event objects are not destroyed by the runtime

### ISSUE THREAD

**Issue by nyalloc** [intel/llvm#1520]
It has been observed in the PI CUDA backend that `pi_context` objects, `pi_queue` objects and `pi_event` objects can be leaked by the runtime.

In the PI CUDA backend, `pi_context` and `pi_queue` objects are retained by `pi_event` objects. The runtime creates many new `pi_event` objects without releasing them.

https://github.com/intel/llvm/blob/3f21371a40ccff330089ddbfe260d0950c588481/sycl/source/detail/scheduler/commands.cpp#L1779

https://github.com/intel/llvm/blob/3f21371a40ccff330089ddbfe260d0950c588481/sycl/source/detail/memory_manager.cpp#L480

These functions return new `pi_event` objects as an output parameter. These new objects are never released. This is likely to affect all `piEnqueue...` functions.

The only call to `piEventRelease` in the runtime source outside of the PI CUDA backend is in the destructor of the `event_impl` class.

https://github.com/intel/llvm/blob/092367be7785a7764c6dc41497f2c74c6e164824/sycl/source/detail/event_impl.cpp#L49

`event_impl`'s destructor never calls `piEventRelease` in any of our tests. The lifetime of `event_impl` objects are managed through `std::shared_ptr`, so it is possible that a circular reference has occurred, or that a stray copy of the `shared_ptr` is preventing the event object from being released.

To ensure PI API can be used correctly across all backends, all `pi_event` objects should be explicitly released when they are no longer needed. This will require some investigation into `pi_event` use through the runtime to determine if all events created are appropriately released.

**Comment by sergey-semenov** [comment]
The first iteration of the patch that addresses the issue should be up for review on Tuesday.

**Comment by sergey-semenov** [comment]
I thought I found a reproducer for this behaviour, but on further investigation this turned out not to be the case. In stark contrast to "`event_impl`'s destructor never calls `piEventRelease` in any of our tests", all the tests I inspected had a `piEventRelease` call for each `piEventCreate`/`piEventRetain`/`piEnqueue*`... call (outputs for two tests with `SYCL_PI_TRACE=1` attached: [accessor.txt](https://github.com/intel/llvm/files/4509613/accessor.txt) [DataMovement.txt](https://github.com/intel/llvm/files/4509617/DataMovement.txt)). 

Moreover, after inspecting the code for event-producing/retaining PI calls, I haven't discovered any issues: the runtime currently stores a `shared_ptr<event_impl>` for such events in the command graph and the `queue`, and they are released once the related command nodes are cleaned up (at a host-device sync point or during memory object destruction) and the event is removed from the queue (via a call to `queue::wait()` or during queue destruction).

Could you please provide a reproducer for this problem?

**Comment by sergey-semenov** [comment]
> and they are released once the related command nodes are cleaned up ... and the event is removed from the queue

As a side note, here's a PR that changes that behaviour in order to release events earlier: https://github.com/intel/llvm/pull/1561

**Comment by romanovvlad** [comment]
@StuartDAdams  ping

**Comment by StuartDAdams** [comment]
Hello! I'll try to get a reproducer ASAP.

**Comment by StuartDAdams** [comment]
We first observed this when running OneMKL's `test_main_ct` test executable. I have been able to reproduce the behavior I saw before using the newest LLVM and OneMKL available to me. This test runs on the PI CUDA backend.

Intel LLVM: cece82e63f682d5cf1a67fbdd40893e477eca8a6
OneMKL: 751472666ba884397837bbc61961bbadd5670bd0

I have created a branch of OneMKL here that highlights this behavior. https://github.com/StuartDAdams/oneMKL/tree/stuart/leakRepro

Running the test_main_ct exectable with a debugger and inspecting calls made to the cuda_piConextRelease, cuda_piEventRelease and cuda_piQueueRelease functions, it is clear that pi objects are being retained and never released before the application exits. Most calls to release simply decrement the reference count and return. By the end of the application, it has leaked two pi_context objects, two pi_queue objects, and four pi_event objects.

**Comment by sergey-semenov** [comment]
I've tried the linked reproducer with the latest build (albeit I hacked my way around installing a reference BLAS implementation, attached the diff just in case: [Diff.txt](https://github.com/intel/llvm/files/4544962/Diff.txt)).

I haven't observed any leaks in the test case on the DPCPP runtime side when inspecting the calls to `cuda_pi*Release`:
* Each of the 4 events in the test are released twice: once in the CUDA PI plugin after a retain in `_pi_event::record()` and once in the `shared_ptr<event_impl>` destructor, lowering the `pi_event` reference count to 0.
* Each of the 2 queues is released 4 times, again, lowering the reference count to 0.
* 2 created contexts are released once, lowering the reference count to 0, and 2 of them are released 6 times (twice during `piEventRelease` - retained at `piEnqueue*`, twice during `piMemRelease` - retained at `piMemBufferCreate`, once during `piQueueRelease` - retained during `piQueueCreate`, and once during `~context_impl()`), but there's an extra retain during the call to `context::get()` from `onemkl::cublas::CublasScopedContextHandler::get_handle()`, which as far as I can tell is never released, leaving the reference count at 1 at the end of the application. So there's an issue here, but it looks unrelated to the DPCPP runtime.

The PI trace obtained from the test case also seem to confirm that there's no issue on the DPCPP runtime side (attached: [trace.txt](https://github.com/intel/llvm/files/4545406/trace.txt)).

@StuartDAdams Could you please double-check my findings?

**Comment by StuartDAdams** [comment]
No problem. I'll have a look over that now.

**Comment by StuartDAdams** [comment]
Using the same branches as last time, I can observe each of the four **pi_event** objects being created through **_pi_event::make_native**, retained once through **cuda_piEventRetain**, and released once through **cuda_piEventRelease**. They are left with a refcount of 1, and with no subsequent releases, they all leak. While the **event_impl** class destructor is called 6 times, the **MEvent** member is always null, meaning it never bothers to call **piEventRelease**.

**Comment by StuartDAdams** [comment]
For details on builing OneMKL using Intel LLVM with CUDA, please see this thread.

https://github.com/intel/llvm/issues/1548

**Comment by romanovvlad** [comment]
@StuartDAdams 
Could you please provide:
1. standalone reproducer which does not depend on libraries?
2. logs with pi trace enabled for the oneMKL reproducer?

**Comment by bjoernknafla** [comment]
@romanovvlad We are looking into this.

**Comment by bjoernknafla** [comment]
We are able to build and run MKL and trigger the CUDA out of memory failures which we believe to be symptoms of PI objects being kept alive for too long.

However, I am delaying further analysis to create a reproducer due to another high priority bug (which looks like a race condition).

Below is my Linux set up to recreate the problem so far.

## Set up tools for MKL build

Install tools and libraries easily available via a Python3 virtual environment.
```sh
# Substitute ${VENV_DIR}
python3 -m venv "${VENV_DIR}"
source "${VENV_DIR}/bin/activate"
pip install -U cmake
pip install -U sphinx
pip install -U ninja
pip install -U tbb tbb-devel

# Leave venv after building and running via: deactivate
```

Install the commercial Intel oneAPI as described here [oneapi-repo-instructions](https://software.intel.com/content/www/us/en/develop/articles/oneapi-repo-instructions.html) :
```sh
# Create temporary directory.
TMP_DIR=$(mktemp -d -t stateray-oneapi-XXXXXXXX)
echo "Created temporary directory: ${TMP_DIR}"

# use wget to fetch the Intel repository public key
pushd "${TMP_DIR}"
wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
# add to your apt sources keyring so that archives signed with this key will be trusted.
sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
# remove the public key
rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
popd

# Configure APT to use Intel's repository.
sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
sudo apt-get update

# Install oneAPI packages.
sudo apt-get install intel-basekit

echo "Remove temporary directory: ${TMP_DIR}"
rm -rf "${TMP_DIR}"
```

## Clone NETLIB LAPACK and oneMKL

```sh
# cd into repo holding dir
git clone git@github.com:Reference-LAPACK/lapack.git
git clone git@github.com:oneapi-src/oneMKL.git
```

## Build NETLIB LAPACK

```sh
# cd into lapack build dir
# Substitute where to install: ${NETLIBLAPACK_INSTALL_DIR}
# Substitute where to find the sources: ${NETLIBLAPACK_SOURCE_DIR}
cmake \
-G Ninja \
-DCMAKE_BUILD_TYPE="release" \
-DBUILD_SHARED_LIBS="ON" \
-DCMAKE_INSTALL_PREFIX="${NETLIBLAPACK_INSTALL_DIR}" \
-DUSE_OPTIMIZED_BLAS="ON" \
-DCBLAS="ON" \
-DLAPACKE="ON" \
"${NETLIBLAPACK_SOURCE_DIR}"
ninja
ninja install
```

## Build oneMKL for CUDA

```sh
# cd into oneMKL build dir
# Substitute where to install: ${ONEMKL_INSTALL_DIR}
# Substitute where to find the SYCL compiler/runtime: ${SYCL_INSTALL_DIR}
# Substitute where to find oneAPI MKL (probably `/opt/intel/inteloneapi/mkl`): ${ONEAPI_MKL_DIR}
# Substitute where to find Intel TBB: ${TBB_ROOT_DIR}
# Substitute NETLIB LAPACK install dir: ${NETLIBLAPACK_INSTALL_DIR}
# Substitute source dir: ${ONEMKL_SOURCE_DIR}
cmake \
-G Ninja \
-DCMAKE_BUILD_TYPE="debug" \
-DCMAKE_INSTALL_PREFIX="${ONEMKL_INSTALL_DIR}" \
-DCMAKE_CXX_COMPILER="${SYCL_INSTALL_DIR}/bin/clang++" \
-DCMAKE_C_COMPILER="${SYCL_INSTALL_DIR}/bin/clang" \
-DMKL_ROOT="${ONEAPI_MKL_DIR}" \
-DTBB_ROOT="${TBB_ROOT_DIR}" \
-DREF_BLAS_ROOT="${NETLIBLAPACK_INSTALL_DIR}" \
-DBUILD_SHARED_LIBS="ON" \
-DENABLE_MKLCPU_BACKEND="OFF" \
-DENABLE_MKLGPU_BACKEND="OFF" \
-DENABLE_CUBLAS_BACKEND="ON" \
-DENABLE_MKLCPU_THREAD_TBB="OFF" \
-DBUILD_FUNCTIONAL_TESTING="OFF" \
"${ONEMKL_SOURCE_DIR}"

ninja
ninja install
```

## Run oneMKL test which shows the problem

```sh
# cd into oneMKL build dir
./bin/test_main_ct
```

**Comment by sergey-semenov** [comment]
> 2. logs with pi trace enabled for the oneMKL reproducer?

Could you please provide this for the original oneMKL reproducer in the meantime?

**Comment by JackAKirk** [comment]
I've ran the `test_main_ct` tests as described above without any errors. A related issue has been closed: https://github.com/intel/llvm/issues/4791.  It appears that the CUDA_ERROR_OUT_OF_MEMORY problem has been fixed so I think this issue can be closed.
