### ISSUE TITLE
SYCL Pre Commit on Windows Failure

### ISSUE THREAD

**Issue by isaacault** [intel/llvm#15333]
### Describe the bug

Build on windows failing with:

```
FAILED: tools/libclc/obj.libclc.dir/amdgcn--amdhsa/amdgcn-amdhsa/libspirv/async/wait_group_events.cl.bc D:/github/_work/llvm/llvm/build/tools/libclc/obj.libclc.dir/amdgcn--amdhsa/amdgcn-amdhsa/libspirv/async/wait_group_events.cl.bc 
```

Example runs:

- https://github.com/intel/llvm/actions/runs/10775869810/job/29882729052?pr=14954
- https://github.com/intel/llvm/actions/runs/10775344643/job/29879576544?pr=15331

### To reproduce

Run SYCL Pre Commit job on `sycl` branch.

### Environment

Current runner version: '2.319.1'
Runner name: 'intel_sycl11989[2](https://github.com/intel/llvm/actions/runs/10775869810/job/29882729052?pr=14954#step:1:2)'
Runner group name: 'Default'
Machine name: 'JFEW-TL-119892'
Testing runner upgrade compatibility

**Comment by uditagarwal97** [comment]
This should be fixed now. It was an infrastructure related issue.
