### ISSUE TITLE
[SYCL][E2E] Several test failures on Gen12 post-commit with UR_RESULT_ERROR_UNSUPPORTED_ENUMERATION

### ISSUE THREAD

**Issue by uditagarwal97** [intel/llvm#15332]
### Describe the bug

The following tests are failing in post-commit on Gen12:
https://github.com/intel/llvm/actions/runs/10769829698/job/29879500890#step:22:2705
```
********************
Failed Tests (11):
  SYCL :: Basic/sub_group_size_prop.cpp
  SYCL :: EnqueueFunctions/kernel_shortcut_with_kb.cpp
  SYCL :: EnqueueFunctions/kernel_submit_with_event_and_kb.cpp
  SYCL :: EnqueueFunctions/kernel_submit_with_kb.cpp
  SYCL :: KernelCompiler/kernel_compiler_opencl.cpp
  SYCL :: KernelCompiler/multi_device.cpp
  SYCL :: KernelCompiler/opencl_capabilities.cpp
  SYCL :: KernelCompiler/opencl_queries.cpp
  SYCL :: syclcompat/launch/launch_policy.cpp
  SYCL :: syclcompat/util/util_match_all_over_group.cpp
  SYCL :: syclcompat/util/util_match_any_over_group.cpp
```

Most of the failures are accompanied by the following msg:
```
# .---command stderr------------
# | ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 
# | ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: libze_tracing_layer.so.1
# | terminate called after throwing an instance of 'sycl::_V1::exception'
# |   what():  Native API failed. Native API returns: 54 (UR_RESULT_ERROR_UNSUPPORTED_ENUMERATION)
# `-----------------------------
``` 

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

### Environment

- OS: Linux
- Target device and vendor: Gen12
- DPC++ version: 97231579fdad2c906439162accc0145e20c23e5b

**Comment by againull** [comment]
I believe these post-commit failures were fixed. Please correct me if I am wrong.
