### ISSUE TITLE
XFAIL Failure OneapiDeviceSelector/no_duplicate_devices.cpp

### ISSUE THREAD

**Issue by isaacault** [intel/llvm#15341]
### Describe the bug

* https://github.com/intel/llvm/actions/runs/10775869808/job/29881845267?pr=14954
* https://github.com/intel/llvm/actions/runs/10782011382/job/29901383866?pr=15337

Showing:
```
********************
Unexpectedly Passed Tests (1):
  SYCL :: OneapiDeviceSelector/no_duplicate_devices.cpp
```

Different from but worth noting another issue associated with the test: https://github.com/intel/llvm/issues/15288

**Comment by KornevNikita** [comment]
As I understand @cperkinsintel fixed that with 18081b9d882c5d50054f2ad6c81721ac800e88fa. Please re-open if needed.
