### ISSUE TITLE
Pass whole SYCL kernel object as OpenCL kernel argument

### ISSUE THREAD

**Issue by Fznamznon** [intel/llvm#1544]
This will help to reduce amount of code in SemaSYCL. With SYCL kernel object passed as OpenCL kernel argument we can avoid creation of kernel object local clone and reduce number of explicit OpenCL kernel arguments.

**Comment by elizabethandrews** [comment]
WIP - https://github.com/intel/llvm/pull/1568

**Comment by Fznamznon** [comment]
This can be closed, since we understood that we can't pass the whole kernel object as a parameter due to OpenCL limitations.
