### ISSUE TITLE
[CUDA] MKL compatibility

### ISSUE THREAD

**Issue by vpascuzz** [intel/llvm#1548]
Hi,
I am trying to compile some MKL code and use the CUDA plugin interface (ee21d66e32e). Only the sycl/cuda toolchain is installed on the machine so I'm pulling MKL from the oneAPI (beta05) we have installed. Seems either they're incompatible, or I'm doing something wrong.
```
...
/opt/intel/inteloneapi/mkl/2021.1-beta05/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::queue::submit_impl(std::function<void (cl::sycl::handler&)>)'
/opt/intel/inteloneapi/mkl/2021.1-beta05/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::Scheduler::addHostAccessor(cl::sycl::detail::AccessorImp
lHost*)'
/opt/intel/inteloneapi/mkl/2021.1-beta05/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::half_impl::half::half(float const&)'
/opt/intel/inteloneapi/mkl/2021.1-beta05/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::pi::CallPi<_pi_result (*)(_pi_mem*), 184ul>::CallPi()'
/opt/intel/inteloneapi/mkl/2021.1-beta05/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::half_impl::half::operator float() const'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
...
```
Should this work, or does MKL need a separate build for the CUDA PI? I note that the same code compiles fine if I do a straight dpcpp/sycl build.

**Comment by mehdi-goli** [comment]
@vpascuzz , to compile oneMKL, you need at least [a69cdda](https://github.com/intel/llvm/commit/a69cdda1c6d5e732da1c41a457011f7e724cf063) onward. 
Before compiling the oneMKL backend, remove `nvidia.icd` (if you have any) from `/etc/OpenCL/vendors`
If you are only compiling the onMKL for CUDA you need to build the oneMKL with
```bash
cd /path/to/mkl-root
mkdir build
cd build
cmake -G Ninja .. -DREF_BLAS_ROOT=/path/to/ref/blas -DENABLE_MKLGPU_BACKEND=OFF \
-DENABLE_MKLCPU_BACKEND=OFF -DENABLE_CUBLAS_BACKEND=ON
```
I wanted to clarify that currently, the cublas backend for oneMKL backend does not support `half` type.

**Comment by vpascuzz** [comment]
Thanks a lot, @mehdi-goli. I will give this a shot.

**Comment by vpascuzz** [comment]
Hi, @mehdi-goli.

Can you tell me what `REF_BLAS_ROOT` is? Is it just the BLAS headers?

**Comment by mehdi-goli** [comment]
Hi  @vpascuzz , It a root to the netlib blas library, used as a reference blas to compare the test result with.

**Comment by vpascuzz** [comment]
Thanks a lot, @mehdi-goli!

**Comment by vpascuzz** [comment]
Sorry, @mehdi-goli. I'm on a machine running CentOS7 and blas is installed but I keep getting:
```
CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CBLAS (missing: cblas_file)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCBLAS.cmake:27 (find_package_handle_standard_args)
  tests/unit_tests/CMakeLists.txt:20 (find_package)
```

**Comment by mehdi-goli** [comment]
Does the `REF_BLAS_ROOT` point to a directory containing both blas `include` and `lib`? something like: 
```bash
├── conaninfo.txt
├── conanmanifest.txt
├── include
│   ├── cblas_f77.h
│   ├── cblas.h
│   ├── cblas_mangling.h
│   ├── cblas_test.h
│   ├── lapacke_config.h
│   ├── lapacke.h
│   ├── lapacke_mangling.h
│   └── lapacke_utils.h
├── lib
│   ├── cmake
│   │   ├── cblas-3.8.0
│   │   │   ├── cblas-config.cmake
│   │   │   ├── cblas-config-version.cmake
│   │   │   ├── cblas-targets.cmake
│   │   │   └── cblas-targets-debug.cmake
│   │   ├── lapack-3.8.0
│   │   │   ├── lapack-config.cmake
│   │   │   ├── lapack-config-version.cmake
│   │   │   ├── lapack-targets.cmake
│   │   │   └── lapack-targets-debug.cmake
│   │   └── lapacke-3.8.0
│   │       ├── lapacke-config.cmake
│   │       ├── lapacke-config-version.cmake
│   │       ├── lapacke-targets.cmake
│   │       └── lapacke-targets-debug.cmake
│   ├── libblas.so -> libblas.so.3
│   ├── libblas.so.3 -> libblas.so.3.8.0
│   ├── libblas.so.3.8.0
│   ├── libcblas.so -> libcblas.so.3
│   ├── libcblas.so.3 -> libcblas.so.3.8.0
│   ├── libcblas.so.3.8.0
│   ├── liblapacke.so -> liblapacke.so.3
│   ├── liblapacke.so.3 -> liblapacke.so.3.8.0
│   ├── liblapacke.so.3.8.0
│   ├── liblapack.so -> liblapack.so.3
│   ├── liblapack.so.3 -> liblapack.so.3.8.0
│   ├── liblapack.so.3.8.0
│   └── pkgconfig
│       ├── blas.pc
│       ├── cblas.pc
│       ├── lapacke.pc
│       └── lapack.pc
└── licenses
    └── LICENSE
````

**Comment by vpascuzz** [comment]
I have a very limited install compare to you, and only a static library:
```
└── 3.8.0
    ├── include
    │   ├── cblas_f77.h
    │   └── cblas.h
    └── lib
        └── cblas.a
```

**Comment by mehdi-goli** [comment]
The oneMKL looks for shared library `libblas.so` library, your installation has the static library `cblas.a`.  That is the reason it fails. I have extra files because I have installed lapack 3.8.0, however it is not necessary.

**Comment by vpascuzz** [comment]
`libblas.so` is available on my system in `/usr/lib64`. Standard, I think. But `lib` and `include` are of course not both there.

**Comment by mehdi-goli** [comment]
Yes, I think that is the issue. The `libblas.so` is it from MKL or from netlib blas? If it is a netlib blas you can create a symlink to it inside the `REF_BLAS_ROOT/lib` folder. However, it the `libblas.so` must be a netlib blas not the mkl one, since there is a runtime check to make sure that oneMKL does not validate its result with itself.

**Comment by vpascuzz** [comment]
Cheers! I will get back with my solution.

**Comment by vpascuzz** [comment]
@mehdi-goli,
I ended up needing to compile `cblas` myself -- good on this front.

Now I'm trying to build oneMKL (290ec06). I've followed the instructions in your first post to this issue, however, run into a bunch of errors of the type:
```
$ cmake --build -j . --target install                                                                        
[2/135] Building CXX object bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_extensions.cpp.o
FAILED: bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_extensions.cpp.o
/opt/modulefiles/dpcpp/dpcpp_wrapper/clang++  -DCUDA_NO_HALF -I/home/vrpascuzzi/sw/intel/oneMKL/include -I/home/vrpascuzzi/sw/intel/oneMKL/src -isystem /usr/local/cuda
-10.2.89/include -O2 -DNDEBUG -fPIC   -fsycl -std=c++11 -MD -MT bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_extensions.cpp.o -MF bin/blas/bac
kends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_extensions.cpp.o.d -o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_extensions.cpp.o 
-c /home/vrpascuzzi/sw/intel/oneMKL/src/blas/backends/cublas/cublas_extensions.cpp
In file included from /home/vrpascuzzi/sw/intel/oneMKL/src/blas/backends/cublas/cublas_extensions.cpp:20:
In file included from /home/vrpascuzzi/sw/intel/oneMKL/include/onemkl/blas/detail/cublas/onemkl_blas_cublas.hpp:21:
In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl.hpp:11:
In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/accessor.hpp:12:
In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/atomic.hpp:13:
In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/detail/helpers.hpp:14:
In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/detail/common.hpp:120:
In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/exception.hpp:15:
/opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/detail/pi.h:221:7: error: use of undeclared identifier 'CL_DEVICE_QUEUE_ON_DEVICE_PROPERTIES'
      CL_DEVICE_QUEUE_ON_DEVICE_PROPERTIES,
      ^
/opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/detail/pi.h:222:45: error: use of undeclared identifier 'CL_DEVICE_QUEUE_ON_HOST_PROPERTIES'
  PI_DEVICE_INFO_QUEUE_ON_HOST_PROPERTIES = CL_DEVICE_QUEUE_ON_HOST_PROPERTIES,
...
/opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/info/info_desc.hpp:213:31: error: unknown type name 'cl_kernel_sub_group_info'; did you mean 'cl_kernel_work_group_info'?
enum class kernel_sub_group : cl_kernel_sub_group_info {
                              ^
/usr/local/cuda-10.2.89/include/CL/cl.h:86:29: note: 'cl_kernel_work_group_info' declared here
typedef cl_uint             cl_kernel_work_group_info;
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[75/135] Building CXX object tests/unit_tests/blas/level2/CMakeFiles/blas_level2_ct.dir/tbsv.cpp.o
ninja: build stopped: subcommand failed.
```

I pulled the latest revision of llvm (9e79d31) and built it with:
```
$ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda --shared-libs
```
Any idea where I could've gone wrong here?

**Comment by vpascuzz** [comment]
Maybe related to: "The NVIDIA OpenCL headers conflict with the OpenCL headers required for this project and may cause compilation issues on some platforms"

**Comment by bader** [comment]
> Maybe related to: "The NVIDIA OpenCL headers conflict with the OpenCL headers required for this project and may cause compilation issues on some platforms"

This seems to be the case.
NVIDIA OpenCL headers are used:
```
/usr/local/cuda-10.2.89/include/CL/cl.h:86:29: note: 'cl_kernel_work_group_info' declared here
typedef cl_uint             cl_kernel_work_group_info;
```
and `CL_DEVICE_QUEUE_ON_DEVICE_PROPERTIES` is OpenCL 2.0 feature, which (I guess) is not supported by NVIDIA OpenCL.

Another thing which seems strage:

> I pulled the latest revision of llvm ([9e79d31](https://github.com/intel/llvm/commit/9e79d31066ba0b837feb83093371dde912222671)) and built it with:
> 
> ```
> $ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda --shared-libs
> ```
> 
> Any idea where I could've gone wrong here?

Do you use the compiler built from sources? From these logs it seems like "installed" headers are used.

> In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl.hpp:11:
> In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/accessor.hpp:12:
> In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/atomic.hpp:13:
> In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/detail/helpers.hpp:14:
> In file included from /opt/dpcpp/2020.05.09-cuda-9e79d31066b/bin/../include/sycl/CL/sycl/detail/common.hpp:120:

I hope these are built from sources. Right?

**Comment by Ruyk** [comment]
@vpascuzz , the error is indeed due to the NVIDIA OpenCL headers being used. They are only OpenCL 1.2 and cannot work with DPC++ compiler. 
Check if your NVIDIA OpenCL headers are installed in a system location (e.g., /usr/include/CL/), some package managers do this and they sometimes get used before the Khronos ones by CMake.

**Comment by vpascuzz** [comment]
@Ruyk,

> Check if your NVIDIA OpenCL headers are installed in a system location (e.g., /usr/include/CL/), some package managers do this and they sometimes get used before the Khronos ones by CMake.

Yes -- they are installed under `/usr/local/cuda`. This path is checked first, and finds `<...>/CL/`. What I want is to have `/usr/include`, which also includes a subdirectory `<...>/CL`, used instead.

I've tried a number of things (I'm not `cmake` expert) but nothing has worked; the headers in `/usr/local/cuda/include/CL` is always used.

> Do you use the compiler built from sources? From these logs it seems like "installed" headers are used.
> ... 
> I hope these are built from sources. Right?

These are the files built from source, yes. I've just put them inside `/opt`.

**Comment by vpascuzz** [comment]
I see in `oneMKL/cmake/FindcuBLAS.cmake:23`, there is a comment about a "hack" to bypass the NVIDIA OpenCL headers, but it doesn't seem to work for me.

**Comment by vpascuzz** [comment]
OK, I've managed to solve this problem. Now it's complaining about:
```
[1/56] : && /opt/modulefiles/dpcpp/dpcpp_wrapper/clang++ -fPIC -O2 -DNDEBUG   -shared -Wl,-soname,libonemkl_blas_cublas.so.0 -o lib/libonemkl_blas_cublas.so.0 bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level1.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level2.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level3.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_batch.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_extensions.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_scope_handle.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/mkl_blas_cublas_wrappers.cpp.o  -lSYCL_LIBRARY-NOTFOUND /usr/lib64/libcublas.so /usr/lib64/libcuda.so /opt/cuda/10.2.89/lib64/libcudart_static.a -lpthread -ldl /usr/lib64/librt.so && :
FAILED: lib/libonemkl_blas_cublas.so.0
: && /opt/modulefiles/dpcpp/dpcpp_wrapper/clang++ -fPIC -O2 -DNDEBUG   -shared -Wl,-soname,libonemkl_blas_cublas.so.0 -o lib/libonemkl_blas_cublas.so.0 bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level1.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level2.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level3.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_batch.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_extensions.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_scope_handle.cpp.o bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/mkl_blas_cublas_wrappers.cpp.o  -lSYCL_LIBRARY-NOTFOUND /usr/lib64/libcublas.so /usr/lib64/libcuda.so /opt/cuda/10.2.89/lib64/libcudart_static.a -lpthread -ldl /usr/lib64/librt.so && :
/usr/bin/ld: cannot find -lSYCL_LIBRARY-NOTFOUND
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```
even though during the `cmake` configuration it shows `Found SYCL:`.

**Comment by mehdi-goli** [comment]
@vpascuzz I think the issue comes from here in oneMKL test line[84](https://github.com/oneapi-src/oneMKL/blob/master/tests/unit_tests/main_test.cpp#L84). The logic for capturing the list of devices does not consider the fact that there might be other OpenCL devices like AMD. In your machine, you have an AMD GPU. Since you have an AMD GPU and there is no escape rule for AMD GPU, the GPU is captured. Executing test on AMD GPU cause fails on your machine.

If you add 
```c++
if (dev.is_gpu() && vendor_id == `THE AMD VENDOR ID`)
    continue;
```
to the main function, I think it should fix the error. Let me know if it fixes the error, so I will create a github issue on oneMKL side.

**Comment by vpascuzz** [comment]
@mehdi-goli While it's probably not a bad idea to include the code snippet above, it doesn't help. The problem is, "Duplicate parameterized test name 'NVIDIAGPU'" (I added a bit of debugging output to the test to check what it devices were found):
```
...
    Path: '/home/vrpascuzzi/sw/intel/build.oneMKL-2020.05.09-cuda-290ec069e3c/bin/test_main_ct'
    Result: Child aborted
    Output:
      GeForce RTX 2080 SUPER, 4318
      GeForce GTX 1050 Ti, 4318
...
```
If I put in a `break` after adding the first 'NVIDIAGPU' device to the `devices` vector, it works fine. The test does not like having multiple devices with the same parameterized test name.

**Comment by vpascuzz** [comment]
Thanks to everyone who provided feedback to this issue.

I'm happy to say I've finally managed to successfully build MKL for with CUDA support. Now to test it...

**Comment by vpascuzz** [comment]
Is there no random-number generator?

**Comment by cdgarland** [comment]
@vpascuzz It will be great if you can bring your RNG request to the https://github.com/oneapi-src/oneMKL project as well.
