### ISSUE TITLE
CUDA version simultaneously needs and cannot have OpenCL

### ISSUE THREAD

**Issue by tomdeakin** [intel/llvm#1559]
The CUDA version still requires the OpenCL ICD to build and run against (an issue in it's own right). If there is then a valid OpenCL platform available at runtime, a runtime error is thrown on device selection.

One unacceptable workaround is this, but it means we then can't run any OpenCL code on that system.
```
sudo mkdir /etc/OpenCL/vendors/disable
sudo mv /etc/OpenCL/vendors/nvidia.icd /etc/OpenCL/vendors/disable/
```

We're running CentOS 7.6, CUDA 10.1, and building with GCC 8.3.0.

**Comment by Ruyk** [comment]
https://github.com/intel/llvm/pull/1543 should fix the accidental selection of the NVIDIA OpenCL platform.

**Comment by Ruyk** [comment]
I think https://github.com/intel/llvm/pull/1689  solves the problem, am I correct?

**Comment by tomdeakin** [comment]
I think it does, at least for device selection. Thanks!

I think the way the compiler builds now means it's not as tricky to match up with OpenCL. I will try to build this again when I get a chance.

**Comment by bader** [comment]
@tomdeakin, can we close this issue?
