### ISSUE TITLE
ESIMD mask_expand_load test fails in post-commit on unrelated changes

### ISSUE THREAD

**Issue by sommerlukas** [intel/llvm#15653]
### Describe the bug

The test `ESIMD/mask_expand_load.cpp` fails in post-commit CI on unrelated changes. The PR in question only changed documentation in Asciidoc files, so the failure must be unrelated. 

See here: https://github.com/intel/llvm/actions/runs/11235263765/job/31276239269

**Comment by sarnex** [comment]
I have a fix
