### ISSUE TITLE
No exception raised for failed sycl::malloc_device memory allocation.

### ISSUE THREAD

**Issue by pthorali** [intel/llvm#15691]
### Describe the bug

Hi Team,
When I try to assign device memory to an array with sycl::mallco_device, there is no exception raised but the program fails, because the array is assigned NULL. Could you help us here  on why it is getting assigned NULL with out any exception being raised. The device I am testing on is ARC A770. I have attached a test.zip which contains a test.cpp file to replicate the issue, and also added it below.
[test.zip](https://github.com/user-attachments/files/17347800/test.zip)
 
Thank you,
Preethi Raksha

### To reproduce

1. Code Snippet:
   ```
   #include <sycl/sycl.hpp>
   #include <dpct/dpct.hpp>
   #include <iostream>
   #include <sstream>
   using namespace std;
   const int64_t max_buffer_size = 64* 1024*1024+2;

   int main(int argc, char **argv){

    dpct::device_ext &dev_ct1 = dpct::get_current_device();
    sycl::queue &q = dev_ct1.in_order_queue();

    try{

        float *dA;
        dA = sycl::malloc_device<float>(max_buffer_size, q);
    
        if (dA == nullptr) {
            std::cerr << "Failed to allocate device memory for dArray" << std::endl;
            return -1;
        }
        
        dpct::dpct_free(dA, q);
     
     }
    catch (sycl::exception const &e) {
            std::cerr <<"Sycl Exception caught: " <<e.what() << "\n";
            return 1;
    }
    
    }  

2. Command to Compile: 
    Save the above code as test.cpp file.
   ` icpx -fsycl -o test test.cpp `
3. Command to Run:
     ` ./test `
4. What is wrong:
    There is no exception raised, but the array "dA" is getting assigned NULL.


### Environment

- OS: [Linux]
- Target device and vendor: [Intel GPU ARC A770]
- DPC++ version: [Intel(R) oneAPI DPC++/C++ Compiler 2024.0.2 (2024.0.2.20231213)]
- Dependencies version: 
   ```
   [opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  
   [2023.16.12.0.12_195853.xmain-hotfix]
   [opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8352M CPU @ 2.30GHz OpenCL 3.0 (Build 0) 
   [2023.16.12.0.12_195853.xmain-hotfix]
   [opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics OpenCL 3.0 NEO  [24.22.29735.27]
   [ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.29735]

   Platforms: 4
   Platform [#1]:
    Version  : OpenCL 1.2 Intel(R) FPGA SDK for OpenCL(TM), Version 20.3
    Name     : Intel(R) FPGA Emulation Platform for OpenCL(TM)
    Vendor   : Intel(R) Corporation
    Devices  : 1
        Device [#0]:
        Type       : acc
        Version    : OpenCL 1.2
        Name       : Intel(R) FPGA Emulation Device
        Vendor     : Intel(R) Corporation
        Driver     : 2023.16.12.0.12_195853.xmain-hotfix
        Aspects    : accelerator fp64 online_compiler online_linker queue_profiling usm_device_allocations usm_host_allocations 
     usm_shared_allocations ext_intel_mem_channel usm_atomic_host_allocations usm_atomic_shared_allocations ext_oneapi_srgb 
    ext_intel_device_id
           info::device::sub_group_sizes: 4 8 16 32 64
   Platform [#2]:
    Version  : OpenCL 3.0 LINUX
    Name     : Intel(R) OpenCL
    Vendor   : Intel(R) Corporation
    Devices  : 1
        Device [#1]:
        Type       : cpu
        Version    : OpenCL 3.0 (Build 0)
        Name       : Intel(R) Xeon(R) Platinum 8352M CPU @ 2.30GHz
        Vendor     : Intel(R) Corporation
        Driver     : 2023.16.12.0.12_195853.xmain-hotfix
        Aspects    : cpu fp64 online_compiler online_linker queue_profiling usm_device_allocations usm_host_allocations 
    usm_shared_allocations usm_system_allocations ext_intel_mem_channel usm_atomic_host_allocations 
    usm_atomic_shared_allocations atomic64 ext_oneapi_srgb ext_intel_device_id ext_intel_legacy_image
        info::device::sub_group_sizes: 4 8 16 32 64
   Platform [#3]:
    Version  : OpenCL 3.0
    Name     : Intel(R) OpenCL Graphics
    Vendor   : Intel(R) Corporation
    Devices  : 1
        Device [#2]:
        Type       : gpu
        Version    : OpenCL 3.0 NEO
        Name       : Intel(R) Arc(TM) A770 Graphics
        Vendor     : Intel(R) Corporation
        Driver     : 24.22.29735.27
        Aspects    : gpu fp16 online_compiler online_linker queue_profiling usm_device_allocations usm_host_allocations 
    usm_shared_allocations ext_intel_mem_channel atomic64 ext_oneapi_srgb ext_intel_device_id ext_intel_legacy_image
        info::device::sub_group_sizes: 8 16 32
   Platform [#4]:
    Version  : 1.3
    Name     : Intel(R) Level-Zero
    Vendor   : Intel(R) Corporation
    Devices  : 1
        Device [#0]:
        Type       : gpu
        Version    : 1.3
        Name       : Intel(R) Arc(TM) A770 Graphics
        Vendor     : Intel(R) Corporation
        Driver     : 1.3.29735
        Aspects    : gpu fp16 online_compiler online_linker queue_profiling usm_device_allocations usm_host_allocations 
       usm_shared_allocations ext_intel_pci_address ext_intel_gpu_eu_count ext_intel_gpu_eu_simd_width ext_intel_gpu_slices 
      ext_intel_gpu_subslices_per_slice ext_intel_gpu_eu_count_per_subslice atomic64 ext_intel_device_info_uuid 
      ext_intel_gpu_hw_threads_per_eu ext_intel_device_id ext_intel_memory_clock_rate ext_intel_memory_bus_width 
      ext_intel_legacy_image
        info::device::sub_group_sizes: 8 16 32
    default_selector()      : gpu, Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.29735]
     accelerator_selector()  : acc, Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  
     [2023.16.12.0.12_195853.xmain-hotfix]
     cpu_selector()          : cpu, Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8352M CPU @ 2.30GHz OpenCL 3.0 (Build 0) 
     [2023.16.12.0.12_195853.xmain-hotfix]
     gpu_selector()          : gpu, Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.29735]
     custom_selector(gpu)    : gpu, Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.29735]
     custom_selector(cpu)    : cpu, Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8352M CPU @ 2.30GHz OpenCL 3.0 (Build 0) 
     [2023.16.12.0.12_195853.xmain-hotfix]
     custom_selector(acc)    : acc, Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  
     [2023.16.12.0.12_195853.xmain-hotfix]

**Comment by kris-rowe** [comment]
According to the [SYCL spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_allocation_functions), an exception will only be thrown if the device does not support USM allocations (or if the device does not belong to the context provided, which doesn't apply in your example).

If an allocation fails (e.g., because insufficient memory is available for the allocation) then returning a `nullptr` is the correct behaviour.

**Comment by KornevNikita** [comment]
Right, according to [the spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_allocation_functions) you will get a nullptr:
> If there are not enough resources to allocate the requested memory, these functions return nullptr.

May be you can try querying the device for [ext::intel::info::device::free_memory](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md#device-information-descriptors-10).

**Comment by pthorali** [comment]
Thank you Kris, and Nikita. 

One query, I tried [ext::intel::info::device::free_memory] and it gives an exception Invalid device. The device I am using is Arc A770, is there any other query that I can use to check what is wrong with the device.

**Comment by KornevNikita** [comment]
> Thank you Kris, and Nikita.
> 
> One query, I tried [ext::intel::info::device::free_memory] and it gives an exception Invalid device. The device I am using is Arc A770, is there any other query that I can use to check what is wrong with the device.

Are you using a level-zero backend?

**Comment by pthorali** [comment]
Yes, I think. 
When I run the below code, I get **ext_oneapi_level_zero**

![image](https://github.com/user-attachments/assets/e16a45e0-1f0a-4015-b68e-e1ca10050fdd)

**Comment by AlexeySachkov** [comment]
> Thank you Kris, and Nikita.
> 
> One query, I tried [ext::intel::info::device::free_memory] and it gives an exception Invalid device. The device I am using is Arc A770, is there any other query that I can use to check what is wrong with the device.

AFAIK, there are some limitations as to which devices support the query, but the main issue why you see the exception is likely a lack of environment variable. From [the extension spec](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md#free-global-memory) (emphasis mine):

> This new device descriptor is only available for devices in the Level Zero platform, and the matching aspect is only true for those devices. The DPC++ default behavior is to expose GPU devices through the Level Zero platform. **NOTE: one may need to set ZES_ENABLE_SYSMAN=1 to fully enable this extension.**

To see if device supports the query, you should check for `aspect::ext_intel_free_memory`, see examples in the spec. If I remember correctly, the aspect also won't be returned without the env variable.

**Comment by pthorali** [comment]
Thank you!!
Setting the  ZES_ENABLE_SYSMAN=1, gave the memory details.
