### ISSUE TITLE
Various SYCLcompat test failures

### ISSUE THREAD

**Issue by joeatodd** [intel/llvm#15737]
### Describe the bug

Recently we have started seeing failures in the following tests:
- `syclcompat/util/util_shift_sub_group_right.cpp`
- `syclcompat/memory/usm_allocations.cpp`
- `syclcompat/launch/launch_policy_lmem.cpp`
- `syclcompat/math/math_ops.cpp`

These are occurring across various PRs unrelated to these tests, so I believe the breakage is already in `sycl`.

https://github.com/intel/llvm/actions/runs/11363119797/job/31606773901?pr=15719
https://github.com/intel/llvm/actions/runs/11364896963/job/31612247815?pr=15572
https://github.com/intel/llvm/actions/runs/11370543686/job/31630960112?pr=15728
https://github.com/intel/llvm/actions/runs/11367014317/job/31619261890?pr=15721

I am working on this with high priority. I have made this issue to help unblock unrelated PRs.

### Environment

- OS: [e.g Windows/Linux]
- Target device and vendor: [e.g. Intel GPU]
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g. the output of `sycl-ls --verbose`]

**Comment by pbalcer** [comment]
This might be related to the change that was already reverted here: https://github.com/intel/llvm/pull/15720 

Are you still seeing this issue after that revert?

**Comment by joeatodd** [comment]
@pbalcer thanks, I think you're right! I will wait to confirm before closing.

**Comment by joeatodd** [comment]
Seems to be fixed. I pulled tip into [this PR](https://github.com/intel/llvm/pull/15683) and it's [passing](https://github.com/intel/llvm/actions/runs/11385706479/).

**Comment by pbalcer** [comment]
@joeatodd was there any other patch that went into that could have addressed the syclcompat issues in your opinion? We are hoping to reintroduce the reverted patch (see @winstonzhang-intel PR here: https://github.com/oneapi-src/unified-runtime/pull/2234), and we'd like to avoid reintroducing the same problem.

**Comment by joeatodd** [comment]
@pbalcer I don't know to be honest; the only symptom was that 3 quite different tests started failing all at once. I would suggest that if the PR passes CI it could be reintroduced and then if these tests start failing again we'll have fairly high confidence of the root cause.

**Comment by pbalcer** [comment]
@joeatodd No worries, thanks!
