### ISSUE TITLE
Include file portability check was disable to unblock pulldown

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#1594]
The check was disabled to unblock pulldown: https://github.com/intel/llvm/pull/1564
Once enabled it generates false diagnostics if Unix emulation console is used on windows to run LIT tests.

**Comment by vladimirlaz** [comment]
the PR https://github.com/intel/llvm/pull/5621 enables back the portability check

**Comment by bader** [comment]
> the PR #5621 enables back the portability check

FYI: you can link this issue with the pull request, so when PR is merged, the issue will be closed automatically.
