### ISSUE TITLE
deploy-sycl-toolchain build target missing L0 library dependencies

### ISSUE THREAD

**Issue by EwanC** [intel/llvm#15986]
### Describe the bug

From testing the L0 loader bump PRs:
* https://github.com/oneapi-src/unified-runtime/pull/2279 / https://github.com/intel/llvm/pull/15967
* https://github.com/intel/llvm/pull/15522#issuecomment-2431560786

I have discovered that the `deploy-sycl-toolchain` build target does not include all the necessary L0 dependencies.

### To reproduce

With git branch from https://github.com/intel/llvm/pull/15967 
```sh
$ python3 buildbot/configure.py
$ python3 buildbot/compile.py
$ cd build
$ ./bin/sycl-ls
SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
$ ninja deploy-sycl-toolchain
$ ./bin/sycl-ls
SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
$  ninja libze_tracing_layer.so
$ ./bin/sycl-ls
<works correctly>
```

In this case manually building `libze_tracing_layer.so`  fixes the issue, however I am not knowledgeable about DPC++ CMake or L0 to know if this is the only missing dependency.

**EDIT** On another system I also had to manually build the `ninja libze_validation_layer.so` target

### Environment

- Ubuntu 22.04
-  i9-13900K
- https://github.com/intel/compute-runtime/releases/tag/24.39.31294.12 installed

**Comment by ianayl** [comment]
I am unfortunately not familiar with L0 either, but it would seem that libze_tracing_layer.so was intentionally not built by default: It is not required for L0 to run.

From my experimentation, I noticed that older commits were using an UR was using an incompatible version of libze_tracing_layer.so provided via LD_LIBRARY_PATH. Are you still getting this error if you remove libze_tracing_layer.so from LD_LIBRARY_PATH? I suspect using a more recent version of the UR, i.e. https://github.com/intel/llvm/commit/18737897b57d535608215f98a848ce420089daad would fix the issue, but I would need to do further experimentation.

**Comment by EwanC** [comment]
Hiya, I've pulled tip and tried `buildbot/configure.py` followed by `buildbot/compile.py` on a clean build and indeed the error is no longer present.

Since I can't reproduce the issue any more I'm happy to close this. The workaround will still be documented in the closed issue if we ever need to reference it
