### ISSUE TITLE
Reland libclc patches reverted in sycl-web

### ISSUE THREAD

**Issue by maarquitos14** [intel/llvm#16015]
### Describe the bug

A lot of libclc-related patches are coming in from upstream causing massive conflicts in sycl-web. Some of them are not easy to apply without deep knowledge of libclc, so they were just reverted and need to be relanded. Please, see below a list of the reverted patches:

- https://github.com/llvm/llvm-project/commit/7be30fd5335ca7fe050ee1789ea2648f014daf1b
- https://github.com/llvm/llvm-project/commit/b231647475b7fa78ad9382a5505889f1167e9cea

Please, feel free to edit the description to add new reverted patches.

**Comment by frasercrmck** [comment]
I think we could perhaps close this issue and re-open another one when a new batch of commits comes in. Otherwise this ticket will be open forever :smile:
