### ISSUE TITLE
CMake SYCL_BUILD_PI_HIP_ROCM_DIR is not propagated to Unified Runtime's UR_HIP_ROCM_DIR.

### ISSUE THREAD

**Issue by etiennemlb** [intel/llvm#16052]
### Describe the bug

It appears that `SYCL_BUILD_PI_HIP_ROCM_DIR ` is not propagated to `UR_HIP_ROCM_DIR` in `unified-runtime-src/source/adapters/hip/CMakeLists.txt`.

This is contrary to what the `sycl/doc/GetStartedGuide.md` document tells us about specifying `SYCL_BUILD_PI_HIP_ROCM_DIR`.

**Comment by jinz2014** [comment]
I didn't try to build, but 

llvm/sycl/doc/GetStartedGuide.md:variable `UR_HIP_ROCM_DIR` which can be passed using the
llvm/sycl/doc/GetStartedGuide.md:  --cmake-opt=-DUR_HIP_ROCM_DIR=/usr/local/rocm
