### ISSUE TITLE
[IGC-DEV]  dev-igc CI not reflecting targeted IGC commits: likely using an older version of IGC

### ISSUE THREAD

**Issue by YixingZhang007** [intel/llvm#16251]
### Describe the bug

The dev-igc CI is not applying the intended IGC commits that should be included in the IGC version listed in `dependencies-igc-dev.json`. Instead, it appears to be using an older version of IGC, likely the version set for the regular IGC CI test. 

### To reproduce

The support for `joint_matrix_bf16_fill_k_cache_runtime_dim.cpp` and  `joint_matrix_bf16_fill_k_cache_arg_dim.cpp` are done in `intel-graphics-compiler` commit 92236dc and should be included in the dev-igc. However, these two tests are currently failing in igc_dev env.

To reproduce, please remove the XFAIL in test `joint_matrix_bf16_fill_k_cache_runtime_dim.cpp` or `joint_matrix_bf16_fill_k_cache_arg_dim.cpp` and run test using igc_dev env. 

### Environment

OS: Linux
Target device and vendor: Intel GPU
DPC++ version:
Dependencies version: igc-dev

**Comment by YixingZhang007** [comment]
FYI @YuriPlyakhin, @sarnex, @jsji

**Comment by sarnex** [comment]
the problem might be the igc dev container is broken, ill take an initial look at this
