### ISSUE TITLE
build beta06 from source?

### ISSUE THREAD

**Issue by cgleggett** [intel/llvm#1629]
Is it possible to build the same version of clang++ that's it the beta06 release from the llvm source? I didn't see a "beta06" git tag or anything that resembles that.

**Comment by fwyzard** [comment]
`/opt/intel/inteloneapi/compiler/2021.1-beta06/linux/include/sycl/CL/sycl/version.hpp` has
```c++
#define __SYCL_COMPILER_VERSION 20200415
```

but I don't know if that corresponds to some kind of closest upstream tag (*i.e.* [`20200415`](https://github.com/intel/llvm/tree/20200415)) or it's just the date when the oneAPI build was configured.

**Comment by bader** [comment]
AFAIK, beta06 corresponds to https://github.com/intel/llvm/commit/ba404be42c028934c3e33da1239e526975d51ef6.

**Comment by fwyzard** [comment]
Ah... so tag [`2020-03`](https://github.com/intel/llvm/tree/2020-03) ?

**Comment by bader** [comment]
> Ah... so tag [`2020-03`](https://github.com/intel/llvm/tree/2020-03) ?

I think so. Yes.

**Comment by cgleggett** [comment]
ahh, and thus `beta05` is `2020-02`?

thanks.

**Comment by AlexeySachkov** [comment]
@cgleggett, can we close this issue?

**Comment by cgleggett** [comment]
yes.
