### ISSUE TITLE
Potential `nulltpr` dereference in `graph_impl`

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#16332]
https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/graph_impl.cpp#L1014-L1023

`if` on 1014 implies that `NewEvent` could be `nullptr`. However, we directly dereference it on 1023.

Either 1023 dereference should be made conditional, or `if` on 1014 should be turned into an assertion.

**Comment by EwanC** [comment]
tagging @intel/sycl-graphs-reviewers
