### ISSUE TITLE
Reduce amount of `AccessorImplHost` copies

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#16335]
There are many places where we accept objects of `Requirement` data type by value. `Requirement` is defined as an alias to `AccessorImplHost`:

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/accessor_impl.hpp#L186

And the latter is pretty heavy (200+ bytes):

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/accessor_impl.hpp#L99-L125

List of places where we accept `Requirement` by value:

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1529-L1533

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1175

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1382

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1054-L1057

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1446

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1875

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1704-L1708

https://github.com/intel/llvm/blob/83fe1c17821730ac6f0c1c9be7224113b1a1f336/sycl/source/detail/scheduler/commands.cpp#L1097

**Comment by KseniyaTikhomirova** [comment]
all of these copies is passed to std::move after. These copies are intentional.
