### ISSUE TITLE
libsycl.so-gdb.py installed with wrong name in wrong directory

### ISSUE THREAD

**Issue by cgleggett** [intel/llvm#1636]
with 95ded993d14   libsycl.so-gdb.py is getting installed as
`INST_DIR//SRC_DIR/sycl/xmethods/$<TARGET_FILE_NAME:sycl>-gdb.py`

where **INST_DIR** is the value of `CMAKE_INSTALL_PREFIX`, **SRC_DIR** is the location of the llvm source, and `$<TARGET_FILE_NAME:sycl>` is actually that exact string. 

this got messed up somewhere between bb73d926bea and 95ded993d14

config.py options were `--cuda --shared-libs -o . -t release --no-werror`

```

**Comment by bader** [comment]
Installation script is located here: https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L211 and was recently modified by @alexbatashev.
@alexbatashev, could you take a look, please?

Additional note: I would refactor the cmake files and move the parts related to libsyc.so-gdb.py to https://github.com/intel/llvm/tree/sycl/sycl/xmethods.

Tagging @mihails-strasuns-intel to keep him in the loop.
