### ISSUE TITLE
instantiating fold expression with 512 arguments exceeded expression nesting limit of 256

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#16399]
Compiling the program shows the following error. Thanks for your suggestions.

https://github.com/zjin-lcf/HeCBench/tree/master/src/zmddft-sycl

clang++ --version
clang version 20.0.0git (https://github.com/intel/llvm.git 746a2bd12821edd8b9982f9d16daf7962bd68a4b)
Target: x86_64-unknown-linux-gnu
Thread model: posix

../include/sycl/ext/oneapi/device_global/device_global.hpp:102:75: fatal error: instantiating fold expression with 512 arguments exceeded expression nesting limit of 256
  102 |               (!IsDeviceGlobalOrBaseRef<std::remove_cv_t<Args>>::value && ...),

**Comment by AlexeySachkov** [comment]
Hi @jinz2014,

Most likely this error is not specific to SYCL, but we inherit it from the upstream clang.

I was able to find the following documentation on the topic: [User Manual: Controlling implementation limits](https://clang.llvm.org/docs/UsersManual.html#controlling-implementation-limits). You can try and tweak some of those defaults to see if it helps.

[D86936](https://reviews.llvm.org/D86936) suggests that `-fbracket-depth=N` is what you are looking for.

**Comment by jinz2014** [comment]
Thanks.
