### ISSUE TITLE
SYCL Level-Zero plugin

### ISSUE THREAD

**Issue by airlied** [intel/llvm#1640]
I'm just wondering what the plans for a level 0 backend for the sycl runtime?

Thanks,
Dave.

**Comment by smaslov-intel** [comment]
We are working right now on adding it to https://github.com/intel/llvm with ETA for completion in May 2020 (@againull).

**Comment by AlexeySachkov** [comment]
@airlied, see #1718

**Comment by AlexeySachkov** [comment]
@airlied, L0 backend for SYCL runtime has been merged: go ahead and check it out!
