### ISSUE TITLE
 SYCL Pre Commit on Linux / test (NVIDIA/CUDA, ["Linux", "cuda"] - fails

### ISSUE THREAD

**Issue by YuriPlyakhin** [intel/llvm#16461]
https://github.com/intel/llvm/actions/runs/12471122950/job/34808134055?pr=16435

Total Discovered Tests: 2238
  Unsupported      : 1179 (52.68%)
  Passed           :   75 (3.35%)
  Expectedly Failed:   23 (1.03%)
  Failed           :  961 (42.94%)

 .---command stderr------------
 | <CUDA>[ERROR]: 
 | UR CUDA ERROR:
 | 	Value:           999
 | 	Name:            CUDA_ERROR_UNKNOWN
 | 	Description:     unknown error
 | 	Function:        operator()
 | 	Source Location: /__w/llvm/llvm/build/_deps/unified-runtime-src/source/adapters/cuda/platform.cpp:80
 | 
 | terminate called after throwing an instance of 'sycl::_V1::exception'
 |   what():  Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
 `-----------------------------
 error: command failed with exit status: -6

**Comment by sarnex** [comment]
I restarted the runner and updating the software and it seems to be working now, so closing.
