### ISSUE TITLE
[CUDA] Experimental support for Windows ?

### ISSUE THREAD

**Issue by coumbsek** [intel/llvm#1646]
Hy,

As I undestand the doc (https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#build-dpc-toolchain-with-support-for-nvidia-cuda)  : "To enable support for CUDA devices, **follow the instructions for the Linux DPC++ toolchain**, but add the --cuda flag to configure.py" currently the experimental support of CUDA backend is only for Linux build.

Can someone confirm this to me or should I try harder to build it under my computer running Windows ?

Thanks

**Comment by bader** [comment]
From https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#cuda-back-end-limitations

> Backend is only supported on Linux

**Comment by Ruyk** [comment]
We are not testing the CUDA backend on windows at the moment. Its also unclear what the support for CUDA on LLVM is on windows, according to the documentation there is no maintainer (See https://llvm.org/docs/CompileCudaWithLLVM.html#prerequisites), so its not a priority for us at the moment.
