### ISSUE TITLE
SVM prefetch and home preference optimisations?

### ISSUE THREAD

**Issue by paboyle** [intel/llvm#1648]
Developing code under UVM for Nvidia GPU's, we have been reluctantly driven to use
cudaMemAdvise and cudaMemPrefetchAsynch  place and move large volumes of less frequently used data on host memory, due to slow performance of pulling memory into the GPU when accessed by GPU kernels.

These sort of placement hint optimisations may be useful for SVM under SyCL and might need to be considered.

**Comment by paboyle** [comment]
Not sure it's CUDA specific - I'm suggesting the SVM in Gen9 and beyond might benefit from such hints & prefetches?

**Comment by bader** [comment]
Sorry, I fought that the request is to add SYCL API to expose CUDA API.
I think we have similar API for USM extension: https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/USM.adoc#prefetch and https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/USM.adoc#performance-hints-1.
Will these performance hinting APIs work for you?

**Comment by paboyle** [comment]
Thanks - exactly what I was looking for/suggesting. Will close issue?

**Comment by bader** [comment]
Yes, please.

NOTE: I'm not sure how well these hints are supported on Gen9, but I suggest opening a separate issue if you hit problems with using this API. Does it sounds okay to you?

**Comment by paboyle** [comment]
Less concerned about Gen 9 than I am about roadmap / API definition. It's Aurora that counts.
