### ISSUE TITLE
[SYCL] Half type in global scope

### ISSUE THREAD

**Issue by Ruyk** [intel/llvm#1651]
The line below:

https://github.com/intel/llvm/blob/c72cbc4ef8662f4d57d3ae9e6c4e4d449e47cbf0/sycl/include/CL/sycl/half_type.hpp#L223

defines Half type in global scope, but that is not required by the SYCL specification. Is there any reason this is there?

It causes conflicts with CUDA headers, which define also the half type in global scope.

**Comment by Ruyk** [comment]
In case someone arrives here from finding this error in SYCL for CUDA code:  the CUDA_NO_HALF definition removes the half type in CUDA.

**Comment by bader** [comment]
@Fznamznon, you seem to commit the original code. Do you recall the reason?

**Comment by bader** [comment]
Might be related to this spec issue: https://github.com/KhronosGroup/SYCL-Docs/issues/40. At some point `half` was defined as fundamental type. It might be just an artifact of old implementation.

**Comment by Fznamznon** [comment]
> Might be related to this spec issue: [KhronosGroup/SYCL-Docs#40](https://github.com/KhronosGroup/SYCL-Docs/issues/40). At some point `half` was defined as fundamental type. It might be just an artifact of old implementation.

Yes, you are right. `half` was defined in global scope because CTS tests were checking it without any namespaces. If tests are fixed, we can remove this definition.

**Comment by bader** [comment]
Can we make it in reverse order? Let's remove the global scope declaration and test it against the latest SYCL-CTS. If tests fail, we fix both the implementation and the tests.

**Comment by pvchupin** [comment]
@AlexeySachkov, can you please take a look?

**Comment by bader** [comment]
Fixed by https://github.com/intel/llvm/pull/2624.
