### ISSUE TITLE
Default build instructions result in empty directory

### ISSUE THREAD

**Issue by tomdeakin** [intel/llvm#1653]
The instructions in the README are these:
```
export DPCPP_HOME=~/sycl_workspace
mkdir -p $DPCPP_HOME/build
cd $DPCPP_HOME

git clone https://github.com/intel/llvm -b sycl
cd $DPCPP_HOME/build

python $DPCPP_HOME/llvm/buildbot/configure.py
python $DPCPP_HOME/llvm/buildbot/compile.py
```

This results in an *empty* `$DPCPP_HOME/build` directory.
The output shows most things installed in `$DPCPP_HOME/llvm/build/install`.
However, the OpenCL ICD is being installed in `$DPCPP_HOME/llvm/tools/opencl-aot`.

This is messy and tricky to figure out what bits I need to manually deploy.

**Comment by bader** [comment]
@tomdeakin, thanks for reporting this.
`$DPCPP_HOME/build` is an artifact of old instructions. I fixed it in #1697.

WRT OpenCL ICD, I agree that there is some mess with it, but I'd like to clarify your use case.
Do you expect OpenCL ICD to be the part of the deployed toolchain? 
I think it's not needed if OpenCL ICD is installed in the system.

Moreover, OpenCL ICD is built/installed twice during the build if it's not found in the system or user haven't specified custom location: once by opencl-aot tool and another build is done by sycl library.

I also find it confusing that "compile.py" does installation **before** the tool chain is tested.

**Comment by tomdeakin** [comment]
Thanks for updating the docs.

My OpenCL question came from the lack of Deployment instructions. I had to reverse engineer what important looking things were built. As long as I install an OpenCL driver somewhere, then it should be fine to build/run application code. I don't necessarily need the one that's built here.

**Comment by AlexeySachkov** [comment]
@tomdeakin, was the problem resolved? can we close the issue?
