### ISSUE TITLE
Need to fix regression introduced by f5360d4 and reapply the patch

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#1660]
I have done pulldown (https://github.com/intel/llvm/pull/1656) from LLVM to intel/llvm. It looks like patch f5360d4bb3376347479d86547d21b95d80be786d “Reapply "Add support for #pragma float_control" with buildbot fixes” regress SYCL compiler on windows:
	http://ci.llvm.intel.com:8010/#/builders/18/builds/1820

Need to fix regression and reapply the patch.

**Comment by mibintc** [comment]
I have posted a patch to fix this on llorg https://reviews.llvm.org/D79631

**Comment by vladimirlaz** [comment]
The fix has been propagated to intel/llvm (sycl) in scope of https://github.com/intel/llvm/pull/1677
