### ISSUE TITLE
Clarifying which Intel CPU OpenCL version to use

### ISSUE THREAD

**Issue by bjoernknafla** [intel/llvm#1691]
Which Intel CPU OpenCL version to install for use with SYCL?

The [GetStartedGuide.md](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime) points to the [ReleaseNotes.md](https://github.com/intel/llvm/blob/sycl/sycl/ReleaseNotes.md#prerequisites) which point to https://github.com/intel/llvm/releases/ . The daily DPC++ releases do not seem to contain the oclcpuexp driver though.

When going back through the release history, then the following is the first that contains links to Intel OpenCL CPU and GPU drivers to use: https://github.com/intel/llvm/releases/tag/2020-02

For Linux it points to:
* CPU: https://github.com/intel/llvm/releases/download/2020-02/oclcpuexp-2020.10.3.0.04_rel.tar.gz
* GPU: https://github.com/intel/compute-runtime/releases/tag/20.06.15619

**Is the OpenCL CPU driver 2020-10.3.0.0.4 the correct one to use?**

With the above CPU driver I do not need to follow the [Install low level runtime](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime) steps for the OpenCL CPU driver as it does not seem to require the Intel TBB libraries or contains them itself already.

**Comment by michaelphamct** [comment]
I have a closely related issue to @bjoernknafla 's original issue. I think the documentation should have more clear information about the differences between the DPC++ daily releases and the oneAPI DPC++ Compiler releases. The first kind of release has three assets (dpcpp-compiler.tar.gz, Source code (zip and tar.gz)), and the second kind of release has four assets (oclcpuexp-2020.10.4.0.15_rel.tar.gz, win-oclcpuexp-2020.10.4.0.15_rel.zip, Source code (zip and tar.gz)). I'm mainly interested in the Intel CPU OpenCL runtime driver but having two seperate kinds of releases on [https://github.com/intel/llvm/releases?after=20200506](https://github.com/intel/llvm/releases?after=20200506) is confusing.

**Comment by bader** [comment]
Sorry for confusion. We recently uploaded a file with all versions for external dependencies and links, where these versions can be downloaded.
@vladimirlaz is going to update the documentation with more detailed instructions.
https://github.com/intel/llvm/blob/sycl/buildbot/dependency.conf - these versions are used in pre-commit validation.

**Comment by vladimirlaz** [comment]
The first version of configuration file has been submitted (today it contains links to the binaries which are used for testing). Documentation pointing to the new file is under review: https://github.com/intel/llvm/pull/1699/files. 

We do expect that frequency of dependency update will raise.

**Comment by bjoernknafla** [comment]
That is very helpful, thank you!
