### ISSUE TITLE
latest release tarball has weird file permissions

### ISSUE THREAD

**Issue by yxliang01** [intel/llvm#1696]
Upon uncompressing, the files are not readable by others and the directory can't be entered by others as well. I think it makes more sense to make all the files readable by others and all directories have the `x` bit for others.

**Comment by bader** [comment]
@vladimirlaz, @tfzhu, could you check what is wrong with the release tarball, please?

**Comment by tfzhu** [comment]
@yxliang01, can you put the link of problematic release here?

**Comment by vladimirlaz** [comment]
@yxliang01 Why do you think we should set default permissions for others? 
 - The owner can always change any permissions
 - By default there is no any reason to let other (all users) access experimental RTs

**Comment by yxliang01** [comment]
@tfzhu https://github.com/intel/llvm/releases/download/2020-03/oclcpuexp-2020.10.4.0.15_rel.tar.gz

@vladimirlaz Ideally for an official release, the file permissions upon decompression should be usable by most people (at least I believe).
Although the code in this repo is currently experimental, from the Intel official site, it seems like this will eventually be the official codebase. So, I would say this is eventually a TODO.

**Comment by vladimirlaz** [comment]
What is the use-case for installing this RT and let "others" to access them?
These RTs are for development purposes and NOT for redistribution or end-user.

**Comment by bader** [comment]
I guess it might be needed if RT is being installed on the machine shared among multiple "SYCL developers". Right?

**Comment by yxliang01** [comment]
To be honest, I have never thought of the case that it is intentionally not allowing "others" to access the experimental RT for the sake of protection (I guess). But, what's generally happening is that we need root permission to copy/extract these files to the system directories while we generally don't run OpenCL programs with root user. In other scenario where there are normal users and advanced developers, we also shouldn't install both the stable 18.1 version and this experimental RT concurrently as suggested. Under this circumstance, I don't think it makes sense to simply block the normal users from accessing the CPU.

Anyways, since there're valid counter-arguments (intentionally preventing other users from accessing), I am fine with closing this issue.

**Comment by vladimirlaz** [comment]
The latest drops have access permissions for other
