### ISSUE TITLE
python $DPCPP_HOME/llvm/buildbot/compile.py

### ISSUE THREAD

**Issue by mpak2** [intel/llvm#1698]
```
export DPCPP_HOME=~/sycl_workspace
mkdir -p $DPCPP_HOME/build
cd $DPCPP_HOME

git clone https://github.com/intel/llvm -b sycl
cd $DPCPP_HOME/build

python $DPCPP_HOME/llvm/buildbot/configure.py
python $DPCPP_HOME/llvm/buildbot/compile.py
```

[2276/2440] Performing install step for 'ocl-icd'
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: /root/sycl_workspace/llvm/build/tools/sycl/icd_install/lib/libOpenCL.so.1.2
-- Installing: /root/sycl_workspace/llvm/build/tools/sycl/icd_install/lib/libOpenCL.so.1
-- Installing: /root/sycl_workspace/llvm/build/tools/sycl/icd_install/lib/libOpenCL.so
[2279/2440] Building CXX object tools/sycl-post-link/CMakeFiles/sycl-post-link.dir/sycl-post-link.cpp.o
/root/sycl_workspace/llvm/llvm/tools/sycl-post-link/sycl-post-link.cpp: In function ‘string_vector saveResultSymbolsLists(string_vector&)’:
/root/sycl_workspace/llvm/llvm/tools/sycl-post-link/sycl-post-link.cpp:326:19: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
  326 |   return std::move(Res);
      |          ~~~~~~~~~^~~~~
/root/sycl_workspace/llvm/llvm/tools/sycl-post-link/sycl-post-link.cpp:326:19: note: remove ‘std::move’ call
[2280/2440] Building CXX object tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o
FAILED: tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o 
/usr/bin/c++  -DCL_TARGET_OPENCL_VERSION=220 -DXPTI_ENABLE_INSTRUMENTATION -DXPTI_STATIC_LIBRARY -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/sycl/source -I/root/sycl_workspace/llvm/sycl/source -Iinclude -I/root/sycl_workspace/llvm/llvm/include -I/root/sycl_workspace/llvm/xpti/include -I/root/sycl_workspace/llvm/sycl/include -Itools/sycl/OpenCL/inc -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wextra -Wno-deprecated-declarations -Werror -O3    -UNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -std=c++14 -MD -MT tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o -MF tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o.d -o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o -c /root/sycl_workspace/llvm/sycl/source/detail/accessor_impl.cpp
In file included from /root/sycl_workspace/llvm/sycl/include/CL/sycl/types.hpp:53,
                 from /root/sycl_workspace/llvm/sycl/include/CL/sycl/intel/sub_group.hpp:22,
                 from /root/sycl_workspace/llvm/sycl/include/CL/sycl/nd_item.hpp:17,
                 from /root/sycl_workspace/llvm/sycl/include/CL/sycl/detail/cg.hpp:22,
                 from /root/sycl_workspace/llvm/sycl/source/detail/scheduler/scheduler.hpp:11,
                 from /root/sycl_workspace/llvm/sycl/source/detail/accessor_impl.cpp:11:
/root/sycl_workspace/llvm/sycl/include/CL/sycl/multi_ptr.hpp:520:3: error: converting ‘cl::sycl::multi_ptr<const void, Space>’ to the same type will never use a type conversion operator [-Werror=class-conversion]
  520 |   operator multi_ptr<const void, Space>() const {
      |   ^~~~~~~~
cc1plus: all warnings being treated as errors
[2283/2440] Building CXX object tools/llvm-spirv/lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/LLVMToSPIRVDbgTran.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/sycl_workspace/llvm/buildbot/compile.py", line 63, in <module>
    ret = main()
  File "/root/sycl_workspace/llvm/buildbot/compile.py", line 59, in main
    return do_compile(args)
  File "/root/sycl_workspace/llvm/buildbot/compile.py", line 37, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/root/sycl_workspace/llvm/build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '4']' returned non-zero exit status 1
root@f324ecb951a5:~/sycl_workspace#

**Comment by bader** [comment]
@mpak2, please, use `--no-werror` option for untested host compilers.
I'm going to set this option by default soon, but this is tracked by already existing issue, so I'm closing this one.

**Comment by mpak2** [comment]
thank you very much
