### ISSUE TITLE
[SYCL] build spir-v doesn't validate

### ISSUE THREAD

**Issue by airlied** [intel/llvm#17]
This might be an artifact of my install, but attempting to validate the produced spirv with spirv-val errors here.

[airlied@dreadlord-bne-redhat-com ~]$ /opt/intel/bin/clang++ --sycl -Xclang -fsycl-int-header=simple-sycl-app-int-header.h -c simple-sycl-app.cpp -o kernel.spv
[airlied@dreadlord-bne-redhat-com ~]$ spirv-val ./kernel.spv 
error: 212: Invalid decoration operand: 4469
[airlied@dreadlord-bne-redhat-com ~]$ spirv-dis ./kernel.spv 
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 197
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
               OpCapability Int64
               OpCapability Int8
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %17 "_ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE10FillBuffer"
        %193 = OpString "kernel_arg_type._ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE10FillBuffer.int*,range<1>,id<1>,"
               OpSource OpenCL_CPP 100000
               OpName %_Z13get_global_idj "_Z13get_global_idj"
               OpName %class_cl__sycl__range "class.cl::sycl::range"
               OpName %class_cl__sycl__detail__array "class.cl::sycl::detail::array"
               OpName %struct_cl__sycl__id "struct.cl::sycl::id"
               OpName %_arg_ "_arg_"
               OpName %_arg_Range "_arg_Range"
               OpName %_arg_Offset "_arg_Offset"
               OpName %class_anon "class.anon"
               OpName %class_cl__sycl__accessor "class.cl::sycl::accessor"
               OpName %struct_cl__sycl__detail__accessor_impl "struct.cl::sycl::detail::accessor_impl"
               OpName %_ZZZ4mainENK3__0clERN2cl4sycl7handlerEENKUlNS1_2idILi1EEEE_clES5_ "_ZZZ4mainENK3$_0clERN2cl4sycl7handlerEENKUlNS1_2idILi1EEEE_clES5_"
               OpName %struct_cl__sycl__detail__accessor_subscript_w "struct.cl::sycl::detail::accessor_subscript_w"
               OpName %struct_cl__sycl__detail__accessor_common "struct.cl::sycl::detail::accessor_common"
               OpName %class_cl__sycl__detail__accessor_base "class.cl::sycl::detail::accessor_base"
               OpDecorate %194 FuncParamAttr ByVal
        %194 = OpDecorationGroup
               OpDecorate %195 Alignment 8
        %195 = OpDecorationGroup
error: 212: Invalid decoration operand: 4469

**Comment by airlied** [comment]
this seems like a possible bug in the llvm<->spirv translator, and also I might need to update the spirv-tools I have to newer version.

**Comment by airlied** [comment]
Updated tools more correctly print:
error: line 29: 2nd operand of Decorate: operand 4469 requires one of these extensions: SPV_KHR_no_integer_wrap_decoration 
  OpDecorate %196 NoSignedWrap

**Comment by bader** [comment]
The same issue is reported in #2. I reported this problem to SPIR-V translator project.

**Comment by airlied** [comment]
indeed reverting the  offending commit makes validate work.

**Comment by bader** [comment]
@airlied, I'd like to close this issue as it duplicates the issue #2. Are you okay with closing this one?

**Comment by airlied** [comment]
Good plan.
