### ISSUE TITLE
[SYCL] Crash for range of zero?

### ISSUE THREAD

**Issue by Pennycook** [intel/llvm#1708]
The following code crashes:
```c++
#include <CL/sycl.hpp>
using namespace sycl;

int main(int argc, char* argv[])
{
  queue q;
  q.submit([&](handler& cgh) {
    cgh.parallel_for(range<1>(0), [=](id<1> i) {});
  }).wait();
}
```
with the following error:
```
llvm/sycl/source/detail/scheduler/commands.cpp:1439: void cl::sycl::detail::adjustNDRangePerKernel(cl::sycl::detail::NDRDescT&, cl::sycl::detail::pi::PiKernel, const cl::sycl::detail::device_impl&): Assertion `NDR.NumWorkGroups[0] != 0 && NDR.LocalSize[0] == 0' failed.
```

The documentation for the function containing the failing assert (see [here](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/scheduler/commands.cpp#L1439)) suggests that the function only expects to be called if the user enqueues a `parallel_for_work_group` kernel.  I would expect a `parallel_for` with a range of 0 to be submitted as an empty kernel.

**EDIT**: Removed reference to code working with a previous version of the compiler.  Something else in the latest compiler is changing a value in my code to zero (which then leads to this crash).  Leaving this open because I'm curious what the expected behavior is.

**Comment by Pennycook** [comment]
This code no longer crashes, and the expected behavior for a range of zero was clarified in https://github.com/KhronosGroup/SYCL-Docs/pull/192.

**Comment by abagusetty** [comment]
Hi @Pennycook The CUDA, L0, HIP, OpenCL plugins all [asserts](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/scheduler/commands.cpp#L1958) to the `zero` range launches. 

```bash
llvm/sycl/source/detail/scheduler/commands.cpp:1958: void sycl::_V1::detail::adjustNDRangePerKernel(sycl::_V1::detail::NDRDescT&, sycl::_V1::detail::pi::PiKernel, const sycl::_V1::detail::device_impl&): Assertion `NDR.NumWorkGroups[0] != 0 && NDR.LocalSize[0] == 0' failed.
Aborted
```
I was wondering if you can confirm this on any backend and if assert is the case, may be this issue needs to be reopened ?

**Comment by Pennycook** [comment]
> I was wondering if you can confirm this on any backend and if assert is the case, may be this issue needs to be reopened ?

The reproducer from the start of this issue works on my current installation across multiple backends.

Can you share a reproducer that triggers the `assert`?

**Comment by abagusetty** [comment]
I have used the exact one from above with just one change: `<sycl/sycl.hpp>` header. 

It is so strange, I've just built the compiler for CUDA backend and tested it on A100, also tested L0 build on a intel gpu too (both with L0 and OCL backend). All these tests asserts.  

But even more strangely, when I used the NDA-version of SDK we get at ANL (JLSE), everything seems to be fine on Intel hardware. The kernel behaves as expected, (i.e., no assert). Not sure how to approach this.

**Comment by Pennycook** [comment]
> It is so strange, I've just built the compiler for CUDA backend and tested it on A100, also tested L0 build on a intel gpu too (both with L0 and OCL backend). All these tests asserts.

I suspect that the difference is in how the SYCL library is being built.  If you build in "Debug" mode, the `assert` will trigger; if you build in "Release" mode, the `NDEBUG` macro is defined and so the `assert` is removed.

**Comment by abagusetty** [comment]
@Pennycook I was building the compiler in Release mode.

For the above test snippet: It looks like it will trigger the assert from this [line](https://github.com/abagusetty/llvm/blob/sycl/sycl/source/detail/scheduler/commands.cpp#L1958). Since these variables `NDR.GlobalSize[0]`, `NDR.NumWorkGroups[0]` and `NDR.LocalSize[0]` were set to zero for an empty-kernel.

Can you please confirm the expected behavior @AerialMantis from the discussion: https://github.com/KhronosGroup/SYCL-Docs/pull/192
