### ISSUE TITLE
[SYCL] Manual direction via -I parameter sycl headers in build directory.

### ISSUE THREAD

**Issue by fadeeval** [intel/llvm#1732]
Manual direction via -I parameter sycl headers in build directory doesn't do them non-system.

Signed-off-by: Aleksander Fadeev aleksander.fadeev@intel.com

**Comment by fadeeval** [comment]
The fallowing RUN string doesn't show sycl header warnings:

`// RUN: %clangxx -fsycl -I /path/to/sycl/headers/in/build/directory -Wall -Wextra  %s -o %t.out`

**Comment by bader** [comment]
> The fallowing RUN string doesn't show sycl header warnings:
> 
> `// RUN: %clangxx -fsycl -I /path/to/sycl/headers/in/build/directory -Wall -Wextra %s -o %t.out`

It's not supposed to show warnings in SYCL headers because `-fsycl` makes them system headers.
Please, try w/o `-fsycl` option.
