### ISSUE TITLE
llvm-spirv/test/DebugInfo/DebugDeclareUnused.cl is failing after LLVM pulldown

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#1744]
During pull down (https://github.com/intel/llvm/pull/1745) the test has been XFAILed (119b4b11).
The issue has been created to find root cause and provide proper fix.

**Comment by AlexeySotkin** [comment]
To be fixed by https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/549

**Comment by vladimirlaz** [comment]
The fix was cherry-picked in 7e078f7
