### ISSUE TITLE
[SYCL][CI] Provide Windows GPU driver download source in llvm/buildbot/dependency.conf

### ISSUE THREAD

**Issue by kbobrovs** [intel/llvm#1753]
llvm/buildbot/dependency.conf contains:
```
# https://downloadcenter.intel.com/download/29557/Intel-Graphics-Windows-10-DCH-Drivers
ocl_gpu_rt_ver_win=ci-neo-015900
```
The above web page does not contain any links matching the provided version id "ci-neo-015900". Examples of ids found on the web page: "Version: 27.20.100.8190 (Latest)"

So it is not clear how to use the info in dependency.conf to download specific Windows GPU driver version used in CI.

**Comment by vladimirlaz** [comment]
this is first version and the link is closest version. The file is going to be updated with the next release.

**Comment by AlexeySachkov** [comment]
Looks like it is fixed already:

https://github.com/intel/llvm/blob/304067c7d54b8ccaeff52e056753b7d894fa976f/buildbot/dependency.conf#L9-L11
