### ISSUE TITLE
[DPCPP] 'fmax' built-in is not supported

### ISSUE THREAD

**Issue by LeicongLi** [intel/llvm#1790]
Hi DPCPP developers

  Ran into an issue when trying to switch from computecpp to dpcpp. 
  The built-in math function fmax works fine when compiling with computecpp, and throwing an error when using dpcpp. Is there difference with using built-in math functions between computecpp and dpcpp. Please take a look, and help to point a direction?

Thanks

**DPCPP Build info:**
Intel(R) oneAPI DPC++ Compiler 2021.1-beta06 (2020.4.0.0415)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/inteloneapi/compiler/latest/linux/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Error Message:**
error: builtin is not supported on this target deviceAccessorA[index] = fmax(3, 10);

**Sample code:**
```
#include <CL/sycl.hpp>
#include <iostream>
#include <array>
#include <cstdio>

#define SIZE 1024

int main() {
  std::array<int, SIZE> myArray;
  for(int i = 0; i < SIZE; ++i)
    myArray[i] = i;
  {
    cl::sycl::queue myQ;
    cl::sycl::range<1> mySize{SIZE};
    cl::sycl::buffer<int, 1> bufferA(myArray.data(), mySize);

    myQ.submit([&](cl::sycl::handler &myHandle) {
      auto deviceAccessorA =
        bufferA.get_access<cl::sycl::access::mode::read_write>(myHandle);
      myHandle.parallel_for<class uniqueID>(mySize,
        [=](cl::sycl::id<1> index)
        {
          deviceAccessorA[index] = fmax(3, 10);
        });
    });
  }
}
```

**Compile command:**
dpcpp file_name.cpp

**Comment by MrSidims** [comment]
Hi, I think you shall use cl::sycl::fmax instead.

**Comment by LeicongLi** [comment]
Hihi, thanks for your suggestion, it throws an error says fmax could not be found.
![image](https://user-images.githubusercontent.com/24490992/83405871-0cede180-a440-11ea-9a5c-6ad50eb475e8.png)

**Comment by LeicongLi** [comment]
Thanks.
Ahh, stupid me!

**Comment by MrSidims** [comment]
> Thanks.

You are welcome!

> Ahh, stupid me!

I'm not an expert in computecpp implementation, but I can imagine that in dpcpp there is not obvious ambiguity for built-ins that are declared in clang and that are implemented in out headers - for that they are placed in cl::sycl:: namespace.
