### ISSUE TITLE
[SYCL] DPC++ CCache Support

### ISSUE THREAD

**Issue by ax3l** [intel/llvm#1797]
Hi,

although this probably needs a change in [`ccache`](https://ccache.dev/) ([repo](https://github.com/ccache/ccache)) itself: are there plans to support `dpcpp` with `ccache`? Just opening this to indicate that we (cc @WeiqunZhang) rely on it heavily for productive development workflows.

Thanks for considering!

**Comment by AlexeySachkov** [comment]
Hi @ax3l, 

I did some experiments with `ccache` some time ago using simple SYCL/DPC++ apps and I was able to do so just fine.
A few notable moments, though:

`ccache` which is available in Ubuntu 20 repos is a bit outdated (for me it was `3.4.1`) and [per the docs](https://ccache.dev/manual/3.4.1) it doesn't have a mechanism to tell which kind/type of compiler is being used - that version was mainly designed for `gcc` and not for `clang`.

So, I've updated it to the latest `4.2.1` and used `compiler_type` configuration option to tell the tool that `dpcpp` is a `clang`-based compiler - this setup worked just fine on a simple app.

Could you please try it yourself and see if it works for you? I haven't used `ccache` so I don't know what are regular and most popular use-cases to test them myself.

**Comment by WeiqunZhang** [comment]
I can confirm that `ccache` and `dpcpp` now work for me.  I am using ccache 4.3 and oneAPI 2021.2.0.  I am also using it without specifying `compiler_type`.  It seems to just work fine.

**Comment by ax3l** [comment]
Awesome, thanks a lot for testing and confirming!
