### ISSUE TITLE
[SYCL][FE] Disable #pragma syntax for SYCL attributes

### ISSUE THREAD

**Issue by kbobrovs** [intel/llvm#1813]
Per @erichkeane:
> we don’t expect/don’t want people to start using pragma spellings, we want them to exclusively use the attribute spellings.

Attributes which allow that are listed in:
https://github.com/intel/llvm/blob/sycl/clang/test/Misc/pragma-attribute-supported-attributes-list.test

**Comment by erichkeane** [comment]
Basically all of the SYCL attributes should not permit a pragma spelling, so they should not be required to be on this list.  I don't remember how to exclude pragma spellings, but @smanna12 might be able to give advise to whoever picks this up.

**Comment by MrSidims** [comment]
> how to exclude pragma spellings

One needs to set `let PragmaAttributeSupport = 0` for each attribute in Attr.td.

**Comment by MrSidims** [comment]
Well, since I've raised it here: https://github.com/intel/llvm/pull/1754#pullrequestreview-420840994 I don't mind to pick it up.

**Comment by smanna12** [comment]
> > how to exclude pragma spellings
> 
> One needs to set `let PragmaAttributeSupport = 0` for each SYCL attribute in Attr.td.

Yes, this needs to be set.

**Comment by keryell** [comment]
Do no derail from the final goal of SYCL: pure C++!

So
> we don’t expect/don’t want people to start using pragma spellings, we want them to exclusively use the attribute spellings.

should be rather "we want them to avoid using pragma or attrribute". :-)
