### ISSUE TITLE
DPC++ Feature Testing

### ISSUE THREAD

**Issue by ax3l** [intel/llvm#1825]
Hi,

it would be great for us if DPC++ and general SYCL extension features can be detected via macro and/or other feature tests in codes.

Currently, out of the list in here https://spec.oneapi.com/versions/latest/elements/dpcpp/source/index.html it seems that only `SYCL_INTEL_unnamed_kernel_lambda` has a feature test macro (`__SYCL_INTEL_UNNAMED_LAMBDA__`), but I might be missing something.

This would help us downstream developers to test proposed SYCL features with simple fallback paths for various SYCL compilers.

Refs.:
- ISO C++ feature tests: https://en.cppreference.com/w/cpp/feature_test
- full list: https://spec.oneapi.com/versions/latest/elements/dpcpp/source/index.html
- unnamed lambda example: https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/UnnamedKernelLambda/SYCL_INTEL_unnamed_kernel_lambda.asciidoc

**Comment by bader** [comment]
@ax3l, thanks for the feedback.
We discussed this topic here: https://github.com/intel/llvm/issues/806 and @AlexeySachkov prepared a PR with the detailed proposal: https://github.com/intel/llvm/pull/1793.
Please, let us know if it doesn't fit your needs.

**Comment by ax3l** [comment]
Thanks a lot @bader, I will close this as duplicate and contributed additional thoughts in both the issue and PR :)
