### ISSUE TITLE
LIT XFAIL spec_const tests passing with Intel OpenCL GPU 20.19.16754

### ISSUE THREAD

**Issue by bjoernknafla** [intel/llvm#1873]
After noticing in [buildbot/dependency.conf](https://github.com/intel/llvm/blob/sycl/buildbot/dependency.conf#L7) to update to the Intel OpenCL GPU driver 20.19.16754 I am now seeing two LIT XFAILs for OpenCL pass:

```sh
cd <BUILD-DIR>
./bin/llvm-lit -a -v tools/sycl/test --param SYCL_BE=PI_OPENCL --filter=.*spec.*

...

Unexpectedly Passed Tests (2):
  SYCL :: spec_const/spec_const_hw.cpp
  SYCL :: spec_const/spec_const_redefine.cpp
```
Current tip commit: da6bfd0d9368b83ce2dc153de1b78443a30fd689

However, I do not see them pass in the PR buildbot runs and try to figure out if to update to the newer driver, or not.

Are these expected with the mentioned driver version?
Are the buildbot machines using a different driver version?

**Comment by bader** [comment]
I suppose these tests still fail on non-GPU devices.
The buildbot expects these tests to pass on all the configured devices.

Feel free to adjust the XFAIL pattern to fix status on your configuration.

**Comment by bjoernknafla** [comment]
From what I see they are passing now for all OpenCL devices (though I do not have access to an FPGA for testing).

Do you want me to open a PR that removes the XFAILs - although I expect this to then fail the buildbots?

**Comment by bader** [comment]
I was thinking about something like this:
```
// XFAIL: linux && opencl && !gpu && !cpu
```

**Comment by bjoernknafla** [comment]
@bader That is a neat idea! PR with your idea is here: #1875
