### ISSUE TITLE
predefined macros question

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#1894]
Are there predefined DPC++ specific macros people can use in a SYCL program ?  I ask the question because some features are not supported by codeplay's compiler. 
```
#ifdef __DPCPP__

#endif 
```
Thanks

**Comment by MrSidims** [comment]
Hi,

I don't think that we have a specifically designed macro for that, but in the same time we have macro `__SYCL_COMPILER_VERSION` and I doubt that other compilers has it, so I can imagine it be used for such purposes.
