### ISSUE TITLE
【Install】The Source directory “/.../llvm/build/4" does not  exist

### ISSUE THREAD

**Issue by Chenzejun-Dummkopf** [intel/llvm#1901]
I install llvm and dpcpp.
But when i run 'python $DPCPP_HOME/llvm/buildbot/compile.py' in the command line, the error occurs. It is :
'CMake Error: The source directory "/home/ddd/Desktop/sycl_workspace/llvm/build/4" does not exist. Specify --help for usage, or press the help button on the CMake GUI.'
Thus, i come here to figure it out.

**Comment by bader** [comment]
@Chenzejun-Dummkopf, could you clarify what are your trying to achieve?
Isn't having dpcpp installed enough for you?

**Comment by Chenzejun-Dummkopf** [comment]
> @Chenzejun-Dummkopf, could you clarify what are your trying to achieve?
> Isn't having dpcpp installed enough for you?

Hi, thank you for your attention. I clarify what i am trying to achieve.
I want to use 'clang -fsycl helloworld.cpp' to compile the sycl program. So I need to install oneAPI DPCPP with the install guide from the link 'https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#run-simple-dpc-application'.

My machine is vmware ubuntu 16.04 and the cpu is intel i5 7th. Then i follow the guide.
1. export DPCPP_HOME=~/sycl_workspace
    mkdir $DPCPP_HOME
    cd $DPCPP_HOME
    git clone https://github.com/intel/llvm -b sycl
These are all done successfully.

2. python $DPCPP_HOME/llvm/buildbot/configure.py
    Then i choose to configure. The problem is:
    'HAVE_GNU_POSIX_REGEX --Performing Test Failed'

**Comment by alexbatashev** [comment]
@Chenzejun-Dummkopf if you only need a pre-built version of the compiler, you can take nightly builds: https://github.com/intel/llvm/releases

Otherwise, you can try supplying the following options to both of the scripts to make sure they pick right locations:
`-s <path to source dir>`
`-o <path to build dir>`

**Comment by Chenzejun-Dummkopf** [comment]
> @Chenzejun-Dummkopf if you only need a pre-built version of the compiler, you can take nightly builds: https://github.com/intel/llvm/releases
> 
> Otherwise, you can try supplying the following options to both of the scripts to make sure they pick right locations:
> `-s <path to source dir>`
> `-o <path to build dir>`

Thank you for your help. I want to compile my sycl file.
I download the released llvm. However, when i run 'bash startup.sh', i have some trouble. The log is:
'startup.sh: line 9: /home/ddd/dpcppCompiler/dpcpp_compiler/lib/oclfpga/fpgavars.sh: No such file or directory.'

The second problem is that i don't know how to use this released chain.
When i run '/home/ddd/dpcppCompiler/dpcpp_compiler/bin/clang -fsycl Mysycl.cpp', the problem occurs.  It is:
'./clang: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./clang).'

So, i need to update the libstdc++.so.6.
After finishing the update, i run the command '/home/ddd/dpcppCompiler/dpcpp_compiler/bin/clang -fsycl Mysycl.cpp'.
Then i get the file 'a.out'.
I run './a.out', then './a.out: error while loading shared libraries: libsycl.so.1: cannot open shared object file: No such file or directory'.

**Comment by alexbatashev** [comment]
> I run './a.out', then './a.out: error while loading shared libraries: libsycl.so.1: cannot open shared object file: No such file or directory'.

I think our [FAQ](https://intel.github.io/llvm-docs/FAQ.html#q-dpc-application-complains-about-missing-libsycl-so-or-sycl-dll-library) guide answers this question.

**Comment by Chenzejun-Dummkopf** [comment]
Really thank you for your help! Now i can compile my sycl.cpp file.
However, i create a simple sycl file by using the gudie named 'sycl-1.2.1.pdf'.
The code of my sycl file is:
`#include <CL/sycl.hpp> 
#include <iostream> 
int main() { 
using namespace cl::sycl; 
int data[1024]; 
{  
queue myQueue; 
buffer<int, 1> resultBuf { data, range<1> { 1024 } }; 
myQueue.submit([&](handler& cgh) { 
auto writeResult = resultBuf.get_access<access::mode::discard_write>(cgh); 
cgh.parallel_for<class simple_test>(range<1> { 1024 }, [=](id<1> idx) { 
writeResult[idx] = idx[0]; 
}); 
}); 
} 
for (int i = 0; i < 1024; i++) 
std::cout << "data[" << i << "] = " << data[i] << std::endl;  
return 0; 
}`

Then i compile it to get the a.out. I run the a.out and get the log, which is 'Segmentation fault'.
Why?

**Comment by Chenzejun-Dummkopf** [comment]
I locate the bug, which is occurs in the code
`cgh.parallel_for(range<1> { 1024 }, [=](id<1> idx) {writeResult[idx] = idx[0];});`
I don't know why the parallel_for will cause the bug 'segmentation fault'.

My machine is ubuntu16.04 and intel i5 7th. No cuda. No gpu.

**Comment by Chenzejun-Dummkopf** [comment]
Another some questions. 
1. Must the SYCL kernel function be compiled using a device compiler?
2. What are the host code and the device code?
3. The llvm clang compiler tool is used for host or device?
Really appreciate for your help.

**Comment by alexbatashev** [comment]
> Really thank you for your help! Now i can compile my sycl.cpp file.
> However, i create a simple sycl file by using the gudie named 'sycl-1.2.1.pdf'.
> The code of my sycl file is:
> #include <CL/sycl.hpp>
> #include
> int main() {
> using namespace cl::sycl;
> int data[1024];
> {
> queue myQueue;
> buffer<int, 1> resultBuf { data, range<1> { 1024 } };
> myQueue.submit([&](handler& cgh) {
> auto writeResult = resultBuf.get_accessaccess::mode::discard_write(cgh);
> cgh.parallel_for(range<1> { 1024 }, [=](id<1> idx) {
> writeResult[idx] = idx[0];
> });
> });
> }
> for (int i = 0; i < 1024; i++)
> std::cout << "data[" << i << "] = " << data[i] << std::endl;
> return 0;
> }
> 
> Then i compile it to get the a.out. I run the a.out and get the log, which is 'Segmentation fault'.
> Why?

I'm afraid, the provided info is not enough to debug this issue. A bit more information about your system, stacktrace, [PI trace](https://intel.github.io/llvm-docs/EnvironmentVariables.html) would be helpful.

> Must the SYCL kernel function be compiled using a device compiler?

As log as you want to run your code on an accelerator device, yes. If you only require host code, there's no need to use any special compiler.

> What are the host code and the device code?

DPC++ inherits SYCL's single source model. Whenever you write a compute kernel, the device compiler is able to extract it from your code and compiler for the device target (those are currently SPIR-V, x86_64, vISA, and PTX). You can find out more about SYCL programming model in section 3.6 of the [specification](https://www.khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf).

> The llvm clang compiler tool is used for host or device?

[Both](https://intel.github.io/llvm-docs/FAQ.html#q-what-do-i-need-to-start-developing-with-dpc)

**Comment by Chenzejun-Dummkopf** [comment]
**Thank you so much for your help.**
My code is the example of the section 3.2 of the SYCL [specification](https://www.khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf). 
**Could this code only be compiled by host compiler and be only executed on host ?**
I know the class name in the parallel_for method is used to link the kernel and the host code.
**I wonder if the kernel only can be executed on the device. Could Intel CPU be both the host and device?**
Thank you so much.

**Comment by alexbatashev** [comment]
> Could this code only be compiled by host compiler and be only executed on host ?

Yes, you need to point your host compiler (which can be any C++ compiler) to SYCL include and library locations and link your application against libsycl.so. Refer to your compiler manual on how to do that. Please note, that our current implementation doesn't fully support host device.

> Could Intel CPU be both the host and device?

Yes. To expose Intel CPU as a device you need an OpenCL CPU Runtime. Our [Getting Started guide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime) has installation instructions. Host device does not require any low level runtimes and is always available.

**Comment by Chenzejun-Dummkopf** [comment]
Thank you so much for your attention and help. Your answer indeedly helps me to successfully run my first SYCL example. After installing the OpenCL CPU Runtime, my code runs successfully. Last three questions about the base knowledege.
1. How to understand the meaning of the 'low level runtimes'? Does high level runtimes exist?
2. How to compute the running time of the SYCL code? How to evaluate the performance of SYCL code?
3. Where can i get the more examples of the SYCL code for learning? Official example better.
Really appreciate your answer!

**Comment by MrSidims** [comment]
1. SYCL/DPCPP runtime can be considered as a 'high level' runtime. It's self-sufficient for execution of a program on host device. When you want to run the program on any other device - you need a 'low level' runtime to be installed, for example for CPU it shall be OpenCL CPU runtime.
2. I personally used perf and vtune for such purposes. Guess, more info (and tools themselves) can be found here https://software.intel.com/content/www/us/en/develop/tools/oneapi.html
3. https://github.com/intel/BaseKit-code-samples . Also, in https://software.intel.com/content/www/us/en/develop/tools/oneapi.html there are webinars and other trainings.

**Comment by Chenzejun-Dummkopf** [comment]
Thank you for your help!

I find more examples in [Basekit_Example](https://github.com/intel/BaseKit-code-samples).
The examples in the Basekit_Example needs to be compiled by Intel® oneAPI DPC++ Compiler.
I use the 'make all' to compile it, however, 
'dpcpp -g -o bin/simple-vector-incr src/simple-vector-incr.cpp -lOpenCL -lsycl
make: dpcpp: Command not found
Makefile:11: recipe for target 'main' failed
make: *** [main] Error 127'.

I have installed the release compiler from [Release DPCPP
 Compiler](https://github.com/intel/llvm/releases/tag/20200618) and the OpenCL CPU runtime.
Why i only can compile the sycl file with 'clang++ -fscyl'?
Why i missing the compiler 'dpcpp'?
What are the differences between the compiler 'clang++ -fsycl' and the compiler 'dpcpp'?

**Comment by alexbatashev** [comment]
> Thank you for your help!
> 
> I find more examples in [Basekit_Example](https://github.com/intel/BaseKit-code-samples).
> The examples in the Basekit_Example needs to be compiled by Intel® oneAPI DPC++ Compiler.
> I use the 'make all' to compile it, however,
> 'dpcpp -g -o bin/simple-vector-incr src/simple-vector-incr.cpp -lOpenCL -lsycl
> make: dpcpp: Command not found
> Makefile:11: recipe for target 'main' failed
> make: *** [main] Error 127'.
> 
> I have installed the release compiler from [Release DPCPP Compiler](https://github.com/intel/llvm/releases/tag/20200618) and the OpenCL CPU runtime.
> Why i only can compile the sycl file with 'clang++ -fscyl'?
> Why i missing the compiler 'dpcpp'?
> What are the differences between the compiler 'clang++ -fsycl' and the compiler 'dpcpp'?

`dpcpp` is a custom compiler driver provided by [Intel oneAPI Base Toolkit](https://software.intel.com/content/www/us/en/develop/tools/oneapi.html). It is not available on the open-source version of the compiler. `dpcpp` shortcuts some of the most commonly used options to the `clang++`, like `-fsycl`.

**Comment by Chenzejun-Dummkopf** [comment]
Really appreciate it. Thank you! :)

1. Is the dpcpp code based on the SYCL code? In another word, the dpcpp is developed from SYCL by Intel. Is my understanding right?

2. Where can i learn dpcpp?

**Comment by alexbatashev** [comment]
> Really appreciate it. Thank you! :)
> 
> 1. Is the dpcpp code based on the SYCL code? In another word, the dpcpp is developed from SYCL by Intel. Is my understanding right?
> 2. Where can i learn dpcpp?

[Intel website](https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit.html) contains a rich set of training materials that should answer both of your questions. You may also want to get familiar with [oneAPI Data Parallel C++ specification](https://spec.oneapi.com/versions/latest/elements/dpcpp/source/index.html#overview).

**Comment by Chenzejun-Dummkopf** [comment]
Thank you so much for your meaningful help. :)
Really appreciate that.
