### ISSUE TITLE
[SYCL] Handler2 Copy Clarification/Possible bug

### ISSUE THREAD

**Issue by agozillon** [intel/llvm#191]
```
#include <vector>
#include <CL/sycl.hpp>

int main()
{
  const size_t nElems = 10u;

  std::vector<int> v(nElems);
  std::iota(std::begin(v), std::end(v), 0);

  buffer<int, 1> b{cl::sycl::range<1>(nElems)};

  cl::sycl::queue q;
  q.submit([&](handler& cgh) {
     accessor<int, 1, access::mode::write, access::target::global_buffer>
        acc(b, cgh, range<1>(nElems / 2), id<1>(0));

      cgh.copy(v.data(), acc);
  });

  q.wait();

  return 0;
}
```

So, I'm not entirely sure this is a bug, the above example is a slightly altered variation of this spec example: https://github.com/KhronosGroup/SYCL-Docs/blob/master/latex/code/explicitcopy.cpp 

What I've found is that `Handler2`'s copy methods are killing the device compilation for Xilinx devices, while the original `Handler`'s implementations are not. It seems to be because the non-buffer pointer (`v.data()` in the above example) isn't being wrapped in a `buffer` and being passed by `accessor` to the `parallel_for` like it was in the original `Handler` implementation (in our case this means the pointer isn't given an address space and chokes in one of our passes unfortunately).

Is there a reason why it's accessed directly and not via an `accessor` at the moment (even if it's a host side `parallel_for`, the device still has to compile it if I'm not mistaken)? It seems like it's a temporary solution in the **TODO** and will be replaced by an OpenCL call inside `memory_manager.cpp `at some point. So I'm wondering if it's worth implementing a fix for it at the moment or if the update based on the `memory_manager.cpp` is perhaps close to completion?

**Comment by agozillon** [comment]
In hindsight and looking into it a little more after this issue was opened, I'm pretty sure this is more of a problem on our end and I've worked out an easy fix/workaround for it. Sorry for opening up this issue, I'll close this tomorrow around the same time if no one has any problems!

**Comment by bader** [comment]
@agozillon, I haven't looked into this issue yet, so I can't say if there is anything wrong in our implementation or not. @romanovvlad, did you have a chance to look into this issue?

**Comment by asavonic** [comment]
I actually faced a similar issue as well, and applied a workaround in #207

**Comment by agozillon** [comment]
Sorry didn't mean to force you to answer/look into the issue, genuinely thought it was perhaps just something we had to deal with for a little bit (originally thought perhaps something was missing from the old handler when I opened the issue but I was incorrect)!

Yes, I think there just needs to be some host side `copy` methods rather than relying on some parallel_for's that are only used on the host (the `handler`'s `fill` method is also the same at the moment I think). I think the intention is to add them at some point as there is a TODO there though.

We did close to the same work around: https://github.com/triSYCL/sycl/blob/sycl/unified/next/sycl/include/CL/sycl/handler2.hpp#L1058 our backend compiler is very picky, so I thought it was probably just an issue we'd run into and have to deal with for a little while which was why I mentioned closing the issue!

**Comment by bader** [comment]
TODO:
- [ ] commit this test case to our regression test suite

**Comment by romanovvlad** [comment]
> 
> 
> TODO:
> 
>     * [x]  commit this test case to our regression test suite

https://github.com/intel/llvm/blob/sycl/sycl/test/basic_tests/handler/handler_mem_op.cpp

**Comment by bader** [comment]
Fixed by https://github.com/intel/llvm/commit/ff30897111ee8df5551212a758298f5f8c87275f.
@agozillon, please, re-open the issue if it doesn't work for you.
