### ISSUE TITLE
Error cmake could not load VersionFromVCS

### ISSUE THREAD

**Issue by han2291** [intel/llvm#1924]
Hi, great software

I am writing this question because I would like to compile sycl project from source code, however when I am trying to use cmake to compile it I get the following error message:

`CMake Error at CMakeLists.txt:50 (include):
include could not find load file:
VersionFromVCS`

I am using windows 10, so I would like to know if there is a manual or a series of steps to configure the development environment and to be able to compile the sycl library.

Note: I have already compiled llvm, llvm-spiv and clang

Any thoughts will be greatly appreciated.
Best

**Comment by bader** [comment]
Googling this error hints that your system might be missing some of the dependencies.
Have you installed all [pre-requisites](https://intel.github.io/llvm-docs/GetStartedGuide.html#prerequisites)?

If it doesn't help, could you provide a full log, please?

**Comment by han2291** [comment]
I have followed the instructions in the following link: [pre-requisites](https://intel.github.io/llvm-docs/GetStartedGuide.html#prerequisites)
I have installed the requirements software, but I get the following error message

`C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h:29:12: error: 'recursive_mutex' in namespace 'std' does not name a type
   29 |       std::recursive_mutex impl;
      |            ^~~~~~~~~~~~~~~
C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h:19:1: note: 'std::recursive_mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   18 | #include <mutex>
  +++ |+#include <mutex>
   19 |
C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h: In member function 'bool llvm::sys::SmartMutex<mt_only>::lock()':
C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h:35:11: error: 'impl' was not declared in this scope
   35 |           impl.lock();
      |           ^~~~
C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h: In member function 'bool llvm::sys::SmartMutex<mt_only>::unlock()':
C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h:48:11: error: 'impl' was not declared in this scope
   48 |           impl.unlock();
      |           ^~~~
C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h: In member function 'bool llvm::sys::SmartMutex<mt_only>::try_lock()':
C:/Users/hanie/sycl_workspace/llvm/llvm/include/llvm/Support/Mutex.h:62:18: error: 'impl' was not declared in this scope
   62 |           return impl.try_lock();
      |                  ^~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\hanie\sycl_workspace\llvm\buildbot\compile.py", line 63, in <module>
    ret = main()
  File "C:\Users\hanie\sycl_workspace\llvm\buildbot\compile.py", line 59, in main
    return do_compile(args)
  File "C:\Users\hanie\sycl_workspace\llvm\buildbot\compile.py", line 37, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "C:\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'C:\\Users\\hanie\\sycl_workspace\\llvm\\build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '4']' returned non-zero exit status 1.`

I Attach the complete cmake log file: [CMakeOutput.log](https://github.com/intel/llvm/files/4805131/CMakeOutput.log)

**Comment by bader** [comment]
Sorry for the delay. It looks like CMake picked up GCC compiler instead of MSVC.
Do you run commands from VS command prompt?
An excerpt from Get Started Guide:
```
Open a developer command prompt using one of two methods:

Click start menu and search for “x64 Native Tools Command Prompt for VS XXXX”, where XXXX is a version of installed Visual Studio.

Ctrl-R, write “cmd”, click enter, then run "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
```
