### ISSUE TITLE
[SYCL][SUBGROUPS] support load of complex data type 

### ISSUE THREAD

**Issue by psteinbrecher** [intel/llvm#1946]
Support subgroup loads from a complex pointer ptr that has the memory layout:

ptr = { real0, imag0, real1, imag1, ... , ... }

A single work-item should get {real0, imag0} returned from a subgroup load.

**Comment by Pennycook** [comment]
I think that the new [sycl_ext_oneapi_group_load_store](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_group_load_store.asciidoc) extension provides this functionality.

`std::complex` satisfies trivially copyable and default constructible, so it should be compatible with the default "single value" overloads.  Alternatively, the new block-load option would provide a way to load pairs of floats into a `vec` or `marray`, which could then be assigned to a `std::complex`.

@aelizaro, do you agree?  If so, I'll close this.
