### ISSUE TITLE
[SYCL] custom group reductions

### ISSUE THREAD

**Issue by psteinbrecher** [intel/llvm#1947]
Support user defined group reductions similar to:

https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/Reduction/Reduction.md

**Comment by AlexeySachkov** [comment]
Hi @psteinbrecher, I think this is finally comes to life with #7202 and #7436

**Comment by AlexeySachkov** [comment]
I will close this one as implemented. See links to the spec and implementation above.

Please feel free to re-open if you think that proposed solution is not what you requested.
