### ISSUE TITLE
[SYCL] Using NoSignedWrap decoration without declaring SPV_KHR_no_integer_wrap_decoration

### ISSUE THREAD

**Issue by kpet** [intel/llvm#2]
Building [the simple app from the doc](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md#creating-a-simple-sycl-program) results in an invalid SPIR-V module. The `NoSignedWrap` decoration is used but the `SPV_KHR_no_integer_wrap_decoration` isn't declared with an `OpExtension`. Declaring the extension is enough to make the module pass the validator.

**Comment by bader** [comment]
Looks like an issue of [LLVM/SPIR-V translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator). I'll create another issue there.
Thanks for reporting it.

**Comment by bader** [comment]
I think https://github.com/intel/llvm/pull/135 fixed that issue.
@kpet, could you confirm, please?

**Comment by bader** [comment]
I believe this issue is fixed by https://github.com/intel/llvm/pull/135, so I'm closing this issue.
@kpet, feel free to re-open if it doesn't work on your side.
