### ISSUE TITLE
[SYCL] Default selector should filter devices based on available device images

### ISSUE THREAD

**Issue by jbrodman** [intel/llvm#2004]
The default selector should not select a device for which no devices images exist.

Example: Don't pick a CUDA device if there are no PTX modules in the fat binary.  Likewise don't pick a CL device if there are no SPIR-V modules or AOT binary images.

**Comment by bader** [comment]
Related issues: 
- https://github.com/intel/llvm/issues/1665,
- https://github.com/intel/llvm/issues/1588, with the solution prototype https://github.com/intel/llvm/pull/1670.
