### ISSUE TITLE
no support in global stack protection on x86 cpu only TLS

### ISSUE THREAD

**Issue by labba** [intel/llvm#2006]
I’m trying to enable stack protection in and find out that clang always uses TLS for the canary value.Also, the flag that is on GCC to change from TLS to global is: "-mstack-protector-guard=global"  but it is unknown in clang

**Comment by bader** [comment]
@labba, I think it's better to ask this question using official clang communication channels.

cfe-users List - http://lists.llvm.org/mailman/listinfo/cfe-users or IRC: irc.oftc.net#llvm
