### ISSUE TITLE
[SYCL] Bitcode output is only supported with LTO

### ISSUE THREAD

**Issue by huangzhiyuan** [intel/llvm#2074]
I want to use clang++ compiler generate `LLVM IR` and `SPIR-V` file. but got error like below:
```
huang@pc:~$ clang++ -emit-llvm -c test.cpp -fsycl -fsycl-unnamed-lambda
error: Bitcode output is only supported with LTO.
1 error generated.

```
any suggestions for this ? thanks!

**Comment by bader** [comment]
I assume you are using `clang++` from oneAPI toolchain. The compiler built from the `sycl` branch can emit LLVM IR just fine.

NOTE: you probably wanted to get LLVM IR and SPIR-V for "device code". Right?
If so, you should add `-fsycl-device-only` option as documented here: https://intel.github.io/llvm-docs/UsersManual.html#sycl-device-code-compilation
