### ISSUE TITLE
[SYCL][Level 0] Inefficient device lookup

### ISSUE THREAD

**Issue by jbrodman** [intel/llvm#2113]
The Level 0 plugin should cache ze device handles->_pi_device objects so it doesn't create a new _pi_device every time you query what devices exist in the system.

**Comment by gmlueck** [comment]
Maybe the caching should be one layer up in the general SYCL runtime.  That way, the caching will work for all of the backends.

**Comment by jbrodman** [comment]
My PR already does that - but it requires that you actually have stable device handles to compare otherwise you can't cache.

**Comment by alexbatashev** [comment]
This seems to be fixed now. Please, re-open if you disagree.

tagging @smaslov-intel
