### ISSUE TITLE
[SYCL][CUDA] 7/14 accessor tests fail when compiled into a single executable

### ISSUE THREAD

**Issue by againull** [intel/llvm#2118]
**Build compiler**
git clone https://github.com/intel/llvm
Hash: b00fb7cd42f6790e9f4eea5abfdd24939f2b63e1

Includes: https://github.com/intel/llvm/pull/1990, https://github.com/intel/llvm/pull/1977

python /localdisk2/ws/againull/sycl/llvm/buildbot/configure.py --cuda -o /localdisk2/ws/againull/sycl/build
python /localdisk2/ws/againull/sycl/llvm/buildbot/compile.py -o /localdisk2/ws/againull/sycl/build

**Build accessor CTS tests**
git clone https://github.com/KhronosGroup/SYCL-CTS.git
Hash: 9cbe1a719b25c269ef78a2ee08f2e5ed12a1cc6d

Applied: https://github.com/KhronosGroup/SYCL-CTS/pull/52

cmake -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DINTEL_SYCL_ROOT=/localdisk2/ws/againull/sycl/build -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda-sycldevice  -DSYCL_IMPLEMENTATION=Intel_SYCL -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On -DINTEL_SYCL_FLAGS="-Xsycl-target-backend;--cuda-gpu-arch=sm_50" -DOpenCL_INCLUDE_DIR=/localdisk2/ws/againull/sycl/build/include/sycl -DOpenCL_LIBRARY=/localdisk2/ws/againull/sycl/build/lib/libOpenCL.so ..

ninja test_accessor -j 12

**Run CTS tests**
 ./bin/test_accessor -p nvidia -d opencl_gpu
7/14 tests are failing: 
[test_accessor.log](https://github.com/intel/llvm/files/4923514/test_accessor.log)

If each test is compiled to a separate binary (not to a single binary) then 13/14 tests pass (only accessor_api_image is failing - separate issue).
For example, if remove all cpp files from tests/accessor except accessor_api_buffer.cpp.
And run cmake/ninja as described above, accessor_api_buffer test will pass.

There is an issue when all accessor tests are compiled into a single executable.

**Comment by bader** [comment]
@againull, @pvchupin, I think we figured out that this was caused by the regression in the driver. Can we close this one?

**Comment by againull** [comment]
Yes, problem does't reproduce on 435.21 nvidia driver.
