### ISSUE TITLE
[SYCL] <type_traits> compile error with -std=gnu++11 flag

### ISSUE THREAD

**Issue by pkeir** [intel/llvm#212]
An odd one here: adding the `-std=gnu++11` flag to the sycl compile command produces the error below. (This occurred unexpectedly within a build script in our project.) The `sycl-gnu++11.cpp` input file contains only `#include <type_traits>` and the invocation is:

`clang++ -std=c++11 -fsycl -std=gnu++11 -c sycl-gnu++11.cpp`

```
In file included from sycl-gnu++11.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits:335:39: error: __float128 is not supported on this target
    struct __is_floating_point_helper<__float128>
                                      ^
1 error generated.
In file included from sycl-gnu++11.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits:335:39: error: __float128 is not supported on this target
    struct __is_floating_point_helper<__float128>
                                      ^
1 error generated.
```

**Comment by bader** [comment]
@pkeir, this issue should have been fixed by https://github.com/intel/llvm/commit/047bfeaf72b4f4ecf926073c3c4d835015854d80.

I think we should add a regression test to check that enabling GNU extensions do not break SYCL code compilation.
