### ISSUE TITLE
Compiler does not allow function multi-versioning in host code

### ISSUE THREAD

**Issue by krasznaa** [intel/llvm#2128]
Dear All,

I'm running into an issue with building SYCL code against our code base. In it we use function multi-versioning for some very performance critical functions. And if I let `clang++` see the declaration of such a multi-versioned function, it does not want to continue. Even though I (of course) don't try to use such a function in device code.

This is a small example:

```c++
// Copyright (C) 2002-2020 CERN for the benefit of the ATLAS collaboration

// System include(s).
#undef NDEBUG
#include <cassert>
#include <iostream>

/// Do we have function multiversioning  GCC and Clang > 7 support __attribute__ target
#if defined(__ELF__) && defined(__GNUC__) && !defined(__CLING__) && !defined(__ICC) && \
  !defined(__COVERITY__) && !defined(__CUDACC__) && !defined(SPIR)
# define HAVE_FUNCTION_MULTIVERSIONING 1
#else
# define HAVE_FUNCTION_MULTIVERSIONING 0
#endif

// Use popcnt instruction if available.  This ugliness needed
// because our default compilation options do not enable
// use of this instruction.
#if HAVE_FUNCTION_MULTIVERSIONING
/**
 * @brief Count the number of 1 bits in the set.
 */
__attribute__ ((target ("popcnt")))
unsigned int count() {
  return 2;
}
/**
 * @brief Count the number of 1 bits in the set.
 */
__attribute__ ((target ("default")))
#endif
unsigned int count() {
  return 2;
}

int main() {

  // Use the multi-versioned function in host code.
  assert( count() == 2 );
  std::cout << "count() = " << count() << std::endl;

  // Return gracefully.
  return 0;
}
```

As you can see, it doesn't even call any SYCL functions. But if I try to compile this code with `-fsycl`, I get the following:

```
[bash][Legolas]:oneAPI > clang++ -fsycl -o sycl_function_multiversioning sycl_function_multiversioning.cxx
sycl_function_multiversioning.cxx:33:14: error: function multiversioning is not supported on the current target
unsigned int count()
             ^
sycl_function_multiversioning.cxx:24:14: note: previous declaration is here
unsigned int count()
             ^
1 error generated.
[bash][Legolas]:oneAPI >
```

As you can see, I even thought that maybe this is just an issue while the compiler is generating device code. So I tried to use the `SPIR` definition to turn off multi-versioning support explicitly for the device code. But that made no difference. :frowning:

It would really help us a lot if we wouldn't have to give up on this Clang feature when building our code with "SYCL parts enabled".

Pinging @ivorobts, @cleggett, @vpascuzz.

Cheers,
     Attila

**Comment by bader** [comment]
You can check if SYCL mode is enabled or not by adding `&& !defined(CL_SYCL_LANGUAGE_VERSION)`.

BTW, when we compile for SPIR target, compiler defines `__SPIR__` macro, not `SPIR`.

**Comment by krasznaa** [comment]
Interesting. I got `SPIR` from:

```
[bash][Legolas]:~ > clang++ -fsycl -o - -dM -E - < /dev/null

// __CLANG_OFFLOAD_BUNDLE____START__ sycl-spir64-unknown-unknown-sycldevice
#define CL_SYCL_LANGUAGE_VERSION 121
#define SPIR 1
#define SPIR64 1
#define SYCL_EXTERNAL __attribute__((sycl_device))
#define _LP64 1
...
```

But exchanging `SPIR` for `__SPIR__` or `CL_SYCL_LANGUAGE_VERSION` both seem to work. (I guess `CL_SYCL_LANGUAGE_VERSION` is the more generic one, in case the SYCL compilation is not happening for a SPIR target.)

Thanks! I'll experiment a bit with those flags. (Since in order to get multi-versioning functional, I still have to separate all my host code that wants to use such things, into source files that are **not** compiled with `-fsycl`.)

**Comment by krasznaa** [comment]
I should've closed this issue a while ago... The suggested solution with `CL_SYCL_LANGUAGE_VERSION` works fine. (See https://gitlab.cern.ch/atlas/athena/-/merge_requests/35624 if you're interested in the full context in our code.)
