### ISSUE TITLE
[SYCL][CUDA] Build failure

### ISSUE THREAD

**Issue by tomdeakin** [intel/llvm#2130]
I'm seeing an error on building today's version 55eef6c5b56e39627e0ec47396ffd1ff59256668

```
CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda
CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/compile.py
```
```$ gcc --version
gcc (GCC) 8.2.0
```

```/home/br-tdeakin/software/dpcpp/llvm/sycl/plugins/cuda/pi_cuda.cpp: In function ‘pi_result cuda_piMemBufferPartition(pi_mem, pi_me
m_flags, pi_buffer_create_type, void*, _pi_mem**)’:
/home/br-tdeakin/software/dpcpp/llvm/sycl/plugins/cuda/pi_cuda.cpp:1785:67: error: type qualifiers ignored on cast result type [-W
error=ignored-qualifiers]
       *reinterpret_cast<const pi_buffer_region>(buffer_create_info);
                                                                   ^
cc1plus: all warnings being treated as errors
```

**Comment by bader** [comment]
@tomdeakin, please, add `--no-werror` to `configure.py`.

**Comment by tomdeakin** [comment]
@bader Thanks, that gets me a bit further.
It then failed to find the Khronos EGL headers - they don't seem to be shipped by CUDA 10.2. So, downloading them and putting the directory in `CPATH` solves that, but then it crashes again building the ICD:
```
/cm/shared/apps/cuda10.2/toolkit/10.2.89/targets/x86_64-linux/include/CL/cl.h:661:2: warning: #warning CL_USE_DEPRECATED_OPENCL_1_
0_APIS is defined. These APIs are unsupported and untested in OpenCL 1.1! [-Wcpp]                                                 
 #warning CL_USE_DEPRECATED_OPENCL_1_0_APIS is defined. These APIs are unsupported and untested in OpenCL 1.1!                    
  ^~~~~~~                                                                                                                         
/lustre/home/br-tdeakin/software/dpcpp/llvm/build/tools/sycl/OpenCL/icd/loader/icd_dispatch.c: In function ‘clSetProgramSpecializa
tionConstant’:                                                                                                                    
/lustre/home/br-tdeakin/software/dpcpp/llvm/build/tools/sycl/OpenCL/icd/loader/icd_dispatch.c:616:60: error: expected declaration 
specifiers before ‘CL_API_SUFFIX__VERSION_2_2’                                                                                    
                                    const void* spec_value) CL_API_SUFFIX__VERSION_2_2                                            
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~                                            

```

**Comment by bader** [comment]
This seems to be a known problem with OpenCL headers provided with CUDA, which are quite old. The recommended fix it to install Khronos OpenCL ICD or Intel OpenCL CPU runtime.
https://intel.github.io/llvm-docs/GetStartedGuide.html#using-the-dpc-toolchain-on-cuda-platforms

**Comment by jeffhammond** [comment]
@bader Given that the recipe Tom and I were using to hit this involves Pythons scripts invoking CMake, there really should be a way to automate the solution, and not require users to install OpenCL headers themselves.

**Comment by npmiller** [comment]
The DPC++ build now automatically fetches the correct version of the OpenCL headers from the Khronos repository and uses them, see:

* https://github.com/intel/llvm/blob/sycl/opencl/CMakeLists.txt

In addition the include path for the downloaded Khronos headers is included before the path to the CUDA headers so these should be correctly picked up over the outdated CUDA headers.

So unless anyone had any issues with this more recently I believe it should be fixed.

**Comment by bader** [comment]
@tomdeakin, do you still have problems with building DPC++ with CUDA back-end?

**Comment by AerialMantis** [comment]
We believe this issue to be resolved now so we're closing the ticket, please see the comment above from @npmiller for details, @tomdeakin if you feel this is still an issue please leave a comment and we will look into it.
