### ISSUE TITLE
llvm and oneMKL beta07

### ISSUE THREAD

**Issue by vpascuzz** [intel/llvm#2211]
Is it expected that llvm built from source is compatible with oneMKL from beta07? It seems only the host device works with the two together.  For example, trying the configuration on my own project, I see:
```
<...>
Device: "Intel(R) Gen9"
Device random number memory allocated...
	num_random: 100000
	size: 400 kb

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  No kernel named _ZTSN3mkl3rng8internal11engine_funcINS0_13philox4x32x10EffNS1_3gpu11uniform_stdIfEELb1EEE was found -46 (CL_INVALID_KERNEL_NAME)
Aborted
```

Thinking this could be a problem specific to my code, compiling and building [1] with the GPU device selector:
```
$ source <...>/inteloneapi/mkl/latest/env/vars.sh
$ clang++ -fsycl -g -std=c++11 -O3 -DMKL_ILP64 pi_mc_oneAPI_usm_allocator.cpp -o pi_mc_oneAPI_usm_allocator.out -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lmkl_sycl
$ ./pi_mc_oneAPI_usm_allocator.out
Number of points = 120000000
MONTE CARLO EVALUATION OF PI
Please wait...
Running on: Intel(R) Gen9
Segmentation fault
```
What’s more, if I use the CPU device selector with [1]:
```
$ ./pi_mc_oneAPI_usm_allocator.out
<…>
terminate called after throwing an instance of 'cl::sycl::runtime_error'
 what():  No device of requested type available. -1 (CL_DEVICE_NOT_FOUND)
Aborted
```
whereas if I use dpcpp from oneAPI beta07 with oneMKL beta07, the build and runtime of [1] is fine. (I need the llvm for my project so this is not a solution for me.)

Thanks in advance,
                Vince.

[1] https://software.intel.com/sites/default/files/managed/15/35/pi_mc_oneAPI_usm_allocator.cpp

**Comment by pvchupin** [comment]
Most likely problem is coming from DPC++ RT ABI changes done between beta07 and top of trunk.

I believe https://github.com/intel/llvm/releases/tag/2020-05 corresponds to beta07. It could help with compatibility issues like that.
Or alternatively oneMKL should be built from source by newer compiler https://github.com/oneapi-src/oneMKL.

**Comment by vpascuzz** [comment]
Hi, @pvchupin.

Thanks for the follow-up!

Unfortunately, https://github.com/intel/llvm/releases/tag/2020-05 doesn't include @Pennycook's extended atomics extensions, and open-source oneMKL doesn't include RNG...

**Comment by vpascuzz** [comment]
Things are OK with oneMKL-beta08.
