### ISSUE TITLE
Enable back hier_par_wgscope_O0.cpp and generic-shuffle.cpp which are temporarily marked as Unsupported

### ISSUE THREAD

**Issue by yinyangsx** [intel/llvm#2228]
Following is the change to mark.

1. sycl/test/hier_par/hier_par_wgscope_O0.cpp 
// RUN: %GPU_RUN_PLACEHOLDER %t.out
// RUN: %ACC_RUN_PLACEHOLDER %t.out

 -// XFAIL: accelerator || (system-windows && cpu)
 +// UNSUPPORTED: accelerator || (system-windows && cpu)

// This test checks correctness of hierarchical kernel execution when there is
// code and data in the work group scope, and when the test is compiled with

2. sycl/test/sub_group/generic-shuffle.cpp 
 -// UNSUPPORTED: cuda
 +// UNSUPPORTED: cuda || cpu
// CUDA compilation and runtime do not yet support sub-groups.
//
// RUN: %clangxx -fsycl -fsycl-targets=%sycl_triple %s -o %t.out

**Comment by bader** [comment]
-// XFAIL: accelerator || (system-windows && cpu)
+// UNSUPPORTED: accelerator || (system-windows && cpu)

Why? It's supposed to be supported. AFAIK, @againull is working on resolving these failures.

The same is applied to sub-groups on CPU.

**Comment by vladimirlaz** [comment]
Changing OpenCL RTs exposed several flacky issues. We disabled these test to let us move forward with update and fix tets afterwords.

**Comment by bader** [comment]
Do you plan to fix "flacky issues"? Just disabling the test doesn't seem like the right approach to me.

**Comment by vladimirlaz** [comment]
this is the reason to have this issue openned:)

**Comment by bader** [comment]
It seems to me that PR title and description say the opposite: "Mark hier_par_wgscope_O0.cpp and generic-shuffle.cpp as Unsupported".
