### ISSUE TITLE
sycl/test/sub_group/generic-shuffle.cpp failed on OpenCL CPU (2020.10.7.0.15) with avx2 instruction set

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#2245]
the same test pass on on OpenCL GPU RT and OpenCL CPU RT with other instruction sets

build $ CL_CONFIG_CPU_TARGET_ARCH=corei7-avx SYCL_DEVICE_TYPE=CPU SYCL_BE=PI_OPENCL  build/tools/sycl/test/sub_group/Output/generic-shuffle.cpp.tmp.out
Test passed.
build $ CL_CONFIG_CPU_TARGET_ARCH=corei7 SYCL_DEVICE_TYPE=CPU SYCL_BE=PI_OPENCL build/tools/sycl/test/sub_group/Output/generic-shuffle.cpp.tmp.out
Test passed.
build $ CL_CONFIG_CPU_TARGET_ARCH=corei7-avx SYCL_DEVICE_TYPE=CPU SYCL_BE=PI_OPENCL build/tools/sycl/test/sub_group/Output/generic-shuffle.cpp.tmp.out
Test passed.
**build $ CL_CONFIG_CPU_TARGET_ARCH=core-avx2 SYCL_DEVICE_TYPE=CPU SYCL_BE=PI_OPENCL build/tools/sycl/test/sub_group/Output/generic-shuffle.cpp.tmp.out
Unexpected result for shuffle: (6.72623e-43,0) expected value: (122,123)**
build $ CL_CONFIG_CPU_TARGET_ARCH=skx SYCL_DEVICE_TYPE=CPU SYCL_BE=PI_OPENCL build/tools/sycl/test/sub_group/Output/generic-shuffle.cpp.tmp.out
Test passed.

**Comment by Pennycook** [comment]
Is this specific to generic shuffles, or are shuffles impacted as well?

**Comment by vladimirlaz** [comment]
this is only about generic shuffles. Others are OK.

**Comment by vladimirlaz** [comment]
After additional investigation it looks like test issue. Fix is ongoing.

**Comment by vladimirlaz** [comment]
https://github.com/intel/llvm/pull/2253
