### ISSUE TITLE
Error using CUDA BE with large 2D data on GPU 

### ISSUE THREAD

**Issue by Suraj42** [intel/llvm#2290]
Hello 

I am testing a simple code with a vector of arrays using CUDA backend. For the size of n given in the attached code, I get the following error: 
Platform: NVIDIA CUDA BACKEND
  Device: Quadro P2000
Platform: SYCL host platform
  Device: SYCL host device
using device : Quadro P2000

PI CUDA ERROR:
	Value:           1
	Name:            CUDA_ERROR_INVALID_VALUE
	Description:     invalid argument
	Function:        cuda_piEnqueueKernelLaunch
	Source Location: /home/user/Downloads/llvm/sycl/plugins/cuda/pi_cuda.cpp:2343

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)
Aborted (core dumped)

For the size of n less than 100000 there is no error. Please kindly advise on a solution as this test is paramount for the rest of my work. Thank you in Advance.
System info: Ubuntu 20.04.1 LTS, CUDA 10.2, Driver version 440.100, Device: Nvidia Quadro P2000

CODE:
```c++
#include <iostream>
#include <vector>
#include <array>
#include <CL/sycl.hpp>

int main(int argc, char** argv)
{
  size_t n = 100000;
  const int arrSize = 3;
  
  std::vector<std::array<float,arrSize>> vec(n);

  auto platforms = sycl::platform::get_platforms();
  
  for (auto &platform : platforms) {
    
    std::cout << "Platform: "
	      << platform.get_info<sycl::info::platform::name>()
	      << std::endl;
    
    
    auto devices = platform.get_devices();
    for (auto &device : devices ) {
      std::cout << "  Device: "
		<< device.get_info<sycl::info::device::name>()
		<< std::endl;
    }
  }
  
  sycl::gpu_selector device_selector;
  sycl::queue d_queue(device_selector);
  
  std::cout << "using device : " << d_queue.get_device().get_info<sycl::info::device::name>() << std::endl;

  sycl::range<2> vec_range(size_t(n),arrSize);
  
  sycl::buffer<float, 2>  b_vec((float*)(vec.data()), vec_range);

  d_queue.submit([&](sycl::handler &cgh) {
      auto ab_vec = b_vec.get_access<sycl::access::mode::write>(cgh);
		   
      cgh.parallel_for<class ex1>(vec_range,[=](sycl::id<2> idx) {
	  size_t i = idx.get(0);
	  size_t j = idx.get(1);
							       
	  ab_vec[i][j] = 1.;
	});
		   
    });

  //  b_vec.get_access<sycl::access::mode::read>();
}
```

**Comment by bader** [comment]
I think it's CUDA limitation on the # of thread blocks.
There are no issue with `n` < 65536. I suggest re-writing the code - e.g. to run `parallel_for` with {50000, 6} nd_range instead of {100000, 3}.
