### ISSUE TITLE
[SYCL] Copying sub-buffers is not done correctly

### ISSUE THREAD

**Issue by krasznaa** [intel/llvm#2328]
Dear All,

@czangela brought it to my attention that "sub-buffers" don't really work as we would expect them to from the documentation.

In our code we want to be able to run on a "larger" buffer on the device, but then only copy back a small part of that buffer back to the host. The setup here is that the device code is trying to create some sort of objects (let's not get into the details...). We want to allocate enough memory on the device for the "worst case scenario", for the case when the code creates the maximal number of possible objects. But once the device code ran, and it figured out how many objects it actually created, we would only like to copy that exact number back to the host. Because we can definitely win by being clever here. (We need to allocate much more memory on the device on average than how much data we need to get back.)

From the documentation we thought that using "sub-buffers" would be the way to achieve this. Take the following example:

```c++
// SYCL include(s).
#include <CL/sycl.hpp>

// System include(s).
#include <iostream>
#include <vector>

int main() {

   // Set up the data on the host.
   static constexpr std::size_t DATA_SIZE = 10000;
   std::vector< int > hostData( DATA_SIZE, 1 );

   // Set up a buffer grabbing just the first 2000 elements of the host
   // vector.
   cl::sycl::range< 1 > buffer1Range( 5000 );
   cl::sycl::buffer< int > buffer1( hostData.data(), buffer1Range );

   // Set up a helper buffer that's only holding some "counts".
   cl::sycl::range< 1 > counterRange( 1 );
   cl::sycl::buffer< int > counterBuffer( counterRange );

   // Set up the SYCL queue.
   cl::sycl::queue queue;
   cl::sycl::range< 1 > workItems( buffer1.get_count() );

   // Run a weird kernel.
   queue.submit( [&]( cl::sycl::handler& handler ) {
         auto acc =
            buffer1.get_access< cl::sycl::access::mode::read_write >( handler );
         auto counterAcc =
            counterBuffer.get_access< cl::sycl::access::mode::read_write >( handler );
         handler.parallel_for< class SYCLMultiply >( workItems,
            [=]( cl::sycl::id< 1 > id ) {
               acc[ id ] *= 2;
               if( id == 0 ) {
                  counterAcc[ 0 ] = 50;
               }
            } );
      } );

   // Get the specified number of elements back to the host.
   auto counterAcc = counterBuffer.get_access< cl::sycl::access::mode::read >();
   std::cout << "Requesting to copy back " << counterAcc[ 0 ] << " elements" << std::endl;

   // Try to initiate the copy of just 50 elements back to the host.
   cl::sycl::id< 1 > buffer2Id( 0 );
   cl::sycl::range< 1 > buffer2Range( counterAcc[ 0 ] );
   cl::sycl::buffer< int > buffer2( buffer1, buffer2Id, buffer2Range );
   auto bufferAcc = buffer2.get_access< cl::sycl::access::mode::read >();
   // Do an out-of-range access. (Which also triggers the copy to the host...)
   bufferAcc[ 100 ];

   // Print the contents of the host buffer.
   for( std::size_t i = 0; i < DATA_SIZE; ++i ) {
      std::cout << i << ": " << hostData[ i ] << std::endl;
   }

   // Return gracefully.
   return 0;
}
```

`buffer1` is set up to not own its memory area just to make it easier to see what's happening... What I would hope to get out of this is that the first 50 elements of the buffer would be updated to `2`, and the rest of the elements would remain at the starting `1` value.

But what we see is that every element of `buffer1` gets copied back to the host. Whatever we do, we always trigger the copy of 5000 elements. :frowning: And when I try to access an element on `buffer2` that would in principle be out of range for that object, that operation is done without any complaint. :confused:

As I started, this is just a dumb example. But in our real code we would really expect to get an improvement by being able to specify exactly how much memory want to copy back to the host.

So... Was this behaviour intentional, was it an oversight, or was it just a "temporary implementation simplification" until a better implementation would be made?

Ping @ivorobts, @vpascuzz, @cleggett, @fwyzard.

Cheers,
           Attila

P.S. I checked the behaviour with both the Level-Zero and CUDA backends. It consistently behaves badly. :frowning:

**Comment by cperkinsintel** [comment]
Correct, presently the sub-buffers provide no real benefit, vis-a-vis any data copy optimizations. However, the work is underway. So, it is a "temporary implementation simplification" .

**Comment by krasznaa** [comment]
Thanks for the confirmation! We'll just have to live with it for now then...

But this is definitely a feature that could help others as well. To be able to move parts of buffers between the host and the accelerator.

**Comment by krasznaa** [comment]
Let me close this one. We didn't end up using sub-buffers in any of our "actual" code yet.
