### ISSUE TITLE
LLVM_SPIRV::unsup_invoke_instr.ll failing on Windows after pulldown

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#2433]
@fadeeval, could you please check the tests which start to fail after pulldown from KhronosGroup/SPIRV-LLVM-Translator (guilty commit: KhronosGroup/SPIRV-LLVM-Translator@e0f29294)
Compilation crashed instead of proper diagnostics.

It looks like there is no Windows validation in SPIRV-LLVM-Translator so the roblem may be present there and the fix need to be upstreamed.

I XFAIL the test on windows until fix is ready.

**Comment by fadeeval** [comment]
PR: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/741

**Comment by fadeeval** [comment]
The PR KhronosGroup/SPIRV-LLVM-Translator#741 was merged so the issue can be closed now

**Comment by AlexeySachkov** [comment]
I suggest we do not close this yet as we need to propagate KhronosGroup/SPIRV-LLVM-Translator#741 into intel/llvm and remove `XFAIL` from the test

**Comment by vladimirlaz** [comment]
fixed goes to intel/llvm in https://github.com/intel/llvm/commit/3addf30c9448d64bcfeca436b6cbe1f5186edfe2
