### ISSUE TITLE
When can we expect reductions to work with the CUDA backend?

### ISSUE THREAD

**Issue by mfbalin** [intel/llvm#2498]
When I use sycl::ONEAPI::reduction with the CUDA backend, I get the following error:
```ptxas fatal   : Unresolved extern function '_Z17__spirv_GroupIAddjjm'```

**Comment by bader** [comment]
Tagging @Pennycook.

**Comment by Pennycook** [comment]
Ok, I'm hopeful that we can get this working within a few weeks.  I have a prototype passing the tests for 32-bit types, and just need to spend a little longer working out the details for 64-bit types.

**Comment by Pennycook** [comment]
I'm apparently really bad at predicting how long things will take.

https://github.com/intel/llvm/pull/2647 enables reductions with the CUDA backend.  Please take a look and let me know if you encounter any issues with it.
