### ISSUE TITLE
[SYCL] -save-temps is broken

### ISSUE THREAD

**Issue by airlied** [intel/llvm#25]
/opt/sycl/bin/clang++ -save-temps -std=c++11 -fsycl simple-sycl-app.cpp -o simple-sycl-app -lsycl -lOpenCL 

clang++: /home/airlied/devel/intel/llvm/clang/lib/Driver/ToolChains/Clang.cpp:5280: virtual void clang::driver::tools::Clang::ConstructJob(clang::driver::Compilation&, const clang::driver::JobAction&, const clang::driver::InputInfo&, const InputInfoList&, const llvm::opt::ArgList&, const char*) const: Assertion `Tgts && Tgts->getNumValues() && "SYCL offloading has to have targets specified."' failed.

**Comment by mdtoguchi** [comment]
Assertion due to not setting default triple with -fsycl.  Addressed in #400
