### ISSUE TITLE
[SYCL] [CUDA] libclang_rt.profile-x86_64.a not found when compiling package in Debug

### ISSUE THREAD

**Issue by cgleggett** [intel/llvm#2508]
When building a package using clang++ from dpcpp/llvm with -DCMAKE_BUILD_TYPE=Debug, I'm seeing this error:
```
/usr/bin/ld: cannot find /opt/dpcpp/2020.09.21-cuda-9db44f8551a/lib/clang/12.0.0/lib/linux/libclang_rt.profile-x86_64.a
```

dpcpp was built with
```
buildbot/configure.py -s ../llvm -o . -t release --no-werror --shared-libs --cmake-opt=-DCMAKE_INSTALL_PREFIX=/opt/dpcpp/2020.09.21-cuda-9db44f8551a --cuda
```
I don't see `libclang_rt.profile-x86_64.a` anywhere in the llvm build directory, so it's not that it was built but not installed. In fact the whole `/opt/dpcpp/2020.09.21-cuda-9db44f8551a/lib/clang/12.0.0/lib` directory does not exist.

Is there another parameter that needs to be given to buildbot to build this?

The version of dpcpp is from git commit hash 9db44f8551a, but this seems the same in versions going back to March. I do see this library in the beta-0X packages however.

**Comment by vpascuzz** [comment]
Hi, @cgleggett.
To hopefully answer part of your question, I usually `cp -r lib include bin ${LLVM_INSTALLDIR}/` as, indeed, the "installation" doesn't put all the required files. This, of course, also copies some build files -- e.g. `.o`, `.spv` -- as well (you can be smarter about the `cp`).

(P.S. Try my installation in /opt/dpcpp/2020.10.02-cuda-8149957a819a with `module load dpcpp/2020.10.02-a7ad8b8-cuda` : )

**Comment by cgleggett** [comment]
Actually, it wasn't being built at all, as some cmake option was missing. For reference, here's the magic sauce:
```
> cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/dpcpp/2020.10.02-cuda-8149957a819a \
-DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;compiler-rt;llvm-spirv;sycl;libclc \
-DLLVM_EXTERNAL_PROJECTS=sycl;llvm-spirv;opencl-aot;xpti;libdevice \
-DLLVM_EXTERNAL_SYCL_SOURCE_DIR=/opt/install/intel/llvm/sycl \
-DLLVM_EXTERNAL_LLVM_SPIRV_SOURCE_DIR=/opt/install/intel/llvm/llvm-spirv \
-DLLVM_EXTERNAL_LIBDEVICE_SOURCE_DIR=/opt/install/intel/llvm/libdevice \
-DLLVM_TARGETS_TO_BUILD=X86;NVPTX -DSYCL_BUILD_PI_CUDA=ON \
-DLIBCLC_TARGETS_TO_BUILD=nvptx64--;nvptx64--nvidiacl \
-DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_PIC=ON -DLLVM_ENABLE_RTTI=ON \
-DOpenCL_INCLUDE_DIRS= -DOpenCL_LIBRARIES= -DOpenCL_INSTALL_KHRONOS_ICD_LOADER=TRUE \
-DGCC_INSTALL_PREFIX=/opt/gcc/8.4.0 \
-DCUDA_TOOLKIT_ROOT_DIR=/opt/cuda/10.1.243 -G Ninja \
/opt/install/intel/llvm/llvm

> ninja ocl-headers && ninja ocl-icd && ninja -j72 && ninja libsycldevice
> ninja install
```

**Comment by sebastian-freitag-pylot** [comment]
compiler-rt in LLVM_ENABLE_PROJECTS is the one that will provide libclang_rt.profile-x86_64.a
See here:
https://compiler-rt.llvm.org/
