### ISSUE TITLE
[SYCL] Implement eviction in program and kernel caches

### ISSUE THREAD

**Issue by kbobrovs** [intel/llvm#2517]
Programs and kernels created by SYCL runtime are recorded in internal cache-like data structures. But cache entries are never evicted, which makes it possible to exhaust resources in big long-running apps. So SYCL runtime needs to implement some eviction scheme - like LRU.

**Comment by romanovvlad** [comment]
@kbobrovs AFAIK program and kernel caches are attached to the sycl::context object which program is compiled for. So, cached values are freed when the context object is released.
@s-kanaev  Please, correct me if I'm wrong.

**Comment by s-kanaev** [comment]
> AFAIK program and kernel caches are attached to the sycl::context object which program is compiled for. So, cached values are freed when the context object is released.

That's correct. We have this code in [`KernelProgramCache::~KernelProgramCache`](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/kernel_program_cache.cpp#L16)

**Comment by kbobrovs** [comment]
@romanovvlad, manual management can do the job in some cases. Users can delete/re-create context. But there will always be scenarios where this is not possible or practical, I believe.  I don't think this is high-priority until we hit this.

**Comment by romanovvlad** [comment]
> I think this one may be combined with general policy and the policy should be enforced/lifted with API or environment variable.

> @romanovvlad, manual management can do the job in some cases. Users can delete/re-create context. But there will always be scenarios where this is not possible or practical, I believe. I don't think this is high-priority until we hit this.

Just to clarify, I was thinking about adding a new method in the sycl::context class(may not only) which removes cached program for a given kernel name(or some other identification).

**Comment by kbobrovs** [comment]
I see. That would be a SYCL extension to workaround our implementation, as SYCL spec does not mandate caches.

**Comment by uditagarwal97** [comment]
Fixed in https://github.com/intel/llvm/pull/16062
