### ISSUE TITLE
[SYCL] Abstraction layer for device-side SIMT intrinsics like getting global id

### ISSUE THREAD

**Issue by kbobrovs** [intel/llvm#253]
SYCL device runtime code uses various "intrinsic" functionalities like getting global and local id of a work item or group, which is usually expressed via efficient hardware-mapped code sequences in the native device code. SYCL device runtime should clearly define an interface layer of such intrinsic functionality and mechanisms to implement it for various devices, including those without SPIRV support. See some discussion here: 
https://github.com/intel/llvm/pull/221#discussion_r295587062

Currently device-side APIs this functionality are defined in headers under CL/__spirv directory.

**Comment by Naghasan** [comment]
Among the advantages I see by trying to be interface compatible with the SPIR-V friendly format, there is those 3:
  - This you will allow you to link with externally generated module;
  - This allow to push the specialization of the module for a target to the backend, hence the compilation from C++ to LLVM IR could be done only once (unless macro are defined);
  - It also simplify testing: the SYCL library has 1 target and backends can be tested independently 

SPIR-V may not enable the expression of some important details of an architecture, but this can be circumvented by making a SPIR-V extension. Op code can be reserved for that purpose and they don't have to go through Khronos (i.e. they could be part of the compiler documentation).
