### ISSUE TITLE
[SYCL] Possibly redundant getSpirvSource() call in program_manager.cpp

### ISSUE THREAD

**Issue by agozillon** [intel/llvm#26]
Fairly irrelevant issue and I could be wrong  and misunderstanding the code (I apologize if I am) but I think the new addition of the function `createOpenCLProgram` inside **sycl/source/detail/program_manager/program_manager.cpp** makes the call to `getSpirvSource()` on line _125_ inside the function `getBuiltOpenCLProgram` redundant.

As `createOpenCLProgram` calls it on line _115_ (which is invoked by `getBuiltOpenCLProgram`) and the return from the invocation on line _125_ doesn't appear to be used at the moment. The check for existing Spirv source inside  `getSpirvSource()`probably stops the source getting loaded in twice but thought I'd bring it up in case.

**Comment by bader** [comment]
@agozillon, thanks for reporting this!
I talked to @vladimirlaz and it seems to be an artifact of merge conflict resolution.

**Comment by vladimirlaz** [comment]
The fix has been merged.
