### ISSUE TITLE
Segmentation Fault  - Simple SYCL Example  

### ISSUE THREAD

**Issue by IgorBaratta** [intel/llvm#2663]
I'm building the DPC++ toolchain on a an HPC machine following these steps:

```bash
module purge
module load gcc/9
module load cmake/latest
module load ninja

export DPCPP_HOME=~/sycl_workspace
mkdir $DPCPP_HOME
cd $DPCPP_HOME

git clone https://github.com/intel/llvm -b sycl

python3 $DPCPP_HOME/llvm/buildbot/configure.py
python3 $DPCPP_HOME/llvm/buildbot/compile.py
```
with apparent success.

However when I try to compile a simple [file](https://intel.github.io/llvm-docs/GetStartedGuide.html) :

```bash
$ clang++ -fsycl simple-sycl-app.cpp -o simple-sycl-app

../include/sycl/CL/sycl/detail/helpers.hpp:50:22: error: no member named 'is_trivially_copyable' in namespace 'std' 
static_assert(std::is_trivially_copyable<From>::value,
                ~~~~~^
../include/sycl/CL/sycl/detail/helpers.hpp:50:44: error: 'From' does not refer to a value
  static_assert(std::is_trivially_copyable<From>::value,

.....

```
I guess it's using an old gcc-toolchain.  If I specify gcc9  toolchain explicitely it compiles fine:
```bash
$ clang++ --gcc-toolchain=/path/to/gcc/9  -fsycl simple-sycl-app.cpp -o simple-sycl-app
```

And, as an alternative, I added the following line to [buildbot/configure.py](https://github.com/intel/llvm/blob/ac7255df1087068ac5f4f9031d18d9c7936ad5b7/buildbot/configure.py#L82) file:
```
"-DGCC_INSTALL_PREFIX=/path/to/gcc/9/"
```
to avoid setting `--gcc-toolchain` for each compilation.

Now, If I ran the compiled using a `cpu_selector` I get the following error:
```
$ clang++ -fsycl simple-sycl-app.cpp -o simple-sycl-app
$ gdb ./simple-sycl-app
.....
Program received signal SIGSEGV, Segmentation fault.
0x00002aaaf5d29f50 in llvm::ReplaceableMetadataImpl::getIfExists(llvm::Metadata&) ()
   from /opt/ocl/opencl_compilers_and_libraries_18.1.0.014/linux/compiler/lib/intel64_lin/libclang_compiler.so
```
which doesn't happen when I choose host or gpu selectors.

**Comment by dm-vodopyanov** [comment]
Hi @IgorBaratta, sorry for delay. OpenCL CPU RT version 18.1.0.014 is too old for co-existing with SYCL. Could you please try to use [oclcpuexp-2020.11.8.0.27_rel.tar.gz](https://github.com/intel/llvm/releases/download/2020-09/oclcpuexp-2020.11.8.0.27_rel.tar.gz) from https://github.com/intel/llvm/releases/tag/2020-09 ?

**Comment by IgorBaratta** [comment]
Hi @dm-vodopyanov , thank you for your reply.

I though OpenCL dependencies were downloaded via cmake without the  `--system-ocl` flag.

> Could you please try [oclcpuexp-2020.11.10.0.05_rel.tar.gz](https://github.com/intel/llvm/releases/download/2020-WW41/oclcpuexp-2020.11.10.0.05_rel.tar.gz) with [oneTBB](https://github.com/oneapi-src/oneTBB/releases/download/v2021.1-beta08/oneapi-tbb-2021.1-beta08-lin.tgz) from [the dependency configuration file](https://github.com/intel/llvm/blob/sycl/buildbot/dependency.conf)? The setup instruction is [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime).

Unfortunately, I don' have root access in this machine to follow the instructions and install the low level runtime.
Is there any alternative? Any environment variable that I can set pointing to the OpenCL CPU RT local dir?

I looked in the documentation but found no information.

**Comment by dm-vodopyanov** [comment]
Enabled ```--system-ocl``` option prevents to download only OpenCL headers and library and forces to use the system ones. OpenCL runtimes should be downloaded separately.

By default, it is impossible to install OpenCL runtime without root access, but the installation process can be modified and may require root permissions only once for a machine. Subsequent installations can be done without root access. This is an addition to the **Install low level runtime - Linux** instruction:
1. No changes, archive can be unpacked to any directory.
2. (requires root access) The machine administrator can create ```/etc/OpenCL/vendors/intel_expcpu.icd``` file once and put only filename to it, without absolute path: ```libintelocl.so```. So:
**$ cat /etc/OpenCL/vendors/intel_cpu.icd
libintelocl.so**
It will bring flexibility, and after that you can source any OpenCL CPU RT without root access. Together with this, the same files can be created once for OpenCL GPU RT and OpenCL FPGA Emulation RT:
**$ cat /etc/OpenCL/vendors/intel_gpu.icd
libigdrcl.so
$ cat /etc/OpenCL/vendors/intel_fpga_emu.icd
libintelocl_emu.so**
3. No changes. The only difference, it is better to download newer oneTBB, not the one I provided above. [The link](https://github.com/oneapi-src/oneTBB/releases/download/v2021.1-beta10/oneapi-tbb-2021.1-beta10-lin.tgz) to the latest oneTBB release.
4. The third way (besides copying oneTBB libs or creating symbolic links to them) is to set ```LD_LIBRARY_PATH``` to ```<...>/oneapi-tbb-2021.1-beta10/lib/intel64/gcc4.8/```
5. Doesn't require root access now. Set ```LD_LIBRARY_PATH``` to the unpacked OpenCL CPU RT folder ```<...>/x64```.

To check that OpenCL runtime was integrated correctly, ```<build>/bin/sycl-ls``` tool can be executed. E.g., output for my machine is 
**$ ./sycl-ls
CPU : Intel(R) OpenCL 2.1 [2020.11.10.0.05_160000]
HOST: SYCL host platform 1.2 [1.2]**
There we can see that low-level runtime for CPU is Intel(R) OpenCL 2.1, and it's version is 2020.11.10.0.05_160000.

To find more information about available SYCL default/gpu/cpu/... selectors on the current machine, execute ```./sycl-ls --verbose```.

**Comment by IgorBaratta** [comment]
Thank you for the information.

I will contact the machine administrator to update OpenCL and help me with step 2.

Anyway, loading an old version of oneAPI with the Environment Modules seems also to work:
```bash
./sycl-ls
CPU : Intel(R) CPU Runtime for OpenCL(TM) Applications 2.1 [18.1.0.0920]
HOST: SYCL host platform 1.2 [1.2]

$ module load intel/oneapi/2021.1.4

$ ./sycl-ls 
ACC : Intel(R) FPGA Emulation Platform for OpenCL(TM) 1.2 [2020.9.1.0]
CPU : Intel(R) OpenCL 2.1 [2020.9.1.0.18]
CPU : Intel(R) CPU Runtime for OpenCL(TM) Applications 2.1 [2020.9.1.0.18]
HOST: SYCL host platform 1.2 [1.2]
```
