### ISSUE TITLE
[SYCL] [SPEC] USM Feedback

### ISSUE THREAD

**Issue by kevin-harms** [intel/llvm#268]
Is there a reason why this is done through new allocation interfaces rather than with the existing buffer and accessor classes? It seems like all the functionality could be described as new types of buffers corresponding to the tables shown in the proposal. What is the basis for providing a new allocation method in SYCL?

If we must have a new interface, I prefer code that is easy for the reader rather than for the writer and as such, would rather see a single sycl_malloc() call that is parameterized.

```
sycl_malloc_device(size, device);
sycl_malloc(size, device);
```
It is not obvious how these two functions are different without looking into the spec in detail. An interface like this:

`sycl_malloc(size_t size, size_t alignment, const sycl::device& device, const sycl::memory::allocation_type& type);`

```
sycl_malloc(size, 0, device, sycl::memory::allocation::device);
sycl_malloc(size, 0, device, sycl::memory::allocation::shared);
```

These two are immediately obvious in how the allocations are different and what they do.

**Comment by AlexeySachkov** [comment]
@jbrodman: FYI

**Comment by keryell** [comment]
I think the idea of @jbrodman was to use SYCL with some existing code operating on some memory area that can also be processed by some SYCL kernel without a lot of boiler plate code (porting CUDA or Thrust code, for example ;-) ).
What you are proposing is perhaps closer to the SVM envisioned in the SYCL 2.2 provisional and is also something we should address separately.
Now we have also buffer properties for this that we could use.
Using a completely different type of buffers is possible (and why not using http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1393r0.html) but you need to write generic code to handle them in your application if you want to pass around different kinds of buffers...
A lot of design choices...

**Comment by jbrodman** [comment]
Yes, Ronan is correct.

I am currently tweaking the design in favor of a c++ allocator style solution.

I wasn't in favor of the allocation-kind-as-a-parameter-of-sycl-malloc approaches:
sycl_malloc<kind>(...) - can lead to some awkward code 
sycl_malloc(..., kind) can lead to cases where your program could fail b/c you passed the wrong thing, but where the thing came from now could be somewhere else completely and hard to debug.

**Comment by jbrodman** [comment]
At the risk of being pedantic, I also want to point out the difference between Spec and implementation.

For the Spec, I'll go with the C++-style allocator (by popular request: https://github.com/intel/llvm/issues/119).

This implementation, however, can define whatever function flavors it likes on top of the Spec as helpers.

**Comment by jbrodman** [comment]
@kevin-harms We have since defined and implemented every flavor of allocation: C++-style allocator, named functions, parameterized functions, both of those but with <T>, etc.

Does that sufficiently address your concerns?

**Comment by AlexeySachkov** [comment]
@kevin-harms, can we close this issue in context of USM spec updates mentioned by @jbrodman, or there is still something you would like to discuss?
