### ISSUE TITLE
Add a useful warning to warn for any functionality which isn't supported without generic address space

### ISSUE THREAD

**Issue by srividya-sundaram** [intel/llvm#2728]
Input from @rolandschulz 

Raw pointers for SYCL_EXTERNAL are prohibited without generic address space. Generic address space doesn't exist in 1.2.1 and is optional in 2020. Our implementation isn't spec compliant to 1.2.1 because we use generic address space (among other).

It seems useless to warn about a detail (SYCL_EXTERNAL with pointers) if the base functionality (pointers using inference rules vs generic address space) isn't implemented spec compliant and the reason for the spec rule is based on the assumption of the implementation.

And this diagnostic has no practical value to users. We aren't warning about something which has any impact for our implementation based on generic address space. And it isn't useful for portability to other implementation. Because this is only a portability concern if the other implementation doesn't support generic address space.

But in that case a useful warning needs to warn for any functionality which isn't supported without generic address space (using the SYCL inference rules instead). This is among other SYCL_EXTERNAL with raw pointer, assignment of raw pointers which can't be inferred (e.g. in conditionals), function ptrs with raw pointers. That warning would allow a user to target implementation which don't support generic address space. And as part of that warning its useful to warn for SYCL_EXTERNAL. But just warning for SYCL_EXTERNAL without also warning for all other features which depend on generic address space is useless.

We might want to create a new issue to add such a useful warning and partially revert this commit and make it a part of such a new optional warning. I'm not sure whether users need that or would just use a different SYCL implementation without generic address space if they need to get diagnostic regarding features not available without generic address space.

**Comment by srividya-sundaram** [comment]
Hi @romanovvlad , this issue was created as a follow up for #2722 to add a new warning based on @rolandschulz's input.
This is not implemented yet, so I am not sure we can close this issue now.

**Comment by romanovvlad** [comment]
Hi @srividya-sundaram, sorry, not sure how it happened. Reopened.

**Comment by romanovvlad** [comment]
It seems it happened because I've merged the PR this issue is linked to. https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
