### ISSUE TITLE
November version of the CPU OpenCL driver does not work with TBB from beta10

### ISSUE THREAD

**Issue by fwyzard** [intel/llvm#2774]
The latest experimental CPU OpenCL ([oclcpuexp-2020.11.11.0.04_rel.tar.gz](https://github.com/intel/llvm/releases/download/2020-WW45/oclcpuexp-2020.11.11.0.04_rel.tar.gz) from the [November 6th release](https://github.com/intel/llvm/releases/tag/2020-WW45) of the oneAPI DPC++ Compiler dependencies is not compatible with the latest version [v2021.1-beta10](https://github.com/oneapi-src/oneTBB/releases/download/v2021.1-beta10/oneapi-tbb-2021.1-beta10-lin.tgz) of TBB.

After setting up the experimental CPU OpenCL runtime following the [GetStartedGuide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime), `clinfo -l` does not show the CPU runtime:
```
$ clinfo -l
Platform #0: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) Gen9 HD Graphics NEO
```

Trying to load `libintelocl.so` results in an error:
```
$ LD_PRELOAD=/opt/intel/oclcpuexp/x64/libintelocl.so /bin/true
/bin/true: symbol lookup error: libtask_executor.so.2020.11.11.0: undefined symbol: _ZN3tbb6detail2r114notify_waitersEm
```

In fact, none of the libraries from the TBB distribution provide that symbol:
```
 $ nm -A /opt/intel/oneapi/tbb/2021.1-beta10/lib/intel64/gcc4.8/*.so | grep notify_waiters
/opt/intel/oneapi/tbb/2021.1-beta10/lib/intel64/gcc4.8/libtbb_debug.so:000000000003f9a6 t _ZN3tbb6detail2d112wait_context14notify_waitersEv
/opt/intel/oneapi/tbb/2021.1-beta10/lib/intel64/gcc4.8/libtbb_debug.so:0000000000076edc r _ZN3tbb6detail2d112wait_context14notify_waitersEv$$LSDA
/opt/intel/oneapi/tbb/2021.1-beta10/lib/intel64/gcc4.8/libtbb_debug.so:000000000003fd49 T _ZN3tbb6detail2r114notify_waitersERNS0_2d112wait_contextE
```

It looks like the symbol is defined in the [master branch](https://github.com/oneapi-src/oneTBB/tree/master) of TBB.
Are there any corresponding binary releases ?

**Comment by AlexeySachkov** [comment]
Tagging @vladimirlaz to comment

**Comment by vladimirlaz** [comment]
https://github.com/oneapi-src/oneTBB/releases/tag/v2021.1.1 should work.

**Comment by fwyzard** [comment]
Thanks, I can confirm that they work with TBB v2021.1.1 .
