### ISSUE TITLE
clang++: error: llvm-spirv command failed with exit code 6

### ISSUE THREAD

**Issue by mgarciamartinez** [intel/llvm#2786]
Hello,

I was suggested by Intel staff to submit this issue. See below problem found on JLSE Gen9 (iris nodes) and how to reproduce it.

*** PROBLEM ***
I’m trying to compile Kokkos Kernels and if I turn on the compilation of the examples (-DKokkosKernels_ENABLE_EXAMPLES=ON) I get this error:

=====================================================================
[ 94%] Linking CXX executable KokkosKernels_wiki_spgemm

...

InvalidFunctionCall: Unexpected llvm intrinsic:

 llvm.ctpop.i32 [Src: /netbatch/donb2965411_00/runDir/88/20201005_160000/llvm/llvm-spirv/lib/SPIRV/SPIRVWriter.cpp:2399  ]

clang++: error: llvm-spirv command failed with exit code 6 (use -v to see invocation)

make[2]: *** [example/wiki/sparse/CMakeFiles/KokkosKernels_wiki_spgemm.dir/build.make:110: example/wiki/sparse/KokkosKernels_wiki_spgemm] Error 6

=====================================================================

While looking for some information, I found the only page that has the same error but for a build using SYCL code.
https://community.intel.com/t5/Intel-oneAPI-Data-Parallel-C/CL-INVALID-KERNEL-NAME-when-built-with-fsycl-targets-spir64-gen/td-p/1217671 

And the Intel expert who suggested this submission mentioned that this is similar to this other issue: https://github.com/intel/llvm/issues/2629

*** TO REPRODUCE IT ***
The Intel in charge of working on this issue, please contact me directly to receive instructions since some details are RSNDA.

Thank you.

**Comment by AlexeySachkov** [comment]
Hi @mgarciamartinez, thanks for the report

The problem within the SPIR-V translator was fixed more than a month ago: KhronosGroup/SPIRV-LLVM-Translator#775 and we incorporated this fix into intel/llvm ~2 weeks later: intel/llvm#2628.

So, I would expect this issue to disappear starting with [DPC++ daily 2020-10-23](https://github.com/intel/llvm/releases/tag/20201023) build

**Comment by mgarciamartinez** [comment]
Thank you Alexey for your reply. It's good to know that it's already been fixed from your side. I have created a reproducer on internal and I asked our Intel contacts if the fix will be part of the next SDK release. I will keep you posted as soon as I see this fixed on our side.

**Comment by AlexeySachkov** [comment]
Hi @mgarciamartinez, any updates from your side? Have you confirmed that the issue is fixed?
