### ISSUE TITLE
Implement AtomicFAddEXT for the CUDA BE

### ISSUE THREAD

**Issue by AGindinson** [intel/llvm#2853]
After https://github.com/intel/llvm/commit/4fdbfae9397aef25f3de0ecb7eb2bc85cac3b6fb, there are [preparations](https://github.com/intel/llvm/pull/2765) to switch atomic `fetch_add`/`fetch_sub` FP implementations to using the new SPIR-V operand. Providing a "native" implementation in the CUDA BE would enable us to use the leveraged function for NVPTX targets as well (`#if !defined(__NVPTX__)` macros would have to be removed to achieve this).

**Comment by ldrumm** [comment]
I think this is now implemented. It looks like @AGindinson did the meat of this work in 37a9a2a9dbb8d035b82748633fbaca8f0377e36c

Additionally, relevant libclc support went in in the following PRs:
https://github.com/intel/llvm/pull/4820 
https://github.com/intel/llvm/pull/4853
https://github.com/intel/llvm/pull/5025
https://github.com/intel/llvm/pull/5191

@AGindinson is there anything missing? Perhaps we can close this?

**Comment by AGindinson** [comment]
@AlexeySachkov, could you please help with evaluating this one?

**Comment by npmiller** [comment]
@AlexeySachkov @AGindinson any updates on this?

**Comment by AlexeySachkov** [comment]
> @AlexeySachkov @AGindinson any updates on this?

Not really. Both of us are not directly working on CUDA, so this item is a lower priority for us both. Feel free to pick it up. I'm also fine with closing it if we believe that everything is implemented already
