### ISSUE TITLE
About all the IDs in 2D space, what is the right relationship between get_*_linear_id and get_*_id

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/llvm#2888]
Copy from OpenCL standard:

```
For 2D work-groups, it is computed as (get_global_id(1) - get_global_offset(1)) * get_global_size(0) + (get_global_id(0) - get_global_offset(0)).
```

My test snippet says:
```
pos.get_global_linear_id()
               == pos.get_global_id(1) + pos.get_global_id(0) * pos.get_global_range()[0]
```

What's the convention here?

**Comment by alexbatashev** [comment]
@CaoZhongZ I think, the equation 4.3 found on page 119 of [SYCL Spec](https://www.khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf) answers this question: `id2 + (id1 · r2) + (id0 · r2 · r1)`
