### ISSUE TITLE
[SYCL] Investigate arbitrary attribute bounds for FPGA attributes 

### ISSUE THREAD

**Issue by elizabethandrews** [intel/llvm#2911]
Are these bounds required? Can we just test for unsigned int values?

See comment thread https://github.com/intel/llvm/pull/2877#discussion_r545209989 for details

**Comment by MrSidims** [comment]
@mohammadfawaz @jessicadavies-intel @GarveyJoe to address this question.

From what I remember now - we definitly need such limitation for `max_global_work_dim` kernel attribute (which has a natural limitation of '3').

**Comment by mohammadfawaz** [comment]
Many attributes have sane limitations such as `force_pow2_depth` (which can be either 0 or 1). Other memory attributes, such as `bankwidth`, need to have a lower bound of 1. However, an upper bound of `1024*`1024` seems quite arbitrary. I tried searching for where this number comes from, but I couldn't find anything. I am okay with removing the restriction, as long as:
1. We make sure that Clang doesn't care if we do so. I know the compiler will be okay.
2. We all other bounds that actually make sense.

**Comment by elizabethandrews** [comment]
Thanks for the inputs!

I took a look at the attributes and identified these with what looks like an arbitrary upper bound
```
0 - 1024*1024
SYCLIntelSchedulerTargetFmaxMhz 
SYCLIntelLoopFuse
IntelFPGAPrivateCopies
IntelFPGABankBits

1 - 1024*1024
IntelFPGABankWidth
IntelFPGANumBanks
IntelFPGAMaxReplicates
```
I can keep the lower bounds but remove the upper bounds for these. 

>>I know the backend will be okay.

@mohammadfawaz are you confirming the backend doesn't care? Or is this something I need to verify with someone?

**Comment by mohammadfawaz** [comment]
> Thanks for the inputs!
> 
> I took a look at the attributes and identified these with what looks like an arbitrary upper bound
> 
> ```
> 0 - 1024*1024
> SYCLIntelSchedulerTargetFmaxMhz 
> SYCLIntelLoopFuse
> IntelFPGAPrivateCopies
> IntelFPGABankBits
> 
> 1 - 1024*1024
> IntelFPGABankWidth
> IntelFPGANumBanks
> IntelFPGAMaxReplicates
> ```
> 
> I can keep the lower bounds but remove the upper bounds for these.
> 
> > > I know the backend will be okay.
> 
> @mohammadfawaz are you confirming the backend doesn't care? Or is this something I need to verify with someone?

Already verified that the backend doesn't care. Thanks!
