### ISSUE TITLE
[SYCL] Should loop fusion attributes be enabled for C code?

### ISSUE THREAD

**Issue by elizabethandrews** [intel/llvm#2912]
Investigate this and enable attribute and add tests for C code if required. See comment thread https://github.com/intel/llvm/pull/2877#discussion_r538776532 for details

**Comment by GarveyJoe** [comment]
Currently these attributes are only understood by the FPGA backend and since the only way to target that backend is through SYCL there's no value to supporting them in C.  This answer could change in the future if other backends decide to support these attributes as well.

**Comment by AaronBallman** [comment]
Good to know, thank you! Then I think it's safe to close this issue and we can revisit it in the future.
