### ISSUE TITLE
Discrepancies with provisional SYCL2020 specs?

### ISSUE THREAD

**Issue by al42and** [intel/llvm#2971]
Hello!

Given that the `-sycl-std=2020` switch is allowed and `SYCL_LANGUAGE_VERSION` is set to 202001, one would expect that [the provisional specs](https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf) are supported.

I wasn't able to find details about any limitations related to the support for the SYCL 2020 standard in the current version of the compiler. Please, point me to such a document if it exists.

However, the following program, seemingly compliant with the specs, fails to compile with the latest `sycl` branch (f58c568425b3a05630252daf609be5f91a021bdb). 

```cpp
#include <iostream>

// Section 4.3 Header files and namespaces
#include <SYCL/sycl.hpp>

auto myKernel(cl::sycl::handler& cgh)
{
    sycl::stream debug(10240, 128, cgh);
   
    return [=](cl::sycl::nd_item<1> itemIdx) {
        if (itemIdx.get_global_linear_id() == 0) {
            // Section 4.10.1.8 sub_group class
            sycl::sub_group sg = itemIdx.get_sub_group();
            float f = 0;
            // Section 4.19.5.4 group_reduce
            f = sycl::group_reduce(sg, f, sycl::plus<float>{});
            debug << "    Sub_group range: " << sg.get_local_range()[0] << cl::sycl::endl;
        }
    };
}

constexpr int numBlocks = 8;
constexpr int blockSize = 16;

int main()
{
    cl::sycl::device dev(cl::sycl::gpu_selector{});
    cl::sycl::queue q{dev};

    std::cout << "Running 1D kernel" << std::endl;
    const cl::sycl::nd_range<1> range1D{ { numBlocks * blockSize }, { blockSize } };
    q.submit([&](cl::sycl::handler& cgh) {
            auto kernel = myKernel(cgh);
            // Section 4.14.2 Defining kernels as lambda functions
            cgh.parallel_for(range1D, kernel);
            }).wait_and_throw();
    std::cout << "    Done" << std::endl;
    return 0;
}
```

Compilation options: `clang++ -fsycl -sycl-std=2020 ./sycl_2020.cpp -o sycl_2020`.

References to specific parts of SYCL2020 provisional specs that are apparently missing:

- Section 4.3: The include should be `SYCL/sycl.hpp`, but only `CL/sycl.hpp` is available.
- Section 4.14.2: Providing a name for lambda-kernel must be optional, but requires `-fsycl-unnamed-lambda` to work.
- Section 4.10.1.8: There should be `sycl::sub_group` class, but only `sycl::ONEAPI::sub_group` is available.
- Section 4.19.5.4: There should be `sycl::group_reduce` function, but only `sycl::ONEAPI::reduce` is available.
- Section 4.19.3: There should be `sycl::plus` functor, but only `sycl::ONEAPI::plus` is available.

**Comment by pvchupin** [comment]
Thanks for issue and list of items noticed as missing. Work is in progress for SYCL2020. We should update our documentation to set clear expectations. I'll update docs and we'll keep this issue open until items mentioned here are done.

**Comment by al42and** [comment]
@pvchupin Thanks for the heads up.

Not sure if this issue is worth keeping open after the docs are updated. It's not a comprehensive list of all things missing. E.g., there's also `sycl::group_any_of`, `sycl::memory_order`, `sycl::memory_scope`, `sycl::atomic_ref` that are part of SYCL2020, but are currently only available in `sycl::ONEAPI` namespace. Probably others -- these are the ones I personally encountered.

A dedicated meta-issue for proper tracking of missing features might be a better idea? And it would also work as the live documentation about the current state of the SYCL2020 support.

**Comment by keryell** [comment]
This issue will need some update anyway once the final specification is published but it is probably useful to keep it open to be sure we do not miss at least these points if they still exists in respect to the final spec.

**Comment by pvchupin** [comment]
Right, it's clear that list mentioned here is not complete. We track many other items internally. I think it is a good idea indeed to produce a more detailed list on what's not supported yet for SYCL2020. I think as soon as final spec is published we can build one.

**Comment by al42and** [comment]
Updated references to the final SYCL 2020 specs:

- Section 4.3: The include should be `sycl/sycl.hpp`, but only `CL/sycl.hpp` is available.
- Section 4.9.4.2: Providing a name for lambda-kernel must be optional, but requires `-fsycl-unnamed-lambda` to work.
- Section 4.9.1.8: There should be `sycl::sub_group` class, but only `sycl::ONEAPI::sub_group` is available.
- Section 4.17.4.5: There should be `sycl::reduce_over_group` function, but only `sycl::ONEAPI::reduce` is available.
- Section 4.17.2: There should be `sycl::plus` functor, but only `sycl::ONEAPI::plus` is available.

**Comment by al42and** [comment]
Most of the issues listed here have been resolved, so I see no point in keeping this issue open anymore.
