### ISSUE TITLE
error: no member named 'cl_size_t' in namespace 'sycl'

### ISSUE THREAD

**Issue by RudenkoRNK** [intel/llvm#2982]
According to the [SYCL spec](https://www.khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf) (pg. 38) there is a `cl_size_t` type defined in cl::sycl namespace.

Compiler throws an error with, for example, this code:
```
#include <CL/sycl.hpp>

int main() { cl::sycl::cl_size_t x; }
```

`error: no type named 'cl_size_t' in namespace 'sycl';`

**Comment by AlexeySachkov** [comment]
I believe that this is most likely a mistake, because `cl_*` types were invented for interoperability with OpenCL, which is device-dependent and don't have a host equivalent, so it would be hard to define it in SYCL.

Tagging @Pennycook, @rolandschulz, @jbrodman, @mkinsner here.

**Comment by keryell** [comment]
Actually these types have to exist on the host for the reason you want interoperability.
For example you can create a `buffer` of `cl_size_t` and then use it from an OpenCL C kernel using `size_t`.

**Comment by AlexeySachkov** [comment]
> Actually these types have to exist on the host for the reason you want interoperability.

This is probably true, but I really wonder how to implement that, because you can easily have several devices available that potentially have different size of `size_t`, so, this `cl_size_t` must be somehow coupled with a device?

**Comment by keryell** [comment]
Ah I see. You are talking specifically about `cl_size_t` here, not on the general case for OpenCL compatibility types, like `cl_int` and so on.
Yes, the problem with `cl_size_t`, which actually does not exist in OpenCL, is that it depends on the pointer size of OpenCL devices which is not specified...
It has been removed from the latest SYCL 2020 specification already.

**Comment by keryell** [comment]
Internal to Khronos: https://gitlab.khronos.org/sycl/Specification/-/issues/491

**Comment by keryell** [comment]
While answering this I found another bug in https://github.com/triSYCL/triSYCL/issues/292 about these OpenCL interoperability types... :-(

**Comment by AlexeySachkov** [comment]
> Ah I see. You are talking specifically about cl_size_t here, not on the general case for OpenCL compatibility types, like cl_int and so on.

Re-reading my own comment: yep, it is a bit confusing, I've update it to clarify that I was specifically talking about `cl_size_t`

**Comment by RudenkoRNK** [comment]
So, this was a bug in the spec, and there should not be any `cl_size_t` type in the library, right? I suppose this issue can be closed then.

**Comment by keryell** [comment]
> So, this was a bug in the spec, and there should not be any `cl_size_t` type in the library, right? I suppose this issue can be closed then.

Yes, unfortunately a bug in the specification...
