### ISSUE TITLE
Cannot build CTS

### ISSUE THREAD

**Issue by nyalloc** [intel/llvm#3020]
Trying to build the [SYCL CTS](https://github.com/KhronosGroup/SYCL-CTS) fails to build when using the lastest Intel LLVM.

```sh
cmake -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=/home/stuart/2021/llvm/build ../
make
```

Results in numerous failures with the same complaint:

```sh
In file included from /home/stuart/2021/llvm/build/bin/../include/sycl/CL/sycl.hpp:16:
In file included from /home/stuart/2021/llvm/build/bin/../include/sycl/CL/sycl/ONEAPI/reduction.hpp:14:
/home/stuart/2021/llvm/build/bin/../include/sycl/CL/sycl/handler.hpp:819:9: error: no matching function for call to object of type 'const accessor_utility::buffer_accessor_api_r<int, 0, sycl::access::mode::read, sycl::access::target::global_buffer, sycl::access::target::global_buffer, sycl::access::placeholder::false_t>'
        KernelFunc(Arg);
        ^~~~~~~~~~
```

**Comment by bader** [comment]
@nyalloc, unfortunately, I can't reproduce this problem.

> ```shell
> /home/stuart/2021/llvm/build/bin/../include/sycl/CL/sycl/handler.hpp:819:9: error: no matching function for call to object of type 'const accessor_utility::buffer_accessor_api_r<int, 0, sycl::access::mode::read, sycl::access::target::global_buffer, sycl::access::target::global_buffer, sycl::access::placeholder::false_t>'
>         KernelFunc(Arg);
>         ^~~~~~~~~~
> ```

Line [819](https://github.com/intel/llvm/blob/sycl/sycl/include/CL/sycl/handler.hpp#L819), doesn't look like this in the latest version of the source code. Could you check if your build directory is up-to-date, please?

**Comment by v-klochkov** [comment]
I don't know if CTS that I am using is the latest one. It is reproducible for me.
Below is the reduced version of one of failed CTS tests:
> #include <CL/sycl.hpp>
> 
> struct MyFunctor {
>   void operator()(cl::sycl::id<1> idx) {}
> };
> 
> void run() {
>   cl::sycl::queue queue;
>   queue.submit([&](cl::sycl::handler &handler) {
>     handler.parallel_for(cl::sycl::range<1>{8}, MyFunctor());
>   });
> }

clang++ -fsycl accessor_api_buffer.cpp

> 15:44:29 > clang++ -fsycl accessor_api_buffer.cpp 
> In file included from accessor_api_buffer.cpp:1:
> In file included from /export/users/vklochko/ws/gs_public/llvm/build/install/bin/../include/sycl/CL/sycl.hpp:16:
> In file included from /export/users/vklochko/ws/gs_public/llvm/build/install/bin/../include/sycl/CL/sycl/ONEAPI/reduction.hpp:15:
> /export/users/vklochko/ws/gs_public/llvm/build/install/bin/../include/sycl/CL/sycl/handler.hpp:823:9: error: no matching function for call to object of type 'const MyFunctor'
>         KernelFunc(Arg);
>         ^~~~~~~~~~
> /export/users/vklochko/ws/gs_public/llvm/build/install/bin/../include/sycl/CL/sycl/handler.hpp:1035:5: note: in instantiation of function template specialization 'sycl::handler::parallel_for_lambda_impl<sycl::detail::auto_name, MyFunctor, 1>' requested here
>     parallel_for_lambda_impl<KernelName>(NumWorkItems, std::move(KernelFunc));
>     ^
> accessor_api_buffer.cpp:10:13: note: in instantiation of function template specialization 'sycl::handler::parallel_for<sycl::detail::auto_name, MyFunctor>' requested here
>     handler.parallel_for(cl::sycl::range<1>{8}, MyFunctor());
>             ^
> accessor_api_buffer.cpp:4:8: note: candidate function not viable: 'this' argument has type 'const MyFunctor', but method is not marked const
>   void operator()(cl::sycl::id<1> idx) {}
>        ^
> 1 error generated.
> 

Adding 'const' specifier to the MyFunctor::operator() fixes the problem.

**Comment by bader** [comment]
@v-klochkov, you should build SYCL-CTS with `-sycl-std=121` option ON.
If you are building source from https://github.com/KhronosGroup/SYCL-CTS/ repository, please, make sure that it contains this commit - 
https://github.com/KhronosGroup/SYCL-CTS/commit/856f9a2a63bedc2c72c4ffb2ae745b0657d7aa2d.

**Comment by v-klochkov** [comment]
I forgot to write that, but with -sycl-std=121 the error is the same. A month or two ago -sycl-std=121 worked as a workaround for that issue, but not now. Probably, something got pulled to compiler

**Comment by v-klochkov** [comment]
The problem is caused by the fix https://github.com/intel/llvm/pull/2703
