### ISSUE TITLE
"ii" is a low-quality name for an attribute

### ISSUE THREAD

**Issue by AaronBallman** [intel/llvm#3035]
While in the attribute definition file, I happened to notice that we have an attribute named `[[intel::ii]]` (https://github.com/intel/llvm/blob/sycl/clang/include/clang/Basic/Attr.td#L1843). While `ii` may have some domain-specific meaning within SYCL, that meaning doesn't translate well when reading code. I'd have no idea what such an attribute would mean or what effects it could have when reading code.

I think we should pick a more descriptive identifier for the attribute name and deprecate the old name. Additionally, we should update the semantic attribute name to something more descriptive than `SYCLIntelFPGAII` and correctly mark that the attribute is a statement attribute.

**Comment by MrSidims** [comment]
Tagging @GarveyJoe

**Comment by GarveyJoe** [comment]
That's fair.  II in this case is short for initiation interval, which is a well known concept and acronym in the context of pipelined loops and high level synthesis but not for SYCL users in general.  [[intel::initiation_interval]] or [[intel::pipelineII]] would be more descriptive.  @ajaykumarkannan what do you think?  If we change this I ask that we support both names for some time to give users time to make the switch in their code and us time to make the switch in our examples.

**Comment by AaronBallman** [comment]
I think `[[intel::initiation_interval]]` would be plenty descriptive -- it would certainly solve my concerns. And I agree on the deprecation strategy. We should even be able to provide a pretty easy fixit to help users migrate their code to the new name.

**Comment by ajaykumarkannan** [comment]
While I agree with the sentiment here, II is an extremely common initialism in the FPGA community, so every user who would want to use this would know what it means, and I worry a little about forcing a more verbose naming here. Is one option allowing both to cater to both types of users? Note that this attribute will have no impact on non-FPGA targets.

**Comment by AaronBallman** [comment]
I don't think having both names officially supported is a good option, though it wouldn't be a burden for us to implement. The biggest issue is that users will invariably be confused as to why there are two names (neither of which is deprecated) which adds complexity when they need to decide which spelling to use. Additionally, should anyone else want to be compatible with our behavior, they're stuck implementing two attributes (which may be harder for implementations outside of Clang). I think using `ii` would be a barrier to upstreaming the attribute to community, as well (I'm uncertain if that's a concern here or not).

**Comment by ajaykumarkannan** [comment]
I solicited an initial set of feedback from some of our internal users. The gist is that that they would object to anything but ii or initiation_interval, and while they're not happy about the extra 21 characters that they would have to type, this is the only feasible alternative that is descriptive. While II is a common term in the FPGA community, it is also not web searchable whereas "initiation interval" is. I think it is reasonable for now. Let me confirm within a day or two though, once I get the rest of the feedback.

**Comment by AaronBallman** [comment]
Sounds good to me, thank you! Btw, regarding the name length, the usual approach for most attributes is to hide them behind a macro for code portability reasons, so `#define II(N) [[intel::initiation_interval(N)]]` would always be a possibility for those users.

**Comment by ajaykumarkannan** [comment]
Got it, thanks Aaron. I just got consensus. I think we can go ahead with `initiation_interval`.

**Comment by AaronBallman** [comment]
Thanks! I'll go ahead and assign this issue to myself and tackle it, unless anyone objects.

**Comment by keryell** [comment]
At least you save the characters of `#pragma `...
