### ISSUE TITLE
[SYCL][Compilation] Question on Mangling of Record Types

### ISSUE THREAD

**Issue by agozillon** [intel/llvm#304]
So I was looking through some Kernel IR recently and I had a question on why we're currently mangling RecordDecl's during CodeGen inside of the addRecordTypeName function, snippet here: https://github.com/intel/llvm/blob/sycl/clang/lib/CodeGen/CodeGenTypes.cpp#L64

There is a comment right now but it isn't too descriptive (probably because I lack the background knowledge) to me about what the problem it's solving is, to me it seems to be a Re-flower thing, as it mentions reflown to a proper name?  If it is a Re-flower related segment of code, do we still require it as we've removed the Re-flower pass?

We currently don't have an issue with this piece of code, but I was interested in what the workaround is currently for! Thanks.

**Comment by bader** [comment]
@agozillon, good question.
I think you are right assuming that it was added with the re-flower pass.
https://github.com/intel/llvm/commit/2260ff1ea61329baf4b4d28553685ade64990122

@Fznamznon, could you check if this code is still needed, please?
