### ISSUE TITLE
Sphinx documentation target can't be built because of documented attribute without spelling

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#3046]
The following attribute breaks sphinx documentation build:

https://github.com/intel/llvm/blob/9c136945ed0d83caa56463cb2e8b765dff322b32/clang/include/clang/Basic/Attr.td#L1183-L1190

Example of logs:
```
build.log: 1616: [100%] Built target 
build.log: 1617: llvm/clang/docs/../include/clang/Basic/Attr.td:1201:1: error: Attribute has no supported spellings; cannot be documented
build.log: 1618: def SYCLSimdAccessorPtr : InheritableAttr {
build.log: 1619: ^
build.log: ...
build.log: 1620: make[3]: *** [tools/clang/docs/AttributeReference.rst] Error 1
```

https://github.com/intel/llvm/blob/9c136945ed0d83caa56463cb2e8b765dff322b32/clang/utils/TableGen/ClangAttrEmitter.cpp#L4084-L4088

**Comment by AaronBallman** [comment]
I can take this one on Tue when I get back, if no one else gets to it first.

**Comment by kbobrovs** [comment]
The fix: https://github.com/intel/llvm/pull/3058
