### ISSUE TITLE
[SYCL] Question : Which GPU devices are supported?

### ISSUE THREAD

**Issue by pramodk** [intel/llvm#312]
Hello All,

Thanks for excellent efforts! I am new to OpenCL/SYCL ecosystem and would like to clarify about which GPU devices are supported from this sycl branch.

On my linux box I have installed OpenCL and see following devices:

```
$ clinfo | grep Device
  Device Name                                     Quadro K620
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Device Type                                     GPU
...
  Device Name                                     Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.1 (Build 0)
  Device Type                                     CPU
...
```

Using `sycl::device::get_devices()`, I am able to list both devices. But, can I offload to NVIDIA device? I am assume not (?). (Or, with SPIR-V this is possible?)

It will be great if you could clarify/confirm.

**Comment by illuhad** [comment]
I'm not one of the devs here, but to my knowledge it's not possible to target NVIDIA GPUs with clang SYCL since NVIDIA's OpenCL implementation doesn't support SPIR-V ingestion. In order to run SYCL on NVIDIA GPUs, you can however use the [hipSYCL](https://github.com/illuhad/hipSYCL) implementation of SYCL.

**Comment by alexbatashev** [comment]
@pramodk @illuhad the offline compilation mode is also supported. You can see an example [here](https://github.com/intel/llvm/blob/sycl/sycl/test/aot/with-llvm-bc.cpp). So, technically, you can get SPIRV, convert it to LLVM IR, compile it with LLVM (I believe it has NVidia backend) and bundle with your app. However, a) it is very complicated b) I haven't tried it myself.

**Comment by keryell** [comment]
Or you can just use the LLVM IR before going through SPIR-V.
This is what is done in https://github.com/triSYCL/sycl for some devices not supporting SPIR-V.
But anyway none of these solutions can use the 2 Nvidia+Intel GPU at the same time out-of-the-box... :-(

**Comment by bhack** [comment]
Nvidia just has the president chair of Kronos Group. Is it a little bit funny? ☺

**Comment by AlexeySachkov** [comment]
@pramodk, was your question answered? can we close this ticket?

**Comment by pramodk** [comment]
yes, we can close this. Thank you very much!
