### ISSUE TITLE
[Question][CUDA] dump ptx code

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#3148]
How can a user dump PTX codes annotated with SYCL's kernel code ?

nvcc has the option "--source-in-ptx".

Thank you for the instructions.

**Comment by alexbatashev** [comment]
@zjin-lcf you can try `-fsycl-device-only` option. Also there's a `-###` compiler option. Instead of performing actual compilation, it will print out all the steps, required to obtain resulting binary. You can execute only those, that lead to PTX.

**Comment by zjin-lcf** [comment]
What is -### ?

**Comment by alexbatashev** [comment]
> What is -### ?

It's a command line option, just like `-g`, or `-O0`, or `-fsycl`. You just add `-###` to your compilation command line, and compiler driver prints exact steps it does to produce the result. It's aimed to be used to debug the driver, but can also serve your purpose. There's been a nice talk on LLVM Dev on how clang compiles the program, and it also explains the different driver stages and use of `-###`: https://youtu.be/5kkMpJpIGYU?t=438

**Comment by JackAKirk** [comment]
Probably the most straightforward way is to add `-save-temps` as an option to clang,
in which case it keeps the intermediately generated files in the same
location as other files generated by the build. For the cuda backend your PTX device code
will be in the longest named .S file. You should compile your program in an empty directory for -save-temps to work correctly.

Just do your normal build with `-save-temps` e.g.

`clang++ -fsycl .... -save-temps ....` etc

**Comment by zjin-lcf** [comment]
Thank you for your answers.
