### ISSUE TITLE
using item.barrier() to synchronize data accessed by USM

### ISSUE THREAD

**Issue by SimonWang9610** [intel/llvm#3192]
**Describe the bug**
I was trying to write matrix multiplication using sycl, but I found some problems that I can not fix. I an not sure whether they are bugs or not, so  I post here for some help.
In the below codes, if I use the first for-loop to calaulate `result_shared = w_device  * x_device + b_device`, it occasionally gave me wrong results (only part wrong elements). However, if I use the second for-loop, the result keep correct. I am confused about that.
I write another version of matrix multiplication using `Buffer and Accessor`, `item.barrier()` work correctly, and the result also keeps correct.
Therefore, I guess there are some problems when using `item.barrier()` to synchronize data accessed by USM. If I have wrong understanding, please let me know the right thing, thanks!.

**To Reproduce**
// data allocation
// result_shared = w_device * x_device + b_device
`int* w_device = malloc_device<int>(M * N, Q);`
`int* b_device = malloc_device<int>(M, Q);`
`int* temp = malloc_device<int>(SIZE, Q);`
`int* x_shared = malloc_shared<int>(N * K, Q);`
`int* result_shared = malloc_shared<int>(M * K, Q);`

//two events: copy data to device
`auto e1 = ... cgh.memcpy(w_device...)..;`
`auto e2 = ..cgh.memcpy(b_device...)...;`
`cgh.depneds_on({ e1, e2 });`

// nd_range<2>{ {M, K}, {1, GROUP_SIZE}}
`int m = item.get_global_id(0);`
`int n = item.get_global_id(1);`
`int i = item.get_local_id(1);`

//first for-loop
`for (int k = 0; k < N; k += GROUP_SIZE) {`
  `temp[i] = w_device[m][k +i];`
  `item.barrier();`
  `for(int kk = 0; kk < GROUP_SIZE; kk++) {`
   ` sum += temp[kk] * x_shared[(k + kk) * K + n];`
    `item.barrier();`
  `}
}`

//seond for-loop
`for(int k = 0; k < N; k++) { `
`  sum += w_device[m * N + k] * x_shared[k * K + n];`
`}`

//
`result[m * K + n] = sum + b_device[m];`

**Environment (please complete the following information):**

- OS: [windows 10
- Target device and vendor: IntelCPU
- OneAPI base tookit, version 2021.1.1

**Comment by SimonWang9610** [comment]
Also, if I use `work_group` instead of `nd_range`, the result also keep correct!

**Comment by illuhad** [comment]
In the SYCL execution model, synchronization is only possible within a work group. `item.barrier()`  only synchronizes work items within a group, it doesn't synchronize with other groups.
Since `item.get_local_id()` returns the same set of values for each work group, all your work groups are attempting to write into the same `temp` memory. Huge race condition, and most likely not a DPC++ bug.
For such a pattern to work you need to use local memory (which is memory that is allocated per work group) or offset the index that each work group uses for `temp`.
