### ISSUE TITLE
piEnqueueEventsWaitWithBarrier is not support by CUDA backend

### ISSUE THREAD

**Issue by smaslov-intel** [intel/llvm#3218]
**Describe the bug**
The PI function piEnqueueEventsWaitWithBarrier is not implemented by CIDA PI plugin.

**To Reproduce**
Use the barrier test (currently disabled for CUDA): https://github.com/intel/llvm-test-suite/blob/intel/SYCL/Basic/enqueue_barrier.cpp

**Environment (please complete the following information):**

- OS: Windows/Linux
- Target device and vendor: CUDA GPU
- DPC++ version: any
- Dependencies version: n/a

**Comment by masterleinad** [comment]
Partly addressed by #3932.

**Comment by npmiller** [comment]
The test is currently working and was re-enabled in https://github.com/intel/llvm-test-suite/pull/571

**Comment by AerialMantis** [comment]
As this feature was implemented for the CUDA backend and the test has been re-enabled we believe this issue has been resolved, and are closing this ticket, if there is still an issue or there is further work to do here we can re-open it.
