### ISSUE TITLE
[ESIMD] [[intel::sycl_explicit_simd]] does not work

### ISSUE THREAD

**Issue by RudenkoRNK** [intel/llvm#3229]
**Description**
This instruction advertises [[intel::sycl_explicit_simd]] attribute as the way to mark esimd kernels.
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/ExplicitSIMD/dpcpp-explicit-simd.md
Is it obsolete or is it the new way? If it is the new one, it does not work:
```
warning: unknown attribute 'sycl_explicit_simd' ignored [-Wunknown-attributes]
        range<1>{size / SIMDSize}, [=](id<1> id) [[intel::sycl_explicit_simd]] 
```

**To Reproduce**
Basically any esimd kernel:
```
#include <CL/sycl.hpp>
#include <CL/sycl/INTEL/esimd.hpp>

int main() {
  using namespace cl::sycl;
  using namespace sycl::INTEL::gpu;
  auto size = size_t{16};
  auto constexpr SIMDSize = unsigned{16};

  auto GPUSelector = gpu_selector{};
  auto q = queue{GPUSelector};
  auto vec = std::vector<int>(size);
  auto buf = buffer{vec};

  q.submit([&](handler &h) {
    auto access = buf.template get_access<access::mode::read_write>(h);
    h.parallel_for<class SimplestKernel>(
        range<1>{size / SIMDSize}, [=](id<1> id) [[intel::sycl_explicit_simd]] {
          auto data = simd<int, SIMDSize>(id * SIMDSize, 1);
          block_store<int, SIMDSize>(access, id * SIMDSize, data);
        });
  });
  buf.template get_access<access::mode::read_write>();

  for (auto i = 0; i != size; ++i)
    std::cout << "Index: " << i << "; Result: " << vec[i] << std::endl;
}
```

**Comment by bader** [comment]
Only GNU spelling is enabled for this attribute - https://github.com/intel/llvm/blob/489df6bbf3d4f307fee6cef1cc05caf2d395412d/clang/include/clang/Basic/Attr.td#L1179.

You can use `__attribute__((sycl_explicit_simd))` like here: https://github.com/intel/llvm/blob/d2d20d6c45561da8d107a68929f183fa7eb7e479/sycl/test/esimd/intrins_trans.cpp#L20

Either implementation or documentation must be fixed.

**Comment by NikitaRudenkoIntel** [comment]
Thanks!
GNU-styled one works.
