### ISSUE TITLE
Getting Error while compiling OneAPI sample codes

### ISSUE THREAD

**Issue by vibhad1509** [intel/llvm#3246]
**Describe the bug**
/tmp/vector-add-usm-fb120e.o: In function `VectorAdd(cl::sycl::queue&, int const*, int const*, int*, unsigned long)':
vector-add-usm.cpp:(.text+0x75): undefined reference to `cl::sycl::queue::submit_impl(std::__1::function<void (cl::sycl::handler&)>, cl::sycl::detail::code_location const&)'
/tmp/vector-add-usm-fb120e.o: In function `main':
vector-add-usm.cpp:(.text+0x320): undefined reference to `cl::sycl::queue::queue(cl::sycl::device const&, std::__1::function<void (cl::sycl::exception_list)> const&, cl::sycl::property_list const&)'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

**To Reproduce**
Please describe the steps to reproduce the behavior:

I get this error while compiling any of the oneapi sample codes. This is the command I ran:

/root/llvm-sycl/bin/bin/clang -O2 -std=c++17 -stdlib=libc++ -L/root/llvm-sycl/bin/lib/  -lpi_cuda -L/usr/local/lib/ -I /root/llvm-sycl/bin/include/sycl/ -lc++ -lc++abi -lm -lstdc++ -lsycl -o vector-add-usm src/vector-add-usm.cpp

**Environment (please complete the following information):**

- OS: RHEL7
- Target device and vendor: NVIDIA GPU
- DPC++ version: clang 13
- Dependencies version: 

**Additional context**

**Comment by alexbatashev** [comment]
@vibhad1509 I'm a bit concerned about `-stdlib=libc++`. Did you enable libc++ support in compiler at build time? We have a section about that in [Getting Started Guide](https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-libc-library). If not, the problem is not with the compiler. We use libstdc++ to build SYCL runtime by default, and user application must use it too.

**Comment by vibhad1509** [comment]
I have not explicitly enable libc++ support in compiler at build time. I get following error if I remove -stdlib=libc++
/root/llvm-sycl/bin/bin/clang -O2 -std=c++17  -L/root/llvm-sycl/bin/lib/ -lpi_cuda -L/usr/local/lib/ -I /root/llvm-sycl/bin/include/sycl/ -lc++ -lc++abi -lm -lstdc++ -lsycl -o vector-add-usm src/vector-add-usm.cpp
In file included from src/vector-add-usm.cpp:22:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic_accessor.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic_enums.hpp:12:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/access/access.hpp:10:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/detail/common.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/cl_ext_intel.h:44:
In file included from /root/llvm-sycl/bin/include/sycl/CL/cl.h:20:
/root/llvm-sycl/bin/include/sycl/CL/cl_version.h:22:9: warning: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2) [-W#pragma-messages]
#pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
        ^
In file included from src/vector-add-usm.cpp:22:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic_accessor.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic_enums.hpp:14:
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:52:22: error: no member named 'is_trivially_copyable' in namespace 'std'
  static_assert(std::is_trivially_copyable<From>::value,
                ~~~~~^
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:52:44: error: 'From' does not refer to a value
  static_assert(std::is_trivially_copyable<From>::value,
                                           ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:48:33: note: declared here
template <typename To, typename From>
                                ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:52:51: error: no member named 'value' in the global namespace
  static_assert(std::is_trivially_copyable<From>::value,
                                                ~~^
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:54:22: error: no member named 'is_trivially_copyable' in namespace 'std'
  static_assert(std::is_trivially_copyable<To>::value,
                ~~~~~^
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:54:44: error: 'To' does not refer to a value
  static_assert(std::is_trivially_copyable<To>::value,
                                           ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:48:20: note: declared here
template <typename To, typename From>
                   ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/detail/helpers.hpp:54:49: error: no member named 'value' in the global namespace
  static_assert(std::is_trivially_copyable<To>::value,
                                              ~~^
In file included from src/vector-add-usm.cpp:22:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic_accessor.hpp:14:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/accessor.hpp:12:
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/accessor_property_list.hpp:89:19: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
            !std::is_same_v<typename ContainerT::Head, void> &&
             ~~~~~^~~~~~~~~
                  is_same
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/type_traits:1278:12: note: 'is_same' declared here
    struct is_same
           ^
In file included from src/vector-add-usm.cpp:22:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic.hpp:11:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/atomic_accessor.hpp:14:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/accessor.hpp:12:
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/accessor_property_list.hpp:89:62: error: expected '(' for function-style cast or type construction
            !std::is_same_v<typename ContainerT::Head, void> &&
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
In file included from src/vector-add-usm.cpp:22:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl.hpp:15:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:14:
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/functional.hpp:27:17: error: too few template arguments for class template 'less'
    return std::less<>()(std::forward<const T>(lhs), std::forward<const U>(rhs))
                ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stl_function.h:231:12: note: template is declared here
    struct less : public binary_function<_Tp, _Tp, bool>
           ^
In file included from src/vector-add-usm.cpp:22:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl.hpp:15:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:14:
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/functional.hpp:44:17: error: too few template arguments for class template 'greater'
    return std::greater<>()(std::forward<const T>(lhs),
                ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stl_function.h:222:12: note: template is declared here
    struct greater : public binary_function<_Tp, _Tp, bool>
           ^
In file included from src/vector-add-usm.cpp:22:
In file included from /root/llvm-sycl/bin/include/sycl/CL/sycl.hpp:15:
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:167:10: error: no member named 'is_trivially_copyable' in namespace 'std'
    std::is_trivially_copyable<T>::value &&
    ~~~~~^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:167:32: error: 'T' does not refer to a value
    std::is_trivially_copyable<T>::value &&
                               ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:165:20: note: declared here
template <typename T>
                   ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:167:44: error: expected ';' after alias declaration
    std::is_trivially_copyable<T>::value &&
                                           ^
                                           ;
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:189:11: error: no member named 'is_trivially_copyable' in namespace 'std'
     std::is_trivially_copyable<T>::value) ||
     ~~~~~^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:189:33: error: 'T' does not refer to a value
     std::is_trivially_copyable<T>::value) ||
                                ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:185:20: note: declared here
template <typename T, typename BinaryOperation>
                   ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:189:37: error: no member named 'value' in the global namespace
     std::is_trivially_copyable<T>::value) ||
                                  ~~^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:308:27: error: no member named 'is_trivially_copyable' in namespace 'std'
                     std::is_trivially_copyable<T>::value &&
                     ~~~~~^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:308:49: error: 'T' does not refer to a value
                     std::is_trivially_copyable<T>::value &&
                                                ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:306:36: note: declared here
template <typename Group, typename T>
                                   ^
/root/llvm-sycl/bin/include/sycl/CL/sycl/ONEAPI/group_algorithm.hpp:308:53: error: no member named 'value' in the global namespace
                     std::is_trivially_copyable<T>::value &&
                                                  ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.

**Comment by vibhad1509** [comment]
nm -a /root/llvm-sycl/bin/lib/libsycl.so|grep submit_impl
00000000002dc5d0 T _ZN2cl4sycl5queue11submit_implESt8functionIFvRNS0_7handlerEEERKNS0_6detail13code_locationE
00000000002dc5f0 T _ZN2cl4sycl5queue11submit_implESt8functionIFvRNS0_7handlerEEES1_RKNS0_6detail13code_locationE
000000000008561a t _ZN2cl4sycl5queue11submit_implESt8functionIFvRNS0_7handlerEEES1_RKNS0_6detail13code_locationE.cold
00000000002dc070 t _ZN2cl4sycl6detail10queue_impl11submit_implERKSt8functionIFvRNS0_7handlerEEERKSt10shared_ptrIS2_ERKNS1_13code_locationE

**Comment by alexbatashev** [comment]
@vibhad1509 DPC++ requires GCC 7+ to work correctly. RHEL 7 should allow you to update your current GCC version. For example, using [these](https://developers.redhat.com/blog/2018/07/07/yum-install-gcc7-clang/) instructions.

**Comment by vibhad1509** [comment]
I have compiled all the code with gcc9.2

**Comment by keryell** [comment]
> @vibhad1509 DPC++ requires GCC 7+ to work correctly.

I guess you mean the C++ standard library from G++, not the compiler itself.
But anyway, it would be nice to have it working with the LLVM C++ standard library too and having it the CI validation.

**Comment by alexbatashev** [comment]
> it would be nice to have it working with the LLVM C++ standard library too

@jinge90 has submitted a number of patches recently, so it should be working if the runtime is linked with libc++.

> I have compiled all the code with gcc9.2

I'm not sure if your issue is resolved, but as Ronan mentioned above, you need to use the standard library, that comes with new compiler toolchain. One way you can do that is specifying `--gcc-toolchain=/path/to/gcc` flag to a location, where your gcc toolchain resides. Otherwise, clang should have taken the latest version of the runtime it could find in the standard location (which is usually `/usr`).

**Comment by pgorlani** [comment]
Unfortunately, we are not able to reproduce the behavior. Everything works as expected in our case.
When I compile the OneAPI sample with the ``-stdlib=libc+`` flag using a DPC++ built without the LLVM C++ standard library support, the compilation fails, as expected, due to a missing header. We able to compile and run the sample without any issues on a Titan RTX card within a Ubuntu 18.04.2 system using the following command.

```
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -O2 -g -std=c++17 -o vector-add-usm src/vector-add-usm.cpp

$ ./vector-add-usm
Running on device: TITAN RTX
Vector size: 10000
[0]: 0 + 0 = 0
[1]: 1 + 1 = 2
[2]: 2 + 2 = 4
...
[9999]: 9999 + 9999 = 19998
Vector add successfully completed on device.
```

The compilation of the sample goes as expected in versions of DPC++ built with and without the CUDA support, so we think that this issue is not related to the CUDA backend.

One contributing cause of this issue could be the utilization of ``clang`` in place of `clang++`, since this could cause linker errors.

**Comment by AerialMantis** [comment]
I've removed the CUDA label as it has been established this is not a CUDA-specific issue.
