### ISSUE TITLE
reqd_work_group_size argument checking

### ISSUE THREAD

**Issue by AaronBallman** [intel/llvm#3253]
According to https://www.intel.com/content/www/us/en/programmable/documentation/mwh1391807965224.html#mwh1391807939093, 11.3.1.2 says: "Note: The parameters of the reqd_work_group_size(X,Y,Z) attribute must be divisors of 2^32.". it is not clear how to interpret this note because it can be read two ways: 

1) that `reqd_work_groups_size` should *always* be able to evenly divide 2^32 (regardless of `autorun`).
2) in order to be eligible for `autorun`, a kernel function marked with `reqd_work_groups_size` has to be able to evenly divide 2^32 (if it doesn't, that's not an issue, the function is just not eligible for `autorun`).

DPC++ currently uses the second interpretation, but I'd like to validate that interpretation is correct.

**Comment by smanna12** [comment]
Tagging @GarveyJoe here for discussion here too.

**Comment by smanna12** [comment]
>>in order to be eligible for autorun, a kernel function marked with reqd_work_groups_size has to be able to evenly divide 2^32 (if it doesn't, that's not an issue, the function is just not eligible for autorun).

Currently we do not have support available for "autorun" attribute in DPC++, the OpenCL attribute is available only in downstream. My impression was that it is a requirement only when reqd_work_group_size is used in conjunction with autorun attribute.  Currently i can't prove this. 

Tagging @MrSidims for any information/comment on this?

**Comment by MrSidims** [comment]
> in order to be eligible for `autorun`, a kernel function marked with `reqd_work_groups_size` has to be able to evenly divide 2^32 (if it doesn't, that's not an issue, the function is just not eligible for `autorun`).

IMO this interpretation is correct, see: https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/functionQualifiers.html (`reqd_work_group_size` is not Intel-specific attribute, instead it's a part of core OpenCL spec). As we see, Intel spec append an extra rule in case of simultaneous use of `autorun` and `reqd_work_groups_size` attributes. 

AFAIK there are no plans to add support of `autorun` attribute in DPCPP (it serves a purpose to mark a kernel to be run automatically without explicit enqueue task launched by a user till programs' termination (to, for example, collect data from H/W periphery though I/O pipes) , and I think it can be emulated via USM). 

With all that said, I think the following statement is incorrect (in context of simulations usage of `autorun` and `reqd_work_group_size` attributes):

> Note: The parameters of the reqd_work_group_size(X,Y,Z) attribute must be divisors of 2^32. 

AFAIU autorun kernel shall be launched as a single work item kernel and hence `reqd_work_group_size` must have 1,1,1 parameters.

**Comment by AaronBallman** [comment]
Thank you for the explanation! In that case, I think this issue can be closed and we should probably open a new issue for the Intel OpenCL docs to be investigated or corrected.

**Comment by GarveyJoe** [comment]
In OpenCL autorun kernels actually can have larger reqd_work_group_sizes than 1,1,1 but extra restrictions apply to them in that case (e.g. they can't use get_compute_id()).  @MrSidims is correct that we don't currently support autorun in dpcpp and don't have any plans to at this time.

**Comment by AaronBallman** [comment]
@GarveyJoe -- do you know where I should open the issue for the Intel OpenCL docs? Once I (or someone) does that, I'll close this issue.

**Comment by GarveyJoe** [comment]
I opened one.

**Comment by smanna12** [comment]
> I opened one.

Thanks @GarveyJoe

**Comment by AaronBallman** [comment]
Thank you @GarveyJoe, I'll close this issue now.
