### ISSUE TITLE
SYCL 2020 Implementation prioritisation for me

### ISSUE THREAD

**Issue by tomdeakin** [intel/llvm#3258]
The SYCL 2020 features I'd like to see implemented are:

1. SYCL header location.
2. `sycl` namespace.
3. Unspecified work-group size `parallel_for(range<1>,)` reductions.
4. Accessor CTAD, though I think this is already there.
5. Multiple `sycl::reduction` objects in a single `parallel_for`.

For 1. through 4., my use case is the [SYCL 2020 update to BabelStream](https://github.com/UoB-HPC/BabelStream/pull/89). [More details](http://uob-hpc.github.io/2021/02/09/SYCL-2020.html) in this post.

For 5. the widely used CloverLeaf mini-app has a kernel which needs to reduce multiple variables. We have a [SYCL port of CloverLeaf](https://github.com/UoB-HPC/cloverleaf_sycl) that we need to update to SYCL 2020. The current SYCL 1.2.1 implementation is pretty verbose, and moving it to SYCL 2020 would be a big step forward.

**Comment by AlexeySachkov** [comment]
Hi @tomdeakin, 

At this point we consider intel/llvm SYCL implementation to be feature-complete and have everything from the SYCL 2020 specification implemented.

1,2,4 seem like a simple and obvious ones, I think that we have implemented them a while ago.

For 3 and 5, I found [`reduction_nd_N_vars.cpp`](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Reduction/reduction_nd_N_vars.cpp) and [`reduction_range_item.cpp`](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Reduction/reduction_range_item.cpp) to confirm that those are implemented as well.

Therefore, I will close the issue as complete, please let us know if you find any bugs or missing functionality
