### ISSUE TITLE
llvm.fshr.i32 missing

### ISSUE THREAD

**Issue by masterleinad** [intel/llvm#3308]
**Describe the bug**
Bit rotate right triggers "unexpected llvm intrinsic (`llvm.fshr.i32`)

**To Reproduce**
Compiling
```C++
#include <iostream>
#include <CL/sycl.hpp>


unsigned rotate_right(unsigned i, int r) {
  enum { size = static_cast<int>(sizeof(unsigned) * CHAR_BIT) };
  return r ? ((i >> r) | (i << (size - r))) : i;
}

int main(int, char**) {
   unsigned a = 1;
   unsigned b = 4;

   cl::sycl::default_selector device_selector;
   cl::sycl::queue queue(device_selector);
   queue.submit([&] (cl::sycl::handler& cgh) {
     cgh.single_task([=] () {
       rotate_right(a, b);
     });
   });
   return 0;
}
```
via 
```
clang++ -fsycl -fsycl-unnamed-lambda foo.cc
```
results in
```
InvalidFunctionCall: Unexpected llvm intrinsic:
 llvm.fshr.i32 [Src: /netbatch/donb1245322_00/runDir/95/20201113_160000/llvm/llvm-spirv/lib/SPIRV/SPIRVWriter.cpp:2634  ]
llvm-foreach: 
clang++: error: llvm-spirv command failed with exit code 1 (use -v to see invocation)
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz
- DPC++ version: Intel(R) oneAPI DPC++ Compiler 2021.1 (2020.10.0.1113) but also daily release 2021/03/03 (https://github.com/intel/llvm/commit/2a7a1496e3062fd585f88d86ade190096a990659)
- Dependencies version: OpenCL 2.1 (Build 0)

**Comment by AlexeySachkov** [comment]
Hi @masterleinad,

We have actually fixed this problem already in the upstream SPIR-V translator repo: KhronosGroup/SPIRV-LLVM-Translator#985, but by some reason I don't see this patch in intel/llvm repo: it looks like it was lost. @vmaksimo, could you please check as well and include it into the next pulldown?

**Comment by vmaksimo** [comment]
Actually, two commits were lost between WW17 and WW18 pulldowns:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/5071ae977065ac11661c6d3a9e56cf42f2258c42
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/b9e4fa4b912d9dc65f776c94197185a86d1d200f

I'll apply them with the nearest pulldown.

**Comment by vmaksimo** [comment]
These patches were merged as a part of https://github.com/intel/llvm/pull/3779 on May, 25.

**Comment by AlexeySachkov** [comment]
@vmaksimo, thanks!

@masterleinad, could you please verify that you don't see this problem on your side anymore and close the issue?

**Comment by masterleinad** [comment]
> @masterleinad, could you please verify that you don't see this problem on your side anymore and close the issue?

Yes, the issue seems to be resolved. Thanks!
