### ISSUE TITLE
Clang LIT tests using the sycl.hpp header should use "#" syntax instead of @Inputs/sycl.hpp@LINE

### ISSUE THREAD

**Issue by erichkeane** [intel/llvm#3415]
As discussed in #3345, we want to have all of those common warning places have a 'stable name' (done by adding a comment containing #SomeName), and to update all the tests to use the same syntax.

Tentatively assigning to @srividya-sundaram  since she did all the Inputs/sycl.hpp split work.

**Comment by elizabethandrews** [comment]
Just an FYI - I modified test lines breaking due to header change in my patch. I'm not sure if any remaining tests have this issue. This bug can be closed after this has been verified.

**Comment by bader** [comment]
I suggest we verify by adding an empty line at the beginning of the header to change **all** line numbers. PR https://github.com/intel/llvm/pull/3345 moves lines after 295, so all hard-coded checks for lines up to 295 are not verified by https://github.com/intel/llvm/pull/3345.

**Comment by erichkeane** [comment]
> 
> 
> I suggest we verify by adding an empty line at the beginning of the header to change **all** line numbers. PR #3345 moves lines after 295, so all hard-coded checks for lines up to 295 are not verified by #3345.

A just as easy way is to just  'grep' for "Inputs/sycl.hpp" in our files, just about every use should go away.
