### ISSUE TITLE
Refactor construction of LLVM-SPIRV job to eliminate duplicated code

### ISSUE THREAD

**Issue by DenisBakhvalov** [intel/llvm#3451]
There is some amount of duplicate code in `SPIRVTranslator::ConstructJob` and in `SYCL::Linker::constructLLVMSpirvCommand`, that was raised during the review of https://github.com/intel/llvm/pull/3443.

**Comment by mdtoguchi** [comment]
This was fixed here: https://github.com/intel/llvm/pull/5294
