### ISSUE TITLE
Fails to build with C++14

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#3490]
**Describe the bug**
Building with DPC++ with C++14 causes errors. Looks like 4524a6b1d06636b93f9805387ce2d2fec0374416 broke C++14 support and the only test that used it was removed shortly after: https://github.com/intel/llvm/commit/815b43b13c6e828992047c612e1a2854b790268c 

Among other similar errors, the commands results in the error:
```
.../include/sycl/CL/sycl/kernel_handler.hpp:51:13: error: 'auto' not allowed in template parameter until C++17
  template <auto &S, typename T = std::remove_reference_t<decltype(S)>,
            ^~~~
.../include/sycl/CL/sycl/kernel_handler.hpp:52:35: error: no template named 'is_fundamental_v' in namespace 'std'; did you mean 'is_fundamental'?
            std::enable_if_t<std::is_fundamental_v<T>> * = nullptr>
                             ~~~~~^
.../include/c++/7/type_traits:593:12: note: 'is_fundamental' declared here
    struct is_fundamental
           ^
```

Has C++14 support been dropped in its entirety?

**To Reproduce**
Build benchmark by running:
```
git clone https://gitlab.com/NERSC/nersc-proxies/su3_bench.git
cd su3_bench
make -f Makefile.dpcpp USE_SYCL=1 CC=path/to/clang++
```

**Environment:**

- OS: Linux
- Device: NVIDIA GPU
- DPC++ version: 77d4fdfb1f4ac0889f4687f8c0ecc16b586faa52

**Comment by dm-vodopyanov** [comment]
Hi @steffenlarsen, that's correct, since 4524a6b the compiler now supports C++17 and higher C++ standards. I've prepared a PR with an update to documentation: https://github.com/intel/llvm/pull/3478

**Comment by steffenlarsen** [comment]
According to the documentation (even after the current change in #3478):

> * DPC++ runtime and headers require C++14 at least.

However, the failure above stems from CL/sycl/kernel_handler.hpp using C++17 features, so it does not adhere to that requirement. Maybe that point needs to be change accordingly?

**Comment by pvchupin** [comment]
@steffenlarsen, any concerns if we move forward with #3447 ?

**Comment by steffenlarsen** [comment]
Apart from my comment above, if this is the plan I will not stand in the way. Thank you for clarifying. 😄
