### ISSUE TITLE
Remove FE dependency on SYCL header scope of accessor properties 

### ISSUE THREAD

**Issue by schittir** [intel/llvm#3529]
Remove the fragility caused by the FE relying on SYCL header scope gathered from the DeclContext; This needs to be addressed for not only no_alias, but also buffer_location and other (future) accessor properties such as no_offset and noinit. This can be addressed using an attribute consistently for all the accessor properties. Creating this task to as a follow-up to the conversation here: https://github.com/intel/llvm/pull/3452 

_Originally posted by @schittir in https://github.com/intel/llvm/pull/3452#discussion_r609933985_

**Comment by schittir** [comment]
Hi @AaronBallman - I am considering picking up this issue soon; there is still the case for it, but I don't think no_offset support is implemented yet. Could you please share your thoughts on this/what you would like to see?

**Comment by AaronBallman** [comment]
We should check with @bader and probably @erichkeane as well, but my thinking was that we should have an undocumented attribute that only works in system headers along the lines of what's prototyped in https://github.com/intel/llvm/pull/2091. I'm not certain where this PR ended up or why it was dropped though, so it'd be good to understand what was learned from it.

**Comment by erichkeane** [comment]
Yeah, that is supposed to be the direction of the fix.  @Fznamznon stopped working on CFE tasks, so I'm guessing that is why this was abandoned.

**Comment by bader** [comment]
@schittir, according to my understanding @zahiraam is about to start working on #2091.
Please, sync with @zahiraam to avoid work duplication.

**Comment by zahiraam** [comment]
> @schittir, according to my understanding @zahiraam is about to start working on #2091.
> Please, sync with @zahiraam to avoid work duplication.

Yes I have started looking at the #2091 that implements the sycl_class_attribute.

**Comment by schittir** [comment]
Thank you all for your comments/updates! I transferred this issue to @zahiraam

**Comment by zahiraam** [comment]
Implementation of the sycl_special_class attribute is here: https://github.com/intel/llvm/pull/3892
