### ISSUE TITLE
[CUDA] Build error in imageElementByteSize

### ISSUE THREAD

**Issue by Pennycook** [intel/llvm#3550]
**Describe the bug**
Trying to build the CUDA backend fails with the following error:
```
/home/sjpennyc/llvm/sycl/plugins/cuda/pi_cuda.cpp: In function ‘size_t imageElementByteSize(CUDA_ARRAY_DESCRIPTOR)’:
/home/sjpennyc/llvm/sycl/plugins/cuda/pi_cuda.cpp:3824:10: error: enumeration value ‘CU_AD_FORMAT_NV12’ not handled in switch [-Werror=switch]
   switch (array_desc.Format) {
          ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-covered-switch-default’ [-Werror]
cc1plus: all warnings being treated as errors
```

I've added a `default` to the switch statement locally to work around this, but the error about `-Wno-covered-switch-default` suggests to me that this is a violation of some style guide and some other fix is expected.

**To Reproduce**
Build with:
```
python3 ../buildbot/configure.py --cuda -t Release
ninja
```

**Environment:**

- OS: Ubuntu 18.04
- C/CXX Compiler: GNU 7.5.0
- CUDA Version: 11.0

**Comment by bader** [comment]
Probably this should be a feature request to support CUDA 11.
The supported CUDA version is 10.2.

**Comment by Pennycook** [comment]
> Probably this should be a feature request to support CUDA 11.
> The supported CUDA version is 10.2.

I'm happy to convert this to a feature request if that would be preferable; I wasn't sure exactly what was going on here.

The switch statement in question looks weird to me:
```c++
static size_t imageElementByteSize(CUDA_ARRAY_DESCRIPTOR array_desc) {
  switch (array_desc.Format) {
  case CU_AD_FORMAT_UNSIGNED_INT8:
  case CU_AD_FORMAT_SIGNED_INT8:
    return 1;
  case CU_AD_FORMAT_UNSIGNED_INT16:
  case CU_AD_FORMAT_SIGNED_INT16:
  case CU_AD_FORMAT_HALF:
    return 2;
  case CU_AD_FORMAT_UNSIGNED_INT32:
  case CU_AD_FORMAT_SIGNED_INT32:
  case CU_AD_FORMAT_FLOAT:
    return 4;
  }
  cl::sycl::detail::pi::die("Invalid iamge format.");
  return 0;
}
```
It covers all the formats from CUDA 10.2, so it's impossible to reach the `die` statement.  It seems like the design is intended to allow unsupported `enum` values, but the code doesn't compile in that case.

**Comment by steffenlarsen** [comment]
I think it was assumed that the compiler would allow incomplete switches, though we should arguably have checked. I think the easiest solution to your problem would be to move the `die` into a `default` case. I don't have CUDA 11 ready at this time so I cannot confirm whether or not that fixes your issue, but if you give it a try and confirm that it works I'll be happy to give a patch a 👍 .

**Comment by Pennycook** [comment]
> I think it was assumed that the compiler would allow incomplete switches, though we should arguably have checked. I think the easiest solution to your problem would be to move the `die` into a `default` case. I don't have CUDA 11 ready at this time so I cannot confirm whether or not that fixes your issue, but if you give it a try and confirm that it works I'll be happy to give a patch a 👍 .

Thanks, @steffenlarsen.  Makes sense to me -- I've opened a PR as https://github.com/intel/llvm/pull/3562.
