### ISSUE TITLE
install target

### ISSUE THREAD

**Issue by hiaselhans** [intel/llvm#3554]
i am trying to make a docker build container with llvm precompiled:
https://github.com/airgproducts/llvm/blob/private/Dockerfile

however i'd need some help with the install step:

```
RUN cmake --build . --target install
RUN cmake -DCMAKE_INSTALL_PREFIX=$DPCPP_PKG/usr -P cmake_install.cmake
```

results in CL/sycl being missing.
Also i can see a file `include/llvm/cmake_install.cmake` but none in `include/sycl`

how can i add the sycl toolchain to the install targets? Should we have a buildbot script for this aswell?

**Comment by bader** [comment]
Tagging @vladimirlaz.
Don't we use `deploy-sycl-toolchain` target instead of `install`?

**Comment by vladimirlaz** [comment]
We are using deploy-sycl-toolchain to install minimum subset of SYCL specific and LLVM files required to use SYCL compiler and runtime.

**Comment by hiaselhans** [comment]
thx @bader @vladimirlaz 

i tried:
``` bash
cmake --build . --target deploy-sycl-toolchain
cmake --install . --prefix pkg
ls pkg
>bin  include  lib  libexec  share
ls pkg/include
>clang  clang-c  clc  level_zero  llvm  llvm-c
```

no sign of CL/sycl.hpp includes... :/

**Comment by hiaselhans** [comment]
Here are my logs:

```
-- Up-to-date: /home/user/llvm_build/pkg/lib/clc/libspirv-nvptx64--nvidiacl.bc
-- Up-to-date: /home/user/llvm_build/pkg/lib/clc
-- Up-to-date: /home/user/llvm_build/pkg/lib/clc/clc-nvptx64--.bc
-- Up-to-date: /home/user/llvm_build/pkg/lib/clc/clc-nvptx64--nvidiacl.bc
-- Up-to-date: /home/user/llvm_build/install/include/sycl/CL
-- Up-to-date: /home/user/llvm_build/install/include/sycl/CL/cl_gl_ext.h
-- Up-to-date: /home/user/llvm_build/install/include/sycl/CL/cl_ext_intel.h
-- Up-to-date: /home/user/llvm_build/install/include/sycl/CL/cl_platform.h
```

so, after all it seems like the manifest targets don't support CMAKE_INSTALL_PREFIX ?

**Comment by alexbatashev** [comment]
@hiaselhans did you pass `-DCMAKE_INSTALL_PREFIX=smth` to your cmake configuration command? `configure.py` has `--cmake-opt` option for that.

**Comment by hiaselhans** [comment]
that's it, thanks!
The configure script already sets cmake_install_prefix.
