### ISSUE TITLE
Unable to compile intel/llvm on Linux Mint 20

### ISSUE THREAD

**Issue by SylvainJoube** [intel/llvm#3618]
**Describe the bug**

Unable to compile Intel/LLVM on branch `sycl`. Output for the build (at 97%) :

```
Scanning dependencies of target prepare-libspirv-nvptx64--nvidiacl.bc
[ 97%] Generating ../../lib/clc/libspirv-nvptx64--nvidiacl.bc
error: file too small to contain bitcode header
make[2]: *** [tools/libclc/CMakeFiles/prepare-libspirv-nvptx64--nvidiacl.bc.dir/build.make:62: lib/clc/libspirv-nvptx64--nvidiacl.bc] Error 1
make[1]: *** [CMakeFiles/Makefile2:77139: tools/libclc/CMakeFiles/prepare-libspirv-nvptx64--nvidiacl.bc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:152: all] Error 2
```

**To Reproduce**

Commands I used :

```
$ git clone https://github.com/intel/llvm
$ cd llvm
$ python ./buildbot/configure.py --cuda -t release --cmake-gen "Unix Makefiles"
$ cd build
$ ccmake .  # and disable the SYCL_ENABLE_WERROR flag
$ make install -j `nproc`
```

On branch `sycl`, at the following commit :

```
1811037bc8b3e9352b6806b24724eecb6d862895 (HEAD -> sycl, origin/sycl, origin/HEAD)
Date:   Sun Apr 25 14:11:44 2021 -0400).
```

**Environment (please complete the following information):**

OS : `Linux Mint 20 (Ulyana)` (based on Ubuntu focal)

Current compiler : `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

Clang version :
```
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Target device and vendor : `NVIDIA CUDA GPU`

Installed CUDA version : `cuda_11.3.r11.3/compiler.29745058_0`

**Comment by bader** [comment]
> Installed CUDA version : `cuda_11.3.r11.3/compiler.29745058_0`

FYI: CUDA 11 is not supported yet.

> Output for the build (at 97%) :

Could you attach the full log, please? I suppose the problem happened before:

> Scanning dependencies of target prepare-libspirv-nvptx64--nvidiacl.bc
> [ 97%] Generating ../../lib/clc/libspirv-nvptx64--nvidiacl.bc
> error: file too small to contain bitcode header

Tagging @steffenlarsen.

**Comment by SylvainJoube** [comment]
I thought CUDA 11 was fully supported yet, sorry, because @steffenlarsen just said on the IWOCL oneAPI Developer Summit (I'm currently following it) that his tests were working with CUDA 11 but I may have misunderstood what he was saying.

Here is the full log : [cuda_11-3_mint-20_log.log](https://github.com/intel/llvm/files/6377789/cuda_11-3_mint-20_log.log)

**Comment by bader** [comment]
The documentation still lists only CUDA 10.2: https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-nvidia-cuda (although I'm not sure it's relevant to the issue). Our CI system uses CUDA 10.x to build DPC++ with CUDA support and there is no such issue there.

**Comment by steffenlarsen** [comment]
> 
> 
> I thought CUDA 11 was fully supported yet, sorry, because @steffenlarsen just said on the IWOCL oneAPI Developer Summit (I'm currently following it) that his tests were working with CUDA 11 but I may have misunderstood what he was saying.
> 
> Here is the full log : [cuda_11-3_mint-20_log.log](https://github.com/intel/llvm/files/6377789/cuda_11-3_mint-20_log.log)

I am glad I made an impression! Yes, I am currently using CUDA 11.0, however we haven't yet gone as far as to mark it as "officially support".

That said, I was able to reproduce your problem. Looks like using Unix Makefiles to build DPC++ for CUDA causes a problem in libclc. Exactly what the issue is still to be determined, but the quickest solution may be to use Ninja instead if possible.

**Comment by steffenlarsen** [comment]
If Ninja is not available, you can try and run the make command again. For me it succeeded after failing the first time. It smells a bit like a broken dependency in libclc.

**Comment by steffenlarsen** [comment]
Great news, @SylvainJoube! I believe I found the issue and has a fix up (https://github.com/intel/llvm/pull/3624) so if you ever feel like returning to using Unix Makefiles as the generator you should hopefully be able to.

Thank you for reporting this issue. I will discuss this with the tutorial maintainers so we avoid problems like this in the future. If you have any other issues, feel free to ping me directly on the issue. It saves @bader the trouble. 😄

**Comment by SylvainJoube** [comment]
Oh, great, thank you !

Got it, I'll remember it should I have another issue :)
