### ISSUE TITLE
[Driver] Clang :: Driver/sycl-device-lib.cpp fails if libdevice project is not pre-built

### ISSUE THREAD

**Issue by bader** [intel/llvm#3630]
**Describe the bug**
`Clang :: Driver/sycl-device-lib.cpp` has a dependency on `libdevice` libraries. It seems to me, that driver schedules different actions based on presence of `libdevice` libraries. If libraries are missing some actions are skipped, but test passes only if required libraries are present.

**To Reproduce**
Checkout `sycl` branch, configure build files and build `check-clang` target. It's important to not build `libdevice` target or any other target building `libdevice` (e.g. `check-sycl`) before building `check-clang`.

**Environment (please complete the following information):**

- OS: Linux

**Comment by bader** [comment]
@jinge90, it looks like the is not fixed. There were two commits recently breaking SYCL project build, which impacted `check-clang` results. `Clang :: Driver/sycl-device-lib.cpp` still fails if libdevice project is not built.
Could you take a look, please?
See https://github.com/intel/llvm/runs/2738419633?check_suite_focus=true and https://github.com/intel/llvm/runs/2740297660?check_suite_focus=true for details.

**Comment by jinge90** [comment]
> @jinge90, it looks like the is not fixed. There were two commits recently breaking SYCL project build, which impacted `check-clang` results. `Clang :: Driver/sycl-device-lib.cpp` still fails if libdevice project is not built.
> Could you take a look, please?
> See https://github.com/intel/llvm/runs/2738419633?check_suite_focus=true and https://github.com/intel/llvm/runs/2740297660?check_suite_focus=true for details.

Hi, @bader 
It looks weird, I just built the latest compiler and removed all libdevice binary, the sycl-device-lib.cpp can still pass with all the libdevice binary removed.
Can I log in the machine to have a look or can anyone provide the file list in compiler library folder from the failed SYCL project?
Thanks very much.

**Comment by bader** [comment]
I think this issue should be reproducible from clean state (i.e. when build directory is removed):
1. run `configure.py` + `check-clang` before building other targets.
2. or maybe `make/ninja clean` + `check-clang` will work.

Anyway the steps from post-commit will work if you checkout https://github.com/intel/llvm/commit/70281eac7af19d242259490ec4ae88c4248f8cf5.

> Can I log in the machine to have a look or can anyone provide the file list in compiler library folder from the failed SYCL project?

Please, contact @tfzhu or @DoyleLi, if you won't be able to reproduce it locally.
