### ISSUE TITLE
latest OpenCL cpu runtime not working

### ISSUE THREAD

**Issue by ImanHosseini** [intel/llvm#3652]
I have the latest graphics drivers (27.20.100.9466), Windows 10 OS, I followed the instructions here: [https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#install-low-level-runtime)to get CPU runtime, and now the device (CPU) is exposed to OpenCL (it gets listed) _BUT_ it doesn't work, for valid code that works on Intel HD GPU/ nvidia GPU, if I try to run on CPU, it throws -36 error (invalid command queue)
=> The instructions are obviously wrong. The installation batch file makes a symlink to "tbb.dll", and guess what? There is NO "tbb.dll" not in the latest oneAPI version which I had, and not if you go through the _LINKED_ github repo and build tbb from the source -> it has a tbb12.dll and NOT tbb.dll   EVEN the archived binaries -> no tbb.dll . And the batch script just makes a broken symlink.

**Comment by ImanHosseini** [comment]
Ok, the issue was _just_ that: if you manually move tbb12.dll, it works. I didn't find that 'install.bat' and well, it has already made it's way to *Release*, anyway hopefully someone can fix that, or add a line here: [https://github.com/intel/llvm/edit/sycl/sycl/doc/GetStartedGuide.md](https://github.com/intel/llvm/edit/sycl/sycl/doc/GetStartedGuide.md) saying that either rename tbb12.dll to tbb.dll before running install.bat, or do the copying by hand.

**Comment by ImanHosseini** [comment]
This did not solve it, now the program crashes at clCreateContext, and here is the debugging state: 
![icrash](https://user-images.githubusercontent.com/12172889/116509196-e70bcf80-a890-11eb-887b-22aef9986ed8.PNG)

**Comment by vladimirlaz** [comment]
I have applied fix in install.bat https://github.com/intel/llvm/pull/3654
As a workaround you can create links to correct files manually

**Comment by ImanHosseini** [comment]
> This did not solve it, now the program crashes at clCreateContext, and here is the debugging state:
> ![icrash](https://user-images.githubusercontent.com/12172889/116509196-e70bcf80-a890-11eb-887b-22aef9986ed8.PNG)

As I discovered above, this did not work, it seems the "tbb.dll" isn't a typo:

The renaming did not fix it for me. What fixed it was using an older OneTBB release from 2020. Back then it was actually named 'tbb.dll' so it seems that it was meant to work with that version and it's incompatible with new tbb12 ones. Fix would be to change dependency configuration file and instructions to reflect the correct (older) version of OneTBB maybe?

**Comment by vladimirlaz** [comment]
@ImanHosseini  Could you please share the link you used to get CPU RT?

**Comment by ImanHosseini** [comment]
installation instructions links to: https://github.com/intel/llvm/blob/sycl/buildbot/dependency.conf
in which we find: https://downloadmirror.intel.com/30381/a08/igfx_win10_100.9466.zip
and I guessed that the issue is compatiblity with OneTBB because the dll used to be called 'tbb.dll' so I guessed the batch install was made back then and the rt would work with that older version (and it does).
