### ISSUE TITLE
compile_sub_group_size is not implemented

### ISSUE THREAD

**Issue by turinevgeny** [intel/llvm#367]
info::kernel_sub_group::compile_sub_group_size from sub_group_ndrange is not implemented:

`: error: no member named 'compile_sub_group_size' in 'cl::sycl::info::kernel_sub_group'; did you mean 'kernel_sub_group_size'?
cl::sycl::info::kernel_sub_group::compile_sub_group_size>(device);
          kernel_sub_group_size
`

**Comment by shileiti** [comment]
Does anyone plan to fix it? Or I'd like to help. :)

**Comment by AlexeySachkov** [comment]
@turinevgeny, I believe this issue is fixed by #373
