### ISSUE TITLE
How to use cudnn or cublas by DPC++?

### ISSUE THREAD

**Issue by malixian** [intel/llvm#3711]
Is it possible to achieve this demand? Can you give me an example？

**Comment by alexbatashev** [comment]
Both [oneDNN](https://github.com/oneapi-src/oneDNN) and [oneMKL](https://github.com/oneapi-src/oneMKL) have CUDA backend, and as far as I know, they use cudnn and cublas under the hood. As a bonus you get full DPC++ compatibility and performance portability across multiple vendors and device types. Would that fit your needs?
