### ISSUE TITLE
[SYCL] Unnamed lambdas should be fine with -sycl-std=2020

### ISSUE THREAD

**Issue by pkeir** [intel/llvm#3740]
With a build of the current DPC++ tip, the code below from Section 3.2 of the SYCL 2020 spec. can be compiled using `clang++ -fsycl -fsycl-unnamed-lambda sycl_spec_2020_example_3_2.cpp`.

The same command will fail with the `-fsycl-unnamed-lambda` flag removed; even with `-sycl-std=2020` added explicitly. Am I right that the code below should build without the `-fsycl-unnamed-lambda` flag?

```
#include <iostream>
#include <sycl/sycl.hpp>
using namespace sycl;

int main() {
  int data[1024]; // Allocate data to be worked on

  queue myQueue;

  {
    buffer<int, 1> resultBuf { data, range<1> { 1024 } };

    myQueue.submit([&](handler& cgh) {
      accessor writeResult { resultBuf, cgh, write_only, no_init };

      cgh.parallel_for(1024, [=](id<1> idx) {
        writeResult[idx] = idx;
      }); // End of the kernel function
    });   // End of our commands for this queue
  }       // End of scope, so we wait for work producing resultBuf to complete

  for (int i = 0; i < 1024; i++)
    std::cout << "data[" << i << "] = " << data[i] << std::endl;

  return 0;
}
```

**Comment by erichkeane** [comment]
I don't have a good idea of that, are we saying that 'unnamed lambda' support is required for SYCL2020?  If so, there is likely a task here to enable that feature by default.  @mdtoguchi : is this something that fits in with the driver, or should this be done in the CC1 invocation? @AaronBallman : Do you happen to know how we might do that for the marshalling?

**Comment by AaronBallman** [comment]
> I don't have a good idea of that, are we saying that 'unnamed lambda' support is required for SYCL2020? If so, there is likely a task here to enable that feature by default. @mdtoguchi : is this something that fits in with the driver, or should this be done in the CC1 invocation? @AaronBallman : Do you happen to know how we might do that for the marshalling?

Given that CC1 has a `-sycl-std=`, this likely should be handled in the CC1 invocation only if the `-fno-` flag is not also present. I have no idea how to do that from the new-fangled marshaling stuff.

**Comment by erichkeane** [comment]
Actually, I'm not sure how we could do this with our compiler without driver help.  The unnamed-lambdas only work with support for __builtin_unique_stable_name in the 'host' compiler, so we can't jsut set this with sycl-2020.

**Comment by mdtoguchi** [comment]
I suppose the driver could be of assistance here given the lovely ability to call an external host compiler. :)

**Comment by zjin-lcf** [comment]
My test is that the compiler reports errors without using the 'unamed flag' 

sycl/CL/sycl/handler.hpp:1004:50: error: unnamed lambda 'sycl::detail::__pf_kernel_wrapper<(lambda at )>' used

a minor change: no_init -> noinit

**Comment by AlexeySachkov** [comment]
> Is this a bug?

SYCL 2020 spec explicitly says that unnamed lambdas should work, so yes, this seems to be a bug

> My test is that the compiler reports errors without using the 'unamed' flag. The '2020' flag is not used.

In SYCL 1.2.1 unnamed lambdas aren't a thing and we require a flag explicitly.

Anyway, unnamed lambdas are enabled by default in SYCL 2020 mode since 55a1b088c6761, therefore closing the issue
