### ISSUE TITLE
[SYCL][CUDA] Support multiple devices 

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#3745]
Add a relevant issue for multiple Nvidia GPUs  when running the example #3583 

Thanks.

llvm/sycl/plugins/cuda/pi_cuda.cpp:1588: pi_result cuda_piContextCreate(const pi_context_properties*, pi_uint32, _pi_device* const*, void (*)(const char*, const void*, size_t, void*), void*, _pi_context**): Assertion `num_devices == 1' failed.

**Comment by AerialMantis** [comment]
@zjin-lcf there is a ticket for exploring support for multi-device contexts in the CUDA backend - https://github.com/intel/llvm/issues/4381, does this cover what you're looking for?

**Comment by zjin-lcf** [comment]
You were discussing the implementation details of the feature. I wonder if the concept of "context" can be hidden from a user. For example, if there are N devices on a platform, then N queues must be created for N devices.

Thanks for your question. It covers what people looked for.

**Comment by AerialMantis** [comment]
Apologies for the delayed reply. So in SYCL there is always a context associated with work being enqueued to a device, in some cases this is implicit, for example if a queue is constructed it will create an implicit context. However, the context is used to ensure efficient sharing of data between devices which have visibility of each other's memory, those from the same platform, so to ensure this a queue can be constructed from an explicit context. So the user can choose to create a separate context per device or use a shared context.

**Comment by zjin-lcf** [comment]
No problem. Thank you for your explanation.
