### ISSUE TITLE
[ESIMD] private_memory tests sporadically fail

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#3758]
`pm_access_1/2/3` tests fail on GPU sporadically with the following error message:

```
LLVM ERROR: Cannot find pointer replacement
```

They were disabled in intel/llvm-test-suite#277 and intel/llvm-test-suite#282. Failures were encountered in #3748 and #2292. This issue is submitted to track analysis and tests re-enabling

**Comment by bader** [comment]
More instances of these failures in https://github.com/intel/llvm/pull/3634 and https://github.com/intel/llvm/pull/3718

**Comment by DenisBakhvalov** [comment]
Yes, the vector backend compiler team is working on it.

**Comment by sarnex** [comment]
These tests are all enabled and passing.
