### ISSUE TITLE
[SYCL][CUDA] Recommended API for deprecated ones

### ISSUE THREAD

**Issue by mmeterel** [intel/llvm#3780]
oneMKL open source interfaces is using the context "get" API for CUBLAS backend. As noted below, it is being deprecated. What is the recommendation to replace this API?

https://github.com/intel/llvm/blob/bd581c5e04338dc068bdbedd8980ae4bf76bdbe1/sycl/include/CL/sycl/context.hpp#L191

**Comment by bader** [comment]
I think this message must be updated to include the replacement.

**Comment by romanovvlad** [comment]
@alexbatashev  Could you please help?

**Comment by alexbatashev** [comment]
> oneMKL open source interfaces is using the context "get" API for CUBLAS backend

That is not a correct usage of APIs. `get()` method does not return a native handle for CUDA backend, and instead returns [this structure](https://github.com/intel/llvm/blob/sycl/sycl/plugins/cuda/pi_cuda.hpp#L123).

> What is the recommendation to replace this API?
You can use [get_native](https://github.com/intel/llvm/blob/5c4275ac8f37f210a2529ab494dcf74c56ba8406/sycl/include/CL/sycl/backend.hpp#L64)

**Comment by mmeterel** [comment]
@alexbatashev Thanks for the recommendation. It works. Closing.
