### ISSUE TITLE
[SYCL] segfaulting accessor

### ISSUE THREAD

**Issue by reguly** [intel/llvm#379]
I have an application, which compiles and runs fine with ComputeCpp and hipSYCL, however, I am getting segfaults with this compiler. Both with CPU target (using the experimental drivers), and the host target.

Is there something non-standard I am doing? Error is coming when accessing du (all the rest I can access, and they have the valid results)
https://github.com/OP-DSL/OP2-Common/blob/736c89e59d5269f5c094277849c3045c619354d1/apps/c/jac1/dp/sycl/res_kernel.cpp#L110

**Comment by bader** [comment]
@reguly, thanks for this reporting this issue.
I'll try to investigate.
How can I reproduce the crash?

**Comment by reguly** [comment]
Here is the procedure (assumes g++ and clang++ are in the PATH).

git clone https://github.com/OP-DSL/OP2-Common.git -b feature/sycl
cd OP2-Common/op2/
export OP2_COMPILER=sycl
export OP2_INSTALL_PATH=`pwd`
cd c
make core sycl
cd ../../apps/c/jac1/dp/
make jac_sycl
./jac_sycl


Currently cpu_selector is used - can be changed in op2/c/src/sycl/op_sycl_rt_support.cpp:337 (needs recompiling).

**Comment by reguly** [comment]
Have you been able to reproduce this? Any ideas as to a solution or a workaround?

**Comment by bader** [comment]
@reguly, I was able to reproduce this issue, but I still debugging it.
I don't see any issues in SYCL code, it looks like data passed to the kernel is corrupted.

[Here](https://github.com/OP-DSL/OP2-Common/blob/736c89e59d5269f5c094277849c3045c619354d1/apps/c/jac1/dp/sycl/res_kernel.cpp#L121) we read an index from one SYCL buffer and use it to offset accessor to another buffer.

The index value I see in debugger is `-134458760`, which doesn't seem to be right.
I don't know the application good enough to say what is the root case of this problem.
Any ideas why `map1_buffer` may have values like this?

NOTE: `-134458760` is `0`th element (`map2idx`) of the buffer. `105` element (`map1idx`) of the buffer is something sane like (`0` IIRC).

**Comment by reguly** [comment]
@bader Thanks for looking into this - below is a short summary of how that buffer is set up. Of course this is across many different compilation units. Things are cast to raw pointers so they can be passed through a C API. The same exact code works fine with ComputeCpp (host & NVPTX) and hipSYCL (CUDA). In the debugger, I see correct values in pp being passed, before we read the invalid ones in the SYCL kernel itself. The values in map1_buffer should be between 0 and 25.

`int nedge = 105;`
`int *pp = (int *)malloc(sizeof(int) * 2 * nedge);`
`//populate pp`
`int *map_d = (int*)(void*)new cl::sycl::buffer<int, 1>((const int *)pp,
          cl::sycl::range<1>(2 * nedge));`
`free(pp);`
`cl::sycl::buffer<int,1> *map1_buffer = static_cast<cl::sycl::buffer<int,1>*>((void*)map_d);`
`op2_queue->submit([&](cl::sycl::handler &cgh) {`
`  auto opDat1Map = (*map1_buffer).template get_access<cl::sycl::access::mode::read>(cgh);`

**Comment by bader** [comment]
> `int nedge = 105;`
> `int *pp = (int *)malloc(sizeof(int) * 2 * nedge);`
> `//populate pp`
> `int *map_d = (int*)(void*)new cl::sycl::buffer<int, 1>((const int *)pp, cl::sycl::range<1>(2 * nedge));`
> **`free(pp);`** <--- this might be a problem.
> `cl::sycl::buffer<int,1> *map1_buffer = static_cast<cl::sycl::buffer<int,1>*>((void*)map_d);`
> `op2_queue->submit([&](cl::sycl::handler &cgh) {`
> ` auto opDat1Map = (*map1_buffer).template get_access<cl::sycl::access::mode::read>(cgh);`

Here is how buffer constructor is defined in the SYCL specification today:
```c++
buffer(const T* hostData,
  const range<dimensions> & bufferRange,
  const property_list &propList = {})
```
> Construct a SYCL buffer instance with the hostData parameter provided. **The ownership of this memory is given to the constructed SYCL buffer _for the duration of it’s lifetime_.**

Our implementation rely on this ownership to optimize data allocation/transfer.

If I remove `free(pp)`, the application do not crash and reports

> Results check PASSED!

**Comment by reguly** [comment]
My apologies, it does indeed work without the deallocation. My mistake for relying on ComputeCpp docs which implied otherwise.

**Comment by Ruyk** [comment]
@reguly  , what ComputeCpp docs are implying otherwise? We rely on the same behavior that intel does for various optimizations - you may be just being lucky that it works. You can't free a pointer after given it to a sycl::buffer , thats undefined behavior

**Comment by reguly** [comment]
@Ruyk 
[Here](https://developer.codeplay.com/products/computecpp/ce/api-reference/classcl_1_1sycl_1_1buffer) the version with const T* host_pointer says 

> The user has given a const pointer, but the buffer is not const, so the runtime copies the data into a temporary space created using the given allocator.

Which I took to mean that the original memory will not be used anymore. It does not explicitly state this of course.

**Comment by Ruyk** [comment]
I see. We create an internal copy when the origin is const but the buffer is not, so further down write accessors can write back to the host directly. But that's an implementation detail that we can change for different platforms and situations.

I'll open a ticket for the team to clarify the documentation, thanks!

**Comment by bader** [comment]
I also noticed one issue in build script: to link SYCL static library (i.e. library with the device code), special option is required (-foffload-static-lib).
You can find examples of use cases here: https://github.com/intel/llvm/blob/sycl/clang/test/Driver/sycl-offload.c#L353
+@mdtoguchi

**Comment by reguly** [comment]
Just to clarify, I should be linking libraries of my own that contain SYCL device code using this? Or a lib that comes with the compiler itself?

**Comment by mdtoguchi** [comment]
> Just to clarify, I should be linking libraries of my own that contain SYCL device code using this? Or a lib that comes with the compiler itself?

Any static library you create that contains device code (created with -fsycl -c, then archived) should be using -foffload-static-lib=<lib> to pull it in.
