### ISSUE TITLE
kernel_bundle::get_kernel_ids returns empty vector on CUDA

### ISSUE THREAD

**Issue by alexbatashev** [intel/llvm#3833]
kernel_bundle gets information about available kernels from offload entries. However, no offload entries are generated for CUDA images (according to [this](https://github.com/intel/llvm/pull/3609/files#diff-f8c64e36dfe3828a6f816c4550e78bb0305769ace1be53207e86ac9a3280ac9eR4351)). As a result no kernel_id-related APIs are available with CUDA backend.

**Comment by romanovvlad** [comment]
@mdtoguchi, @AGindinson  FYI

**Comment by pgorlani** [comment]
This issue seems fixed now, `sycl::get_kernel_ids()` returns a non-empty vector.

Please let me know if this is fine for you and we can close this issue.

**Comment by AerialMantis** [comment]
As the issue described is no longer reproducible we believe this issue to be resolved, so we're closing the ticket, if you still experience this issue we can re-open the ticket.
