### ISSUE TITLE
[Driver] Provide CLI for configuring SPIR-V extensions

### ISSUE THREAD

**Issue by AGindinson** [intel/llvm#3906]
In specific cases, the compiler user may want to enable/disable certain or all SPIR-V extensions for the forwards SPIR-V translation. For example, whenever a third-party OpenCL Runtime is to be used under the hood of DPC++ RT, it [can be necessary](https://github.com/intel/llvm/pull/3869#discussion_r648358297) to pass `--spirv-ext=-all` to the translator.

Possible driver solutions:
1. A CLI option to disable all SPIR-V extensions (tailored to the exemplary use-case)
2. A CLI option to pass a custom list of SPIR-V extensions for the translator command (with the same +/-, comma-separated syntax or as a configuration file of a sort)
3. A CLI option to pass any set of additional options to the SPIR-V Translator

**3** is the broadest option, and may also cover some of the future problems.

**Comment by mdtoguchi** [comment]
Fixed here:  https://github.com/intel/llvm/commit/bcf6885cbb9bbb0a56cd861db2c02329744690bc
Introduces `-Xspirv-translator <arg>` to pass any arguments to the translation step.
