### ISSUE TITLE
[Regression] Cannot target nvptx64 and spir64_x86_64 at the same time

### ISSUE THREAD

**Issue by Michoumichmich** [intel/llvm#3948]
**Describe the bug**
When compiling the example from https://github.com/intel/llvm/issues/3947 we cannot target both CPU and GPU at the same time. Targeting the CPU or GPU separately works.

**To Reproduce**
See https://github.com/intel/llvm/issues/3947 and build with `make all`.

We get, with the current version of clang (`clang version 13.0.0 (git@github.com:intel/llvm.git 5e8e5eaa253d0881c5772e7413e5abe7a3471fb8)`):
```
Warning: Expected device not found! Fall back on: SYCL host device
Successfully ran on SYCL host device
Successfully ran on Intel(R) Xeon(R) CPU           X5677  @ 3.47GHz
Successfully ran on SYCL host device
```

We get with a previous one (`clang version 13.0.0 (git@github.com:intel/llvm.git 8b56cbb1b8c688f88303c04435772d8269175e63)`):
```
Successfully ran on NVIDIA GeForce GTX 1660 Ti
Successfully ran on Intel(R) Xeon(R) CPU           X5677  @ 3.47GHz
Successfully ran on SYCL host device
```
The last commit on which it works seems to be 126934871c97d937ebc810d7142525ddf9e2571f and after the merge 8dea105598c1a3f893a0a677694577024633d088 it does not work

**Comment by alexbatashev** [comment]
@mkinsner @AGindinson @steffenlarsen could you please take a look?

**Comment by Michoumichmich** [comment]
So I diffed the compilation logs, when I add `spir64`, the `clang-offload-bundler` is not called - the following step is missing:
```
"/home/.../bin/clang-offload-bundler" -type=o -targets=host-x86_64-unknown-linux-gnu,sycl-nvptx64-nvidia-cuda-sycldevice -inputs=CMakeFiles/demo_context.dir/demo_cuda_context.cpp.o -outputs=/tmp/demo_cuda_context-d32c6a.o,/tmp/demo_cuda_context-ff1ab7.o -unbundle -allow-missing-bundles
```

**Comment by AidanBeltonS** [comment]
The issue appears to be resolved since at least the 20th of July.
Replicated failure for commit: 5e8e5eaa253d0881c5772e7413e5abe7a3471fb8
Tested on tip and a commit in July to narrow down when error was resolved. Appears that some changes between 16th of June and the 20th of July have resolved this error. I am unsure of the precise PR which has resolved this error.

@Michoumichmich could you confirm that the error is not occurring with a recent dpc++ build?
Thanks

```
Passes on 56c9ec4e3ef02b677fa57175aacdad08e443a84b (1st September)
Successfully ran on TITAN RTX
Successfully ran on Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Successfully ran on SYCL host device

Passes on 9bc3bc4e00d5ecad76fce332fe4e4950049d776d (20 Jul)
Successfully ran on TITAN RTX
Successfully ran on Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Successfully ran on SYCL host device

Fails on 5e8e5eaa253d0881c5772e7413e5abe7a3471fb8 (16 Jun)
Something went wrong running on TITAN RTX
Successfully ran on Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Successfully ran on SYCL host device

Passes on 126934871c97d937ebc810d7142525ddf9e2571f (30 Apr)
Successfully ran on TITAN RTX
Successfully ran on Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Successfully ran on SYCL host device
```

**Comment by Michoumichmich** [comment]
Hello @AidanBeltonS, you're right, I missed that it was working again. But still, if I switch the target order I get: 
```
clang++: /home/michel/sycl_workspace/llvm/clang/lib/Driver/ToolChains/Cuda.cpp:682: virtual void clang::driver::toolchains::CudaToolChain::addClangTargetOptions(const llvm::opt::ArgList &, llvm::opt::ArgStringList &, Action::OffloadKind) const: Assertion `!GpuArch.empty() && "Must have an explicit GPU arch."' failed.
```

**Comment by Michoumichmich** [comment]
But if at least one ordering works I'm fine
