### ISSUE TITLE
codecoverage for dpc++

### ISSUE THREAD

**Issue by KimBioInfoStudio** [intel/llvm#3953]
**Describe the bug**
when I try get code coverage of dpc++ code I find a error like
```
clang++ --coverage foo.o -o foo
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /home/gta/20210607/build/linux_prod/compiler/linux/lib/clang/13.0.0/lib/linux/libclang_rt.profile-x86_64.a(GCDAProfiling.c.o): in function `llvm_gcda_start_file':
GCDAProfiling.c:(.text.llvm_gcda_start_file+0x234): undefined reference to `_intel_fast_memset'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /home/gta/20210607/build/linux_prod/compiler/linux/lib/clang/13.0.0/lib/linux/libclang_rt.profile-x86_64.a(InstrProfilingUtil.c.o): in function `lprofApplyPathPrefix':
InstrProfilingUtil.c:(.text.lprofApplyPathPrefix+0x55): undefined reference to `_intel_fast_memcpy'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: InstrProfilingUtil.c:(.text.lprofApplyPathPrefix+0x80): undefined reference to `_intel_fast_memcpy'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. Include code snippet as short as possible
2. Specify the command which should be used to compile the program
3. Specify the comment which should be used to launch the program
4. Indicate what is wrong and what was expected

**Environment (please complete the following information):**

```
echo "int main(){return 0;}" >> foo.cc
clang++ -fprofile-arcs -ftest-coverage foo.cc  -c
clang++ --coverage  foo.o  -o foo
```

- OS: Linux
- Target device and vendor: /
- DPC++ version: 2021.3.0.20210603
- Dependencies version: [e.g. low-level runtime versions (like NEO 20.04)]

**Additional context**

**Comment by KimBioInfoStudio** [comment]
yep, i am  using a closed-source  compiler and  i have source vars.sh before run

**Comment by olegmaslovatintel** [comment]
@KimBioInfoStudio 
For closed-source compiler can you please submit issue at Intel Data Parallel C++ support forum - https://community.intel.com/t5/Intel-oneAPI-Data-Parallel-C/bd-p/oneapi-data-parallel-c?
