### ISSUE TITLE
[L0] SYCL does not destroy all events before destroying ze event pool / context 

### ISSUE THREAD

**Issue by TApplencourt** [intel/llvm#3967]
**Describe the bug**

 SYCL does not destroy all events before destroying ze event pool/context. This is against the Level Zero semantic (https://spec.oneapi.com/level-zero/latest/core/api.html#zeeventpooldestroy) which states  that `the application must destroy all event handles created from the pool before destroying the pool itself.`
 
This breaks profilers among other things. 

**To Reproduce**

Compile:
```
$ cat event_not_destroyed.cpp
#include <CL/sycl.hpp>
using namespace cl;
int main(int argc, char **argv) {
  sycl::queue Q;
  const unsigned n_chunk = 129;
  for (int i = 0 ; i < n_chunk ; i++)
    Q.single_task([=]() { });
  Q.wait();
  return 0;
}
$ dpcpp event_not_destroyed.cpp
```
Now one needs to trace the code with their favorite tracing tool (https://github.com/argonne-lcf/THAPI, https://github.com/intel/pti-gpu/tree/master/tools/ze_tracer).

```
tapplencourt@arcticus15:~/tmp> iprof ./a.out
API calls | 1 Hostnames | 1 Processes | 1 Threads

                                  Name |     Time | Time(%) | Calls |  Average |      Min |      Max |
                    zeEventPoolDestroy |   1.63ms |   5.58% |     1 |   1.63ms |   1.63ms |   1.63ms |
                         zeEventCreate | 301.42us |   1.03% |   129 |   2.34us | 754.00ns | 151.16us |
                     zeEventPoolCreate |  34.11us |   0.12% |     1 |  34.11us |  34.11us |  34.11us |
                      zeContextDestroy |   3.24us |   0.01% |     1 |   3.24us |   3.24us |   3.24us |
                       zeContextCreate |   2.63us |   0.01% |     1 |   2.63us |   2.63us |   2.63us |
                        zeEventDestroy |   2.04us |   0.01% |     5 | 408.20ns | 223.00ns |   1.02us |
```

As one can see, the number of `zeEventCreate` (129) is not equal to the number of events destroyed via `zeEventDestroy`(5).
Please note that the number of `zeEventDestroy` fluctuates from run to run (leading to a possible race condition). The occurrence of this bug depends on the total number of events created (for example it's not triggered in our system when `n_chunk=128`)

**Environment (please complete the following information):**

- OS: Linux
- Intel GPU
- DPC++ version: `Intel(R) oneAPI DPC++/C++ Compiler 2021.2.0 (2021.x.0.20210520)`

**Comment by smaslov-intel** [comment]
A fix is coming in https://github.com/intel/llvm/pull/3985

**Comment by bader** [comment]
https://github.com/intel/llvm/pull/3985 is merged.

**Comment by TApplencourt** [comment]
Amazing! Thanks a lot for the quick fix.
