### ISSUE TITLE
CTS handler_copy fail with CUDA backend

### ISSUE THREAD

**Issue by XunZhangIntel** [intel/llvm#3969]
**Describe the bug**
CTS handler_copy fail with CUDA backend on latest SYCL builds. See logs below:

```sh
PI CUDA ERROR:
    Value:           1
    Name:            CUDA_ERROR_INVALID_VALUE
    Description:     invalid argument
    Function:        commonEnqueueMemBufferCopyRect
    Source Location: sycl/plugins/cuda/pi_cuda.cpp:3524

  . line: 777
  . copy(shared_ptr_class<int>, accessor<int, 2, write, global_buffer>) [strided] failed: Exception thrown during call:
  . sycl exception caught
  . what - OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)
  . line: 967
  . a SYCL exception was caught: OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)
  - fail
```
**To Reproduce**
_Note_: Due to a recent uplift of minimal supported C++ standard, one should modify this line to require C++17.
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and [SYCL-CTS](https://github.com/KhronosGroup/SYCL-CTS)
2. Build CTS tests
```sh
cd SYCL-CTS
mkdir build && cd build
cmake -GNinja  -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -Dopencl_platform_name=nvidia -Dopencl_device_name=opencl_gpu -DCMAKE_BUILD_TYPE=Release -DINTEL_SYCL_FLAGS="-Xsycl-target-backend;--cuda-gpu-arch=sm_50" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda-sycldevice -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja test_handler
```
3. Run Test

```sh
SYCL_DEVICE_FILTER="cuda:gpu:0" ./bin/test_handler -p nvidia -d opencl_gpu  --test handler_copy
```

**Environment (please complete the following information):**
OS version: Ubuntu 18.04.5 LTS (Bionic Beaver)
CUDA version:
```sh
nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
```

**Comment by bader** [comment]
> However, I did hit some problems during the compilation of this. This test has been modified since the time when this issue was opened. Now it uses `sycl::access::target::device` instead of `sycl::access::target::global_buffer` it used before. This enum value was added in SYCL 2020 standard and is not yet supported in DPC++, so I had to replace it back to get this to compile.

@romanovvlad, @vladimirlaz, @s-kanaev, are there plans to add `sycl::access::target::device` support to fix SYCL-CTS build?

**Comment by romanovvlad** [comment]
@cperkinsintel  is looking into this.s

**Comment by AerialMantis** [comment]
We believe this issue to be resolved, so are closing it, @XunZhangIntel if you experience this issue again please comment and we can re-open the ticket.
