### ISSUE TITLE
[SYCL] Support building on ARM

### ISSUE THREAD

**Issue by kpet** [intel/llvm#4]
There are quite a few x86 assumptions that prevent building for ARM (e.g. `cpuid`, `get_native_vector_width`, etc)

**Comment by bader** [comment]
I think we should move these to some platform specific layer and add ARM specific implementation.
There shouldn't be much places we need to change.

**Comment by keryell** [comment]
@agozillon made some progress on compilation for ARM recently in https://github.com/triSYCL/sycl/pull/47
If someone from ARM can contribute with a more definitive solution...

**Comment by kpet** [comment]
Thank you :)
