### ISSUE TITLE
[Driver] Enhance usability by allowing more simplified known targets

### ISSUE THREAD

**Issue by mdtoguchi** [intel/llvm#4010]
We are adding short aliases for commonly used triples that are passed via the `-fsycl-targets` option here: https://github.com/intel/llvm/pull/3984

This only covers the `spir64` arch targets for device and AOT.  We should enhance this by providing additional known documented aliases that can be used for other targets as well.

From @AGindinson : Could/should we extend the aliasing logic for the non-SPIR targets?
I realize that in general, after sycldevice removal the flow will already be quite convenient for users of these targets, e.g. -fsycl-targets=nvptx64-nvidia-nvcl. But maybe a documented default of Vendor/OS would make CLI even better.

**Comment by AGindinson** [comment]
Looks like this one has been resolved a while ago.
