### ISSUE TITLE
Windows on-device tests - 'true': command not found

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#4152]
**Describe the bug**
Running `check-sycl-*-on-device` on Windows causes the majority of on-device tests to fail with `'true': command not found`.

**To Reproduce**
Follow the instructions for building on Windows as described in the [Getting Started guide](https://intel.github.io/llvm-docs/GetStartedGuide.html). Run any `check-sycl-*-on-device`.

**Environment:**

- OS: Microsoft Windows 11 Pro - 10.0.22000 Build 22000
- DPC++ version: b06a7f69443006da03a4209eea1ea9e8871d4621

**Additional context**
This was originally produced on a configuration that requires some patches that are not up yet. These patches should not have any effect on this part of the testing however and this should be reproducible on any `check-sycl-*-on-device` testing run on Windows.

**Comment by steffenlarsen** [comment]
Pinging @bader  and @alexbatashev

**Comment by alexbatashev** [comment]
@steffenlarsen could you please try the same in git bash? `true`, as well as some other utilities, used in our tests, are unix-based, so using git bash should help.

**Comment by bader** [comment]
@alexbatashev, how do you configure MSVC compiler environment in git bash?

**Comment by alexbatashev** [comment]
@bader I see two options:
a) Configure it in `cmd.exe` and then copy environment variables to git bash console.
b) Configure it in `cmd.exe` and then run `bash.exe` in the same console. The environment should be inherited by bash.

**Comment by steffenlarsen** [comment]
> 
> 
> @bader I see two options:
> a) Configure it in `cmd.exe` and then copy environment variables to git bash console.
> b) Configure it in `cmd.exe` and then run `bash.exe` in the same console. The environment should be inherited by bash.

I am trying to do b, but bash doesn't seem to carry the environment correctly. I have also tried building it in bash started from a cmd with the right environment set, but it insists on using gcc instead of MSVC. Do you have some more detailed instructions?

**Comment by bader** [comment]
I think the right solution is to remove usages of Linux tools from the tests executed on Windows platform.

**Comment by AlexeySachkov** [comment]
`-on-device` tests don't exist anymore, closing this as outdated.
