### ISSUE TITLE
[SYCL][RT][Documentation]

### ISSUE THREAD

**Issue by jbrodman** [intel/llvm#4159]
**Describe the bug**
The comments in the headers about USM memcpy() operations is incorrect.

**Additional context**
For example:

  /// Copies data from one memory region to another, both pointed by
  /// USM pointers.
  /// No operations is done if \param Count is zero. An exception is thrown
  /// if either \param Dest or \param Src is nullptr. The behavior is undefined
  /// if any of the pointer parameters is invalid.
  ///
  /// \param Dest is a USM pointer to the destination memory.
  /// \param Src is a USM pointer to the source memory.
  /// \param Count is a number of bytes to copy.
  /// \return an event representing copy operation.
  event memcpy(void *Dest, const void *Src, size_t Count);

"both pointed by USM pointers" is incorrect and more restrictive than SYCL requires.  The main use case of memcpy is copying to/from malloc'd memory and malloc_device() allocations.  That would be impossible the comment's restrictions were true.  memcpy() should work if 0, 1, or both of the pointers are USM pointers.

**Comment by colleeneb** [comment]
Any updates on fixing this? Not really urgent, but it would help avoid confusion. The current SYCL spec's description of `memcpy` is:

> Copies numBytes of data from the pointer src to the pointer dest. Both dest and src may be either host or USM pointers. For more detail on USM, please see [Section 4.8](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:usm).

(under https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#subsec:explicitmemory)

Thanks!
