### ISSUE TITLE
Bug in sycl::queue::copy

### ISSUE THREAD

**Issue by arkantos493** [intel/llvm#4197]
**Describe the bug**
Divergent function signature of the `sycl::queue::copy` function compared to the SYCL standard.
In the SYCL standard the `sycl::queue:copy` function has the signature:
```cpp
template <typename T>
event copy(T* dest, const T* src, size_t count);
```
However, in the file https://github.com/intel/llvm/blob/sycl/sycl/include/CL/sycl/queue.hpp the signature is:
```cpp
template <typename T> 
event copy(const T *Src, T *Dest, size_t Count);
```
i.e. the source and destination pointers are reversed.

**To Reproduce**

This leads for example to garbage output or to a compiler error (`candidate template ignored: deduced conflicting types for parameter 'T' ('int' vs. 'const int')`) when compiling the USM example from the [SYCL](https://www.khronos.org/registry/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf) standard document on page 228:
```cpp
#include <iostream>
#include <sycl/sycl.hpp>
using namespace sycl; // (optional) avoids need for "sycl::" before SYCL names

int main() {
  // Create a default queue to enqueue work to the default device
  queue myQueue;

  // Allocate shared memory bound to the device and context associated to the queue
  int *data = sycl::malloc_device<int>(1024, myQueue);

  myQueue.parallel_for(1024, [=](id<1> idx) {
    // Initialize each buffer element with its own rank number starting at 0
    data[idx] = idx;
  }); // End of the kernel function

  // Explicitly wait for kernel execution since there is no accessor involved
  myQueue.wait();

  // Create an array to receive the device content
  int hostData[1024];
  // Receive the content from the device

  // myQueue.copy(hostData, data, 1024); // results in garbage data 
  myQueue.copy(hostData, const_cast<const int*>(data), 1024); // results in a compile time error

  // Wait for the copy to complete
  myQueue.wait();

  // Print result
  for (int i = 0; i < 1024; i++)
    std::cout <<"hostData["<< i << "] = " << hostData[i] << std::endl;

  return 0;
}
``` 
Compiled with:
```
clang++ -sycl-std=2020 -std=c++17 -fsycl main.cpp
```
using a fresh DPC++ installation (build yesterday using the instructions in https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain):
```
clang version 13.0.0 (git@github.com:intel/llvm.git c121bbb2750dd62fea153d8034dafd146db0f22c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ~/Programs/dpcpp/llvm/build/bin
```

**Comment by bader** [comment]
I think your spec text is 5+ days old :).
Here is the spec change https://github.com/KhronosGroup/SYCL-Docs/commit/d1c96f6b2d3e8ec5fa9685d23178df6087142d91, which resolves this issue.

**Comment by arkantos493** [comment]
Ah ok. I only looked at the standard PDF uploaded on the official Khronos homepage.

However, what is the rationale behind this change? 
`sycl::queue::memcpy` still has the dest -> src order. Why change `sycl::queue::copy` to have a src -> dest order?
That's really confusing and dangerous imho.

**Comment by bader** [comment]
> Ah ok. I only looked at the standard PDF uploaded on the official Khronos homepage.
> 
> However, what is the rationale behind this change?
> `sycl::queue::memcpy` still has the dest -> src order. Why change `sycl::queue::copy` to have a src -> dest order?
> That's really confusing and dangerous imho.

From https://github.com/KhronosGroup/SYCL-Docs/pull/168 description:

> We noticed that the USM copy() functions had a parameter order of
> (dest, src), which is opposite of the copy() functions for
> accessors. 

Tagging @gmlueck for awareness.

**Comment by gmlueck** [comment]
Just adding some more information on the rationale ... we thought it was more important for all of the functions named "copy" to take the same parameter order of `(src, dest)`, so we changed these USM functions to match the other functions named "copy".

We agree that it is unfortunate that the functions named "memcpy" take the opposite parameter order.  However, this inconsistency exists in standard C++ as well, where the first parameter of `std::copy()` is the source iterator (not the destination iterator).

BTW, the example you quote above appears to have been modified from what we have in the spec.  In the spec, the example uses `myQyueue.memcpy()`, but the example quoted above uses `myQueue.copy()` instead.
