### ISSUE TITLE
[SYCL] Improve hierarchical parallelism implementation

### ISSUE THREAD

**Issue by kbobrovs** [intel/llvm#421]
Current implementation is also of a limited functionality. The main restriction is that ```group::parallel_for_work_item``` and ```group::wait_for``` must be syntactically immediately nested within the parallel_for_work_group. E.g. the following is not supported yet:
```
void foo(group &g) {
  g.parallel_for_work_item(...);
}

parallel_for_work_group(...,[=](group g) {
  foo(g);
});
```

Main directions for improvement:
- call graph-based analysis which identifies functions invoked from work group scope
- change the work-group scope code generation approach from
   "execute work group scope code under ```if (local_id() == 0)``` except ```parallel_for_work_item```,
     wait_for``` calls and control flow"
  to
   "execute work group scope code normally w/o any guards except code with side effects like stores to
    non-private memory"

In the presence of generic pointers, some stores can be made through a generic pointer, and it can't be (in general case) known in compile time whether it has side-effects or not. So for each store instruction through a generic pointer in a work group scope the following code needs to be generated:

```
*ptr = val;
```
=>
```
bool store_has_no_side_effects = __is_private_pointer(ptr);
if (store_has_no_side_effects || local_id() == 0) {
  *ptr = val;
}
if (!store_has_no_side_effects)
  barrier();
```
where  ```__is_private_pointer``` is a new built-in which tells whether the argument is a private pointer or not, and must be supported by the back-ends. After address space inference pass the ```store_has_no_side_effects``` may become a constant for a better performance.
There can be back-ends which don't support generic pointers, for such back-ends front-end should probably not generate generic pointers (and revert to the inference rules prescribed by SYCL spec?).

**Comment by asavonic** [comment]
> So for each store instruction through a generic pointer in a work group scope the following code needs to be generated:
> 
> ```
> *ptr = val;
> ```
> 
> =>
> 
> ```
> bool store_has_no_side_effects = __is_private_pointer(ptr);
> if (store_has_no_side_effects || local_id() == 0) {
>   *ptr = val;
> }
> if (!store_has_no_side_effects)
>   barrier();
> ```

Barriers are pretty expensive on CPU. Do you really want to generate this code for *every* store?

**Comment by kbobrovs** [comment]
> Barriers are pretty expensive on CPU. Do you really want to generate this code for every store?

I don't. Only for stores to global or local memory. Even for those optimizations are possible and the barrier avoided. I'm illustrating the basic idea above.
