### ISSUE TITLE
[SYCL] [CUDA]  Unresolved extern function '__sqrtf_finite' when compiling for CUDA BE with -fast-math

### ISSUE THREAD

**Issue by kkasimov** [intel/llvm#4222]
**Describe the bug**
When compiling the code snippet below with -ffast-math option, user is getting ptxas fatal   : Unresolved extern function '__sqrtf_finite' error.

**To Reproduce**
Please describe the steps to reproduce the behavior:

Here is the code snippet (my file is called repro.cpp):
```
#include <CL/sycl.hpp>
#include <cmath>
#include <complex>

typedef std::complex<double> cxtype;

SYCL_EXTERNAL
void ixzxxx(cxtype fi[1])
{
  const double& pvec0 = 1.23456789;
  const double& pvec3 = 3.98765421;

  double sqp0p3 = sqrtf(pvec0 + pvec3);
  cxtype chi0 = cxtype (sqp0p3, 0.0);

  if (1)
  {
    fi[0] = chi0;
  }

  return;
}

int main (void) {
        return 0;
}
```

Fails with -ffast-math:
```
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice -ffast-math repro.cpp
clang-13: warning: Unknown CUDA version. cuda.h: CUDA_VERSION=11030. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
ptxas fatal   : Unresolved extern function '__sqrtf_finite'
clang-13: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 13.0.0 (https://github.com/intel/llvm d1556e41db47010ef795ad851439d5d7dbbe4ee5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /scratch/DOWNLOAD/Tools_Beta/oneAPI/Codeplay4Nvidia/build-sycl-210716.000001-210715.132919_d1556e41db47_release/bin
clang-13: note: diagnostic msg: Error generating preprocessed source(s).
```

Compilation succeeds when -ffast-math is not specified and when -fsycl-targets is not specified:
```
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice repro.cpp
clang-13: warning: Unknown CUDA version. cuda.h: CUDA_VERSION=11030. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
$ clang++ -fsycl -ffast-math repro.cpp
```

Expected behavior: successful compilation.

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: `$ clang++ --version
clang version 13.0.0 (https://github.com/intel/llvm d1556e41db47010ef795ad851439d5d7dbbe4ee5)
`

**Comment by zjin-lcf** [comment]
May I call sycl::sqrt  ?  Thanks.

**Comment by t4c1** [comment]
Calling functions from `std::` namespace in device code is not supported by SYCL. While DPC++ adds an extension for that, it is not yet implemented for the CUDA backend. So weird behavior like something not working with certain compiler flags is possible.

In the meantime you can use functions from `sycl::` namespace as suggested above. These should work.
