### ISSUE TITLE
potential incorrect accessor offset behaviour in get_access 

### ISSUE THREAD

**Issue by FMarno** [intel/llvm#4238]
Hello,
I think the way DPC++ handles offsets in get_access is at odds with the specification.
Looking at page 119 here https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf and 94 here https://www.khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf it says 

> Only the values starting from the given offset and up to the given range are guaranteed to be updated.

Whereas the DPC++ spec (https://docs.oneapi.io/versions/latest/dpcpp/iface/buffer.html#buffer-get-access) suggests that a sub buffer will be created.
This leads to offsets giving different result using DPC++ and ComputeCpp, and I personally think the ComputeCpp implementation is closer to the SYCL specification.

Here is an example program
```cpp
#include <CL/sycl.hpp>
#include <iostream>

int main(){
	sycl::default_selector selector;
	sycl::queue q{selector};

	sycl::buffer<int, 1> buff(sycl::range{5});

	// init to indexes
	q.submit([&](sycl::handler& h){
		auto acc = buff.get_access<sycl::access::mode::discard_write>(h);
		h.parallel_for(sycl::range{5}, [=](sycl::id<1> it){
			acc[it] = it[0];
		});
	});

	// update values
	q.submit([&](sycl::handler& h){
		auto acc = buff.get_access<sycl::access::mode::write>(h, sycl::range{4}, sycl::id{1});
		h.parallel_for(sycl::range{3}, [=](sycl::id<1> it){
			acc[1+it] += 1;
		});
	});

	// print values
	std::cout << "expected output: 0 2 3 4 4\n";

	auto host_acc = buff.get_access<sycl::access::mode::read>();
	std::cout << "actual output  : ";
	for (size_t i = 0; i < 5; ++i){
		std::cout << host_acc[i] << ' ';
	}
	std::cout << '\n';
}
```

which gives the output 
```
expected output: 0 2 3 4 4
actual output  : 0 1 3 4 5
```

Kind Regards,
Finlay

**Comment by zjin-lcf** [comment]
// update values
	q.submit([&](sycl::handler& h){
		auto acc = buff.get_access<sycl::access::mode::write>(h, sycl::range{4}, sycl::id{1});
		h.parallel_for(sycl::range{3}, [=](sycl::id<1> it){   // the values of it are 1, 2, 3, 4
			acc[1+it] += 1;  // the values of it+1 are 2, 3, 4 
		});
	});

**Comment by FMarno** [comment]
Why would `it` have those values? I have not specified an offset in the parallel_for call.

**Comment by zjin-lcf** [comment]
Because of the offset sycl::id{1}. Do you see different results of the program with dpc++ and computecpp ?

**Comment by FMarno** [comment]
That offset is for the acccessor, I don't believe the value of `it` is dependent on that.

Compiled with ComputeCpp i got:
```
expected output: 0 2 3 4 4
actual output  : 0 2 3 4 4
```

**Comment by zjin-lcf** [comment]
It is good to know the difference. What is your expected output for the program below ?   

// update values
q.submit([&](sycl::handler& h){
	auto acc = buff.get_access<sycl::access::mode::write>(h, sycl::range{4}, sycl::id{1});
	h.parallel_for(sycl::range{3}, [=](sycl::id<1> it){ 
		acc[it] += 1;  
	});
})

**Comment by FMarno** [comment]
I swapped the second submit with the one you posted there and recompiled to get

oneAPI output:
```
expected output: 0 2 3 4 4
actual output  : 0 2 3 4 4
```

ComputeCpp output:
```
expected output: 0 2 3 4 4
actual output  : 1 2 3 3 4
```

of course I would now consider the "expected output" row to be wrong since we have changed the code

**Comment by zjin-lcf** [comment]
I think vendors would look at our conversation and give a definite answer.  Thanks.

**Comment by bader** [comment]
DPC++ follows https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html spec and sometimes incorporates fixes, which have been landed to https://github.com/KhronosGroup/SYCL-Docs, but not published yet.

Here is the current wording for `get_access` from https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html

> Returns a valid accessor to the buffer with the specified access mode and target in the command group buffer. **The accessor is a ranged accessor, where the range starts at the given offset from the beginning of the buffer.** The value of target can be target::device or target::constant_buffer.Throws an exception with the errc::invalid error code if the sum of accessRange and accessOffset exceeds the range of the buffer in any dimension.

According to my interpretation DPC++ implementation is aligned with this wording.

Tagging "vendors": @AerialMantis, @Ruyk, @gmlueck, @mkinsner, @keryell, @illuhad.

**Comment by gmlueck** [comment]
I believe the DPC++ behavior you posted is consistent with the published SYCL 2020 specification.  As @bader posted above, you are creating a "ranged accessor", which starts at element 1 (i.e. the second element) of your buffer.  Therefore, when you index into this accessor with `acc[0]`, you are really accessing element 1 of the buffer.  See this section of the SYCL 2020 specification for a description of how ranged accessors work:

https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:accessors.ranged

In particular, this paragraph is relevant to your case:

> Most of the accessor member functions which provide a reference to the underlying buffer elements are affected by a ranged accessor’s offset and range. For example, calling `operator[](0)` on a one-dimensional ranged accessor returns a reference to the element at the position specified by the accessor’s offset, which is not necessarily the first element in the buffer. In addition, the accessor’s iterator functions iterate only over the elements that are within the sub-range.

**Comment by FMarno** [comment]
I guess I was looking at the wrong specification. Thanks for your help!
