### ISSUE TITLE
Host execution not following event depend_on specification

### ISSUE THREAD

**Issue by swoodeng** [intel/llvm#4273]
The example https://github.com/argonne-lcf/sycltrain/blob/master/9_sycl_of_hell/8_event.cpp
Runs correctly on a GPU and out of order on the Host.

**Comment by AlexeySachkov** [comment]
Hi @swoodeng,

Unfortunately, I'm going to close this as won't fix, because `host` device is not mandatory to have anymore with SYCL 2020 specification and we plan to remove it completely.
