### ISSUE TITLE
__builtin_sycl_unique_stable_name & kernel_device_specific info

### ISSUE THREAD

**Issue by joeatodd** [intel/llvm#4277]
**Describe the bug**

I have been attempting to compile kernel functors prior to kernel launch in order to extract `kernel_device_specific` information to inform work group size (see context below). However, when working with either an anonymous lambda directly, or a functor which wraps an anonymous lambda, this fails with the following error message:

```
In file included from mwe.cpp:1:
In file included from /soft/llvm/bin/../include/sycl/CL/sycl.hpp:17:
In file included from /soft/llvm/bin/../include/sycl/CL/sycl/ONEAPI/reduction.hpp:16:
/soft/llvm/bin/../include/sycl/CL/sycl/handler.hpp:884:3: error: kernel instantiation changes the result of an evaluated '__builtin_sycl_unique_stable_name'
  kernel_single_task(const KernelType &KernelFunc) {
  ^
/soft/llvm/bin/../include/sycl/CL/sycl/handler.hpp:997:7: note: in instantiation of function template specialization 'sycl::handler::kernel_single_task<LambdaWrapper<(lambda at mwe.cpp:20:20)>, LambdaWrapper<(lambda at mwe.cpp:20:20)>>' requested here
      kernel_single_task<KernelName>(KernelFunc);
      ^
/soft/llvm/bin/../include/sycl/CL/sycl/handler.hpp:1197:5: note: in instantiation of function template specialization 'sycl::handler::kernel_single_task_wrapper<LambdaWrapper<(lambda at mwe.cpp:20:20)>, LambdaWrapper<(lambda at mwe.cpp:20:20)>>' requested here
    kernel_single_task_wrapper<NameT>(KernelFunc);
    ^
mwe.cpp:30:9: note: in instantiation of function template specialization 'sycl::handler::single_task<sycl::detail::auto_name, LambdaWrapper<(lambda at mwe.cpp:20:20)>>' requested here
    cgh.single_task(wrapper);
        ^
/soft/llvm/bin/../include/sycl/CL/sycl/detail/kernel_desc.hpp:108:29: note: '__builtin_sycl_unique_stable_name' evaluated here
  static constexpr auto n = __builtin_sycl_unique_stable_name(T);
```

Essentially, the generation of the unique stable name differs between the pre-compilation & the compilation at launch.

**To Reproduce**

Here is a MWE with a lambda wrapper:

```c++
#include <CL/sycl.hpp>

using namespace cl::sycl;

template <typename Functor> class LambdaWrapper {
public:
  void operator()() const { my_functor(); }

  LambdaWrapper(Functor f) : my_functor(f){};

private:
  Functor my_functor;
};

int main() {
  queue q{gpu_selector()};
  program p(q.get_context());

  // Define a do-nothing lambda
  auto my_lambda = [=]() {};

  // Wrap the lambda in a templated functor
  LambdaWrapper<decltype(my_lambda)> wrapper(my_lambda);

  // Build the kernel (e.g. in order to query device-specific kernel info)
  p.build_with_kernel_type<decltype(wrapper)>();

  // Single task to call the lambda via the wrapper
  auto e = q.submit([&](handler &cgh) {
    cgh.single_task(wrapper);
  });

  return 0;
}

```

and a simpler case without the wrapper:

```c++
#include <CL/sycl.hpp>

using namespace cl::sycl;

int main() {
  queue q{gpu_selector()};
  program p(q.get_context());

  // Define a do-nothing lambda
  auto my_lambda = [=](){};

  // Build the kernel (e.g. in order to query device-specific kernel info)
  p.build_with_kernel_type<decltype(my_lambda)>();

  // Single task to call the lambda via the wrapper
  auto e = q.submit([&](handler &cgh) {
    cgh.single_task(my_lambda);
  });

  return 0;
}
```

compiled with:

```
clang++ -fsycl -fsycl-unnamed-lambda mwe.cpp
```

Both examples fail to compile with the error described above.

**Context**

I've been working on Kokkos & attempting to extract device-specific kernel info. For example, [here](https://github.com/Ruyk/kokkos/blob/8d17bed3c1213ec5681c25acb8279f7e14b0a45a/core/src/SYCL/Kokkos_SYCL_Parallel_Range.hpp#L59-L80) I wrap the application's lambda in a functor for conditional execution, and [here](https://github.com/Ruyk/kokkos/blob/8d17bed3c1213ec5681c25acb8279f7e14b0a45a/core/src/SYCL/Kokkos_SYCL_Parallel_Range.hpp#L106-L126) I first attempt to build the kernel & query it, then launch it with parallel_for. This produces the error message describe above & compilation fails.

The functor wrapping isn't central to the issue here I don't think. If I were to attempt to define the lambda outside the call to parallel_for, build it, then launch it, the same error would occur, as demonstrated by the 2nd MWE above.

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- Target device and vendor: Nvidia GPU
- DPC++ version:
  clang version 13.0.0 (https://github.com/intel/llvm.git ce7177d25a390e60bd27fef2170742972f67ae4e)
  Target: x86_64-unknown-linux-gnu
  Thread model: posix

**Comment by erichkeane** [comment]
What does `build_with_kernel_type` do?  If it is what is causing the `__builtin_sycl_unique_stable_name` evaluation, it likely needs to ALSO mark this as a device type.  @romanovvlad likely is the one who needs to fix this in the library.

**Comment by joeatodd** [comment]
> What does `build_with_kernel_type` do? If it is what is causing the `__builtin_sycl_unique_stable_name` evaluation, it likely needs to ALSO mark this as a device type. @romanovvlad likely is the one who needs to fix this in the library.

It compiles the kernel for the default device, AFAIK. The motivation is to get device-specific kernel info before kernel launch. As you suggest, it is indeed what's causing the evaluation of `__builtin_sycl_unique_stable_name`.

**Comment by bader** [comment]
Let's simplify the question:
@erichkeane, `parallel_for<decltype(my_lambda)>();` - is this allowed? I thought types which can't be forward-declared by the compiler are not allowed as a kernel name type. Am I wrong?
If so, it's exactly the same problem we discussed last week with oneDPL library team.

**Comment by erichkeane** [comment]
> 
> 
> Let's simplify the question:
> @erichkeane, `parallel_for<decltype(my_lambda)>();` - is this allowed? I thought types which can't be forward-declared by the compiler are not allowed as a kernel name type. Am I wrong?
> If so, it's exactly the same problem we discussed last week with oneDPL library team.

That, as written, isn't legal, no.

**Comment by bader** [comment]
> > Let's simplify the question:
> > @erichkeane, `parallel_for<decltype(my_lambda)>();` - is this allowed? I thought types which can't be forward-declared by the compiler are not allowed as a kernel name type. Am I wrong?
> > If so, it's exactly the same problem we discussed last week with oneDPL library team.
> 
> That, as written, isn't legal, no.

The reproducer has the same problem.
`parallel_for` implicitly calls `build_with_kernel_type` to build the kernel if it's not built already explicitly with `build_with_kernel_type`.

Another issue is that kernel invocation function must be specialized with the kernel name type as well.
```c++
  // Build the kernel (e.g. in order to query device-specific kernel info)
  p.build_with_kernel_type<decltype(my_lambda)>();

  // Single task to call the lambda via the wrapper
  auto e = q.submit([&](handler &cgh) {
    cgh.single_task(my_lambda);  // <<<<<< HERE IT SHOULD BE cgh.single_task<decltype(my_lambda)>(my_lambda);
  });
```
I'm not sure if CTAD is enabled/helps to bind kernel build and invoke APIs, so better to do this explicitly.

@joeatodd, is it possible for Kokkos to create a kernel name type w/o using lambda types?

**Comment by joeatodd** [comment]
If I modify my mwe to provide a kernel name, it works fine:

```c++
#include <CL/sycl.hpp>

using namespace cl::sycl;

class some_name;

int main() {
  queue q{gpu_selector()};
  program p(q.get_context());

  // Define a do-nothing lambda
  auto my_lambda = [=](){};

  // // Build the kernel (e.g. in order to query device-specific kernel info)
  p.build_with_kernel_type<some_name>();

  // Single task to call the lambda via the wrapper
  auto e = q.submit([&](handler &cgh) {
    cgh.single_task<some_name>(my_lambda);
  });

  return 0;
}
```

However, I'm struggling to see how this could be implemented in something like Kokkos where Kokkos' own functor/lambda wraps many different application defined lambdas. If I understand what's going on, this would probably work so long as the Kokkos' parallel_for was only ever used once, but as soon as you use it to wrap multiple kernels, surely they each need unique names?

I'm quite new to this, so if I'm missing something obvious please do let me know.

**Comment by erichkeane** [comment]
That IS in fact a weakness to providing names to a kernel, wrapping them becomes difficult, particularly because the names need to be dependent on ALL your template parameters, but can't be dependent on a lambda.  If you DON'T have any lambdas as a template parameter, it is easy enough to have each of your parallel-fors wrap the 'user provided' name in some way.

I think the 'correct' answer for you is probably going to be something like OneDPL is doing (@rarutyun might be able to give tips!), where you use the 'unnamed kernel' feature.  

The 'gotcha' here is that your `build_with_kernel_type` likely needs to do some level of marking of the kernel for the unnamed-kernels.  We provide a builtin (`__builtin_sycl_mark_kernel_name`) that can be used to ensure that an unnamed kernel functor is 'correct';  In this case, you'd need your `build_with_kernel_type` and `single_task` invocation to work on the same type, and have the `build_with_kernel_type` use the builtin (or something that our library provides? I'm unsure what exists) before looking into the KernelInfo type.

**Comment by joeatodd** [comment]
This seems to be fixed on tip :+1: thanks a lot for your help!
