### ISSUE TITLE
Update CudaArch structs and functions in clang to something more generic

### ISSUE THREAD

**Issue by npmiller** [intel/llvm#4279]
The `CudaArch` struct and functions include AMD GPU values in:

* https://github.com/intel/llvm/blob/sycl/clang/lib/Basic/Cuda.cpp#L73

It would be good to revisit this and change it to something more generic like maybe `GPUArch` or something like that as the `Cuda` tag doesn't really reflect what it is anymore.

This was discussed on the following PR:

* https://github.com/intel/llvm/pull/4239#discussion_r684087808

**Comment by jchlanda** [comment]
Upstream PR: https://github.com/llvm/llvm-project/pull/97028
