### ISSUE TITLE
[SYCL][ROCM] amdgcn flag shows lld errors

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#4468]
Because of the message "clang-14: warning: argument 'amdgcn-amd-amdhsa-sycldevice' is deprecated, use 'amdgcn' instead [-Wdeprecated]", 

changing the argument shows the following error for a few SYCL programs. Could you reproduce the error using any SYCL program ?

clang++  -fsycl-unnamed-lambda -fsycl **-fsycl-targets=amdgcn** -Xsycl-target-backend --offload-arch=gfx9xx -O3 main.o -o main
lld: error: <unknown>:0:0: in function _ZTSZZ4mainENKUlRN2cl4sycl7handlerEE_clES2_E1k void (i32 addrspace(1)*, i64, i64, i64): unsupported hsa intrinsic without hsa target

lld: error: lto.tmp:(function typeinfo name for cl::sycl::detail::AssertInfoCopier: .text._ZTSN2cl4sycl6detail16AssertInfoCopierE+0x60): internal linker error: cannot read addend for relocation R_AMDGPU_GOTPCREL32_LO
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.

lld: error: lto.tmp:(function typeinfo name for cl::sycl::detail::AssertInfoCopier: .text._ZTSN2cl4sycl6detail16AssertInfoCopierE+0x68): internal linker error: cannot read addend for relocation R_AMDGPU_GOTPCREL32_HI
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.

lld: error: undefined symbol: SCRATCH_RSRC_DWORD0
>>> referenced by lto.tmp:(typeinfo name for cl::sycl::detail::AssertInfoCopier)

lld: error: undefined symbol: SCRATCH_RSRC_DWORD1
>>> referenced by lto.tmp:(typeinfo name for cl::sycl::detail::AssertInfoCopier)
llvm-foreach:

llvm-foreach:
clang-14: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
m

**Comment by npmiller** [comment]
This is most likely due to dropping `-sycldevice` in #3929, could you try with `-fsycl-targets=amdgcn-amd-amdhsa`? Maybe it's just the suggestion in the warning not being correct.

**Comment by zjin-lcf** [comment]
It is fine with or without "-sycldevice". Thanks.

**Comment by bader** [comment]
> This is most likely due to dropping `-sycldevice` in #3929, could you try with `-fsycl-targets=amdgcn-amd-amdhsa`? Maybe it's just the suggestion in the warning not being correct.

Right. The warning message is misleading. It applies to the triples with SPIR target only. I'll try to fix the warning.
