### ISSUE TITLE
[SYCL][ROCM] lld: error: undefined hidden symbol: __spirv_AtomicFAddEXT(float AS1*, __spv::Scope::Flag, __spv::MemorySemanticsMask::Flag, float) >

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#4471]
fast atomic operations are helpful on an AMD GPU.  

Thanks

**Comment by skambapugithub** [comment]
Hi @zjin-lcf,
Did you eventually fix this error?

Thanks

**Comment by zjin-lcf** [comment]
I am not certain how the error can be fixed entirely. Thanks.

**Comment by hdelan** [comment]
Adding some basic atomics for HIP here https://github.com/intel/llvm/pull/8003 . More to be rolled out soon

**Comment by hdelan** [comment]
This should be fixed now @zjin-lcf . Can I close the issue?

**Comment by zjin-lcf** [comment]
I closed it. Thanks.
