### ISSUE TITLE
Broken links in doxygen-generated documentation.

### ISSUE THREAD

**Issue by bader** [intel/llvm#4474]
If you go https://intel.github.io/llvm-docs/GetStartedGuide.html#run-simple-dpc-application section and click the "User Manual" link, you will get 404. It looks like the reason is that the link has wrong document extension: `md` instead of `html`.

The same is true for "Device code formats" link.

**Comment by KornevNikita** [comment]
Looks like it was fixed, as I don't see any 404. Please re-open if needed.
