### ISSUE TITLE
Make sure the `clang-format` version from infrastructure check during the PR has the version that aligned with the version from this repo

### ISSUE THREAD

**Issue by capatober** [intel/llvm#4495]
`clang-format` check differs from `clang-format` from the repo. Seems it should be improved on infrastructure side.

_Originally posted by @capatober in https://github.com/intel/llvm/issues/4439#issuecomment-910093722_

**Comment by bader** [comment]
@capatober, it's by design. Currently this check runs in a few minutes. We don't use the "clang-format from the repo" because takes a lot of time to build clang-format tool from sources using GitHub Actions resources and difference you get from it is minimal.
Do you have any problems with using clang-format installed on your system?

**Comment by capatober** [comment]
Yes. Firstly it's not mentioned in the instruction which `clang-format` versions should be used. I used `clang-format-6.0`, but it fails during on working on sources. I tried to install the newest version of `clsng-format` on the system, but paths are not recognized by the system. The only way that works is to use clang-format that built from the repo, but result of applying to sources is different to what infrastructure check shows. It's also not specified which `clang-format` version is used for PRs

**Comment by bader** [comment]
> paths are not recognized by the system.

What do you mean by that?

**Comment by capatober** [comment]
It means that `clang-format` is not found, but it's installed

**Comment by bader** [comment]
Did you install it into custom directory? Why is clang-format not found?

**Comment by capatober** [comment]
It's installed in the default directory. I didn't investigate the reason since I didn't know which `clang-format` version should have been used. Since version is not mentioned in the instruction I thought that any version can be used, but it's not true

**Comment by bader** [comment]
You probably need to update default version with `update-alternatives` tool.

Here is GitHub actions workflow, which you can repeat to get the same results: https://github.com/intel/llvm/blob/sycl/.github/workflows/clang-format.yml.

NOTE: GitHub actions job attaches output of clang-format tool to the job artifacts, so you can just download the patch and apply if you don't want to install clang-format locally.

**Comment by capatober** [comment]
Am I right that the recommended way for contributors is following?
1) try to run any `clang-format` version
2) if 1) doesn't work, call `update-alternatives`
3) if 2) doesn't work, try to repeat actions from `.yml` file mentioned above
4) if 3) doesn't work, download output and apply patch

Could you please update the instruction for contributors with correct steps?

However, in my opinion, step 4) looks inconvenient and time-consuming if we do it per each commit.
If my understanding is correct, the process should definitely be improved.

**Comment by bader** [comment]
I've updated instructions in #4499.

**Comment by bader** [comment]
> Am I right that the recommended way for contributors is following?
> 
> 1. try to run any `clang-format` version
> 2. if 1) doesn't work, call `update-alternatives`
> 3. if 2) doesn't work, try to repeat actions from `.yml` file mentioned above
> 4. if 3) doesn't work, download output and apply patch

I would recommend install `clang-format` locally if you plan to do multiple contributions. One time contributors can just apply the patch prepared by GitHub actions job.
All the hints I was giving you are about installing the right version of clang-format and all these knowledge is basic Linux administration, which easy to find by searching the Internet. What is useful to know is what version of clang-format tool GitHub Actions check is using.

**Comment by capatober** [comment]
I see. Thanks. I think mentioning in the instruction is enough for one-time contributors.
By the way, you mentioned Linux administration. What about advises for Windows?

**Comment by bader** [comment]
> What about advises for Windows?

I expect clang-format to produce the same results on any platform, so the advise is the same - install clang-format 10 locally if you want to format the patch before opening a pull request.
I personally not able to provide any BKMs as my primary development platform is Linux.
