### ISSUE TITLE
Default context has multiple devices which is not supported by CUDA and HIP plugins

### ISSUE THREAD

**Issue by npmiller** [intel/llvm#4541]
This was introduced with:

* https://github.com/intel/llvm/pull/2805

The issue is that the default context it creates contains multiple devices which is not supported by the CUDA or HIP plugins, which means that on machines with multiple NVidia or AMD GPUs, the default queue creation will fail on Linux.

There's several ways of fixing this at the application level, setting the environment variable `SYCL_ENABLE_DEFAULT_CONTEXTS` to `0`, creating the context manually like in https://github.com/intel/llvm-test-suite/pull/433

However we should probably fix it at the DPC++ level as it is quite confusing, but I'm not entirely sure how we should fix it:

* Disable it by default if either CUDA or HIP plugins are built (default selected with preprocessor define at the moment)?
* Still create it but only with one device (not sure if that would work if the device from the selector is not in the default context)
* Completely bypass the extension at runtime depending on the plugin being used?

**Comment by romanovvlad** [comment]
I would suggest the following short/middle term solution - Update CUDA plugin(and HIP one if needed) to return each device in a separate platform.
