### ISSUE TITLE
SYCL+Cuda unresolved extern function for atomic_ref overloads for long long 

### ISSUE THREAD

**Issue by masterleinad** [intel/llvm#4554]
**Describe the bug**
It seems that the `long long` overloads for `sycl::atomic_ref` are not properly mapped for SYCL+Cuda.

**To Reproduce**
Compiling https://github.com/intel/llvm/blob/bcfb6e7e3d1cbb8c6ce259c38b50cde9e027a017/sycl/test/atomic_ref/compare_exchange.cpp via
```bash
clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice -fsycl-libspirv-path=/opt/sycl/lib/clc/libspirv-nvptx64--nvidiacl.bc atomic_reproducer.cpp
```
gives
```
clang-14: warning: unknown CUDA version: version.txt: 10.2.89.; assuming the latest supported version 10.1 [-Wunknown-cuda-version]
ptxas fatal   : Unresolved extern function '_Z29__spirv_AtomicCompareExchangePU3AS1xN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagES5_xx'
llvm-foreach: 
clang-14: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 14.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/sycl/bin
clang-14: note: diagnostic msg: Error generating preprocessed source(s).
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: NVIDIA GPU, V100
- DPC++ version: nightly release from 2021/08/18
- Dependencies version: bundled with the release

**Comment by Michoumichmich** [comment]
That's surprising, I remember using them on this very back-end. Can you try using `uint64_t` or `int64_t` ? I noticed you are passing `-fsycl-libspirv-path=`, but it should work without

**Comment by masterleinad** [comment]
Without `-fsycl-libspirv-path=<library-built-with-compiler>` I get
```
clang-14: warning: unknown CUDA version: version.txt: 10.2.89.; assuming the latest supported version 10.1 [-Wunknown-cuda-version]
clang-14: error: cannot find 'libspirv-nvptx64--nvidiacl.bc'; provide path to libspirv library via '-fsycl-libspirv-path', or pass '-fno-sycl-libspirv' to build without linking with libspirv
clang-14: error: cannot find 'libspirv-nvptx64--nvidiacl.bc'; provide path to libspirv library via '-fsycl-libspirv-path', or pass '-fno-sycl-libspirv' to build without linking with libspirv
```
I believe this is fixed by https://github.com/intel/llvm/pull/4452.

Replacing `long `long` by `unit64_t` or `int64_t` passes the test.

**Comment by masterleinad** [comment]
Looks like this is resolved in a nightly release after https://github.com/intel/llvm/pull/4452 has been merged.
