### ISSUE TITLE
[SYCL] query the status of a SYCL queue (without a synchronization)

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#4620]
*Feature Request*
I was wondering if there is a way to monitor the status of work completion enqueued to a given SYCL queue. This is to mimic the functionality of `cudaStreamQuery` to report on the completion status of the work assigned to a CUDA stream.

**Comment by keryell** [comment]
It looks like this could be a good suggestion for the SYCL standard on https://github.com/KhronosGroup/SYCL-Docs, not only this implementation.

**Comment by abagusetty** [comment]
Thanks @keryell for supporting this. Hope this create some traction with the committee. https://gitlab.khronos.org/sycl/Specification/-/issues/569

**Comment by romanovvlad** [comment]
@abagusetty 
Hi, since there is a tracker in Khronos repo, do you mind closing this tracker?
