### ISSUE TITLE
Ptxas command failed - Parsing error

### ISSUE THREAD

**Issue by Luigi-Crisci** [intel/llvm#4623]
Hi,
When targeting cuda, I got this parsing error:
```
ptxas /tmp/dock-1de3aa-ef3ce8.s, line 127; fatal   : Parsing error near '$str1': syntax error
ptxas fatal   : Ptx assembly aborted due to errors
llvm-foreach: 
clang-14: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 14.0.0 (https://github.com/intel/llvm f37b22d1552eda5a77f77a4f6e1f413f408476f2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

This is the related code:
```
.global .align 1 .b8 $str1[12] = {95, 95, 67, 85, 68, 65, 95, 65, 82, 67, 72, 0};
mov.u64     %rd10, ($str1);  <-- Line 127
```

**Comment by Luigi-Crisci** [comment]
I forgot to post the compilation flags I am using:
```
-fsycl -fsycl-unnamed-lambda -g -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend '--cuda-gpu-arch=sm_70'
```

**Comment by AerialMantis** [comment]
Hi @Luigi-Crisci, unfortunately we have not been able to reproduce this error and without a sample code which produces this error we cannot identify whether this is still a problem or not, therefore we will now close this ticket. If you are still experiencing this error, please let us know and if you could provide a sample code which reproduces the problem we can re-open the ticket again. Thanks.
