### ISSUE TITLE
CUDA build fails to find CUDA

### ISSUE THREAD

**Issue by tomdeakin** [intel/llvm#4651]
Building with the CUDA PI is still very challenging.

I have gcc 8.1, cuda10.2, cmake 3.18.3.

```
$ CUDA_BIN_PATH=/cm/shared/apps/cuda10.2/toolkit/10.2.89 CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda
$ CUDA_BIN_PATH=/cm/shared/apps/cuda10.2/toolkit/10.2.89 CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/compile.py
ninja: error: 'CUDA_CUDA_LIBRARY-NOTFOUND', needed by 'lib/libpi_cuda.so', missing and no known rule to make it
```

Looking in `llvm/build/CMakeCache.txt`, I see:
```
CUDA_CUDA_LIBRARY:FILEPATH=CUDA_CUDA_LIBRARY-NOTFOUND
```
but I also see all the other CUDA variables defined correctly.

I tried setting it manually on configure, but this gets the same error.
```
$ CUDA_BIN_PATH=/cm/shared/apps/cuda10.2/toolkit/10.2.89 CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda  --cmake-opt="-DCUDA_CUDA_LIBRARY=/cm/shared/apps/cuda10.2/toolkit/10.2.89/lib64/stubs/libcuda.so" 
```

If I also set `CUDA_TOOLKIT_ROOT_DIR`, then I get nonsense errors:
```
$CUDA_BIN_PATH=/cm/shared/apps/cuda10.2/toolkit/10.2.89 CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda  --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/cm/shared/apps/cuda10.2/toolkit/10.2.89 -DCUDA_CUDA_LIBRARY=/cm/shared/apps/cuda10.2/toolkit/10.2.89/lib64/stubs/libcuda.so"
[...]
-- Including the PI API CUDA backend.
CMake Error at /lustre/projects/bristol/modules/cmake/3.18.3/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found suitable version
  "10.2", minimum required is "10.1")
``` 

What do I need to pass to CMake to guarantee it finds the toolkit?

**Comment by alexbatashev** [comment]
This is a dirty hack, but it usually helps me in similar situations:
Set `CUDA_CUDA_LIBRARY` to libcudadrv.so full path and `CUDA_INCLUDE_DIRS` to full path to CUDA includes. You can do it with something like `python configure.py --cuda --no-werror --cmake-opt="-DCUDA_CUDA_LIBRARY=/smth/lib.so" --cmake-opt="-DCUDA_INCLUDE_DIRS=/smth/include"`.

**Comment by Naghasan** [comment]
From my poor cmake understanding you could set the path using `CUDA_PATH` or `CUDA_LIB_PATH` (https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA.cmake#L977)

I think the cmake set-up is using very legacy stuff (hence your trouble I guess),

**Comment by alexbatashev** [comment]
@Naghasan [FindCudaToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html) was introduced in CMake 3.17, and LLVM community has settled with CMake 3.14, so that is probably very close to the right way of linking with CUDA in 2019.

**Comment by tomdeakin** [comment]
@alexbatashev Thanks for the reply.

There is no `libcudadrv.so` in the Toolkit. What is the library name?


Please document `--cmake-opt`. Ideally in the`--help` output and on [the online docs](https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-nvidia-cuda).

**Comment by tomdeakin** [comment]
@alexbatashev - still fails even when setting it manually:
```
$ CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda  --cmake-opt="-DCUDA_CUDA_LIBRARY=/cm/shared/apps/cuda10.2/toolkit/10.2.89/lib64/stubs/libcuda.so"

$ CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/compile.py

ninja: error: 'CUDA_CUDA_LIBRARY-NOTFOUND', needed by 'lib/libpi_cuda.so', missing and no known rule to make it
```

Even specifying it manually doesn't set it.

**Comment by Ruyk** [comment]
Did you try modifying the CMakeCache.txt file directly with the correct path? On my system:

```quote
//"cuda" library (older versions only).
CUDA_CUDA_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcuda.so
```

**Comment by tomdeakin** [comment]
@Ruyk I did try, but CMake runs again and throws it away when I run the `$DPCPP_HOME/llvm/buildbot/compile.py` script. 😞

**Comment by Ruyk** [comment]
compile just re-runs Cmake with --build, seems there is something wrong with the way CMake finds CUDA in your system. Usually there is no need to point to the CUDA library directly. But also the error can be misleading: Sometimes by not finding the header files it makers the entire library as -NOTFOUND, i wonder if you have to manually specify libraries and headers...

**Comment by tomdeakin** [comment]
@Ruyk Setting `CUDA_INCLUDE_DIRS` too doesn't help either.

This is the output for `grep CUDA llvm/build/CMakeCache.txt`. Maybe it shows something weird going on, but from what I can see, everything apart from `CUDA_CUDA_LIBRARY`, `CUDA_SDK_ROOT_DIR` and `CUDA_cupti_LIBRARY` - none of which should matter given it has everything else filled out.
[cuda.txt](https://github.com/intel/llvm/files/7245432/cuda.txt)

**Comment by tomdeakin** [comment]
@joeatodd 
Setting `CUDA_PATH` gives me a warning on configure, and the same `NOTFOUND` error on compile:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CUDA_PATH
```

The same happens for `CUDA_LIB_PATH`.

**Comment by joeatodd** [comment]
That looks like maybe you're setting a cmake variable rather than an environment variable?

**Comment by tomdeakin** [comment]
@joeatodd I was - and setting it as an environment variable doesn't help either.

**Comment by joeatodd** [comment]
There's a similar problem described here https://github.com/ddemidov/vexcl/issues/149, including a useful minimal CMakeLists.txt:

```
cmake_minimum_required(VERSION 2.8)

find_package(CUDA)

message(STATUS "CUDA LIBRARIES: ${CUDA_LIBRARIES}")
message(STATUS "CUDA LIBRARY:   ${CUDA_CUDA_LIBRARY}")
```

Perhaps we should work with that to iterate faster? On our system, this gives me:
```
-- CUDA LIBRARIES: /usr/local/cuda/lib64/libcudart_static.a;Threads::Threads;dl;/usr/lib/x86_64-linux-gnu/librt.so
-- CUDA LIBRARY:   /usr/lib/x86_64-linux-gnu/libcuda.so
```

**Comment by tomdeakin** [comment]
@joeatodd Thanks for that, that page was useful. The key is `CUDA_LIB_PATH` is the *directory* `/cm/shared/apps/cuda10.2/toolkit/10.2.89/lib64/stubs` not the library itself.

With that change, it starts to build. It errors on OpenCL stuff which look like they are caused by picking up the OpenCL headers that ship with CUDA, rather than the ones that were downloaded as part of configure.
I can't use the `-v` flag on `compile.py` because it is not understood correctly by ninja:
```
ninja: unrecognized option '--verbose'
```



```

**Comment by tomdeakin** [comment]
Update.

I managed to make this work. Thanks for all the pointers.

The problem is CUDA is installed in a non-default location. If you have it available in the usual environment variables (`PATH`, `LIBRARY_PATH`, etc), then this CMake build system gets in a tangle.

The "trick" is to *not load* CUDA into any paths. On a cluster, this means not loading the module.

Then, tell the build system where CUDA lives.
You need to tell it twice on configure, once on compile, and again when using the compiler.

`CUDA_LIB_PATH` should be set to the **directory** where `libcuda.so` lives. Do not set it to the library itself.

```bash
$ CUDA_LIB_PATH=/path/to/cuda/toolkit/lib64/stubs CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/path/to/cuda/toolkit"

$ CUDA_LIB_PATH=/path/to/cuda/toolkit/lib64/stubs CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/compile.py

$ $DPCPP_HOME/llvm/build/bin/clang++ -std=c++17 -O3 -fsycl -fsycl-targets=nvptx64-nvidia-cuda --cuda-path=/path/to/cuda/toolkit *.cpp -o a.out

$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DPCPP_HOME/llvm/build/lib ./a.out
```

Please document this procedure for non-default location CUDA installs somewhere, such as [here](https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-nvidia-cuda).

I'm happy for this issue to be closed once the documentation has been updated.

Thanks everyone.

**Comment by joeatodd** [comment]
Glad you got it working & thanks for posting the fix. The OpenCL headers problem is something I'd faced before but I couldn't quite figure out how to solve it.

**Comment by joeatodd** [comment]
I've made a PR describing installation with non-standard CUDA location, including your example.
