### ISSUE TITLE
Provide `address_space::generic_space` and default template space argument for `atomic_ref`

### ISSUE THREAD

**Issue by masterleinad** [intel/llvm#4669]
**Is your feature request related to a problem? Please describe**

The SYCL2020 specification (https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:multiptr) say that `address_space::generic_space` exists.
Additionally, `atomic_ref` should have a default Space argument with the default being `adress_space::generic", see https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:atomic-references.

The missing enum causes problems when trying to implement an interface for atomics for which the address space is not known, see https://github.com/desul/desul/pull/21#discussion_r651352679 and https://github.com/kokkos/kokkos/pull/4358. Ideally, `SYCL`/`DPCPP` would provide a facility to obtain the address space for a given pointer at runtime but if this is not available we require a fallback option that is compatible with all address spaces.
Currently, we need to work around this and restricting the usage to `global_space` (which I believe is global space on the device).

**Describe the solution you would like**
Provide `address_space::generic_space` and default template space argument for `atomic_ref`.

**Describe alternatives you have considered**
Provide a facility to obtain the address space for a given pointer.

**Comment by Pennycook** [comment]
> Describe alternatives you have considered
Provide a facility to obtain the address space for a given pointer.

This kind of exists, but not in a form that is easy to use today.  SYCL 2020 defines `address_space_cast` (although Revision 3 doesn't include a definition for it).  The latest draft contains a fix for this: see https://github.com/KhronosGroup/SYCL-Docs/commit/c9af406303cb372e738021b367a2d78ebd977e71

DPC++ doesn't implement this API yet, but the SPIR-V instruction that it corresponds to ([`OpGenericCastToPtrExplicit`](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpGenericCastToPtrExplicit)) is supported.  Some of the DPC++ headers use it today, and you could use it as a workaround: see [here](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/ext/oneapi/sub_group.hpp#L430) for an example.

If this would be useful to you, I think you should open a separate feature request for `address_space_cast` support.

**Comment by crtrott** [comment]
I think that address_space_cast could be generally useful, though maybe a runtime traits test like 
`bool is_space<address_space>(ptr);`
would be a nicer interface. I mean I can write that with the address_space_cast I guess, but it feels like if I were to write that you can't optimize this as well. For example, on architectures where the ptr value encodes the address space, the above function could be implemented simply via a bitmask, while the cast and then check if its nullptr would likely be more instructions.

**Comment by masterleinad** [comment]
It appears to me that `sycl::make_ptr` should have a similar function as `address_space_cast` (what it is deprecated for) but the current implementation has https://github.com/intel/llvm/blob/4112cbc5c864a40423e13599f1edc6471ca5caa4/sycl/include/CL/sycl/multi_ptr.hpp#L57-L60 and https://github.com/intel/llvm/blob/4112cbc5c864a40423e13599f1edc6471ca5caa4/sycl/include/CL/sycl/multi_ptr.hpp#L578-L584
and doesn't check the space compatibility.

**Comment by bader** [comment]
> doesn't check the space compatibility.

Right. DPC++ doesn't deduce address space during semantic analysis. It's rather a performance optimization.

Tagging @rolandschulz, @Naghasan.

**Comment by rolandschulz** [comment]
Yes. We use generic address space as default (5.9.3) and not inferred address space (5.9.4). 1.2.1 (and therefore `make_ptr`) only supported inferred(/deduced) address space. [address_space_cast](https://github.com/KhronosGroup/SYCL-Docs/blob/SYCL-2020/master/adoc/chapters/programming_interface.adoc#user-content-table.constructors.multiptr) makes the distinction between runtime- (generic) and compile-time (inferred) and we will need to return `nullptr` when the address space is incompatible.

**Comment by Naghasan** [comment]
The API for `make_ptr` and some other parts of `multi_ptr` were built with for 1.2.1 (with the assumption that address spaces are fully deduced at compile time).

By "some other parts of `multi_ptr`" I mean things like what you pointed out here
https://github.com/intel/llvm/blob/4112cbc5c864a40423e13599f1edc6471ca5caa4/sycl/include/CL/sycl/multi_ptr.hpp#L57-L60

But that is no longer part of the 2020 `multi_ptr` API
https://github.com/KhronosGroup/SYCL-Docs/blob/SYCL-2020/master/adoc/headers/multipointer.h#L49 (there is still access to the legacy interface though)

**Comment by masterleinad** [comment]
In https://github.com/KhronosGroup/SYCL-Docs/blob/SYCL-2020/master/adoc/chapters/programming_interface.adoc#user-content-table.constructors.multiptr the description of `make_ptr` and `address_space_cast` are pretty much identical.
Since `address_space_cast` had not yet been implemented, I had hoped that `make_ptr` would provide the functionality I am asking for in this pull request. That's all.

**Comment by alexbatashev** [comment]
@masterleinad generic address space has been added in https://github.com/intel/llvm/commit/e99f298e20511ae3f592f1a4d3a491507a91b01c

Can this issue be closed now?

**Comment by masterleinad** [comment]
Tested in https://github.com/kokkos/kokkos/pull/4739.
