### ISSUE TITLE
Suspicious compiler behaviour with different localSize in `nd_range<1>` kernel 

### ISSUE THREAD

**Issue by itzmeanjan** [intel/llvm#4679]
## Background

Hello, I was writing one 1D parallel (inv)FFT implementation from scratch & noticed something strange when using `dpcpp` compiler with different local sizes for `nd_range<1>` kernels. When I compiled same program with same local sizes using `clang++`, strange behaviour doesn't show up anymore. 

I suspect it is a bug, but feel free to correct me 🙂

Parallel (inv) FFT implementation: https://gist.github.com/itzmeanjan/94cadd86e99cf6fe6dfe4f6439b7ce28

`dpcpp` compiler version

```bash
$ dpcpp --version
Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2021.3.0/linux/bin
```

`clang++` compiler version

```bash
$ clang++ --version
Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2021.3.0/linux/bin
```

I'm using oneAPI base tool kit on GNU/Linux, downloaded from [here](https://software.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/apt.html#apt)

```bash
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

## Problem

When compiling with `dpcpp` & local work group size B > 4 ( such as 8/ 16/ 32 ), final assertion fails https://gist.github.com/itzmeanjan/94cadd86e99cf6fe6dfe4f6439b7ce28#file-fft-cpp-L228-L230.

```bash
dpcpp -fsycl 30.cpp && ./a.out # with B = 32
running on Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
fft ✅, in 479 ms
inverse fft ✅, in 7 ms
a.out: 30.cpp:229: int main(int, char **): Assertion `src_vec[i] == std::round(inv_dst_vec[i].real())' failed.
Aborted (core dumped)
```

When compiling same program with B <= 4, it computes FFT & inverse FFT correctly.

```bash
$ dpcpp -fsycl 30.cpp && ./a.out # set B = 4, see https://gist.github.com/itzmeanjan/94cadd86e99cf6fe6dfe4f6439b7ce28#file-fft-cpp-L10
running on Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
fft ✅, in 490 ms
inverse fft ✅, in 7 ms
asserted !
```

Now do same while compiling with `clang++`, everything works fine for any local size ( such as B = {1, 2, 4, 8, 16, 32 ...})

```bash
$ clang++ -fsycl 30.cpp && ./a.out # always correct when B <= 4 or B > 4
running on Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
fft ✅, in 1542 ms
inverse fft ✅, in 9 ms
asserted !
```

## Insights 

For deeper understanding into what I'm doing, consider setting `N = 8 & B = 4` ( check https://gist.github.com/itzmeanjan/94cadd86e99cf6fe6dfe4f6439b7ce28#file-fft-cpp-L9-L10 ) while adding following for printing logs

```bash
228| for (uint i = 0; i < N; i++) {
229|    std::cout << src_vec[i] << "\t" << dst_vec[i] << "\t" << inv_dst_vec[i] << std::endl;
230|    // assert(src_vec[i] == std::round(inv_dst_vec[i].real()));
231| }
```

Now compile & run with `dpcpp`, see inverse fft inverts back to original values correctly. This works pretty fine if you set B <= 4 & N >= 1 (power of 2).

```bash
...

0       (28,0)  (0,-1.11022e-16)
1       (-4,9.65685)    (1,1.36716e-16)
2       (-4,4)  (2,1.14424e-17)
3       (-4,1.65685)    (3,8.53284e-17)
4       (-4,0)  (4,1.11022e-16)
5       (-4,-1.65685)   (5,-1.36716e-16)
6       (-4,-4) (6,-1.14424e-17)
7       (-4,-9.65685)   (7,-8.53284e-17)

...
```

Now leave N = 8 & set B = 8, consider recompiling & running. See fft doesn't work anymore ! 

```bash
...

0       (-4,-10)        (-2.06066,2.02513)
1       (4,10)  (0,-2)
2       (4,10)  (0,-2)
3       (12.2426,9.89949)       (1.70711,-2.14645)
4       (4,10)  (0,-2)
5       (12.2426,9.89949)       (1.70711,-2.14645)
6       (12.2426,9.89949)       (1.70711,-2.14645)
7       (3.75736,-9.89949)      (0.353553,2.12132)

...
```

Actual part of fft computation is written in this kernel https://gist.github.com/itzmeanjan/94cadd86e99cf6fe6dfe4f6439b7ce28#file-fft-cpp-L73-L86, where change in local size B should not get reflected ! 

As I only make use of `global_id` https://gist.github.com/itzmeanjan/94cadd86e99cf6fe6dfe4f6439b7ce28#file-fft-cpp-L74.

> Let me know if I can provide with any thing else.
Thanks.

**Comment by alexbatashev** [comment]
@itzmeanjan `dpcpp` adds more aggressive optimization flags by default (including floating points). So I would expect this kind of behavior.

**Comment by itzmeanjan** [comment]
Thanks @alexbatashev for confirming. While setting local work group size <= 4, it works fine, do you think it has anything to do with preferred work group size for CPUs ?

**Comment by AlexeySachkov** [comment]
> Just a quick question, while setting local work group size <= 4, it works fine, do you think it has anything to do with preferred work group size for CPUs ?

@itzmeanjan, it might be that with small local size, vectorization isn't possible anymore, which leads to a different code being executed. So, probably there is some difference in precision in scalar and vector paths?
There should be some flags which allow you to explicitly control the vectorization - using them you can try and prove the idea.

About more aggressive optimizations flags: if I'm not mistaken, `dpcpp` uses `-fp-model=fast` by default, whilst `clang++` defaults to `-fp-model=strict`. (if I remember the spelling correctly). You can try toggling those options as well to investigate a bit more

**Comment by AlexeySachkov** [comment]
@itzmeanjan, based on [release notes](https://software.intel.com/content/www/us/en/develop/articles/opencl-runtime-release-notes.html), the env variable is `CL_CONFIG_CPU_VECTORIZER_MODE`: I guess passing `1` there should disable the vectorization

**Comment by itzmeanjan** [comment]
Thanks @AlexeySachkov ! 

I'm closing this issue.
