### ISSUE TITLE
Debug build optionally allow optimized target

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/llvm#4689]
```
   if (Args.getLastArg(options::OPT_O0))
-    BeArgs.push_back(IsGen ? "-O0" : "-cl-opt-disable");
+    BeArgs.push_back("-cl-opt-disable");
   if (BeArgs.empty())
```

The AOT driver presume "-g -cl-opt-disable' when option contains "-O0 -g". However, when compile large project this end up extreme compilation time and unknown error at the end of linking, probably too much work to do for ocloc. I guess even compilation is done the device part is extremely slow and useless for certain debug granularity.

So, can we have an option that allows host part to be non-optimized and debuggable while device target part to be optimized, without -cl-opt-disable?

**Comment by CaoZhongZ** [comment]
Update for the case of our usage. ```sycl-post-link``` is OOM killed when digesting ```-g``` bitcode of massive number of kernels, with per-kernel split configuration. Machine configured about 64GB ram.

**Comment by AlexeySachkov** [comment]
@CaoZhongZ, my understanding is that should be possible with [`-Xsycl-target-frontend=<T> "options"`](https://github.com/intel/llvm/blob/sycl/sycl/doc/UsersManual.md#target-toolchain-options) option, i.e. something like:
```
clang++ -fsycl -O0 -g -Xsycl-target-frontend=spir64 "-O2 -g0" ...
```

should do the trick.
