### ISSUE TITLE
Remove restrictions on sycl::group_broadcast

### ISSUE THREAD

**Issue by masterleinad** [intel/llvm#4717]
**Is your feature request related to a problem? Please describe**
Related to https://github.com/kokkos/kokkos/pull/4388.
Despite `SYCL2020` not constraining `sycl::group_broadcast` (https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_group_broadcast), the oneAPI implementation does, see https://github.com/intel/llvm/blob/f844f709820fd3b5fad008eb9d957334a8093ef7/sycl/include/CL/sycl/group_algorithm.hpp#L452-L499.

**Describe the solution you would like**
Remove the restriction to arithmetic types.

**Describe alternatives you have considered**
There is a workaround in https://github.com/kokkos/kokkos/pull/4388 that should also work as a general fallback option if a more efficient implementation for `non-arithmetic` types cannot be provided.

**Comment by Pennycook** [comment]
https://github.com/intel/llvm/pull/4910/ restored support for trivially copyable types. @masterleinad, please close this issue if that is sufficient.
