### ISSUE TITLE
Investigate if streams/samplers work as base classes

### ISSUE THREAD

**Issue by elizabethandrews** [intel/llvm#4762]
Looks like https://github.com/intel/llvm/pull/3892 might fix some of the existing issues. Investigate current status and add test coverage.

**Comment by KornevNikita** [comment]
Hi! There have been no updates for at least the last 60 days, though the ticket has assignee(s).

      @elizabethandrews, could I ask you to take one of the following actions? :)
      - Please provide an update if you have any (or just a small comment if you don't have any yet).
      - OR mark this issue with the 'confirmed' label if you have confirmed the problem/request and our team should work on it.
      - OR close the issue if it has been resolved.
      - OR take any other suitable action.

      Thanks!

**Comment by elizabethandrews** [comment]
Streams/samplers should work in base classes. This can be closed.
