### ISSUE TITLE
CUDA target functionality using clang-cl on Windows

### ISSUE THREAD

**Issue by mdtoguchi** [intel/llvm#4764]
When running through various scenarios with CUDA, it was found that the CUDA based enabling options are not typically available with the clang-cl (MSVC compatible) driver interface.

What is required/needs to be done to enable on the platform?  Use of clang/clang++ is available as an alternative.

**Comment by AerialMantis** [comment]
The pull request for this has been merged and we believe this issue to be resolved, so we are closing it, if you are still seeing this issuer we can re-open the ticket.
