### ISSUE TITLE
[CUDA] Asserts tests from llvm-test-suite are failed for unresolved extern function '_wassert' on Windows

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#4810]
**Describe the bug**
Asserts tests from [intel/llvm-test-suite](https://github.com/intel/llvm-test-suite) are failed for unresolved extern function '_wassert' with CUDA backend on Windows

**To Reproduce**
1. Failed tests are from intel/llvm-test-suite, which are
```
  SYCL :: Assert/assert_in_kernels_win.cpp
  SYCL :: Assert/assert_in_multiple_tus_one_ndebug_win.cpp
  SYCL :: Assert/assert_in_multiple_tus_win.cpp
  SYCL :: Assert/assert_in_one_kernel_win.cpp
  SYCL :: Assert/assert_in_simultaneous_kernels_win.cpp
```
2. Commands used to compile and launch the program
Take [SYCL/Assert/assert_in_multiple_tus.cpp](https://github.com/intel/llvm-test-suite/blob/intel/SYCL/Assert/assert_in_multiple_tus.cpp) as an example.
```
clang-cl /EHsc -DSYCL_ENABLE_FALLBACK_ASSERT -fsycl -fsycl-targets=nvptx64-nvidia-cuda -DDEFINE_NDEBUG_INFILE2 -I ./SYCL/Assert/Inputs SYCL/Assert/assert_in_multiple_tus.cpp SYCL/Assert/Inputs/kernels_in_file2.cpp -o build/SYCL/Assert/Output/assert_in_multiple_tus_one_ndebug_win.cpp.tmp.out
```
Error message:
```
ptxas fatal   : Unresolved extern function '_wassert'
llvm-foreach:
Assertion failed: !KeyInfoT::isEqual(Val, EmptyKey) && !KeyInfoT::isEqual(Val, TombstoneKey) && "Empty/Tombstone value shouldn't be inserted into map!", file ${compiler_build_path}\llvm\include\llvm/ADT/DenseMap.h, line 624
```

**Environment**

- OS: Windows
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git 3ef8c82338801e946c4410bd7699bd17004f3f61
- CUDA version:
```
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

**Comment by jchlanda** [comment]
I believe this has been fixed in: https://github.com/intel/llvm/commit/f29b498d00b1c062891407e873365fdee13eba65
(now moved to libdevice: https://github.com/intel/llvm/commit/1fe92c544e4fbeac8e322b882cda451fd7e5f725)
@yuxianch are you still experiencing that error?

**Comment by jchlanda** [comment]
Closing it now as fixed, please feel free to re-open if you still can reproduce the error.
