### ISSUE TITLE
[CUDA] CTS device test runfail with 'No device of requested type available' on Linux

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#4812]
**Describe the bug**
CTS device test runfail with 'No device of requested type available' with CUDA backend on Linux.

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and [SYCL-CTS](https://github.com/KhronosGroup/SYCL-CTS)
2. Build CTS tests
```
cd SYCL-CTS
mkdir build && cd build
cmake -GNinja  -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -Dopencl_platform_name=nvidia -Dopencl_device_name=opencl_gpu -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-fsycl -fsycl-unnamed-lambda -Wno-deprecated-declarations" -DINTEL_SYCL_FLAGS="-Xsycl-target-backend;--cuda-gpu-arch=sm_50" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda-sycldevice -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja test_device_selector
```
3. Run test
```
export SYCL_DEVICE_FILTER="cuda:gpu:0"
export SYCL_ENABLE_HOST_DEVICE="1"
./bin/test_device_selector -p nvidia -d opencl_gpu  --test device_selector_custom
```
Error message:
```
--- device_selector_custom
  . sycl exception caught
  . what - No device of requested type available. -1 (CL_DEVICE_NOT_FOUND)
  . line: 110
  . a SYCL exception was caught: No device of requested type available. -1 (CL_DEVICE_NOT_FOUND)
  - fail

  . Passed 0/2 tests (0%)
```

**Environment**

- OS: ubu20.04
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git c623223a78e0d1b8bc8bdba6cd7fd4ddf960cb3e
- CUDA version: 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
```

**Additional context**
This issue is a regression caused by https://github.com/intel/llvm/commit/ef4e6ddce56fe21621bca7d62932713152de3f0e ( @bso-intel )

**Comment by yuxianch** [comment]
Thanks @bader 
Just try to run the test from updated SYCL-CTS. The test can get passed now. The run commands have been updated to:
```
export SYCL_DEVICE_FILTER="CUDA:GPU,HOST"
export SYCL_ENABLE_HOST_DEVICE="1"
./bin/test_device_selector  --test device_selector_custom
```
As the test gets passed, I am going to close this issue.

**Comment by pgorlani** [comment]
I'm glad to see you managed to resolve the issue, we looked into this and we were able to reproduce the error. The exception is thrown when the test try to select the host device. As you pointed out, you can make visible the host device to the SYCL runtime by setting `SYCL_DEVICE_FILTER=host,cuda:gpu:0`. Actually, setting `SYCL_ENABLE_HOST_DEVICE` doesn't have any effect for us. This environmental variable seems not used in DPC++, see the variable list at https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md
