### ISSUE TITLE
[SYCL] ```sycl::nextafter``` returning unaltered input for ```sycl::half```

### ISSUE THREAD

**Issue by hdelan** [intel/llvm#4815]
For ```sycl::half```s, ```sycl::nextafter``` returning incorrect result. 

**To Reproduce**

```
int main () {
  sycl::half a {.32}, b {.134};
  sycl::half c = sycl::nextafter(a,b);
  if (a==c) std::cout << "Nextafter returning unaltered input!" << std::endl;
}
```
**To compile:**
```
clang++ -fsycl file.cpp
```
**To run:**
```
./a.out
```
The program will execute the std::cout call. This should not happen as ```sycl::nextafter``` should return one of the floating point values adjacent to ```a```. The issue only occurs for ```sycl::half```.

**Environment :**

- OS: Ubuntu 18.04
- Target device and vendor: Host device
- DPC++ version: [clang version 14.0.0]

**Comment by vladimirlaz** [comment]
@hdelan could you close the issue to avoid duplication. The fix is going to be implemented in scope of https://github.com/intel/llvm/issues/5418.

**Comment by hdelan** [comment]
Sure will do.
