### ISSUE TITLE
[CUDA] CTS multi_ptr tests are failed to build due to ptxas fatal: Unresolved extern function '_Z20__spirv_ocl_prefetchPU3AS1Kcy'

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#4817]
**Describe the bug**
CTS multi_ptr tests are failed to build due to ptxas fatal: Unresolved extern function '_Z20__spirv_ocl_prefetchPU3AS1Kcy' with CUDA backend on Windows.

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and [SYCL-CTS](https://github.com/KhronosGroup/SYCL-CTS https://github.com/KhronosGroup/SYCL-CTS/commit/14fac446f4454d4889a6b0e7bf5eab83bbe4cf26)
2. Build CTS tests
```
cd SYCL-CTS
mkdir build && cd build
cmake -GNinja  -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -Dopencl_platform_name=nvidia -Dopencl_device_name=opencl_gpu -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-fsycl -fsycl-unnamed-lambda /EHsc /EHsc /MD -Wno-deprecated-declarations" -DINTEL_SYCL_FLAGS="-Xsycl-target-backend;--cuda-gpu-arch=sm_50" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda-sycldevice -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja test_multi_ptr
```
Error message:
```
ptxas fatal   : Unresolved extern function '_Z20__spirv_ocl_prefetchPU3AS1Kcy'
llvm-foreach:
Assertion failed: !KeyInfoT::isEqual(Val, EmptyKey) && !KeyInfoT::isEqual(Val, TombstoneKey) && "Empty/Tombstone value shouldn't be inserted into map!", file <build path>\llvm\include\llvm/ADT/DenseMap.h, line 624
```

**Environment**

- OS: Windows
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git c623223a78e0d1b8bc8bdba6cd7fd4ddf960cb3e
- CUDA version: 
```
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

**Comment by AidanBeltonS** [comment]
I can replicate the issue on CTS. The issue appears to be due to the built-in not being within the nvidia libspirv library. 
A valid function is defined within libclc, however the remangler replaces the char type with a signed char and does not correctly create the replacement alias. So `_Z20__spirv_ocl_prefetchPU3AS1Kay` exists but `_Z20__spirv_ocl_prefetchPU3AS1Kcy` is not aliased to the builtin.

I have proposed a fix: https://github.com/intel/llvm/pull/5041

**Comment by AidanBeltonS** [comment]
This is not a fix to the test as there are some runtime issues.
```
--- multi_ptr_api
  . sycl exception caught
  . what - No kernel named _ZTSN20multi_ptr_api_common7kernel0IbvEE was found -46 (CL_INVALID_KERNEL_NAME)
  . line: 26
  . a SYCL exception was caught: No kernel named _ZTSN20multi_ptr_api_common7kernel0IbvEE was found -46 (CL_INVALID_KERNEL_NAME)
  - fail

--- multi_ptr_api_fp16
  . sycl exception caught
  . what - Native API failed. Native API returns: -42 (CL_INVALID_BINARY) -42 (CL_INVALID_BINARY)
  . line: 26
  . a SYCL exception was caught: Native API failed. Native API returns: -42 (CL_INVALID_BINARY) -42 (CL_INVALID_BINARY)
  - fail

--- multi_ptr_constructors
  . sycl exception caught
  . what - No kernel named _ZTSN29multi_ptr_constructors_common7kernel0IbvEE was found -46 (CL_INVALID_KERNEL_NAME)
  . line: 26
  . a SYCL exception was caught: No kernel named _ZTSN29multi_ptr_constructors_common7kernel0IbvEE was found -46 (CL_INVALID_KERNEL_NAME)
  - fail

--- multi_ptr_constructors_fp16
  . sycl exception caught
  . what - Native API failed. Native API returns: -42 (CL_INVALID_BINARY) -42 (CL_INVALID_BINARY)
  . line: 26
  . a SYCL exception was caught: Native API failed. Native API returns: -42 (CL_INVALID_BINARY) -42 (CL_INVALID_BINARY)
  - fail

  . Passed 0/4 tests (0%)
```

**Comment by AerialMantis** [comment]
We believe the remaining issue here is the same as that seen in https://github.com/intel/llvm/issues/4873.

**Comment by AerialMantis** [comment]
We believe the remaining issue here to the same as that in https://github.com/intel/llvm/issues/4873 and the proposed solution there more generic and not CUDA-specific, so I will remove the CUDA label, if there is CUDA-specific issues involved here after all please re-add the label and we can look into it again.

**Comment by romanovvlad** [comment]
Closing then, please track further progress in https://github.com/intel/llvm/issues/4873. Please, feel free to reopen if any concerns.
