### ISSUE TITLE
[CUDA] CTS specialization_constants tests are failed for exception "No kernel found with the specified name" on Windows

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#4836]
**Describe the bug**
CTS specialization_constants tests are failed for exception "No kernel found with the specified name" with CUDA backend on Windows.
These following tests get the same output when running binary:
```
specialization_constants_exceptions_throwing_core
specialization_constants_external_core
specialization_constants_same_command_group_core
specialization_constants_via_handler_core
```

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and [SYCL-CTS](https://github.com/KhronosGroup/SYCL-CTS https://github.com/KhronosGroup/SYCL-CTS/commit/14fac446f4454d4889a6b0e7bf5eab83bbe4cf26)
2. Build CTS tests
```
cd SYCL-CTS
mkdir build && cd build
cmake -GNinja  -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -Dopencl_platform_name=nvidia -Dopencl_device_name=opencl_gpu -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-fsycl -fsycl-unnamed-lambda /EHsc /EHsc /MD -Wno-deprecated-declarations" -DINTEL_SYCL_FLAGS="-Xsycl-target-backend;--cuda-gpu-arch=sm_50" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda-sycldevice -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja test_specialization_constants
```
3. Run test
```
export SYCL_DEVICE_FILTER="cuda:gpu:0"
export SYCL_ENABLE_HOST_DEVICE="1"
bin/test_address_space -p nvidia -d opencl_gpu  --test specialization_constants_exceptions_throwing_core
```
Error message:
```
  . sycl exception caught
  . what - No kernel found with the specified name -46 (CL_INVALID_KERNEL_NAME)
  . line: 45
  . a SYCL exception was thrown: No kernel found with the specified name -46 (CL_INVALID_KERNEL_NAME)
  - fail

  . Passed 0/15 tests (0%)
```

**Environment**

- OS: Windows
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git 074944e44f5af12c0f41e622c84cac3b20b11211
- CUDA version: 
```
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

**Comment by npmiller** [comment]
Closing this as the kernel not found issue was fixed by recent patches (/link fix and objcopy bugfix). The specialization constant tests are still not working as they're not fully implemented for the CUDA plugin, but this is tracked in other tickets such as #5911
