### ISSUE TITLE
[SYCL] [L0] unhandled error status from level zero in _pi_queue::executeCommandList

### ISSUE THREAD

**Issue by ddabek-i** [intel/llvm#4854]
**Describe the bug**
Calling `zeCommandQueueExecuteCommandLists` can fail and return an error code. queue.wait() can then be called, resulting in application hang.

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. Include code snippet as short as possible
```
#include <CL/sycl.hpp>
#include <chrono>
#include <vector>
#include <iostream>

using namespace sycl;

int main(int argc, char* argv[]) {
  try {
    queue q;
	
    std::vector<void *> vector_pointers;
    // allocate enough memory so that executing the queue fails
    for (size_t i = 0; i < 10; i++)
        vector_pointers.push_back(sycl::malloc_device(4000000000, q));

    q.submit([&](handler &h) {
	h.parallel_for(1, [=](id<1> idx) {
      	});  // End of the kernel function
    });
    q.wait();
  } catch (exception const &e) {
    std::terminate();
  }

  return 0;
}
```

2. Specify the command which should be used to compile the program
`dpcpp reproducer.cpp -g -O0 -o reproducer`

3. Specify the comment which should be used to launch the program
SYCL_DEVICE_FILTER="level_zero:gpu" ./reproducer

4. Indicate what is wrong and what was expected
Behavior: The application hangs on q.wait().
Expected: An exception should be thrown either in q.submit() or q.wait().

**Environment (please complete the following information):**

- OS: Linux, Ubuntu 20.04
- Target device and vendor: Intel GPU (tested on dedicated)
- DPC++ version:
```
Intel(R) oneAPI DPC++/C++ Compiler 2021.4.0 (2021.4.0.20210924)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2021.4.0/linux/bin
```
- Dependencies version: versions from latest intel gfx-driver

**Additional context**
I believe something similar is happening with the opencl backend.

**Comment by romanovvlad** [comment]
@ddabek-i 

> Behavior: The application hangs on q.wait().
> Expected: An exception should be thrown either in q.submit() or q.wait().

Could you please clarify why an exception is required here? What specifically is incorrect in the application?
Also, could you please clarify why it was decided that the application hangs?

**Comment by ddabek-i** [comment]
> @ddabek-i please, try setting the async handler for queue. I think we haven't updated that part to match SYCL 2020 behavior yet.

Same behavior with async handler.
I'm attaching output from the reproducer with exception handler.
[log_for_sycl_issue.txt](https://github.com/intel/llvm/files/7458743/log_for_sycl_issue.txt)

Updated reproducer:
```
#include <CL/sycl.hpp>
#include <chrono>
#include <vector>
#include <iostream>

using namespace sycl;

static auto exception_handler = [](sycl::exception_list e_list) {
  for (std::exception_ptr const &e : e_list) {
    try {
      std::cout << "Failure, rethrowing" << std::endl;
	  std::cout << e.what() << std::endl;
      std::rethrow_exception(e);
    }
    catch (std::exception const &e) {
      std::cout << "Failure" << std::endl;
	  std::cout << e.what() << std::endl;
      std::terminate();
    }
  }
};

int main(int argc, char* argv[]) {
  try {
    queue q(exception_handler);
	
	std::vector<void *> vector_pointers;
    for (size_t i = 0; i < 10; i++)
        vector_pointers.push_back(sycl::malloc_device(4000000000, q));

    q.submit([&](handler &h) {
		h.parallel_for(1, [=](id<1> idx) {
        
      });  // End of the kernel function
	});
	q.wait();
  } catch (exception const &e) {
	std::cout << e.what() << std::endl;
    std::terminate();
  }

  return 0;
}
```

**Comment by ddabek-i** [comment]
transferred to internal tracking
