### ISSUE TITLE
Run on AMD Radeon graphics using openCL

### ISSUE THREAD

**Issue by dahubley** [intel/llvm#4858]
**Describe the bug**
The following error occurs when trying to run the program attached producing the following error:
InvalidBuiltinSetName: Expects OpenCL.std. Actual is OpenCL.DebugInfo.100 [Src: ..\..\..\libSPIRV\SPIRVModule.cpp:594 SPIRVBuiltinSetNameMap::rfind(BuiltinSetName, &BuiltinSet) ]

Expected behavior would be to have the GPU function as expected or have the GPU not listed if it is not support.

**To Reproduce**
Please describe the steps to reproduce the behavior:
Run attached program on an AMD CPU with Vega 10 Integrated Graphics.  

Environment:

- OS: Windows
- AMD Integrated Graphics
- DPC++ version: oneAPI Base Toolkit 2021.4
- Dependencies version: OpenCL 2.0

**Additional context**
[DPCPPConsoleApplication1.zip](https://github.com/intel/llvm/files/7449758/DPCPPConsoleApplication1.zip)

**Comment by Michoumichmich** [comment]
I don't believe that it is the support page for the oneAPI toolkit... Furthermore I don't think (and never saw) that AMD GPUs are supported through OpenCL. It'd recommend following the [GetStartedGuide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md) for AMD GPU support.

**Comment by dahubley** [comment]
Your tone is horrendous anyways. I understand that AMD cpu's are not supported. I'm not sure I understand why given that AMD includes openCL 2.0 in their drivers... Anyway. I do have a AMD CPU which should run the code in openCL mode or as the host device however when I use the "default_selector" it selects the unsupported GPU. Also please confirm the DPC++ compiler in oneAPI toolkit is the same compiler as is contained in this repo correct?

**Comment by Michoumichmich** [comment]
Hi, I'm not an Intel employee so I cannot confirm anything regarding the content of oneAPI toolkits. I'm just working with both CUDA and HIP back-ends. 
AMD is dropping OpenCL support and SYCL 2020 is moving away from OpenCL too, that' why I believe there's not much work done on supporting these backends in DPC++. 
To change the behaviour of the default selector, you can use [SYCL_DEVICE_FILTER](https://intel.github.io/llvm-docs/EnvironmentVariables.html#sycl_device_filter)

**Comment by alexbatashev** [comment]
> given that AMD includes openCL 2.0 in their drivers...

As far as I can tell, AMD reports OpenCL 2.2 platform, but the driver does not actually implement any of its features, including SPIR-V support, which is the default path for our OpenCL plugin. I’m not sure, though, if you can somehow run it in AOT mode, I never tried it myself.

**Comment by MrSidims** [comment]
I believe, that issue here is that AMD backend supports only 'legacy' debug info and doesn't support https://www.khronos.org/registry/SPIR-V/specs/unified1/OpenCL.DebugInfo.100.html . So in theory we can do something like this https://github.com/intel/llvm/pull/3991/files though I can not imagine, how we can change debug info flag for JIT compilation without breaking other targets, that supports newer version of debug info. Note, OpenCL.DebugInfo.100 is not Intel extension, but Khronos core feature.

**Comment by MrSidims** [comment]
For reference: there is a repo of the project used to [translate](https://github.com/KhronosGroup/SPIRV-LLVM-Translator) LLVM IR to SPIR-V and backwards. Both [master](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/lib/SPIRV/libSPIRV/SPIRVModule.cpp) and the oldest [release branch ](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/llvm_release_70/lib/SPIRV/libSPIRV/SPIRVModule.cpp) contains different code then "InvalidBuiltinSetName: Expects OpenCL.std. Actual is OpenCL.DebugInfo.100 [Src: ......\libSPIRV\SPIRVModule.cpp:594 SPIRVBuiltinSetNameMap::rfind(BuiltinSetName, &BuiltinSet) ]" (instead the check that is firing is placed on 798 line on master branch). So AMD uses custom version of the translator and you'd better to ask them to support new debug info.

**Comment by dahubley** [comment]
From what I'm gathering from this is AMD is posting that is compliant with openCL 2.x but does not actually implement the entire standard. In this case it seems this is an AMD issue rather than a DPC++ one. Generally I tend to believe when someone says they're complaint with a standard but I guess that is false optimism.

**Comment by dahubley** [comment]
> Hi, I'm not an Intel employee so I prefer not to comment on the content of the oneAPI toolkits. AMD is dropping OpenCL support and SYCL 2020 is moving away from OpenCL too, that' why I believe there's not much work done on supporting these backends in DPC++. To change the behaviour of the default selector, you can use [SYCL_DEVICE_FILTER](https://intel.github.io/llvm-docs/EnvironmentVariables.html#sycl_device_filter).

@Michoumichmich are ROCm and CUDA replacing the openCL backends?

**Comment by Michoumichmich** [comment]
> > Hi, I'm not an Intel employee so I prefer not to comment on the content of the oneAPI toolkits. AMD is dropping OpenCL support and SYCL 2020 is moving away from OpenCL too, that' why I believe there's not much work done on supporting these backends in DPC++. To change the behaviour of the default selector, you can use [SYCL_DEVICE_FILTER](https://intel.github.io/llvm-docs/EnvironmentVariables.html#sycl_device_filter).
> 
> @Michoumichmich are ROCm and CUDA replacing the openCL backends?

Yes, and Intel added as is still working on "Level-Zero" for their GPUs in addition to OpenCL.  There are several OpenCL limitations it allows to resolve, such as the absence of sub-groupe/warps.  Unfortunately there's no ROCm on Windows

**Comment by MrSidims** [comment]
>> From what I'm gathering from this is AMD is posting that is compliant with openCL 2.x but does not actually implement the entire standard.

Guess, it's too strong claim saying, that AMD doesn't support OpenCL 2.x since the issue is only with debug version. I can suggest to try following W/A and see if it works:
1. add '-v' (stands to verbose) to whatever compilation command you are using (dpcpp or clang++ -fsycl...) and print the output in a different file;
2. find an option 'spirv-debug-info-version' and replace 'ocl-100' with 'legacy' like [here](https://github.com/intel/llvm/pull/3991/files);
3. compile using the modified file as a compilation string.

If it works - I suggest to ask AMD to support ocl-100 debug info in SPIR-V compilation flow, if it does not - well, that's another story and issue to debug.

**Comment by AerialMantis** [comment]
Hi @dahubley, for AMD GPUs there is the HIP backend for AMD GPU support in DPC++, which is currently experimental and supported on Linux only. There are instructions for how to build with the HIP backend on the DPC++ getting started guide (https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-hip-amd).

**Comment by dahubley** [comment]
Thanks for all the very helpful support. I have one more point of confusion. Why does sycl list the GFX902 integrated graphics card in my laptop and attempt to use it if the backend doesn't support it. I would like to be able to use the default selector and have code dynamically pick the best platform to use. Right now default selector picks the AMD graphics card and crashes. That seems like undesirable behavior.

**Comment by Michoumichmich** [comment]
> Thanks for all the very helpful support. I have one more point of confusion. Why does sycl list the GFX902 integrated graphics card in my laptop and attempt to use it if the backend doesn't support it. I would like to be able to use the default selector and have code dynamically pick the best platform to use. Right now default selector picks the AMD graphics card and crashes. That seems like undesirable behavior.

I have the same issue on Linux as DPC++ is picking up the OpenCL and HIP backends for the integrated GFX902 but defaulting the OpenCL which does not work. That's particularly confusing as the SYCL code, queries,... works fine until you submit the kernel.

**Comment by alexbatashev** [comment]
> > Thanks for all the very helpful support. I have one more point of confusion. Why does sycl list the GFX902 integrated graphics card in my laptop and attempt to use it if the backend doesn't support it. I would like to be able to use the default selector and have code dynamically pick the best platform to use. Right now default selector picks the AMD graphics card and crashes. That seems like undesirable behavior.
> 
> I have the same issue on Linux as DPC++ is picking up the OpenCL and HIP backends for the integrated GFX902 but defaulting the OpenCL which does not work. That's particularly confusing as the SYCL code, queries,... works fine until you submit the kernel.

You can exclude certain devices from search order completely with SYCL_DEVICE_ALLOWLIST. See https://github.com/intel/llvm/blob/22474664d3a1840015e11be8d9a65f708f1fe42d/sycl/source/detail/config.def#L15 and https://intel.github.io/llvm-docs/EnvironmentVariables.html#sycl-device-allowlist

You can either put it to sycl.conf or use as env variable.
