### ISSUE TITLE
[SYCL] Using -isystem /usr/include makes <CL/sycl.hpp> unusable

### ISSUE THREAD

**Issue by krasznaa** [intel/llvm#4940]
# Describe the bug

In a fairly complicated CMake based build I ended up in a situation where the build system tries to add `-isystem /usr/include` to the compilation of one of my "SYCL source files" in order to provide it with the Boost headers. (It seems to be a bug in CMake itself that this happens. Since CMake normally doesn't do this. It only shows up in a very particular build configuration.)

When that flag is on the command line, I get a build failure like:

```
In file included from /data/ssd-1tb/projects/traccc/traccc/device/sycl/src/seeding/doublet_counting.sycl:8:
In file included from /data/ssd-1tb/projects/traccc/traccc/device/sycl/include/sycl/seeding/doublet_counting.hpp:10:
In file included from /home/krasznaa/software/intel/clang/nightly-20211110/x86_64-ubuntu2004-gcc9-opt/bin/../include/sycl/CL/sycl.hpp:11:
In file included from /home/krasznaa/software/intel/clang/nightly-20211110/x86_64-ubuntu2004-gcc9-opt/bin/../include/sycl/CL/sycl/accessor.hpp:12:
In file included from /home/krasznaa/software/intel/clang/nightly-20211110/x86_64-ubuntu2004-gcc9-opt/bin/../include/sycl/CL/sycl/atomic.hpp:11:
In file included from /home/krasznaa/software/intel/clang/nightly-20211110/x86_64-ubuntu2004-gcc9-opt/bin/../include/sycl/CL/__spirv/spirv_ops.hpp:13:
In file included from /home/krasznaa/software/intel/clang/nightly-20211110/x86_64-ubuntu2004-gcc9-opt/bin/../include/sycl/CL/sycl/detail/stl_type_traits.hpp:12:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/iterator:64:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ostream:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ios:42:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/ios_base.h:41:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/locale_classes.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/string:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:6493:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/string_conversions.h:41:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cstdlib:75:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
```

# To Reproduce

You can pretty much just use the following dummy file:

```c++
#include <CL/sycl.hpp>

int main() {
   return 0;
}
```

And then compile it with:

```
[bash][Legolas]:dpcpp_boost_error > source ~/software/intel/oneapi-2021.4.0/setvars.sh 
 
:: initializing oneAPI environment ...
   bash: BASH_VERSION = 5.0.17(1)-release
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: intelpython -- latest
:: ipp -- latest
:: ippcp -- latest
:: ipp -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: vpl -- latest
:: vtune -- latest
:: oneAPI environment initialized ::
 
[bash][Legolas]:dpcpp_boost_error > more boost_test.cpp 

#include <CL/sycl.hpp>

int main() {
   return 0;
}
[bash][Legolas]:dpcpp_boost_error > dpcpp -isystem /usr/include boost_test.cpp 
In file included from boost_test.cpp:2:
In file included from /home/krasznaa/software/intel/oneapi-2021.4.0/compiler/2021.4.0/linux/bin/../include/sycl/CL/sycl.hpp:11:
In file included from /home/krasznaa/software/intel/oneapi-2021.4.0/compiler/2021.4.0/linux/bin/../include/sycl/CL/sycl/accessor.hpp:12:
In file included from /home/krasznaa/software/intel/oneapi-2021.4.0/compiler/2021.4.0/linux/bin/../include/sycl/CL/sycl/atomic.hpp:11:
In file included from /home/krasznaa/software/intel/oneapi-2021.4.0/compiler/2021.4.0/linux/bin/../include/sycl/CL/__spirv/spirv_ops.hpp:13:
In file included from /home/krasznaa/software/intel/oneapi-2021.4.0/compiler/2021.4.0/linux/bin/../include/sycl/CL/sycl/detail/stl_type_traits.hpp:12:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/iterator:64:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ostream:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ios:42:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/ios_base.h:41:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/locale_classes.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/string:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:6493:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/string_conversions.h:41:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cstdlib:75:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
[bash][Legolas]:dpcpp_boost_error >
```

# Environment (please complete the following information):

- OS: Ubuntu 20.04
- Target device and vendor: Irrelevant
- DPC++ version: 2021.4.0

```
Intel(R) oneAPI DPC++/C++ Compiler 2021.4.0 (2021.4.0.20210924)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/krasznaa/software/intel/oneapi-2021.4.0/compiler/2021.4.0/linux/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

- Dependencies version: Irrelevant

# Additional context

As I wrote above, CMake adding `-isystem /usr/include` to my compile command is definitely not right. Yet, if DPC\+\+ would not die because of it, that would certainly help. :wink:

**Comment by krasznaa** [comment]
Since this ticket has not received any attention yet, let me ping @ivorobts on it... :wink:

**Comment by ivorobts** [comment]
@krasznaa, I don't think it is a bug of the dpcpp driver. I can see same behaviour with clang itself.
Note that there are multiple stdlib.h implementations in /usr/include, e.g. in /usr/include/c++/9/stdlib.h and /usr/include/stdlib.h (and some other paths too).  I reproduced what you get:
```
$ dpcpp -isystem /usr/include test.cpp
In file included from test.cpp:1:
In file included from /opt/intel/oneapi/2022.1.1/compiler/2022.0.1/linux/bin-llvm/../include/sycl/CL/sycl.hpp:11:
In file included from /opt/intel/oneapi/2022.1.1/compiler/2022.0.1/linux/bin-llvm/../include/sycl/CL/sycl/accessor.hpp:12:
In file included from /opt/intel/oneapi/2022.1.1/compiler/2022.0.1/linux/bin-llvm/../include/sycl/CL/sycl/atomic.hpp:11:
In file included from /opt/intel/oneapi/2022.1.1/compiler/2022.0.1/linux/bin-llvm/../include/sycl/CL/__spirv/spirv_ops.hpp:13:
In file included from /opt/intel/oneapi/2022.1.1/compiler/2022.0.1/linux/bin-llvm/../include/sycl/CL/sycl/detail/stl_type_traits.hpp:12:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/iterator:64:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ostream:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ios:42:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/ios_base.h:41:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/locale_classes.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/string:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:6493:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/string_conversions.h:41:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cstdlib:75:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
```
But with the proper path (found it from the compiler driver internals via -# option) it works fine
```
$ dpcpp -isystem /usr/include/c++/9/ test.cpp
$
```
Note that include_next within cstdlib is used to find the stdlib. By adding the path via -isystem you do change dafaults and the order of found paths to this header (it matters).

**Comment by krasznaa** [comment]
Yeah, I imagined that `-isystem` does a bit more than what I'd want to use it for. From my perspective I just use `-isystem` over `-I` for code that I don't control to not see any possible warnings from those headers. This is why CMake also uses it out of the box for "imported targets".

I believe the issue I have in my build is that since I declare DPC\+\+ as the compiler for a separate language, CMake doesn't exclude `/usr/include` from the list of include paths that it would give to the compiler. It seems that for C\+\+ compilers it does filter that path out on Linux. I imagine exactly to avoid these types of issues...

It's still a pity that one can torpedo Clang in such an unexpected way. 🤔  But I guess I should be complaining on their issue tracker about that then...

**Comment by alexbatashev** [comment]
> Yeah, I imagined that `-isystem` does a bit more than what I'd want to use it for. From my perspective I just use `-isystem` over `-I` for code that I don't control to not see any possible warnings from those headers. This is why CMake also uses it out of the box for "imported targets".
> 
> I believe the issue I have in my build is that since I declare DPC++ as the compiler for a separate language, CMake doesn't exclude `/usr/include` from the list of include paths that it would give to the compiler. It seems that for C++ compilers it does filter that path out on Linux. I imagine exactly to avoid these types of issues...
> 
> It's still a pity that one can torpedo Clang in such an unexpected way. 🤔 But I guess I should be complaining on their issue tracker about that then...

My understanding is that these options affect the ordering of include directories. Which in turn affects `#include_next` directive. So, that is sad, but expected.

**Comment by valassi** [comment]
@krasznaa , for what is worth, I just had a totally bizarre situation (https://sft.its.cern.ch/jira/browse/SPI-1933) with clang13: a simple file compiles ok if I build it with "clang++", while it fails to find a system header if I build it with "<full path>/clang++" (I even just tried "`clang++`"). Debugging with "-v", the difference between the two is that in the first case I get a printout `Found candidate GCC installation:`, in the second case I do not. Browsing a bit I ended up on https://clang.llvm.org/docs/Modules.html#includes-as-imports, which discusses "#include_next" that we discussed this morning. I am having a hard time understanding what is going on, but IMHO my issue looks like a bug in the clang++ executable itself, or in the way it was installed. Maybe this rings some bell for you. If ir is totally irellevant, please ignore!

**Comment by krasznaa** [comment]
It may be best to just close this one... :thinking: Since the issue comes from the base llvm/clang code, I don't think much should be done in this repository about it. And in any case, I worked around this issue in our CMake based build system a long time ago... (But I'd leave the closing of the ticket to somebody from the Intel team. In case you guys may want to pursue this issue after all.)
