### ISSUE TITLE
[SYCL] double-precision recip

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#4954]
Only single-precision recip seems supported by SYCL.

https://stackoverflow.com/questions/63101094/is-there-a-cuda-equivalent-of-native-recip-in-opencl#63101095

**Comment by alexbatashev** [comment]
@zjin-lcf I suggest you raise this issue in https://github.com/KhronosGroup/SYCL-Docs

I'm going to close this, as this is more of specification issue, rather than a particular implementation.

Tagging @keryell @jbrodman @Pennycook

**Comment by zjin-lcf** [comment]
Tagging may have raised the issue already.
