### ISSUE TITLE
[SYCL][CUDA] Missing double atomic add with nd_range

### ISSUE THREAD

**Issue by joeatodd** [intel/llvm#4968]
**Describe the bug**

When attempting to compile an `nd_range` `sycl::reduction` which sums doubles, I get the compilation error described below. Any of the following prevents the error:
 - replace `nd_range` with `range`
 - replace `double` with `float`
 - remove `-DSYCL_USE_NATIVE_FP_ATOMICS` flag 
 - specifying the cuda architecture with: `-Xsycl-target-backend --cuda-gpu-arch=sm_86`
 
**To Reproduce**

``` c++
#include <CL/sycl.hpp>

int main(){

sycl::queue myQueue{sycl::gpu_selector()};
double sum = 0.0;
{
sycl::buffer<double> sum_buff(&sum, 1);

sycl::nd_range<3> myRange(sycl::range<3>{32,32,32},sycl::range<3>{1,1,32});

myQueue.submit([&](sycl::handler& cgh){
    cgh.parallel_for(myRange,
       sycl::reduction(sum_buff, cgh, std::plus<double>()),
       [=](sycl::nd_item<3> item, auto& local_sum) {
         local_sum.combine(static_cast<double>(item.get_local_id(2)));
       });
 });
}
}
```
Compile with:
``` bash
clang++ -fsycl -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda -DSYCL_USE_NATIVE_FP_ATOMICS test_atomic.cpp -o test.o
```
Throws a compilation error:
```
fatal error: error in backend: Cannot select: t5: f64,ch = AtomicLoadFAdd<(volatile load store monotonic (s64) on %ir.add.ptr.i, addrspace 1)> t0, t4, t2
  t4: i64,ch = CopyFromReg t0, Register:i64 %0
    t3: i64 = Register %0
  t2: f64,ch = CopyFromReg t0, Register:f64 %31
    t1: f64 = Register %31
In function: _ZTSZN2cl4sycl3ext6oneapi6detail22reduCGFuncImplAtomic64INS0_6detail9auto_nameEZZ4mainENKUlRNS0_7handlerEE_clES8_EUlNS0_7nd_itemILi3EEERT_E_Li3ENS3_14reduction_implIdSt4plusIdELi1ELb0ELNS0_6access11placeholderE1EEEEENSt9enable_ifIXsrT2_22has_atomic_add_float64EvE4typeES8_T0_RKNS0_8nd_rangeIXT1_EEERSM_NSM_16rw_accessor_typeEEUlSB_E_
```

**Environment (please complete the following information):**

- Linux
- GeForce RTX 3060
- DPC++ version: [sycl-nightly/20211102]

**Comment by steffenlarsen** [comment]
Since changing the CUDA arch removes the issue my money is on this using an operation that requires a minimum arch version. Since it is complaining about a `AtomicLoadFAdd` I imagine the instruction it is unable to select is `atom.add.f64` which, according to the [PTX ISA](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#parallel-synchronization-and-communication-instructions-atom), requires `sm_60`. I believe the CUDA backend currently defaults to `sm_50`, which may explain the issue you're seeing.

**Comment by joeatodd** [comment]
Aha, yeah that's probably right. I suppose this can be closed then, as it's not really a bug *per se*. Thanks a lot @steffenlarsen
