### ISSUE TITLE
dpcpp_compiler/lib/oclfpga/fpgavars.sh: No such file or directory

### ISSUE THREAD

**Issue by JinJieGan** [intel/llvm#4981]
**Describe the bug**

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. Include code snippet as short as possible
2. Specify the command which should be used to compile the program
3. Specify the comment which should be used to launch the program
4. Indicate what is wrong and what was expected

**Environment (please complete the following information):**

- OS: ubuntu18
- Target device and vendor: [e.g. Intel GPU]
- DPC++ version: 2021.11.17, dpcpp-compiler.tar.gz
- Dependencies version: [e.g. low-level runtime versions (like NEO 20.04)]

**Additional context**
When I download dpcpp-compiler.tar.gz and run command
 `tar -zxvf dpcpp-compiler.tar.gz` 
 `cd dpcpp_compiler`
 `source startup.sh`
I got the error message: 
`-bash: dpcpp_compiler/lib/oclfpga/fpgavars.sh: No such file or directory`
If I wanna use compiler , what should I do next?

**Comment by zjin-lcf** [comment]
Could we copy and paste the following in a terminal ?

export SYCL_BUNDLE_ROOT=$(realpath $(dirname "${BASH_SOURCE[0]}"))
export PATH=$SYCL_BUNDLE_ROOT/bin:$PATH
export CPATH=$SYCL_BUNDLE_ROOT/include:$CPATH
export LIBRARY_PATH=$SYCL_BUNDLE_ROOT/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$SYCL_BUNDLE_ROOT/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$SYCL_BUNDLE_ROOT/linux/lib/x64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$SYCL_BUNDLE_ROOT/lib/oclgpu:$LD_LIBRARY_PATH

**Comment by JinJieGan** [comment]
> Could we copy and paste the following in a terminal ?
> 
> export SYCL_BUNDLE_ROOT=$(realpath $(dirname "${BASH_SOURCE[0]}")) export PATH=$SYCL_BUNDLE_ROOT/bin:$PATH export CPATH=$SYCL_BUNDLE_ROOT/include:$CPATH export LIBRARY_PATH=$SYCL_BUNDLE_ROOT/lib:$LIBRARY_PATH export LD_LIBRARY_PATH=$SYCL_BUNDLE_ROOT/lib:$LD_LIBRARY_PATH export LD_LIBRARY_PATH=$SYCL_BUNDLE_ROOT/linux/lib/x64:$LD_LIBRARY_PATH export LD_LIBRARY_PATH=$SYCL_BUNDLE_ROOT/lib/oclgpu:$LD_LIBRARY_PATH

I delete the command in startup.sh about fpga  , run again and succeed, same to your solution.
thanks.

**Comment by AlexeySachkov** [comment]
> When I download dpcpp-compiler.tar.gz and run command
tar -zxvf dpcpp-compiler.tar.gz
cd dpcpp_compiler
source startup.sh
I got the error message:
-bash: dpcpp_compiler/lib/oclfpga/fpgavars.sh: No such file or directory
If I wanna use compiler , what should I do next?

@JinJieGan, simply ignore the error and use DPC++ compiler. The script failed to set up paths for FPGA emulator, but the compiler itself is configured correctly.

@vladimirlaz, @wanyaman, can we update the script so it checks for the existence of FPGA emulator before trying to use vars script from it?

**Comment by vladimirlaz** [comment]
@AlexeySachkov I have no idea where startup.sh comes from.
@tfzhu do you have any clue?

**Comment by JinJieGan** [comment]
> @AlexeySachkov I have no idea where startup.sh comes from. @tfzhu do you have any clue?
Hi buddy,
I download the tar.gz file from this link [https://github.com/intel/llvm/releases/tag/sycl-nightly%2F20211117](url).
file name is `dpcpp-compiler.tar.gz`.
best wishes.

**Comment by tfzhu** [comment]
> > @AlexeySachkov I have no idea where startup.sh comes from. @tfzhu do you have any clue?
> > Hi buddy,
> > I download the tar.gz file from this link [https://github.com/intel/llvm/releases/tag/sycl-nightly%2F20211117](url).
> > file name is `dpcpp-compiler.tar.gz`.
> > After decompression , startup.sh will be in folder `dpcpp_compiler`
> > best wishes.

@DoyleLi is working on a fix.

**Comment by AlexeySachkov** [comment]
We do not seem to ship any `startup.sh` anymore - I will close this issue as not a problem.

However, I can imagine that the lack of such script is also a usability problem, but it should be reported and discussed separately
