### ISSUE TITLE
[SYCL][CUDA] only supports image with RGBA channel order 

### ISSUE THREAD

**Issue by jingwan2** [intel/llvm#4990]
**Describe the bug**
SYCL CUDA backend only supports image with RGBA channel order, other channel order leads to crash in cuda_piMemImageCreate 

**To Reproduce**
Compile below source code for cuda backend and run.

*Code*
>#include <CL/sycl.hpp>
#define SIZE 100
int main(int argc, char *argv[]) {
  sycl::queue q;
  sycl::range<1> r(SIZE);
  const auto channel_order = cl::sycl::image_channel_order::r;
  const auto channel_type = cl::sycl::image_channel_type::fp32;
  auto img = cl::sycl::image<1>(channel_order, channel_type, r);
  q.submit([&](cl::sycl::handler &cgh) {
     auto img_acc = img.template get_access<cl::sycl::float4, cl::sycl::access::mode::read>(cgh);
     cgh.parallel_for(r, [=](sycl::id<1> idx) {
     });
  });
  q.wait();
  return 0;
}

*Compile*
> clang++  -fsycl -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda-sycldevice sycl_test.cpp  -lOpenCL

*Run*
>SYCL_DEVICE_FILTER=CUDA:GPU ./a.out

**Environment (please complete the following information):**

- OS: [Linux]
- Target device and vendor: [NVIDIA GPU]
- DPC++ version: 
clang version 14.0.0 (https://github.com/intel/llvm.git 0b8cff452158f0b5234232857d5d9d71823230a2)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Additional context**
Log
>pi_die: cuda_piMemImageCreate only supports RGBA channel order
terminate called without an active exception
Aborted (core dumped)

**Comment by badross92** [comment]
I can confirm I'm getting similar error on Windows with anything besides RGBA : 

> die: piMemImageCreate: unsupported image format layout

**Environment:**
- OS: [Windows]
- Target device and vendor: [INTEL GPU]
- DPC++ version:
  Intel(R) oneAPI DPC++/C++ Compiler 2021.4.0 (2021.4.0.20210924)
  Target: x86_64-pc-windows-msvc
  Thread model: posix

**Comment by jchlanda** [comment]
Hi @jingwan2, @badross92 

Thank you for reaching out with your report. I've looked into the issue and believe that the sample code provided is invalid. DPC++ (PI CUDA backend of DPC++) implements SYCL 2020, which only allows the following image formats (note the new enum combining image order and channel type):

```cpp
enum class image_format : unsigned int {
  r8g8b8a8_unorm,
  r16g16b16a16_unorm,
  r8g8b8a8_sint,
  r16g16b16a16_sint,
  r32b32g32a32_sint,
  r8g8b8a8_uint,
  r16g16b16a16_uint,
  r32b32g32a32_uint,
  r16b16g16a16_sfloat,
  r32g32b32a32_sfloat,
  b8g8r8a8_unorm,
}
```
Please see section `4.7.3. Images` of the spec here: https://www.khronos.org/registry/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf for the details. This is a significant departure from SYCL 1.2.1 which allowed users to specify `image_channel_order` alongside `image_channel_type` (section `4.7.3 Images` here: https://www.khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf).

Saying that, there is obviously work required in DPC++ to update the image related interfaces and bring them to SYCL 2020, your sample clearly demonstrates the problem of the implementation only supporting SYCL 2020 while still allowing the interface of 1.2.1. Furthermore, from a quick look at the current implementation it looks like it would also fail with `b8g8r8a8_unorm`.

For now, the only solution for you would be to either pack 4 `R` channels into `r32g32b32a32_sfloat` or pad the `G`, `B` and `A` of the aforementioned format; either of which would require work in the kernel to reflect the format change.

**Comment by AerialMantis** [comment]
As this issue is due to using an image format not supported in SYCL 2020, we believe this issue can be closed. If you believe there is still an issue here please comment and we can re-open it, otherwise this issue could be raised as a new feature request for the CUDA backend.
