### ISSUE TITLE
Loop unroll behavior is not meet expectation of programmer.

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/llvm#5015]
For a code snippet, MAX_DIMS = 12.
```
#pragma unroll (MAX_DIMS)
     for (int dim = 0; dim < MAX_DIMS; ++dim) {
       if (dim == dims) {
         break;
```
```
#pragma unroll
     for (int dim = 0; dim < MAX_DIMS; ++dim) {
       if (dim == dims) {
         break;
```

Behave differently. Former will unroll as expected, but later won't unroll even when I specified -funroll-loop -unroll=16384. How should I force unroll?

**Comment by CaoZhongZ** [comment]
Or, What should I do to make ```#pragma unroll``` same as ```#pragma unroll (MAX_DIMS)```

**Comment by zjin-lcf** [comment]
Is there a compiler option that says a loop is unrolled ?  For example, -Minfo in nvc++.   

Thanks

**Comment by CaoZhongZ** [comment]
Many, ```-funroll-loop, -funroll=<number>```, etc. I add them all, seems not much difference.

**Comment by zjin-lcf** [comment]
Sorry, I tried to say that the compiler could produce compile-time message about whether a loop is unrolled or not.  So people don't need to look at lower-level codes.

**Comment by CaoZhongZ** [comment]
Oh, there is no warning message. Everything is fine except the unroll behaviors are different.
