### ISSUE TITLE
[SYCL] Program with both host_accessor and queue::wait stalls

### ISSUE THREAD

**Issue by pkeir** [intel/llvm#5164]
The program below stalls at the call to `queue::wait` with both oneAPI on Windows, and a CUDA build of llvm-sycl-nightly-20211124 on Ubuntu 21.04. I believe the program is valid, and should return with no output displayed. The command to build on Ubuntu is: `clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -fsycl-unnamed-lambda bug.cpp`

```cpp
#include <iostream>
#include <sycl/sycl.hpp>

// With the host_accessor declaration at A, this will stall at queue::wait (B)

int main(int argc, char *argv[])
{
  sycl::queue q;
  int x{};

  sycl::buffer<int, 1> buf{&x, 1};

  sycl::host_accessor ha{ buf, sycl::read_write };  // A

  q.submit([&](sycl::handler& cgh)
  {
    sycl::accessor acc{ buf, cgh, sycl::read_write };

    cgh.single_task([=]()
    {
      acc[0] = 42;
    });
  });

  std::cerr << "1\n";

  q.wait();  // B

  std::cerr << "2\n";

  return 0;
}
```

**Comment by alexbatashev** [comment]
Host accessors are blocking by design. You can’t simultaneously access buffers on both host and device.

**Comment by pkeir** [comment]
Thanks. Though I see some implementation variance from other vendors, I see now that this is as specified by Khronos: "Any command groups with requirements to the same memory object cannot execute until the host accessor is destroyed..." (from [here](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_synchronization_in_the_sycl_application).

**Comment by keryell** [comment]
I think this should not work if both accessors are read-only.
But I cannot remember whether we have finished processing this issue.
