### ISSUE TITLE
Mix of namespaces in headers causes build failures

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#5213]
In [the code](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/ext/oneapi/matrix/matrix-tensorcore.hpp#L54) there is `using namespace` in headers which causes mixture of namespcaes.
 As a C++ developer I wouldn't expect to see `using namespace` in the C++ code especially in library and/or headers that are used by multiple users.

see https://github.com/intel/llvm-test-suite/pull/659#issuecomment-1000132200

**Comment by bader** [comment]
@JackAKirk, see https://github.com/intel/llvm-test-suite/issues/666 for more details.
Please, do not forget to enable the test back when you fix the problem.

**Comment by JackAKirk** [comment]
@bader This issue is addressed in #5217
