### ISSUE TITLE
[AOT] Is it possible that doing AOT in compile stage instead of linking

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/llvm#5219]
For a large project the parallel building system will take advantage of this and make compile time shorter.

**Comment by CaoZhongZ** [comment]
Brought up again?

**Comment by AlexeySachkov** [comment]
I will tag @mdtoguchi and @sarnex here to reply. I believe that we should have this capability now

**Comment by mdtoguchi** [comment]
@AlexeySachkov is correct - this capability is available when using `-fno-sycl-rdc` when generating your object with `-c`.

compile:
`clang++ -fsycl -fsycl-targets=spir64_gen -Xsycl-target-backend "-device pvc" -fno-sycl-rdc -c file.cpp`
link:
`clang++ -fsycl file.o`

**Comment by AlexeySachkov** [comment]
@CaoZhongZ, I will close this as complete, but please let us know if you have any follow-up questions or encounter any bugs when you try the feature
