### ISSUE TITLE
Build error when SYCL_ENABLE_XPTI_TRACING is off

### ISSUE THREAD

**Issue by lforg37** [intel/llvm#5274]
**Describe the bug**

The sycl toolchain compilation fail if is not defined.
In `sycl/source/detail/xpti_registry.hpp`, inclusion of the xpti_trace_framework header is enabled only if the XPTI_ENABLE_INSTRUMENTATION macro is defined.

A `xpti::trace_event_data_t`  at line 101 is not protected by this macro.

This leads to a compilation error when trying to build the compiler without defining this macro, (when the cmake option SYCL_ENABLE_XPTI_TRACING is not set to ON).

**To Reproduce**
Configure and build without the `SYCL_ENABLE_XPTI_TRACING` cmake option enabled.

**Environment:**

- DPC++ version:  8677d5d562bb

**Comment by bader** [comment]
@lforg37, could you check if https://github.com/intel/llvm/commit/0cfec311666fece8122e4e5deb7a7af97820a1f8 fixes this issue, please?

**Comment by lforg37** [comment]
Sorry for missing the related PR.

On my system this commit does not solve the build issue (the issue with `sycl/source/detail/xpti_registry.hpp` stay the same).

**Comment by psamolysov-intel** [comment]
@bader @lforg37 I'm sorry, it's a bit strange but the code was built on my Windows machine. I've open a new PR #5289 to fix the found issue with the `XPTIRegistry::createTraceEvent` method, and tested the solution in a clean build, it seems to work.

**Comment by Michoumichmich** [comment]
On my side everything build but `buffer_impl.cpp` and it fails with:
```
/home/michel/sycl_workspace/llvm/sycl/source/detail/buffer_impl.cpp:40:3: error: incomplete type 'sycl::detail::XPTIRegistry' named in nested name specifier
  XPTIRegistry::bufferConstructorNotification(UserObj, CodeLoc);
  ^~~~~~~~~~~~~~
/home/michel/sycl_workspace/llvm/sycl/source/detail/global_handler.hpp:27:7: note: forward declaration of 'sycl::detail::XPTIRegistry'
class XPTIRegistry;
      ^
/home/michel/sycl_workspace/llvm/sycl/source/detail/buffer_impl.cpp:43:3: error: incomplete type 'sycl::detail::XPTIRegistry' named in nested name specifier
  XPTIRegistry::bufferDestructorNotification(UserObj);
  ^~~~~~~~~~~~~~
/home/michel/sycl_workspace/llvm/sycl/source/detail/global_handler.hpp:27:7: note: forward declaration of 'sycl::detail::XPTIRegistry'
class XPTIRegistry;
```
