### ISSUE TITLE
__builtin_sycl_unique_stable_name can't be used in non-sycl mode.

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/llvm#5345]
If try to use old style separate passes, we see following errors.

```
clang++ -std=c++17 -g -fsycl -fsycl-id-queries-fit-in-int -fsycl-default-sub-group-size=16 -D__SYCL_INTERNAL_API -fsycl-targets=spir64_gen -fsycl-device-only -Xclang -fsycl-int-header=main.dev.hpp -c -o main.dev.bc main.cpp
clang++ -std=c++17 -g -D__SYCL_UNNAMED_LAMBDA__ -I/home/caozhong/llvm/include/sycl -I/home/caozhong/llvm/include -c -o main.host.o -include main.dev.hpp main.cpp
In file included from <built-in>:1:
In file included from ./main.dev.hpp:4:
/home/caozhong/llvm/include/sycl/CL/sycl/detail/kernel_desc.hpp:101:63: error: 'T' does not refer to a value
  static constexpr auto n = __builtin_sycl_unique_stable_name(T);
```

**Comment by erichkeane** [comment]
This is a known limitation of the builtin, and was done at the request of the Clang maintainer.  While it might potentially be useful in other modes, we don't support it in non-SYCL builds.  I'd suggest putting -fsycl-host (or however it is spelled? (@bader  @mdtoguchi  can help with that) on the host build if you want to use it.

**Comment by bader** [comment]
-fsycl-host is still a SYCL mode, I guess. :)

Probably the right fix is using `__has_builtin` function in the integration header to check if `__builtin_sycl_unique_stable_name` is supported by the compiler. If not, we can give a more user-friendly error message that "unnamed lambda" feature is not supported in this configuration.

**Comment by CaoZhongZ** [comment]
I looked for sycl host only flags but failed to find it. There is a ```--cuda-host-only ``` but no ```--sycl-host-onlly```

or -fsycl-host
```clang-14: error: unknown argument: '-fsycl-host'```

Also, there is problem in old named lambda feature when I passed in named functors instead of lambda. it still complain I don't give a name.

**Comment by CaoZhongZ** [comment]
I see, -Xclang -fsycl-is-host. That's hard to find :)
