### ISSUE TITLE
fatal error: va/va.h: No such file or directory

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#5351]
When compiling the SYCL compiler with the python script, I got the error. Could you reproduce that ? Thanks.

/path/to/objdir/tools/sycl/plugins/esimd_emulator/cm-emu-prefix/src/cm-emu/cmake/../common/linux/cm_include.h:22:10: fatal error: va/va.h: No such file or directory

**Comment by bader** [comment]
@zjin-lcf, https://github.com/intel/llvm/commit/50ccce9e9b1e6412097aab8b997e36a5673246f7 added new pre-requisites for the environment. You can either install required libraries (according to https://github.com/intel/llvm/commit/6f17b18e30d0572948bdd6784c5bcc6f9dec08f1 they are libffi-dev, libva-dev and libtool) or pass `--disable-esimd-emulator` to the configure.py script.

**Comment by zjin-lcf** [comment]
I will disable the emulator. 
Thanks for updating https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md.

**Comment by bader** [comment]
Good point. @dongkyunahn-intel, could you update GetStartedGuide, please? It uses old option name `--enable-esimd-cpu-emulation`.

**Comment by dongkyunahn-intel** [comment]
PR posted : https://github.com/intel/llvm/pull/5352
