### ISSUE TITLE
DPC++ build failure due to #5058 (ESIMD cm-emu configure step)

### ISSUE THREAD

**Issue by JackAKirk** [intel/llvm#5360]
After https://github.com/intel/llvm/pull/5058 DPC++ build is failing during the cm-emu configure step.  A temporary fix is to set `sycl_build_pi_esimd_emulator = 'OFF'` in llvm/buildbot/configure.py.  This definitely affects the CUDA backend but may well affect other backends.

**Output**

```
[584/3182] Performing download step (git clone) for 'cm-emu'
Cloning into 'cm-emu'...
Note: switching to 'c19234cea13bdfc32b5ed9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at c19234c CM EMU Release, v2021-12-09 (#112)
[601/3182] Performing configure step for 'cm-emu'
FAILED: tools/sycl/plugins/esimd_emulator/cm-emu-prefix/src/cm-emu-stamp/cm-emu-configure 
cd /home/jackkirk/jackLLVM/llvm/build/tools/sycl/plugins/esimd_emulator/cm-emu_build && /usr/bin/cmake -DLIBVA_INSTALL_PATH=/usr -D__SYCL_EXPLICIT_SIMD_PLUGIN__=true -DCMAKE_INSTALL_PREFIX=/home/jackkirk/jackLLVM/llvm/build/tools/sycl/plugins/esimd_emulator/cm-emu_install -GNinja /home/jackkirk/jackLLVM/llvm/build/tools/sycl/plugins/esimd_emulator/cm-emu-prefix/src/cm-emu && /usr/bin/cmake -E touch /home/jackkirk/jackLLVM/llvm/build/tools/sycl/plugins/esimd_emulator/cm-emu-prefix/src/cm-emu-stamp/cm-emu-configure
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LibFFI (missing: LibFFI_LIBRARY LibFFI_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibFFI.cmake:24 (find_package_handle_standard_args)
  libcm/CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by bader** [comment]
@pvchupin, @kbobrovs, FYI.

**Comment by dongkyunahn-intel** [comment]
@JackAKirk , where does this problem happen? If local, you can try to install `libffi-dev` package (ubuntu). I'm updating documentation for requirements (https://github.com/intel/llvm/pull/5352).

Please note that this failure can be prevented with `--disable-esimd-emulator` option for `configure.py`. It has same effect as `sycl_build_pi_esimd_emulator = 'OFF'`.

**Comment by JackAKirk** [comment]
> @JackAKirk , where does this problem happen? If local, you can try to install `libffi-dev` package (ubuntu). I'm updating documentation for requirements (#5352).
> 
> Please note that this failure can be prevented with `--disable-esimd-emulator` option for `configure.py`. It has same effect as `sycl_build_pi_esimd_emulator = 'OFF'`.

Yes locally.  I have `libffi-dev` installed also.  I have tried it on two separate systems now with the same result.

**Comment by dongkyunahn-intel** [comment]
Did you remove `$LLVM_BUILD_ROOT/CMakeCache.txt`? I would suggest running following command after applying some changes regarding CM_EMU build.

`> rm -rf $LLVM_BUILD_ROOT/install/* $LLVM_BUILD_ROOT/CMakeCache.txt $LLVM_BUILD_ROOT/tools/sycl/*`

Basically, required packages are `libffi-dev` and `libva-dev` (PR for infra update : https://github.com/intel/llvm/pull/5212). If you don't need esimd emulation, please try to use `--disable-esimd-emulator` command line option like my previous comment.

**Comment by JackAKirk** [comment]
> Did you remove `$LLVM_BUILD_ROOT/CMakeCache.txt`? I would suggest running following command after applying some changes regarding CM_EMU build.
> 
> `> rm -rf $LLVM_BUILD_ROOT/install/* $LLVM_BUILD_ROOT/CMakeCache.txt $LLVM_BUILD_ROOT/tools/sycl/*`
> 
> Basically, required packages are `libffi-dev` and `libva-dev` (PR for infra update : #5212). If you don't need esimd emulation, please try to use `--disable-esimd-emulator` command line option like my previous comment.

I had tried a complete rebuild (by rm -rf the build folder).  For myself I do not need to build esimd emulation, so #5366 should solve the issue for me.  Thanks

**Comment by bader** [comment]
https://github.com/intel/llvm/pull/5366/ is merged. @JackAKirk, can you confirm that we can close that issue, please?

**Comment by JackAKirk** [comment]
> #5366 is merged. @JackAKirk, can you confirm that we can close that issue, please?

Yes everything builds fine now by default, thanks! I think that it is fine to close this issue.
