### ISSUE TITLE
building sycl code for CUDA with Cmake fails

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#5396]
**Describe the bug**
using sycl-tool-chain (compiled CUDA) to compile code with CMake failed.
Building DPC++ toolchain with support for NVIDIA CUDA is correctl with testing simple code
 testing output as follow:
![image](https://user-images.githubusercontent.com/22990858/151093335-5cdf301d-af39-49a7-a5e5-1040374b5e6e.png)

I wanted to build this project with cmake,so I write the CMakeLists.txt as follow:
```cmake_minimum_required(VERSION 2.8.12)

set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")
set(CMAKE_CXX_STANDARD 17)

project(simple-sycl-app)

set(DPCPP_HOME "/home/wzy/sycl_workspace")
set(DPCPP_SYCL_HOME "${DPCPP_HOME}/llvm/build-cuda-debug")

message(STATUS "dpcpp_home : "${DPCPP_HOME})
message(STATUS "dpcpp_cuda_sycl_home : "${DPCPP_SYCL_HOME})


set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")

add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)

aux_source_directory(. DIR_SRCS)
add_executable(simple-sycl-app ${DIR_SRCS})
target_link_libraries(simple-sycl-app)

```
Then I run
> mkdir build & cd build
> cmake ..
> make
I get the Error as follow
![image](https://user-images.githubusercontent.com/22990858/151094497-b9784214-48c2-4e37-ab5c-0f9ec0b22757.png)

**Environment (please complete the following information):**

- OS: [/Linux]
- Target device and vendor: [e.g. Nvidia GPU]
- DPC++ version: [clang++ 14.0.0`]
- 

**Additional context**

**Comment by alexbatashev** [comment]
You probably don't have libsycl.so path in your LD_LIBRARY_PATH

**Comment by wangzy0327** [comment]
I tried compile and link the project by cmake.
modified file as follow:
![image](https://user-images.githubusercontent.com/22990858/151161864-1a423da9-6d9e-4c0d-b9a3-f5818a924203.png)

But when I run binary warpped file, the outputs shows terminated as follows:
![image](https://user-images.githubusercontent.com/22990858/151161651-42039e68-7600-4275-a19d-2516b201c40d.png)

**Comment by alexbatashev** [comment]
@wangzy0327 CMake splits compilation and linking steps. You also need to pass -fsycl when linking the binary

**Comment by wangzy0327** [comment]
> @wangzy0327 CMake splits compilation and linking steps. You also need to pass -fsycl when linking the binary
Ok . it is correct by modifing link symbol
![image](https://user-images.githubusercontent.com/22990858/151164502-1bdb5ece-ffed-418e-8865-2ee15ec6ba0d.png)
![image](https://user-images.githubusercontent.com/22990858/151164635-6806d086-2133-4071-bf5a-77d221ac4ea9.png)

**Comment by alexbatashev** [comment]
@wangzy0327 it appears your issue is resolved now. I'm closing this issue, please, re-open if you disagree.
