### ISSUE TITLE
[CUDA] Atomic fetch_add call cannot be inlined

### ISSUE THREAD

**Issue by anton-v-gorshkov** [intel/llvm#5429]
**Describe the bug**
DPC++ compiler for NVidia PTX backend cannot inline atomic_ref::fetch_add function that may lead to ~20% performance degradation vs. nvcc on the same device.

**To Reproduce**
[histograms.zip](https://github.com/intel/llvm/files/7970349/histograms.zip)

Steps to reproduce:
```sh
$ unzip histograms.zip
$ cd histograms/cuda
$ export PATH=$PATH:/usr/local/cuda/bin
$ ./build.sh
$ ./hist
Size   23013896 => min: 2.516 ms; avg: 2.637 ms; max: 3.149 ms
$ cd ../dpcpp
$ source <intel/llvm compiler>
$ ./build.sh
$ ./hist
Size   23013896 => min: 2.949 ms; avg: 3.155 ms; max: 3.767 ms
```
_**Performance degradation is about 17-20%.**_

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- Target device and vendor: NVidia RTX2070
- DPC++ version: clang version 14.0.0 (https://github.com/intel/llvm e15ac50231ddd6fb0a68bae5c9351f5f93114e28)
- Dependencies version: CUDA 11.4

**Additional context**
It was found based on initial investigation, that the major difference between these two binaries are that fact that in case of nvcc atomic operation is fully inlided while for DPC++/clang it is not inlined, call/ret approach is used instead that leads to more instructions executed and higher number of branches.

For DPC++ it was found, that `__spirv_AtomicFAddEXT` function call is not inlined (in spriv.hpp):
```cpp
template <typename T, access::address_space AddressSpace>
__attribute__((always_inline)) typename detail::enable_if_t<std::is_floating_point<T>::value, T>
AtomicFAdd(multi_ptr<T, AddressSpace> MPtr, memory_scope Scope,
           memory_order Order, T Value) {
  auto *Ptr = MPtr.get();
  auto SPIRVOrder = getMemorySemanticsMask(Order);
  auto SPIRVScope = getScope(Scope);
  return __spirv_AtomicFAddEXT(Ptr, SPIRVScope, SPIRVOrder, Value); // <--- HERE
}
```

**Comment by Michoumichmich** [comment]
Got the same issue!

**Comment by Michoumichmich** [comment]
These are not inlined: 
```
_Z19__spirv_AtomicStorePU3AS1jN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagEj
_Z18__spirv_AtomicLoadPU3AS1KjN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagE
_Z18__spirv_AtomicIAddPU3AS1jN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagEj
```

**Comment by P-Jensen** [comment]
For the AtomicFAdd the problem can be fixed by adding __attribute__((always_inline)) to the definition.  Like so:

```
diff --git a/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h b/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
index 66e2b890bf14..9a0d1326bdb1 100644
--- a/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
+++ b/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
@@ -78,9 +78,9 @@ Memory order is stored in the lowest 5 bits */

 #define __CLC_NVVM_ATOMIC(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,    \
                           NAME_MANGLED)                                        \
-  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
+__attribute__((always_inline))  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
                          NAME_MANGLED, __global, AS1, _global_)                \
-  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
+__attribute__((always_inline))  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
                          NAME_MANGLED, __local, AS3, _shared_)

 #endif

```

**Comment by Michoumichmich** [comment]
> For the AtomicFAdd the problem can be fixed by adding **attribute**((always_inline)) to the definition. Like so:
> 
> ```
> diff --git a/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h b/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
> index 66e2b890bf14..9a0d1326bdb1 100644
> --- a/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
> +++ b/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
> @@ -78,9 +78,9 @@ Memory order is stored in the lowest 5 bits */
> 
>  #define __CLC_NVVM_ATOMIC(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,    \
>                            NAME_MANGLED)                                        \
> -  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
> +__attribute__((always_inline))  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
>                           NAME_MANGLED, __global, AS1, _global_)                \
> -  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
> +__attribute__((always_inline))  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
>                           NAME_MANGLED, __local, AS3, _shared_)
> 
>  #endif
> ```

Nice, thanks! Adding `__attribute__((always_inline))` in `atomic_load.cl`, `atomic_store.cl` and `atomic_add.cl` solved it for me. Only the change in `atomic_helpers.h` wasn't enough for `AtomicIAdd`.

**Comment by P-Jensen** [comment]
> > For the AtomicFAdd the problem can be fixed by adding **attribute**((always_inline)) to the definition. Like so:
> > ```
> > diff --git a/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h b/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
> > index 66e2b890bf14..9a0d1326bdb1 100644
> > --- a/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
> > +++ b/libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
> > @@ -78,9 +78,9 @@ Memory order is stored in the lowest 5 bits */
> > 
> >  #define __CLC_NVVM_ATOMIC(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,    \
> >                            NAME_MANGLED)                                        \
> > -  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
> > +__attribute__((always_inline))  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
> >                           NAME_MANGLED, __global, AS1, _global_)                \
> > -  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
> > +__attribute__((always_inline))  __CLC_NVVM_ATOMIC_IMPL(TYPE, TYPE_MANGLED, TYPE_NV, TYPE_MANGLED_NV, OP,     \
> >                           NAME_MANGLED, __local, AS3, _shared_)
> > 
> >  #endif
> > ```
> 
> Nice, thanks! Adding `__attribute__((always_inline))` in `atomic_load.cl`, `atomic_store.cl` and `atomic_add.cl` solved it for me. Only the change in `atomic_helpers.h` wasn't enough for `AtomicIAdd`.

@Michoumichmich Thanks for verifying that it works for the other ones as well.

**Comment by Michoumichmich** [comment]
@P-Jensen you're lucky, unfortunately I don't have improvements as I the kernel is memory bound anyway. 
But more importantly, I noticed that changes in `atomic_helpers.h` and `atomic_inc_dec_helpers.h` do not trigger a rebuild of `libclc` (which will probably cause headaches in the future while working on it). Adding the headers in `SOURCE` does not solve the issue either :/
