### ISSUE TITLE
[CUDA][New PM] Regression on the CUDA backend

### ISSUE THREAD

**Issue by Michoumichmich** [intel/llvm#5431]
**Describe the bug**

I'm not sure if this is *really* a bug, but https://github.com/intel/llvm/commit/375d2136c0c547d3a8e2a2e642a385f6fd4566d9 disabled some optimizations, but the new pass manager isn't enabled by default. 

I was working on molecular dynamics code and my kernels went literally from using several registers and no stack-frame to 255 registers and kilobytes of stack (and so a 50x performance penalty).

**Environment (please complete the following information):**

- OS: rhel8
- DPC++ version:375d2136c0c547d3a8e2a2e642a385f6fd4566d9 
- Dependencies version: CUDA 11.6

**Comment by bader** [comment]
I expected `SYCLOptimizationMode` to be enabled only for SPIR target (i.e. it should be off for NVPTX and AMDGCN). @mlychkov, could you check that, please?

**Comment by mlychkov** [comment]
@Michoumichmich I see that you closed the issue. Could you please say if you solved the issue?

**Comment by Michoumichmich** [comment]
> @Michoumichmich I see that you closed the issue. Could you please say if you solved the issue?

Hi, yes, finally the bug wasn't caused by this commit. I had moved a function call and the ptx kernel blew up. The behavior was still surprising. 

So I have a constexpr function template defined like:

```C++
template<int N>
static constexpr std::array<sycl::vec..., N> get_some_permutations(){
    ...
}
```

And then in a kernel I unroll a range for loop that uses these returned values:
```C++
static constexpr auto p = get_some_permutations<N>();
#pragma unroll
for(auto & perm : p){
       // use perm
}
```
That code compiles fine, uses a few registers and no stack. 

The issue happened whey I moved the call to have:
```C++
#pragma unroll
for(auto & perm :  get_some_permutations<N>();){
     // use perm
}
```
With the unroll it uses 255 registers and 2KB of stack, without it, it goes up to 4KB.

**Comment by Michoumichmich** [comment]
The goal was to generate a kernel with the "known at compile time permutations" embedded inside (rather than a runtime loop with the cost of the computation of the permutations)

**Comment by mlychkov** [comment]
> I expected `SYCLOptimizationMode` to be enabled only for SPIR target (i.e. it should be off for NVPTX and AMDGCN). @mlychkov, could you check that, please?

Yes, `SYCLOptimizationMode` is enabled for SPIR target only in clang.

**Comment by Michoumichmich** [comment]
> > I expected `SYCLOptimizationMode` to be enabled only for SPIR target (i.e. it should be off for NVPTX and AMDGCN). @mlychkov, could you check that, please?
> 
> Yes, `SYCLOptimizationMode` is enabled for SPIR target only in clang.

My apologies for pinging your commit

**Comment by mlychkov** [comment]
> > > I expected `SYCLOptimizationMode` to be enabled only for SPIR target (i.e. it should be off for NVPTX and AMDGCN). @mlychkov, could you check that, please?
> > 
> > 
> > Yes, `SYCLOptimizationMode` is enabled for SPIR target only in clang.
> 
> My apologies for pinging your commit

No problem at all. I’m glad to be of service.
