### ISSUE TITLE
Is there a flag to get or generate the spirv kernel?

### ISSUE THREAD

**Issue by markgarcia** [intel/llvm#546]
I'd like to have something akin to https://developer.codeplay.com/products/computecpp/ce/guides/compute-compiler (`compute++ -sycl -c`) where it just generates the spirv file. What I'd like to do with it is do reflection and modifications to adapt and feed it to my own runtime. I don't care much for stability or documentation of the output spirv as I'll figure them out myself.

**Comment by AlexeySachkov** [comment]
Hi @markgarcia,

There are several ways to do so:

1. Use [`SYCL_DUMP_IMAGES`](https://github.com/intel/llvm/blob/d4efd2ae3a708fc995e61b7da9c7419dac900372/sycl/source/detail/program_manager/program_manager.cpp#L378) env variable to get `.spv` file
2. Use `-###` `clang`s command line option to get list of commands executed under the hood - there you can find basically 3 commands: `clang -cc1 -emit-llvm-bc` then `llvm-link` and `llvm-spirv` - you can launch them manually to get SPIR-V file from you `.cpp` file
   * As a shortcut here you can use `--sycl` option. See [clang/test/CodeGenSYCL/inlining.cpp](https://github.com/intel/llvm/blob/8198a669173942a9c214a4445c585d2591f4305c/clang/test/CodeGenSYCL/inlining.cpp) or some other tests

If you made any manual modifications to you `.spv` file and want to get it used during execution of your application, you can use [`SYCL_USE_KERNEL_SPV`](https://github.com/intel/llvm/blob/d4efd2ae3a708fc995e61b7da9c7419dac900372/sycl/source/detail/program_manager/program_manager.cpp#L268) env variable.

**Comment by markgarcia** [comment]
Hello. These are exactly what I need! Is there a plan to formalize these into clang options?

For method 2, could I expect the spirv output of llvm-spirv to be identical (given identical flags) to the one when I build normally? I'm thinking that maybe you're doing passes after the translation on the back-end, just making sure.

Thanks!

**Comment by bader** [comment]
I would not commend suggestions from https://github.com/intel/llvm/issues/546#issuecomment-524615708. These can be used by the compiler developers, but not users.

Instead, please, use `-c -fsycl-is-device -fno-sycl-use-bitcode` options to get SPIR-V module for the device code.

**Comment by markgarcia** [comment]
Hmm yeah I realized `SYCL_DUMP_IMAGES` is on the sycl app itself. I'll try to use those options then, @bader. Thanks!

**Comment by markgarcia** [comment]
It's works perfectly! `-fsycl-is-device` seem to be renamed to `-fsycl-device-only`. For reference my full command line is `../bin/clang++ -c -fsycl-device-only -fno-sycl-use-bitcode -I../lib/clang/9.0.0/include/ -stdlib=libstdc++ -o test1.spv sycl-test-1.cpp`
