### ISSUE TITLE
Matrix LIT tests fails for CUDA target with new Pass Manager in clang

### ISSUE THREAD

**Issue by mlychkov** [intel/llvm#5473]
LIT testing using clang with the new Pass Manager by default is failed for the following tests:
  SYCL :: check_device_code/matrix/matrix-nvptx-bf16-test.cpp
  SYCL :: check_device_code/matrix/matrix-nvptx-half-float-test.cpp
  SYCL :: check_device_code/matrix/matrix-nvptx-half-half-test.cpp
  SYCL :: check_device_code/matrix/matrix-nvptx-int8-test.cpp
  SYCL :: check_device_code/matrix/matrix-nvptx-uint8-test.cpp

Test log can be found here: https://github.com/intel/llvm/runs/5035322838?check_suite_focus=true.

These tests have been added in https://github.com/intel/llvm/commit/537336232d28fde30b068040b356664c727f583d

**Comment by mlychkov** [comment]
Tagging @JackAKirk for awareness.

**Comment by JackAKirk** [comment]
Thanks.  It seems that the nightly build system is generating different names for the reinterpret_casted pointers than my system, although the calls still appear correct.  I can disable the tests until I understand why this is and fix the tests.

**Comment by mlychkov** [comment]
You may try to reproduce the issue on your current system just adding option `-fno-legacy-pass-manager` to clang compiler.

**Comment by JackAKirk** [comment]
> You may try to reproduce the issue on your current system just adding option `-fno-legacy-pass-manager` to clang compiler.

OK, yes I'm see the same result on my system using -fno-legacy-pass-manager.  I think I can still disable the tests temporarily until I understand the behaviour.  I think that the functionality will be identical in either case, as tested fully by this integration test in intel/llvm-test-suite: https://github.com/intel/llvm-test-suite/blob/intel/SYCL/Matrix/joint_matrix_tensorcore.cpp

**Comment by mlychkov** [comment]
@AerialMantis You added "Needs triage" label. Could you please clarify what are your concerns?
As I understood the issue was just in a bit different sequence of instructions in test IRs generated after optimizations by legacy and new PMs. @JackAKirk just fixed check strings in LIT tests.
Do you think that this difference may affect matrixes support on CUDA?

**Comment by mlychkov** [comment]
@AerialMantis Ok, I see. Thank you for clarification. 
@JackAKirk Thank you so much for fixing this so fast.
I think this issue can be closed now.
