### ISSUE TITLE
Support complex numbers in sycl::reduction

### ISSUE THREAD

**Issue by Pennycook** [intel/llvm#5477]
The [sycl_ext_oneapi_complex_algorithms](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_complex_algorithms.asciidoc) extension adds support for `std::complex` to algorithms like `reduce` and `reduce_over_group`.

During review of https://github.com/intel/llvm/pull/5394, it became clear that adding support for `std::complex` to `sycl::known_identity` would have two benefits:

1) It would simplify the implementation of the group algorithms, since `known_identity` could be used for all supported types
2) It would enable `std::complex` to be used by `sycl::reduction` without the user passing an explicit identity

Opening this issue to gauge interest in the idea, and for discussion with reduction implementers (e.g. @v-klochkov) regarding feasibility of extending `known_identity` in this way.

**Comment by v-klochkov** [comment]
I agree and think that sycl::has_known_identity should return true for std::plus<std::complex>.
That will automatically enable std::complex plus operation for sycl::reductions without explicitly passed identity value.

**Comment by uditagarwal97** [comment]
Addressed in #8425.
