### ISSUE TITLE
`-ffast-math` can cause significant slow down 

### ISSUE THREAD

**Issue by t4c1** [intel/llvm#5519]
**Describe the bug**
Specifying `-ffast-math` can under some circumstances cause significant slowdown. 

**To Reproduce**
TODO: @t4c1 to add a reproducer.
Compare performance with and without `-ffast-math`

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: aa2162ca8602d0ab71bfc78bc962802e9379a9bb
- Dependencies version: CUDA 10.2

**Additional context**

**Comment by zjin-lcf** [comment]
It is not a public repository, is it ?

**Comment by t4c1** [comment]
There was a bit of a misunderstanding. The reproducer for this requires code that is not public. Links are now removed.

Closing this for now. Will reopen when we have a better understanding of what is going on or a public reproducer.
