### ISSUE TITLE
llvm buildbot compile error - opencl environment issue?

### ISSUE THREAD

**Issue by DGASUK** [intel/llvm#5545]
After downloading llvm package, followed instructions in 'Getting started with oneAPI DPC++' for Windows (64 bit Pro version). Configure.py buildbot completed but compile.py failed and exited - see attached files configure.txt and compile.txt.

Have previously been using AMD APP SDK for OpenCL successfully with kernels for Intel CPU, Intel HD integrated graphics, and AMD GPU devices. Wanted to try using these devices with SYCL.

Now, As well as compile.py buildbot error, clinfo does not run correctly. This also indicates issue with OpenCL runtime/environment/setup?

[configure.txt](https://github.com/intel/llvm/files/8045405/configure.txt)
[compile.txt](https://github.com/intel/llvm/files/8045411/compile.txt)
[clinfo.txt](https://github.com/intel/llvm/files/8045414/clinfo.txt)

**Comment by alexbatashev** [comment]
@DGASUK you're trying to compile with mingw. We do not support this scenario:

```

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Qt/Tools/mingw730_64/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw730_64/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw730_64/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw730_64/bin/c++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw730_64/bin/c++.exe - works
```

**Comment by DGASUK** [comment]
@alexbatashev It's not quite correct to say I was trying to compile with mingw. As you can see from the attached file, I had run vcvarsall.bat from a Visual Studio folder and was fully expecting that compiler to be selected - I very rarely use mingw myself. I just followed the suggestion in the 'Getting Started with OneAPI DPC++' guide that it was easier to use the buildbot scripts. Is it something in my CMake environment or something in one of the CMakeLists.txt build files that led to this selection?
How do I enforce selection of the msvc compiler, if that is the issue?

**Comment by alexbatashev** [comment]
@DGASUK you can specify the compiler manually by passing `--cmake-opt="-DCMAKE_C_COMPILER=cl" --cmake-opt="-DCMAKE_CXX_COMPILER=cl"` to `configure.py`

**Comment by romanovvlad** [comment]
@DGASUK Could you please tell if the suggestion above helps?

**Comment by romanovvlad** [comment]
@DGASUK friendly ping.

**Comment by DGASUK** [comment]
I tried passing the above parameters to configure.py but this gave an error indication (see attached text file 1).
My VS 2019 indicates version 16.11.10 (see attached text file 2) and the latest update is now 16.11.11, co I'm not sure what 19.20 refers to?
[File 1.txt](https://github.com/intel/llvm/files/8215997/File.1.txt)
[File 2.txt](https://github.com/intel/llvm/files/8216000/File.2.txt)
