### ISSUE TITLE
[hip][SYCL] Implement "case PI_DEVICE_INFO_ATOMIC_64" check on hip backend.

### ISSUE THREAD

**Issue by denis-kabanov** [intel/llvm#5570]
The case for PI_DEVICE_INFO_ATOMIC_64 is currently not implemented in sycl/plugins/hip/pi_hip.cpp, so get_device_info receives PI_INVALID_VALUE. But without the 'template <> struct get_device_info<bool, info::device::atomic64>' specialization from sycl/source/detail/device_info.hpp (this specialization is planned to be [removed](https://github.com/intel/llvm/pull/5430)), PI_INVALID_VALUE will cause some tests to fail.

**Comment by zjin-lcf** [comment]
Does PI_DEVICE_INFO_ATOMIC_64  mean atomic operations over both global and shared memory ?

**Comment by denis-kabanov** [comment]
As I know, the PI_DEVICE_INFO_ATOMIC_64 case should checks that kernels submitted to the device may perform 64-bit atomic operations. (e.g. device.has(aspect::atomic64) == 1 if the device supports 64-bit atomic operations)

**Comment by npmiller** [comment]
Closing this as it was implemented in https://github.com/intel/llvm/pull/6429, feel free to re-open if the issue persists.
