### ISSUE TITLE
[SYCL] program aborted with the level zero backend and results do not match on Nvidia/AMD GPUs.

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#5573]
Running the program (compression/decompression) aborted with the level zero backend on an Intel GPU in DevCloud.  The program does not abort with the OpenCL backend. Can you reproduce the issue ?  If the CUDA program is not ported right, please let me know.  Thanks.

```
cd https://github.com/zjin-lcf/HeCBench/tree/master/fpdc-sycl
make 
./main 255 8 2 < ../README.md > README.bin
Aborted
```

Additionally, the decompressed output of the SYC program does not match that of the CUDA/HIP program on Nvidia/AMD GPUs.

**Comment by romanovvlad** [comment]
>> Can you reproduce the issue ? If the CUDA program is not ported right, please let me know. Thanks.

Reproduced. It's highly likely that there are bugs in the program. Valgrind reports a lot of invalid accesses in the kernel when running on CPU. Also warp size notion concerns a little bit, if there is an assumption that some work items inside a work group work in lock-step mode, then, I believe, sub-groups should be used instead.

If you believe this is a SYCL stack issue, could you please provide smaller reproducer?

**Comment by zjin-lcf** [comment]
How did you run the kernel on CPU ?  Could you please paste the invalid accesses in the kernel ? 

Thanks

**Comment by romanovvlad** [comment]
>> How did you run the kernel on CPU ? 

To run on Intel OpenCL CPU(it should be available in the system) I changed how queue is created to: `queue q{};` and set `SYCL_DEVICE_FILTER=opencl,cpu` env var when running the test.

Could you please paste the invalid accesses in the kernel ?

There are a lot of them reported, I cannot provide full log, but pattern looks like:

> ==3584698== Use of uninitialised value of size 8
> ==3584698==    at 0x4855384: ???
> ==3584698==    by 0xB7E00E8: ... (...libOclCpuBackEnd.so...)
> ...

**Comment by zjin-lcf** [comment]
In the first kernel:
```
    // prefix sum to determine start positions of non-zero delta bytes
    ibufs[iindex] = bcount;
    __threadfence_block();

    ibufs[iindex] += ibufs[iindex-1];
    __threadfence_block();

    ibufs[iindex] += ibufs[iindex-2];
    __threadfence_block();

    ibufs[iindex] += ibufs[iindex-4];
    __threadfence_block();
    ibufs[iindex] += ibufs[iindex-8];
   ..

```

The values of ibufs (allocated in shared local memory) at locations 16, 17, 18, 19 are still 8 after prefix sum in the SYCL kernel.  The expected values are 8, 16, 24, 32 in the CUDA kernel.  This is my observation.

**Comment by romanovvlad** [comment]
If you believe that this is a SYCL stack issue, could you please provide a small reproducer?

**Comment by zjin-lcf** [comment]
Sorry, I couldn't provide a small reproducer. I will look into the issue though it was solved.
