### ISSUE TITLE
sycl test result

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#561]
I ran the sycl test after building the compiler on an CentOS 7 with a processor with an Gen8 GPU. I have not looked into the tests yet.

Failing Tests (15):
    SYCLUnitTests :: aot/with-llvm-bc.cpp
    SYCLUnitTests :: basic_tests/boolean.cpp
    SYCLUnitTests :: basic_tests/device_event.cpp
    SYCLUnitTests :: basic_tests/image_array.cpp
    SYCLUnitTests :: basic_tests/stream.cpp
    SYCLUnitTests :: hier_par/hier_par_basic.cpp
    SYCLUnitTests :: hier_par/hier_par_wgscope.cpp
    SYCLUnitTests :: sub_group/barrier.cpp
    SYCLUnitTests :: sub_group/broadcast.cpp
    SYCLUnitTests :: sub_group/common.cpp
    SYCLUnitTests :: sub_group/common_ocl.cpp
    SYCLUnitTests :: sub_group/reduce.cpp
    SYCLUnitTests :: sub_group/scan.cpp
    SYCLUnitTests :: sub_group/vote.cpp
    SYCLUnitTests :: usm/math.cpp

  Expected Passes    : 94
  Unexpected Failures: 15

**Comment by bader** [comment]
@jinz2014, could you provide more information about the environment, please?
Particularly: GCC version, what OpenCL implementations are installed?

Please, make sure that:
* GCC version is 5.1.0 or later
* Recommended OpenCL CPU/GPU implementations are used for Intel HW. See https://github.com/intel/llvm/blob/sycl/sycl/ReleaseNotes.md#prerequisites

**Comment by jinz2014** [comment]
Is it right that all tests should pass ?  If so, I will try to match the Recommended OpenCL CPU/GPU implementations.

Thanks

**Comment by bader** [comment]
Yes. All tests should pass.
Each PR is validated by CI system.
Although we don't use CentOS, I think it shouldn't matter as long as C++ and OpenCL runtimes are configured correctly.

**Comment by AlexeySachkov** [comment]
@jinz2014, do you have any additional questions? Can we close this issue?

**Comment by jinz2014** [comment]
Please close the issue.

Thanks
