### ISSUE TITLE
[CUDA Backend] sparse matrix multiplication 70% performance regression by https://github.com/intel/llvm/pull/2724

### ISSUE THREAD

**Issue by jingwan2** [intel/llvm#5627]
**Describe the bug**
Sparse matrix multiplication 70% performance regression on CUDA backend by https://github.com/intel/llvm/pull/2724

**To Reproduce**
1. Compiler for CUDA backend using head https://github.com/intel/llvm/commit/bc3cf094b850a861533c8ee27e5b0a71af0513ba or later, call it as **EXP**
2. Compiler for CUDA backend using EXP and revert https://github.com/intel/llvm/pull/2724, call it as **REF**
3. Get [sycl_test.txt](https://github.com/intel/llvm/files/8113885/sycl_test.txt) , rename it as sycl_test.cpp and compile by command
 clang++ -fsycl -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda -O2 -ffast-math sycl_test.cpp -o a.out
4. SYCL_DEVICE_FILTER="CUDA:GPU" ./a.out
5. There will be output like "Time : 1.06338 s", compare the time compiled with **EXP** and **REF**

Result:
**EXP**: 1.06s
**REF**: 0.6s

**Environment (please complete the following information):**

- OS: Linux-Ubuntu 20.04
- Target device and vendor: NVIDIA TITAN RTX
- DPC++ version: clang version 15.0.0 (https://github.com/intel/llvm bc3cf094b850a861533c8ee27e5b0a71af0513ba)
- Dependencies version: NVIDIA-SMI 510.47.03, CUDA Version: 11.6

**Additional context**
nvprof profiling data shows performance regression happened on kernel execution.
**EXP**:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   98.04%  **909.78ms**      1000  909.78us  903.40us  917.58us  _ZTSZZ4mainENKUlRN2cl4sycl7handlerEE0_clES2_EUlNS0_2idILi1EEEE_
                    1.96%  18.141ms         4  4.5352ms  226.01us  11.726ms  [CUDA memcpy HtoD]
                    0.00%  5.2480us         1  5.2480us  5.2480us  5.2480us  _ZTSZZ4mainENKUlRN2cl4sycl7handlerEE_clES2_EUlNS0_2idILi1EEEE_

**REF**:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   95.81%  **417.51ms**      1000  417.51us  409.27us  427.16us  _ZTSZZ4mainENKUlRN2cl4sycl7handlerEE0_clES2_EUlNS0_2idILi1EEEE_
                    4.18%  18.222ms         4  4.5556ms  224.41us  11.777ms  [CUDA memcpy HtoD]
                    0.01%  44.063us         1  44.063us  44.063us  44.063us  _ZTSZZ4mainENKUlRN2cl4sycl7handlerEE_clES2_EUlNS0_2idILi1EEEE_

**Comment by zjin-lcf** [comment]
@jingwan2   Do the Nvidia PTX codes look the same for the two versions ?

**Comment by jingwan2** [comment]
@zjin-lcf , I can confirm that device bitcode doesn't change. Do you know how to check PTX code?

**Comment by zjin-lcf** [comment]
adding the '-save-temps' compiler option would produce a ".s" file.

**Comment by jingwan2** [comment]
@zjin-lcf , thanks, .s files have no difference. 
And I tried to run binary built by **REF**, and run with **EXP** runtime, performance also is bad, so should be runtime issue.

**Comment by zjin-lcf** [comment]
I converted the sycl program to cuda, and ran the cuda program on sm_70 and sm_86 devices. The following lists show the execution time of the spmm kernel only.  Did you observe similar results ?  Thanks.
 
```
sm_70
thread block size: 32
Time : 0.762959 s
thread block size: 64
Time : 0.842495 s
thread block size: 128
Time : 0.843036 s
thread block size: 256
Time : 0.85008 s
thread block size: 512
Time : 0.94828 s
thread block size: 1024
Time : 1.47075 s
```

```
sm_86
thread block size: 32
Time : 0.388415 s
thread block size: 64
Time : 0.565948 s
thread block size: 128
Time : 0.631123 s
thread block size: 256
Time : 0.622051 s
thread block size: 512
Time : 0.664461 s
thread block size: 1024
Time : 0.720332 s
```

**Comment by jingwan2** [comment]
@zjin-lcf, yes I saw similar result for cuda kernel.

**Comment by zjin-lcf** [comment]
Is it helpful to file a report with Nvidia support about performance/occupancy ?

**Comment by zjin-lcf** [comment]
I added simple spmv benchmarks. They are not exactly the same as your program, but the performance trends are the same.
https://github.com/zjin-lcf/HeCBench/tree/master/simpleSpmv-cuda

**Comment by GeorgeWeb** [comment]
This should now be resolved by PR [#9736](https://github.com/intel/llvm/pull/9736) (see commit: [fa501fd21a286c5d6d760249a88c6ffddaffe2e8](https://github.com/intel/llvm/commit/fa501fd21a286c5d6d760249a88c6ffddaffe2e8)).

@jingwan2  Would you be able to confirm if that solves the regression on your side as well. Thanks!

**Comment by jingwan2** [comment]
@GeorgeWeb , I saw performance from 0.73s improves to 0.54s on Titian RTX.

**Comment by GeorgeWeb** [comment]
That sounds back to (or slightly better) to what was the last reported REF timing on the TITAN RTX.
@jingwan2 Is this now enough to close this issue wrt wrong local work size guessing, and if any other problems/regressions were identified from this sample, then open a new issue?

**Comment by jingwan2** [comment]
@GeorgeWeb, agree, thanks for your effort.
