### ISSUE TITLE
[SYCL][CUDA] Alignment issue with zero-sized local arguments

### ISSUE THREAD

**Issue by nmnobre** [intel/llvm#5682]
**Describe the bug**

The alignment strategy for local arguments introduced with PR #5113 does not take into account zero-sized local arguments. Since, in such circumstances, the requested alignment is also zero (see `sycl/plugins/cuda/pi_cuda.hpp`):

`const size_t alignment = std::min(max_alignment, size);`,

the program receives signal SIGFPE, Arithmetic exception at runtime at the following modulus test:

`localOffset % alignment != 0`.

This problem is similar to that reported in issue #1467. I confess I understand little about local arguments or why the application I'm using uses zero-sized local arguments. Please do feel free to disregard this issue if this is just incorrect behaviour by the application.

**Environment:**

- OS: CentOS Linux release 8.5.2111
- Target device and vendor: NVIDIA Quadro GV100
- DPC++ version: ebb1281 and newer

**Comment by JackAKirk** [comment]
Hi @nmnobre 

We hope that #5683 will fix your issue, but do you have your sample code that ran into the problem so that we can check that your particular issue is solved by the patch?

Thanks

**Comment by AerialMantis** [comment]
Related pull request for adding a test for zero-sized local accessors - https://github.com/intel/llvm-test-suite/pull/1001

**Comment by AerialMantis** [comment]
This issue has been addressed more generically in the SYCL runtime by https://github.com/intel/llvm/pull/6032, with this patch zero-sized local memory arguments are padded to 1 byte so this case is never encountered in the backends. @nmnobre I believe this issue to be resolved so I will close the ticket, however, if you feel an issue persists we can re-open it.
