### ISSUE TITLE
[SYCL/L0] sycl::memcpy creates an additional L0 command queue

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#5808]
**Describe the bug**
I was mostly profiling an app using onetrace and have created a reproducer shown below. In short, the reproducer creates 2 queues and a `sycl::memcpy`.

Adding a memcpy op creates an additional command-queue and was just curious if this is an expected behavior. Looks like DPC++'s `memcpy` adds in an additional creation of L0 command-queue. This is evident from the number of calls to `zeCommandQueueCreate` shown in the profiling output.

From the point of view of L0, an L0 queue needs to be created to append a zeCopy operation that has been appended to a list, or alternatively, the zeCopy needs to go to an immediate command list. Not sure which of the above two cases that DPC++ is using to implement and translate to L0 code.

**To Reproduce**
```
#include <sycl/sycl.hpp>

int main(int argc, char **argv)
{
  std::vector<sycl::device> allDevices = sycl::device::get_devices(sycl::info::device_type::gpu);
  auto subDevices = allDevices[0].create_sub_devices<sycl::info::partition_property::partition_by_affinity_domain>(sycl::info::partition_affinity_domain::numa);
  sycl::device *targetDev = new sycl::device(subDevices[0]);
  sycl::context *targetContext = new sycl::context(*targetDev);

  const int nQueues = 2;
  const int n = targetDev->get_info<sycl::info::device::max_mem_alloc_size>() / (2*sizeof(float));
  std::cout << "n : " << n << ", (GBs) : " << n*sizeof(float) * 1.0e-09 << std::endl;
  
  // create events and queues
  sycl::queue *queue[nQueues];
  for (int i = 0; i < nQueues; ++i) {
    queue[i] = new sycl::queue(*targetContext, *targetDev, sycl::property_list{sycl::property::queue::in_order{}});
  }

  // allocate host memory and device memory
  float *h_a   = new float[n];
  float *d_a = sycl::malloc_device<float>(n, *targetDev, *targetContext); // device

  queue[0]->memcpy(d_a, h_a, n*sizeof(float));

  return 0;
}
```
Some of the profiling output is truncated for clarity.

<details><summary>Before (without `sycl::memcpy`)</summary>

                              Function,       Calls,           Time (ns),  Time (%),        Average (ns),            Min (ns),            Max (ns)
                      zeMemAllocDevice,           1,            20804520,     94.12,            20804520,            20804520,            20804520
          zeCommandListCreateImmediate,           1,              964433,      4.36,              964433,              964433,              964433
                  zeCommandQueueCreate,           2,              314511,      1.42,              157255,              154330,              160181
</details>

<details><summary>After (with `sycl::memcpy`)</summary>

                              Function,       Calls,           Time (ns),  Time (%),        Average (ns),            Min (ns),            Max (ns)
         zeCommandListAppendMemoryCopy,           1,           247365887,     90.94,           247365887,           247365887,           247365887
                      zeMemAllocDevice,           1,            20889025,      7.68,            20889025,            20889025,            20889025
     zeCommandQueueExecuteCommandLists,           1,             1777965,      0.65,             1777965,             1777965,             1777965
          zeCommandListCreateImmediate,           1,              995988,      0.37,              995988,              995988,              995988
                  zeCommandQueueCreate,           3,              481460,      0.18,              160486,              151290,              166893
                   zeCommandListCreate,           1,              356701,      0.13,              356701,              356701,              356701
</details>

**Environment (please complete the following information):**
Intel(R) oneAPI DPC++/C++ Compiler 2022.1.0 (2022.x.0.20220112)
Target: x86_64-unknown-linux-gnu

**Comment by smaslov-intel** [comment]
The extra L0 queue is expected and is handling copy operations via copy engines. It allows for the best parallelism as this way copies are executed in parallel to compute.  Note also, that devices that have multiple engines (both copy and compute) will create/use multiple L0 queues (in a round-robin fashion currently) for optimal parallelism on submissions (submission to the same engine are serialized).

**Comment by keryell** [comment]
@abagusetty this behavior is la raison d'être de SYCL.
If you want to write in assembly code you can use CUDA/OpenCL/HIP/.... Or even better use the interoperability mode of SYCL to get the CUDA/OpenCL/HIP/... underlying object. :-)
Do you think there are valuable use cases in SYCL for such a single underlying queue? We could add a queue property for this if necessary.
There is already the ordered queue for a similar behavior.
How to avoid some kind of dead-locks if there is a single queue in the general case when the concrete hardware queue is in-order?

**Comment by abagusetty** [comment]
@keryell I wasn't really aware of an additional ZeImmediateCmdList gets created to target copy-engines. 

From the above reproducer, I was creating `in_order` queues and wasn't sure of this detail on additional L0 queue. From @smaslov-intel explanation, it sounds like whether the queue is `in_order` or `default/out-of-order` and additional queue gets created to handle the case of overlapping-compute-copy. 

@smaslov-intel might be best to answer regarding your dead-lock query. Also on the single underlying queue, I don't atleast forsee a single/singleton unique queue like property in need.

**Comment by smaslov-intel** [comment]
It's important to know that a SYCL queue maps to possibly multiple native L0 queues under the hood for performance reasons. The L0 plugin layer is taking care of any synchronization needed across those queues (of course on top what SYCL had requested like in-order semantics and/or explicit dependencies between commands).
