### ISSUE TITLE
Compiler crash at "Instruction does not dominate all uses!"

### ISSUE THREAD

**Issue by jingwan2** [intel/llvm#5840]
**Describe the bug**
CUDA backend compiler crash at "Instruction does not dominate all uses!" with guilty commit https://github.com/llvm/llvm-project/commit/1eeb2bfe727323332800e8d390f2f8c63c953779

**To Reproduce**
1. Compiler for CUDA backend using head https://github.com/intel/llvm/commit/191a62ad85043c2b5d7b2b2d968cb65ad6190397 or later
2. Get [sycl_test.txt](https://github.com/intel/llvm/files/8312579/sycl_test.txt), rename it as sycl_test.cpp and compile by command
clang++ -fsycl -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda -O2 -ffast-math sycl_test.cpp -o a.out

**Environment (please complete the following information):**

OS: Linux-Ubuntu 20.04
Target device and vendor: NVIDIA TITAN RTX
DPC++ version: clang version 15.0.0 (https://github.com/intel/llvm.git 191a62ad85043c2b5d7b2b2d968cb65ad6190397)
Dependencies version: NVIDIA-SMI 510.47.03, CUDA Version: 11.6

**Additional context**
Compiler log:
Instruction does not dominate all uses!
  %92 = fadd fast <2 x double> %56, %54
  %91 = shufflevector <2 x double> %92, <2 x double> %59, <2 x i32> <i32 0, i32 2>
in function _Z21binomialOptionsKernelN2cl4sycl7nd_itemILi1EEEP13__TOptionDataPdS5_
fatal error: error in backend: Broken function found, compilation aborted!
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)

**Comment by zjin-lcf** [comment]
I could reproduce it. The error is caused by -ffast-math

**Comment by jingwan2** [comment]
Remove cuda label as it also reproduced on other backend.

**Comment by AlexeySachkov** [comment]
> Remove cuda label as it also reproduced on other backend.

@jingwan2, could you please provide more info here? I was trying to reproduce the issue on the fresh local build (without `-fsycl-targets` option), but wasn't able to do so

**Comment by jingwan2** [comment]
@AlexeySachkov , what's your code base? seems latest pulldown fixed the issue. 
https://github.com/intel/llvm/commit/c818709fcebd5d8183e0ebe127e7f37b8867c3f2

I'm closing this issue as it's resolved.

**Comment by zjin-lcf** [comment]
@bader  could you please point out which codes fix the issue ?  Thanks.

**Comment by bader** [comment]
@zjin-lcf, unfortunately, I don't know. 
According to @jingwan2, it might be https://github.com/intel/llvm/commit/c818709fcebd5d8183e0ebe127e7f37b8867c3f2. Are you able to use this version or later?

**Comment by zjin-lcf** [comment]
I wonder if people who know could point out the codes.  I will try the later version.
