### ISSUE TITLE
SYCL_USE_NATIVE_FP_ATOMICS not set for NVIDIA targets

### ISSUE THREAD

**Issue by al42and** [intel/llvm#5936]
**Describe the bug**

When compiling for NVIDIA devices, `SYCL_USE_NATIVE_FP_ATOMICS` is not set automatically, which causes floating-poing atomics to be expanded into a CompareExchange loop.

**To Reproduce**

```cpp
#include <CL/sycl.hpp>
#include <vector>

void run_kernel(const cl::sycl::device &syclDevice) {
  static const int numThreads = 8;
  sycl::queue queue = cl::sycl::queue(syclDevice);
  auto buf = sycl::malloc_device<float>(1, queue);
  sycl::event ev = queue.submit([&](sycl::handler &cgh) {
    cgh.parallel_for<class DummyKernel>(
        sycl::range<1>{numThreads}, [=](sycl::id<1> threadId) {
            sycl::atomic_ref<float, sycl::memory_order::relaxed, sycl::memory_scope::device, sycl::access::address_space::global_space> ref(buf[0]);
            ref.fetch_add(1);
        });
  });
  ev.wait_and_throw();
}

int main() {
  std::vector<cl::sycl::device> devices = cl::sycl::device::get_devices();
  for (const auto &dev : devices) {
    run_kernel(dev);
  }
}
```

```
# Default flags: fetch_add gets expanded into a CAS loop
$ rm -f atomic-*
$ clang++ -fsycl -O3 -fsycl-targets=nvptx64-nvidia-cuda atomic.cpp -o atomic -save-temps
$ fgrep atom. atomic-*.s
        atom.global.cas.b32     %r6, [%rd2], %r4, %r5;
        atom.global.cas.b32     %r6, [%rd2], %r4, %r5;
        atom.global.cas.b32     %r3, [%rd1], %r1, %r2;
# Setting SYCL_USE_NATIVE_FP_ATOMICS manually: hardware FP32 atomics are used
$ rm atomic-*
$ clang++ -fsycl -O3 -DSYCL_USE_NATIVE_FP_ATOMICS=1 -fsycl-targets=nvptx64-nvidia-cuda atomic.cpp -o atomic -save-temps
$ fgrep atom. atomic-*.s
        atom.global.add.f32     %f2, [%rd1], %f1;

$ clang++ --version
clang version 15.0.0 (https://github.com/intel/llvm 5224f78863c3d3578d8c6a2e189432d2286fbd4a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/aland/intel-sycl/llvm/build/install//bin
```

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- Target device and vendor: NVIDIA GTX1660SUPER (sm_75)
- DPC++ version: 5224f78863c3d3578d8c6a2e189432d2286fbd4a
- Dependencies version: CUDA 11.5

**Comment by AerialMantis** [comment]
Hi @al42and, thanks for raising this issue. We would like to enable `SYCL_USE_NATIVE_FP_ATOMICS` by default when targeting Nvidia, however, there are still some atomic functions, specifically double add, which require a later compute capability (sm_60) than the default (sm_50), so we have the compare exchange loop implementation by default to ensure correctness.

We are planning to introduce a pre-sm_60 implementation for those specific atomic functions, after which we will be able to enable `SYCL_USE_NATIVE_FP_ATOMICS` by default.

I hope this helps, and we'll keep you updated as we're working on this.

**Comment by al42and** [comment]
Hi @AerialMantis,

> there are still some atomic functions, specifically double add, which require a later compute capability (sm_60) than the default (sm_50), so we have the compare exchange loop implementation by default to ensure those will always compile.

I see, thanks for clarifying. However, atomics are not enabled even when explicitly compiling for newer hardware (`-fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --offload-arch=sm_70`). Or for FP32, which has been available since forever (sm_13, if I recall correctly).

One can always define the macro manually, so it's all not critical. But the [release notes](https://github.com/intel/llvm/blob/c2f8602c843d2ba87dc1c9057f1422f23a77ed66/sycl/ReleaseNotes.md) are misleading (I guess they were written with SPIR-V compilation in mind):

>  - Enabled native FP atomics by default. Defining the
>   `SYCL_USE_NATIVE_FP_ATOMICS` macro explicitly is no longer required - it is
>   now automatically defined for hardware targets with "native" support for
>   atomic functions.

> I hope this helps, and we'll keep you updated as we're working on this.

Thanks! Manually defining `SYCL_USE_NATIVE_FP_ATOMICS` works for me just fine. But I think keeping this issue open would be helpful to others who also use atomics with CUDA backend.

**Comment by AerialMantis** [comment]
@al42and thanks very much for your feedback, I'm glad you're able to work around this.

You are correct that the `SYCL_USE_NATIVE_FP_ATOMICS` is disabled for all cases where it could be selectively enabled for certain cases in the meantime, however, since there is only the double add case where remaining to be addressed we opted for just resolving this and then enabling it by default.

https://github.com/intel/llvm/pull/5998 will address this remaining case and enable `SYCL_USE_NATIVE_FP_ATOMICS` by default.
