### ISSUE TITLE
Error when compile LLVM

### ISSUE THREAD

**Issue by andreagen0r** [intel/llvm#5943]
**Describe the bug**
I trying to compile it to support CUDA but I get an error at the end when installing

**To Reproduce**
```
cd /home/myuser;
git clone https://github.com/intel/llvm.git -b sycl;
cd llvm;
python3 ./buildbot/configure.py --cuda -t release --cmake-gen "Unix Makefiles";
cd build
make install -j 6
```

The error:
```
CMake Error at tools/libdevice/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/home/andreagenor/code/llvm/build/lib/libsycl-crt.o": No such file or
  directory.
Call Stack (most recent call first):
  tools/cmake_install.cmake:143 (include)
  cmake_install.cmake:77 (include)
```

**Environment (please complete the following information):**

- OS: Linux - Kubuntu 21.10
- Target device and vendor: Intel CPU + NVidia GPU
- DPC++ version: sycl Branch

**Comment by bader** [comment]
@andreagen0r, could you attach a full log, please?

**Comment by alexbatashev** [comment]
I think the correct way is to call `deploy-sycl-toolchain` target instead of `install`, at least for now.

**Comment by andreagen0r** [comment]
@bader 
[CMakeError.log ](https://paste.cutelyst.org/JyfiBD2jT)
[CMakeOutput.log ](https://paste.cutelyst.org/lIgZvM_9S)

@alexbatashev I'm using this [tutorial](https://codeplay.com/solutions/oneapi/for-cuda/#getting-started)

**Comment by npmiller** [comment]
Yes, at the moment `make install` doesn't build all of the SYCL dependencies correctly, instead you should run:

```
make sycl-toolchain -j 6
make install
```

Instead of just `make install`, or `deploy-sycl-toolchain` as pointed out previously.

The tutorial you linked is a little out of date but should be updated soon to reflect this.

**Comment by npmiller** [comment]
I believe this issue is resolved and the tutorial has also now been updated so closing this ticket. Feel free to re-open if you have further issues with this.

**Comment by andreagen0r** [comment]
Hi @npmiller, I tried your suggestion but I got a new error at the end of the install

```
[ 98%] Performing update step for 'level-zero-loader'
CMake Error at /home/andreagenor/code/external/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-update-release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-P' '/home/andreagenor/code/external/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/tmp/level-zero-loader-gitupdate.cmake'

  See also

    /home/andreagenor/code/external/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-update-*.log


make[2]: *** [tools/sycl/plugins/level_zero/CMakeFiles/level-zero-loader.dir/build.make:125: tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:85031: tools/sycl/plugins/level_zero/CMakeFiles/level-zero-loader.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
``` 
[CMakeError.log](https://paste.cutelyst.org/kXBgENB_R)
[CMakeOutput.log](https://paste.cutelyst.org/Q-Eb0DiiS)

**Comment by npmiller** [comment]
Hello @andreagen0r that's strange, I'm not seeing this locally, this part is simply updating some of the level zero repository so it's strange it would fail, maybe a connection issue on your side during the build?

There may be more information in the specific log files the error is suggesting:
```
/home/andreagenor/code/external/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-update-*.log
```

And a clean build may also help if this wasn't one.

**Comment by andreagen0r** [comment]
@npmiller  I did a clean build and the build step was successful.

```
rm -rf build
python3 ./buildbot/configure.py --cuda -t release --cmake-gen "Unix Makefiles"
cd build
make sycl-toolchain -j6
sudo make install
```

**Comment by andreagen0r** [comment]
@npmiller 
Hi Nicolas, now the installation was successful. I needed to run this command below. Thank you for the support
`sudo git config --global --add safe.directory /home/andreagenor/code/external/llvm/build/tools/sycl/plugins/level_zero/level_zero/level_zero_loader`
