### ISSUE TITLE
[CUDA] Embedding runfail on CUDA backend with PI CUDA ERROR: CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by skosnits** [intel/llvm#5970]
**Describe the bug**
[CUDA] Embedding runfail on CUDA backend with PI CUDA ERROR: CUDA_ERROR_ILLEGAL_ADDRESS

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) 
2. Build and run attached source file: [embedding_for_external.cpp.txt](https://github.com/intel/llvm/files/8421787/embedding_for_external.cpp.txt)

```
clang++ -fsycl -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda-sycldevice embedding_for_external.cpp -o embedding.run  -lOpenCL
./embedding.run
```

Error message:
```
./embedding.run

 Work group : input len = 32768, slice = 2, NumWERow = 8, local_x = 6000000, local_y = 32, global_x = 6000000, global_y = 64, group_x = 1, group_y = 2
PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        wait
        Source Location: llvm.src/sycl/plugins/cuda/pi_cuda.cpp:449

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  Native API failed. Native API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
Aborted (core dumped)
```

**Environment**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git 8ec97550b7a84e5d2483f4891059f80abd8db39c
- CUDA version: 
```
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
```

**Comment by zjin-lcf** [comment]
Is there a CUDA program for comparison ?   

cuda-gdb shows:

Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 1, block (1,1365,0), thread (0,2,0), device 0, sm 0, warp 12, lane 0]
sycl/main.cpp:130
130                     output[global_address + col] = weight[indexToSearch * weight_feature_size + col];

**Comment by bader** [comment]
This might be a bug in the application. I would check that indices fit into the allocated memory region.

**Comment by zjin-lcf** [comment]
cuda-gdb shows illegal warp address after converting the sycl program to cuda. I hope that a modified version will be an oneAPI sample.

**Comment by zjin-lcf** [comment]
@skosnits  Could you please explain the meaning of normal operations in the kernel ?

**Comment by zjin-lcf** [comment]
Thank you for describing the kernel function.

**Comment by t4c1** [comment]
This is a user error on line 327 - accessing a USM allocation out of bounds. The variable `output` has size of `input_length * weight_feature_size`, while it is being indexed with `global_address + col`, where maximum value of `col` is `weight_feature_size-1` and `global_address` is `row * weight_feature_size`. `row` has a maximal value of `global_size_x`, which is greater than `input_length`.
