### ISSUE TITLE
clinfo  does not work on ghcr.io/intel/llvm/ubuntu2004_base

### ISSUE THREAD

**Issue by guoyejun** [intel/llvm#5974]
https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md says that： you can use Docker image, that has everything you need pre-installed， but looks that  clinfo does not work within it.

clinfo works on my host machine, but it does not work in the container.

Here are my steps, anything I missed? thanks.

```
$ clinfo | more
Number of platforms                               2
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 3.0
  Platform Profile                                FULL_PROFILE
...

$ docker run --name sycl_build --device=/dev/dri -it -v /mypath/sycl_workspace:/src ghcr.io/intel/llvm/ubuntu2004_base /bin/bash

root@c9497c8fe565:/# apt-get install clinfo
root@c9497c8fe565:/# clinfo
Number of platforms                               0
root@c9497c8fe565:/# ls /dev/dri/
card0  card1  renderD128

```

**Comment by bader** [comment]
Sorry, the document a bit confusing. This docker image doesn't have installed OpenCL drivers. As document says:

> This command will start a terminal session, from which you can proceed with the instructions below.

The instructions below include driver installation instructions, so you can install them manually. cl_info should work as you expected.

> See [Docker BKMs](https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/DockerBKMs.md) for more info on Docker commands.

This document has following section:

> ## SYCL Containers overview
> 
> The following containers are publicly available for DPC++ compiler development:
> 
> - `ghcr.io/intel/llvm/ubuntu2004_base`: contains basic environment setup for building DPC++ compiler from source.
> - `ghcr.io/intel/llvm/ubuntu2004_intel_drivers`: contains everything from the base container + pre-installed Intel drivers.
> - `ghcr.io/intel/llvm/sycl_ubuntu2004_nightly`: contains the latest successfully built nightly build of DPC++ compiler. The image comes in two flavors: with pre-installed Intel drivers (`latest`) and without them (`no-drivers`).

You can switch to ubuntu2004_intel_drivers container in case you'd like to have pre-configured environment for running SYCL applications.

**Comment by guoyejun** [comment]
thanks, I got a mis-understanding, ghcr.io/intel/llvm/ubuntu2004_intel_drivers works.
