### ISSUE TITLE
nondeterministic behaviour of reduce_over_group on OpenCL CPU 

### ISSUE THREAD

**Issue by iamholger** [intel/llvm#5989]
**Describe the bug**
When using reduce_over_group in an nd_range<1> I observe observe
behaviour similar to a race condition leading to wrong results.
Curiously, this only happens on CPUs (OpenCL runtime).
The same code runs fine on intel and cuda devices.

**To Reproduce**
Please describe the steps to reproduce the behavior:

This is my reproducer, **demo.cxx**:

```c
#include <numeric>

#include <CL/sycl.hpp>
using namespace sycl;

static queue mQ(default_selector{});
    
// Create array with Nhave doubles
// Reduce packets of gathersize elements using reduce_over_group
//
// E.g.
//
//  data = [0,1,2,3,4,5,6,7,8,9]
//  gathersize=2
//
//  --> reduce_over_group with maximum<>() results in
//  data = [1,3,5,7,9]
//
//

void demo(sycl::queue Q, const size_t Nhave, const size_t gathersize)
{
    std::vector<double> test(Nhave);
    std::iota(test.begin(), test.end(), 0);
    
    auto data = malloc_shared<double>(Nhave,mQ);
    mQ.memcpy(data, test.data(), sizeof(double)*Nhave).wait();
    
    
    Q.submit([&](handler & cgh)
    {
      cgh.parallel_for(nd_range<1>{{Nhave}, {gathersize}}, [=](nd_item<1> it) 
      {
            auto temp = reduce_over_group(it.get_group(), data[it.get_global_id(0)], maximum<>());
            data[it.get_group(0)] = temp;
        
      });
    }).wait();

    // Check that the reduction was successful for a representative chunk of the data
    for (int i=0;i< std::min<int>(gathersize, 100);i++)
    {
        auto truth = *std::max_element(test.begin() + i*gathersize, test.begin() + (i+1)*gathersize);
        std::cout << data[i] - truth << " ";
        assert(data[i] == truth);
    }
    std::cout << "\n";
    std::cout << "\n";

}

int main(int argc, char* argv[])
{
    // By default use the configuration where the problem was first discovered
    if (argc<3) demo(mQ, 17963973, 961);
    else demo(mQ, std::atoi(argv[1]), std::atoi(argv[2]));
}
```

I compile as such:
```bash
clang++ ../demo.cxx -fsycl -fsycl-targets=nvptx64-nvidia-cuda--sm_75,spir64,spir64_x86_64 -o demo
```

To run reproduce the problem, I need to run it a couple of times as the problem does not always show up:

```bash
for i in {1..100}; do  SYCL_DEVICE_FILTER=cpu ./demo;done
```

**Environment (please complete the following information):**

- OS: [e.g Windows/Linux]
Linux
- Target device and vendor: [e.g. Intel GPU]
Intel CPU
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
clang version 15.0.0 (https://github.com/intel/llvm 4b1a4bca94fd61148f9d71b00aa20bbcaa7fc0d8)

- Dependencies version: [e.g. low-level runtime versions (like NEO 20.04)]
I use the intel compute runtime.
My [Dockerfile](https://github.com/iamholger/syclbits/blob/main/Docker/Dockerfile) is following the instructions
on this repo and that of the compute-runtime.

**Additional context**
This is also reproducible on devcloud with oneAPI Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)

**Comment by zjin-lcf** [comment]
what are your command-line arguments to ./demo ? 

data[it.get_group(0)] = temp;    // multiple threads writing to the same group...

**Comment by iamholger** [comment]
Either no arguments, so just 
```
./demo
```

or  any combination of argv[1] and argv[2]
such that "argv[1] % argv[2] = 0", e.g.

```
./demo 17963973   961
```

**Comment by AlexeySachkov** [comment]
Hi @iamholger,

@zjin-lcf is correct, your example contains a race condition: `reduce_over_group` result from a one work-group is written to a location, which is used as an input for another work-group's reduction. That leads to unexpected results and it is indeed sporadic, because it depends on how exactly work-groups were scheduled and which was launched first.

```
            data[it.get_group(0)] = temp;
```

As said above, this is the culprit: you need to use a separate memory location to store results

**Comment by iamholger** [comment]
Ah great, thanks!
