### ISSUE TITLE
Support assert on HIP backend

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#5990]
> For the HIP backend, is there some 'assert()' called in the sycl kernel ?

Oh, yes. The problem with the HIP backend is completely separate from what I'm describing here. We use `assert(...)` statements in our code in a few places, and the HIP backend doesn't seem to support that yet.

Note that for the CUDA backend we've had the following workaround in place for a while:
  - https://github.com/acts-project/vecmem/blob/main/sycl/CMakeLists.txt#L43-L75
  - https://github.com/acts-project/vecmem/blob/main/sycl/src/utils/sycl/cuda_assert_polyfill.sycl

But I didn't find a similar workaround for HIP yet. Also note that the CUDA workaround is not actually needed with the latest version of the compiler. (This is where it comes handy that our build checks at configuration whether it should use the workaround or not.)

_Originally posted by @krasznaa in https://github.com/intel/llvm/issues/5980#issuecomment-1093059613_

**Comment by AlexeySachkov** [comment]
@zjin-lcf, @krasznaa, do I understand it correctly, that the purpose of this issue is to request support (or at least workaround) for `assert` on HIP backend?

**Comment by krasznaa** [comment]
Hi,

Yes, that is exactly it. We have a bunch of `assert(...)` statements in our SYCL code. Right now we can't build that code in Debug mode with the HIP backend because of this issue.

It's of course not the absolute highest priority for us, we've just not been debugging our code on AMD hardware so far... :stuck_out_tongue: 

Cheers,
         Attila

**Comment by npmiller** [comment]
Assert on HIP should be working now, it was implemented in:
* https://github.com/intel/llvm/pull/6424

**Comment by npmiller** [comment]
Closing this as it should be fixed, please feel free to re-open if the issues persist.
