### ISSUE TITLE
[HIP][SYCL] llvm-foreach: Couldn't find replace string for output in the command.

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#5996]
When building a SYCL program, the following error is shown. The SYCL program calls some functions in the GNU scientific library (GSL). Do I need to build GSL with the SYCL compiler (clang++) ?  Thanks.

llvm-foreach: Couldn't find replace string for output in the command.
clang-15: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)

**Comment by abagusetty** [comment]
@zjin-lcf I too came across this when building a project on Crusher with DPCPP (ROCM-5.1.0). Any pointers ?

**Comment by jgtong** [comment]
Is there any work around for this?
