### ISSUE TITLE
compile intel/llvm source FAILED

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#6008]
**Describe the bug**
I  compiles C++ and SYCL* source files with code refer to [GetStartGuide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md)

When I execute "python $DPCPP_HOME/llvm/buildbot/compile.py" , I get error

**To Reproduce**
Please describe the steps to reproduce the behavior:

![image](https://user-images.githubusercontent.com/22990858/163125517-89f78871-19a1-4f97-9577-69f5979bb29d.png)

**Environment (please complete the following information):**

- OS: [CentOS Linux release 7.9.2009 (Core)]
- Target device and vendor: [Nvidia GPU]
- Dependencies version: [cmake version 3.22.1  gcc version gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)]

**Additional context**

**Comment by s-mx** [comment]
Hi @wangzy0327 ! 
Is it possible that you cropped a piece of printed information while taking a screenshot? Because usually build systems (make or ninja) print some reason right after a compiling command, which in your case is a long list of object files. Could you please check whether there is missed something in your case?

**Comment by wangzy0327** [comment]
Sorry，it is not complete. These are other pieces of printed information.
![image](https://user-images.githubusercontent.com/22990858/163295045-ca795bca-b55c-45d5-8a77-c6f7c50e7735.png)

![image](https://user-images.githubusercontent.com/22990858/163295011-fb9b9c1b-9af9-4a7a-b04d-608f740b0d73.png)

**Comment by s-mx** [comment]
@wangzy0327
I see a similar discussion here https://github.com/intel/llvm/discussions/4926.
There is a workaround which proposes to comment out 3-4 lines here https://github.com/intel/llvm/blob/7fb56cf563e3bf9e4b4a462f21f60596d6687f39/sycl/source/CMakeLists.txt#L55-L58
Could you please try to repeat it in your environment?

**Comment by wangzy0327** [comment]
> @wangzy0327 I see a similar discussion here #4926. There is a workaround which proposes to comment out 3-4 lines here
> 
> https://github.com/intel/llvm/blob/7fb56cf563e3bf9e4b4a462f21f60596d6687f39/sycl/source/CMakeLists.txt#L55-L58
> 
> 
> Could you please try to repeat it in your environment?

Thank you！
