### ISSUE TITLE
sycl::half arithmetic operator promotes results to float 

### ISSUE THREAD

**Issue by TApplencourt** [intel/llvm#6028]
**Describe the bug**

`sycl::half` arithmetic operator promotes results to float 

**To Reproduce**

```
$cat test.cpp
#include <type_traits>
#include <sycl/sycl.hpp>
int main() {
   sycl::queue myQueue;
   myQueue.submit([&](sycl::handler& cgh) {
    sycl::device dev = myQueue.get_device();
    if (dev.has(sycl::aspect::fp16)) {
       cgh.single_task([=]{
            static_assert(std::is_same_v<decltype(sycl::half(1)), sycl::half>,"Not a sycl::half");
            static_assert(std::is_same_v<decltype(sycl::half(1) *  sycl::half(1) ), sycl::half>,"Not a sycl::half");
     });
    };
   });
   return 0;
}
$dpcpp test.cpp
test.cpp:11:13: error: static_assert failed due to requirement 'std::is_same_v<float, sycl::detail::half_impl::half>' "Not a sycl::half"
            static_assert(std::is_same_v<decltype(sycl::half(1) *  sycl::half(1) ), sycl::half>,"Not a sycl::half");
            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Intel GPU
- DPC++ version: Intel(R) oneAPI DPC++/C++ Compiler 2022.1.0 (2022.1.0.20220224)

**Comment by TApplencourt** [comment]
( @AerialMantis The bug were found when porting sycl::complex to half precision)

**Comment by zjin-lcf** [comment]
the cuda programming guide shows the fp16 operations.

__device__​ __half __hmul ( const __half a, const __half b )
Performs half multiplication in round-to-nearest-even mode.
Description
Performs half multiplication of inputs a and b, in round-to-nearest mode.

__device__​ __half __hmul_rn ( const __half a, const __half b )
Performs half multiplication in round-to-nearest-even mode.
Description
Performs half multiplication of inputs a and b, in round-to-nearest mode. Prevents floating-point contractions of mul+add or sub into fma.

__device__​ __half __hmul_sat ( const __half a, const __half b )
Performs half multiplication in round-to-nearest-even mode, with saturation to [0.0, 1.0].
Description
Performs half multiplication of inputs a and b, in round-to-nearest mode, and clamps the result to range [0.0, 1.0]. NaN results are flushed to +0.0.

**Comment by AidanBeltonS** [comment]
I have looked into this issue and can reproduce the error.
The problem is that there are some missing operators.
So the operators +-*/ were functioning via the implicit conversion to floating point type.

I have proposed a solution in #6061

**Comment by TApplencourt** [comment]
Thanks a lot!
