### ISSUE TITLE
question: what is the expected ref-count of devices returned by piDevicesGet ?

### ISSUE THREAD

**Issue by Ralender** [intel/llvm#6034]
I am in the process of writing a plugin and the SYCL runtime usually call my plugin with something like:
```
piPlatformsGet // get count
piPlatformsGet // get value
piDevicesGet // get count
piDevicesGet // get value
...
piDeviceRetain // increment ref-count
...
piDeviceRelease // decrement ref-count
...
```
piDevicesGet return devices with a ref-count of 1,
and there is one call to piDeviceRetain and one to piDeviceRelease. so devices are not cleaned up.

it makes no sense(to me) to have piDevicesGet return devices with ref-count of 0 because ref-count of 0 means the object are already cleaned up and every other pi object are created with a ref-count of 1.

is this a bug ? or am I missing something ?

**Comment by keryell** [comment]
This is somehow related to discussion in https://github.com/intel/llvm/pull/5934

**Comment by romanovvlad** [comment]
Actually, it seems like a bug to me. Will prepare a patch.

**Comment by romanovvlad** [comment]
Should be fixed by https://github.com/intel/llvm/pull/6708
