### ISSUE TITLE
[Windows] CMakeLists.txt requires fixing/improvements

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#605]
I've tried to build this project on Windows: in my setup I don't have pre-built/installed OpenCL ICD and OpenCL Headers and I encountered several issues:

1. value for `OpenCL_LIBRARIES` is set incorrectly:

In the following [line of code](https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L65):
```
  set(OpenCL_LIBRARIES "${LLVM_LIBRARY_OUTPUT_INTDIR}/libOpenCL.so")
```

Instead of `.so` we should use [`CMAKE_SHARED_LIBRARY_SUFFIX`](https://cmake.org/cmake/help/v3.12/variable/CMAKE_SHARED_LIBRARY_SUFFIX.html)

2. By some reason I don't have `make` utility in my setup, so the next problem is [here](https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L73):
```
    CONFIGURE_COMMAND ${CMAKE_COMMAND} "${CMAKE_CURRENT_BINARY_DIR}/OpenCL/icd" -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_PREFIX=${LLVM_BINARY_DIR}
    BUILD_COMMAND     make C_INCLUDE_PATH=${CMAKE_CURRENT_BINARY_DIR}/OpenCL/inc
    INSTALL_COMMAND   make install
```

This section can be simplified by removing all three mentioned parameters. In that case cmake will assume that external project is cmake-based and will perform configuration step automatically, then launch build for default target and then launch default install target. See [documentation](https://cmake.org/cmake/help/v3.12/module/ExternalProject.html?highlight=externalproject_add#command:externalproject_add):

> The default configure command runs CMake with options based on the main project. For non-CMake external projects, the CONFIGURE_COMMAND option must be used to override this behavior

> Overrides the default build command (generator expressions are supported). If this option is not given, the default build command will be chosen to integrate with the main build in the most appropriate way (e.g. using recursive make for Makefile generators or cmake --build if the project uses a CMake build).

> The default install step builds the install target of the external project, but this can be overridden with a custom command using this option (generator expressions are supported).

For passing options we should use `CMAKE_CACHE_ARGS` or `CMAKE_CACHE_DEFAULT_ARGS`. We might encounter problem with `C_INCLUDE_PATH` option which is passed directly to `make` right now, but the proper way to resolve this issue is to contribute into KhronosGroup/OpenCL-ICD-Loader in order to make [`OPENCL_ICD_LOADER_HEADERS_DIR`](https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/master/CMakeLists.txt#L74) configurable.

@v-klochkov, @sndmitriev, @alexbatashev: FYI

**Comment by v-klochkov** [comment]
The 1st and 2nd problems mentioned above are going to be fixed by https://github.com/intel/llvm/pull/528

**Comment by bader** [comment]
@AlexeySachkov, is this issue fixed?

**Comment by AlexeySachkov** [comment]
#528 works for me, thanks!
