### ISSUE TITLE
[SYCL][PI][HIP][CMake] Support non-standard ROCM installation paths

### ISSUE THREAD

**Issue by ajaypanyala** [intel/llvm#6091]
**Is your feature request related to a problem? Please describe**
The HIP build of the compiler fails in the configure step when ROCM is installed in a non-standard location especially when multiple rocm versions exist and are loaded via modules. The CMake infrastructure for the HIP plugins assumes it to always be in `/opt/rocm` as shown [here](https://github.com/intel/llvm/blob/sycl/sycl/plugins/hip/CMakeLists.txt#L26) and [here](https://github.com/intel/llvm/blob/sycl/sycl/plugins/hip/CMakeLists.txt#L8-L9)

The configure step used is as follows:
```CC=gcc CXX=g++ python ./buildbot/configure.py -w ./build_rocm --hip --hip-platform AMD -o ./```

**Describe the solution you would like**
This is already supported in other places as shown [here](https://github.com/intel/llvm/blob/sycl/mlir/lib/ExecutionEngine/CMakeLists.txt#L155-L178). Similar ROCM discovery logic needs to be added to the HIP plugins [part](https://github.com/intel/llvm/blob/sycl/sycl/plugins/hip/CMakeLists.txt).

**Comment by npmiller** [comment]
You're right that we could improve ROCm installation detection but note that you can already point the build to a different ROCm directory, for example, if say your ROCm installation is in `/usr/local/rocm`:

```
CC=gcc CXX=g++ python ./buildbot/configure.py -w ./build_rocm --hip --hip-platform AMD -o . \
  --cmake-opt=-DSYCL_BUILD_PI_HIP_INCLUDE_DIR=/usr/local/rocm/hip/include \
  --cmake-opt=-DSYCL_BUILD_PI_HIP_HSA_INCLUDE_DIR=/usr/local/rocm/hsa/include \
  --cmake-opt=-DSYCL_BUILD_PI_HIP_AMD_LIBRARY=/usr/local/rocm/hip/lib/libamdhip64.so
```

**Comment by ajaypanyala** [comment]
@npmiller Thanks! I added the additional cmake-options you suggested to the configure line and it works well!

**Comment by zjin-lcf** [comment]
I hope the solution may be added to the getting started guide.

**Comment by npmiller** [comment]
The variables are already described in the getting started guide:

* https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-hip-amd

I can add a note that they can be specified with `--cmake-opt` if you want

**Comment by zjin-lcf** [comment]
The note will be helpful. Thanks.
