### ISSUE TITLE
[SYCL][HIP][AMD] Vendor ID for HIP AMD is not correct

### ISSUE THREAD

**Issue by densamoilov** [intel/llvm#6123]
SYCL API returns a vendor ID for HIP AMD that is equal to vendor ID for NVIDIA - 4318 (10DE).

Reproducer:
```cpp
#include <CL/sycl.hpp>
#include <iostream>

int main() {
    auto dev = sycl::device(sycl::gpu_selector{});
    auto vid = dev.template get_info<sycl::info::device::vendor_id>();
    std::cout << vid << std::endl;

    auto name = dev.template get_info<sycl::info::device::name>();
    std::cout << name << std::endl;

    auto vendor = dev.template get_info<sycl::info::device::vendor>();
    std::cout << vendor << std::endl;
    return 0;
}
```
Compile command:
```bash
clang++ -fsycl ./1.cpp
```
Run command:
```bash
./a.out
```
Output:
```bash
4098
gfx908:sramecc+:xnack-
Advanced Micro Devices, Inc.
```

Run command:
```bash
SYCL_DEVICE_FILTER=hip ./a.out
```
Output:
```bash
4318
gfx908:sramecc+:xnack-
AMD Corporation
```

Compiler commit: 92cfd5365ae1040f4b530c6fa73cca7968951b7a

**Comment by densamoilov** [comment]
+@AerialMantis

**Comment by zjin-lcf** [comment]
Is this a vendor ID for all AMD GPU devices ?

**Comment by densamoilov** [comment]
@zjin-lcf, vendor ID for AMD devices is expected to be `4098`.

**Comment by densamoilov** [comment]
It seems that DPC++ with HIP backend always returns 4318, which is vendor ID for NVIDIA. Looks like a bug.

**Comment by steffenlarsen** [comment]
Closing this issue with https://github.com/intel/llvm/pull/6127 merged. @densamoilov - Please reopen if the issue persists.
