### ISSUE TITLE
[SYCL] Some GroupAlgorithm tests disabled for HIP

### ISSUE THREAD

**Issue by cperkinsintel** [intel/llvm#6185]
The GroupAlgorithm tests on llvm-test-suite were recently expanded to ensure that all the binary ops are actually tested.  Unfortunately, this has lead to failures on the HIP side, we are getting undefined symbols for a handful of __spirv__ * functions.  
We have temporarily marked those tests as XFAIL ( https://github.com/intel/llvm-test-suite/pull/1034 ).  However, I suspect that majority of these tests and binary ops work just fine, and only some few are actually failing. Perhaps the root problem could be identified and fixed, or, barring that, the test could be split out so that the HIP coverage is maximal.

**Comment by JackAKirk** [comment]
Fixed by https://github.com/intel/llvm/pull/10656
