### ISSUE TITLE
Unresolved conflict marker in clang/test/Driver/clang-offload-bundler.c

### ISSUE THREAD

**Issue by Ralender** [intel/llvm#6222]
there is unresolved conflict marker at https://github.com/intel/llvm/blob/9c39a30197ba772d3d7a634f155ffa0095216d0d/clang/test/Driver/clang-offload-bundler.c#L117

**Comment by bader** [comment]
@pvchupin, could you take a look, please?

**Comment by pvchupin** [comment]
@smanna12, can you take a look please?
I'm also wondering why our testing don't catch that...

**Comment by smanna12** [comment]
I am looking into this. Not clear to me how we missed it with our testing. I will create a PR to fix the problem.
