### ISSUE TITLE
❓Interoperability of sycl::queue when enabled command list batching

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/llvm#6241]
Using level-zero as example, when I get ```ze_command_queue_handle_t``` from ```get_native``` function, does it immediately execute still opening command list? Or there must be a function that can execute all pending command list before user execute more level-zero command list.

**Comment by dm-vodopyanov** [comment]
@smaslov-intel, could you please comment?

**Comment by smaslov-intel** [comment]
The `get_native` API doesn't specify that. Currently, no, the queue will not be forced to execute its open command-lists (there might be multiple of them, one for copy, another for compute).

A trick for Level Zero backend could be to use the get_native on **the event of the last command** in the queue, which will force that command (with its command-list) to be submitted for execution.

Sounds like another reasonable request for adding a new "flush" queue API.

**Comment by CaoZhongZ** [comment]
Or any chance that we could get the still opened queue, save the flush?

**Comment by smaslov-intel** [comment]
> Or any chance that we could get the still opened queue, save the flush?

@CaoZhongZ : I don't understand the question, can you elaborate?
BTW, I was pointed out that we already proposed ab extension similar to flush: https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_prod.asciidoc

**Comment by CaoZhongZ** [comment]
@smaslov-intel My mistake, flush is good. Go with it.

**Comment by KornevNikita** [comment]
Hi! There have been no updates for at least the last 60 days, though the ticket has assignee(s).

      @smaslov-intel, could I ask you to take one of the following actions? :)
      - Please provide an update if you have any (or just a small comment if you don't have any yet).
      - OR mark this issue with the 'confirmed' label if you have confirmed the problem/request and our team should work on it.
      - OR close the issue if it has been resolved.
      - OR take any other suitable action.

      Thanks!

**Comment by steffenlarsen** [comment]
Hi @CaoZhongZ! The sycl_ext_oneapi_prod extension was implemented in https://github.com/intel/llvm/pull/13555. I am closing this issue as resolved as a result. Please let us know if you have any other problems.
