### ISSUE TITLE
Sampler/unnormalized-* tests from llvm-test-suite fails on CUDA target

### ISSUE THREAD

**Issue by pvchupin** [intel/llvm#6285]
These tests from llvm-test-suite are currently failing on CUDA target

```
Failed Tests (3):
  SYCL :: Sampler/unnormalized-clamp-nearest.cpp
  SYCL :: Sampler/unnormalized-clampedge-nearest.cpp
  SYCL :: Sampler/unnormalized-none-nearest.cpp
```

These are temporary disabled on CUDA to recover CUDA pre-commit testing.
Need to be reenabled back as soon as fixed.

**Comment by AerialMantis** [comment]
We believe this issue has been addressed by https://github.com/intel/llvm/pull/6335 and the tests re-enabled in https://github.com/intel/llvm-test-suite/pull/1062, so we will close the ticket.
