### ISSUE TITLE
cannot open shared object file : No such file or directory

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#6301]
**Describe the bug**
build intel/llvm compile cuda toolchain in release tag version[[2021-12](https://github.com/intel/llvm/tree/2021-12)]

and reference discussion here #4926 to revise source files. There is a workaround which proposes to comment out 3-4 lines here

https://github.com/intel/llvm/blob/7fb56cf563e3bf9e4b4a462f21f60596d6687f39/sycl/source/CMakeLists.txt#L55-L58

The compile process is normally until I run a example case.

<details>
<summary>my example code</summary>

```
#include <CL/sycl.hpp>

void show_platforms() {
  auto platforms = sycl::platform::get_platforms();

  for (auto &platform : platforms) {
    std::cout << "Platform: "
	      << platform.get_info<sycl::info::platform::name>()
	      << std::endl;

    auto devices = platform.get_devices();
    for (auto &device : devices ) {
      std::cout << "  Device: "
		<< device.get_info<sycl::info::device::name>()
		<< std::endl;
    }
  }
}

int main() {

  show_platforms();
  // auto name = sycl::info::platform::name;
  // auto con = cl::sycl::context();
  // auto properties = cl::sycl::property_list();
  // Creating buffer of 4 ints to be used inside the kernel code
  cl::sycl::buffer<cl::sycl::cl_int, 1> Buffer(4);

  //sycl::gpu_selector s;

  // Creating SYCL queue
  cl::sycl::queue Queue;
  //cl::sycl::queue Queue();

  auto dev = Queue.get_device();
  std::cout<<"================================"<<std::endl;
  std::cout << "Default Device: "
		<< dev.get_info<sycl::info::device::name>()
		<< std::endl;

  // Size of index space for kernel
  cl::sycl::range<1> NumOfWorkItems{Buffer.size()};

  // Submitting command group(work) to queue
  Queue.submit([&](cl::sycl::handler &cgh) {
    // Getting write only access to the buffer on a device
    auto Accessor = Buffer.get_access<cl::sycl::access::mode::write>(cgh);
    // Executing kernel
    cgh.parallel_for<class FillBuffer>(
        NumOfWorkItems, [=](cl::sycl::id<1> WIid) {
          // Fill buffer with indexes
          Accessor[WIid] = (cl::sycl::cl_int)WIid.get(0);
        });
  });

  // Getting read only access to the buffer on the host.
  // Implicit barrier waiting for queue to complete the work.
  const auto HostAccessor = Buffer.get_access<cl::sycl::access::mode::read>();

  // Check the results
  bool MismatchFound = false;
  for (size_t I = 0; I < Buffer.size(); ++I) {
    if (HostAccessor[I] != I) {
      std::cout << "The result is incorrect for element: " << I
                << " , expected: " << I << " , got: " << HostAccessor[I]
                << std::endl;
      MismatchFound = true;
    }
  }

  if (!MismatchFound) {
    std::cout << "The results are correct!" << std::endl;
  }

  return MismatchFound;
}
```
</details>

<details>
<summary>my CMakeLists.txt</summary>

```
cmake_minimum_required(VERSION 2.8.12)

set(DPCPP_HOME "/home/wzy/sycl_workspace")
set(DPCPP_SYCL_HOME "${DPCPP_HOME}/build-cuda-debug")

set(CMAKE_C_COMPILER "${DPCPP_SYCL_HOME}/bin/clang")
set(CMAKE_CXX_COMPILER "${DPCPP_SYCL_HOME}/bin/clang++")
set(CMAKE_CXX_STANDARD 17)

project(simple-sycl-app)


message(STATUS "dpcpp_home : "${DPCPP_HOME})
message(STATUS "dpcpp_cuda_sycl_home : "${DPCPP_SYCL_HOME})

include_directories("${DPCPP_SYCL_HOME}/build-cuda-debug/include")
include_directories("${DPCPP_SYCL_HOME}/build-cuda-debug/include/sycl")

link_directories("${DPCPP_SYCL_HOME}/build-cuda-debug/lib")

set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")

add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)

aux_source_directory(. DIR_SRCS)
add_executable(simple-sycl-app ${DIR_SRCS})
#target_link_libraries(simple-sycl-app -fsycl -fsycl-targets=nvptx64-nvidia-cuda -lsycl)
target_link_libraries(simple-sycl-app  -lsycl)
```
</details>

The result is that simple-sycl-app: error while loading shared libraries: libsycl.so.5: cannot open shared object file: No such file or directory

![image](https://user-images.githubusercontent.com/22990858/173509531-96d9d4cc-f9aa-4fca-a3a0-6cb06acc5dd6.png)

my intel/llvm install path:
/home/wzy/sycl_workspace/build-cuda-debug/lib

![image](https://user-images.githubusercontent.com/22990858/173509706-799fcf17-dfec-411a-a494-d02752cae6e7.png)

how to solve the problem?

**To Reproduce**

1. Include code snippet as short as possible
2. Specify the command which should be used to compile the program
3. Specify the comment which should be used to launch the program
4. Indicate what is wrong and what was expected

**Environment (please complete the following information):**

- OS: [e.g Windows/Linux]
- centos7.9 NVIDIA GPU
- DPC++ version: clang version 14.0.0 (/home/wzy/sycl_workspace/llvm/clang b4771da657843317235c5e3d662b7fceea41f58e)
- Dependencies version: cuda runtime

**Additional context**

**Comment by npmiller** [comment]
This is because `libsycl.so` is not in your library search path, as a workaround you can modify `LD_LIBRARY_PATH` as follows:

```
export LD_LIBRARY_PATH=/home/wzy/sycl_workspace/build-cuda-debug/lib:$LD_LIBRARY_PATH
```

Also note that you don't need to explicitly link against the SYCL library with `-lsycl`, `-fsycl` will take care of that. Which is also why CMake isn't able to set the `RPATH` for libsycl properly, there's probably some room for improvement here but at the moment you should use `LD_LIBRARY_PATH`.

**Comment by wangzy0327** [comment]
> This is because `libsycl.so` is not in your library search path, as a workaround you can modify `LD_LIBRARY_PATH` as follows:
> 
> ```
> export LD_LIBRARY_PATH=/home/wzy/sycl_workspace/build-cuda-debug/lib:$LD_LIBRARY_PATH
> ```
> 
> Also note that you don't need to explicitly link against the SYCL library with `-lsycl`, `-fsycl` will take care of that. Which is also why CMake isn't able to set the `RPATH` for libsycl properly, there's probably some room for improvement here but at the moment you should use `LD_LIBRARY_PATH`.

OK，I know to add LD_LIBRARY_PATH could to solve it problem. I am not familer with Cmake. Is it can be solved in CMake way?

**Comment by npmiller** [comment]
With CMake you can add it to the `RPATH`:

```cmake 
set(CMAKE_BUILD_RPATH "/home/wzy/sycl_workspace/build-cuda-debug/lib;${CMAKE_BUILD_RPATH}")
```

CMake usually does it automatically but I believe that because `libsycl` is linked through `-fsycl` it doesn't know to do it.
