### ISSUE TITLE
compile intel/llvm source FAILED

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#6319]
**Describe the bug**
I compiles  SYCL cuda toolchain source files with code refer to [GetStartGuide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md)

When I execute "python $DPCPP_HOME/llvm/buildbot/compile.py" , I get error . Besides my gcc version is gcc-9.5.0（build from source）and OS is Centos 7.9

![1655426456922](https://user-images.githubusercontent.com/22990858/174200144-46660c5d-364b-4f18-8d5c-9f00918da06e.png)

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. Include code snippet as short as possible
2. Specify the command which should be used to compile the program
3. Specify the comment which should be used to launch the program
4. Indicate what is wrong and what was expected

**Environment (please complete the following information):**

- OS: [e.g CentOS 7.9]
- Target device and vendor: [e.g. NVIDIA GPU]
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g.CUDA 11.2]

**Additional context**
python3

**Comment by changbozhu** [comment]
Centos 7.9 is not supported by DPC++ toolchain

**Comment by changbozhu** [comment]
I recommended to try ubuntu 18.04LTS ubuntu 20.04LTS on your PC or redhat8.x on your server

**Comment by bader** [comment]
> Besides my gcc version is gcc-9.5.0（build from source）

I think some part of libstdc++ is not properly configured/built.

**Comment by steffenlarsen** [comment]
Hi @wangzy0327 . What is the status on this? Did you have any luck getting it to work?
