### ISSUE TITLE
LLD is not installed for HIP backend

### ISSUE THREAD

**Issue by densamoilov** [intel/llvm#6338]
I'm not sure whether it's an expected behavior or not, but LLD linker is not copied from `build/bin` to `build/install/bin` directory. Since it's required for AMD target and users tend to add only `build/install/bin` to `PATH` it can cause unexpected issues.

**Comment by bader** [comment]
I see that lld is installed separately in our CI.
https://github.com/intel/llvm/blob/sycl/.github/workflows/sycl_linux_build_and_test.yml#L154-L155
