### ISSUE TITLE
[Experimental CPU runtime] No platforms after installation

### ISSUE THREAD

**Issue by reguly** [intel/llvm#634]
I am having some trouble with installing/using the experimental CPU runtime. I have a Intel(R) Xeon(R) Gold 6126 CPU, running CentOS Linux release 7.6.1810 (Core). I installed the opencl-headers, clinfo, and ocl-icd packages with yum, and followed the instructions [here](https://github.com/intel/llvm/releases/tag/oclcpuexp-2019.8.7.0.0725_rel).
I do get a warning about the python file: `ldconfig: /opt/intel/oclcpuexp/x64/libintelocl.so-gdb.py is not an ELF file - it has the wrong magic bytes at the start`, but otherwise things finish fine.
`ldconfig -p` does list all the so files in  /opt/intel/oclcpuexp/x64. That directory, and all the files in them have 755 permissions.

Yet, when I run clinfo, I get 0 platforms. OpenCL and SYCL applications also fail to select the CPU device. What am I missing here? How could I get further info about where things go wrong?

(l_opencl_p_18.1.0.015 (the official Intel CPU OpenCL runtime) installs and works fine, though during installation it complains about not finding libstdc++.so.6 and others - I have uninstalled it and rebuilt the ldconfig cache before trying to install the experimental CPU runtime).

**Comment by yxliang01** [comment]
@reguly After installing the updated build toolchain, does the issue with `clinfo` not showing platform resolve?

**Comment by reguly** [comment]
@yxliang01 It seems so unfortunately.

- On CentOS 7.6, which comes with GCC 4.8, after installing  oclcpuexp-2020.10.4.0.15, `clinfo` shows no platforms. 
- Once I load GCC 9.2, which has a newer libstdc++, `clinfo` does show the CPU. 
- I can compile `clang++ simple-sycl-app.cpp -fsycl -L/home/shared/software/gcc/9.2.0/lib64`
- ldd shows the correct things
- I get a runtime error:
`terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  Attempt to set multiple actions for the command group. Command group must consist of a single kernel or explicit memory operation. -59 (CL_INVALID_OPERATION)`
- If I try to print the name of the device, right after creating Queue:
`std::cout << "Running on " << Queue.get_device().get_info<cl::sycl::info::device::name>() << "\n";`
I get a huge binary dump of some sort (thousands of lines of jibberish)

**Comment by bader** [comment]
> * I get a runtime error:
>   `terminate called after throwing an instance of 'cl::sycl::runtime_error' what():  Attempt to set multiple actions for the command group. Command group must consist of a single kernel or explicit memory operation. -59 (CL_INVALID_OPERATION)`

This is a bug in the app.

**Comment by reguly** [comment]
@bader this is the copy-pasted simple-sycl-app.cpp from https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#test-dpc-toolchain

**Comment by bader** [comment]
I can't reproduce this issue and exception states that command group has more than one kernel, which is prohibited by the specification.
I'm not sure how GCC configuration might lead to this type of error, so I suggest checking that the app is not modified after "copy-paste".

**Comment by reguly** [comment]
I double checked, here is the process. Also printed some environment variables and the output of ldd. 

[reguly@haar oclexp]$ export LD_LIBRARY_PATH=`pwd`/dpcpp_compiler/lib:$LD_LIBRARY_PATH
[reguly@haar oclexp]$ export PATH=`pwd`/dpcpp_compiler/bin:$PATH
[reguly@haar oclexp]$ module load gcc/9.2.0
[reguly@haar oclexp]$ echo $PATH
/home/shared/software/gcc/9.2.0//bin:/home/reguly/oclexp/dpcpp_compiler/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/reguly/.local/bin:/home/reguly/bin
[reguly@haar oclexp]$ echo $LD_LIBRARY_PATH
/home/shared/software/gcc/9.2.0//lib:/home/shared/software/gcc/9.2.0//lib64:/home/reguly/oclexp/dpcpp_compiler/lib:
[reguly@haar oclexp]$ cat test.cpp
#include <CL/sycl.hpp>

int main() {
  // Creating buffer of 4 ints to be used inside the kernel code
  cl::sycl::buffer<cl::sycl::cl_int, 1> Buffer(4);

  // Creating SYCL queue
  cl::sycl::queue Queue;

  // Size of index space for kernel
  cl::sycl::range<1> NumOfWorkItems{Buffer.get_count()};

  // Submitting command group(work) to queue
  Queue.submit([&](cl::sycl::handler &cgh) {
    // Getting write only access to the buffer on a device
    auto Accessor = Buffer.get_access<cl::sycl::access::mode::write>(cgh);
    // Executing kernel
    cgh.parallel_for<class FillBuffer>(
        NumOfWorkItems, [=](cl::sycl::id<1> WIid) {
          // Fill buffer with indexes
          Accessor[WIid] = (cl::sycl::cl_int)WIid.get(0);
        });
  });

  // Getting read only access to the buffer on the host.
  // Implicit barrier waiting for queue to complete the work.
  const auto HostAccessor = Buffer.get_access<cl::sycl::access::mode::read>();

  // Check the results
  bool MismatchFound = false;
  for (size_t I = 0; I < Buffer.get_count(); ++I) {
    if (HostAccessor[I] != I) {
      std::cout << "The result is incorrect for element: " << I
                << " , expected: " << I << " , got: " << HostAccessor[I]
                << std::endl;
      MismatchFound = true;
    }
  }

  if (!MismatchFound) {
    std::cout << "The results are correct!" << std::endl;
  }

  return MismatchFound;
}

[reguly@haar oclexp]$ clang++ test.cpp -fsycl -L/home/shared/software/gcc/9.2.0/lib64
[reguly@haar oclexp]$ ldd a.out
	linux-vdso.so.1 =>  (0x00007ffe8dd58000)
	libstdc++.so.6 => /home/shared/software/gcc/9.2.0//lib64/libstdc++.so.6 (0x00007fe226630000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe22632e000)
	libgcc_s.so.1 => /home/shared/software/gcc/9.2.0//lib64/libgcc_s.so.1 (0x00007fe226116000)
	libsycl.so.1 => /home/reguly/oclexp/dpcpp_compiler/lib/libsycl.so.1 (0x00007fe225c20000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe225853000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe226a09000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe22564f000)
	libOpenCL.so.1 => /home/reguly/oclexp/dpcpp_compiler/lib/libOpenCL.so.1 (0x00007fe225446000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe22522a000)
[reguly@haar oclexp]$ ./a.out
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  Attempt to set multiple actions for the command group. Command group must consist of a single kernel or explicit memory operation. -59 (CL_INVALID_OPERATION)
Aborted (core dumped)

**Comment by reguly** [comment]
The hello world example from:
https://us.fixstars.com/products/opencl/book/OpenCLProgrammingBook/first-opencl-program/
does work on the CPU (there are no other OpenCL devices in the system).

**Comment by bader** [comment]
@romanovvlad, any ideas why runtime might throw this exception?

> what(): Attempt to set multiple actions for the command group. Command group must consist of a single kernel or explicit memory operation. -59 (CL_INVALID_OPERATION)
