### ISSUE TITLE
SYCL-toolchain cannot build by CMake? 

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#6372]
**Describe the bug**
sycl-example build by cmake execuate error

sycl build from source release version [2021-12](https://github.com/intel/llvm/tree/2021-12)

<details>
<summary>simple-sycl-app</summary>

```
#include <CL/sycl.hpp>

void show_platforms() {
  auto platforms = sycl::platform::get_platforms();

  for (auto &platform : platforms) {
    std::cout << "Platform: "
	      << platform.get_info<sycl::info::platform::name>()
	      << std::endl;

    auto devices = platform.get_devices();
    for (auto &device : devices ) {
      std::cout << "  Device: "
		<< device.get_info<sycl::info::device::name>()
		<< std::endl;
    }
  }
}

int main() {

  show_platforms();
  // auto name = sycl::info::platform::name;
  // auto con = cl::sycl::context();
  // auto properties = cl::sycl::property_list();
  // Creating buffer of 4 ints to be used inside the kernel code
  cl::sycl::buffer<cl::sycl::cl_int, 1> Buffer(4);

  //sycl::gpu_selector s;

  // Creating SYCL queue
  cl::sycl::queue Queue;
  //cl::sycl::queue Queue();

  auto dev = Queue.get_device();
  std::cout<<"================================"<<std::endl;
  std::cout << "Default Device: "
		<< dev.get_info<sycl::info::device::name>()
		<< std::endl;

  // Size of index space for kernel
  cl::sycl::range<1> NumOfWorkItems{Buffer.size()};

  // Submitting command group(work) to queue
  Queue.submit([&](cl::sycl::handler &cgh) {
    // Getting write only access to the buffer on a device
    auto Accessor = Buffer.get_access<cl::sycl::access::mode::write>(cgh);
    // auto out = sycl::stream(1024, 768, cgh);
    // auto task = [=]() { out << "In a task\n"; };
    // Executing kernel
    cgh.parallel_for<class FillBuffer>(
        NumOfWorkItems, [=](cl::sycl::id<1> WIid) {
          // out<<"parallel for before\n";
          // Fill buffer with indexes
          Accessor[WIid] = (cl::sycl::cl_int)WIid.get(0);
        });
    // cgh.single_task<class stream_task>(task);
  });

  // Getting read only access to the buffer on the host.
  // Implicit barrier waiting for queue to complete the work.
  const auto HostAccessor = Buffer.get_access<cl::sycl::access::mode::read>();

  // Check the results
  bool MismatchFound = false;
  for (size_t I = 0; I < Buffer.size(); ++I) {
    if (HostAccessor[I] != I) {
      std::cout << "The result is incorrect for element: " << I
                << " , expected: " << I << " , got: " << HostAccessor[I]
                << std::endl;
      MismatchFound = true;
    }
  }

  if (!MismatchFound) {
    std::cout << "The results are correct!" << std::endl;
  }

  return MismatchFound;
}


```

</details>

<details>
<summary>CMakeLists.txt</summary>

```
cmake_minimum_required(VERSION 2.8.12)

set(CMAKE_C_COMPILER "/home/wzy/sycl_workspace/build-cuda/bin/clang")
set(CMAKE_CXX_COMPILER "/home/wzy/sycl_workspace/build-cuda/bin/clang++")
set(CMAKE_CXX_STANDARD 17)

project(simple-sycl-app)

set(DPCPP_HOME "/home/wzy/sycl_workspace")
set(DPCPP_SYCL_HOME "${DPCPP_HOME}/build-cuda")


message(STATUS "dpcpp_home : ${DPCPP_HOME}")
message(STATUS "dpcpp_cuda_sycl_home : ${DPCPP_SYCL_HOME}")


#link_directories("${DPCPP_SYCL_HOME}/build-cuda-debug/lib")
message(STATUS "find library path : ${DPCPP_SYCL_HOME}/lib")
set(CMAKE_BUILD_RPATH "${DPCPP_SYCL_HOME}/lib;${CMAKE_BUILD_RPATH}")
message(STATUS "cmake build rpath : ${CMAKE_BUILD_RPATH}")

# set(CMAKE_BUILD_PATH "${DPCPP_SYCL_HOME}/lib:${CMAKE_BUILD_PATH}")

set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")

# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")

add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)

link_directories("${DPCPP_SYCL_HOME}/lib")

aux_source_directory(. DIR_SRCS)
add_executable(simple-sycl-app ${DIR_SRCS})
add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
#target_link_libraries(simple-sycl-app -fsycl -fsycl-targets=nvptx64-nvidia-cuda -lsycl)
# target_link_libraries(simple-sycl-app PRIVATE ${SYCL} )
target_link_libraries(simple-sycl-app PRIVATE sycl )
```

</details>

![image](https://user-images.githubusercontent.com/22990858/176341984-dec83459-664f-4420-926a-814ad847286e.png)

![image](https://user-images.githubusercontent.com/22990858/176342014-b46c2732-f35c-4773-8699-d5f1a74f18f1.png)

![image](https://user-images.githubusercontent.com/22990858/176342140-781863e9-ac41-464c-875c-4b9baeb6e1ef.png)

how to solve the problem?

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. Include code snippet as short as possible
2. Specify the command which should be used to compile the program
3. Specify the comment which should be used to launch the program
4. Indicate what is wrong and what was expected

**Environment (please complete the following information):**

- OS: ubuntu-server 18.04
- Target device and vendor: Nvidia GPU V100-PCIE-32G
- DPC++ version: clang version 14.0.0
- Dependencies version: cuda-11.2

**Additional context**

**Comment by wangzy0327** [comment]
> Do you still have the problem with the latest release (https://github.com/intel/llvm/releases/tag/2022-06)?

Yes, I also tried it in  the latest release (https://github.com/intel/llvm/releases/tag/2022-06)

this is log in release/tag/2022-06

<details>

<summary>run sycl-simple-app in 2022-06</summary>

```
$cmake -B build-rpath-cmake

-- The C compiler identification is Clang 15.0.0
-- The CXX compiler identification is Clang 15.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/wzy/sycl_workspace/build-cuda/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/wzy/sycl_workspace/build-cuda/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- dpcpp_home : /home/wzy/sycl_workspace
-- dpcpp_cuda_sycl_home : /home/wzy/sycl_workspace/build-cuda
-- find library path : /home/wzy/sycl_workspace/build-cuda/lib
-- cmake build rpath : /home/wzy/sycl_workspace/build-cuda/lib;
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wzy/sycl_workspace/dpcpp-application/simple-sycl-app/build-rpath-cmake
wzy@gxnzx1277:~/sycl_workspace/dpcpp-application/simple-sycl-app$ cmake --build build-rpath-cmake
Scanning dependencies of target simple-sycl-app
[ 50%] Building CXX object CMakeFiles/simple-sycl-app.dir/simple-sycl-app.cpp.o
warning: linking module '/home/wzy/sycl_workspace/build-cuda/lib/clang/15.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc': Linking two modules of different target triples: '/home/wzy/sycl_workspace/build-cuda/lib/clang/15.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc' is 'nvptx64-unknown-nvidiacl' whereas '/home/wzy/sycl_workspace/dpcpp-application/simple-sycl-app/simple-sycl-app.cpp' is 'nvptx64-nvidia-cuda'
 [-Wlinker-warnings]
1 warning generated.
[100%] Linking CXX executable simple-sycl-app
[100%] Built target simple-sycl-app

$./build-rpath-cmake/simple-sycl-app

Platform: NVIDIA CUDA BACKEND
  Device: Tesla V100-PCIE-32GB
Platform: NVIDIA CUDA BACKEND
  Device: Tesla V100-PCIE-32GB
Platform: SYCL host platform
  Device: SYCL host device
================================
Default Device: Tesla V100-PCIE-32GB
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  No kernel named _ZTSZZ4mainENKUlRN2cl4sycl7handlerEE_clES2_E10FillBuffer was found -46 (CL_INVALID_KERNEL_NAME)
Aborted (core dumped)

```

</details>

**Comment by npmiller** [comment]
The issue is that you set the link flags before calling `add_executable` so they are not applied to the link command so it doesn't link in SYCL mode and the kernel code gets dropped, the following change to your `CMakeLists.txt` fixes it:

```diff
+++ CMakeLists.txt.orig 2022-07-06 10:50:37.524388748 +0100
--- CMakeLists.txt      2022-07-06 10:49:53.564221071 +0100
@@ -29,12 +29,12 @@
 # include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
 
 add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
+add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
 
 link_directories("${DPCPP_SYCL_HOME}/lib")
 
 aux_source_directory(. DIR_SRCS)
 add_executable(simple-sycl-app ${DIR_SRCS})
-add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
 target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
 target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
 #target_link_libraries(simple-sycl-app -fsycl -fsycl-targets=nvptx64-nvidia-cuda -lsycl)

```

Since the SYCL flags are needed for both compilation and linking it may be easier to add them to `CMAKE_CXX_FLAGS` rather than pass them to `add_compile_options` and `add_link_options`.

Also note that when using `-fsycl` `clang++` will implicitly link against `libsycl.so`, and set the correct link and include directories, so you could simplify your `CMakeLists.txt` a lot, for example:

```diff
--- CMakeLists.txt.orig 2022-07-06 10:50:37.524388748 +0100
+++ CMakeLists.txt      2022-07-06 10:58:01.196026555 +0100
@@ -22,21 +22,9 @@
 # set(CMAKE_BUILD_PATH "${DPCPP_SYCL_HOME}/lib:${CMAKE_BUILD_PATH}")
 
 set(CMAKE_BUILD_TYPE "Debug")
+set(CMAKE_CXX_FLAGS "-fsycl -fsycl-targets=nvptx64-nvidia-cuda")
 set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
 set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")
 
-# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
-# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
-
-add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
-
-link_directories("${DPCPP_SYCL_HOME}/lib")
-
 aux_source_directory(. DIR_SRCS)
 add_executable(simple-sycl-app ${DIR_SRCS})
-add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
-target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
-target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
-#target_link_libraries(simple-sycl-app -fsycl -fsycl-targets=nvptx64-nvidia-cuda -lsycl)
-# target_link_libraries(simple-sycl-app PRIVATE ${SYCL} )
-target_link_libraries(simple-sycl-app PRIVATE sycl )
```

With these changes building the sample works fine for me.

**Comment by wangzy0327** [comment]
> The issue is that you set the link flags before calling `add_executable` so they are not applied to the link command so it doesn't link in SYCL mode and the kernel code gets dropped, the following change to your `CMakeLists.txt` fixes it:
> 
> ```diff
> +++ CMakeLists.txt.orig 2022-07-06 10:50:37.524388748 +0100
> --- CMakeLists.txt      2022-07-06 10:49:53.564221071 +0100
> @@ -29,12 +29,12 @@
>  # include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
>  
>  add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
> +add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
>  
>  link_directories("${DPCPP_SYCL_HOME}/lib")
>  
>  aux_source_directory(. DIR_SRCS)
>  add_executable(simple-sycl-app ${DIR_SRCS})
> -add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
>  target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
>  target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
>  #target_link_libraries(simple-sycl-app -fsycl -fsycl-targets=nvptx64-nvidia-cuda -lsycl)
> ```
> 
> Since the SYCL flags are needed for both compilation and linking it may be easier to add them to `CMAKE_CXX_FLAGS` rather than pass them to `add_compile_options` and `add_link_options`.
> 
> Also note that when using `-fsycl` `clang++` will implicitly link against `libsycl.so`, and set the correct link and include directories, so you could simplify your `CMakeLists.txt` a lot, for example:
> 
> ```diff
> --- CMakeLists.txt.orig 2022-07-06 10:50:37.524388748 +0100
> +++ CMakeLists.txt      2022-07-06 10:58:01.196026555 +0100
> @@ -22,21 +22,9 @@
>  # set(CMAKE_BUILD_PATH "${DPCPP_SYCL_HOME}/lib:${CMAKE_BUILD_PATH}")
>  
>  set(CMAKE_BUILD_TYPE "Debug")
> +set(CMAKE_CXX_FLAGS "-fsycl -fsycl-targets=nvptx64-nvidia-cuda")
>  set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
>  set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")
>  
> -# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
> -# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
> -
> -add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
> -
> -link_directories("${DPCPP_SYCL_HOME}/lib")
> -
>  aux_source_directory(. DIR_SRCS)
>  add_executable(simple-sycl-app ${DIR_SRCS})
> -add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
> -target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
> -target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
> -#target_link_libraries(simple-sycl-app -fsycl -fsycl-targets=nvptx64-nvidia-cuda -lsycl)
> -# target_link_libraries(simple-sycl-app PRIVATE ${SYCL} )
> -target_link_libraries(simple-sycl-app PRIVATE sycl )
> ```
> 
> With these changes building the sample works fine for me.

OK，thank you ！ The samples works fine following your instructions.

**Comment by AlexeySachkov** [comment]
@wangzy0327, am I right that we can now close this issue?

**Comment by steffenlarsen** [comment]
Added stale label due to no response from reporter. @wangzy0327 - Please let us know if you are still having issues.
