### ISSUE TITLE
failed to link program with g++

### ISSUE THREAD

**Issue by guoyejun** [intel/llvm#6576]
I have two source files, main.cpp and device.cpp, they are compiler into .o files with dpcpp, and then, it works to link with dpcpp, but it failed to link with g++, is this a bug (need to fix dpcpp or fix my command line) or is expected (it is a must to use dpcpp for the link)? thanks.

main.cpp
```
#include <CL/sycl.hpp>
#include <unistd.h>

void device_fun(sycl::queue &q, int *data, const int num_ints);

int main() {
  sycl::property_list properties{sycl::property::queue::enable_profiling(), sycl::property::queue::in_order()};
  auto q = sycl::queue(sycl::gpu_selector(), properties);

  std::cout
      << "  Platform: "
      << q.get_device().get_platform().get_info<sycl::info::platform::name>()
      << std::endl;

  const int num_ints = 1024 * 1024;
  const size_t num_bytes = num_ints * sizeof(int);

  // Alloc memory on device
  auto data = sycl::malloc_device<int>(num_ints, q);
  q.memset(data, 0x12, num_bytes).wait();

  device_fun(q, data, num_ints);

  std::cout << "program finished." << std::endl;

  sycl::free(data, q);
  return 0;
}
```

device.cpp
```
#include <CL/sycl.hpp>
#include <unistd.h>

void device_fun(sycl::queue &q, int *data, const int num_ints)
{
  auto e2 = q.submit([&](sycl::handler &h) {
      h.parallel_for(num_ints, [=](cl::sycl::item<1> item) {
          int idx = item.get_id(0);
          for (int i = 0; i < 10000; ++i)
            data[idx] = int(sycl::sin(float(data[idx]))) + idx;
      });
  });
  e2.wait();
}
```

run:
```
$ dpcpp -c main.cpp -o main.o
$ dpcpp -c device.cpp -o device.o

// it works with dpcpp for the link
$ dpcpp -o a.out main.o device.o
$ ./a.out
  Platform: Intel(R) Level-Zero
program finished.

// it fails with g++ for the link
$ g++ -o a.out main.o device.o -lsycl -L...../lib/intel64_lin -lintlc
$ ./a.out
  Platform: Intel(R) Level-Zero
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  No kernel named _ZTSZZ10device_funRN2cl4sycl5queueEPiiENKUlRNS0_7handlerEE_clES5_EUlNS0_4itemILi1ELb1EEEE_ was found -46 (CL_INVALID_KERNEL_NAME)
Aborted (core dumped)

```

**Comment by cperkinsintel** [comment]
@bader , @mdtoguchi can either of you advise?

**Comment by mdtoguchi** [comment]
@cperkinsintel, This linking model does not work.  The link step requires the usage of `dpcpp` to be successful.  `g++` does not know anything about the generated fat objects from the `dpcpp` compilation, and also does not know about device code linking (and a natural extension, any AOT requirements).

Use of `g++` here will only link the host part of the given objects so the entirety of the device code will be missing.

**Comment by guoyejun** [comment]
thanks @cperkinsintel  @mdtoguchi  for the answers.

And want to more about why, is it related to `Diagram 2. Split compilation and linkage.` in https://github.com/intel/llvm/blob/sycl/sycl/doc/design/CompilerAndRuntimeDesign.md ?
![image](https://user-images.githubusercontent.com/10448440/184480619-a46245a3-79a8-4ea2-8041-954bc0a56d94.png)

main.o and object.o are fat objects as the results of  compile step, and in link stag, g++ is unable to do 'offload (un)bundler', g++ just extracts the `Host object` from the fat objects and links these host objects. Is my understanding correct? thanks.

**Comment by bader** [comment]
> g++ just extracts the `Host object` from the fat objects and links these host objects. Is my understanding correct?

Fat objects are regular host object files with device code being stored as data blobs + "registration data". g++ treats all object files as regular host object files, so linking of device code is completely skipped and "registration data" are invalidated.
The runtime library relies on offload-bundler tool to register device binary, but g++ doesn't invoke offload tools.

**Comment by guoyejun** [comment]
thanks @bader
