### ISSUE TITLE
[CPU runtime] Crash in LLVM when compiling bitonic sort from PyOpenCL

### ISSUE THREAD

**Issue by inducer** [intel/llvm#6607]
**Describe the bug**
Upon running
```
# Suffices if "intel" is unique among your platform names, otherwise adjust or use 0-based index.
export PYOPENCL_TEST=intel

git clone https://github.com/inducer/pyopencl.git
cd pyopencl
git checkout 3a96299f0e60248aa11261646d82155c0c6bbd89
python3 -m venv .test-env
source .test-env/bin/activate
pip install .
pip install pytest mako
cd test
python -m pytest -k test_bitonic_sort
```
I get a segmentation fault (apparently) deep inside the kernel compiler, with the following backtrace: https://gist.github.com/inducer/98c365a429a09faccb551712c72720ae.

**Environment (please complete the following information):**

- OS: Linux 5.19.0-trunk-amd64, Debian testing
- Target device and vendor: Intel CPU, Icelake Client
- Dependencies version: https://github.com/intel/llvm/releases/tag/2022-WW33

**Comment by zhaomaosu** [comment]
@inducer, thank you for reporting this bug. We will analyze and fix it. BTW, could you please tell us how you fully tested the pyopencl with cpu runtime? I asked this because there are longer interval between releases. We can do such testing internally to aovid such round-fixing...

**Comment by inducer** [comment]
Certainly, thanks for offering! The instructions are similar to the above:
```
# Suffices if "intel" is unique among your platform names, otherwise adjust or use 0-based index.
export PYOPENCL_TEST=intel

git clone https://github.com/inducer/pyopencl.git
cd pyopencl
python3 -m venv .test-env
source .test-env/bin/activate
pip install .
pip install pytest mako
cd test
python -m pytest
```
Let me know if you run into trouble with them.

These instructions use the `main` branch. You can verify that this is passing tests (across various ICDs) from the badges in the README: https://github.com/inducer/pyopencl. Note that I've xfailed the tests of this issue in the test suite for now: https://github.com/inducer/pyopencl/commit/5a1d37c33e787e48b73d763423505b83ed35f4fa (so you may want to un-xfail them, but there are other failures as well.)

**Comment by Nuullll** [comment]
@inducer Sorry for the late response.
It's been fixed since https://github.com/intel/llvm/releases/tag/sycl-nightly%2F20221215!

**Comment by inducer** [comment]
Thanks! I can confirm that this is fixed.

**Comment by inducer** [comment]
Here's the next one: #7877
