### ISSUE TITLE
Building for Nvidia GPU

### ISSUE THREAD

**Issue by e404044** [intel/llvm#6682]
I just built my sycl_workspace with support for cuda. The commands I ran to build the environment were 
`git clone https://github.com/intel/llvm.git -b sycl
cd llvm
python ./buildbot/configure.py --cuda -t release --cmake-gen "Unix Makefiles"
cd build
make sycl-toolchain -j `nproc`
make install`

I then made this script from one of the templated scripts. just changed the target device in the queue to gpu.

#include <CL/sycl.hpp>
#include <iostream>
using namespace sycl;
int main() {
    // Create queue to use the host device explicitly
    queue Q{ gpu_selector{} };
    std::cout << "Selected device: " <<
        Q.get_device().get_info<info::device::name>() << "\n";
    std::cout << " -> Device vendor: " <<
        Q.get_device().get_info<info::device::vendor>() << "\n";
return 0;
}

[19:39]ec2-user$ whereis clang++
clang++: /data_disk01/wsa/projects/sycl_workspace/llvm/build/bin/clang++

[19:39]ec2-user$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda selected-device-app.cpp -o selected-device-gpu
clang-16: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
warning: linking module '/data_disk01/wsa/projects/sycl_workspace/llvm/build/lib/clang/16.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc': Linking two modules of different target tri
ples: '/data_disk01/wsa/projects/sycl_workspace/llvm/build/lib/clang/16.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc' is 'nvptx64-unknown-nvidiacl' whereas 'selected-device-app.cpp
' is 'nvptx64-nvidia-cuda'
 [-Wlinker-warnings]
1 warning generated.

[19:39]ec2-user$ ./selected-device-gpu
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  No device of requested type available. -1 (PI_ERROR_DEVICE_NOT_FOUND)
Aborted (core dumped)

Anyone have any recommendations? the simple-sycl-app that everyone's probably familiar with worked as shown below at least. 

[19:51]ec2-user$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda simple-sycl-app.cpp -o simple-sycl-app-cuda
clang-16: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
warning: linking module '/data_disk01/archboldw/projects/sycl_workspace/llvm/build/lib/clang/16.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc': Linking two modules of different target triples: '/data_disk01/archboldw/projects/sycl_workspace/llvm/build/lib/clang/16.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc' is 'nvptx64-unknown-nvidiacl' whereas 'simple-sycl-app.cpp' is 'nvptx64-nvidia-cuda'
 [-Wlinker-warnings]
1 warning generated.

[19:51]ec2-user$ ./simple-sycl-app-cuda
The results are correct!

**Comment by zjin-lcf** [comment]
[SYCL_DEVICE_FILTER may be needed ](https://intel.github.io/llvm-docs/EnvironmentVariables.html)

**Comment by e404044** [comment]
@zjin-lcf i'm pretty new to all this. where would i use SYCL_DEVICE_FILTER ?

**Comment by zjin-lcf** [comment]
Assume your computer has an NVIDIA GPU. 
In the terminal:
```
$ sycl-ls
[ext_oneapi_cuda:gpu:0] NVIDIA CUDA BACKEND, Tesla V...

$ SYCL_DEVICE_FILTER=gpu  ./exe
```

**Comment by e404044** [comment]
[22:28]ec2-user$ sycl-ls
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]

@zjin-lcf looks like i don't have a GPU listed

**Comment by e404044** [comment]
@zjin-lcf that helped get the ball rolling.  running nvidia-smi showed that my driver and cuda were misaligned. Reinstalled and now it works.
