### ISSUE TITLE
Compiler error when compile {fmt} library

### ISSUE THREAD

**Issue by andreagen0r** [intel/llvm#6702]
The compiler interprets a struct member as a bit field, but is not

Please, see the fmt repository thread  
https://github.com/fmtlib/fmt/issues/3078

``` shell
fmt/include/fmt/format.h:2477:11: error: cannot capture a bit-field by reference
      if (sign) *it++ = detail::sign<Char>(sign);

fmt/include/fmt/include/fmt/format.h:2418:8: note: 'sign' declared here
  auto sign = fspecs.sign;

fmt/include/fmt/core.h:2785:10: note: bit-field is declared here
  sign_t sign : 8;

fmt/include/fmt/os.h:20:
/home/andreagenor/code/external_libraries/fmt/include/fmt/format.h:2491:11: error: cannot capture a bit-field by reference
      if (sign) *it++ = detail::sign<Char>(sign);
```
I changed the lambda passing by value and now works fine, but it is just a workaround

![diff](https://snipboard.io/8r7YW1.jpg)

``` cpp
namespace sign {
enum type FMT_ENUM_UNDERLYING_TYPE(unsigned char){none, minus, plus, space};
}
using sign_t = sign::type;

struct float_specs {
  int precision;
  float_format format : 8;
  sign_t sign : 8;
  bool upper : 1;
  bool locale : 1;
  bool binary32 : 1;
  bool showpoint : 1;
};

auto sign = fspecs.sign;

// The error is passing by reference to the lambda
return write_padded<align::right>(out, specs, size, [&](iterator it) {
    if (sign) *it++ = detail::sign<Char>(sign);
    *it++ = zero;
    if (!pointy) return it;
    *it++ = decimal_point;
    it = detail::fill_n(it, num_zeros, zero);
    return write_significand<Char>(it, significand, significand_size);
  });

```

**To Reproduce**
Compile the master branch

- OS: Kubuntu 22.04
- Target device and vendor: NVidia
- DPC++ version: clang version 16.0.0 (https://github.com/intel/llvm 22e3fc56c8c2bef6d92a19819b7bea106a7992d1)

**Comment by KornevNikita** [comment]
@andreagen0r already fixed by a1a71b7dc97b35133425a31ede90c40529f1be9e. We just need to wait a little until this change is in sycl branch.

**Comment by AlexeySachkov** [comment]
Hi @andreagen0r, 

> The compiler interprets a struct member as a bit field, but is not

Why do you think that `float_specs` struct doesn't contain bit-field members? According to [cppreference](https://en.cppreference.com/w/cpp/language/bit_field) (or alternatively a [C++ spec draft](https://eel.is/c++draft/class.bit#::,bit-field_declaration)) that is exactly a bit-filed:

> A bit-field declaration is a [class data member declaration](https://en.cppreference.com/w/cpp/language/data_members) which uses the following declarator:
> identifier(optional) attr(optional) : size	(1)

**Comment by bader** [comment]
I guess, because @vitaut said so [here](https://github.com/fmtlib/fmt/issues/3078#issuecomment-1237271232).

**Comment by vitaut** [comment]
I was talking about a variable called `sign` which is not a bit field, not about the struct member which is a bit field. The lambda captures the variable, not the member.

**Comment by andreagen0r** [comment]
> Hi @andreagen0r, 
> 
> 
> 
> > The compiler interprets a struct member as a bit field, but is not
> 
> 
> 
> Why do you think that `float_specs` struct doesn't contain bit-field members? According to [cppreference](https://en.cppreference.com/w/cpp/language/bit_field) (or alternatively a [C++ spec draft](https://eel.is/c++draft/class.bit#::,bit-field_declaration)) that is exactly a bit-filed:
> 
> 
> 
> > A bit-field declaration is a [class data member declaration](https://en.cppreference.com/w/cpp/language/data_members) which uses the following declarator:
> 
> > identifier(optional) attr(optional) : size	(1)

You is right, It was my fail to interpret the text, my English is bad I guess :)

**Comment by vitaut** [comment]
No worries, just wanted to clarify since there was some confusion about the nature of the bug.
