### ISSUE TITLE
FPGA set up for SYCL 

### ISSUE THREAD

**Issue by e404044** [intel/llvm#6727]
I've successfully gained access to using my Nvidia GPU and Intel CPU for host_selction in my sycl_environment. I now need to show that I can select an FPGA. Anyone have any recommendations on where to start with this? I'm new to FPGAs and need to do it on an AWS EC2 instance.

**Comment by steffenlarsen** [comment]
Hi @e404044! Assuming you have an OpenCL implementation installed for the FPGA, it should be possible to select it in your SYCL code using `sycl::accelerator_selector` or `sycl::accelerator_selector_v`. To see if SYCL is able to find the FPGA you can try running running `sycl-ls` and see if the FPGA shows up in the list of devices.

**Comment by e404044** [comment]
@steffenlarsen yup i saw the instructions on the getting started page and set up my FPGA simulator. Thanks!
