### ISSUE TITLE
DPC++ support for NVIDIA is not supporting GPU compiler options except "--cuda-gpu-arch"

### ISSUE THREAD

**Issue by nsirgien** [intel/llvm#6821]
**Describe the bug**
It looks like DPC++ compiler with NVIDIA support can't properly pass options to CUDA GPU compiler via `-Xsycl-target-backend` except "--cuda-gpu-arch". For example this compilation command:
`clang++ -fsycl -Iinclude -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda "--cuda-gpu-arch=sm_86" main.cpp -o main_few_options.exe`
will work fine and CUDA GPU compiler will have proper options during compilation:
`"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6/bin\ptxas" -m64 -O3 --gpu-name sm_86 --output-file "C:\Users\Nikita\AppData\Local\Temp\main-sm_86-d864aa.o"
              "C:\Users\Nikita\AppData\Local\Temp\main-sm_86-acef31.s"`

But this compilation command:
`clang++ -fsycl -Iinclude -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda "--verbose --maxrregcount 128 --cuda-gpu-arch=sm_86" main.cpp -o main_few_options.exe`
won't work as expected and will lead to this CUDA GPU compiler command:
`"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6/bin\ptxas" -m64 -O3 --gpu-name sm_50 --output-file "C:\Users\Nikita\AppData\Local\Temp\main-sm_50-304b5a.o"
              "C:\Users\Nikita\AppData\Local\Temp\main-sm_50-fa05b6.s"`
which is not correct, because if this options will be handle properly, then the GPU compiler command should looks like this:
`"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6/bin\ptxas" -m64 -O3 --verbose --maxregcount 128 --gpu-name sm_86 --output-file "C:\Users\Nikita\AppData\Local\Temp\main-sm_86-304b5a.o"
              "C:\Users\Nikita\AppData\Local\Temp\main-sm_86-fa05b6.s"`

**To Reproduce**
Because problem is related to command line arguments parsing, any complex source code will work - complex code is needed for the GPU compiler to spend enough time, which will allow check it's compilation command ( I am using this Powershell command for this purpose: `Get-WmiObject Win32_Process -Filter "name = 'ptxas.exe'" | Select-Object CommandLine | fl`.

But I have also a mine reproducer for this problem and in order to use it you will need to perform this steps:
1. Download an archive [dpcpp_nvidia_additional_options_problems.zip](https://github.com/intel/llvm/files/9606474/dpcpp_nvidia_additional_options_problems.zip)
2. Unpack archive and put it's content in some directory
3. Open console and load an DPC++ environment with CUDA support
4. In the same console, go to the directory with archive content from the second step
5. Run script "Makefile_correct.bat" and check (via powershell command) that PTXAS command line is corresponding to DPC++ compilation command

6. Run script "Makefile_wrong.bat" and observe (via powershell command) a problem that PTXAS is not fully correct and don't correspond to DPC++ compilation command 

**Environment (please complete the following information):**

- OS: Windows
- Target device and vendor: NVIDIA GPU
- DPC++ version: 079494e8dcc05b41051e396c9a0271905a9879aa
- Dependencies version: Cuda Toolkit 11.6

**Additional context**
I am consider current behaviour of CUDA backend option parser as a problem, because Intel backend don't have any problems with parsing options and forwarding them to the Intel GPU compiler - for example you can use this command 

`clang++ -fsycl -fsycl-targets=spir64_gen -Xsycl-target-backend=spir64_gen "-device adls --format zebin -options '-ze-opt-large-register-file -ze-opt-regular-grf-kernel integrator_intersect'"`

and this will work as expected and arguments `-device adls --format zebin -options '-ze-opt-large-register-file -ze-opt-regular-grf-kernel integrator_intersect'"` will be forwared to Intel GPU compiler.

**Comment by pgorlani** [comment]
Hi @nsirgien, thanks for raising this question.

Does passing these arguments with `-Xcuda-ptxas` works for you?  I.e., 
```
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda  -Xcuda-ptxas --maxrregcount=128 -Xcuda-ptxas --verbose  -Xsycl-target-backend  --cuda-gpu-arch=sm_60 ...
...
ptxas info    : 0 bytes gmem
...
ptxas info    : Compiling entry function '_ZTSZZ4mainENKUlRN4sycl3_V17handlerEE_clES2_EUlNS0_2idILi1EEEE__with_offset' for 'sm_60'
ptxas info    : Function properties for _ZTSZZ4mainENKUlRN4sycl3_V17handlerEE_clES2_EUlNS0_2idILi1EEEE__with_offset
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 12 registers, 380 bytes cmem[0]
...
```

**Comment by nsirgien** [comment]
Hi @pgorlani, yes, "-Xcuda-ptxas" option is work for me as expected.

**Comment by pgorlani** [comment]
Thank you so much for your feedback, @nsirgien.

If you are happy, please consider closing the issue.

**Comment by pgorlani** [comment]
I close this issue since there are no more updates. Feel free to open it again if there are any problems.
