### ISSUE TITLE
Cant use barrier in CPU: nd_item::barrier not implemented for host device

### ISSUE THREAD

**Issue by ManuelCostanzo** [intel/llvm#6872]
Hi everyone! I have a code that computes perfectly on GPU using clang, but when I use CPU I get the following error:

`nd_item::barrier not implemented for host device`

Can I solve this? Are there alternatives for synchronization inside the kernel?

Thank you very much

**Comment by bader** [comment]
You can solve this problem by using OpenCL CPU devices instead of host device.
Here you can find installation instructions for OpenCL CPU - https://intel.github.io/llvm-docs/GetStartedGuide.html#install-low-level-runtime.

**Comment by ManuelCostanzo** [comment]
Excelent! Thank you very much @bader
