### ISSUE TITLE
[PI][HIP] warning: Linking two modules of different target triples: amdgcn-unknown-amdhsa and amdgcn-amd-amdhsa

### ISSUE THREAD

**Issue by TejaX-Alaghari** [intel/llvm#6922]
While compiling a simple SYCL code with LLVM for HIP backend, the following warning was reported:

warning: linking module 'llvm/build/install/lib/clang/16.0.0/../../clc/remangled-l64-signed_char.libspirv-amdgcn--amdhsa.bc': Linking two modules of different target triples: 'llvm/build/install/lib/clang/16.0.0/../../clc/remangled-l64-signed_char.libspirv-amdgcn--amdhsa.bc' is 'amdgcn-unknown-amdhsa' whereas 'hip_interop_test_rocblas.cpp' is 'amdgcn-amd-amdhsa'

What is this warning about and how can this warning be suppressed from the code?

**Comment by npmiller** [comment]
This is because of how `libclc` is built, and is really something we need to fix in DPC++.

I'm not aware of a way to suppress it but it's safe to ignore for now.
