### ISSUE TITLE
libclc build in Debug mode is very slow

### ISSUE THREAD

**Issue by pvchupin** [intel/llvm#6925]
Is there a way to improve that?

To reproduce:
```
python buildbot/configure.py --ci-defaults -t Debug
python buildbot/compile.py
```

I've notice that hang is happening at these lines (take ~13 minutes each):
```
.../llvm/build/bin/opt -O3 --nvvm-reflect-enable=false -o .../llvm/./lib/clc/builtins.opt.libspirv-nvptx64--nvidiacl.bc .../llvm/./lib/clc/builtins.link.libspirv-nvptx64--nvidiacl.bc
```

**Comment by pvchupin** [comment]
Tagging @Naghasan , @AerialMantis

**Comment by Naghasan** [comment]
libclc uses the toolchain you build (there is actually a hack to trick cmake into thinking clang is available during configuration).

This is hard to actually solve for CI (as you want a one off self contained build). Tablegen improved build time by building an optimised tablegen even in debug mode, but here this would mean an entire llvm toolchain is release when you want a debug mode...

From a user perspective we could have a flag for the user to provide a pre-build libclc or an alternative clang / opt / llvm-link / llc. The first would skip the build of the lib and the second speed it up.

Providing a pre-build libclc is opening the door to sync issues though, alternative clang and llvm toolchain is less of a problem as required backend or clang builtins update are not happening that often.
