### ISSUE TITLE
Build logs from link steps are missed

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#693]
In `program_impl(vector_class<std::shared_ptr<program_impl>>, string_class LinkOptions = "")` we have the following code which doesn't include logs from link step into exception which is thrown in case of errors. The same is applicable for `link` method in this class

https://github.com/intel/llvm/blob/6e76414eaf7248a3fade94f09efb344a3f8dec2d/sycl/include/CL/sycl/detail/program_impl.hpp#L87-L92

Example of how it is done for `build` method:
https://github.com/intel/llvm/blob/6e76414eaf7248a3fade94f09efb344a3f8dec2d/sycl/include/CL/sycl/detail/program_impl.hpp#L378-L385

**Comment by przemb** [comment]
Hi, 
I would like improve logging mechanism :)

**Comment by alexbatashev** [comment]
The issue appears to be resolved in our source code: https://github.com/intel/llvm/blob/ae7e3d8d7e3ab011c08ed1d85ba211947dc22c05/sycl/source/detail/program_manager/program_manager.cpp#L1666-L1669
