### ISSUE TITLE
[SYCL][Doc] add compiler options for the SYCL compiler with CUDA support

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#6942]
The issue is described in https://github.com/intel/llvm/issues/6821

Reference
https://intel.github.io/llvm-docs/UsersManual.html

**Comment by pgorlani** [comment]
Hi @zjin-lcf, does [this](https://github.com/intel/llvm/pull/7045) document update work for you?

**Comment by pgorlani** [comment]
I closed this issue since there are no more updates. Feel free to open it again if there are any problems.

**Comment by zjin-lcf** [comment]
Thank you. Sorry, I am late for the reply.
