### ISSUE TITLE
[SYCL][CUDA][HIP] Crashes with range zero SYCL kernel 

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#6963]
This following reproducer crashes with the following error. Instead the discussion here: https://github.com/KhronosGroup/SYCL-Docs/pull/192 states the expected behavior.

A similar discussion was posed here #1708 

```c++
#include <sycl/sycl.hpp>
using namespace sycl;

int main(int argc, char* argv[])
{
  queue q;
  q.submit([&](handler& cgh) {
    cgh.parallel_for(range<1>(0), [=](id<1> i) {});
  }).wait();
}
```
When built with asserts enabled:
```
llvm/sycl/source/detail/scheduler/commands.cpp:1958: void sycl::_V1::detail::adjustNDRangePerKernel(sycl::_V1::detail::NDRDescT&, sycl::_V1::detail::pi::PiKernel, const sycl::_V1::detail::device_impl&): Assertion `NDR.NumWorkGroups[0] != 0 && NDR.LocalSize[0] == 0' failed.
Aborted
```
When compiler built with `--no-assertions` the following error from CUDA  plugin for example:
```bash
PI CUDA ERROR:
	Value:           1
	Name:            CUDA_ERROR_INVALID_VALUE
	Description:     invalid argument
	Function:        cuda_piEnqueueKernelLaunch
	Source Location: llvm/sycl/plugins/cuda/pi_cuda.cpp:3082

terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -30 (PI_ERROR_INVALID_VALUE) -30 (PI_ERROR_INVALID_VALUE)
Aborted (core dumped)
```

**Comment by AerialMantis** [comment]
Hi @abagusetty thanks for reporting this issue, we will investigate the issue that you're reporting in the CUDA backend, though as this was a recent clarification to the specification this could impact other backends as well so may require a more general solution. We will look into this and get back to you shortly.

**Comment by mmoadeli** [comment]
[7044](https://github.com/intel/llvm/pull/7044) created to address the issue.

**Comment by abagusetty** [comment]
Closing since #7044 addresses the issue.
