### ISSUE TITLE
[SYCL] Performance regression with nd::item::barrier() vs sycl::group_barrier()

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#7069]
**Describe the bug**
Using `sycl::group_barrier(g)` causes about 50% performance regression in comparison to using `nd_item::barrier(local_space)`. This can be seen with the following reproducer. For example: the common use case of SLM.

While the SYCL 2020 spec, deprecated `nd_item::barrier()` this commit https://github.com/intel/llvm/commit/51c747da21370087a93ec00432a7e77e23aa29e0#diff-9859065be283dfac82303b3ba5791f52a1610929c962516cba23fad3dc49ff94R115 added deprecation notice which since then was removed some where down the line. 

**To Reproduce**
```c++
#include <sycl/sycl.hpp>
#include <iostream>

int main() {
  sycl::queue q{sycl::gpu_selector_v, sycl::property::queue::enable_profiling{}};
  std::cout << "Device: " << q.get_device().get_info<sycl::info::device::name>()
            << std::endl;

  constexpr int N = 32;
  int *data = sycl::malloc_device<int>(N, q);

  auto e = q.parallel_for(
    sycl::nd_range(sycl::range{N}, sycl::range{32}), [=](sycl::nd_item<1> it) {

      // shared memory
      sycl::group thread_block = it.get_group();
      using tile_t = int[32 * 64];
      tile_t& slm = *sycl::ext::oneapi::group_local_memory_for_overwrite<tile_t>(thread_block);

      int i = it.get_global_linear_id();
      int j = it.get_local_linear_id();

      slm[j] = 0;
      it.barrier(sycl::access::fence_space::local_space);
      //sycl::group_barrier(thread_block);

      for (int m = 0; m < 1024 * 1024; m++) {
        slm[j] += i * m;
        it.barrier(sycl::access::fence_space::local_space);
        //sycl::group_barrier(thread_block);        
      }

      data[i] = slm[j];
    });


  e.wait();
  std::cout << "Kernel time = "
            << (e.template get_profiling_info<
                    sycl::info::event_profiling::command_end>() -
                e.template get_profiling_info<
                    sycl::info::event_profiling::command_start>())
            << " ns" << std::endl;
  return 0;
}
```

Looking at the SPIR-V calls, for the above code, the only difference is in the last argument (i32 912 vs i32 272),
group_barrier: `call spir_func void @__builtin_spirv_OpControlBarrier_i32_i32_i32(i32 2, i32 2, i32 912) #0`
item.barrier(local_space): `call spir_func void @__builtin_spirv_OpControlBarrier_i32_i32_i32(i32 2, i32 2, i32 272) #0`

The differences are:
group_barrier: https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/group_algorithm.hpp#L1030-L1033
nd_item::barrier(local_space): https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/helpers.hpp#L236-L239

**Comment by Pennycook** [comment]
`sycl::group_barrier` has different semantics, which may explain the performance difference.

What performance do you see if you use `it.barrier(sycl::access::fence_space::global_and_local)`?

**Comment by abagusetty** [comment]
@Pennycook Thanks for confirming on semantics.

On a 1-tile Intel GPU: 
Performance of `it.barrier(sycl::access::fence_space::global_and_local)` vs `sycl::group_barrier()` was almost comparable. 

Averaged timings over 10 executions (ns): 
`it.barrier(sycl::access::fence_space::global_and_local)`: 146210688
`sycl::group_barrier()`: 146045664

`it.barrier(sycl::access::fence_space::local_space)`: 102135128
`sycl::group_barrier()`: 145905952

Given that majority of the applications sees this use case with porting for the common case of a SLM usage:
`__syncthreads()` --> `item.barrier(sycl::access::fence_space::local_space)` the performance degradation was a bit substantial with even the simplest test case above and was seen more predominant in some large-scale science apps too.

With `item.barrier()` deprecated and I wasn't sure if `sycl::group_barrier()` was some how it's replacement, a bit confused what should the appropriate practice here.

**Comment by Pennycook** [comment]
> On a 1-tile Intel GPU: Performance of `it.barrier(sycl::access::fence_space::global_and_local)` vs `sycl::group_barrier()` was almost comparable.
> 
> Averaged timings over 10 executions (ns): `it.barrier(sycl::access::fence_space::global_and_local)`: 146210688 `sycl::group_barrier()`: 146045664

Thanks for running this test.  I think this is the expected behavior.


> Given that majority of the applications sees this use case with porting for the common case of a SLM usage: `__syncthreads()` --> `item.barrier(sycl::access::fence_space::local_space)` the performance degradation was a bit substantial with even the simplest test case above and was seen more predominant in some large-scale science apps too.

The correct migration of `__syncthreads()` to SYCL is `item.barrier(sycl::access::fence_space::global_and_local)`.  The [NVIDIA documentation](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#synchronization-functions) says that `__syncthreads` "waits until all threads in the thread block have reached this point and all global and shared memory accesses made by these threads prior to `__syncthreads()` are visible to all threads in the block."  Making both global and shared accesses visible requires fencing both address spaces, not just the `local` one.


> With `item.barrier()` deprecated and I wasn't sure if `sycl::group_barrier()` was some how it's replacement, a bit confused what should the appropriate practice here.

`item.barrier()` was deprecated because most developers don't want to think about multiple address spaces and how a scoped memory model works.  There are also some confusing corner cases that can arise when using atomics to different address spaces: https://dl.acm.org/doi/10.1145/3456669.3456696 has some high-level discussion of this, and links out to https://dl.acm.org/doi/10.1145/2837614.2837637 for the low-level details.

**Comment by abagusetty** [comment]
Thanks so much for the above pointers. Closing this.

**Comment by al42and** [comment]
@Pennycook, thanks for the detailed explanation.

But, while in general, `fence_space::global_and_local` is the proper one to use when porting `__syncthreads()`, I believe in the example above the use of `fence_space::local` should be correct, right? If so, that looks like quite a lot of performance is being left on the table, even if that's a fault of the standard and not the IntelLLVM.
