### ISSUE TITLE
Using the nvidia opencl runtime

### ISSUE THREAD

**Issue by fcharras** [intel/llvm#7114]
Can opencl sycl devices be nvidia opencl devices ? 

I have `libnvidia-opencl.so.1` installed and the `icd` is correctly configured and `clinfo` can detect the device, but this device is not detected as a sycl device.

The corresponding cuda device is properly detected (assuming the `--cuda` flag at build time).

I have not seen this mentioned much in documentation so was wondering if it's normal or not to not see nvidia opencl devices show up as sycl devices, if not what in general prevents interoperability between intel opencl and nvidia opencl backends ?

**Comment by fcharras** [comment]
I'm exploring the interoperability potential of the python software stack `dpnp` / `dpctl` / `numba_dpex`, see e.g https://github.com/IntelPython/dpctl/issues/947 . I'm writing kernels with `numba_dpex` and investigated the possibility to distribute and run it on the largest possible scope of devices. ATM `dpctl` does not support compiling kernels for cuda (see issue), I thought maybe adapting the opencl support for intel hardware to other opencl runtimes might be an easier leap. I'm not well used to c/c++ programming myself I'm more trying to inquiry the potential for interoperability in general from the point of view of higher level layers of code.

**Comment by fcharras** [comment]
Yes I think that's what happens in `dpctl`. Thank you for the added explanations it's very informative and really help understanding the remaining barriers.

**Comment by AlexeySachkov** [comment]
@fcharras, can we close the issue or you have some other questions on the topic?

**Comment by fcharras** [comment]
The questions has been answered let's close it, thank you :+1:
