### ISSUE TITLE
[CUDA] Compilation error for Nvidia gpu, libspirv

### ISSUE THREAD

**Issue by lmontigny** [intel/llvm#7132]
I have the following error at compile time, using dpcpp compiler, cuda 11.5 and -fsycl -fsycl-targets=nvptx64-nvidia-cuda.
Nvidia hardware is V100 GPU.

```
dpcpp: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
dpcpp: error: cannot find 'remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc'; provide path to libspirv library via '-fsycl-libspirv-path', or pass '-fno-sycl-libspirv' to build without linking with libspirv
make[2]: *** [constant/CMakeFiles/dpcpp_constant_cuda.dir/build.make:76: constant/CMakeFiles/dpcpp_constant_cuda.dir/constant_dpcpp_cuda.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:527: constant/CMakeFiles/dpcpp_constant_cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
2 warnings generated.
```

dpcpp --version
Intel(R) oneAPI DPC++/C++ Compiler 2022.2.0 (2022.2.0.20220730)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2022.2.0/linux/bin-llvm

 clang --version
clang version 16.0.0 (https://github.com/intel/llvm.git 4a67f2a92b2c37ff3d0fdf3df67f57a4c21982bd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/llvm/build/bin

**Comment by pvchupin** [comment]
This target is not supported in DPC++ product 2022.2.
There should be some solution available soon, driven by @AerialMantis and the team, based on 2023.0 product that will be released soon.
