### ISSUE TITLE
Non-standard `RT` namespace is exposed in `sycl` namespace

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#7133]
It looks like the following code:

https://github.com/intel/llvm/blob/321c733c392cad288cba91952cee60db2694d615/sycl/include/sycl/detail/pi.hpp#L259-L260

Brings `RT` namespace into `sycl` namespace - whilst that is not explicitly prohibited by the spec, it should be considered as a bad tone according to discussion in KhronosGroup/SYCL-Docs#137

**Comment by dm-vodopyanov** [comment]
Just a note: https://github.com/intel/llvm/pull/9837 fixes only one usage of `RT` namespace. There are also 

https://github.com/intel/llvm/blob/b3e0428ffef4edddb1e7236219de056de8d0ffcc/sycl/include/sycl/detail/pi.hpp#L244

and

https://github.com/intel/llvm/blob/b3e0428ffef4edddb1e7236219de056de8d0ffcc/sycl/unittests/helpers/PiMock.hpp#L52

**Comment by marcin-smuklerz-mobica** [comment]
> Just a note: #9837 fixes only one usage of `RT` namespace. There are also
> 
> https://github.com/intel/llvm/blob/b3e0428ffef4edddb1e7236219de056de8d0ffcc/sycl/include/sycl/detail/pi.hpp#L244
> 
> and
> 
> https://github.com/intel/llvm/blob/b3e0428ffef4edddb1e7236219de056de8d0ffcc/sycl/unittests/helpers/PiMock.hpp#L52

I initially thought it is related to the exactly one mentioned in report. I will work on removal of others.

**Comment by dm-vodopyanov** [comment]
@marcin-smuklerz-mobica, thanks!
