### ISSUE TITLE
SYCL runtime incorrectly waits on other tasks during command submission

### ISSUE THREAD

**Issue by npmiller** [intel/llvm#7146]
**Describe the bug**

The SYCL specification in section [3.9.11](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_scheduling_of_kernels_and_data_movement) states that calls to submit on the queue are non-blocking:

> These calls will be non-blocking on the host, but enqueue operations to the queue that the command group is submitted to.

Therefore I believe it's incorrect for the runtime to wait on other commands when submitting a command, meaning that it may need to hold off on submitting the command to PI until a later point.

**To Reproduce**

The following code snippet using the `host_task` hangs with DPC++, but I believe it is valid SYCL code:

```cpp
#include <sycl/sycl.hpp>
#include <vector>
#include <mutex>

int main(int argc, char *argv[]) {
  sycl::queue q;

  std::vector<int> a(32, 2);
  sycl::buffer<int, 1> Ba{a.data(), a.size()};

  std::mutex l;
  l.lock();

  sycl::event e = q.submit([&](sycl::handler &h) {
    h.host_task([&]() {
      l.lock();
      l.unlock();
    });
  });

  q.submit([&](sycl::handler &h) {
     h.depends_on(e);

     auto acca = Ba.get_access<sycl::access::mode::read_write>(h);
     h.parallel_for<class kernel1>(sycl::range<1>{1}, [=](sycl::id<1> idx) {
       acca[0] = 1;
     });
   });

  l.unlock();
  q.wait();

  auto acca = Ba.get_access<sycl::access::mode::read>();
  printf("val: %d\n", acca[0]);

  return 0;
}
```

I'm getting deadlocks with this on Linux with the CUDA plugin.

But I believe it hangs in the runtime, suggesting that the kernel enqueue is actually blocking trying to wait on the event `e` from the `host_task`, which is invalid.

cc @Pennycook

**Comment by KseniyaTikhomirova** [comment]
@npmiller I am working on host task improvements and have 1 PR that is not fully ready but should help. Is it possible for you to check and confirm if it also helps you? https://github.com/intel/llvm/pull/6995

**Comment by npmiller** [comment]
@KseniyaTikhomirova I've tried with your branch and it does fix this sample, and your description matches exactly the issue here so I believe https://github.com/intel/llvm/pull/6995 should indeed solve it.

Thank you!

**Comment by KseniyaTikhomirova** [comment]
@npmiller the fix is merged to intel/llvm now

**Comment by npmiller** [comment]
I can confirm it's fixed on the `sycl` branch now, Thanks!
