### ISSUE TITLE
[SYCL][CUDA] lg2 instruction for pow(x,y)

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#7194]
Is it better to call lg2 for pow(x,y) ?  Please ignore the meanings of registers.  Thanks.

clang++
```
        setp.gt.f32     %p13, %f79, 0f42FC0000;
        mov.b32         %r18, %f78;
        and.b32         %r19, %r18, -2147483648;
        or.b32          %r20, %r19, 1123811328;
        mov.b32         %f80, %r20;
        selp.f32        %f81, %f80, %f78, %p13;
        fma.rn.f32      %f82, %f81, 0fBF317218, %f75;
        fma.rn.f32      %f83, %f81, 0f3102E308, %f82;
        mul.f32         %f84, %f83, 0f3FB8AA3B;
        ex2.approx.ftz.f32      %f85, %f84;
```

nvcc
```
        lg2.approx.ftz.f32      %f18, %f17;
        mul.ftz.f32     %f19, %f18, %f8;
        ex2.approx.ftz.f32      %f20, %f19;
```
Reference
https://stackoverflow.com/questions/54168896/raise-x-to-power-of-y-in-ptx-nvidia-cuda-assembly

**Comment by zjin-lcf** [comment]
The SYCL kernel calls sycl::pow(), but `--ffasth-math` does not convert sycl::pow() to sycl::native::powr().  Thank you for the answer!

**Comment by JackAKirk** [comment]
> The SYCL kernel calls sycl::pow(), but `--ffasth-math` does not convert sycl::pow() to sycl::native::powr(). Thank you for the answer!

Yes it only does the sycl -> sycl::native swap if the corresponding native math function exists. So -ffast-math works with sycl::powr but not sycl::pow, because there is no sycl::native::pow.
