### ISSUE TITLE
Broken sycl::get_native<sycl::backend::ext_oneapi_hip, sycl::device>

### ISSUE THREAD

**Issue by al42and** [intel/llvm#7223]
**Describe the bug**

Using `sycl::get_native` to obtain HIP device handle fails to compile.

**To Reproduce**

```cpp
#include <CL/sycl.hpp>

int main() {
    sycl::device d;
    if (d.get_backend() == sycl::backend::ext_oneapi_hip) {
        auto native_d = sycl::get_native<sycl::backend::ext_oneapi_hip>(d);
    }
}
```

```console
$ clang++ -fsycl -fsycl-targets=amdgcn-amd-amdhsa -Xsycl-target-backend --offload-arch=gfx1032 test.cpp 
In file included from test.cpp:1:
In file included from /home/aland/intel-sycl/llvm/build/install//bin/../include/sycl/CL/sycl.hpp:11:
In file included from /home/aland/intel-sycl/llvm/build/install//bin/../include/sycl/sycl.hpp:16:
/home/aland/intel-sycl/llvm/build/install//bin/../include/sycl/backend.hpp:130:10: error: reinterpret_cast from 'pi_native_handle' (aka 'unsigned long') to 'backend_return_t<(backend)'\x06', device>' (aka 'int') is not allowed
  return reinterpret_cast<backend_return_t<BackendName, SyclObjectT>>(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.cpp:8:31: note: in instantiation of function template specialization 'sycl::get_native<sycl::backend::ext_oneapi_hip, sycl::device>' requested here
        auto native_d = sycl::get_native<sycl::backend::ext_oneapi_hip>(d);
                              ^
1 error generated.
```

**Environment (please complete the following information):**

- OS: Linux, Ubuntu 20.04
- Target device and vendor: AMD RX6600
- DPC++ version: bc1b30652d112610b9c45694872f069f47db8c38
- Dependencies version: ROCm 5.3.0 (from AMD repositories)

**Additional context**

No such error with `sycl::backend::ext_oneapi_cuda`

**Comment by abagusetty** [comment]
@al42and Thanks for checking this. I just took a peek and found that the `get_native` support for free-functions were missing on the HIP-plugin. Looks like a easy fix.

**Comment by npmiller** [comment]
Closing this as it should be fixed, feel free to re-open if the issue persists.

**Comment by al42and** [comment]
Sorry for the late update.

The code snippet posted above still fails for me with the same error when using 5a188c74d7be4229ecb36116e28398ca894d9abb

**Comment by al42and** [comment]
Sorry, read the PR description. With `#include <sycl/ext/oneapi/backend/hip.hpp>` everything works :ok_hand:
