### ISSUE TITLE
Implement sycl::opencl::cl_*

### ISSUE THREAD

**Issue by TApplencourt** [intel/llvm#7242]
**Is your feature request related to a problem? Please describe**

SYCL 2020, moved the `cl::sycl::cl_*` into `sycl::opencl::cl_*` and not into the main namespace. 

For now, `intel/llvm` moved them to the main namespace. Regardless of the fact that this is not a spec compliment and leads people to write nonportable code, they should also be moved into `sycl::opencl`. 

```
$ icpx --version
Intel(R) oneAPI DPC++/C++ Compiler 
$ cat float.cpp
#include <sycl/sycl.hpp>
int main() {
#ifndef _WA
    sycl::opencl::cl_float a;
#else
    sycl::cl_float a; # This should not compile
#endif
}
$ icpx -fsycl float.cpp
float.cpp:7:5: error: no type named 'cl_float' in namespace 'sycl::opencl'; did you mean simply 'cl_float'?
    sycl::opencl::cl_float a;
    ^~~~~~~~~~~~~~~~~~~~~~
    cl_float
/soft/libraries/khronos/headers/master-2022.05.18/include/CL/cl_platform.h:266:25: note: 'cl_float' declared here
typedef float           cl_float;
                        ^
1 error generated.
$ icpx -fsycl -D_WA float.cpp
$
```

**Comment by TApplencourt** [comment]
Also may want to follow: https://github.com/KhronosGroup/SYCL-Docs/issues/312 for`cl_int` location.

**Comment by jbrodman** [comment]
Technically it is spec conformant - because I think there's a spec bug in the OpenCl interop spec that needs to be fixed.
"In order for the SYCL device compiler to ensure that the sizes of these types match the sizes on the host and to enable data of these types to be shared between host and device, the OpenCL interoperability types are defined, sycl::cl_int and sycl::cl_size_t."

**Comment by TApplencourt** [comment]
Agree! My `_WA` was more of a side note. sorry for the confusion. 

My main point was can we also have them in `sycl::opencl::`? So we can encourage people to use the "correct" namespace.

**Comment by jbrodman** [comment]
Yes. :)
