### ISSUE TITLE
[SYCL][RT] DPC++ runtime throws deprecated exceptions

### ISSUE THREAD

**Issue by bader** [intel/llvm#7268]
https://github.com/intel/llvm/commit/5c0f74863d86cbe4797be1a5baa02b8fbb0dda4c deprecated SYCL 1.2.1 exceptions, but these are still used in DPC++ library source code.
We need migrate DPC++ runtime library source code to SYCL 2020 exceptions.

**Comment by pwisniewskimobica** [comment]
I created PR for this issue
https://github.com/intel/llvm/pull/9771

**Comment by steffenlarsen** [comment]
https://github.com/intel/llvm/pull/9771 has been merged. Closing this issue.
