### ISSUE TITLE
DPC++ headers do not compile with -DDISABLE_SYCL_INSTRUMENTATION_METADATA option.

### ISSUE THREAD

**Issue by bader** [intel/llvm#7270]
**Describe the bug**
DPC++ compiler is not able to parse `sycl/sycl.hpp` header file when `-DDISABLE_SYCL_INSTRUMENTATION_METADATA` option is set.

**To Reproduce**
```bash
echo "#include <sycl/sycl.hpp>" > /tmp/test.cpp && clang++ -fsycl -DDISABLE_SYCL_INSTRUMENTATION_METADATA /tmp/test.cpp
```

I see errors like 
```bash
include/sycl/usm.hpp:137:27: error: no matching function for call to 'aligned_alloc_device'
```

**Environment (please complete the following information):**

- DPC++ version: clang version 16.0.0 (https://github.com/intel/llvm.git 97c0c997147487096b86549f48215284413dd245)

**Comment by aelovikov-intel** [comment]
The macro was removed in https://github.com/intel/llvm/pull/9847.
