### ISSUE TITLE
how to instantiate a kernel object sycl::kernel?

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#7295]
how to instantiate a sycl::kernel with variable initialization?

**Comment by AlexeySachkov** [comment]
HI @wangzy0327, 

The core SYCL spec explicitly says that [`sycl::kernel`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_the_kernel_class) has no public default constructor (or any other public constructors), so it is only possible to obtain it by calling some other APIs. For example, you can use backend-specific [`make_kernel`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:backend-interoperability-make) or you can query a kernel from [`kernel_bundle`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_the_kernel_bundle_class) using `get_kernel` method.

**Comment by wangzy0327** [comment]
> HI @wangzy0327,
> 
> The core SYCL spec explicitly says that [`sycl::kernel`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_the_kernel_class) has no public default constructor (or any other public constructors), so it is only possible to obtain it by calling some other APIs. For example, you can use backend-specific [`make_kernel`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:backend-interoperability-make) or you can query a kernel from [`kernel_bundle`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_the_kernel_bundle_class) using `get_kernel` method.

OK , Thank for your reply.

**Comment by wangzy0327** [comment]
> HI @wangzy0327,
> 
> The core SYCL spec explicitly says that [`sycl::kernel`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_the_kernel_class) has no public default constructor (or any other public constructors), so it is only possible to obtain it by calling some other APIs. For example, you can use backend-specific [`make_kernel`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:backend-interoperability-make) or you can query a kernel from [`kernel_bundle`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_the_kernel_bundle_class) using `get_kernel` method.

how to use backend-specfic make_kernel ep:cuda backend ? 

```
kernel make_kernel(const backend_input_t<Backend, kernel>& backendObject,
                   const context& targetContext)
```

how to create backend_input_t<ext_oneapi_cuda,kernel> backendObject ?

**Comment by AlexeySachkov** [comment]
Tagging @npmiller and @JackAKirk here. Folks, could you please help answering questions above?

**Comment by npmiller** [comment]
Hello, for the CUDA backend we don't support `make_kernel` at the moment, but this interface is meant to be used for interoperability, so even if we did the `backend_input_t` would be some CUDA kernel object that you want to call from SYCL.

If you're trying to access a pure SYCL kernel object, I believe the main way to do that is through the kernel bundle class.

**Comment by wangzy0327** [comment]
> Hello, for the CUDA backend we don't support `make_kernel` at the moment, but this interface is meant to be used for interoperability, so even if we did the `backend_input_t` would be some CUDA kernel object that you want to call from SYCL.
> 
> If you're trying to access a pure SYCL kernel object, I believe the main way to do that is through the kernel bundle class.

OK, I meant to use OnlineCompiler reference to  [ref](https://github.com/intel/llvm-test-suite/blob/intel/SYCL/OnlineCompiler/online_compiler_OpenCL.cpp). Are there some good advice?

**Comment by npmiller** [comment]
I'm afraid I don't have a good solution for you. We don't support this interop for the CUDA plugin at the moment, and we only support ahead of time compilation. It may be something we look into in the future but I don't think there's an easy way to work around that currently.

**Comment by AlexeySachkov** [comment]
I assume that all questions were answered and therefore, closing the issue. Feel free to re-open or submit another one for further questions.

**Comment by wangzy0327** [comment]
> I assume that all questions were answered and therefore, closing the issue. Feel free to re-open or submit another one for further questions.

Yes，Thank you for reply
