### ISSUE TITLE
Basic/barrier_order.cpp hangs on opencl:gpu

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#7330]
The new SYCL/Basic/barrier_order.cpp (https://github.com/intel/llvm-test-suite/pull/1122) test in [intel/llvm-test-suite](https://github.com/intel/llvm-test-suite) is failing sporadically in pre-commit CI. See for example https://github.com/intel/llvm/actions/runs/3427185876/jobs/5710264332.

```
******************** TEST 'SYCL :: Basic/barrier_order.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';    /__w/llvm/llvm/toolchain/bin/clang++     -Xsycl-target-backend=amdgcn-amd-amdhsa --offload-arch=gfx1031 -fsycl -fsycl-targets=amdgcn-amd-amdhsa /__w/llvm/llvm/llvm_test_suite/SYCL/Basic/barrier_order.cpp -o /__w/llvm/llvm/build/SYCL/Basic/Output/barrier_order.cpp.tmp.out
: 'RUN: at line 2';   true /__w/llvm/llvm/build/SYCL/Basic/Output/barrier_order.cpp.tmp.out
: 'RUN: at line 3';    env ONEAPI_DEVICE_SELECTOR=ext_oneapi_hip:gpu  /__w/llvm/llvm/build/SYCL/Basic/Output/barrier_order.cpp.tmp.out
--
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 1"
note: command had no output on stdout or stderr
$ "/__w/llvm/llvm/toolchain/bin/clang++" "-Xsycl-target-backend=amdgcn-amd-amdhsa" "--offload-arch=gfx1031" "-fsycl" "-fsycl-targets=amdgcn-amd-amdhsa" "/__w/llvm/llvm/llvm_test_suite/SYCL/Basic/barrier_order.cpp" "-o" "/__w/llvm/llvm/build/SYCL/Basic/Output/barrier_order.cpp.tmp.out"
note: command had no output on stdout or stderr
$ ":" "RUN: at line 2"
note: command had no output on stdout or stderr
$ "true" "/__w/llvm/llvm/build/SYCL/Basic/Output/barrier_order.cpp.tmp.out"
note: command had no output on stdout or stderr
$ ":" "RUN: at line 3"
note: command had no output on stdout or stderr
$ "env" "ONEAPI_DEVICE_SELECTOR=ext_oneapi_hip:gpu" "/__w/llvm/llvm/build/SYCL/Basic/Output/barrier_order.cpp.tmp.out"
# command output:
1111111111111111111111111111111111111111111111111111111111111111
0111111111111111111111111111111111111111111111111111111111111111
failed

error: command failed with exit status: 1

--
```

**Comment by steffenlarsen** [comment]
Temporarily disabled for HIP in https://github.com/intel/llvm-test-suite/pull/1375.

**Comment by zjin-lcf** [comment]
1 std::cout << std::bitset<8 * sizeof(unsigned long long)>(*x) << std::endl;

 2 q.wait_and_throw();
 
Is line2 in front of line1 in the test ?

**Comment by romanovvlad** [comment]
> 1 std::cout << std::bitset<8 * sizeof(unsigned long long)>(*x) << std::endl;
> 
> 2 q.wait_and_throw();
> 
> Is line2 in front of line1 in the test ?

Right the access to `x` should be after `wait_and_throw`. Could be the root cause.

**Comment by Fznamznon** [comment]
The test also fails on CUDA.
https://github.com/intel/llvm/actions/runs/3477880483/jobs/5814961418
https://github.com/intel/llvm/actions/runs/3480131323/jobs/5820955932

**Comment by bader** [comment]
Another fail on CUDA.
https://github.com/intel/llvm/actions/runs/3480747007/jobs/5821438624

**Comment by aelovikov-intel** [comment]
Failed in https://github.com/intel/llvm/actions/runs/3576302183/jobs/6014387312

**Comment by aelovikov-intel** [comment]
Reproducer for the hang we're tracking with this issue currently:

```
#include <sycl/sycl.hpp>

int main() {
  sycl::queue q;
  q.single_task([=]() {});
  q.ext_oneapi_submit_barrier();
#ifdef GOOD
  q.single_task([=]() {});
#endif
  q.wait_and_throw();
  return 0;
}
```

**Comment by omarahmed1111** [comment]
This test have failed on `HIP` porting [PR](https://github.com/intel/llvm/pull/9617) in the [Linux / [AWS] CUDA LLVM Test Suite](https://github.com/intel/llvm/actions/runs/5255237665/jobs/9495377795?pr=9617#logs). The PR is based on top of `CUDA` porting [PR](https://github.com/intel/llvm/pull/9512) which passes the test on the same CI job.

**Comment by aelovikov-intel** [comment]
CI logs expire with time, so copy-pasting the error here:
```
 "env" "SYCL_PI_CUDA_ENABLE_IMAGE_SUPPORT=1" "ONEAPI_DEVICE_SELECTOR=ext_oneapi_cuda:gpu" "/__w/llvm/llvm/build-e2e/Basic/Output/barrier_order.cpp.tmp.out"
# command output:
got: 1111111111111111111111111111111111111111111111111111111111111111
ref: 1111111111111111111111111111111111111111111111111111111111111111
got: 0111111111111111111111111111111111111111111111111111111111111111
ref: 1111111111111111111111111111111111111111111111111111111111111111
failed
```

**Comment by AlexeySachkov** [comment]
I've experienced the same failure recently in #9871 ([CI logs](https://github.com/intel/llvm/actions/runs/5344409611/jobs/9689167097?pr=9871)) and also noticed that CI in #10006 failed with the same issue ([CI logs](https://github.com/intel/llvm/actions/runs/5332809770/jobs/9662882371?pr=10006))

**Comment by aelovikov-intel** [comment]
@intel/llvm-reviewers-cuda , could you investigate the hang on CUDA? Hang on opencl:gpu is unrelated as it is caused by the underlying GPU RT.

**Comment by bader** [comment]
The test fails on my local system with 
```
got: 0000000000000000000000000000000000000000001111111111111111111111
ref: 1111111111111111111111111111111111111111111111111111111111111111
got: 1111111111111111111111111111111111111111111111111111111111111111
ref: 1111111111111111111111111111111111111111111111111111111111111111
failed
```

Considering that it misbehaves on multiple different devices, it should be a bug in some shared component. Either in the barrier implementation or the test itself.
