### ISSUE TITLE
build make failed with intel-llvm clang 16.0.0

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#7343]
**Describe the bug**
sycl-example build by cmake execuate error

sycl build from source  version [ESIMD] Fix specialization/instantiation order in traits infra. (#6677) · intel/llvm@3dc891f (github.com)

**To Reproduce**

<details>
<summary>simple-sycl-app</summary>

```
#include <CL/sycl.hpp>

void show_platforms() {
  auto platforms = sycl::platform::get_platforms();

  for (auto &platform : platforms) {
    std::cout << "Platform: "
	      << platform.get_info<sycl::info::platform::name>()
	      << std::endl;

    auto devices = platform.get_devices();
    for (auto &device : devices ) {
      std::cout << "  Device: "
		<< device.get_info<sycl::info::device::name>()
		<< std::endl;
    }
  }
}

int main() {

  show_platforms();
  // auto name = sycl::info::platform::name;
  // auto con = cl::sycl::context();
  // auto properties = cl::sycl::property_list();
  // Creating buffer of 4 ints to be used inside the kernel code
  cl::sycl::buffer<cl::sycl::cl_int, 1> Buffer(4);

  //sycl::gpu_selector s;

  // Creating SYCL queue
  cl::sycl::queue Queue;
  //cl::sycl::queue Queue();

  auto dev = Queue.get_device();
  std::cout<<"================================"<<std::endl;
  std::cout << "Default Device: "
		<< dev.get_info<sycl::info::device::name>()
		<< std::endl;

  // Size of index space for kernel
  cl::sycl::range<1> NumOfWorkItems{Buffer.size()};

  // Submitting command group(work) to queue
  Queue.submit([&](cl::sycl::handler &cgh) {
    // Getting write only access to the buffer on a device
    auto Accessor = Buffer.get_access<cl::sycl::access::mode::write>(cgh);
    // auto out = sycl::stream(1024, 768, cgh);
    // auto task = [=]() { out << "In a task\n"; };
    // Executing kernel
    cgh.parallel_for<class FillBuffer>(
        NumOfWorkItems, [=](cl::sycl::id<1> WIid) {
          // out<<"parallel for before\n";
          // Fill buffer with indexes
          Accessor[WIid] = (cl::sycl::cl_int)WIid.get(0);
        });
    // cgh.single_task<class stream_task>(task);
  });

  // Getting read only access to the buffer on the host.
  // Implicit barrier waiting for queue to complete the work.
  const auto HostAccessor = Buffer.get_access<cl::sycl::access::mode::read>();

  // Check the results
  bool MismatchFound = false;
  for (size_t I = 0; I < Buffer.size(); ++I) {
    if (HostAccessor[I] != I) {
      std::cout << "The result is incorrect for element: " << I
                << " , expected: " << I << " , got: " << HostAccessor[I]
                << std::endl;
      MismatchFound = true;
    }
  }

  if (!MismatchFound) {
    std::cout << "The results are correct!" << std::endl;
  }

  return MismatchFound;
}

```
</details>

<details>
<summary>CMakeLists.txt</summary>

```
cmake_minimum_required(VERSION 2.8.12)

set(CMAKE_C_COMPILER "/home/wzy/sycl_workspace/tvm-sycl-build-cuda-debug/bin/clang")
set(CMAKE_CXX_COMPILER "/home/wzy/sycl_workspace/tvm-sycl-build-cuda-debug/bin/clang++")
set(CMAKE_CXX_STANDARD 17)

project(simple-sycl-app)

set(DPCPP_HOME "/home/wzy/sycl_workspace")
set(DPCPP_SYCL_HOME "${DPCPP_HOME}/tvm-sycl-build-cuda-debug")


message(STATUS "dpcpp_home : ${DPCPP_HOME}")
message(STATUS "dpcpp_cuda_sycl_home : ${DPCPP_SYCL_HOME}")


#link_directories("${DPCPP_SYCL_HOME}/tvm-sycl-build-cuda-debug/lib")
message(STATUS "find library path : ${DPCPP_SYCL_HOME}/lib")
set(CMAKE_BUILD_RPATH "${DPCPP_SYCL_HOME}/lib;${CMAKE_BUILD_RPATH}")
message(STATUS "cmake build rpath : ${CMAKE_BUILD_RPATH}")

# set(CMAKE_BUILD_PATH "${DPCPP_SYCL_HOME}/lib:${CMAKE_BUILD_PATH}")

set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")

# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
# include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")

add_compile_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)

link_directories("${DPCPP_SYCL_HOME}/lib")

aux_source_directory(. DIR_SRCS)
add_executable(simple-sycl-app ${DIR_SRCS})
add_link_options(-fsycl -fsycl-targets=nvptx64-nvidia-cuda)
target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include/sycl")
target_include_directories(simple-sycl-app PRIVATE "${DPCPP_SYCL_HOME}/include")
#target_link_libraries(simple-sycl-app -fsycl -fsycl-targets=nvptx64-nvidia-cuda -lsycl)
# target_link_libraries(simple-sycl-app PRIVATE ${SYCL} )
target_link_libraries(simple-sycl-app PRIVATE sycl )
```

</details>

![image](https://user-images.githubusercontent.com/22990858/200982974-bfb5ac2b-889f-4b0e-8f89-5b4c71f2405e.png)

how to solve the problem?

**Environment (please complete the following information):**

- OS: Ubuntu18.04
- Target device and vendor: Nvidia GPU
- DPC++ version: clang++ 16.00
- Dependencies version: g++ 7.5.0

**Additional context**

**Comment by maksimsab** [comment]
@wangzy0327 Hi.
I see error message: `/opt/rh/devtoolset-8/root/usr/bin/gmake cmTC_6b0a6/fast && No such file or directory`

Probably, you don't have gmake tool installed in your system. Please, check it and if it isn't installed then install it or specify different generator.

**Comment by wangzy0327** [comment]
> @wangzy0327 Hi. I see error message: `/opt/rh/devtoolset-8/root/usr/bin/gmake cmTC_6b0a6/fast && No such file or directory`
> 
> Probably, you don't have gmake tool installed in your system. Please, check it and if it isn't installed then install it or specify different generator.

how to specify different generator like make?

**Comment by maksimsab** [comment]
You can use cmake option `-G`
Example:
```
cmake -G "Unix Makefiles"  .
```

The list of available generators is [here](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html).

Alternatively, you can specify a full path to the generator using cmake parameter [CMAKE_MAKE_PROGRAM](https://cmake.org/cmake/help/latest/variable/CMAKE_MAKE_PROGRAM.html)
Example:
```
cmake -DCMAKE_MAKE_PROGRAM=/home/wzy/path/to/your/generator .
```

**Comment by wangzy0327** [comment]
> usr/bin/gmake cmTC_6b0a6/fast && No such file or directory

how to solve the problem 'error: sixth template parameter of the accessor must be of accessor_pro
perty_list type'?

![image](https://user-images.githubusercontent.com/22990858/202177261-01d7cb0a-66cb-460c-8af6-6b36d2de0821.png)

**Comment by maksimsab** [comment]
@wangzy0327. I see that this app is from GetStartedGuide. Could you please test suggested CMake? [This one](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#build-dpc-application-with-cmake)

**Comment by wangzy0327** [comment]
Yes,I use it.But the code seems apply old version(clang 15) instead of new version(clang 16).The code running occurs error in simple-sycl-app the line 'Accessor[WIid] = (cl::sycl::cl_int)WIid.get(0); '

**Comment by maksimsab** [comment]
Please check if your `PATH` variable contains a path to clang 16.

Or set `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` variables as you did in your CMakeLists. And try to remote your modifications with `add_link_options(...)` and stuff like that.

**Comment by wangzy0327** [comment]
> Please check if your `PATH` variable contains a path to clang 16.
> 
> Or set `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` variables as you did in your CMakeLists. And try to remote your modifications with `add_link_options(...)` and stuff like that.

![image](https://user-images.githubusercontent.com/22990858/202209181-11b423de-9c8c-41ea-b8b3-c92024a3c13d.png)

![Uploading image.png…]()

**Comment by maksimsab** [comment]
@wangzy0327 Can I close this issue?
