### ISSUE TITLE
[SYCL][PI] Design PI plugin lookup to be reusable in tools and tests

### ISSUE THREAD

**Issue by bjoernknafla** [intel/llvm#741]
With the [move to PI plugins as dynamic libraries](https://github.com/intel/llvm/pull/708) as documented [here](https://github.com/intel/llvm/pull/680) the PI unittests need to be changed.

Ideally PI plugin discovery should use the same mechanism as the one used by the SYCL runtime.

If it was possible to set up the PI plugin discovery mechanism as a (static?) library, then PI specific unittests and other tools on top of PI would be straightforward to implement.

**Comment by romanovvlad** [comment]
The current plan is to get rid of real plugin discovery logic in unittests(see https://github.com/intel/llvm/pull/6684/files) and there are no tools(please correct me if I'm wrong) which would reuse this functionality. So, closing this, we can get back to this if we find more use cases. Please, feel free to reopen if there are any concerns.
