### ISSUE TITLE
[MLIR] error: ‘decodeBase64’ is not a member of ‘llvm’

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#7515]
**Describe the bug**

With the following change to enable mlir as an external project:
```
--- a/buildbot/configure.py
+++ b/buildbot/configure.py
@@ -13,7 +13,7 @@ def do_configure(args):
-    llvm_external_projects = 'sycl;llvm-spirv;opencl;xpti;xptifw'
+    llvm_external_projects = 'sycl;llvm-spirv;opencl;xpti;xptifw;mlir'
```
`ninja check-mlir` fails with `error: ‘decodeBase64’ is not a member of ‘llvm’`.

Commit 26e2524ddf4d pull in bf87d5ad8207b6002d0ff247f4803698be35950d, which uses `llvm::decodeBase64`.
The definition of `llvm::decodeBase64` is removed in 1ef977aafbea0f2379a879879bbac93333efc6d5 when resolving a merge conflict.

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. Modify `configure.py`:
```
--- a/buildbot/configure.py
+++ b/buildbot/configure.py
@@ -13,7 +13,7 @@ def do_configure(args):
-    llvm_external_projects = 'sycl;llvm-spirv;opencl;xpti;xptifw'
+    llvm_external_projects = 'sycl;llvm-spirv;opencl;xpti;xptifw;mlir'
```
2. Then run the following commands:
```
python3 buildbot/configure.py
python3 buildbot/compile.py
cd build
ninja check-mlir
```

**Environment (please complete the following information):**

- OS: Linux
- DPC++ version: 26e2524ddf4d

**Comment by whitneywhtsang** [comment]
FYI @dwoodwor-intel

**Comment by dwoodwor-intel** [comment]
It looks like the function was supposed to be re-added by ea9ac3519c13 but was lost in the merge 8b549f64a62f. I've posted #7517 to fix this.

**Comment by etiotto** [comment]
@whitneywhtsang #7517 was merged, is this problem fixed ?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang #7517 was merged, is this problem fixed ?

It is not merged. I am still waiting for it to be merged.
