### ISSUE TITLE
[SYCL][CUDA] memory access across peer devices

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#7543]
I tried to run DPCT on a CUDA sample and it shows the following message for the function `cudaDeviceCanAccessPeer(&can_access_peer, i, j);`
```
SYCL currently does not support memory access across peer devices.
```

**Comment by JackAKirk** [comment]
There is not yet a corresponding function to `cudaDeviceCanAccessPeer` in DPC++.

See my answer here:

https://github.com/intel/llvm/issues/6749#issuecomment-1307091990

and discussion here:

https://github.com/intel/llvm/pull/6104

for a summary for the P2P status.
