### ISSUE TITLE
[SPV_INTEL_function_pointers] inconsistent spelling of IndirectReferencesINTEL

### ISSUE THREAD

**Issue by SamB** [intel/llvm#7548]
The [SPV_INTEL_function_pointers](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_function_pointers.asciidoc) apparently sometimes spells **IndirectReferencesINTEL** as **IndirectlyReferencableINTEL**.

(I would have sent a patch, but couldn't figure out how to search and replace in github's editor on my phone.)

**Comment by MrSidims** [comment]
Thanks! As a side note, in the translator the capability is known as IndirectReferencesINTEL

**Comment by AlexeySachkov** [comment]
PR with the fix: #8147
