### ISSUE TITLE
Why accessor get data not equal primary data?

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#7591]
**Describe the bug**

My code ref [doc](https://sycl.readthedocs.io/en/latest/iface/queue.html#queue-example-2)

Before I add the code
```
cgh.copy(data_accessor,data);
```
the code can run.But the data print not synchronize device operation. The result display as follow:
![df6d55a13cf101a5cae4392c9c5f35d](https://user-images.githubusercontent.com/22990858/204818989-a9c47300-8756-4867-b31a-f7ee1bab128c.png)

Then I add the code "cgh.copy(data.accessor,data)" to copy result from device to host.It get error ?

![image](https://user-images.githubusercontent.com/22990858/204819287-3a001ac7-98cc-4014-ab3e-2820fdbd83cc.png)

how can I sovle the problem ?

terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Attempt to set multiple actions for the command group. Command group must consist of a single kernel or explicit memory operation. -59 (PI_ERROR_INVALID_OPERATION)

**To Reproduce**

<details>
<summary>my-example-code</summary>

```
#include <sycl/sycl.hpp>
#include <iostream>
#include <algorithm>

using namespace sycl; // (optional) avoids need for "sycl::" before SYCL names

constexpr int count = 10;

class AddFive; // Forward declare the name of our kernel.

int main() {
  size_t N = 1024;
  queue myQueue;
  auto myContext = myQueue.get_context();
  auto myDev = myQueue.get_device();

  // Get an executable kernel bundle containing our kernel.
  kernel_id kernelId = get_kernel_id<AddFive>();
  std::string myKernelName = kernelId.get_name();
  std::cout<<"my kernel name : "<<myKernelName<<std::endl;
  auto myBundle =
      get_kernel_bundle<bundle_state::executable>(myContext, { kernelId });

  // Get the kernel's maximum work group size when running on our device.
  kernel myKernel = myBundle.get_kernel(kernelId);
  size_t maxWgSize =
      myKernel.get_info<info::kernel_device_specific::work_group_size>(myDev);

  std::cout<<"maxWgSize group size : "<<maxWgSize<<std::endl;
  // Compute a good ND-range to use for iteration in the kernel
  // based on the maximum work group size.
  std::array<size_t, 11> divisors = { 1024, 512, 256, 128, 64, 32,
                                      16,   8,   4,   2,   1 };
  size_t wgSize = *std::find_if(divisors.begin(), divisors.end(),
                                [=](auto d) { return (d <= maxWgSize); });

  std::cout<<"work group size : "<<wgSize<<std::endl;

  // Data initialized to zeros.
  int data[count] {0};
//   std::vector<int> vec_data(count,0);
  sycl::buffer<int, 1> data_buffer(data,sycl::range<1>(count));   
  
//   sycl::buffer<int, 1, std::vector<int>> vec_data_buffer(vec_data.data(), sycl::range<1>(count));                                  
  nd_range<1> myRange { range<1> { N }, range<1> { wgSize } };

  myQueue.submit([&](handler& cgh) {
    // Use the kernel bundle we queried, so we are sure the queried work-group
    // size matches the kernel we run.
    // accessor acc  {data_buffer,cgh,range<1>(vec_data.size()/2),nd_item<1>(0),sycl::access::mode::read_write};
    auto data_accessor =
          data_buffer.get_access<sycl::access::mode::read_write>(cgh);
    // cgh.copy(vec_data.data(),data_accessor);          
    cgh.use_kernel_bundle(myBundle);
    cgh.parallel_for<class AddFive>(myRange, ([=](nd_item<1> index) {
                                 // kernel code
                                 auto in = index.get_global_id(0);
                                         data_accessor[in] += 5;        
                               }));
    //copy elements of the vector into buffer associated with the accesstor
    cgh.copy(data_accessor,data);
  });

  myQueue.wait();

  for (auto e : data)
    std::cout << e << " ";
  std::cout << std::endl;

  auto arr = data_buffer.get_access<sycl::access::mode::read>();
  for (int i = 0;i < count;i++){
    std::cout<<arr[i]<<" ";
    if (arr[i] != 5) {
        std::cout << "Wrong value " << arr[i] << " on element not equal 5 " << std::endl;
        exit(-1);
    }
  }

  std::cout<<std::endl;
  std::cout << "Good Random distribution !" << std::endl;
  return 0; 

}
```

</details>

1. Include code snippet as short as possible
2. Specify the command which should be used to compile the program
3. Specify the comment which should be used to launch the program
4. Indicate what is wrong and what was expected

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: [2022-09]
- Dependencies version: cuda 11.2

**Additional context**

**Comment by dm-vodopyanov** [comment]
Hello @wangzy0327, it is undefined behavior to access the original data (`arr` in the example) in the same scope in which `sycl::buffer` which owns `arr` (`data_buffer` in the example) is initialized. During `sycl::buffer` object destruction, implicit copy of the result from device to host is happening, so no need to call `cgh.copy(...)` explicitly. Regarding the second issue, SYCL prohibits to put multiple kernels and/or memory operations to the single `submit` aka command group. Only one kernel / memory operation per single command group is allowed.
These are the changes which should be made to get rid of the issue, do they work for you?

```diff --git a/code.cpp b/code.cpp
index d00ffa2..f29670b 100644
--- a/code.cpp
+++ b/code.cpp
@@ -39,6 +39,7 @@ int main() {
   // Data initialized to zeros.
   int data[count] {0};
 //   std::vector<int> vec_data(count,0);
+  {
   sycl::buffer<int, 1> data_buffer(data,sycl::range<1>(count));   
   
 //   sycl::buffer<int, 1, std::vector<int>> vec_data_buffer(vec_data.data(), sycl::range<1>(count));                                  
@@ -57,16 +58,10 @@ int main() {
                                  auto in = index.get_global_id(0);
                                          data_accessor[in] += 5;        
                                }));
-    //copy elements of the vector into buffer associated with the accesstor
-    cgh.copy(data_accessor,data);
   });
 
   myQueue.wait();
 
-  for (auto e : data)
-    std::cout << e << " ";
-  std::cout << std::endl;
-
   auto arr = data_buffer.get_access<sycl::access::mode::read>();
   for (int i = 0;i < count;i++){
     std::cout<<arr[i]<<" ";
@@ -75,7 +70,11 @@ int main() {
         exit(-1);
     }
   }
+  std::cout << std::endl;
+  }
 
+  for (auto e : data)
+    std::cout << e << " ";
   std::cout<<std::endl;
   std::cout << "Good Random distribution !" << std::endl;
   return 0; 
```

**Comment by wangzy0327** [comment]
> Hello @wangzy0327, it is undefined behavior to access the original data (`arr` in the example) in the same scope in which `sycl::buffer` which owns `arr` (`data_buffer` in the example) is initialized. During `sycl::buffer` object destruction, implicit copy of the result from device to host is happening, so no need to call `cgh.copy(...)` explicitly. Regarding the second issue, SYCL prohibits to put multiple kernels and/or memory operations to the single `submit` aka command group. Only one kernel / memory operation per single command group is allowed. These are the changes which should be made to get rid of the issue, do they work for you?
> 
> ```diff
> index d00ffa2..f29670b 100644
> --- a/code.cpp
> +++ b/code.cpp
> @@ -39,6 +39,7 @@ int main() {
>    // Data initialized to zeros.
>    int data[count] {0};
>  //   std::vector<int> vec_data(count,0);
> +  {
>    sycl::buffer<int, 1> data_buffer(data,sycl::range<1>(count));   
>    
>  //   sycl::buffer<int, 1, std::vector<int>> vec_data_buffer(vec_data.data(), sycl::range<1>(count));                                  
> @@ -57,16 +58,10 @@ int main() {
>                                   auto in = index.get_global_id(0);
>                                           data_accessor[in] += 5;        
>                                 }));
> -    //copy elements of the vector into buffer associated with the accesstor
> -    cgh.copy(data_accessor,data);
>    });
>  
>    myQueue.wait();
>  
> -  for (auto e : data)
> -    std::cout << e << " ";
> -  std::cout << std::endl;
> -
>    auto arr = data_buffer.get_access<sycl::access::mode::read>();
>    for (int i = 0;i < count;i++){
>      std::cout<<arr[i]<<" ";
> @@ -75,7 +70,11 @@ int main() {
>          exit(-1);
>      }
>    }
> +  std::cout << std::endl;
> +  }
>  
> +  for (auto e : data)
> +    std::cout << e << " ";
>    std::cout<<std::endl;
>    std::cout << "Good Random distribution !" << std::endl;
>    return 0; 
> ```

OK，Thank you for reply. The code works correctly.
There are two question about sycl memory.
1. If I want to copy memory data from sycl Device to anothor sycl Device, it seems no relative API to directly complete the op.
2. In my development project with sycl , I met the piUSMFree Error by 
···
free(data,queue)
···
![image](https://user-images.githubusercontent.com/22990858/204850233-6dae9e68-e495-4f24-9e44-0c226cc858cf.png)

Do you have any advice about cause this error ?

**Comment by AlexeySachkov** [comment]
It seems like all the questions from this thread have been answered, so I will close the issue. If there are still questions, or problems, please open a new issue and we will take a look
