### ISSUE TITLE
[SYCL][HIP] HIP backend timing out on max_local in CI

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#7604]
[SYCL/AtomicRef/max_local.cpp](https://github.com/intel/llvm-test-suite/blob/intel/SYCL/AtomicRef/max_local.cpp) in the test-suite is seen to cause a time-out in Linux CI for HIP target. See for example [6041169168](https://github.com/intel/llvm/actions/runs/3588593330/jobs/6041169168) and [6040184966](https://github.com/intel/llvm/actions/runs/3588479558/jobs/6040184966).

**Comment by zjin-lcf** [comment]
I am confused by the comments. Does HIP support floating point atomics ?

**Comment by steffenlarsen** [comment]
Thank you, @hdelan ! Closing this issue, then we can reopen if the issue persists.
