### ISSUE TITLE
[SYCL-MLIR] Investigate `check-cgeist` failures with `d948427`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#7647]
d9484274cd1a21f90509cb79f0cd5f425f8f9e3b comes from `sycl` branch.
When merging `sycl` branch to `sycl-mlir` branch, we noticed that d9484274cd1a21f90509cb79f0cd5f425f8f9e3b causes `check-cgeist` failures, so we reverted it in `sycl-mlir` branch temporally. 
We need to investigate the failures, and add it back.

To reproduce:
```
git revert 9f5ba51229b090fc6af1db1b7b25494d241f86b1
ninja check-cgeist
```

**Comment by etiotto** [comment]
@whitneywhtsang is this still valid or can you close it?

**Comment by whitneywhtsang** [comment]
Resolved by https://github.com/intel/llvm/pull/7648.
