### ISSUE TITLE
[Bug] Assertion KSIdMap[EntriesIt->name] == KSIdIt->second &&   "Kernel sets are not disjoint"

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#7676]
**Describe the bug**

When I run my code by [intel/llvm 2022-09](https://github.com/intel/llvm/tree/2022-09), it occurs a assertion error in [addImages](https://github.com/intel/llvm/blob/2022-09/sycl/source/detail/program_manager/program_manager.cpp).

I saw there is TODO . Does it have some tutorial and document of the program_manager ?

And how to solve the problem?

![1375807c573ce0d6a0634b24025bef5](https://user-images.githubusercontent.com/22990858/206084908-0c3b5fb9-b90d-4023-b3bb-34f11e2264d6.png)

![image](https://user-images.githubusercontent.com/22990858/206086374-24ca6ebb-07fa-4e4c-bf68-f932f51ad9f6.png)

**To Reproduce**

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: [NvidiaGPU]
- DPC++ version:  sycl 2022-09 clang-16.0.0
- Dependencies version: cuda 11.2

**Additional context**

**Comment by AlexeySachkov** [comment]
I remember that there were some discussions concluding that this particular assertion is an incorrect assumption and it should be removed and surrounding code adjusted.

I wasn't able to find the exact commit which did that, but the assertion is not there anymore, from what I can see.

Tagging @KseniyaTikhomirova, @sergey-semenov here to comment further if we still have a limitation described in the assertion above. If we don't have it anymore, then I think that this issue can be closed

**Comment by KseniyaTikhomirova** [comment]
@AlexeySachkov assert was removed in https://github.com/intel/llvm/commit/4817b3f61f0423dcbc734d279084a3e0a5bb0eea. I am pretty confident we don't have it since then.
