### ISSUE TITLE
get_access for host accessor is deprecated in SYCL 2020

### ISSUE THREAD

**Issue by tomdeakin** [intel/llvm#7698]
`__SYCL2020_DEPRECATED` should be added to this deprecated method, in favour of the new `get_host_access()` method.

https://github.com/intel/llvm/blob/ead840494a6ecbd534f9161190217c02d3c6189a/sycl/include/sycl/buffer.hpp#L509

**Comment by marcin-smuklerz-mobica** [comment]
It looks it was fixed with this pull request:
https://github.com/intel/llvm/pull/8005

**Comment by KornevNikita** [comment]
Done by https://github.com/intel/llvm/pull/8005
