### ISSUE TITLE
The values of the advice argument in the mem_advise function

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#7708]
Do users need to look into the pi_cuda.cpp to know the values for `advice` in the function ?  

```
void mem_advise(void* ptr, size_t numBytes, int advice)
```

Could the values of `advice` be vendor-agnostic ?

Thanks

**Comment by npmiller** [comment]
The values are vendor/backend agnostic:

From the `mem_advise` section of [Table 134](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.members.handler.copy):

> The values for advice are vendor- or backend-specific, with the exception of the value 0 which reverts the advice for ptr to the default behavior.

However it looks like the values are not documented anywhere currently, so we should fix that.

**Comment by zjin-lcf** [comment]
These values are vendor-specific, but I hope they are not.  Thanks.

**Comment by JackAKirk** [comment]
They are documented here: https://github.com/KhronosGroup/SYCL-Docs/pull/420/files#diff-c1ccc21c9f986f2300984f76b8c363000dc0335cb43b545824a956c0bcb2d742R83
although it maybe looks out of date.

**Comment by JackAKirk** [comment]
We have updated our docs with the up to date information regarding this and they will appear at https://developer.codeplay.com/products/oneapi/nvidia/2024.2.1/guides/get-started-guide-nvidia when the 2025.0 plugins are released.
