### ISSUE TITLE
 undefined symbol: _ZNK4sycl3_V16detail12buffer_plain13handleReleaseEv

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#7716]
**Describe the bug**
Since 894ce25635c5ead4d1c42e70f66d1970c86a7bf5, there is a runtime failure ` undefined symbol: _ZNK4sycl3_V16detail12buffer_plain13handleReleaseEv` when running sycl test cases. Also fails on 9f9503ffb3e81d5b19d4df798a9a5e65cdbd6c03 and a534b94e32f7bc96f548183c8bf506a57910ee98.

**To Reproduce**
```
clang++ -fsycl t.cpp
./a.out
```
t.cpp:
```
#include <sycl/sycl.hpp>
using namespace sycl;

void single_task(std::array<int, 1> &A) {
  auto q = queue{};

  {
    auto buf = buffer<int, 1>{A.data(), 1};
    q.submit([&](handler &cgh) {
      auto A = buf.get_access<access::mode::write>(cgh);
      cgh.single_task<class kernel_single_task>([=]() {
        A[0] = 1;
      });
    });
  }
}

int main() {
  std::array<int, 1> A = {0};
  single_task(A);
  assert(A[0] == 1);
  std::cout << "Test passed" << std::endl;
}
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Intel CPU
- DPC++ version: 894ce25635c5ead4d1c42e70f66d1970c86a7bf5

**Comment by KseniyaTikhomirova** [comment]
@whitneywhtsang I could not reproduce the issue you reported. I guess that this may happen if headers files and library is used from different builds (headers - after my changes and old library without). Could you please double check your environment or do the same on clear environment and provide more detailed steps to reproduce?

**Comment by whitneywhtsang** [comment]
@KseniyaTikhomirova True, my LD_LIBRARY_PATH is pointing to an old library. Thanks for looking into it. Closing the issue.

**Comment by koaie** [comment]
> LD_LIBRARY_PATH

Hi, im having the same issue, would you mind listing the current libraries you are using?
best regards

**Comment by whitneywhtsang** [comment]
> Hi, im having the same issue, would you mind listing the current libraries you are using?

There are over 700 files in my current libraries. Try to build from scratch and ensure your LD_LIBRARY_PATH point to the build lib directory.

**Comment by koaie** [comment]
> > Hi, im having the same issue, would you mind listing the current libraries you are using?
> 
> There are over 700 files in my current libraries. Try to build from scratch and ensure your LD_LIBRARY_PATH point to the build lib directory.

Thank you!, i had an old directory in there :x
