### ISSUE TITLE
Where are *.bc files locate?

### ISSUE THREAD

**Issue by nVietUK** [intel/llvm#7725]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8066	Custom build for 'A:\nVietUK\llvm\build\CMakeFiles\50b8e60535849051e1fa2d437c055110\builtins.opt.libspirv-nvptx64--nvidiacl.bc.rule;A:\nVietUK\llvm\build\CMakeFiles\dcdd0522c571bf86f7194fb18854c766\opt.libspirv-nvptx64--nvidiacl.bc.rule' exited with code 1.	opt.libspirv-nvptx64--nvidiacl.bc	B:\VisualStudio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	247	
```

OS: Windows 10 
GPU: RTX 2060
CUDA toolkit version: 11.8
Visual studio: latest

Can someone help me to solve this problem, please?

**Comment by JackAKirk** [comment]
How are you building dpc++? Please try a completely fresh build by deleting your current build directory if you are building from source. Those .bc libraries have out of date names. A fresh build may fix it.

**Comment by nVietUK** [comment]
i've tried many times but i realized that using `--cuda` on windows 10 with cuda 11.8 is impossible
