### ISSUE TITLE
How to build flang and openmp with sycl?

### ISSUE THREAD

**Issue by nVietUK** [intel/llvm#7735]
I want to build this llvm but i'm also need both flang and openmp to build other repo. How can i build with these features?

**Comment by AlexeySachkov** [comment]
Hi @nVietUK,

You can pass`--llvm-external-projects openmp,flang` argument to `configure.py` to enable those. If you are launching `cmake` manually, than an alternative would be to extend the value of `-DLLVM_ENABLE_PROJECTS`. See related discussion #6921

**Comment by zjin-lcf** [comment]
Is it openmp target offloading ?
