### ISSUE TITLE
code_location_e2e in intel/llvm-test-suite times out on Windows

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#7740]
**Describe the bug**
Basic/code_location_e2e.cpp is seen to time out on Windows in intel/llvm verification runs. See for example https://github.com/intel/llvm/pull/7391 and https://github.com/intel/llvm/pull/7077.

**Environment:**

- OS: Windows

**Comment by KseniyaTikhomirova** [comment]
fixed by https://github.com/intel/llvm/commit/d47b99e327774b37744eac333369a53102e610f0
