### ISSUE TITLE
HostInteropTask in intel/llvm-test-suite time out on Windows

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#7741]
**Describe the bug**
HostInteropTask/host-task-failure.cpp and HostInteropTask/host-task.cpp are seen to time out on Windows in intel/llvm verification runs. See for example https://github.com/intel/llvm/pull/7391 and https://github.com/intel/llvm/pull/7077.

**Environment:**

- OS: Windows

**Comment by KseniyaTikhomirova** [comment]
I am working on it right now

**Comment by KseniyaTikhomirova** [comment]
should fix: https://github.com/intel/llvm/pull/7801
