### ISSUE TITLE
multiple-kernel-linking.cpp in intel/llvm-test-suite fails on Windows

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#7742]
**Describe the bug**
KernelAndProgram/multiple-kernel-linking.cpp has been seen failing in intel/llvm verification passes. See for example https://github.com/intel/llvm/pull/7391 and https://github.com/intel/llvm/pull/7077.

Ouput:

```
$ "env" "ONEAPI_DEVICE_SELECTOR=opencl:cpu" "...\build\SYCL\KernelAndProgram\Output\multiple-kernel-linking.cpp.tmp_per_kernel.out"
note: command had no output on stdout or stderr
$ "FileCheck" "...\llvm-test-suite\SYCL\KernelAndProgram\multiple-kernel-linking.cpp"
# command stderr:
FileCheck error: '<stdin>' is empty.
FileCheck command line:  filecheck.exe ...\llvm-test-suite\SYCL\KernelAndProgram\multiple-kernel-linking.cpp

error: command failed with exit status: 2
```

**Environment (please complete the following information):**

- OS: Windows
- Backend: OpenCL

**Comment by KseniyaTikhomirova** [comment]
fixed by https://github.com/intel/llvm/pull/7801
