### ISSUE TITLE
Multiple intel/llvm-test-suite reduction tests failing with L0 on Windows

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#7743]
**Describe the bug**
The following reduction tests from the intel/llvm-test-suite repo are seen failing for L0 on Windows in intel/llvm verification runs:

* SYCL :: Reduction/reduction_big_data.cpp
* SYCL :: Reduction/reduction_nd_N_vars.cpp
* SYCL :: Reduction/reduction_nd_ext_half.cpp
* SYCL :: Reduction/reduction_nd_lambda.cpp
* SYCL :: Reduction/reduction_nd_rw.cpp
* SYCL :: Reduction/reduction_range_1d_dw.cpp
* SYCL :: Reduction/reduction_range_1d_dw_64bit.cpp
* SYCL :: Reduction/reduction_range_1d_rw.cpp
* SYCL :: Reduction/reduction_range_2d_dw.cpp
* SYCL :: Reduction/reduction_range_2d_rw.cpp
* SYCL :: Reduction/reduction_range_3d_dw.cpp
* SYCL :: Reduction/reduction_range_3d_rw.cpp
* SYCL :: Reduction/reduction_range_lambda.cpp
* SYCL :: Reduction/reduction_usm_dw.cpp

See for example https://github.com/intel/llvm/pull/7391 and https://github.com/intel/llvm/pull/7077.

**Environment:**

- OS: Windows
- Backend: Level-zero

**Comment by aelovikov-intel** [comment]
Reproduced with #6837, all pass with commit before it. Tagging @KseniyaTikhomirova .

**Comment by KseniyaTikhomirova** [comment]
@steffenlarsen, @aelovikov-intel hello, is it flaky failures?

**Comment by aelovikov-intel** [comment]
Looked stable enough, but I didn't look deeper.

**Comment by KseniyaTikhomirova** [comment]
@aelovikov-intel thanks, the reason I am asking - it haven't failed in precommit and post commit for my change. So want to understand how likely it is related to that feature. I will take a look tomorrow.

**Comment by KseniyaTikhomirova** [comment]
should fix https://github.com/intel/llvm/pull/7801
