### ISSUE TITLE
Multiple intel/llvm-test-suite DeviceLib tests failing with L0 on Windows

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#7744]
**Describe the bug**
The following device-lib tests from the intel/llvm-test-suite repo are seen failing for L0 on Windows in intel/llvm verification runs:

* SYCL :: DeviceLib/imf_fp16_trivial_test.cpp
* SYCL :: DeviceLib/imf_fp32_test.cpp
* SYCL :: DeviceLib/imf_half_type_cast.cpp

See for example https://github.com/intel/llvm/pull/7391 and https://github.com/intel/llvm/pull/7077.

**Environment:**

- OS: Windows
- Backend: Level-zero

**Comment by KseniyaTikhomirova** [comment]
should fix: https://github.com/intel/llvm/pull/7801
