### ISSUE TITLE
[SYCL][CUDA] Nvidia GPUs detected under multiple platform

### ISSUE THREAD

**Issue by TejaX-Alaghari** [intel/llvm#7808]
**Describe the bug**
On a system with 2 Nvidia GPUs, SYCL detected the 2 devices as being under 2 different platforms. Whereas the expected behavior is for them to be listed under a single Nvidia platform.

**To Reproduce**
1. A simple program to list the devices in the environment [sycl_info.cpp](https://github.com/intel/llvm/files/10242958/sycl_info.cpp.txt)

2. Compilation command: `clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda sycl_info.cpp -o sycl_info`
3. Launch command: `./sycl_info` 
Output: [SYCLInfo.txt](https://github.com/intel/llvm/files/10243028/SYCLInfo.txt)
4. The two devices in the above log are listed under 2 different platforms instead of being grouped under a single platform as shown by `clinfo -l` 
Output: [CLInfo.txt](https://github.com/intel/llvm/files/10242895/CLInfo.txt)

**Environment:**
- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: 16.0.0 (https://github.com/intel/llvm.git 7e37406a40b8f661c1173d41eef8ad30ddade9a1)
- Dependencies: 
Nvidia Driver Version: 525.60.13
CUDA Version: 12.0

**Additional Information**

Log of `sycl-ls --verbose` [sycl_ls.txt](https://github.com/intel/llvm/files/10243027/sycl_ls.txt)
Log of `nvidia-smi` [NVInfo.txt](https://github.com/intel/llvm/files/10242893/NVInfo.txt)
Log of `nvidia-smi -a` [nvidia_smi_a.txt](https://github.com/intel/llvm/files/10243046/nvidia_smi_a.txt)

**Comment by pengtu** [comment]
[https://github.com/intel/llvm/issues/7808](url)

**Comment by JackAKirk** [comment]
Closed by https://github.com/intel/llvm/pull/13616
