### ISSUE TITLE
[HIP][CUDA] `get_native` for `sycl::queue` returns different pointers for every call

### ISSUE THREAD

**Issue by densamoilov** [intel/llvm#7837]
I'm using clang version 16.0.0 (https://github.com/intel/llvm.git 9dc14a292f479880b5ab2e95f99a8414b31d1165) with HIP backend (tried rocm-5.0.0 and rocm-5.3.0). 
Every call to `get_native` for a SYCL queue returns different pointers. This becomes a problem when we have to use different AMD libraries (e.g. MIOpen and rocBLAS) that have different handles. We have to set the same stream for all the handles so that all the functions called from the libraries are executed in order. Right now they are executed independently from each other.

**Update**
The same problem exists for CUDA backend.

Below is a reproducer:
```cpp
#include <sycl/sycl.hpp>
#include <sycl/ext/oneapi/backend/hip.hpp>

using namespace sycl;

int main() {
    auto dev = device(gpu_selector_v);
    auto q = queue(dev);
    auto stream1 = sycl::get_native<sycl::backend::ext_oneapi_hip>(q);
    auto stream2 = sycl::get_native<sycl::backend::ext_oneapi_hip>(q);
    printf("stream1:%p, stream2:%p\n", stream1, stream2);
    return 0;
}
```
Output:
```bash
stream1:0x1e3eeb0, stream2:0x1b363d0
```

**Comment by zjin-lcf** [comment]
The pointers are different for the CUDA backend.

**Comment by abagusetty** [comment]
This could be related to multiple (CUDA, HIP) streams mapping to a SYCL queue to provide the functionality of out-of-order queue,which is the case above in the snippet.

Can you try creating the SYCL queue with `in_order` property and verify ?

**Comment by densamoilov** [comment]
For `in-order` the pointers are identical. So different pointers are different streams that are used to implement out-out-order` queue, I see. It seems it was implemented for HIP recently (https://github.com/intel/llvm/pull/7033).

Ok, now I know what the pointers represent and that this is expected. I'm closing this issue, thanks for the clarification!
