### ISSUE TITLE
[hip] Does intel/llvm toolchain support rocm5.2 ?

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#7842]
**Describe the bug**
Does intel/llvm toolchain support rocm5.2 ?

**Comment by abagusetty** [comment]
@wangzy0327  Yes, rocm-5.2 was tested and seems to have no limitations.

**Comment by wangzy0327** [comment]
> @wangzy0327 Yes, rocm-5.2 was tested and seems to have no limitations.

OK，Thank you for reply.
