### ISSUE TITLE
[SYCL] -save-temps unable to create target with default triple

### ISSUE THREAD

**Issue by hailijuan** [intel/llvm#787]
$ bin/clang++ -fsycl simple-sycl-app.cpp -save-temps
error: unable to create target: 'No available targets are compatible with triple "spir64_x86_64-unknown-linux-sycldevice"'
1 error generated.
/usr/bin/ld: cannot find a-sycl-spir64_x86_64-unknown-linux-sycldevice-wrapper.o: No such file or directory
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)

The error would be gone if there is no -save-temps in clang options.

**Comment by AGindinson** [comment]
https://github.com/intel/llvm/pull/1114

**Comment by AGindinson** [comment]
Fixed by #1114.
