### ISSUE TITLE
couldn't find CUPTI when installing the CUDA support with the NVIDIA HPC SDK

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#7873]
I followed the installation guide and chose the NVIDIA HPC SDK 22.11.

During the configure phase, the report error is shown below. Could you reproduce the cmake error ?  Thanks. 

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/path/tosycl/plugins/cuda/CUDA_CUPTI_INCLUDE_DIR
   used as include directory in directory /path/to/sycl/plugins/cuda
CUDA_cupti_LIBRARY (ADVANCED)
    linked by target "pi_cuda" in directory /path/to/sycl/plugins/cuda

```

**Comment by abagusetty** [comment]
@zjin-lcf Could you post your configure line. I usually pass this option: `-cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/cuda/11.4"` as well in addition to CUDA_LIB_PATH

**Comment by zjin-lcf** [comment]
I didn't specify the version (e.g. 11.4),  causing the error. Thanks.

**Comment by unterumarmung** [comment]
Thanks for the issue, made the same mistake 😆
