### ISSUE TITLE
[SYCL] ICE'd CPU JIT with combination of vector math functions

### ISSUE THREAD

**Issue by agozillon** [intel/llvm#788]
```
q.submit([&](handler &cgh) {
  auto wb = ob.get_access<access::mode::write>(cgh);
   cgh.single_task<codegen_or_jit_bug>([=]() {
       wb[0] = cl::sycl::fmax(
                  cl::sycl::dot(
                    cl::sycl::normalize(float3{0,0,0}), 
                                        float3{0,0,0}), 0.f);
    });
});
```

I found this CPU JIT ICE while I was trying to isolate another JIT problem I've got with a larger kernel (kills the compilers VPlan pass so also related to vectorization it seems), this one gives me a nice error log though:

```
**Internal compiler error** Cannot select: 0x36a2858: v4f32 = extract_subvector 0x3698b68, Constant:i64<0>
  0x3698b68: f32 = extract_vector_elt 0x36a2580, Constant:i64<0>
    0x36a2580: v4f32 = X86ISD::MOVSHDUP 0x36a2ac8
      0x36a2ac8: v4f32 = X86ISD::VFPROUND 0x3698828
        0x3698828: v4f64 = X86ISD::VBROADCAST 0x3698ea8
          0x3698ea8: f64 = fdiv ConstantFP:f64<0.000000e+00>, 0x36a27f0
            0x3698e40: f64 = ConstantFP<0.000000e+00>
            0x36a27f0: f64,ch = CopyFromReg 0x3580fe8, Register:f64 %5
              0x3510148: f64 = Register %5
    0x3510218: i64 = Constant<0>
  0x3510218: i64 = Constant<0>
In function: _ZGVdN8uuuu_TS18codegen_or_jit_bug
Please report the issue on Intel OpenCL forum 
https://software.intel.com/en-us/forums/opencl for assistance. 
 Stack dump:
0.	Running pass 'Function Pass Manager' on module 'main'.
1.	Running pass 'X86 DAG->DAG Instruction Selection' on function ''
Aborted (core dumped)
```

I'm currently using the OpenCL CPU runtime mentioned in the Getting Started guide, so perhaps it's a little out of date. It's also feasible that my environment is somewhat misconfigured and this isn't a bug as I had to uninstall an older OpenCL CPU installation (however, I can run all the existing test suite minus two SYCL tests relating to vector integer builtins (perhaps related) and restrict).

Other than that I'm using **Ubuntu 19.10** and the CPU Model I'm using at the moment is: **Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz**

**Comment by AlexeySachkov** [comment]
Hi @agozillon, thanks for the report

I'm able to reproduce the issue with [`oclcpuexp-2019.8.8.0.0822_rel`](https://github.com/intel/llvm/releases/download/2019-09/oclcpuexp-2019.8.8.0.0822_rel.tar.gz). However, it seems to be fixed in the newer build.

So, stay tuned for the upcoming releases: the issue should disappear when you install updated version of Intel(R) CPU Runtime for OpenCL(TM) Applications with SYCL support.

Feel free to leave this issue open until you finally get the fix.

**Comment by agozillon** [comment]
@AlexeySachkov Thanks for the quick update! Looking forward to the upcoming release then.

**Comment by AlexeySachkov** [comment]
Hi @agozillon, 

Here you go: we have released an updated version of Intel(R) CPU Runtime for OpenCL(TM) Applications with SYCL support: [`oclcpuexp-2019.9.11.0.1106_rel`](https://github.com/intel/llvm/releases/download/2019-10/oclcpuexp-2019.9.11.0.1106_rel.tar.gz)

I've just checked - reproducer works fine using it, I got `0 0 0` as a result.

**Comment by agozillon** [comment]
Thanks very much @AlexeySachkov I'll try that today and close this issue when it solves it! Out of interest is the OpenCL CPU runtime open source like the OpenCL GPU Compute runtime?

**Comment by bader** [comment]
> Out of interest is the Intel OpenCL CPU runtime open source like the Intel OpenCL GPU Compute runtime?

No.

**Comment by agozillon** [comment]
Thanks for the quick answer @bader

**Comment by agozillon** [comment]
I've checked and it does indeed fix the problem in this issue, thank you! 

I'll now close this as it's solved.
