### ISSUE TITLE
[SYCL][HIP]  undefined symbol (__devicelib_ConvertFToBF16INTEL, __clc_fabs, __clc_fmin, __clc_fmax)

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#7962]
I tried to remove the `defined(__NVPTX__)` in sycl/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp. Running the bf16 test program in the LLVM test suite shows the following errors.

lld: error: undefined hidden symbol: __devicelib_ConvertFToBF16INTEL
lld: error: undefined hidden symbol: __clc_fabs(unsigned short)
lld: error: undefined hidden symbol: __clc_fmin(unsigned short, unsigned short)
lld: error: undefined hidden symbol: __clc_fmax(unsigned short, unsigned short)
lld: error: undefined hidden symbol: __clc_fma(unsigned short, unsigned short, unsigned short)

**Comment by abagusetty** [comment]
@zjin-lcf Can you point to a case from your test suite that can reproduce this error.

**Comment by zjin-lcf** [comment]
Please see https://github.com/intel/llvm-test-suite/blob/intel/SYCL/BFloat16/bfloat16_builtins.cpp
Thanks

**Comment by JackAKirk** [comment]
Fixed by https://github.com/intel/llvm/pull/10009
