### ISSUE TITLE
[SYCL][HIP] ONEAPI_DEVICE_SELECTOR != SYCL_DEVICE_FILTER ?

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#7967]
```
  auto const& gpu_devices = sycl::device::get_devices(sycl::info::device_type::gpu);
  std::cout << "Number of Root GPUs: " << gpu_devices.size() << std::endl;
```

ONEAPI_DEVICE_SELECTOR=hip ./main 1
Number of Root GPUs: 4
(root-dev) GPU-ID: gfx90x:sramecc+:xnack-
(root-dev) GPU-ID: gfx90x:sramecc+:xnack-
(root-dev) GPU-ID: AMD Instinct MI
(root-dev) GPU-ID: AMD Instinct MI

---------------------------------------------------------------------

SYCL_DEVICE_FILTER=hip ./main  1

WARNING: The enviroment variable SYCL_DEVICE_FILTER is deprecated. Please use ONEAPI_DEVICE_SELECTOR instead.
For more details, please refer to:
https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector

Number of Root GPUs: 2
(root-dev) GPU-ID: AMD Instinct MI
(root-dev) GPU-ID: AMD Instinct MI

**Comment by al42and** [comment]
With 8096a6fb7f5aace1f2998c884079939fc6722327, I'm observing a different behavior with a more explicit error:


```console
$ ONEAPI_DEVICE_SELECTOR=hip ./main 
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Incomplete selector!  Try 'hip:*' if all devices under the backend was original intention.
Aborted (core dumped)

$ ONEAPI_DEVICE_SELECTOR=hip:gpu ./main 
Number of Root GPUs: 1
$ ONEAPI_DEVICE_SELECTOR=hip:* ./main 
Number of Root GPUs: 1
$ SYCL_DEVICE_FILTER=hip ./main

WARNING: The enviroment variable SYCL_DEVICE_FILTER is deprecated. Please use ONEAPI_DEVICE_SELECTOR instead.
For more details, please refer to:
https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector

Number of Root GPUs: 1
```

The documentation at the link mentions it, but it is a bit hard to notice among the rest of the text:

> Additionally, the backend MUST be followed by colon ( : ) and at least one device specifier of some sort, else an error is thrown.

**Comment by zjin-lcf** [comment]
Thank you for your answer
