### ISSUE TITLE
Failed to vc-instrinsics checkout tag: 'abce9184b7a3a7fe1b02289b9285610d9dc45465'

### ISSUE THREAD

**Issue by wangzy0327** [intel/llvm#7999]
**Describe the bug**
Failed to vc-instrinsics checkout tag: 'abce9184b7a3a7fe1b02289b9285610d9dc45465'

**To Reproduce**
sycl-2022-09 execute configure.py

**Environment (please complete the following information):**

- OS: Ubuntu20.04
- Target device and vendor: MI100 GPU
- DPC++ version: clang++ 16
- Dependencies version: rocm 5.2

**Additional context**

**Comment by AlexeySachkov** [comment]
I believe that we actually have a bug in that hash in revision tagged as `2022-09`.

If you go to [intel/vc-intrinsics](https://github.com/intel/vc-intrinsics) repo and try to [search for `abce9184b7a3a7fe1b02289b9285610d9dc45465` commit](https://github.com/search?q=repo%3Aintel%2Fvc-intrinsics+abce9184b7a3a7fe1b02289b9285610d9dc45465&type=code), you won't find anything. 

If you try to open any commit and replace the hash in URL, then you will see it: [link](https://github.com/intel/vc-intrinsics/commit/abce9184b7a3a7fe1b02289b9285610d9dc45465), but GitHub UI shows a warning that "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.". 

The actual hash we should be looking for is [`dd660eef8b11ead7ffd2373bdbf8734200a3a88a`](https://github.com/intel/vc-intrinsics/commit/dd660eef8b11ead7ffd2373bdbf8734200a3a88a) and you can find it in [commits history](https://github.com/intel/vc-intrinsics/commits/master) of `vc-intrinsics` repo.

@wangzy0327, we can't do anything about this, unfortunately, but you can adjust the hash locally to `dd660eef8b11ead7ffd2373bdbf8734200a3a88a` to fix the error. It needs to be changed in the following location:
https://github.com/intel/llvm/blob/0f579bae55c48d810e1ed76db29229c854e61d5e/llvm/lib/SYCLLowerIR/CMakeLists.txt#L15-L19

I will close the issue as "wontfix",  but please let us know if there are other issues or questions
