### ISSUE TITLE
[SYCL] building fails on Fedora/gcc

### ISSUE THREAD

**Issue by airlied** [intel/llvm#8]
In file included from /home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl.hpp:46,
                 from /home/airlied/devel/compute/intel/llvm/sycl/tools/sycl-check.cpp:10:
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp: In member function ‘void cl::sycl::simple_scheduler::Node::addAccRequirement(cl::sycl::accessor<dataT, dimensions, accessMode, accessTarget, isPlaceholder>&&, int)’:
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp:66:48: error: expected ‘,’ or ‘;’ before ‘::’ token
                                  isPlaceholder>::__impl()
                                                ^~
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp: In member function ‘void cl::sycl::simple_scheduler::Node::addExplicitMemOp(cl::sycl::accessor<dataT, dimensions, accessMode, accessTarget, isPlaceholder>&, T)’:
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp:133:62: error: expected ‘,’ or ‘;’ before ‘::’ token
                                                isPlaceholder>::__impl();
                                                              ^~
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp: In member function ‘void cl::sycl::simple_scheduler::Node::addExplicitMemOp(cl::sycl::accessor<T_src, dim_src, mode_src, tgt_src, isPlaceholder_src>, cl::sycl::accessor<T_dest, dim_dest, mode_dest, tgt_dest, isPlaceholder_dest>)’:
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp:158:64: error: expected ‘,’ or ‘;’ before ‘::’ token
                                              isPlaceholder_src>::__impl();
                                                                ^~
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp:163:54: error: expected ‘,’ or ‘;’ before ‘::’ token
                                   isPlaceholder_dest>::__impl();
                                                      ^~
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp: In member function ‘void cl::sycl::simple_scheduler::Scheduler::updateHost(cl::sycl::accessor<dataT, dimensions, accessMode, accessTarget, isPlaceholder>&, cl::sycl::event&)’:
/home/airlied/devel/compute/intel/llvm/sycl/include/CL/sycl/detail/scheduler/scheduler.cpp:196:60: error: expected ‘,’ or ‘;’ before ‘::’ token
                                              isPlaceholder>::__impl();
                                                            ^~
 Converting :: to . seems to fix this particular one. I'll send a PR for it.

**Comment by bader** [comment]
Fixed by #36.
