### ISSUE TITLE
[SYCL] ordered_queue Class Design

### ISSUE THREAD

**Issue by Pennycook** [intel/llvm#801]
The current implementation of `ordered_queue` as a separate class makes it difficult to switch between different queue types (e.g. for debugging purposes).  Passing an out-of-order property to the `queue` constructor would simplify this, and would also allow functions to accept either out-of-order or in-order queues without templates.

There was some discussion of this on https://github.com/intel/llvm/pull/596, but @jbrodman requested that I open a new tracking issue.

**Comment by illuhad** [comment]
I think what could be useful in addition to this is a mechanism that allows e.g. libraries to enforce an execution mode (e.g. ordered/unordered) for a section of code. For example, some library for parallel primitives may want that all kernels submitted for one algorithm should be executed in a low-latency ordered mode, regardless of the user-provided input queue. This is what I'm working towards in hipSYCL.

**Comment by keryell** [comment]
Yes, it could be a property with a mechanism to change the queue property. Come with a proposal! :-)

**Comment by jbrodman** [comment]
Fixed by https://github.com/intel/llvm/pull/1035
