### ISSUE TITLE
0a67e77 causes IPSCCP lit failures

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#8015]
**Describe the bug**
https://github.com/intel/llvm/commit/0a67e771f6d21b1232c40f226c4eee48c3527210 (https://reviews.llvm.org/D139237) causes compile time failure in `IPSCCPPass`.

**To Reproduce**
Test case: [polybench.c](https://github.com/intel/llvm/files/10418940/polybench.c.txt)

```
clang -O1 polybench.c -c
```
Failure:
```
clang-16: /__w/llvm/llvm/src/llvm/include/llvm/Support/Casting.h:578: decltype(auto) llvm::cast(From*) [with To = llvm::CallBase; From = llvm::User]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
 #7 0x00007f9858c5f50e runIPSCCP(llvm::Module&, llvm::DataLayout const&, llvm::AnalysisManager<llvm::Function>*, std::function<llvm::TargetLibraryInfo const& (llvm::Function&)>, std::function<llvm::TargetTransformInfo& (llvm::Function&)>, std::function<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::AnalysisResultsForFn (llvm::Function&)>) SCCP.cpp:0:0
 #8 0x00007f9858c606f4 llvm::IPSCCPPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/localdisk2/waihungt/merge/llvm/build/bin/../lib/libLLVMipo.so.16git+0x2726f4)
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Intel CPU
- DPC++ version: clang version 16.0.0 (https://github.com/intel/llvm.git 0a67e771f6d21b1232c40f226c4eee48c3527210)
- Can be reproduce with current latest `sycl` commit (8759d0728929c4e8aae88fddb06206aad5719d2b)

**Additional context**
The same commit caused 30 polybench lit failures in `sycl-mlir` branch. They all failed the same way. 
https://github.com/intel/llvm/commit/0a67e771f6d21b1232c40f226c4eee48c3527210 is temporarily reverted in `sycl-mlir` branch.

**Comment by AlexeySachkov** [comment]
Should we reported this directly to [llvm/llvm-project](https://github.com/llvm/llvm-project)? Reproducer seem to have nothing to do with SYCL and therefore the issue is likely reproducible with upstream compiler as well

**Comment by whitneywhtsang** [comment]
Resolved by https://github.com/intel/llvm/commit/bf67186bd2a1dcd042219dca408a56ddd06ee16d.
