### ISSUE TITLE
DPC++ build fails on MacOS in post-commit. 

### ISSUE THREAD

**Issue by bader** [intel/llvm#8019]
```
In file included from /Users/runner/work/llvm/llvm/src/sycl-fusion/jit-compiler/lib/KernelFusion.cpp:11:
In file included from /Users/runner/work/llvm/llvm/src/sycl-fusion/common/include/KernelIO.h:14:
/Users/runner/work/llvm/llvm/src/llvm/include/llvm/Support/YAMLTraits.h:1155:36: error: implicit instantiation of undefined template 'llvm::yaml::MissingTrait<unsigned long>'
  char missing_yaml_trait_for_type[sizeof(MissingTrait<T>)];
                                   ^
```
Log - https://github.com/intel/llvm/actions/runs/3933462666/jobs/6727183809

**Comment by bader** [comment]
@AlexeySachkov, @alexbatashev, @sommerlukas, FYI.

**Comment by sommerlukas** [comment]
Sorry for not catching this earlier, I did not have access to a macOS machine and the issue did not occur in my Linux builds. 

A colleague was able to reproduce the build failure on their macOS machine. The changes in https://github.com/intel/llvm/pull/8020 replace the types by types from the [list of supported builtin types](https://www.llvm.org/docs/YamlIO.html#built-in-types) for LLVM YAML. On my colleague's machine, this fixes the build failure.
