### ISSUE TITLE
Cannot build for nvidia suport

### ISSUE THREAD

**Issue by juanchuletas** [intel/llvm#8102]
**Describe the bug**

I have been trying to build and set up the compiler following this instructions for NVIDIA:
https://www.intel.com/content/www/us/en/developer/articles/technical/compiling-sycl-with-different-gpus.html

But I have no success, I got a lot of fatal errors, this is one of many:

```
clang-16: warning: argument unused during compilation: '-fno-bundle-offload-arch' [-Wunused-command-line-argument]
In file included from /home/juan/Documents/DeveloperZone/llvm/libdevice/fallback-cstring.cpp:9:
/home/juan/Documents/DeveloperZone/llvm/libdevice/wrapper.h:16:10: fatal error: 'cstddef' file not found
#include <cstddef>


```

**To Reproduce**
I follow the instructions as the link above:
`
python ./buildbot/configure.py --cuda -t release --cmake-gen "Unix Makefiles"`

and additionally:

`python ./buildbot/compile.py`

because I figure out that: "make deploy-sycl-toolchain" is needed.

The build and compilation were going good until I started to get the errors above.

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: clang version 16.0.0
- gcc and c++ version: 11.3.0
- libstdc++: libstdc++.so.6 and libstdc++.so.5

**Comment by dm-vodopyanov** [comment]
Same as https://github.com/intel/llvm/issues/7844. @juanchuletas, could you please try the suggestions in this issue?

**Comment by juanchuletas** [comment]
> 



> Same as #7844. @juanchuletas, could you please try the suggestions in this issue?

I installed de libstdc++-12-dev and it worked.

**Comment by dm-vodopyanov** [comment]
Thank you @juanchuletas, closing the issue.
