### ISSUE TITLE
[SYCL][L0] ext_oneapi_memcpy2D() fails for malloc_host, malloc_shared

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#8103]
`ext_oneapi_memcpy2D()` fails for the pointer allocations of `malloc_host` and `malloc_shared` while `malloc_device` is fine for PVC.

Tests fails (copy2d.cpp, memcpy2d.cpp): https://github.com/intel/llvm-test-suite/blob/intel/SYCL/USM/memcpy2d.cpp#L425

**Comment by dm-vodopyanov** [comment]
Test was disabled on PVC in https://github.com/intel/llvm-test-suite/pull/1514 until issue is addressed.
FYI, @aelovikov-intel
