### ISSUE TITLE
[SYCL] Weird performance behaviour

### ISSUE THREAD

**Issue by cagnulein** [intel/llvm#813]
Hi, i'm playing around SYCL and i'm facing a really strange performance behaviour on a little script.

Let's start form this little script:

```
#include <CL/sycl.hpp>
#include <iostream>
#include <math.h>
#include <chrono>

#define IMAGE_WIDTH     (20000L)
#define IMAGE_HEIGHT    (40000L)
#define IMAGE_SIZE      (IMAGE_WIDTH*IMAGE_HEIGHT)

unsigned char* old_image;
namespace sycl = cl::sycl;

int main(int argc, char *argv[]) {
    old_image = new unsigned char[IMAGE_SIZE];
    {
        sycl::queue myQueue(sycl::gpu_selector{});
        sycl::buffer<unsigned char, 1> inputBuf(old_image, sycl::range<1>(IMAGE_WIDTH*IMAGE_HEIGHT));
        myQueue.submit([&](sycl::handler& cgh) {
            auto readImage = inputBuf.get_access<sycl::access::mode::read>(cgh);
            cgh.parallel_for<class simple_test>(sycl::range<1>(1821303172), [=](sycl::id<1> idx) {
            });
        });
    }
    return 0;
}
```

This script runs in
sysele@sysele-C08:~/work/sycl/rotate$ time ./rotate.gpu

**real    0m0.978s**
user    0m0.172s
sys     0m0.084s

If i change the iterations of the parallel_for, **decreasing** them, putting 1761303172 instead of 1821303172, the timings change in these:

sysele@sysele-C08:~/work/sycl/rotate$ time ./rotate.gpu

**real    0m4.541s**
user    0m0.190s
sys     0m0.065s

Any explanations? The timings are deterministic.
I'm using a Intel(R) Core(TM) i7-7820EQ CPU @ 3.00GHz with the latest SYCL GIT.
I've tried oclcpuexp-2019.9.11.0.1106_rel.tar.gz and oclcpuexp-2019.8.8.0.0822_rel.tar.gz both and all these assets have the issue.

**Comment by AlexeySachkov** [comment]
Hi @cagnulein, 

> I've tried oclcpuexp-2019.9.11.0.1106_rel.tar.gz and oclcpuexp-2019.8.8.0.0822_rel.tar.gz both and all these assets have the issue.

These are CPU runtimes, while you are explicitly using `gpu_selector` in your application. Could you please specify version of GPU OpenCL runtime instead?

**Comment by cagnulein** [comment]
> These are CPU runtimes, while you are explicitly using `gpu_selector` in your application. Could you please specify version of GPU OpenCL runtime instead?

Hi @AlexeySachkov , thanks for your reply. You're right, i've used https://github.com/intel/compute-runtime/releases/tag/19.43.14583

**Comment by cagnulein** [comment]
@AlexeySachkov any ideas?

**Comment by cagnulein** [comment]
There is definitely something wrong, here other results (you can check the code on my repo https://github.com/cagnulein/sycl-benchmarks/tree/master/issues)

<pre>
./test-around.sh
Index           Time 1st try    Time 2nd try    Time 3rd try

1761303161      1.548           1.561           1.563
<b>1761303162      3.177           3.173           3.194</b>
<b>1761303163      16.447          16.431          16.459</b>
1761303164      1.249           1.235           1.247
1761303165      1.953           1.967           1.955
1761303166      2.052           2.039           2.038
1761303167      2.165           2.172           2.156
1761303168      1.261           1.271           1.290
1761303169      1.392           1.411           1.407
1761303170      1.299           1.305           1.307
<b>1761303171      5.829           5.842           5.838</b>
<b>1761303172      4.509           4.500           4.518</b>
1761303173      1.288           1.291           1.308
1761303174      1.232           1.225           1.242
1761303175      1.813           1.838           1.796
<b>1761303176      2.507           2.528           2.511</b>
1761303177      1.706           1.716           1.699
<b>1761303178      8.490           8.477           8.506</b>
<b>1761303179      16.436          16.447          16.432</b>
1761303180      1.407           1.411           1.429
1761303181      2.465           2.465           2.451
<b>1761303182      8.492           8.502           8.479</b>
1761303183      1.263           1.246           1.239
1761303184      1.847           1.887           1.845
</pre>

**Comment by AlexeySachkov** [comment]
Hi @cagnulein,

Sorry, I haven't had enough time to take a look

> how can i check the kernel code?

To extract device code during compilation, please take a look at [corresponding docs](https://github.com/intel/llvm/blob/sycl/sycl/doc/SYCLCompilerUserManual.md#sycl-device-code-compilation).

You can also use `SYCL_DUMP_IMAGES=1` env variable to extract SPIR-V file which is passed to JIT compiler during execution.

I suggest you to do the following:
1. try to understand whenever this weird performance is introduced by SYCL RT or not
2. if not, proceed with issue in [intel/compute-runtime](https://github.com/intel/compute-runtime)
3. if yes, bug is in our runtime and someone will look into it

In order to check (1) you could use [intel/opencl-intercept-layer](https://github.com/intel/opencl-intercept-layer). In particular, try different [performance timing controls](https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md#performance-timing-controls) to see which exact OpenCL API call is taking so long.

I guess if time spent in OpenCL APIs stays the same for different values of `Index` in the table, then the problem is in SYCL RT.

**Comment by cagnulein** [comment]
Thanks @AlexeySachkov , with the opencl-intercept-layer i saw that the time consumes on **clWaitForEvents: event_list** (the duration of this function changes proportionally with the table that i sent before with different indexes), so i assume that it's a SYCL RT issue isn't it?
If so, stupid question: where is the SYCL RT's repo? :)

<pre>
>>>> clCreateKernel: program = 0xf81df0, kernel_name = _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE11simple_test
<<<< clCreateKernel: returned 0x16e59c0 -> CL_SUCCESS
>>>> clSetKernelExecInfo( _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE11simple_test ): param_name = CL_KERNEL_EXEC_INFO_INDIRECT_HOST_ACCESS_INTEL (00004200)
<<<< clSetKernelExecInfo -> CL_SUCCESS
>>>> clSetKernelExecInfo( _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE11simple_test ): param_name = CL_KERNEL_EXEC_INFO_INDIRECT_DEVICE_ACCESS_INTEL (00004201)
<<<< clSetKernelExecInfo -> CL_SUCCESS
>>>> clSetKernelExecInfo( _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE11simple_test ): param_name = CL_KERNEL_EXEC_INFO_INDIRECT_SHARED_ACCESS_INTEL (00004202)
<<<< clSetKernelExecInfo -> CL_SUCCESS
>>>> clEnqueueNDRangeKernel( _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE11simple_test ): queue = 0xf3ce60, kernel = 0x16e59c0, global_work_offset = < 0 >, global_work_size = < 1761303171 >, local_work_size = < NULL >
<<<< clEnqueueNDRangeKernel created event = 0x16e0b60 -> CL_SUCCESS
<b>>>>> clWaitForEvents: event_list = ( size = 1 )[ 0x16e0b60 ]</b>
<<<< clWaitForEvents -> CL_SUCCESS
>>>> clReleaseMemObject: [ ref count = 1 ] mem = 0x16e0d10
<<<< clReleaseMemObject: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseCommandQueue: [ ref count = 1 ] command_queue = 0xf3ce60
<<<< clReleaseCommandQueue: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseEvent: [ ref count = 1 ] event = 0x16e0b60
<<<< clReleaseEvent: [ ref count = 0 ] -> CL_SUCCESS
</pre>

**Comment by romanovvlad** [comment]
@cagnulein 
Hi, 

>  i saw that the time consumes on clWaitForEvents: event_list (the duration of this function changes proportionally with the table that i sent before with different indexes), so i assume that it's a SYCL RT issue isn't it?
No, 95% that the problem in OCL GPU because clWaitForEvents function is implemented there, SYCL RT just calls it.

> where is the SYCL RT's repo? 
SYCL RT sources are locates in https://github.com/intel/llvm, sycl branch, sycl directory.

**Comment by cagnulein** [comment]
Hi @romanovvlad , thanks for your reply. So, on you opinion, which is best way to analyze this issue?

**Comment by AlexeySachkov** [comment]
@cagnulein, 

> with the opencl-intercept-layer i saw that the time consumes on clWaitForEvents: event_list (the duration of this function changes proportionally with the table that i sent before with different indexes)

If that is the case, I would recommend to transfer this issue into [intel/compute-runtime](https://github.com/intel/compute-runtime) GitHub repo: please attach logs from opencl-intercept-layer there. Also, it would be perfect if you will be able to provide pure OpenCL reproducer there.

**Comment by cagnulein** [comment]
Hi @AlexeySachkov , thanks for your time. For the loop issue i think @MichalMrozek was clear: i've to try with OpenCL 2.0 (i'm facing a clang issue and i can't try right now) but i think [the path is clear](https://github.com/intel/compute-runtime/issues/235).

In the meanwhile i saw another potential issue. This time we talk about memory buffer.

Let's talk about this [simple cpp](https://github.com/cagnulein/sycl-benchmarks/blob/master/issues/buffer/rotate.cpp): it just a empy for loop (this time of 1 iteration) with a creation of 2 buffers, one in read only mode and one in readwrite.

This is the report as i done for the issue before (i did the same example with SYCL and pure OpenCL):
<pre>

<i>SYCL FROM HERE</i>

sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate.gpu 22067 40992

<b>real    0m3.291s</b>
user    0m0.320s
sys     0m0.115s
sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate.gpu 20000 40000

<b>real    0m1.058s</b>
user    0m0.314s
sys     0m0.112s
sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate.gpu 40000 80000

<b>real    0m2.489s</b>
user    0m0.518s
sys     0m0.207s
sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate.gpu 20000 80000

real    0m1.524s
user    0m0.372s
sys     0m0.158s

<i>PURE OPENCL FROM HERE</i>

sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate-opencl.gpu 22067 40992

real    0m0.974s
user    0m0.514s
sys     0m0.191s
sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate-opencl.gpu 20000 40000

real    0m0.947s
user    0m0.486s
sys     0m0.207s
sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate-opencl.gpu 40000 80000

real    0m2.115s
user    0m0.861s
sys     0m0.613s
sysele@sysele-C08:~/work/sycl/issues/buffer$ time ./rotate-opencl.gpu 20000 80000

real    0m1.312s
user    0m0.647s
sys     0m0.287s
</pre>

As you can see, it seems that with particular buffer dimensions, the timings went up for no reasons. With OpenCL everything works fine.

I ran the opencl-intercept-layer and these are the result on the SYCL program:
<pre>
<<<< clSetKernelExecInfo -> CL_SUCCESS
>>>> clSetKernelExecInfo( _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE11simple_test ): param_name = CL_KERNEL_EXEC_INFO_INDIRECT_SHARED_ACCESS_INTEL (00004202)
<<<< clSetKernelExecInfo -> CL_SUCCESS
>>>> clEnqueueNDRangeKernel( _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE11simple_test ): queue = 0x14c8e60, kernel = 0x1c71fd0, global_work_offset = < 0 >, global_work_size = < 1 >, local_work_size = < NULL >
<<<< clEnqueueNDRangeKernel created event = 0x1c6cb60 -> CL_SUCCESS
>>>> clWaitForEvents: event_list = ( size = 1 )[ 0x1c6cb60 ]
<<<< clWaitForEvents -> CL_SUCCESS
>>>> clReleaseMemObject: [ ref count = 1 ] mem = 0x1c6cf00
<<<< clReleaseMemObject: [ ref count = 0 ] -> CL_SUCCESS
>>>> clEnqueueReadBufferRect: queue = 0x14c8e60, buffer = 0x1c6cd10, non-blocking, buffer_origin = < 0, 0, 0 >, host_origin = < 0, 0, 0 >, region = < 22067, 40992, 1 >, ptr = 0x7ffb50517010
<<<< clEnqueueReadBufferRect created event = 0x14b18f0 -> CL_SUCCESS
>>>> clWaitForEvents: event_list = ( size = 1 )[ 0x14b18f0 ]

<b>CODE DELAYS HERE</b>

<<<< clWaitForEvents -> CL_SUCCESS
>>>> clWaitForEvents: event_list = ( size = 1 )[ 0x14b18f0 ]
<<<< clWaitForEvents -> CL_SUCCESS
>>>> clWaitForEvents: event_list = ( size = 1 )[ 0x1c6cb60 ]
<<<< clWaitForEvents -> CL_SUCCESS
>>>> clReleaseMemObject: [ ref count = 1 ] mem = 0x1c6cd10
<<<< clReleaseMemObject: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseEvent: [ ref count = 1 ] event = 0x14b18f0
<<<< clReleaseEvent: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseCommandQueue: [ ref count = 1 ] command_queue = 0x14c8e60
<<<< clReleaseCommandQueue: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseEvent: [ ref count = 1 ] event = 0x1c6cb60
<<<< clReleaseEvent: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseContext: [ ref count = 1 ] context = 0x136b220
<<<< clReleaseContext: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseKernel: [ ref count = 1 ] kernel = 0x1c71fd0
<<<< clReleaseKernel: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseProgram: [ ref count = 1 ] program = 0x19bf600
<<<< clReleaseProgram: [ ref count = 0 ] -> CL_SUCCESS
</pre>

This one is the same path with PURE OpenCL and i have no delay at all
<pre>
>>>> clGetPlatformInfo: platform = [ Intel(R) OpenCL HD Graphics ], param_name = CL_PLATFORM_VERSION (00000901)
<<<< clGetPlatformInfo -> CL_SUCCESS
>>>> clRetainDevice: [ ref count = 1 ] device = 0x55d1b1e4e870
<<<< clRetainDevice: [ ref count = 1 ] -> CL_SUCCESS
>>>> clGetDeviceInfo: device = [ Intel(R) Gen9 HD Graphics NEO (CL_DEVICE_TYPE_GPU) ], param_name = CL_DEVICE_PLATFORM (00001031)
<<<< clGetDeviceInfo -> CL_SUCCESS
>>>> clGetPlatformInfo: platform = [ Intel(R) OpenCL HD Graphics ], param_name = CL_PLATFORM_VERSION (00000901)
<<<< clGetPlatformInfo -> CL_SUCCESS
>>>> clGetPlatformInfo: platform = [ Intel(R) OpenCL HD Graphics ], param_name = CL_PLATFORM_VERSION (00000901)
<<<< clGetPlatformInfo -> CL_SUCCESS
>>>> clRetainDevice: [ ref count = 1 ] device = 0x55d1b1e4e870
<<<< clRetainDevice: [ ref count = 1 ] -> CL_SUCCESS
>>>> clBuildProgram: program = 0x55d1b1f176d0, pfn_notify = (nil)
<<<< clBuildProgram -> CL_SUCCESS
>>>> clReleaseDevice: [ ref count = 1 ] device = 0x55d1b1e4e870
<<<< clReleaseDevice: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseDevice: [ ref count = 1 ] device = 0x55d1b1e4e870
<<<< clReleaseDevice: [ ref count = 0 ] -> CL_SUCCESS
>>>> clCreateBuffer: context = 0x55d1b1f18910, flags = CL_MEM_READ_ONLY (4), size = 800000000, host_ptr = (nil)
<<<< clCreateBuffer: returned 0x55d1b2671db0 -> CL_SUCCESS
>>>> clCreateBuffer: context = 0x55d1b1f18910, flags = CL_MEM_READ_WRITE (1), size = 904570464, host_ptr = (nil)
<<<< clCreateBuffer: returned 0x55d1b25e9850 -> CL_SUCCESS
>>>> clCreateCommandQueue: context = 0x55d1b1f18910, device = [ Intel(R) Gen9 HD Graphics NEO (CL_DEVICE_TYPE_GPU) ], properties =  (0)
<<<< clCreateCommandQueue: returned 0x55d1b292b7e0 -> CL_SUCCESS
>>>> clEnqueueWriteBuffer: queue = 0x55d1b292b7e0, buffer = 0x55d1b25e9850, blocking, offset = 0, cb = 904570464, ptr = 0x7f46f726d010
<<<< clEnqueueWriteBuffer -> CL_SUCCESS
>>>> clCreateKernel: program = 0x55d1b1f176d0, kernel_name = simple_add
<<<< clCreateKernel: returned 0x55d1b2677490 -> CL_SUCCESS
>>>> clSetKernelArg( simple_add ): kernel = 0x55d1b2677490, index = 0, size = 8, value = 0x55d1b2671db0
<<<< clSetKernelArg -> CL_SUCCESS
>>>> clSetKernelArg( simple_add ): kernel = 0x55d1b2677490, index = 1, size = 8, value = 0x55d1b25e9850
<<<< clSetKernelArg -> CL_SUCCESS
>>>> clEnqueueNDRangeKernel( simple_add ): queue = 0x55d1b292b7e0, kernel = 0x55d1b2677490, global_work_size = < 1 >, local_work_size = < NULL >
<<<< clEnqueueNDRangeKernel -> CL_INVALID_KERNEL_ARGS
<b>>>>> clEnqueueReadBuffer: queue = 0x55d1b292b7e0, buffer = 0x55d1b25e9850, blocking, offset = 0, cb = 904570464, ptr = 0x7f46f726d010
<<<< clEnqueueReadBuffer -> CL_SUCCESS</b>
>>>> clReleaseKernel: [ ref count = 1 ] kernel = 0x55d1b2677490
<<<< clReleaseKernel: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseCommandQueue: [ ref count = 1 ] command_queue = 0x55d1b292b7e0
<<<< clReleaseCommandQueue: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseMemObject: [ ref count = 1 ] mem = 0x55d1b25e9850
<<<< clReleaseMemObject: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseMemObject: [ ref count = 1 ] mem = 0x55d1b2671db0
<<<< clReleaseMemObject: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseProgram: [ ref count = 1 ] program = 0x55d1b1f176d0
<<<< clReleaseProgram: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseContext: [ ref count = 1 ] context = 0x55d1b1f18910
<<<< clReleaseContext: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseDevice: [ ref count = 1 ] device = 0x55d1b1e4e870
<<<< clReleaseDevice: [ ref count = 0 ] -> CL_SUCCESS
>>>> clReleaseDevice: [ ref count = 1 ] device = 0x55d1b1e4e870
<<<< clReleaseDevice: [ ref count = 0 ] -> CL_SUCCESS
</pre>

So what do you think?
