### ISSUE TITLE
[SYCL-MLIR]: matrix-matrix multiplication performance (scalar replacement of global variable)

### ISSUE THREAD

**Issue by etiotto** [intel/llvm#8163]
Consider a naive matrix-matrix multiplication in SYCL:

```
static void mm_kernel(queue &q, const std::array<float, N * N> &matrix_a,
                      const std::array<float, N * N> &matrix_b,
                      std::array<float, N * N> &matrix_c) {​​​​​​​​
  std::cout << "Kernel:                mm_kernel\n";
  std::cout << "Configuration:         MATRIX_SIZE = " << N << "x" << N
            << " | WORK_GROUP_SIZE = " << M << "x" << M << "\n";

  buffer a(matrix_a), b(matrix_b), c(matrix_c);

  auto e = q.submit([&](handler &h) {​​​​​​​​
    auto A = a.get_access<access::mode::read>(h);
    auto B = b.get_access<access::mode::read>(h);
    auto C = c.get_access<access::mode::read_write>(h);

    range<2> global_size(N, N), wg_size(M, M);

    h.parallel_for<class kernel_parallel_for>(
        nd_range<2>(global_size, wg_size), [=](nd_item<2> item) {​​​​​​​​​​​​​​​​​​​​​​
          int i = item.get_global_id(0), j = item.get_global_id(1);
          for (int k = 0; k < N; k++) {​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
            C[i * N + j] += A[i * N + k] * B[k * N + j];
          }​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
        }​​​​​​​​​​​​​​​​​​​​​​​​​​​​​);
  }​​​​​​​​​​​​​​​​​​​​​​​​​​​​​);

  auto kernel_duration =
      (e.get_profiling_info<info::event_profiling::command_end>() -
       e.get_profiling_info<info::event_profiling::command_start>());
  std::cout << "Kernel Execution Time: " << kernel_duration / 1e+9 << "secs\n";
}​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
```

The SYCL kernel code is:
```
  h.parallel_for<class kernel_parallel_for>(
        nd_range<2>(global_size, wg_size), [=](nd_item<2> item) {​​​​​​​​​​​​​​​​​​​​​​​​​​
          int i = item.get_global_id(0), j = item.get_global_id(1);
          for (int k = 0; k < N; k++) {​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
            C[i * N + j] += A[i * N + k] * B[k * N + j];
          }​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
    }​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​);
 ```
 
Note that for every k-loop iteration one element of the matrix 'C' is read and then updated with a new results. This is inefficient because every matrix element access is a global memory access (on a GPU). Even in the presence of a cache the memory access is still less efficient than if the code were to use a local temp. variable (a register) to accumulate the partial result. 
 
The code can be transformed to: 
```
  h.parallel_for<class kernel_parallel_for_private>(
        nd_range<2>(global_size, wg_size), [=](nd_item<2> item) {​​​​​​​​​​​​​​​​​​​​​​​​​​​​
          int i = item.get_global_id(0), j = item.get_global_id(1);
          float temp = C[i * N + j];
          for (int k = 0; k < N; k++)
            temp += A[i * N + k] * B[k * N + j];
          C[i * N + j] = temp;
       }​​​​​​​​​​​​​​​​​​​​​​​​​​​​);
```
The transformed code no longer performs unnecessary load/store from matrix 'C' in the k-loop, and instead uses a local variable (temp).
 
We need to measure this performance opportunity on a GPU machine, specifically:
  - measure the effect of the manual transformation using `clang`
  - measure O0, and O3
  - measure a few matrix sizes (e.g. N = 1024, 2048, 4096) and work group sizes (M = 16, 32)

**Comment by whitneywhtsang** [comment]
Performance measurements:
[ScalarReplacement.xlsx](https://github.com/intel/llvm/files/10548927/ScalarReplacement.xlsx)

**Comment by etiotto** [comment]
**Performance measurements using Intel(R) Iris(R) Xe Graphic**

![image](https://user-images.githubusercontent.com/56368199/216172606-95c5e5a1-99a7-4e24-b8f2-11a9a3d2e9be.png)

**Comment by etiotto** [comment]
We have implemented the performance optimizations required to replace reductions with scalars (LICM and affine reduction recognition). On a GEN 12 GPU we can now match the performance of the manual transformation. So this work item is complete.

**Comment by whitneywhtsang** [comment]
Performance measurement with https://github.com/intel/llvm/commit/dd396e7abbf1f00f81b8011fe0d47961cc9f32e6 using Intel(R) Iris(R) Xe Graphic:
![Screenshot (7)](https://user-images.githubusercontent.com/54643204/223805297-eb7f800f-c1ef-47cb-84fb-36a545d22ddf.png)
