### ISSUE TITLE
sycl/bit_cast.hpp is not self-contained

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#8179]
**Describe the bug**

It is not possible to directly include `sycl/bit_cast.hpp`. I understand that this is illegal from the SYCL spec point of view, but it could be useful in our internal unit tests to speed up their compilation.

**To Reproduce**

Add a new SYCL unit-test or modify existing one: include `sycl/bit_cast.hpp` directly without including `sycl/sycl.hpp` and try to use `sycl::bit_cast` in a test.

**Additional context**

I was able to detect the following problems with the header:
- it uses `__has_builtin` without checking that it is available. Can be mitigated by including `detail/defines_elementary.hpp`
- it uses `detail::memcpy`, which is not included and therefore will cause linking error.
- if you try to include `detail/helpers.hpp` to mitigate item above, you will face issues with missing includes/forward declarations for `local_ptr`, `global_ptr` and maybe other classes
- if you try to include `pointers.hpp` into `detail/helpers.hpp` you will face cyclic dependency on `access` enum

**Comment by pwisniewskimobica** [comment]
@AlexeySachkov I realized that in test including` detail/defines_elementary.hpp`
before `sycl/bit_cast.hpp` can resolve problem
Its not enough isnt int?

**Comment by AlexeySachkov** [comment]
@pwisniewskimobica, I believe that there were some changes around some of those headers and circular dependency described in the tracker may be fixed already.

> I realized that in test including `detail/defines_elementary.hpp` before `sycl/bit_cast.hpp` can resolve problem

This is probably enough for the test, but the idea of this tracker is to make `sycl/bit_cast.hpp` work even if it is the only include

**Comment by aelovikov-intel** [comment]
```
$ clang++  -fsycl -include 'sycl/bit_cast.hpp' -x c++ /dev/null -c -o /dev/null && echo Success
Success
```
