### ISSUE TITLE
[SYCL] Poor Performance - Very Low bandwidth of SYCL kernel for Softmax

### ISSUE THREAD

**Issue by AvijitBag** [intel/llvm#8183]
**Describe the bug**
This reproducer is created for enhancing the performance, to achieve higher bandwidth for the SYCL implementation of
Softmax primitive on Nvidia.
This reproducer computes the Softmax algorithm with scale for forward and then the memory bandwidth is calculated. Similarly, for backward propagation Softmax algorithm is computed and memory bandwidth is calculated.

**Reproduce**

For the reproducer code, refer the attachments setup.sh, softmax.cpp and softmax_kernels.hpp 

1. Go to the directory having the reproducer files and run the below script to setup the environment.
 source setup.sh

2. To compile, run.
clang++ -O3 -fsycl -fsycl-targets=nvptx64-nvidia-cuda  softmax.cpp

3. The above generates the output file. To see the output bandwidth, run
./a.out

**Observed behaviour**

For, OuterSize = 10000, Channels = 4 and InnerSize = 10000
Propagation : Forward
Alg : softmax
src_scale : 64.00
dst_scale : 2.00

**Result,
Total time = 0.443462 sec 
Total bandwidth = 7.215951 Gb/s**
______________________________________________________

For, OuterSize = 10000, Channels = 4 and InnerSize = 10000
Propagation : Backward
Alg : softmax

**Result,
Total time = 0.568091 sec 
Total bandwidth = 8.449351 Gb/s**
______________________________________________________

**Expected behavior**
The ideal behavior is to attain the maximum bandwidth (i.e., CLPeak value for Float16 = 251.94 GBPS) for any input size.
For the current reproducer higher bandwidth is expected i.e., a minimum of 100 GBPS is expected.

**Environment** 

-OS: Ubuntu 22.04.1 LTS
-Target device and vendor: Nvidia, Tesla T4
-DPC++ version: clang version 15.0.0 (https://github.com/intel/llvm.git https://github.com/intel/llvm/commit/0c7a1e18978754451f5c2c95129721297e2c2411)
-Dependencies version: Driver Version: 495.29.05 CUDA Version: 11.5

**Additional context**
1.  Currently Outer size , inner size and channels are hard coded, can be changed as per need.
2.  When channels values is less like 1 or 2 , then performance is found much better.
3. Attached the source code of the reproducer below
[Softmax_reproducer.zip](https://github.com/intel/llvm/files/10568939/Softmax_reproducer.zip)

**Comment by zjin-lcf** [comment]
What about the performance of the CUDA implementation of Softmax primitive on the GPU ?

**Comment by AvijitBag** [comment]
The performance of cuda is almost same as sycl.


For, OuterSize = 10000, Channels = 4 and InnerSize = 10000
Propagation : Forward

Total time = 0.420635 sec 
Total bandwidth = 7.607545 Gb/s  
______________________________________________________


For, OuterSize = 10000, Channels = 4 and InnerSize = 10000
Propagation : Backward

Total time = 0.636642 sec 
Total bandwidth = 7.539559 Gb/s 
___________________________________________________________

For compile,
nvcc -O3 softmax.cu

We are attaching the source code below:
 
[cuda.zip](https://github.com/intel/llvm/files/10577299/cuda.zip)

**Comment by JackAKirk** [comment]
Since the performance of SYCL cuda backend matches cuda, we are closing this issue.
