### ISSUE TITLE
group_ballot predicate argument should be defaulted

### ISSUE THREAD

**Issue by Pennycook** [intel/llvm#8201]
**Describe the bug**
[sycl_ext_sub_group_mask](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_sub_group_mask.asciidoc#ballot) defines ballot with `predicate=true`, but the implementation does not default the argument:

`group_ballot` 
https://github.com/intel/llvm/blob/b13561c98d3edac22e79fb7fe49110379da48369/sycl/include/sycl/ext/oneapi/sub_group_mask.hpp#L270

**To Reproduce**
```c++
#include <sycl/sycl.hpp>

int main() {
  sycl::queue Q;
  Q.parallel_for(sycl::nd_range<1>{32, 32}, [=](sycl::nd_item<1> item) {
    auto Mask = sycl::ext::oneapi::group_ballot(item.get_sub_group());
  });
}
```

**Environment (please complete the following information):**

- OS: Linux, Windows
- Target device and vendor: Any
- DPC++ version: b13561c98d3edac22e79fb7fe49110379da48369
- Dependencies version: N/A

**Additional context**
None.

**Comment by haroon26** [comment]
Hello @Pennycook! I am interested in compilers and looking to start contributing in them. Can you please assign this issue to me?
