### ISSUE TITLE
[SYCL-MLIR] SYCL-Bench investigation

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#8204]
This issue is to fix the failures on SYCL-Bench using SYCL-MLIR compiler, and measure performance.

Repository: https://github.com/bcosenza/sycl-bench

To build the benchmarks:
```
mkdir build; cd build
cmake -DSYCL_IMPL=LLVM -DCMAKE_CXX_COMPILER=/iusers/waihungt/llvm/build/bin/clang++ ..
cmake --build .
```

Changes made to `CMakeLists.txt` to use SYCL-MLIR compiler:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -42,7 +42,7 @@ if(SYCL_IMPL STREQUAL "ComputeCpp")
 elseif(SYCL_IMPL STREQUAL "hipSYCL")
   find_package(hipSYCL CONFIG REQUIRED)
 elseif(SYCL_IMPL STREQUAL "LLVM")
-  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl")
+  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=spir64-unknown-unknown-syclmlir -w")
```

Below are the benchmarks that have compile failures with SYCL-MLIR compiler:
```
-  single-kernel/median.cpp
-  single-kernel/scalar_prod.cpp
-  single-kernel/sobel.cpp
-  single-kernel/sobel5.cpp
-  single-kernel/sobel7.cpp
-  single-kernel/mol_dyn.cpp
-  single-kernel/nbody.cpp
-  pattern/segmentedreduction.cpp
-  pattern/reduction.cpp
-  runtime/dag_task_throughput_sequential.cpp
-  runtime/dag_task_throughput_independent.cpp
-  runtime/blocked_transform.cpp
-  runtime/matmulchain.cpp
```

To run the successful benchmarks:
```
for benchmark in 2DConvolution 2mm 3mm atax bicg covariance gemm gesummv gramschmidt matmulchain mvt syr2k syrk; do
  echo "Running $benchmark"
  ./$benchmark --device=gpu --output=output.csv
done
```

Below are the benchemarks that have runtime failures with either SYCL-MLIR or both DPC++ and SYCL-MLIR compiler:
```
#CLANG FAIL/UNSUPPORTED: 3DConvolution correlation DRAM fdtd2d host_device_bandwidth
#In addition:
#CGEIST FAIL TO RUN: arith kmeans lin_reg_coeff lin_reg_error local_mem pattern_L2 sf vec_add
```

**Comment by whitneywhtsang** [comment]
Performance measurements: 
![t](https://user-images.githubusercontent.com/54643204/216750827-967f399a-630e-43ba-9f25-d8c1b9440722.png)

**Comment by whitneywhtsang** [comment]
There are bugs in the Gramshmidt benchmark:
```
--- a/polybench/gramschmidt.cpp
+++ b/polybench/gramschmidt.cpp
@@ -16,8 +16,8 @@ class Gramschmidt2;
 class Gramschmidt3;
 
 void init_array(DATA_TYPE* A, size_t size) {
-       const auto M = 0;
-       const auto N = 0;
+       const auto M = size;
+       const auto N = size;
 
        for(size_t i = 0; i < M; i++) {
                for(size_t j = 0; j < N; j++) {
@@ -27,8 +27,8 @@ void init_array(DATA_TYPE* A, size_t size) {
 }
 
 void gramschmidt(DATA_TYPE* A, DATA_TYPE* R, DATA_TYPE* Q, size_t size) {
-       const auto M = 0;
-       const auto N = 0;
+       const auto M = size;
+       const auto N = size;
```
By fixing the bug, SYCL-MLIR can no longer verify for that benchmark.

**Comment by etiotto** [comment]
@whitneywhtsang in this post https://github.com/intel/llvm/issues/8204#issuecomment-1423590224 you mentioned that the bmks have bugs. Can you pls explain the reason the bmk source code is not correct?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang in this post https://github.com/intel/llvm/issues/8204#issuecomment-1423590224 you mentioned that the bmks have bugs. Can you pls explain the reason the bmk source code is not correct?

For `gramschmidt`, without my suggested change, then `A` is actually not initialized, as the loop nest is never entered. It happens that element of `A` are all zeros. In the kernels, when we do multiplication, reductions, etc on zeros, which will give us zeros. In the cpu code `gramschmidt`, again loop nests are not entered, and element of `A` continue to be zeros. End up we always verify even if in the kernel, we do nothing at all.   

>  How do you know that M and N should be initialized to size ?

I know from the kernels, e.g., `cgh.parallel_for<Gramschmidt3>(range<2>(size, 1), [=, M_ = size, N_ = size](`.

> I do not understand the why the other 2 bmks (Mvt, and Gesummv) have bugs (from your msg). Can you please explain it ?

For `mvt`, in the kernels `x1` and `x2` are calculated as `x1[i] += a[{i, j}] * y1[j];` and `x2[k] += a[{k, l}] * y2[l];`, if elements of `y1` and `y2` are always zeros, then elements of `x1` and `x2` are always zeros too. End up we always verify even if in the kernel, we do nothing at all.   

For `gesummv`, it is not a bug, but making the initial values of array A a bit more complex, SYCL-MLIR would not verify. (only the first element is correctly calculated.)

**Comment by whitneywhtsang** [comment]
With https://github.com/intel/llvm/pull/8290 and the following changes to `SYCLMethodToSYCLCall.cpp`, `gesummv`, `framshmidt`, and `mvt` can all be verified again even after the benchmark changes described in https://github.com/intel/llvm/issues/8204#issuecomment-1423590224.
```
--- a/mlir-sycl/lib/Transforms/SYCLMethodToSYCLCall.cpp
+++ b/mlir-sycl/lib/Transforms/SYCLMethodToSYCLCall.cpp
@@ -69,15 +69,15 @@ static mlir::Value adaptArgumentForSYCLCall(OpBuilder &Rewriter,
 
   auto Alloca = static_cast<Value>(CreateAlloca(Rewriter));
 
-  // Store the element
-  Rewriter.create<memref::StoreOp>(
-      Loc, Original, Alloca,
-      ValueRange{Rewriter.createOrFold<arith::ConstantIndexOp>(Loc, 0)});
-
-  // Cast the memref value to the expected shape
-  Alloca = Rewriter.createOrFold<memref::CastOp>(
-      Loc, MemRefType::get(TargetShape, ThisType), Alloca);
-
+  if (auto Load = Original.getDefiningOp<memref::LoadOp>())
+    Alloca = Load.getOperand(0);
+  else
+    // Store the element
+    Rewriter.create<memref::StoreOp>(
+        Loc, Original, Alloca,
+        ValueRange{Rewriter.createOrFold<arith::ConstantIndexOp>(Loc, 0)});
+
+  auto CurShape = Alloca.getType().cast<MemRefType>().getShape();
   if (Alloca.getType().cast<MemRefType>().getMemorySpaceAsInt() !=
@@ -86,10 +86,14 @@ static mlir::Value adaptArgumentForSYCLCall(OpBuilder &Rewriter,
     Alloca = Rewriter.create<LLVM::AddrSpaceCastOp>(
         Loc, LLVM::LLVMPointerType::get(ThisType, TargetMemSpace), Alloca);
     Alloca = Rewriter.create<polygeist::Pointer2MemrefOp>(
-        Loc, MemRefType::get(TargetShape, ThisType, {}, TargetMemSpace),
-        Alloca);
+        Loc, MemRefType::get(CurShape, ThisType, {}, TargetMemSpace), Alloca);
   }
 
+  // Cast the memref value to the expected shape
+  if (CurShape != TargetShape)
+    Alloca = Rewriter.createOrFold<memref::CastOp>(
+        Loc, MemRefType::get(TargetShape, ThisType), Alloca);
+
   if (Alloca.getType() == MT) {
```
Note that the above changes to `SYCLMethodToSYCLCall.cpp` are error prone. 
In the next meeting, I will explain the bug, and we can discuss a proper fix for it.

![Screenshot (8)](https://user-images.githubusercontent.com/54643204/218240622-fd81424e-f39b-4fd4-a819-43292fc0e7d9.png)
SYCL-MLIR and DPC++ compilers perform the same for `gesummv` and `mvt`.

**Comment by whitneywhtsang** [comment]
With the changes described in https://github.com/intel/llvm/issues/8204#issuecomment-1426614138, there are more benchmarks that can be verified. 
Performance measurements on Intel(R) Iris(R) Xe Graphics:
![Screenshot (11)](https://user-images.githubusercontent.com/54643204/218274640-995682d3-7aff-40b0-8253-f9b54faf9f4f.png)
The `atax` and `covariance` performance differences are within stddev.
The 1% improvement of `3mm` and 1% degradation of `gramschmidt` are reproducible.  
`SYCL-MLIR` and `DPC++` are pretty much on par for the above benchmarks.

**Comment by whitneywhtsang** [comment]
With the changes described in https://github.com/intel/llvm/issues/8204#issuecomment-1426614138, there are 3 extra test suite tests pass.
```
  SYCL :: Basic/buffer/subbuffer.cpp
  SYCL :: Basic/host-task-dependency.cpp
  SYCL :: KernelFusion/ranged_offset_accessor.cpp
```
With https://github.com/intel/llvm/pull/8290 as well, there are 9 extra test suite tests pass, 12 in total.
```
  SYCL :: Basic/access_to_subset.cpp
  SYCL :: Basic/buffer/buffer_full_copy.cpp
  SYCL :: Basic/buffer/reinterpret.cpp
  SYCL :: Basic/buffer/subbuffer.cpp
  SYCL :: Basic/host-task-dependency.cpp
  SYCL :: Basic/linear-sub_group.cpp
  SYCL :: Basic/offset-accessor-get_pointer.cpp
  SYCL :: HostInteropTask/host-task-two-queues.cpp
  SYCL :: KernelFusion/ranged_offset_accessor.cpp
  SYCL :: KernelFusion/three_dimensional.cpp
  SYCL :: KernelFusion/two_dimensional.cpp
  SYCL :: SubGroup/sub_groups_sycl2020.cpp
```

**Comment by etiotto** [comment]
Great progress! The results described in https://github.com/intel/llvm/issues/8204#issuecomment-1426845743 are a good indication that the MLIR based device compiler is on par (performance wise) with the default clang compiler. Next step is to investigate these bmks to see if there are performance opportunities.

**Comment by whitneywhtsang** [comment]
Created 3 branches in https://github.com/whitneywhtsang/sycl-bench:
1. `sycl-mlir`: used as baseline, contains fixes in https://github.com/intel/llvm/issues/8204#issuecomment-1423590224 and run infrastructure. 
2. `scalar_replacement`: manually applied scalar replacement on the 13 successful benchmarks.
3. `all_opts`: manually any other optimizations (e.g., kernel fusion) on top of `scalar_replacement` on the 13 successful benchmarks.

There are good performance gain on 7 benchmarks with scalar replacement, and additional gain on 2 benchmarks with other optimizations.
![Screenshot (4)](https://user-images.githubusercontent.com/54643204/219466386-1a3e9d42-9c73-46da-b535-0a543987e210.png)
Note: It is not always beneficial to apply kernel fusion, e.g., 3mm degraded 22% with kernel fusion.

**Comment by whitneywhtsang** [comment]
Below are the performance gains from doing "scalar replacement on reduction loops" on a modified version of SYCL-Bench :
![image](https://user-images.githubusercontent.com/54643204/224161252-f9656430-4311-4c35-bda3-e6eb70a272c7.png)
**Small modifications are done on the SYCL-Bench source code: https://github.com/whitneywhtsang/sycl-bench/tree/workaround** (more work require to perform the optimization on the original SYCL-Bench)
measured on Intel(R) Iris(R) Xe Graphics with SYCL-MLIR (https://github.com/intel/llvm/commit/e8ae475e37987122e8543b92fb49de66769d5ea2).

**Comment by etiotto** [comment]
To expand on https://github.com/intel/llvm/issues/8204#issuecomment-1462836338 the small source code change required to get the opportunities entails copying the loop upper bound captured in the lambda into a local variable at the top of the kernel. 

This is necessary to allow polygeist transformations that change a scf.while loop into a scf.for loop (and then eventually into a affine.for loop). In order to avoid manual source code changes we will have to develop a transformation that can 'peel' a member from the struct passed to the kernel function ...

**Comment by whitneywhtsang** [comment]
Status update: measured the branch with the workaround again with SYCL-MLIR (https://github.com/intel/llvm/commit/39bd89c6a4705b9b9d3e227ab7d6543286cec5d3), no degradation.

**Comment by whitneywhtsang** [comment]
Status update: 
measured the branch with the workaround again with SYCL-MLIR (https://github.com/intel/llvm/commit/401509d1da2c86e65f0023c1774c70726f876f55), no degradation.
measured the branch **without** the workaround with SYCL-MLIR (https://github.com/intel/llvm/commit/401509d1da2c86e65f0023c1774c70726f876f55), we get the gains mentioned in https://github.com/intel/llvm/issues/8204#issuecomment-1462836338 except `covariance` and `gramschmidt`.

With https://github.com/intel/llvm/pull/8923, we are able to get the gains for `covariance` and `gramschmidt` as well.

**Comment by whitneywhtsang** [comment]
Status update: measured with SYCL-MLIR (b5a387d3346f008c9df8533e3c0e83d9eafb832f), no regression.
The machine we used for performance measurement is reformatted, we can no longer claim 16% performance gain on `syr2k` even with manual source code modifications, `syr2k` now fluctuates.

**Comment by victor-eds** [comment]
@whitneywhtsang should we close this?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang should we close this?

Sure. Verified that there are no functional regressions from DPC++ on both CPU and GPU.
