### ISSUE TITLE
[SYCL] atomicInc and atomicDec functions

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#8220]
Users could call, for example, fetch_inc() and fetch_dec() functions in SYCL atomic_ref.

7.14.1.6. atomicInc() (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html?highlight=atomicinc#atomicinc)

  unsigned int atomicInc(unsigned int* address,
 unsigned int val);

reads the 32-bit word old located at the address address in global or shared memory, computes ((old >= val) ? 0 : (old+1)), and stores the result back to memory at the same address. These three operations are performed in one atomic transaction. The function returns old.

7.14.1.7. atomicDec() (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html?highlight=atomicinc#atomicdec)

  unsigned int atomicDec(unsigned int* address,
 unsigned int val);

reads the 32-bit word old located at the address address in global or shared memory, computes (((old == 0) || (old > val)) ? val : (old-1) ), and stores the result back to memory at the same address. These three operations are performed in one atomic transaction. The function returns old.

**Comment by AlexeySachkov** [comment]
Hi @zjin-lcf,

Thanks for the report. AFAIK, there is no specific support in Intel HW to implement those two functions more efficiently than it is already done in SYCLomatic (https://github.com/oneapi-src/SYCLomatic/issues/559). Therefore, we believe that there is not much sense in implementing those functions as an extension.

I will close this tracker as "won't fix", but please let me know if you have further concerns or questions

**Comment by zjin-lcf** [comment]
Will they be supported in the SYCL compiler though they are not supported by the HW ?
