### ISSUE TITLE
Community's "opaque-pointers"-related commits that were reverted during the pulldowns in intel/llvm

### ISSUE THREAD

**Issue by KornevNikita** [intel/llvm#8232]
These commits were reverted during the pulldowns. We need to apply them when we fully support opaque pointers by default. The list is being updated

- https://github.com/intel/llvm/pull/8053/commits/776d725b095251b4e792ab4f42424534e3dcf87b
https://github.com/intel/llvm/pull/8412:
- https://github.com/intel/llvm/commit/d7cf7ab61cd0a257a4d9907c8005ee89c6cf6985
- https://github.com/intel/llvm/pull/8412/commits/c56da358fefaca54f6251e29a1331eea332e21ac

**Comment by bader** [comment]
Just one commit? :)

**Comment by KornevNikita** [comment]
> Just one commit? :)

in the foreseeable future - 2 :D

**Comment by bader** [comment]
> > Just one commit? :)
> 
> in the foreseeable future - 2 :D And I don't know what was reverted outside of pulldowns.

I expected to see more from the past. Didn't we revert quite a few of similar changes in previous pulldowns?
