### ISSUE TITLE
sycl::target::host_task is not implemented

### ISSUE THREAD

**Issue by aleksmesh** [intel/llvm#8298]
In SYCL 2020 sycl::target::host_task is introduced ([4.7.6.9. Buffer accessor for commands](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_buffer_accessor_for_commands)) but not implemented.

**To Reproduce**
```
#include <sycl.hpp>

int main() {
  auto host_task = sycl::target::host_task;
}
```

To build:
`clang++ -fsycl ./sample_host_task_target.cpp -o sample`

**Output:**
```
./sample_host_task_target.cpp:4:34: error: no member named 'host_task' in 'sycl::access::target'
  auto host_task = sycl::target::host_task;
                   ~~~~~~~~~~~~~~^
1 error generated.
```

**Environment details**
Compiler version: from container [d82412764b4f228f29c518e4407a87c68e8652dc](https://github.com/orgs/intel/packages/container/llvm%2Fsycl_ubuntu2004_nightly/49522996?tag=d82412764b4f228f29c518e4407a87c68e8652dc)

**Comment by mmoadeli** [comment]
https://github.com/intel/llvm/pull/8429
