### ISSUE TITLE
Type size_type is not defined in class sycl::host_accessor

### ISSUE THREAD

**Issue by aleksmesh** [intel/llvm#8299]
Type size_type is not defined in class sycl::host_accessor   [4.7.6.10.1. Interface for buffer host accessors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_interface_for_buffer_host_accessors).

Also type `size_type `is not defined in classes `sycl::accessor` and `sycl::local_accessor`.

**To reproduce:**
```
#include <sycl.hpp>
int main ()
{
  using type = sycl::host_accessor<int, 3>::size_type;
  return 0;
}
```

**To build:**
`clang++ -fsycl -c ./size_type_absent_sample.cpp -o sample`

**Output:**
```
/size_type_absent_sample.cpp:5:45: error: no type named 'size_type' in 'sycl::host_accessor<int, 3, sycl::access::mode::read_write>'
  using type = sycl::host_accessor<int, 3>::size_type;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
```

**Environment:**
Compiler version: from container [d82412764b4f228f29c518e4407a87c68e8652dc](https://github.com/orgs/intel/packages/container/llvm%2Fsycl_ubuntu2004_nightly/49522996?tag=d82412764b4f228f29c518e4407a87c68e8652dc)

**Comment by AlexeySachkov** [comment]
PR with the fix: #8379
