### ISSUE TITLE
sycl::kernel_bundle::get_kernel<KernelName>() is not implemented

### ISSUE THREAD

**Issue by aleksmesh** [intel/llvm#8328]
**Summary**
In SYCL 2020

`template <typename KernelName> kernel get_kernel() const;`
is introduced [4.11.12.1. Queries](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:bundles.query) but not implemented.

**To reproduce**
```
#include <sycl.hpp>
int main ()
{
  sycl::queue queue;
  using kernel_name = class simple_kernel;

  queue.submit(
      [&](sycl::handler &cgh) { cgh.single_task<kernel_name>([=]() {}); });
  auto kernel_bundle =
      sycl::get_kernel_bundle<kernel_name, sycl::bundle_state::executable>(
          queue.get_context());
  auto kernel = kernel_bundle.get_kernel<kernel_name>();
}
```

**To build**
`clang++ -fsycl ./sample_get_kernel.cpp -o sample_get_kernel`

**Output**
```
./sample_get_kernel.cpp:12:31: error: no matching member function for call to 'get_kernel'
  auto kernel = kernel_bundle.get_kernel<kernel_name>();
                ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/opt/sycl/bin/../include/sycl/kernel_bundle.hpp:260:10: note: candidate function template not viable: requires single argument 'KernelID', but no arguments were provided
  kernel get_kernel(const kernel_id &KernelID) const {
         ^
1 error generated.
```

**Environment details**
Compiler version: from container [14bf9d9a9a456f665f2d5c26cf586bc56b4e06f7](https://github.com/intel/llvm/pkgs/container/llvm%2Fsycl_ubuntu2004_nightly/70049542?tag=14bf9d9a9a456f665f2d5c26cf586bc56b4e06f7)

**Comment by andylshort** [comment]
The implementation of this `get_kernel` specialisation should have been merged in this PR last week: https://github.com/intel/llvm/pull/8294

The E2E tests for these are functional but currently waiting to be merged into the test suite: https://github.com/intel/llvm-test-suite/pull/1589
