### ISSUE TITLE
info::device::local_mem_type returns none for LevelZero / UR devices

### ISSUE THREAD

**Issue by al42and** [intel/llvm#8389]
**Describe the bug**

For LevelZero and UR devices, `get_info<sycl::info::device::local_mem_type>()` returns `none` instead of `local`.

The new UR plugin (through which LevelZero, apparently, now works) returns `ZER_DEVICE_LOCAL_MEM_TYPE_LOCAL` for this query, which has the integer value of 0. Later, this zero gets casted to `local_mem_type::none`.

https://github.com/intel/llvm/blob/806775fcdadf07344bf4116f889432da0c4c8114/sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.cpp#L818

Upstream, `ZER_DEVICE_LOCAL_MEM_TYPE_LOCAL` was renamed to `UR_DEVICE_LOCAL_MEM_TYPE_LOCAL`, which is still zero: https://github.com/oneapi-src/unified-runtime/blob/7642d97401cca661b7ba065a004c47d6d0ba403e/include/ur_api.h#L3219

**To Reproduce**

```cpp
#include <CL/sycl.hpp>

int main() {
  for (const auto &Dev : sycl::device::get_devices()) {
      const auto Name = Dev.get_info<sycl::info::device::name>();
      const auto Backend = Dev.get_backend();
      const auto LocalMemType = Dev.get_info<sycl::info::device::local_mem_type>();
      std::cout << Name << " from " << Backend << " has local_mem_type "  << static_cast<int>(LocalMemType) << std::endl;
  }
}
```

```console
$ clang++ -fsycl test.cpp -o test1 && ./test1
cIntel(R) Graphics [0x56a0] from opencl has local_mem_type 1
Intel(R) UHD Graphics 770 [0x4680] from opencl has local_mem_type 1
gfx1034 from opencl has local_mem_type 1
Intel(R) Graphics [0x56a0] from ext_oneapi_unified_runtime has local_mem_type 0
Intel(R) UHD Graphics 770 [0x4680] from ext_oneapi_unified_runtime has local_mem_type 0
Intel(R) Graphics [0x56a0] from ext_oneapi_level_zero has local_mem_type 0
Intel(R) UHD Graphics 770 [0x4680] from ext_oneapi_level_zero has local_mem_type 0
NVIDIA GeForce RTX 3060 from ext_oneapi_cuda has local_mem_type 1
AMD Radeon RX 6400 from ext_oneapi_hip has local_mem_type 1

$ clang++ --version
clang version 16.0.0 (https://github.com/intel/llvm 806775fcdadf07344bf4116f889432da0c4c8114)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/aland/intel-sycl/llvm/build/install//bin
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Intel GPU (Arc 770 and UHD 770)
- DPC++ version: 806775fcdadf07344bf4116f889432da0c4c8114
- Dependencies version: compute-runtime 22.43.24595.30

**Comment by phyBrackets** [comment]
So, We just need to rename the return value to the new constant name `UR_DEVICE_LOCAL_MEM_TYPE_LOCAL` instead of `ZER_DEVICE_LOCAL_MEM_TYPE_LOCAL` ? And not sure if there are places in the codebase where this old constant name is used, So also need to make sure to update any references to the old constant name in the codebase, as it has been deprecated upstream.

**Comment by al42and** [comment]
> So, We just need to rename the return value to the new constant name `UR_DEVICE_LOCAL_MEM_TYPE_LOCAL` instead of `ZER_DEVICE_LOCAL_MEM_TYPE_LOCAL` ?

I don't think that would be enough. That would be necessary when the new version of Unified Runtime is pulled down, but that would not change the behavior: `UR_DEVICE_LOCAL_MEM_TYPE_LOCAL` still has integer value `0`.

I see two solutions:

1. Change integer values of `ur_device_local_mem_type_t` members. Probably also add `UR_DEVICE_LOCAL_MEM_TYPE_NONE` there (or does UR always assume that a device has local memory?). That will break ABI in UR, I think, but will allow keeping the code of the plugin here unmodified.
2. Add extra conversion to https://github.com/intel/llvm/blob/806775fcdadf07344bf4116f889432da0c4c8114/sycl/plugins/unified_runtime/pi2ur.hpp#L327. This, on the one hand, makes sense, because I don't think there are or should be any guarantees about enum values mapping between oneAPI UR (or any other backend) and the plugins API. On the other hand, that looks like a hack, unless a more systematic approach to conversion is used. But it looks like all other "magic" values match up, so only DEVICE_LOCAL_MEM_TYPE_x requires special handling.

**Comment by al42and** [comment]
UR updated their enum values in https://github.com/oneapi-src/unified-runtime/pull/317, so this issue will disappear with the next pulldown.

**Comment by al42and** [comment]
The conversion was added in #8657, so this issue was resolved even before the UR was updated.
