### ISSUE TITLE
SYCL online compiler support for newer Intel GPU architectures

### ISSUE THREAD

**Issue by kris-rowe** [intel/llvm#8564]
**Is your feature request related to a problem? Please describe**

Newer Intel GPU device architectures support F64 and are already supported by `ocloc`.
Currently the [default device architecture](https://github.com/intel/llvm/blob/0a17e16c80e023a880704a6169e487d68e76abda/sycl/source/detail/online_compiler/online_compiler.cpp#L52) for the SYCL online compiler extension is `tgllp`, which does not support FP64.

**Describe the solution you would like**

Add newer device architectures (e.g., PVC) supported by `ocloc` to the [list of device architectures](https://github.com/intel/llvm/blob/0a17e16c80e023a880704a6169e487d68e76abda/sycl/include/sycl/ext/intel/experimental/online_compiler.hpp#L38) considered by the SYCL online compiler and pass the appropriate `-device` flags when invoking `ocloc`. 

**Describe alternatives you have considered**

Invoking the `ocloc` library API directly, using OpenCL interoperability (e.g., `clBuildProgram`); however, avoiding this is the purpose of the online compiler extension.

**Comment by AlexeySachkov** [comment]
@cperkinsintel, could you please comment here? I would expect that recent revamps to the extension specification and implementation have fixed this

**Comment by kris-rowe** [comment]
Since the original online compiler extension has been replaced by the kernel compiler extension I am closing this issue.
