### ISSUE TITLE
iGPU drivers does not work under WSL under Docker

### ISSUE THREAD

**Issue by ZzEeKkAa** [intel/llvm#8571]
I'm trying to get intel GPU available in docker that is run in on WSL backend. Unfortunately it does not show GPUs:

**To Reproduce**
1. Install Ubuntu 22.04 on WSL2.
2. Install Docker Desktop on Windows and make sure it uses WSL as a backend
3. In WSL Ubuntu terminal execute: ```sudo docker run --rm -it --device=/dev/dri https://ghcr.io/intel/llvm/sycl_ubuntu2004_nightly -- sycl-ls```
Response:
```
[opencl:cpu:0] Intel(R) OpenCL, 12th Gen Intel(R) Core(TM) i7-1270P 3.0 [2022.14.8.0.04_160000]
[opencl:acc:1] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.14.8.0.04_160000]
```

Expected response (got from Ubuntu Desktop 22.04 livecd with just docker installed):
```
[opencl:gpu:0] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x46a6] 3.0 [22.43.24595.30]
[opencl:cpu:1] Intel(R) OpenCL, 12th Gen Intel(R) Core(TM) i7-1270P 3.0 [2022.14.8.0.04_160000]
[opencl:acc:2] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.14.8.0.04_160000]
[ext_oneapi_unified_runtime:gpu:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Graphics [0x46a6] 1.3 [1.3.24595]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Graphics [0x46a6] 1.3 [1.3.24595]
```

**Environment (please complete the following information):**

- OS: 
Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎2/‎13/‎2023
OS build	22000.1574
Experience	Windows Feature Experience Pack 1000.22000.1574.0

- Target device and vendor: Integrated GPU 12th Gen Intel(R) Core(TM) i7-1270P   2.20 GHz

Output for sycl-ls from WSL:
```
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.15.12.0.01_081451]
[opencl:cpu:1] Intel(R) OpenCL, 12th Gen Intel(R) Core(TM) i7-1270P 3.0 [2022.15.12.0.01_081451]
[opencl:gpu:2] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x46a6] 3.0 [22.53.25242.13]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Graphics [0x46a6] 1.3 [1.3.25242]
```

**Comment by dm-vodopyanov** [comment]
Hi @ZzEeKkAa, I re-directed the issue to the team that develops GPU drivers, their repo is https://github.com/intel/compute-runtime repo, and the link to the issue is https://github.com/intel/compute-runtime/issues/625. This repo (https://github.com/intel/llvm) covers only compiler issues. If you have no objections, I will close the current issue, and you can track progress and comment in the https://github.com/intel/compute-runtime/issues/625.

**Comment by ZzEeKkAa** [comment]
Thank you @dm-vodopyanov! No objections at all. Thank you!

**Comment by dm-vodopyanov** [comment]
@ZzEeKkAa great idea, thank you! Created https://github.com/intel/llvm/pull/8576.
