### ISSUE TITLE
[SYCL] enable compile-time constant initialization

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#8582]
"In a future version of this extension, it is expected that when C++20 support is available and enabled, the consteval keyword will be used to enable compile-time constant initialization of the device allocations backing device_global"

If the feature is implemented in the SYCL compiler, I appreciate your notification. There is a question. I assume that the CUDA compiler does not need C++20 support to enable compile-time constant initialization of the device allocations. 

Reference
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_device_global.asciidoc

**Comment by fwyzard** [comment]
That is correct, the CUDA compiler does not need C++20 support to enable the initialization of `__device__` variables.

In CUDA,
```c++
__device__ int global = -1;
```
works with any C++ standard.

**Comment by KornevNikita** [comment]
The [specification](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_device_global.asciidoc) has been implemented. Please re-open if needed. Thanks.
