### ISSUE TITLE
[SYCL-MLIR] Opaque pointer handling

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#8616]
1. Add back https://github.com/intel/llvm/commit/02f9cf9266c35795aa44ded0c37f0c44d8c49069, which was reverted in https://github.com/intel/llvm/pull/8600. 
2. Add back https://github.com/intel/llvm/commit/130466e924c51d408408d2a8b8f774d2a119baf4, which was reverted in https://github.com/intel/llvm/pull/8774.
3. Add back https://github.com/intel/llvm/commit/946f8030b58d3d6975369c1b8e047385b86c7ab0, which was reverted in https://github.com/intel/llvm/pull/8849.
4. Revert https://github.com/intel/llvm/commit/479c2ccabb00a3ce204976b100f276d23a0f20fa, added in https://github.com/intel/llvm/pull/10724.
5. Modify test cases to use opaque pointers.
6. Performance testing with using opaque pointers. 
7. Implementation may need to changed, e.g., TBAA for SYCL operations.

**Comment by whitneywhtsang** [comment]
More commits are reverted in https://github.com/intel/llvm/pull/10895: [f0a09fd](https://github.com/intel/llvm/pull/10895/commits/f0a09fd0e82511695c2a1b238bbd191315f82ff4), [e6ebeeb](https://github.com/intel/llvm/pull/10895/commits/e6ebeeb53d385db18a1da3f53015c865b13a685f), [ca951ad](https://github.com/intel/llvm/pull/10895/commits/ca951adca1ba826799f77ad762579b51fb374078), [baf7e83](https://github.com/intel/llvm/pull/10895/commits/baf7e83c323180d13a68eeaf34830000790b7a54), [eaef803](https://github.com/intel/llvm/pull/10895/commits/eaef803e73d283448894895b64039b247004cfcc)

Some CI build and test need to be reenabled: [eaef803](https://github.com/intel/llvm/pull/10895/commits/eaef803e73d283448894895b64039b247004cfcc)

Part of https://github.com/intel/llvm/pull/10895/commits/80301a635366d171a85402d8f7f31fec4c6abf38 needs to be undone.

**Comment by whitneywhtsang** [comment]
Remaining E2E test cases to handle:
```
  SYCL :: Plugin/enqueue-arg-order-image.cpp
  SYCL :: KernelFusion/work_group_barrier.cpp
  SYCL :: Plugin/interop-level-zero-image-ownership.cpp
  SYCL :: Plugin/interop-level-zero-image.cpp
```

**Comment by sommerlukas** [comment]
> Remaining E2E test cases to handle:
> 
> ```
>   SYCL :: Plugin/enqueue-arg-order-image.cpp
>   SYCL :: KernelFusion/work_group_barrier.cpp
>   SYCL :: Plugin/interop-level-zero-image-ownership.cpp
>   SYCL :: Plugin/interop-level-zero-image.cpp
> ```

These are fixed with the patches in #11000 and #11016.

**Comment by whitneywhtsang** [comment]
What's left to be done? Remove all typed pointer handling?

**Comment by sommerlukas** [comment]
Yes, I think left to do include:
* Remove patterns and other code dealing explicitly with the case of typed pointers
* Remove the options from passes and `cgeist`
* Remove test-cases explicitly testing typed pointer behavior

I was currently planning to do this only after a "cool-down" phase of maybe a couple of weeks, in case any regressions only appear later.

WDYT? Would you prefer to do this right away?

**Comment by whitneywhtsang** [comment]
After https://github.com/intel/llvm/pull/11160, all typed pointer handling in `sycl` branch are removed.

**Comment by sommerlukas** [comment]
Opaque pointers are now the default and typed pointer support has been removed from SYCL-MLIR in #11181.
