### ISSUE TITLE
[SYCL-MLIR] Fix `constructors.cpp` lit failure from sycl commit

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#8621]
https://github.com/intel/llvm/pull/8620 merged `sycl` branch to `sycl-mlir` branch.
On of the sycl commit https://github.com/intel/llvm/commit/ba0ea790374a0194d022ba6a633ee679c749acee causes lit failure, so is temporarily reverted in `sycl-mlir` branch.  
This issue is to investigate the failures and add back the reverted commit in `sycl-mlir` branch.

To reproduce:
```
git revert 3f342e448322e33601e51565851cc051374b4c2c
clang++ -fsycl -fsycl-device-only -O0 -w -emit-mlir llvm/polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp -o -
```
Failures:
```
Command Output (stderr):
--
BinaryOperator 0x7f050905a530 '_Bool' '>'
|-SizeOfPackExpr 0x7f050905a4f0 'unsigned long' 0x457e530 Args
`-ImplicitCastExpr 0x7f050905a518 'unsigned long' <IntegralCast>
  `-IntegerLiteral 0x457eb28 'int' 0
SizeOfPackExpr 0x7f050905a4f0 'unsigned long' 0x457e530 Args
cgeist: llvm/polygeist/tools/cgeist/Lib/clang-mlir.cc:987: ValueCategory MLIRScanner::VisitBinaryOperator(clang::BinaryOperator *): Assertion `LHS.val' failed.
```

**Comment by whitneywhtsang** [comment]
@victor-eds Can you please help take a look at this issue?

**Comment by victor-eds** [comment]
This should be fixed by: #8627 and #8632

**Comment by victor-eds** [comment]
This was already fixed by the two PRs above. (see [pipeline](https://github.com/intel/llvm/actions/runs/4411596448/jobs/7730644473))

**Comment by whitneywhtsang** [comment]
Add back the SYCL commit in https://github.com/intel/llvm/pull/8646.
