### ISSUE TITLE
Use CMake to control DPC++ application and meet problem

### ISSUE THREAD

**Issue by AXDHY** [intel/llvm#8689]
**Describe the bug**
I have installed dpc++ simple version and cuda version on my computer. I can use command to compile and link it well. But When I try to use CMake to control the project. the compile option "-fsycl-targets=nvptx64-nvidia-cuda" can not work well. I use "target_compile_options" to add the compile option, but the different result came out: 
clang offer the warning: clang-16: warning: linked binaries do not contain expected 'spir64-unknown-unknown' target; found targets: 'nvptx64-nvidia-cuda-sm_50' [-Wsycl-target],        which never came out when I use command directly.
I just followed the guide to do: https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-application-with-cmake
I use command directly: (work well)
```shell
export PATH=$DPCPP_CUDA_CPDIR/build/bin:$PATH
export LD_LIBRARY_PATH=$DPCPP_CUDA_CPDIR/build/lib:$LD_LIBRARY_PATH
clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda simple-sycl-app.cpp -o simple-sycl-app-cuda.exe
./simple-sycl-app-cuda.exe
```
my cmake: (defeat)
```cmake
cmake_minimum_required (VERSION 3.8)
set(This DPCplusplusPRGPractice)
project (${This} LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl")
add_executable(${_TARGET}
"DPCplusplusPRGPractice.cpp" "DPCplusplusPRGPractice.h"
)
target_compile_options(${_TARGET}
  PRIVATE "-g" "-Wall"
)
set(ENV{PATH} $ENV{DPCPP_CUDA_CPDIR}/build/bin:$ENV{PATH} )
set(ENV{LD_LIBRARY_PATH} $ENV{DPCPP_CUDA_CPDIR}/build/lib:$ENV{LD_LIBRARY_PATH} )
target_compile_options(${_TARGET}
    PRIVATE "-fsycl-targets=nvptx64-nvidia-cuda"
  ) 
```
By the way, I have successfully use cmake to compile & link & run the DPC++ with simple version, but I can't use cmake to successfully run the DPC++ with cuda version, which can run well using command directly. 

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. use cmake like above to control the project. the warning will came out
> clang-16: warning: linked binaries do not contain expected 'spir64-unknown-unknown' target; found targets: 'nvptx64-nvidia-cuda-sm_50' [-Wsycl-target]
I try to change the `-fsycl-targets=nvptx64-nvidia-cuda` to `-fsycl-targets=nvptx64-nvidia-cuda-sm_50`, but the warning turned to found targets: 'nvptx64-nvidia-cuda-sm_50-sm_50',.........
2. Then try to run the DPC++ application. The exception will came out: 
> terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -42 (PI_ERROR_INVALID_BINARY) -42 (PI_ERROR_INVALID_BINARY)

**Environment (please complete the following information):**

- OS: Linux Ubuntu 22.04 (WSL2 on Windows 10)
- Target device and vendor: NVIDIA GeForce GTX 1660 Ti
- DPC++ version: clang version 16.0.0 (https://github.com/intel/llvm e60c549fa31ee8fcbe32a0da3ea0b87594a6fdcf)
- Dependencies version: [e.g. low-level runtime versions (like NEO 20.04)] oclcpuexp-2022.15.12.0.01

**Additional context**
I am a new user. I followed the guide and successfully compile&link&run the DPC++ application with simple&cuda version using command directly. I tried to use cmake to deal with it, but the simple version can work well, the cuda version can't work. What should I do? Thanks a lot.

**Comment by al42and** [comment]
I don't have Windows to test, but I believe you should also add the same flag to `target_link_options`.

**Comment by AXDHY** [comment]
> I don't have Windows to test, but I believe you should also add the same flag to `target_link_options`.

Wow! Because of your suggestion @al42and , it works! It really helped me. As you said, I add the cmake command
```cmake
target_link_options(${_TARGET}
    PRIVATE "-fsycl-targets=nvptx64-nvidia-cuda") 
```
I have to apology for you because you, developers have noticed in the guide, "so using add_compile_options to pass the SYCL flags is not enough on its own, they should also be passed to add_link_options, or more simply the SYCL flags can just be added to CMAKE_CXX_FLAGS.", but I missed the notice and reported the issue. Sry...... 

Emm, "or more simply the SYCL flags can just be added to CMAKE_CXX_FLAGS." Maybe this sentence is somewhat misleading. Using it may not solve problems. add_compile_options + add_link_options is the best method.

By the way, if possible, I hope that the guide(https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-application-with-cmake) can add your suggestion as **a code example**, similar to the previous guide for cuda guide. maybe like this (Consistent with the previous tutorial/guide)
```cmake
  target_compile_options(simple-sycl-app
    PRIVATE "-fsycl-targets=nvptx64-nvidia-cuda"
  ) 
  target_link_options(simple-sycl-app
    PRIVATE "-fsycl-targets=nvptx64-nvidia-cuda"
  ) 
```

Thanks Sir! My problem has been solved. If you see my advise above, whether you accept it or not, you can close this issue.

**Comment by al42and** [comment]
Glad that my advice helped!

If you have any suggestions to improve the docs, I believe you can submit them as PRs :) Here's the file for the webpage you linked to: https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md
