### ISSUE TITLE
[SYCL] device not found error 

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#8693]
Running the SYCL programs causes the error. 
```
Native API failed. Native API returns: -1 (PI_ERROR_DEVICE_NOT_FOUND) -1 (PI_ERROR_DEVICE_NOT_FOUND)
```
However, the program runs to completion after commenting out the kernel body. So I think the error is misleading. Can you reproduce the error ?  Thanks.

Environment
Ubuntu 22.04
Device Name                                   Intel(R) Graphics [0x56a0]
Driver Version                                  22.49.25018.23

To reproduce the error running on the GPU

```
git clone https://github.com/zjin-lcf/HeCBench.git

cd HeCBench/matern-sycl
make CC=icpx run

cd  HeCBench/qtclustering-sycl
make CC=icpx run


```

**Comment by maarquitos14** [comment]
Could you provide the output for `sycl-ls`?

**Comment by AlexeySachkov** [comment]
@jinz2014, does the problem happen only on the two examples you mentioned in the description or other benchmark/samples are also affected?

> However, the program runs to completion after commenting out the kernel body. 

Do you mean removing `queue.submit` completely or just emptying the content of `parallel_for`?

**Comment by jinz2014** [comment]
No, other samples may be affected too. No, just the function body (inside a function).

**Comment by maarquitos14** [comment]
I haven't been able to reproduce the issue yet, although I don't have access to the exact same device. There's a few things you can try that could help us understanding the problem:

- Try to launch the binary directly rather than using `make run`. This is to discard that `make` is somehow affecting your environment.
- Run with `SYCL_PI_TRACE=-1` and `LD_DEBUG=libs` and paste the logs.

Also, is this a regression? Was it working before and it stopped working? If so, did you notice any change that could lead to this? For instance, you are using a new machine, the OS was updated, the compiler was updated, etc...

**Comment by jinz2014** [comment]
@maarquitos14  I have a question about "I haven't been able to reproduce the issue yet," Is this a device-specific issue ?

**Comment by maarquitos14** [comment]
It might be, yes. I tried in a few devices and couldn't reproduce it.

**Comment by jinz2014** [comment]
@al42and  Thank you for the solution! 

I hope that @maarquitos14 will let users know:  either required to rewrite their codes or expect the issue is going to be solved by the compiler.   Thanks.

**Comment by al42and** [comment]
This raises the question of error reporting: when the device is reset due to a timeout, the `PI_ERROR_DEVICE_NOT_FOUND` error code is the opposite of helpful.

**Comment by maarquitos14** [comment]
> @al42and Thank you for the solution!
> 
> I hope that @maarquitos14 will let users know: either required to rewrite their codes or expect the issue is going to be solved by the compiler. Thanks.

I understand the issue is resolved now thanks to @al42and. 


> This raises the question of error reporting: when the device is reset due to a timeout, the `PI_ERROR_DEVICE_NOT_FOUND` error code is the opposite of helpful.

I also agree that the error code is not the best.

**Comment by al42and** [comment]
> > I hope that @maarquitos14 will let users know: either required to rewrite their codes or expect the issue is going to be solved by the compiler. Thanks.
> 
> I understand the issue is resolved now thanks to @al42and.

The issue is resolved for this code, but it can affect any code ported from CUDA, where an early return is safe and quite idiomatic. That raises the importance of better diagnostics here, IMHO.

It's also unclear, at least to me, why only A770 were affected. Sure, UB, nasal daemons etc, but could there be something special about the handling of the hardware?

**Comment by jinz2014** [comment]
I observe that, on a V100 GPU, the execution time of the SYCL kernel is ~18806 us. After the patch, the time is 19913 us.

**Comment by al42and** [comment]
> I observe that, on a V100 GPU, the execution time of the SYCL kernel is ~18806 us. After the patch, the time is 19913 us.

Yeah, it's more effective to do an early return, and on NVIDIA devices, that is safe. Sprinkling around `#ifdef(__NVPTX__)` might help

**Comment by jinz2014** [comment]
@al42and  I had assumed that early return is just a programming style. Thank you for the suggestions and comments.

**Comment by jinz2014** [comment]
@maarquitos14   Would you please notify me when rewrite the kernel is not needed to solve the issue ?

**Comment by maarquitos14** [comment]
> @maarquitos14 Would you please notify me when rewrite the kernel is not needed to solve the issue ?

I think there has been a misunderstanding. This is not a compiler issue. There's nothing we can do from the compiler to support this pattern. CUDA only cares about non-exited threads in their barriers, but SYCL does not provide any guarantee about this. Thus, as of now, if any of the threads doesn't reach the barrier, it simply does not complete, and the program stalls.

**Comment by smaslov-intel** [comment]
> > @maarquitos14 Would you please notify me when rewrite the kernel is not needed to solve the issue ?
> 
> I think there has been a misunderstanding. This is not a compiler issue. There's nothing we can do from the compiler to support this pattern. CUDA only cares about non-exited threads in their barriers, but SYCL does not provide any guarantee about this. Thus, as of now, if any of the threads doesn't reach the barrier, it simply does not complete, and the program stalls.

Shouldn't that be somehow flagged (or fixed) by DPC++ Compatibility Tool?

**Comment by jinz2014** [comment]
@maarquitos14 
As of now, the program is not stalled on the ARC device and other devices don't see the 'device not found' error. I understand you will investigate the cause of the error message.

**Comment by jinz2014** [comment]
@smaslov-intel  
The CUDA compiler supports early exit. Is it good the SYCL compiler can also support it ?

**Comment by jinz2014** [comment]
Thank you for explaining this.  Sorry, I didn't understand the answers from @maarquitos14 and @smaslov-intel.
In short, the compiler support means that early-exit may be mapped to "late"-exit by a compiler.

**Comment by jinz2014** [comment]
> @jinz2014, does the problem happen only on the two examples you mentioned in the description or other benchmark/samples are also affected?
> 
> > However, the program runs to completion after commenting out the kernel body.
> 
> Do you mean removing `queue.submit` completely or just emptying the content of `parallel_for`?

I will try to add a list of examples for the issue:

https://github.com/zjin-lcf/HeCBench/tree/master/gc-sycl
