### ISSUE TITLE
Host pointer missing in handler explicit memory operations documentation

### ISSUE THREAD

**Issue by Luigi-Crisci** [intel/llvm#8714]
The documentation for the functions `copy` and `memcpy` in the `handler` class specifies that such operations:
> Copies data from one memory region to another, both pointed by USM pointers.  

While SYCL KRONOS documentation says:

> Copies [...] from the pointer src to the pointer dest. The dest and src parameters must each either be a host pointer or a pointer within a USM allocation that is accessible on the handler’s device.

This is incorrect as it suggests that you cannot use such functions with anything that is not a USM pointer, while you can call them with host pointers. Also, in _release 2022-12_ it is allowed to do such a thing. 
Does DPC++ define a USM pointer differently compared to the KRONOS docs?

Lastly, Here is a simple example code of a host pointer with explicit memory op:
```c++
int main(){
	sycl::queue Q{sycl::default_selector_v};
	auto ptr = sycl::malloc_device<int>(10, Q);
	std::vector<int> v(10,5);

	Q.copy(v.data(), ptr, 10);
	Q.parallel_for(sycl::range(10), [=](sycl::item<1> it){
		ptr[it.get_id()]++;
	});
	Q.copy(ptr, v.data(), 10);

	for (int i = 0; i < 10; i++) {
		assert(v[i] == 6);
	}
}
```

**Comment by maarquitos14** [comment]
This was fixed in #8026.
