### ISSUE TITLE
Specifying second, empty `-fsycl-targets` causes crash

### ISSUE THREAD

**Issue by psalz** [intel/llvm#8719]
**Describe the bug**

Kind of specific, but I actually ran into this due to a CMake configuration issue. The invocation

```clang++ -fsycl -fsycl-targets= -fsycl-targets=spir64 somefile.cpp```

causes this crash:

```clang++: <path-to>/llvm/include/llvm/ADT/SmallVector.h:298: const T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::operator[](llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type) const [with T = const char*; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::const_reference = const char* const&; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type = long unsigned int]: Assertion `idx < size()' failed.```

**Environment (please complete the following information):**

`clang version 17.0.0 (https://github.com/intel/llvm.git 7c7efeee209205657283f1d054c8d031589aa46e)`

**Comment by mdtoguchi** [comment]
This has been addressed here:  https://github.com/intel/llvm/commit/3c291ef764074ce171ab41419603b14d91ec2b72
