### ISSUE TITLE
The return value of 'sscanf()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [intel/llvm#872]
https://github.com/intel/llvm/blob/9c2035a02f121feaef54f6b19266a19c15caea21/lldb/source/Plugins/Platform/Android/AdbClient.cpp#L259

**Comment by bader** [comment]
@QiAnXinCodeSafe, please, open the issue in https://github.com/llvm/llvm-project/ - lldb development repository.
