### ISSUE TITLE
Extra detail namespaces are causing confusion

### ISSUE THREAD

**Issue by Pennycook** [intel/llvm#8721]
**Describe the bug**
Different headers make different assumptions about the meaning of `detail`, which can lead to issues when headers are moved or included in new places.  There are many instances of this, but I'll give one concrete example below to illustrate the problem.

sub_group_mask.hpp defines `sycl::detail::Builder`:
https://github.com/intel/llvm/blob/c5c7ac2ea55b23c019120885174a6a10f1506282/sycl/include/sycl/ext/oneapi/sub_group_mask.hpp#L17-L21

...and then refers to that definition as `detail::Builder` inside of a class defined in `sycl::ext::oneapi`:
https://github.com/intel/llvm/blob/c5c7ac2ea55b23c019120885174a6a10f1506282/sycl/include/sycl/ext/oneapi/sub_group_mask.hpp#L23-L33

Everything in `sycl::ext::oneapi` is in `sycl`, so the reference to `detail` resolves to `sycl::detail` in this case when the header is compiled in isolation.  However, if any header defines a `detail` namespace in `sycl::ext` or `sycl::ext::oneapi`, `detail` resolves to `sycl::ext::detail` or `sycl::ext::oneapi::detail` and `Builder` cannot be found.

There are several such nested `detail` namespaces around, e.g. in atomic_ref.hpp:
https://github.com/intel/llvm/blob/c5c7ac2ea55b23c019120885174a6a10f1506282/sycl/include/sycl/ext/oneapi/atomic_ref.hpp#L24-L30

My suggestion is to use `sycl::detail::` everywhere, and remove all of these nested namespaces.  Details are details.

**To Reproduce**
Include sub_group_mask.hpp after a definition of a nested `detail` namespace (e.g. `sycl::ext::oneapi::detail`).

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: N/A
- DPC++ version: c5c7ac2ea55b23c019120885174a6a10f1506282
- Dependencies version: N/A

**Additional context**
@bader has suggested previously that it is desirable to be able to include separate headers for different SYCL functionality. I think cleaning this up is a precursor to that -- if we encourage developers to start including headers that aren't sycl.hpp, it's very likely they'll encounter issues like this.  I encountered it while trying to add some new functionality, and @steffenlarsen has encountered this issue previously as well.

**Comment by aelovikov-intel** [comment]
> My suggestion is to use sycl::detail:: everywhere, and remove all of these nested namespaces.

That makes those details' implementation much more verbose - we now have to use the full extension namespace qualifiers inside helpers.

**Comment by Pennycook** [comment]
> That makes those details' implementation much more verbose - we now have to use the full extension namespace qualifiers inside helpers.

Sorry, I'm not sure I follow.  Are you saying that we might have a situation where we have to write this:

```c++
namespace sycl::detail {
void helper(ext::oneapi::experimental::Foo bar);
}
```

instead of:

```c++
namespace sycl::ext::oneapi::experimental::detail {
void helper(Foo bar);
}
```

I hadn't considered that.

I agree there's a trade-off here, but I think we have to pay the verbosity cost somewhere.  If we leave things as they are, every usage of something declared in a `detail` namespace should be fully qualified (to avoid unexpected compilation errors).

**Comment by aelovikov-intel** [comment]
> Are you saying that we might have a situation where we have to write...

yes.

> If we leave things as they are, every usage of something declared in a detail namespace should be fully qualified (to avoid unexpected compilation errors).

Or every inner `detail` namespace has to introduce outer `detail` namespaces into itself, like is done in the example you provided above:

https://github.com/intel/llvm/blob/c5c7ac2ea55b23c019120885174a6a10f1506282/sycl/include/sycl/ext/oneapi/atomic_ref.hpp#L24-L30

I think that's relatively minor thing to do.

**Comment by Pennycook** [comment]
> Or every inner `detail` namespace has to introduce outer `detail` namespaces into itself, like is done in the example you provided above:
> 
> https://github.com/intel/llvm/blob/c5c7ac2ea55b23c019120885174a6a10f1506282/sycl/include/sycl/ext/oneapi/atomic_ref.hpp#L24-L30
> 
> I think that's relatively minor thing to do.

If you think that would be easier, that works for me.  Do you think we could test for this, or would it just have to be something that folks look out for during code review?

**Comment by aelovikov-intel** [comment]
I think the latter, because it's dependent on the include order and, since our headers aren't "self-contained", we can only verify the one used in `<sycl/sycl.hpp>`.

**Comment by aelovikov-intel** [comment]
I think introducing `using namespace ::sycl::detail;` isn't going to break things (unlike changing the namespaces we are actually using), so we can probably just give it a try and see how it would go.

**Comment by aelovikov-intel** [comment]
I don't think we're going to address that specifically, but it's not unlikely it will resolve (if haven't yet) organically on its own using `using namespace ::sycl::detail` "idiom" above. We also have tests to verify our includes are "self-contained", so this shouldn't be as important/common as before (if exists at all).
