### ISSUE TITLE
Some HIP and CUDA tests were disabled during the pulldown.

### ISSUE THREAD

**Issue by KornevNikita** [intel/llvm#8796]
See: https://github.com/intel/llvm-test-suite/pull/1633

These tests are failing (time out) with https://github.com/intel/llvm/pull/8412, so we decided to temporarily disable them to unblock the pulldown.
CUDA test may be okay, but CUDA testing workflow is broken for now, so we can't verify it.
"The AMD failures are fairly limited as they only happen at -O0 so we can fix them in the sycl branch after the merge."

**Comment by JackAKirk** [comment]
The bug from this pulldown was fixed upstream. However there is another O0 bug currently, which a proposed fix: https://github.com/ROCm-Developer-Tools/clr/pull/13

At the moment you can only compile at O0 in the hip backend when using rocm 5.7. Earlier versions lead to seg faults for even an empty kernel.

**Comment by JackAKirk** [comment]
Closing this since this issue hasn't reoccurred on latest rocm versions for a while. The fix above was for old rocm versions and it is up to amd to merge this.
