### ISSUE TITLE
SYCL :: Basic/barrier_order.cpp timeout on L0

### ISSUE THREAD

**Issue by pvchupin** [intel/llvm#8798]
Looks like this test started to fail after https://github.com/intel/llvm-test-suite/pull/1122 in some PRs

First time it was noticed at intel/llvm-test-suite#1122 based on: https://github.com/intel/llvm-test-suite/issues/1122#issuecomment-1270114636_
Currently it failed at least:

* https://github.com/intel/llvm/actions/runs/3421697615/jobs/5698637478
* https://github.com/intel/llvm/actions/runs/3419272559/jobs/5692969517

And passed at:
* https://github.com/intel/llvm/actions/runs/3421705414/jobs/5698877902

All fails due to timeout.
It seems all fails are on the same runner intel_sycl2

@smaslov-intel, any ideas why it may happen?

**Comment by AlexeySachkov** [comment]
The test is currently enabled on L0 and there are no recent reports of it hanging there. There are issues with OpenCL GPU path and potential problems on CUDA, but they are tracked in #7330.
