### ISSUE TITLE
AtomicRef tests enabled by #534 fail on HIP back-end.

### ISSUE THREAD

**Issue by bader** [intel/llvm#8804]
Failed Tests (4):
  SYCL :: AtomicRef/add.cpp
  SYCL :: AtomicRef/max.cpp
  SYCL :: AtomicRef/min.cpp
  SYCL :: AtomicRef/sub.cpp

Log - https://github.com/intel/llvm/runs/5321377517?check_suite_focus=true

**Comment by JackAKirk** [comment]
Fixed by https://github.com/intel/llvm/pull/8003
