### ISSUE TITLE
[CUDA] Enable tests in AtomicRef for CUDA after adding support for generic address space in DPC++

### ISSUE THREAD

**Issue by ghost** [intel/llvm#8807]
Currently the tests in `AtomicRef` for the generic address space are separated in different `*_generic.cpp` files just to let us disable them on CUDA. After support for the generic address space is added to the CUDA backend, the tests should be enabled and can be merged into the .cpp files for the tests with the global address space.

See also: https://github.com/intel/llvm/issues/5215

**Comment by rodburns** [comment]
Fixed by https://github.com/intel/llvm-test-suite/pull/1446
