### ISSUE TITLE
[Flaky] Unexpectedly passing SYCL/Sampler tests.

### ISSUE THREAD

**Issue by DenisBakhvalov** [intel/llvm#8814]
Windows + LevelZero configuration is affected.

Examples are here:
http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FWin%2FTest_Suite/detail/Test_Suite/2168/pipeline/

And here:
http://134.191.240.166:8010/blue/organizations/jenkins/LLVM-Test-Suite-CI%2FLLVM-Test-Suite-WIN/detail/LLVM-Test-Suite-WIN/406/pipeline

**Comment by AlexeySachkov** [comment]
The test was re-enabled in intel/llvm-test-suite#922, this issue is not actual anymore
