### ISSUE TITLE
Swizzle vec doesn't have member type element_type

### ISSUE THREAD

**Issue by kopylovanat** [intel/llvm#8879]
According to [4.14.2.4. Swizzled vec class](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#swizzled-vec-class) "he swizzled_vec class must define an unspecified temporary which provides the entire interface of the SYCL vec class template", but member type element_type of vec class API is not available.

**To Reproduce**
```
#include <sycl.hpp>

int main() {

  sycl::vec<char, 1> vec(5);
  using T = decltype(vec.template swizzle<sycl::elem::s0>())::element_type;
}
```
`clang++ -fsycl ./sample_vec_element_type.cpp -o sample`

Output:
```
./sample_vec_element_type.cpp:7:63: error: no type named 'element_type' in 'sycl::detail::SwizzleOp<sycl::vec<char, 1>, sycl::detail::GetOp<char>, sycl::detail::GetOp<char>, sycl::detail::GetOp, 0>'
  using T = decltype(vec.template swizzle<sycl::elem::s0>())::element_type;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
```
**Environment (please complete the following information):**

- OS: Red_8.2_x86_64
- Memory: 504GB
- CPUCount: 2 CoreCount: 64 HT: yes
- CPU Model: Intel(R) Xeon(R) Platinum 8260M CPU @ 2.40GHz
- Compiler version: [DPC++ daily 2023-03-25](https://github.com/intel/llvm/releases/tag/sycl-nightly%2F20230325)

**Comment by steffenlarsen** [comment]
Implemented with https://github.com/intel/llvm/pull/9065.
