### ISSUE TITLE
[SYCL][Driver] Enable full clang driver unit tests on Windows

### ISSUE THREAD

**Issue by AGindinson** [intel/llvm#888]
Several `sycl-offload*.c` LITs under `clang/test/Driver` are marked with 'XFAIL: windows-msvc'. The failures are seemingly related to some path regexp issue. New tests addition also faces this limitation, e.g. https://github.com/intel/llvm/pull/884.

This XFAIL need to be analyzed and fixed as soon as possible to provide better.

**Comment by mdtoguchi** [comment]
Most of the problems deal with using <code>FileCheck -DOBJ=%t.obj</code> type checks and trying to match with <code>[[OBJ]]</code>.  This doesn't look to work too well on Windows perhaps due to the additional escapes used for the directory separators and dots.

Is there any way to work around this?
