### ISSUE TITLE
Subscript operator for swizzle vec is not available

### ISSUE THREAD

**Issue by kopylovanat** [intel/llvm#8880]
**Describe the bug**
According to [4.14.2.4. Swizzled vec class](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#swizzled-vec-class) "he swizzled_vec class must define an unspecified temporary which provides the entire interface of the SYCL vec class template", but operator[] of vec class API is not available.

**To Reproduce**
```
#include <sycl.hpp>

int main() {

  sycl::vec<int, 2> input_vec(1);

  auto ref = input_vec.template swizzle<sycl::elem::s1>()[0];
}
```
`clang++ -fsycl ./sample_vec_subscript.cpp -o sample`

Output:
```
./sample_vec_subscript.cpp:7:58: error: type 'Swizzle<1>' (aka 'SwizzleOp<sycl::vec<int, 2>, GetOp<int>, GetOp<int>, sycl::detail::GetOp, 1>') does not provide a subscript operator
  auto ref = input_vec.template swizzle<sycl::elem::s1>()[0];
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
1 error generated.
```

**Environment (please complete the following information):**

- OS: Red_8.2_x86_64
- Memory: 504GB
- CPUCount: 2 CoreCount: 64 HT: yes
- CPU Model: Intel(R) Xeon(R) Platinum 8260M CPU @ 2.40GHz
- Compiler version: [DPC++ daily 2023-03-21](https://github.com/intel/llvm/releases/tag/sycl-nightly%2F20230321)

**Comment by steffenlarsen** [comment]
Fixed with https://github.com/intel/llvm/pull/9065.
