### ISSUE TITLE
[SYCL][CUDA]Implement proper device queries for atomic_fence_capabilities

### ISSUE THREAD

**Issue by maarquitos14** [intel/llvm#8938]
Currently, `info::device::atomic_fence_order_capabilities` and `info::device::atomic_fence_scope_capabilities` are just returning minimum mandated capabilities specified by SYCL2020, without querying the device at all. We should actually query the device to get this information.

**Comment by JackAKirk** [comment]
Fixed by https://github.com/oneapi-src/unified-runtime/pull/1291
