### ISSUE TITLE
clang hangs when compiling non-trivial designated initializers

### ISSUE THREAD

**Issue by drhaozhong** [intel/llvm#8961]
The code is as follows:

` static char * name[] = {
 [0x80000000] = "bar"
 };
`
The compilation hangs, and a message is as follows:

.c:2:2: warning: array designators are a C99 extension [-Wc99-designator]
 [0x80000000] = "bar"
 ^~~~~~~~~~~~
.c:2:17: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
 [0x80000000] = "bar"
                ^
^C

**Comment by dm-vodopyanov** [comment]
Closing due to https://github.com/intel/llvm/issues/8967#issuecomment-1499255778
