### ISSUE TITLE
a read of a variable outside its lifetime is not identified.

### ISSUE THREAD

**Issue by drhaozhong** [intel/llvm#8965]
The code is as follows:

` void bar(int n, int x[n]) {}`

MSVC reports an error:

<source>(1): error C2131: expression did not evaluate to a constant
<source>(1): note: failure was caused by a read of a variable outside its lifetime
<source>(1): note: see usage of 'n'
Compiler returned: 2

GCC reports a similar error:

 error: use of parameter outside function body before ‘]’ token

However, the clang++ in this project does not report any errors.

**Comment by dm-vodopyanov** [comment]
Closing due to https://github.com/intel/llvm/issues/8967#issuecomment-1499255778
