### ISSUE TITLE
double floating point suffix of 'd' and 'D' not accepted

### ISSUE THREAD

**Issue by drhaozhong** [intel/llvm#8966]
The Decimal Floating-Point Technical Report (WG14/N1176 and later) added
the suffixes 'd' and 'D' to indicate (binary) double, and 'dd' and 'DD' to 
indicate decimal double (_Decimal64).  The suffixes 'd' and 'D'
are in addition to unsuffixed decimal floating constants (all three
mean 'double').  This is pages 12 and 13 in N1176, section 7 Constants,
which is changing C99 section 6.4.4.2 floating-suffix.

However, I find that this compiler does not accept the above formats. The below code snippets produce errors:

`double x = 9.9D;`

`double x = 9.9DD;
`

error: invalid suffix 'DD' on floating constant
double x = 9.9DD;
              ^
1 error generated.

Meanwhile, gcc accepts the above code lines.

**Comment by dm-vodopyanov** [comment]
Closing due to https://github.com/intel/llvm/issues/8967#issuecomment-1499255778
