### ISSUE TITLE
[SYCL] Reasoning behind `svgenfloat abs(svgenfloat)`

### ISSUE THREAD

**Issue by nmnobre** [intel/llvm#8981]
Hi,

I was wondering how `double sycl::abs(double)` was working since it's not in the standard but after some digging I found this definition for `svgenfloat abs(svgenfloat)`:

https://github.com/intel/llvm/blob/64d4514275516cf66bc3265a574df11838317c61/sycl/include/sycl/builtins.hpp#L893-L897

Do we consider this an extension, a historical trait, or is there another reason behind this definition?

Cheers,
-Nuno

**Comment by bader** [comment]
Nice catch. Looks like an oversight to me. The only reason I can imagine is simplify the migration from `std::` to `sycl::` namespace.

**Comment by nmnobre** [comment]
Thanks @bader. :-)

To be honest, the fact the definition is there doesn't bother me much, so if you think it should stay, I'm happy with that.
What's slightly more troublesome is that it allowed Intel to get away with four such usages of `sycl::abs` in MKL's `poisson_impl.hpp`. :-P
Do you think you can let the appropriate team know or, otherwise, how do you recommend I report this?

**Comment by bader** [comment]
From https://www.intel.com/content/www/us/en/docs/oneapi/programming-guide/2023-0/intel-oneapi-math-kernel-library-onemkl.html.

> For Intel community-support, visit the [oneMKL forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library). For the community-supported open-source version, visit the [oneMKL GitHub* page](https://github.com/oneapi-src/oneMKL).

You seem to use oneMKL from Intel oneAPI toolkit, so the right place to report this issue is https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library.

**Comment by nmnobre** [comment]
[Reported](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Non-standard-usage-of-sycl-abs/td-p/1475431).
