### ISSUE TITLE
Basic/memory-consumption.cpp fails on unrelated PRs

### ISSUE THREAD

**Issue by aelovikov-intel** [intel/llvm#9008]
https://github.com/intel/llvm/pull/9001
https://github.com/intel/llvm/pull/8994
https://github.com/intel/llvm/pull/8979

From https://github.com/intel/llvm/actions/runs/4654281855/jobs/8236090683?pr=9001 (for #9001):
```
$ "env" "ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu" "/__w/llvm/llvm/build-e2e/Basic/Output/memory-consumption.cpp.tmp.out"
# command output:
64000 kb
64004 kb
Platform: Intel(R) Level-Zero
Failed

error: command failed with exit status: 1
```

**Comment by sarnex** [comment]
@bader This is still failing, can we just disable the test for now? I'm happy to do it myself.
