### ISSUE TITLE
[SYCL][CUDA][HIP] Queue fill routine fails 

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#9064]
**Describe the bug**
When using a large array to do `queue.fill()`, there is a runtime error. (ignoring correctness and synchronizations aspects for the below reproducer).

**To Reproduce**
```c++
#include <sycl/sycl.hpp>

int main(int argc, char const *argv[]) {
  sycl::queue q{sycl::gpu_selector_v};
  constexpr size_t n = 1000000;
  float *d_A = sycl::malloc_device<float>(n, q);

  auto ev1 = q.fill(d_A, 0, n * sizeof(float));
  return 0;
}
```
Using some trace from CUDA plugin:
```bash
---> piQueueRelease(
	<unknown> : 0x23e0620

PI CUDA ERROR:
	Value:           700
	Name:            CUDA_ERROR_ILLEGAL_ADDRESS
	Description:     an illegal memory access was encountered
	Function:        operator()
	Source Location: ...../llvm/sycl/plugins/cuda/pi_cuda.cpp:2590

) ---> 	pi_result : -999
```

**Comment by abagusetty** [comment]
On the HIP plugin: the execution hangs instead but at almost the same function as CUDA:
```bash
---> piQueueRelease(
	<unknown> : 0xb86580

```

**Comment by jinz2014** [comment]
template <typename T>
event fill(void* ptr, const T& pattern, size_t count, event depEvent)

the Intel compute runtime does not seem to report failure...

**Comment by konradkusiak97** [comment]
The `queue.fill()` implementation currently invokes a kernel with `range<1>(Count)` that fills the array, so the correct way of calling that function would be:
```cpp
...
auto ev1 = q.fill(d_A, 0, n);
...
```

**Comment by abagusetty** [comment]
Given the SYCL spec proto-types, the above reproducer is buggy. Thanks for clarifying. 

```c++
 template <typename T> event fill(void* ptr, const T& pattern, size_t count);
 template <typename T> event fill(void* ptr, const T& pattern, size_t count, event depEvent);
 template <typename T> event fill(void* ptr, const T& pattern, size_t count, const std::vector<event>& depEvents);
```
