### ISSUE TITLE
Invalid value getting command_execution_status from an event using OpenCL plugin

### ISSUE THREAD

**Issue by jandrovins** [intel/llvm#9099]
**Describe the bug**
When using `event.get_info<sycl::info::event::command_execution_status>()` I get a value that does not belong to the [valid values listed in the SYCL specification](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.event.command-status). I am using the [POCL](https://github.com/pocl/pocl) implementation of OpenCL, running on POCL's pthread device (CPU).

From what I understand reading the code on the OpenCL plugin at [this line](https://github.com/intel/llvm/blob/e11b35835722f018a94eac82d78d73b861e58a6e/sycl/plugins/opencl/pi_opencl.cpp#L2298), SYCL is using the `clGetEventInfo` from OpenCL to get the execution status of the event. And so since OpenCL has one more valid value (being CL_QUEUED) for the EVENT_COMMAND_EXECUTION_STATUS ([as specified here](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_EVENT_COMMAND_EXECUTION_STATUS)), then `clGetEventInfo` can give a value that is not valid for SYCL. I am not very familiar with the implementation of OpenCL's plugin or of POCL, so I am not sure if I am missing something in my reasoning.

**To Reproduce**
Code to reproduce that checks if an event's execution status value belongs to the ones that SYCL has in its specification:

1. CODE SNIPPET:
```
#include <CL/sycl.hpp>
#include <assert.h>
#include <iostream>

static void initialize(double *data, double value, long N, long TS) {
    for (long i = 0; i < N; i++) {
        data[i] = value;
    }
}

int main(int argc, char *argv[]) {

    const long n = 32;
    const long TS = 32;
    const long its = 1;

    sycl::queue q1;

    double *h_x, *h_y, *d_x, *d_y;
    long size = n * sizeof(double);

    // Allocate host vectors
    h_x = (double *)(malloc(size));
    h_y = (double *)(malloc(size));
    assert(h_x != nullptr && h_y != nullptr);

    // Allocate device vectors
    d_x = (double *)(sycl::malloc_device<double>(size, q1));
    d_y = (double *)(sycl::malloc_device<double>(size, q1));
    assert(d_x != nullptr && d_y != nullptr);

    const double alpha = 10.0;

    initialize(h_x, 1.0, n, TS);
    initialize(h_y, 0.0, n, TS);

    sycl::queue q;

    sycl::event e1 = q.memcpy(d_x, h_x, size);
    sycl::event e2 = q.memcpy(d_y, h_y, size);

    sycl::event e3 = q.parallel_for<class C_AXPY>(
        sycl::range<1>(TS), {e1, e2},
        [=](sycl::id<1> i) {
            d_y[i] += alpha * d_x[i];
        });
    //e3.wait();
    // Asynchronous device to host copy  - depends on e3
    sycl::event e5 = q.memcpy(h_y, d_y, size, {e3});
    std::cout << "VVV JUSTO ANTES DE get_info\n";
    auto eret = e5.get_info<sycl::info::event::command_execution_status>();
    if (eret != sycl::info::event_command_status::complete &&
        eret != sycl::info::event_command_status::running &&
        eret != sycl::info::event_command_status::submitted) {
        std::cerr << "VVV ERROR =======> value=" << ((eret)==sycl::info::event_command_status::ext_oneapi_unknown) << " INVALID event.get_info<sycl::info::event::command_execution_status>()\n";
    } else if  (eret == sycl::info::event_command_status::complete) {
        std::cout << "VVV COMPLETED =======> EVENT COMPLETED SUCCESFULLY\n";
    } else if (eret == sycl::info::event_command_status::running) {
        std::cout << "VVV RUNNING =======> EVENT RUNNING SUCCESFULLY\n";
    } else if (eret == sycl::info::event_command_status::submitted) {
        std::cout << "VVV SUBMITTED =======> EVENT SUBMITTED SUCCESFULLY\n";
    }

    e5.wait_and_throw();

    free(h_x);
    free(h_y);
    sycl::free(d_x, q1);
    sycl::free(d_y, q1);

    return 0;
}
```
2. `clang++ -fsycl test_error.cpp`
3. ./a.out
4. **What is wrong:** A message printing that the return value of `event.get_info<sycl::info::event::command_execution_status>()` does not belong to the [valid ones listed in the SYCL specification](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.event.command-status)

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: OpenCL CPU using POCL (pthread device).
- DPC++ version: clang version 17.0.0 (https://github.com/intel/llvm 09ae6434f55f851e75908a3c254b779dd5c5227c)
- Dependencies version: Does not apply

**Additional context**
.

**Comment by AlexeySachkov** [comment]
> From what I understand reading the code on the OpenCL plugin at [this line](https://github.com/intel/llvm/blob/e11b35835722f018a94eac82d78d73b861e58a6e/sycl/plugins/opencl/pi_opencl.cpp#L2298), SYCL is using the `clGetEventInfo` from OpenCL to get the execution status of the event. And so since OpenCL has one more valid value (being CL_QUEUED) for the EVENT_COMMAND_EXECUTION_STATUS ([as specified here](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_EVENT_COMMAND_EXECUTION_STATUS)), then `clGetEventInfo` can give a value that is not valid for SYCL. I am not very familiar with the implementation of OpenCL's plugin or of POCL, so I am not sure if I am missing something in my reasoning.

Thanks! That looks like a correct analysis to me. We should probably have a wrapper around `clGetEventInfo` to convert OpenCL return values to SYCL values.
