### ISSUE TITLE
LLVM_SPIRV tests failed on Windows: transcoding/PipeStorage.ll and extensions/INTEL/SPV_INTEL_io_pipes/PipeStorageIOINTEL.ll

### ISSUE THREAD

**Issue by dm-vodopyanov** [intel/llvm#9387]
- **transcoding/PipeStorage.ll** failed on the patch with unrelated changes: https://github.com/intel/llvm/pull/9365 (logs: https://github.com/intel/llvm/actions/runs/4931427621/jobs/8813455059)
- **extensions/INTEL/SPV_INTEL_io_pipes/PipeStorageIOINTEL.ll** failed on the patch with unrelated changes: https://github.com/intel/llvm/pull/9369 (logs: https://github.com/intel/llvm/actions/runs/4925969516/jobs/8800949058?pr=9369)

All failures are on Windows only.

**Comment by aelovikov-intel** [comment]
@jcranmer-intel has a fix at https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2007
