### ISSUE TITLE
Upstream address spaces handling

### ISSUE THREAD

**Issue by Fznamznon** [intel/llvm#942]
Spec assumes that SYCL implementation does address space deduction, but we implemented other approach.
Without our address space handing support even compilation of SYCL headers with clang from LLORG is not possible. I see the following diagnostics emitted from SYCL headers:

```
build/lib/clang/10.0.0/include/CL/__spirv/spirv_vars.hpp:47:60: error: variable in constant address space must be initialized
extern "C" const __attribute((opencl_constant)) uint32_t __spirv_BuiltInSubgroupLocalInvocationId;
```

Diagnostic is silent in our version of the compiler by adding our own address space map. So when you write `__attribute((opencl_constant))` it turns into "sycl" constant address space:

```
(gdb) p Var->getType().getAddressSpace()
$6 = clang::LangAS::sycl_constant
(gdb) p Var->getType().getAddressSpace() == clang::LangAS::opencl_constant
$7 = false
```

Another one is:

```
build/lib/clang/10.0.0/include/CL/sycl/accessor.hpp:903:12: error: binding reference of type 'int' to value of type 'typename detail::PtrValueType<int, AS>::type' (aka '__global int') changes address space
    return getQualifiedPtr()[LinearIndex];
```

I assume that it happens because we added new address space rules to the compiler: emit generic address space by default and cast when it's possible.

**Comment by Fznamznon** [comment]
@asavonic FYI.

**Comment by bader** [comment]
First patch is uploaded here: https://reviews.llvm.org/D80932.
Send an RFC to cfe-dev mailing list: http://lists.llvm.org/pipermail/cfe-dev/2020-June/066047.html

**Comment by bader** [comment]
Done by https://reviews.llvm.org/D89909 and https://reviews.llvm.org/D100396.
