### ISSUE TITLE
[SYCL-MLIR] Handle `CXXInheritedCtorInitExpr` base initializer in cgeist codegen

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/llvm#9450]
To reproduce: `clang++ -fsycl -fsycl-targets=spir64-unknown-unknown-syclmlir -w sycl/test-e2e/AtomicRef/store_local.cpp`
Number of e2e tests failed: 82

**Comment by victor-eds** [comment]
Handled in #9549. Will report changes in passed tests here.

**Comment by whitneywhtsang** [comment]
Verified that this PR fixes the original problem reported in https://github.com/intel/llvm/issues/9450, the e2e test cases are now failing due to other problems, like https://github.com/intel/llvm/issues/9453, https://github.com/intel/llvm/issues/9448, etc.
