### ISSUE TITLE
HIP PI backend issues warning during build

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#9457]
During build in CI, the HIP backend issues the following warning, which is in turn promoted to an error:

```
In file included from /__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.hpp:34,
                 from /__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:14:
/opt/rocm/hip/include/hip/hip_runtime.h:26:2: error: #warning "This file is deprecated. Use header files from HIP_PATH/include, where HIP_PATH corresponds to HIP install path" [-Werror=cpp]
   26 | #warning "This file is deprecated. Use header files from HIP_PATH/include, where HIP_PATH corresponds to HIP install path"
      |  ^~~~~~~
In file included from /opt/rocm-5.5.0/include/hip/hip_runtime.h:58,
                 from /opt/rocm/hip/include/hip/hip_runtime.h:31,
                 from /__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.hpp:34,
                 from /__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:14:
```

See for example post-commit of https://github.com/intel/llvm/commit/0a6adea3898f037f025a610f68af10a3f4a1c01b.

**Comment by steffenlarsen** [comment]
Temporary solution in https://github.com/intel/llvm/pull/9458.

**Comment by steffenlarsen** [comment]
@npmiller - Ping for awareness.

**Comment by jinz2014** [comment]
Hi @npmiller ,

I took a look and wonder the change is:

  set(PI_HIP_INCLUDE_DIR "${SYCL_BUILD_PI_HIP_ROCM_DIR}/hip/include")  =>
   set(PI_HIP_INCLUDE_DIR "${SYCL_BUILD_PI_HIP_ROCM_DIR}/include") 


Reference
/opt/rocm/hip/include/hip/hip_runtime.h
/opt/rocm/include/hip/hip_runtime.h

**Comment by npmiller** [comment]
That's right @jinz2014 , I was a bit worried about older versions of HIP but even at 4.2 they were symlinking the HIP headers into `include` so just updating is fine, I opened a PR for it: #9550

**Comment by jinz2014** [comment]
Thanks.
