### ISSUE TITLE
joint_matrix operations lose address spaces on CUDA

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#9496]
Looking at sycl/include/sycl/ext/oneapi/matrix/matrix-tensorcores.hpp it seems like the issue is that the tensorcore matrix implementation just calls `get()` on passed `multi_ptr`, which will not have address space decorations when `IsDecorated == access::decorated::no`. The solution here should be to use `sycl::detail::getDecorated` similar to in sycl/include/sycl/ext/oneapi/matrix/matrix-unified.hpp.

_See https://github.com/intel/llvm/pull/8874#discussion_r1196180582_

**Comment by JackAKirk** [comment]
I see thanks. I'll make corresponding changes to https://github.com/intel/llvm/commit/854ab7eab5e45afeae662c45b6112b08e5ec2d68 in the cuda impl.

**Comment by JackAKirk** [comment]
cuda joint_matrix doesn't lose address spaces on CUDA, so I'm closing this issue.
