### ISSUE TITLE
[SYCL][CUDA] Cannot select: intrinsic %llvm.nvvm.implicit.offset 

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#9526]
Compiling the SYCL program in https://github.com/zjin-lcf/HeCBench/tree/master/graphB%2B-sycl for an NVIDIA V100 GPU shows the following error:

fatal error: error in backend: Cannot select: intrinsic %llvm.nvvm.implicit.offset 

clang version 17.0.0 (https://github.com/intel/llvm.git 20c1857da00d99b388490f127059e0cad8717a93)

Thanks

**Comment by bader** [comment]
@jinz2014, I suppose your SYCL program is built with outdated value for -fsycl-targets option. Please, drop `-sycldevice` component from the target triple and it should fix your problem.

**Comment by jinz2014** [comment]
I found the issue is not related to the option or this specific SYCL program. When building a program with an early version of the compiler, there is no such error. Could you reproduce the issue using a recent build  ?  

Thanks

**Comment by bader** [comment]
> I found the issue is not related to the option or this specific SYCL program. When building the SYCL program with an early version of the compiler (e.g. clang version 16.0.0 [ee1ff81](https://github.com/intel/llvm/commit/ee1ff816c5ee4a331456a6a7860e93d8af122328)) , there is no such error. Could you reproduce the issue using a recent build ?
> 
> Thanks

Unfortunately, I don't have system to run the test, but you definitely use unsupported compiler option.
Please, replace "-fsycl-targets=nvptx64-nvidia-cuda-sycldevice" with "-fsycl-targets=nvptx64-nvidia-cuda" in your Makefile.

**Comment by jinz2014** [comment]
Thanks.
