### ISSUE TITLE
[SYCL][CUDA] `Cannot select: intrinsic %llvm.nvvm.implicit.offset` when building HeCBench benchmarks

### ISSUE THREAD

**Issue by callumfare** [intel/llvm#9567]
**Describe the bug**
The compiler hits a fatal error when building some SYCL benchmark applications from the HeCBench benchmark suite with the nvptx64 target.
The output from the error is:
```
fatal error: error in backend: Cannot select: intrinsic %llvm.nvvm.implicit.offset
llvm-foreach: 
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```

**To Reproduce**
Please describe the steps to reproduce the behavior:

1. Clone the [HeCBench project](https://github.com/zjin-lcf/HeCBench)
2. `cd aidw-sycl`
3. `clang++  -std=c++17 -Wall -I../aidw-cuda -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice -Xsycl-target-backend --cuda-gpu-arch=sm_60 --gcc-toolchain="" -DUSE_GPU main.cpp -o main`
4. The compilation will fail with the error mentioned above.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- Target device and vendor: Nvidia GT1030 with CUDA 12.1 (also reproduced on a setup with 12.0 and an A100)
- DPC++ version: af189270ced6d3636a04d1472f258c5ed9bb8a21
- Dependencies version: CUDA 12.1 (but will probably fail on any version)

**Comment by bader** [comment]
This is a duplicate of https://github.com/intel/llvm/issues/9526.
See this comment for the solution: https://github.com/intel/llvm/issues/9526#issuecomment-1553753761.

**Comment by callumfare** [comment]
@bader I missed that issue, thanks!
