### ISSUE TITLE
[SYCL][CUDA] build instruction for interop-experimental-single-TU-SYCL-CUDA-compilation.cpp

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#9702]
What is the command for building the file https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Plugin/interop-experimental-single-TU-SYCL-CUDA-compilation.cpp ?  

Thanks for the instruction and documentation.

**Comment by AlexeySachkov** [comment]
Tagging @aelovikov-intel here to comment. We should have a document (it may be still in progress/planned to be added) explaining what `%{build}` substitution stands for.

If I'm not mistaken, that is something simple like `clang++ -fsycl`

**Comment by jinz2014** [comment]
This program contains both SYCL and CUDA codes. I think users may encounter some link error when building the program with clang. Thank you for listing the command line.

**Comment by aelovikov-intel** [comment]
+ @intel/llvm-reviewers-cuda

**Comment by steffenlarsen** [comment]
The test was added in relation to https://github.com/intel/llvm/pull/7352. Ping @pgorlani .

**Comment by abagusetty** [comment]
The above test worked fine with a built from an old nightly - 03062023 

Build error with the commit: 8990c5503d47e397c837d991bf6bc5a0feda9b8a
```bash
abagusetty@polaris-login-04 ~ $ clang++ -std=c++17 -L/soft/compilers/cudatoolkit/cuda-11.4.4/lib64 -lcudart -lcuda -x cuda -fno-gpu-rdc -fsycl -fsycl-targets=nvptx64-nvidia-cuda sycl_cuda_interop.cpp -o sycl_cuda_interop.out
/soft/compilers/oneapi/llvm/build_cuda11.4.4_06082023/bin/llvm-link: /soft/compilers/oneapi/llvm/build_cuda11.4.4_06082023/lib/clang/17/../../clc/remangled-l64-signed_char.libspirv-nvptx64-nvidia-cuda.bc: error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM17.0.0git' Reader: 'LLVM 17.0.0git')
/soft/compilers/oneapi/llvm/build_cuda11.4.4_06082023/bin/llvm-link: error:  loading file '/soft/compilers/oneapi/llvm/build_cuda11.4.4_06082023/lib/clang/17/../../clc/remangled-l64-signed_char.libspirv-nvptx64-nvidia-cuda.bc'
clang++: error: sycl-link command failed with exit code 1 (use -v to see invocation)
```

Using `-opaque-pointers` or `-no-opaque-pointers` didn't really make a difference to the above error.

**Comment by jinz2014** [comment]
@abagusetty   Thank you for listing the command.
