### ISSUE TITLE
[SYCL][CUDA] DPC++ build warning and error related to unrolling, optimization for CUDA plugin

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#9783]
While building for the CUDA backend, I was seeing some strange warning and errors as shown below but however leading to a cleaner installation.

```bash
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
error: unknown argument: '-fno-lifetime-dse'
```
Using CUDA-11.4.4/11.8.0, gcc-11.2.0, OS SLSE 15.3,

Towards the very end when generating the bc files for spirv 

For instance
```bash
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
[ 97%] Built target opt.libspirv-nvptx64--nvidiacl.bc
[ 97%] Generating ../../lib/clc/libspirv-nvptx64--nvidiacl.bc
[ 97%] Built target prepare-libspirv-nvptx64--nvidiacl.bc
[ 97%] Generating ../../lib/clc/libclc_dummy_in.cc
[ 97%] Generating ../../lib/clc/libclc_dummy_in.cc
[ 97%] Generating ../../lib/clc/libclc_dummy_in.cc
[ 97%] Generating ../../lib/clc/libclc_dummy_in.cc
[ 97%] Generating ../../lib/clc/remangled-l64-unsigned_char.libspirv-nvptx64-nvidia-cuda.bc
[ 97%] Generating ../../lib/clc/remangled-l32-unsigned_char.libspirv-nvptx64-nvidia-cuda.bc
[ 97%] Generating ../../lib/clc/remangled-l32-signed_char.libspirv-nvptx64-nvidia-cuda.bc
[ 97%] Generating ../../lib/clc/remangled-l64-signed_char.libspirv-nvptx64-nvidia-cuda.bc
error: unknown argument: '-fno-lifetime-dse'
error: unknown argument: '-fno-lifetime-dse'
error: unknown argument: '-fno-lifetime-dse'
error: unknown argument: '-fno-lifetime-dse'
```

~~Upon compiling a test with the above built compilers leads to following errors:~~

~~.../bin/llvm-link: /soft/compilers/oneapi/llvm/build/lib/clang/17/../../clc/remangled-l64-signed_char.libspirv-nvptx64-nvidia-cuda.bc: error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM17.0.0git' Reader: 'LLVM 17.0.0git')~~
~~/soft/compilers/oneapi/llvm/build/bin/llvm-link: error:  loading file '/soft/compilers/oneapi/llvm/build/lib/clang/17/../../clc/remangled-l64-signed_char.libspirv-nvptx64-nvidia-cuda.bc'~~
~~clang++: error: sycl-link command failed with exit code 1 (use -v to see invocation)~~

**Comment by npmiller** [comment]
@jchlanda could you have a quick look at this error message: `error: unknown argument: '-fno-lifetime-dse'`, I confirmed that it comes from the `libclc-remangler` invocations, so it's most likely coming from the frontend invocation we use in there for the remangling.

**Comment by jchlanda** [comment]
> @jchlanda could you have a quick look at this error message: `error: unknown argument: '-fno-lifetime-dse'`, I confirmed that it comes from the `libclc-remangler` invocations, so it's most likely coming from the frontend invocation we use in there for the remangling.

Yeap, spotted it on Friday and added to my TODO, will report back.

**Comment by AlexeySachkov** [comment]
FYI: the error showed up once in our CI: https://github.com/intel/llvm/actions/runs/5278855878/jobs/9548777110

**Comment by jchlanda** [comment]
https://github.com/intel/llvm/pull/9974 should address the `error: unknown argument: '-fno-lifetime-dse'`. WRT the loop warning it seems to be a genuine one coming from [`WarnMissedTransforms` Pass](https://github.com/jchlanda/llvm/blob/jakub/libclc_DSE_fix/llvm/lib/Transforms/Scalar/WarnMissedTransforms.cpp#L102) that is part of our [opt run](https://github.com/jchlanda/llvm/blob/jakub/libclc_DSE_fix/libclc/cmake/modules/AddLibclc.cmake#L78). Unlikely to do with the remangler itself, maybe an incorrect use of unroll pragma in the libclc?

**Comment by jchlanda** [comment]
llvm is not able to satisfy user forced unroll, coming from:  https://github.com/jchlanda/llvm/blob/jakub/libclc_DSE_fix/libclc/ptx-nvidiacl/libspirv/group/collectives.cl#L456 will investigate a bit more.
