### ISSUE TITLE
[MacOS] Minimal support/CI pipeline for MacOS ?

### ISSUE THREAD

**Issue by matkara** [intel/llvm#982]
It is common to find scientific software/libraries developed/tested on MacOS and then deployed on Linux.
As a user, I’m looking forward for a minimal support of MacOS by the Intel sycl/clang compiler.
When compiling one of the latest versions of the sycl branch, it fails with the following error

```
In file included from /Users/matkara/Codes/sycl/llvm/sycl/source/detail/devicelib/fallback-cassert.cpp:9:
/Users/matkara/Codes/sycl/llvm/sycl/source/detail/devicelib/wrapper.h:11:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
```

This error looks similar to the ones encountered in https://github.com/intel/llvm/issues/258

Due to the lack of MacOS build in the testing pipeline of sycl, I don’t know if this error comes from my local setup of the project.
Would it be possible to add a minimal support/CI pipeline for MacOS ?

**Comment by alexbatashev** [comment]
> I don’t know if this error comes from my local setup of the project

I'm pretty sure we don't have a buildable macOS in our master. For example, #857 is also os-dependent, and it does not contain any macOS fallback. 
BTW, if you manage to build the whole thing, it would be great if you submitted a PR.
