### ISSUE TITLE
[SYCL] Use the device's platform's default context by default under Windows

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [intel/llvm#9906]
We are developing some library with functionality that depends on having SYCL queues to use the default context from the device’s platform.  As a small sample, it may be like.
```
#include <iostream>
#include <sycl/sycl.hpp>

int main(int argc, char* argv[]) {
    sycl::queue q1, q2;
    const size_t SIZE = 1024LLU;

    int *data = sycl::malloc_shared<int>(SIZE, q2);

    q1.parallel_for(SIZE, [=](sycl::id<1> idx) {
            data[idx] = idx;
    });
    q1.wait();

    std::cout << "data[333]=" << data[333] << "\n";

    free(data, q2);

     return 0;
}

```
This feature was added as [[SYCL] Add support for default contexts](https://github.com/intel/llvm/commit/315593d8453972be0662c536376d64524eed0085), but its disabled by default for Windows.

Enabling the using of default context via the environment variable from a library is far from be an elegant solution. Could it became enabled by default for Windows as it was done for Linux from the beginning?

**Comment by aelovikov-intel** [comment]
+ @cperkinsintel who, I think, was the last person looking into something related.

**Comment by AlexeySachkov** [comment]
#12599 enabled default context on Windows as well, closing the issue. @cperkinsintel: FYI
@Alexandr-Konovalov, please let us know if you encounter any other issues.
