### ISSUE TITLE
Post-commit failure for SYCL :: ESIMD/thread_id_test.cpp

### ISSUE THREAD

**Issue by dm-vodopyanov** [intel/llvm#9941]
https://github.com/intel/llvm/actions/runs/5290172225/jobs/9574401665
```
Unexpectedly Passed Tests (1):
  SYCL :: ESIMD/thread_id_test.cpp
```

It is unclear which commit caused this because we had https://github.com/intel/llvm/issues/9934 which blocked this failure, but it should be some ESIMD-related commit between https://github.com/intel/llvm/commit/405778ab831b86cc536f0ef7730545b1a73920f1 and https://github.com/intel/llvm/commit/8baa8aca04510828859274890f57a5382496e8ed

FYI, @sarnex @v-klochkov @turinevgeny

**Comment by sarnex** [comment]
I'll try to figure it out.

**Comment by v-klochkov** [comment]
> I'll try to figure it out.

GPU driver on Linux was updated/uplifted yesterday. That is why it started passing.
